### ISSUE TITLE
GNS3 Server VM overrides /etc/network/interfaces during updates

### ISSUE THREAD

**Issue by ddompe** [GNS3/gns3-server#1004]
Hi,

I know maybe this is not the right repo to fill the bug, but I couldn't find how to put a bug against the GNS3 VM.

When the GNS3 VM runs the upgrade processes to get newer versions of GNS3, it nukes the /etc/network/interfaces file, and you may have local modifications for them (like an static IP address).

**Comment by noplay** [comment]
Hi,

For the GNS3 VM you can open it here:
https://github.com/GNS3/gns3-vm

The override is normal behavior except if you turn it off:
https://github.com/GNS3/gns3-vm/blob/master/config/interfaces#L9
