### ISSUE TITLE
Frame-Relay Switch

### ISSUE THREAD

**Issue by mad-bison** [GNS3/gns3-server#1005]
Using GNS3 v2.0 Upgraded today.
Using GNS3 VM v0.10.14 upgraded today.

Using the topology below (this is a screenshot from when it was working)
![screenshot](https://cloud.githubusercontent.com/assets/28378590/25689274/f47e3e02-30c9-11e7-897e-5856c63596b5.png)

This was a v1.5.4 topology/project that was upgraded into v2.0.

It failed to open when trying to create the Frame relay switch.
`=> Dynamips error when running command 'frsw create_vc "FR1" udp-a5c9ecf2-5ce2-4a50-9ab6-c982819612da 304 udp-0d899d28-29c4-41ce-b048-3886ced71493 403
': unable to create VC`

I edited the config file and removed all FR commands, and then opened the project successfully.

I added the FR switch back into the project and attempted to re-create the links. The Frame-Relay mapping commands work successfully, but after two links are added, no more can be "plugged in".

I have tried adding the links individually, to no change.
I have tried adding the frame relay switch both on the local host, and the GNS3VM to no change.

Errors with 

```
Error while creating link: Dynamips error when running command 'frsw create_vc "FR1" udp-c7b9805a-a21c-410c-b98d-ca9a098971c7 304 udp-df030228-95c7-4c7a-a800-71fb8e33b914 403
': unable to create VC
Error while creating link: Dynamips error when running command 'frsw create_vc "FR1" udp-c7b9805a-a21c-410c-b98d-ca9a098971c7 304 udp-df030228-95c7-4c7a-a800-71fb8e33b914 403
': unable to create VC
Error while creating link: Port 1 isn't free
Error while creating link: Port 2 isn't free
```
![gns3_issue](https://cloud.githubusercontent.com/assets/28378590/25689484/c76f20b4-30cb-11e7-99c6-00b0c7c8dbb4.png)

I just tested with a new project, and IOS image c3745-adventerprisek.124-25d.image and I was still unable to add more than 2 links to the Frame Relay Switch.

If you want me to export the project for you, just let me know. Also, wasn't sure if this is a gui/server bug, so I filed it here. Please move as necessary.

Thanks

**Comment by noplay** [comment]
Hi,

Could you send the project to developers@gns3.net?

Thanks a lot

**Comment by mad-bison** [comment]
Sent.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/87d42f4eb9fa8770071b5eae5abc97a1dbc38bee
