### ISSUE TITLE
Export is looking for images in the IOS directory instead of Qemu

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#1010]
https://gns3.com/qa/gns3-2-0-0-rc3-unable-to-export-

**Comment by noplay** [comment]
I'm not able to reproduce the problem. Probably a bug related to https://github.com/GNS3/gns3-gui/issues/2008

**Comment by noplay** [comment]
I think it's fixe could you confirm jeremy?

**Comment by grossmj** [comment]
Confirmed.
