### ISSUE TITLE
Wic numbering error on 3745 and 3725

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#1011]
https://gns3.com/qa/gns3-2-0-3725-3745-wics-numberin

![image](https://cloud.githubusercontent.com/assets/345437/25897312/dc60a518-3587-11e7-951a-44460c001fc6.png)

![image](https://cloud.githubusercontent.com/assets/345437/25897318/e0299038-3587-11e7-83bc-f0ad1dc3915e.png)

**Comment by noplay** [comment]
What should be the correct value?

**Comment by grossmj** [comment]
Bug confirmed, this is a regression since it works in 1.5

**Comment by grossmj** [comment]
> What should be the correct value?

With a WIC-2T in every WIC slot you should see the following:

```
Serial0/0
Serial0/1
Serial0/2
Serial0/3
Serial0/4
Serial0/5
```

**Comment by noplay** [comment]
Ok the +16 for dynamips slot is internal to dynamips we should not display
it to the users
