### ISSUE TITLE
[2.0] small GNS3 topologies hogs lots of memory

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1016]
An opened GNS3 project (made of only containers) takes more and more memory if leaved untouched in the background:

![selection_999 029](https://cloud.githubusercontent.com/assets/1716020/25768941/561b980e-320e-11e7-9fb8-4ef639a471f3.png)

After closing the project, ~ 4GB is freed, that's huge for a couple of containers!

![selection_999 030](https://cloud.githubusercontent.com/assets/1716020/25768961/007eab88-320f-11e7-8bba-5f1cbf5af275.png)

**Comment by noplay** [comment]
Can you reopen the issue on the gns3-gui repository? The binary gns3 is for the gui not the server.  Thanks

**Comment by AJNOURI** [comment]
done.
