### ISSUE TITLE
gns3server does not start

### ISSUE THREAD

**Issue by melvincv** [GNS3/gns3-server#1021]
GNS3 2.0 does not start as the local server does not start.
I used the Ubuntu repository: ppa:gns3/ppa

melvin@melvinz-laptop ~ $ **cat /etc/lsb-release** 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"

melvin@melvinz-laptop ~ $ **gns3server**
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/pkg_resources.py", line 2716, in <module>
    working_set.require(__requires__)
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/pkg_resources.py", line 685, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: typing

**Comment by noplay** [comment]
What is the result of the command:
```
apt-cache show gns3-server

**Comment by noplay** [comment]
Andrew confirmed the issue on mint 17.3 but not on mint 18

![rosa - apt-cache search](https://cloud.githubusercontent.com/assets/345437/25850563/1e633ef0-34c3-11e7-8adc-75a8cdf200ba.png)

**Comment by noplay** [comment]
I'm not able to publish the fix until publication because pushing the change will trigger a build of GNS3 on all version of the distribution bringing untested stuff. We will need to wait publication if 2.0.1 to release fix.
