### ISSUE TITLE
Drop SSL support 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#1022]
Discussed with jeremy

The way we have implemented SSL protect only the communication between client and server, but not the access to the console. The only recommended way to protect GNS3 is a VPN.

Also often users use self signed certificate which doesn't protect against man of the middle.

Finally the SSL support is rarely use but create complex issue like OpenSSL version mismatch on user computers.

**Comment by noplay** [comment]
Additional note, this part of code is not correctly audited we are not sure it's secure.

**Comment by CapnCheapo** [comment]
I think the feature probably appealed mostly to corporate users, many of which have a requirement that all authentication traffic is encrypted.  Although we have that requirement, the VPN solution will be fine, just a little more work :)

**Comment by noplay** [comment]
I think it's better to advertise the most secure solution.
