### ISSUE TITLE
Poor error message, when docker version is too old

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1033]
https://www.gns3.com/qa/docker-with-gns3-2-in-ubuntu-17-

If a linux user has installed a docker version, that is too old (api version < 1.25) the following error message is shown:
docker container 400 client is newer than server (client api version: 1.25, server api version: 1.24)

For this situation the error message in _check_connection (compute/docker/\_\_init\_\_.py) was made. But this doesn't work as self.query("GET", "version") itself needs at least the DOCKER_MINIMUM_API_VERSION to run.

**Comment by ehlers** [comment]
That's how I solved that in v1.5:
use API of docker v1.0 for version query: https://github.com/ehlers/gns3-server/commit/de2b5a9c6b15bf90b5792d63373111ad90622879
replace API version by docker version: https://github.com/ehlers/gns3-server/commit/38e690fc947eb9ca3ba1450e21e60c162e367b37

**Comment by noplay** [comment]
Thanks a lot commit have been merged to 2.0
