### ISSUE TITLE
Can't add a VOLUME to docker image by "docker commit"

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1039]
When I add a VOLUME definition to a docker image by `docker commit` this additional volume is not saved by GNS3 (both v1.5 and v2.0).

When creating a docker image with `docker build` the Volumes definition is both added to the ContainerConfig and to the Config hierarchy of the docker image information. When creating an image with `docker commit --change='VOLUME "additional-directory"'`, the updated volume definition is only stored in the Config hierarchy, the ContainerConfig remains untouched.

GNS3 uses the definition in ContainerConfig, see https://github.com/GNS3/gns3-server/blob/2.0/gns3server/compute/docker/docker_vm.py#L216, but after reading some documentation I have the impression, that using the Config hierarchy is the correct way. After changing `image_infos.get("ContainerConfig", {}).get("Volumes")`to `image_infos.get("Config", {}).get("Volumes")` the VOLUME configuration of "docker commit" is now working.

**Comment by noplay** [comment]
I merged your commit. Thanks a lot
