### ISSUE TITLE
Inconsistency with project directory names

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-server#1040]
2.0.1

A standard project is created and a directory with a name of the uid is created for the project. If you duplicate the project, the directory gets created with the project name.  They should probably be one or the other.  My vote is to move to directory name matching the project.  It makes things a lot easier when you have 200 projects to sort through!

The first directory here is the original 4router_box project.  4router_box_ospf is a duplicate of that project.  

drwxrwxr-x 3 gns3 gns3 4096 May 18 13:24 98b4a1fa-0323-4aff-9572-ce429514dd60
drwxrwxr-x 3 gns3 gns3 4096 May 18 13:24 4router_box_ospf

**Comment by noplay** [comment]
It's with a remote server right?

**Comment by CapnCheapo** [comment]
Correct.

**Comment by noplay** [comment]
It should be the UUID, the name should be ignored because on remote server you should not directly interact with the filesystem. We choose to use UUID to avoid conflicts in some corner case in environnement with multiple users.
