### ISSUE TITLE
Integrate Qemu with HAXM on windows

### ISSUE THREAD

**Issue by rcprior** [GNS3/gns3-server#1048]
Running x86 appliances on Windows is painfully slow compared to Linux, due to use of processor emulation instead of running native (hypervisor). Recent versions of Qemu support Intel HAXM, developed to dramatically improve speed of Android (Intel platforms), similarly to qemu-kvm on Linux.
Is there any chance of integrating qemu with HAXM support into GNS3 for windows?

**Comment by noplay** [comment]
It seem you can use this binaries: https://qemu.weilnetz.de/w64/ It's unclear what is the status of HAXML, it seem made only for running Android and not all operation system.

But we recommend using the GNS3 VM with VMware, this allow nested virtualization and the usage of KVM. This is the solution tested by manufacturers when they make their images.
