### ISSUE TITLE
[Feature proposal] API Create Project call should create the project folder with the name of the project instead of its ID

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#1051]
@grossmj 
It would be more human-friendly to use the name of the project as the folder name instead of its ID, so that a human can easily:
- find it.
- send API calls without searching for the corresponding ID

**Comment by jean-christophe-manciot** [comment]
Same proposal regarding nodes.

**Comment by noplay** [comment]
For project if it's not remote you can choose the location using the path
parameter.
http://api.gns3.net/en/latest/api/v2/controller/project/projects.html

For node this is not possible, it's a design decisions to solve multiple
problems.

I  just made a documentation why we use UUID:
http://docs.gns3.com/12Kjb9yXIe8P0UR2YEBjTCQJPXIZqQXeaY4YaBiSgZSA/index.html

It's really important to not try to interact with project directory outside
GNS3. We know it's a common in the community to do that, but it's a source
of bugs.
