### ISSUE TITLE
gns3server fails with newer aiohttp

### ISSUE THREAD

**Issue by fcolista** [GNS3/gns3-server#1054]
Hi folks.
Yes, in the requirements it's stated:

```
aiohttp>=1.3.5,<=1.4.0 # pyup: ignore
aiohttp-cors==0.5.1 # pyup: ignore
```
But we have a newer aiohttp in the repositories, which is 2.0.7, and aiohttp-cors is 0.5.3.
Python is v.3.6, the distribution is Alpine Linux v3.6 (and edge, which is the newer and unstable)

According with this issue: https://github.com/aio-libs/aiohttp/issues/1753

they dropped the compatibility with aiohttp.errors, and this is where aiohttp.errors appear:

```
gns3server/compute/docker/__init__.py:            except (aiohttp.errors.ClientOSError, FileNotFoundError):
gns3server/compute/docker/__init__.py:            except (aiohttp.errors.ClientOSError, FileNotFoundError):
gns3server/compute/docker/__init__.py:            except aiohttp.errors.ServerDisconnectedError:
gns3server/handlers/api/compute/notification_handler.py:import aiohttp.errors
gns3server/handlers/api/compute/notification_handler.py:    except aiohttp.errors.WSServerHandshakeError:
gns3server/handlers/api/controller/project_handler.py:import aiohttp.errors
gns3server/handlers/api/controller/project_handler.py:    except aiohttp.errors.WSServerHandshakeError:
gns3server/controller/node.py:        except (ComputeError, aiohttp.errors.ClientHttpProcessingError, aiohttp.web.HTTPError):
gns3server/controller/gns3vm/virtualbox_gns3_vm.py:            except (OSError, aiohttp.errors.ClientHttpProcessingError, TimeoutError, asyncio.TimeoutError):
gns3server/controller/compute.py:        except (aiohttp.errors.WSServerHandshakeError, aiohttp.errors.ClientResponseError):
gns3server/controller/compute.py:            except aiohttp.errors.WSServerHandshakeError:
gns3server/controller/compute.py:        except (aiohttp.errors.ClientOSError, aiohttp.errors.ClientRequestError, aiohttp.errors.ServerDisconnectedError, aiohttp.ClientResponseError, ValueError) as e:
gns3server/controller/compute.py:        except aiohttp.errors.DisconnectedError:
scripts/random_query.py:            except (ValueError, aiohttp.errors.ServerDisconnectedError):
```

Would it be possible to have gns3 working with newer aiohttp package, perhaps by using the workaround 

```
try:
    yield from aiohttp.request()
except aiohttp.ClientError as err:
    print(err)
```

Thanks for this great software.
.: Francesco Colista
.:Alpine Linux Infra

**Comment by noplay** [comment]
Their is more deep changes require:
https://github.com/GNS3/gns3-server/issues/1000

We start to work on it, it's not yet working fine, we still get bug and discuss with aiohttp folks to see if it's on our side or not. Actually Docker support is broken and their is incompatibilities with Qt.

I know that's a problem for you because our release cycle are not sync. Not sure what we can do to make it work again with alpine

**Comment by noplay** [comment]
GNS3 2.1 will ship with aiohttp 2.2 support
