### ISSUE TITLE
Can't find vmware Shared VMs

### ISSUE THREAD

**Issue by Saki0** [GNS3/gns3-server#1064]
Hello,

I've got an issue where my vmware List on GNS3 is empty even if I have 4 VMs. 
I've tried to make a sym link like $HOME/vmware to /var/lib/vmware/Share Vms/ but list stay empty.

I have no idea how to solve it

**Comment by noplay** [comment]
It's probably because VMware and GNS3 doesn't run as the same user.

**Comment by Saki0** [comment]
Indeed Vmware Workstation server was running as root and gns3server not.
I found out that the manual launch of gns3server as root solve the vm list problem (with a sym link to Shared Vms) but the daemon (modified for root) have empty vm list

**Comment by noplay** [comment]
That's strange VMware is not suppose to run as root

**Comment by Saki0** [comment]
Exact, I will try to fix that later

**Comment by noplay** [comment]
Thanks for all the feedback
