### ISSUE TITLE
Specific remote project doesn't open after upgrade to 2.0.2

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-server#1072]
After upgrading to 2.0.2 we are having a problem opening a project that we use frequently.  Following is the error:  

Bad request http://10.127.49.58:3080/v2/compute/projects/dfa192b8-f8bf-452b-ae1b-2bf1255e3963

/qemu/nodes {
    "message": "None is not of type 'integer'\n\nFailed validating 'type' in schema['properties']['console']:\n    {'description': 'Console TCP port',\n     'maximum': 65535,\n     'minimum': 1,\n     'type': 'integer'}\n\nOn instance['console']:\n    None",
    "method": "POST",
    "path": "/v2/compute/projects/{project_id}/qemu/nodes",
    "request": {
        "acpi_shutdown": false,
        "adapter_type": "e1000",
        "adapters": 16,
        "bios_image": "",
        "boot_priority": "c",
        "cdrom_image": "",
        "cpu_throttling": 0,
        "cpus": 1,
        "hda_disk_image": "IOSv-L2-152-4.0.55.E.qcow2",
        "hda_disk_image_md5sum": "1a3a21f5697cae64bb930895b986d71e",
        "hda_disk_interface": "virtio",
        "hdb_disk_image": "IOSv_startup_config.img",
        "hdb_disk_image_md5sum": "bc605651c4688276f81fd59dcf5cc786",
        "hdb_disk_interface": "virtio",
        "hdc_disk_image": "",
        "hdc_disk_interface": "ide",
        "hdd_disk_image": "",
        "hdd_disk_interface": "ide",
        "initrd": "",
        "kernel_command_line": "",
        "kernel_image": "",
        "legacy_networking": false,
        "linked_clone": true,
        "mac_address": "00:39:63:62:ff:00",
        "options": "-nographic",
        "process_priority": "normal",
        "ram": 768,
        "usage": ""
    },
    "status": 400
}

Sometimes the GUI crashes after displaying this error.  

Project file is attached.

[remote-quemu-nat-test.gns3.txt](https://github.com/GNS3/gns3-server/files/1064169/remote-quemu-nat-test.gns3.txt)

**Comment by noplay** [comment]
Do you still have the issue with 2.0.3?

Thanks

**Comment by CapnCheapo** [comment]
2.0.3 fixed it.  Thanks Julien!
