### ISSUE TITLE
I am able to upload pdf files in "/upload" which also gets stored in database

### ISSUE THREAD

**Issue by aka001** [GNS3/gns3-server#108]
Is this the expected behaviour? We can perform a check on the image format in upload_handler.py before storing them in database.

**Comment by noplay** [comment]
Yeah we are not checking. The porblem is we need to implement a correct check for each file type.  I don't know if it's easy for Qemu.

**Comment by aka001** [comment]
I think we can perform this check in upload_handler.py. Firstly we can find which attribute of data gives the file name, then check for it's extension being in "jpg, png, tif, etc". If it's not in the set then the file format is not correct.

**Comment by aka001** [comment]
@noplay I have created a pull request. The feature works for me. Kindly review it.
https://github.com/GNS3/gns3-server/pull/109
