### ISSUE TITLE
Cannot start telnet QEMU console - port mismatch

### ISSUE THREAD

**Issue by jluk-codi** [GNS3/gns3-server#1082]
The GNS3 GUI (version 2.0.3 from PyPi) cannot open a telnet console to a running QEMU VM. It tries to use a port number that is lower by one than the real port.

In ps aux I can see the qemu command parameters:
`-serial telnet:127.0.0.1:5001,server,nowait`
And in GNS3 GUI log this message:
`2017-06-21 19:13:35 INFO telnet_console:88 Telnet console 127.0.0.1:5000 closed`

When inspecting the console window, the telnet command exits with "connection refused".
Next new VM is created with port 5003 and the GUI tries to connect to port 5002, so the telnet console is unusable in the whole project.

I tracked the issue down to the gns3-server BaseNode class. When creating a QEMU VM node, it first reserves the console port stored in the _console parameter:
https://github.com/GNS3/gns3-server/blob/e7853a1be960539d30324c4ee6c117fa114ad4e2/gns3server/compute/base_node.py#L88

So in case of port range starting from 5000, the first port (5000) is reserved in the port manager.

Then there is another allocation for the _internal_console_port:
https://github.com/GNS3/gns3-server/blob/e7853a1be960539d30324c4ee6c117fa114ad4e2/gns3server/compute/base_node.py#L102
which results in port 5001 being allocated.

And then finally the QemuVM child class uses the _internal_console_port for the qemu commandline creation:
https://github.com/GNS3/gns3-server/blob/e74e66b20363766c60cd46e044005a06cb340393/gns3server/compute/qemu/qemu_vm.py#L1295

I guess that the GUI gets the value of _console and this is the cause of the mismatch.

**Comment by noplay** [comment]
The port mismatch is normal. We wrap the qemu telnet with our own telnet proxy. Do you have the issue with all your qemu images?

**Comment by jluk-codi** [comment]
Ok, I don't know what has changed, but the gns3server started listening on the _internal_console_port. You can remove this issue.
