### ISSUE TITLE
Support for IOU 64 bit image

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#1085]
https://gns3.com/qa/x64-l3-adventerprise-154-2-s-is-

**Comment by noplay** [comment]
I think we just need to check the header to allow 64 bit binary. But I don't have access to this image in order to test

**Comment by grossmj** [comment]
It is just a matter to check for 64-bit in the ELF header there: https://github.com/GNS3/gns3-server/blob/e74e66b20363766c60cd46e044005a06cb340393/gns3server/compute/iou/iou_vm.py#L186

**Comment by grossmj** [comment]
I patched the ELF check https://github.com/GNS3/gns3-server/commit/1e371016413dc1512f2549c32e0130b8e298dd1b

However, still a problem to run the image in GNS3 (not an executable error...)

**Comment by grossmj** [comment]
Running a 64-bit image works however I have detected another problem: https://github.com/GNS3/gns3-gui/issues/2125
