### ISSUE TITLE
GNS3 v2 server fails with "ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by zxyz** [GNS3/gns3-server#1090]
VM with Ubuntu 16.04 with GNS3 ppa running most recent GNS3 2.0.3-xenial1

> 2017-06-26 16:00:28 ERROR local_server:489 Local server process has stopped
> 2017-06-26 16:00:28 ERROR local_server:491 Traceback (most recent call last):
>   File "/usr/bin/gns3server", line 11, in <module>
>     sys.exit(main())
>   File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/main.py", line 79, in main
>     run()
>   File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/run.py", line 207, in run
>     pid_lock(args.pid)
>   File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/run.py", line 163, in pid_lock
>     pid = int(f.read())
> ValueError: invalid literal for int() with base 10: ''

plain installation just for running GNS3, GNS3 2.0.2 worked without problem

Thanks for GNS3!

**Comment by noplay** [comment]
What do you have in the pid file in ~/.config/GNS3/

**Comment by zxyz** [comment]
The PID file of the gns3-server under `~/.config/GNS3/` was empty.
I renamed `~/.config/GNS3/` to give it a fresh start and now the server starts up without the above mentioned error. So for me the issue is solved. @noplay Thanks for pointing me in the right direction!
Unsure if I should let the issue open, up to you to decide.

**Comment by noplay** [comment]
Thanks for the report we will make sure to handle this.
