### ISSUE TITLE
[ 2.0.3 ] Segmentation fault: when bulk deleting > 12 routers, 

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1094]
In my machine it is consistent, when I delete at once  

- < 12 routers ==>OK

> 2017-06-29 14:55:57 INFO node:276 Node instance IOSv-l3-15.4(2)T1-22 has been created
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-10 is being deleted
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-4 is being deleted
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-6 is being deleted
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-8 is being deleted
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-2 is being deleted
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-1 is being deleted
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-9 is being deleted
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-5 is being deleted
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-3 is being deleted
> 2017-06-29 14:56:03 INFO node:399 IOSv-l3-15.4(2)T1-7 is being deleted

- \> 12 routers ==> GNS3 exits with **segmentation fault**

> 2017-06-29 14:51:03 INFO node:399 gns3-openvswitch-8 is being deleted
> 2017-06-29 14:51:03 INFO node:399 CiscoIOSv15.6(2)T-2 is being deleted
> 2017-06-29 14:51:03 INFO node:399 IOSv-l3-15.4(2)T1-2 is being deleted
> 2017-06-29 14:51:03 INFO node:399 IOU11 is being deleted
> 2017-06-29 14:51:03 INFO node:399 gns3-openvswitch-2 is being deleted
> 2017-06-29 14:51:03 INFO node:399 gns3-openvswitch-10 is being deleted
> 2017-06-29 14:51:03 INFO node:399 IOU13 is being deleted
> 2017-06-29 14:51:03 INFO node:399 IOU2 is being deleted
> 2017-06-29 14:51:03 INFO node:399 IOSv-l3-15.4(2)T1-1 is being deleted
> 2017-06-29 14:51:03 INFO node:418 CiscoIOSv15.6(2)T-2 has been deleted
> 2017-06-29 14:51:06 INFO node:418 IOSv-l3-15.4(2)T1-2 has been deleted
> 2017-06-29 14:51:06 INFO node:418 IOU11 has been deleted
> Segmentation fault
>

**Comment by noplay** [comment]
Do you have more details if you start with --debug?

**Comment by AJNOURI** [comment]
Sorry, now, whatever I do, cannot reproduce it :-| 
Maybe a temporary system conditions leading to this behavior.
I'll close this issue, and get back to you if reappears.
