### ISSUE TITLE
Docker mount directory may not exist

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1097]
Docker ensures, that the directories, you define with the VOLUME command in the Dockerfile exist. But directories, that are additionally mounted by GNS3 may not exist in the docker image. Mounting them in the GNS3 injected startup script /gns3/init.sh will then fail. Currently only the /etc/network directory is additionally injected by GNS3, but in future we might see additional volumes, that get added by GNS3.

Normally the /etc/network directory exists, but the new slim debian images are that trimmed down, that they don't have this directory. For example using debian:stretch-slim triggers this issue.

My solution is, to create the mount directory in /gns3/init.sh, see https://github.com/ehlers/gns3-server/commit/f6be6d4ffabbd4f91ea9757ed19b621fdc8d2eee

**Comment by noplay** [comment]
Thanks it's merged
