### ISSUE TITLE
Don't allow user to overwrite GNS3 docker environment variables

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1098]
Currently the user is able to overwrite GNS3 docker environment variables. The user can set GNS3_MAX_ETHERNET or GNS3_VOLUMES with it's own values in the environment section of the Docker VM settings. As the user supplied environment variables are applied later as the predefined ones, they have precedence. That way the user can create issues.

My suggestion is to add the user defined variables first, so the GNS3 defined variables can overwrite them, see https://github.com/ehlers/gns3-server/commit/93d3013132ad48f154406520b92432cd31a18998

**Comment by noplay** [comment]
I have made different implementation. I prevent user to use environnement variable starting with GNS3_ I hope to not break a user topology. But it's more futur proof.
