### ISSUE TITLE
Drop use_ubridge flag 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#1115]
We have a flag use_ubridge that allow to disable ubridge.

It's add complexity in the code in order to support with and without. And we don't test without ubridge. Some feature like ipv6, packet capture and packet filter work only with ubridge. Their is today no reason for disabling ubridge. 

I propose to simplify and always consider that ubridge is enable.

**Comment by grossmj** [comment]
Yes we can probably drop it now.

**Comment by noplay** [comment]
I think it's good thing we remove it. I just discover we don't test qemu with ubridge enable and the test fail
