### ISSUE TITLE
[ 2.1.0dev2 ] canot open existing projects only create new ones: Error transferring http://7BT...cbl@192.168.0.146:8000/v2/projects/load - server replied: Forbidden

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1151]
Can open ONLY new projects, any other existing project gives the following:

> Error transferring http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/load - server replied: Forbidden

![selection_0157](https://user-images.githubusercontent.com/1716020/28757632-578eff7a-7587-11e7-9027-86ea9bb761f5.png)

New projects appear to work fine:

![selection_0158](https://user-images.githubusercontent.com/1716020/28757618-0baa420e-7587-11e7-9385-bd42ef95c705.png)

The same project cannot be opened after being closed:

**Debug info.**

```
2017-07-31 00:25:04 CRITICAL topology.py:222 Error transferring http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/load - server replied: Forbidden
Stack (most recent call last):
  File "/usr/local/bin/gns3", line 11, in <module>
    load_entry_point('gns3-gui===2.1.0dev2-5857d37', 'gui_scripts', 'gns3')()
  File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/main.py", line 289, in main
    exit_code = app.exec_()
  File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/qt/__init__.py", line 270, in partial
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/http_client.py", line 640, in _processError
    callback({"message": error_message}, error=True, server=server, context=context)
  File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/qt/__init__.py", line 270, in partial
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/project.py", line 447, in _projectOpenCallback
    self.project_creation_error_signal.emit(result["message"])
  File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/topology.py", line 222, in _projectCreationErrorSlot
    QtWidgets.QMessageBox.critical(self._main_window, "New project", message)
  File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/qt/__init__.py", line 115, in critical
    LogQMessageBox._get_logger().critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
```

**Comment by noplay** [comment]
Can you check if permission are correct?  I think we fixed a bug in 2.1.0alpha2 regarding docker permissions

**Comment by AJNOURI** [comment]
Do you mean ownership of the projects?

**Comment by noplay** [comment]
Permissions on all files

**Comment by AJNOURI** [comment]
What should I look for? 
Found files belonging to: 

> $USER
> root
> 999 (docker group id)??

and all sort of permissions:

> -rw------- 
> -rw-r----- 
> -rw-r--r-- 
> -rw-rw-r-- 
> -rw-rw-rw- 
> -rwx------ 
> -rwxrwxrwx 
> -rwxr-xr-x
>

**Comment by noplay** [comment]
That the problem. Due to a bug (typing exit in the shell) you can corrupt the permission. You need to fix the permission of the files in order to restore the owner as you.

I was wrong the fix will not be in alpha 2

**Comment by AJNOURI** [comment]
Changed the ownership of everything in GNS3 (after backing it up)
`sudo chown -R user:group`
Still the same issue.
Started the server and gui with sudo and the same behavior.

**Comment by noplay** [comment]
Can you start the server with --debug and share the log?

**Comment by AJNOURI** [comment]
Above is the gui (gns3 --debug) log.
gns3server --debug doesn't show any errors

**gns3 shows:**

> 2017-07-31 19:31:45 CRITICAL topology.py:222 Error transferring http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/load - server replied: Forbidden
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 11, in <module>
>     load_entry_point('gns3-gui===2.1.0dev2-5857d37', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/main.py", line 289, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/qt/__init__.py", line 270, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/http_client.py", line 640, in _processError
>     callback({"message": error_message}, error=True, server=server, context=context)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/qt/__init__.py", line 270, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/project.py", line 447, in _projectOpenCallback
>     self.project_creation_error_signal.emit(result["message"])
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/topology.py", line 222, in _projectCreationErrorSlot
>     QtWidgets.QMessageBox.critical(self._main_window, "New project", message)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/qt/__init__.py", line 115, in critical
>     LogQMessageBox._get_logger().critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> 

**Meanwhile the server:**

> 2017-07-31 19:32:04 INFO response.py:56 GET /v2/computes
> 2017-07-31 19:32:04 DEBUG response.py:57 {'Authorization': 'Basic N0JURUk5bjV6bDVVeVBqUGhpT3lzTGROeGJMM3NwN3Y3UVFPSDhxREc0eFBIQWJ2QXFTelJ4dDhMUzRuMGNibDpybkZZYnlmbW1mRFR1c0hHbndrU0kzeGNtUHBuaXc3bTNEdlFGMDNLa1cyV3BzNEU4YlM5cEdINlllVzVvTWJh', 'User-Agent': 'GNS3 QT Client v2.1.0dev2', 'Content-Type': 'application/json', 'Content-Length': '2', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-GB,*', 'Host': '192.168.0.146:8000'}
> 2017-07-31 19:32:04 DEBUG response.py:59 {}
> 2017-07-31 19:32:04 INFO response.py:60 Response: 200 OK
> 2017-07-31 19:32:04 DEBUG response.py:61 {'Connection': 'close', 'X-Route': '/v2/computes', 'Server': 'Python/3.6 GNS3/2.1.0dev2', 'Content-Type': 'application/json'}
> 2017-07-31 19:32:04 DEBUG response.py:63 [{'capabilities': {'node_types': ['cloud', 'ethernet_hub', 'ethernet_switch', 'nat', 'vpcs', 'virtualbox', 'dynamips', 'frame_relay_switch', 'atm_switch', 'qemu', 'vmware', 'docker', 'iou'], 'platform': 'linux', 'version': '2.1.0dev2'}, 'compute_id': 'local', 'connected': True, 'cpu_usage_percent': 9.0, 'host': '192.168.0.146', 'memory_usage_percent': 63.2, 'name': 'gns3-iouvm', 'port': 8000, 'protocol': 'http', 'user': '7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl'}]
> 2017-07-31 19:32:04 INFO helpers.py:498 192.168.0.146 - - [31/Jul/2017:17:32:04 +0000] "GET /v2/computes HTTP/1.1" 200 1038 "-" "GNS3 QT Client v2.1.0dev2"
> 2017-07-31 19:32:07 INFO response.py:56 GET /v2/settings

**Comment by noplay** [comment]
You don't have more logs on server? I don't see the 403 error.

Can you try to create a project with last code of the 2.1 branch.

**Comment by AJNOURI** [comment]
Only the gui fires errors, not the server, here is debug from each of them during the same timestamps:

installed the latest 2.1 branch code:
- gns3-gui===2.1.0dev2-5857d37
- gns3-server===2.1.0dev3-8a028a6

# **gns3 gui:**

> 2017-08-01 12:16:38 DEBUG http_client:614 Response error: Error transferring http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/load - server replied: Forbidden for http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/load (error: 202)
> 2017-08-01 12:16:38 CRITICAL topology.py:222 Error transferring http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/load - server replied: Forbidden
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 11, in <module>
>     load_entry_point('gns3-gui===2.1.0dev2-5857d37', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/main.py", line 289, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/qt/__init__.py", line 270, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/http_client.py", line 640, in _processError
>     callback({"message": error_message}, error=True, server=server, context=context)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/qt/__init__.py", line 270, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/project.py", line 447, in _projectOpenCallback
>     self.project_creation_error_signal.emit(result["message"])
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/topology.py", line 222, in _projectCreationErrorSlot
>     QtWidgets.QMessageBox.critical(self._main_window, "New project", message)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev2_5857d37-py3.6.egg/gns3/qt/__init__.py", line 115, in critical
>     LogQMessageBox._get_logger().critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> 

# **GNS3 server**

> 2017-08-01 12:16:38 INFO response.py:56 POST /v2/projects/load
> 2017-08-01 12:16:38 DEBUG response.py:57 {'Authorization': 'Basic N0JURUk5bjV6bDVVeVBqUGhpT3lzTGROeGJMM3NwN3Y3UVFPSDhxREc0eFBIQWJ2QXFTelJ4dDhMUzRuMGNibDpybkZZYnlmbW1mRFR1c0hHbndrU0kzeGNtUHBuaXc3bTNEdlFGMDNLa1cyV3BzNEU4YlM5cEdINlllVzVvTWJh', 'User-Agent': 'GNS3 QT Client v2.1.0dev2', 'Content-Type': 'application/json', 'Content-Length': '50', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-GB,*', 'Host': '192.168.0.146:8000'}
> 2017-08-01 12:16:38 DEBUG response.py:59 {'path': '/home/ajn/GNS3/projects/new4/new4.gns3'}
> 2017-08-01 12:16:38 INFO response.py:60 Response: 403 Forbidden
> 2017-08-01 12:16:38 DEBUG response.py:61 {'Connection': 'close', 'X-Route': '/v2/projects/load', 'Server': 'Python/3.6 GNS3/2.1.0dev3'}
> 2017-08-01 12:16:38 INFO helpers.py:498 192.168.0.146 - - [01/Aug/2017:10:16:38 +0000] "POST /v2/projects/load HTTP/1.1" 403 204 "-" "GNS3 QT Client v2.1.0dev2"
> 2017-08-01 12:16:39 INFO response.py:56 GET /v2/computes
> 2017-08-01 12:16:39 DEBUG response.py:57 {'Authorization': 'Basic N0JURUk5bjV6bDVVeVBqUGhpT3lzTGROeGJMM3NwN3Y3UVFPSDhxREc0eFBIQWJ2QXFTelJ4dDhMUzRuMGNibDpybkZZYnlmbW1mRFR1c0hHbndrU0kzeGNtUHBuaXc3bTNEdlFGMDNLa1cyV3BzNEU4YlM5cEdINlllVzVvTWJh', 'User-Agent': 'GNS3 QT Client v2.1.0dev2', 'Content-Type': 'application/json', 'Content-Length': '2', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-GB,*', 'Host': '192.168.0.146:8000'}
> 2017-08-01 12:16:39 DEBUG response.py:59 {}
> 2017-08-01 12:16:39 INFO response.py:60 Response: 200 OK
> 2017-08-01 12:16:39 DEBUG response.py:61 {'Connection': 'close', 'X-Route': '/v2/computes', 'Server': 'Python/3.6 GNS3/2.1.0dev3', 'Content-Type': 'application/json'}
> 2017-08-01 12:16:39 DEBUG response.py:63 [{'capabilities': {'node_types': ['cloud', 'ethernet_hub', 'ethernet_switch', 'nat', 'vpcs', 'virtualbox', 'dynamips', 'frame_relay_switch', 'atm_switch', 'qemu', 'vmware', 'docker', 'iou'], 'platform': 'linux', 'version': '2.1.0dev3'}, 'compute_id': 'local', 'connected': True, 'cpu_usage_percent': 21.8, 'host': '192.168.0.146', 'memory_usage_percent': 80.4, 'name': 'gns3-iouvm', 'port': 8000, 'protocol': 'http', 'user': '7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl'}]
> 2017-08-01 12:16:39 INFO helpers.py:498 192.168.0.146 - - [01/Aug/2017:10:16:39 +0000] "GET /v2/computes HTTP/1.1" 200 1039 "-" "GNS3 QT Client v2.1.0dev2"
> 2017-08-01 12:16:40 INFO response.py:56 GET /v2/settings
> 2017-08-01 12:16:40 DEBUG response.py:57 {'Authorization': 'Basic N0JURUk5bjV6bDVVeVBqUGhpT3lzTGROeGJMM3NwN3Y3UVFPSDhxREc0eFBIQWJ2QXFTelJ4dDhMUzRuMGNibDpybkZZYnlmbW1mRFR1c0hHbndrU0kzeGNtUHBuaXc3bTNEdlFGMDNLa1cyV3BzNEU4YlM5cEdINlllVzVvTWJh', 'User-Agent': 'GNS3 QT Client v2.1.0dev2', 'Content-Type': 'application/json', 'Content-Length': '2', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-GB,*', 'Host': '192.168.0.146:8000'}
> 2017-08-01 12:16:40 DEBUG response.py:59 {}
> 2017-08-01 12:16:40 INFO response.py:60 Response: 200 OK
> 2017-08-01 12:16:40 DEBUG response.py:61 {'Connection': 'close', 'X-Route': '/v2/settings', 'Server': 'Python/3.6 GNS3/2.1.0dev3', 'Content-Type': 'application/json'}
>

**Comment by noplay** [comment]
How do you start the server ? It seem the --local flag is missing

**Comment by AJNOURI** [comment]
Damn!!   That solved the issue.
I was running the server as:

`gns3server --debug`

Should'nt it run "locally" by default? I guess I didn't grasp the significance of "--local" :-|

**Comment by noplay** [comment]
A warning will be now display on the server console.

Local give full access to your file system that why it's not enabled by default excepted when started by the gui process.
