### ISSUE TITLE
The qemu.log in project folder take a lot of space

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-server#1164]
The qemu.log in project folder takes a lot of space.
Once running a topo with dozens of nodes based on qemu  for little long time ,
it will cost all the space of disk,and no more node can be start.

![2](https://user-images.githubusercontent.com/9411604/29323503-ac95e68a-8213-11e7-990d-c515e37f1101.jpg)

![1](https://user-images.githubusercontent.com/9411604/29323520-bc4229cc-8213-11e7-8be0-bd05fda76bd8.png)

![3](https://user-images.githubusercontent.com/9411604/29323527-c18dc026-8213-11e7-8046-aa8b98eec518.png)

**Comment by noplay** [comment]
You are using a Cisco appliance with e1000 network adapters?

**Comment by noplay** [comment]
We are aware of a bug in qemu that generate a lot of noise. We send a patch to qemu but it's not yet merged

**Comment by grossmj** [comment]
@superwolfboy can you update us please? Thanks! :)

**Comment by superwolfboy** [comment]
very sorry for delay I just recived the mail now_ ..

**Comment by superwolfboy** [comment]
@noplay include the csr1000v

**Comment by noplay** [comment]
Yeah it's the qemu issue that spam log

**Comment by grossmj** [comment]
@noplay were you talking about https://github.com/GNS3/gns3-server/issues/939?

**Comment by MaPiBe** [comment]
in case we have "qemu.log" files that are 100MB+, can we safely remove the files from the project folder?

**Comment by noplay** [comment]
Yes you can flush it
