### ISSUE TITLE
Importing large projects

### ISSUE THREAD

**Issue by peterbrittain** [GNS3/gns3-server#1165]
First off, can I just say GNS3 is great!  Thanks for taking the time and effort to make it open source and support it...

I've recently been trying to use GNS3 (v2.x) on Linux to emulate some large networks, which needed more than one remote server to host all the necessary nodes.  I now need a way to be able to share that project with someone else on a different installation, so I use a portable project to export and import the definitions.

The problem is that when I export the project, gns3 flattens the definition down to use just one compute resource (the "local" resource).  When I then import the project definition, it then imports everything to the single server and I cannot run the network.  It is not possible to move the allocations around because https://github.com/GNS3/gns3-server/issues/575 has not been implemented yet.

I therefore created this simple patch to round-robin nodes across all available compute resources.

```
diff --git a/gns3server/controller/import_project.py b/gns3server/controller/import_project.py
index d3cb6f0..1e032a6 100644
--- a/gns3server/controller/import_project.py
+++ b/gns3server/controller/import_project.py
@@ -23,6 +23,7 @@ import shutil
 import asyncio
 import zipfile
 import aiohttp
+import itertools
 
 from .topology import load_topology
 
@@ -116,8 +117,10 @@ def import_project(controller, project_id, stream, location=None, name=None, kee
                         if node["node_type"] in ("docker", "qemu", "iou", "nat"):
                             node["compute_id"] = "vm"
                 else:
+                    # Round-robin through available compute resources.
+                    compute_nodes = itertools.cycle(controller.computes)
                     for node in topology["topology"]["nodes"]:
-                        node["compute_id"] = "local"
+                        node["compute_id"] = next(compute_nodes)
 
             compute_created = set()
             for node in topology["topology"]["nodes"]:

```

I believe that this is at least as good as the existing code because:

- it has exactly the same result when you just have the single compute resource
- it provides rudimentary load-balancing when you have the available resources.  

Of course, I'm new to this code, so could easily have missed something.  Is this any use to you?  Let me know if you'd like me to submit a pull request for this change.

**Comment by grossmj** [comment]
Thanks for the report. This may have to wait for version 2.2

**Comment by peterbrittain** [comment]
Sure.  Anything I can do to help?

**Comment by grossmj** [comment]
All good for now, we just need to have a discussion between developers.

Thanks again.

**Comment by grossmj** [comment]
@noplay I think this should be safe to include. What do you think?

**Comment by noplay** [comment]
The patch will work only for linux and will not take into account the fact that a remote could be a windows.

But it should work on most user computers

**Comment by grossmj** [comment]
Thanks @peterbrittain, we have included your patch :+1:
