### ISSUE TITLE
Wireshark Live Packet capture stucks at "Waiting for capture input data".

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1166]
This need to be investigated: https://gns3.com/qa/gns3-2-0-3-wireshark-live-packet

**Comment by noplay** [comment]
I made test few week ago and didn't replicate the problem on windows. Could be linked to a third party software

**Comment by grossmj** [comment]
This issue may be linked with https://github.com/GNS3/gns3-gui/issues/2235

**Comment by grossmj** [comment]
Maybe linked to this: https://github.com/GNS3/gns3-gui/issues/2130#issuecomment-328264008

**Comment by grossmj** [comment]
Indeed the problem was BitDefender. See GNS3/gns3-gui#2130 (comment) to fix.
