### ISSUE TITLE
Connectivity between Host/Virtual machine to GNS3 topology fails intermittenly

### ISSUE THREAD

**Issue by Azzara1** [GNS3/gns3-server#1167]
Hi GNS3 Team,
Thanks very much for the wonderful software that you have developed.
However I have come across a few issues in connectivity.
I wish to report an issue I am facing where the connectivity between the host PC or VMWare workstation VM and the GNS3 topology (Switches, routers etc fails) **intermittently.**

I have also tried using the beta version 2.1 beta 1 and that fails intermittently as well.
I have noticed that other users have also reported this issue 

https://www.gns3.com/qa/not-able-to-ping-with-a-switch
https://www.gns3.com/qa/router-cant-ping-cloud-vm-when-e
https://www.gns3.com/qa/connection-between-nodes-running
https://www.gns3.com/qa/connectivity-fails-to-gns3-route

Before reporting this issue, I have tried 
1. Deleting and Adding the links between the cloud (that has the vmnet host-only adapter attached) and the GNS3 switch, and the links from the GNS3 switch to the routers

2. I have tried deleting and adding a new GNS3 switch

3. I have tried connecting the cloud directly to the routers without a GNS3 switch in between

4. I have tried the new beta version 2.1 beta 1 and that fails intermittently as well

Thanks for all your hard work and support guys!

**Comment by grossmj** [comment]
Same issue as https://github.com/GNS3/gns3-gui/issues/2228, looped back packets corrupt the Ethernet switch.

**Comment by grossmj** [comment]
@Azzara1 please try with GNS3 2.1 beta 2. This should solve the issue.

**Comment by grossmj** [comment]
For reference, here is how to solve the problem:

**Not using the GNS3 VM**

Uninstall winpcap and install https://nmap.org/npcap/dist/npcap-0.08-r3.exe or just install GNS3 version 2.1 beta 2

**Using the GNS3 VM**
 
Please see https://gns3.com/qa/cloud-does-not-works-after-upgra
