### ISSUE TITLE
Exception: Invalid port range 31000-20000

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#117]
Check user submitted port ranges.

https://app.getsentry.com/gns3/gns3-server/group/60486263/

**Comment by noplay** [comment]
Fixed on client side

**Comment by grossmj** [comment]
We should check on the server side as well ;)

**Comment by noplay** [comment]
The user as corrupted is config file ....
What should we do? Throw an error at startup or inverse the values with a warning?

**Comment by grossmj** [comment]
I think throw an error... but the question is how will he see it?

**Comment by noplay** [comment]
yeah because the server will exit ... And the server output is not visible in the console

**Comment by grossmj** [comment]
Maybe we can send an error when a VM uses the range? not when we read it from the config file.

**Comment by noplay** [comment]
Ok I will implement that

**Comment by noplay** [comment]
Hey hey we display already an ugly error:
![capture d ecran 2015-05-06 a 10 26 48](https://cloud.githubusercontent.com/assets/345437/7489770/b4c11f1a-f3da-11e4-80bc-72c22429db52.png)

I will clean that

**Comment by noplay** [comment]
And more awesome the GUI fixed the error at the next launch. We are so smart!
