### ISSUE TITLE
docker: restore file permissions fails for volumes with soft links

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1180]
Running GNS3 version 2.0.4dev1 on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0 and PyQt 5.6.

When a docker container is restarted, the /gns3/init.sh script restores the file permissions. But when a volume contains a soft link, then the script doesn't restore the permissions of the link, but changes the permissions of the file, that it links to. The linked file will get permission 777 and owner 1000:1000  (the user id of the GNS3 process).

The fix is to not restore the permissions of a link, it's always 777 and doesn't need to be restored. Furthermore the owner of the link should be set (chown -h) instead of the file the link points to. Here my fix:

```
index 43f31685..6f95fa89 100755
--- a/gns3server/compute/docker/resources/init.sh
+++ b/gns3server/compute/docker/resources/init.sh
@@ -39,8 +39,8 @@ do
     then
         while IFS=: read PERMS OWNER GROUP FILE
         do
-            chmod "$PERMS" "$FILE"
-            chown "${OWNER}:${GROUP}" "$FILE"
+            [ -L "$FILE" ] || chmod "$PERMS" "$FILE"
+            chown -h "${OWNER}:${GROUP}" "$FILE"
         done < "$i/.gns3_perms"
     fi
 done
```

**Comment by grossmj** [comment]
Thanks, I will include your fix soon 👍

**Comment by grossmj** [comment]
Thanks again!
