### ISSUE TITLE
IOU: detection of layer 1 keepalive support doesn't work

### ISSUE THREAD

**Issue by ddragic** [GNS3/gns3-server#1183]
Turning on the "Enable layer 1 keepalive messages (testing only)" IOU setting always produces the "layer 1 keepalive messages are not supported by <iou image>" error message.

Looks like the check in _enable_l1_keepalives() (in iou_vm.py) is looking for the pattern "-l\s+Enable Layer 1 keepalive messages" in standard output produced by the IOU executable, but IOU writes the help message on standard error, hence no match.

**Comment by ziajka** [comment]
Hi @ddragic! Thank you for reporting this. We will investigate that. 
Cheers,
Dominik
