### ISSUE TITLE
[2.1.0dev8] Container don't recognize the path to ping

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1189]
Containers doesn't recognize the path to busybox tools, essentially **ping**.
Users need to specify the complete path, **/tmp/gns3/bin**

At the beginning of  [**init.sh**](https://github.com/GNS3/gns3-server/blob/e74e66b20363766c60cd46e044005a06cb340393/gns3server/compute/docker/resources/init.sh), the old path is preserved, busybox tools added
```
OLD_PATH="$PATH"
PATH=/gns3/bin:/tmp/gns3/bin
```

But at the end, only the old path is restored and buxybox tool path is lost
```
\# continue normal docker startup
PATH="$OLD_PATH"
```
I've tried to append it and recompiled the server, but still doesn't recognize the path to ping

`PATH=$PATH:"$OLD_PATH"`

**Comment by ehlers** [comment]
The busybox binaries are meant for the GNS3 specific initialization, not for general use. It can create issues in your container, when the busybox path is added to the normal path and the user is unaware of that. Furthermore it creates another difference between usage of the container within GNS3 and usage outside GNS3 (without these busybox tools). I think, these difference should be kept to the minimum.

If you want a ping in your container, I suggest to install it.

**Comment by AJNOURI** [comment]
OK, got it. Thanks @ehlers.
