### ISSUE TITLE
[v2.1.0dev8] Issue opening a lab after rebooting the host. Cannot change server settings

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1190]
Trying to open a lab in which a couple of nodes installed on the remote server, the remaining installed on local server.

I get "Can't connect to \<myremoteserver\>"

![selection_002_10_10](https://user-images.githubusercontent.com/1716020/31370203-f629a4a2-ad89-11e7-9725-c289d0c7cc00.jpg)

Because of a couple of devices, the entire lab is no more available.

**Comment by AJNOURI** [comment]
The lab gns3 file shows that the lab is using exclusively the remote server, which was used only for a couple of devices that has been deleted since.

![selection_006_10_10](https://user-images.githubusercontent.com/1716020/31370923-8b4e3ae4-ad8e-11e7-8bc2-4fafe778ea04.jpg)

**Comment by grossmj** [comment]
@ziajka how do you think we should handle this?

**Comment by ziajka** [comment]
@grossm Definitely j I don't think we should run a lab when some devices are not available. I think it's necessary to "distribute" devices over available computes. This requires pretty heavy changes in gns3-server and it's related to https://github.com/GNS3/gns3-server/issues/1186

**Comment by ziajka** [comment]
@grossmj There is another solution, we may ask user to delete "missing devices" and when he confirms then we delete devices and links related to those devices. That may do the trick.

**Comment by grossmj** [comment]
Yes, we could do that in last resort however this would break the original project because of the auto save feature.

**Comment by ziajka** [comment]
Yep, that's true.
