### ISSUE TITLE
VPCs never stop crashing 

### ISSUE THREAD

**Issue by MrMic** [GNS3/gns3-server#1191]
Hi,

I have recently update to 2.0.3 and when i try to use VPCs for 
Labs, it never stop crashing after after some seconds.

Thanks to fix it.
Rgds,

**Comment by grossmj** [comment]
Where do you connect your VPCS?

**Comment by MrMic** [comment]
To a router

**Comment by grossmj** [comment]
Is this a Dynamips router or something else?

Unfortunately we don't maintain VPCS and we intend to replace it by something else. My theory is that your VPCS node received a packet that it cannot read correctly which result in a crash.

**Comment by MrMic** [comment]
Yes, it is a C7200 cisco image, on dynamips.

**Comment by grossmj** [comment]
Do you have the image name and the startup-config for that router?

Thanks!

**Comment by MrMic** [comment]
Sure !
It is just a lab ...
Image => c7200-is-mz.123-21.image
StartUp config =>
========8< ===================== >8 ===
!
!
!
!
!
!

!
version 12.3
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname Router_1
!
boot-start-marker
boot-end-marker
!
enable secret 5 $1$6BgZ$zmEem0oWBB4aeJmTrYE06/
enable password pepere
!
no aaa new-model
ip subnet-zero
no ip icmp rate-limit unreachable
!
!
ip cef
ip tcp synwait-time 5
no ip domain lookup
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface FastEthernet0/0
 ip address 192.168.1.1 255.255.255.0
 duplex half
!
interface FastEthernet1/0
 ip address 192.168.0.1 255.255.255.0
 duplex auto
 speed auto
!
interface FastEthernet1/1
 no ip address
 shutdown
 duplex auto
 speed auto
!
ip classless
ip route 0.0.0.0 0.0.0.0 192.168.1.2
no ip http server
!
!
no cdp log mismatch duplex
!
!
!
!
!
!
!
gatekeeper
 shutdown
!
!
line con 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
 stopbits 1
line aux 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
 stopbits 1
line vty 0 4
 password vtypass
 login
!
!
end

=== 8< =========================== >8 ===

**Comment by grossmj** [comment]
@MrMic do you only use Windows?

**Comment by grossmj** [comment]
I could not reproduce the problem on Linux. Do you use VPCS version 0.6.2?

**Comment by grossmj** [comment]
@MrMic ping

**Comment by MrMic** [comment]
Hi,

As i notice you in the crash billet of the new version of GNS3, it seems that VPC do not crash anymore.
If it happens again, i would open a new ticket.
You can close.

Thanks for all.
Rgds,

**Comment by grossmj** [comment]
Ok :+1:
