### ISSUE TITLE
NX-OSv 9k crashes during boot with latest qemu

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#1193]
@noplay @grossmj 
Ubuntu 17.04
qemu 2.10.1(Debian 1:2.10.0+dfsg-2)
gns3 2.0.3
NX-OSv 9k 7.0.3.I6.1

No such issue with previous qemu 2.8.x
Either some parameters usage have changed (for instance -bios) (which would make qemu not backwards compatible) or there is an issue with qemu itself.
The configuration parameters are:
```
                "compute_id": "local",
                "console": 2010,
                "console_type": "telnet",
                "first_port_name": "mgmt0",
                "height": 48,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "NX_OSv_9k_Spine_31",
                    "x": -54,
                    "y": -25
                },
                "name": "NX_OSv_9k_Spine_31",
                "node_id": "8d01119a-0adc-41bc-950b-c5639db7708c",
                "node_type": "qemu",
                "port_name_format": "Ethernet1/{port1}",
                "port_segment_size": 0,
                "properties": {
                    "acpi_shutdown": false,
                    "adapter_type": "e1000",
                    "adapters": 10,
                    "bios_image": "",
                    "bios_image_md5sum": null,
                    "boot_priority": "c",
                    "cdrom_image": "",
                    "cdrom_image_md5sum": null,
                    "cpu_throttling": 0,
                    "cpus": 2,
                    "hda_disk_image": "NX-OSv-9k-7.0.3.I6.1.free.qcow2",
                    "hda_disk_image_md5sum": "18bb991b814a508d1190575f99deed99",
                    "hda_disk_interface": "ide",
                    "hdb_disk_image": "",
                    "hdb_disk_image_md5sum": null,
                    "hdb_disk_interface": "ide",
                    "hdc_disk_image": "",
                    "hdc_disk_image_md5sum": null,
                    "hdc_disk_interface": "ide",
                    "hdd_disk_image": "",
                    "hdd_disk_image_md5sum": null,
                    "hdd_disk_interface": "ide",
                    "initrd": "",
                    "initrd_md5sum": null,
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "kernel_image_md5sum": null,
                    "legacy_networking": false,
                    "mac_address": "00:07:00:03:16:01",
                    "options": "-nographic -enable-kvm -cpu host -machine q35 -smp cpus=2 -bios /usr/share/ovmf/OVMF.fd",
                    "platform": "x86_64",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 6144,
                    "usage": ""
```

The logs are:
- [execution log](https://github.com/GNS3/gns3-server/files/1381651/qemu.log.txt)
- [terminal log](https://github.com/GNS3/gns3-server/files/1381660/terminal.log.txt)

**Comment by jean-christophe-manciot** [comment]
I can boot:
- IOSv 15.6(2)T
- IOSv-L2 15.2(20170321:233949)
- CSR 1000v 16.5.1b
- ASAv 9.6(2)

The major difference with NX-OSv 9k is the bios parameter: ```-bios /usr/share/ovmf/OVMF.fd```: 
```
ll /usr/share/ovmf/OVMF.fd
-rw-r--r-- 1 root root 2097152 Dec  9  2016 /usr/share/ovmf/OVMF.fd
```
A normal boot log with qemu 2.8.1 is available [here](https://github.com/GNS3/gns3-server/files/1381729/terminal.log.2.8.txt)

Highlighting the differences: qemu 2.8.1 on the left, qemu 2.10.1 on the right hand side with the same boot parameters
![qemu 2 8 vs qemu 2 10](https://user-images.githubusercontent.com/13176858/31534998-8429462e-aff9-11e7-9cf3-bf2b00c21e8a.jpg)

**Comment by grossmj** [comment]
The problem is definitely with Qemu 2.10.1. The only thing we could do is post a bug report on their side.

**Comment by jean-christophe-manciot** [comment]
@grossmj 
I've just reported it on [launchpad](https://bugs.launchpad.net/qemu/+bug/1732679).

**Comment by grossmj** [comment]
@jean-christophe-manciot thanks :+1:

**Comment by cioby23** [comment]
I think this issue is not Qemu related since I run same NX-OSv 9000 image (NX-OSv 9k 7.0.3.I6.1) using Qemu 2.10.1 on Archlinux and it works fine.
The problem might be the OVMF bios file which Ubuntu uses. It's released in dec 2016 and it might not be compatible with the latest Qemu version.
On Archlinux I use a recent version (september this year) and the NX-OS image boots fine.

**Comment by jean-christophe-manciot** [comment]
Thanks @cioby23  for your comment.
I'll take a look later on with a fresher ovmf package.

**Comment by jean-christophe-manciot** [comment]
With:
- gns3 GUI/server 2.1.0
- qemu 2.10.0+dfsg-2
- ovmf 0~20171027.76fd5a66-1
Launching an NX-OSv-9k 7.0(3)I6(1) image does work.
There should have been a package constraint in qemu in the form "depends: ovmf >= some minimal version" to avoid the previous situation, even though there is not a direct dependency.

**Comment by grossmj** [comment]
Thanks for the feedback :+1:
