### ISSUE TITLE
Only IOS and IOU imagies will load in GNS3 v1.5.2 and 2.1.0rc1

### ISSUE THREAD

**Issue by jmann12180** [GNS3/gns3-server#1199]
Hello all,
 
I could really use some help with this one.  I have done a lot of looking into this, but I have not been able to find any solution(s).
 
I am running a window 10 pro box with 64gig of memory.  I am running GNS3 in VMWare workstation 12 pro.  I am running GNS3 v 1.5.2.  Please keep in mind that I have also blowen away this version, downloaded the current version and I get the same results.
 
I have no issues getting GNS3 to launch.  I can import IOS'es all day long.  I can drag them onto the topolgy area and launch them, well they turn green, and I can see the cpu amd mem spin up some and then go back down.  I then try to console into the devices and the console window comes up, but no output.  This happens with all imagies except regualr IOS and IOU.  Those load up and I can console into them and get output in the console window.
 
I had read in a few places about certain processors not being able to run the IOSv, XRv, CSR1000 etc because of some threading issue, but I really couldn't find out a lot about this.  My system supports hyper threading and all of the other virtualization requirements.
 
I am attaching a bunch of screen shots so you can see what I am talking about. 
 
I would really love to get these running in GNS3 any assistance would be greatly appreciated.  Thank you in advance.
 
Mike

![router bootup log](https://user-images.githubusercontent.com/32907765/31729931-73dbf54c-b3fe-11e7-9659-e2aebcef7659.PNG)

![cpu info](https://user-images.githubusercontent.com/32907765/31729943-791fabfc-b3fe-11e7-8f38-5f913b08f51f.PNG)

![hyper threading is supported](https://user-images.githubusercontent.com/32907765/31729948-7be8ed80-b3fe-11e7-8159-955b5d931533.PNG)

![iosv-15 5 qemu vm setup](https://user-images.githubusercontent.com/32907765/31729953-7f831b46-b3fe-11e7-9493-aff4c0251df8.PNG)

![kvm support - true](https://user-images.githubusercontent.com/32907765/31729959-81f4334c-b3fe-11e7-8464-8e8b2ad1dbea.PNG)

![router start up](https://user-images.githubusercontent.com/32907765/31729967-845535fa-b3fe-11e7-99f6-435b8b8fd4fd.PNG)

![lscpu - output](https://user-images.githubusercontent.com/32907765/31729971-86ef1ad8-b3fe-11e7-8c98-74b2fe6b5865.PNG)

![vm settings](https://user-images.githubusercontent.com/32907765/31729976-89f1433c-b3fe-11e7-81f3-6d78576b3c34.PNG)

![system](https://user-images.githubusercontent.com/32907765/31729982-8c783264-b3fe-11e7-94b7-ca6c930812e6.PNG)

![intel processor identification info](https://user-images.githubusercontent.com/32907765/31729985-8f1bba18-b3fe-11e7-81cf-2a56d10451e4.PNG)

**Comment by jmann12180** [comment]
Hello,

Has anyone had a chance to look at this issue? Do you need me to gather more information?

Thanks,
Mike

**Comment by ziajka** [comment]
Hi @jmann12180 

It might be a console issue.
Could you try VNC console? (Node settings, change from "telnet" to "vnc").

Cheers,
Dominik

**Comment by jmann12180** [comment]
I changed the console option to VNC in the Preferences tab, QEMU - Qemu VMs, picked my IOSv 15.5(3)M image, but I get an error when the TightVNC viewer pops up.  See attached screen shoot.

![vnc issue](https://user-images.githubusercontent.com/32907765/31841345-2030932a-b5b7-11e7-9edc-10d79bc95f4e.PNG)

**Comment by jmann12180** [comment]
Hello,

Does anyone that knows how GNS3 is put together and works under the hood have any idea what is causing this problem?  Has anyone been able to look at this?  Thank you Dominik for your suggestion.

Thanks,
Mike

**Comment by grossmj** [comment]
IOSv is accessed using Telnet. I don't why you cannot see anything. Have you tried with GNS3 v2.1RC3?

**Comment by ehlers** [comment]
Can you try to stop one node, right-click on it, then configure. Then select the "Advanced Settings" and add " -machine type=pc-1.0" to the options. Afterwards start it again.
![node_properties](https://user-images.githubusercontent.com/896406/31863743-4722563e-b752-11e7-84ac-918f2deee009.png)

I'm using my own GNS3 VM based on Debian with Qemu 2.8 and had to use this option. Up to now, I thought that's because of the newer Qemu. But maybe there's is another reason for that and you are also effected.

**Comment by jmann12180** [comment]
Hello grossmj,

Last night my laptop upgraded to windows 10 creator.  Today I downloaded GNS2.0.3 and its VM.  I have been able to import images like a madman now using their appliances.  I am able to launch them all with the exception of ASAv 9.7.1, I see it go through its two reboots and then it just hangs.  I'll have to get the msg that appears in the console for you.  And I can't get IOS XRv 9000 to load.  I'm using the image from my Virl account but it fails saying I'm missing a file????  

Thank you,
Mike

**Comment by jmann12180** [comment]
Hello grossmj,

Ok so this is where the ASAv just sits, after the second bootup.  I've waited past 30mins for a change.

![asav 971 issue - not coming up after second bootup](https://user-images.githubusercontent.com/32907765/31969080-6073f92c-b8e1-11e7-9416-46d428699a63.PNG)

**Comment by ehlers** [comment]
That's normal behavior of the ASAv, see also David's video https://www.youtube.com/watch?v=UzqBpPP7_iA&t=470 at 7:50. You have to change the console type to telnet.

**Comment by grossmj** [comment]
I am closing this. Please post on the forum if you need support.

Thanks! :+1:
