### ISSUE TITLE
VMware 14 uses different default directory for VM and GNS3 looks for the old.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1201]
Looks like Vmware 14 uses different default location for VMs (**C:\Users\{user}\Documents\Virtual Machine**s)

and GNS3 looks for (**C:\Users\{user}\Documents\My Virtual Machines)**, that's why it cannot detect GNS3 VM nor its IP.

![selection_011_21_10](https://user-images.githubusercontent.com/1716020/31848595-055fceec-b636-11e7-8d7c-8546695c83cc.jpg)

I had to rename the default "Virtual Machines" to "My Virtual Machines" for GNS3 to detect GNS3 VM.

Even though the message is very explicit and clearly hints the solution, it appears only when I tries to import new VMs from \<preferences\>

**But just after installing GNS3, there no hint about the issue, it just don't detect the VM or its IP**. New users could be just stuck there.

**Comment by grossmj** [comment]
Do you use VMware Workstation Pro or Player?

**Comment by AJNOURI** [comment]
Player

**Comment by AJNOURI** [comment]
Even changing the directory name doesn't seem to solve the issue.

It looks like it recognize the VM until I want to perform an operation on the VM (install appliance, import project that needs VM...)

![image](https://user-images.githubusercontent.com/1716020/31849217-48c9c4a4-b63f-11e7-8b46-1404441adbcd.png)

**Comment by grossmj** [comment]
Do you have this file? => %APPDATA%\VMware\preferences.ini

If yes, what is the content?

Thanks :)

**Comment by AJNOURI** [comment]
.encoding = "windows-1252"
pref.keyboardAndMouse.vmHotKey.enabled = "FALSE"
pref.keyboardAndMouse.vmHotKey.count = "0"
pref.vmplayer.firstRunDismissedVersion = "14.0.0"
pref.lastUpdateCheckSec = "1508562402"
pref.mruVM0.filename = "C:\Users\Admin\Documents\My Virtual Machines\GNS3 VM\GNS3 VM.vmx"
pref.mruVM0.displayName = "GNS3 VM"
pref.mruVM0.index = "0"
pref.hostMRU.count = "1"
pref.hostMRU0.name = "localhost"
pref.hostMRU0.type = "vim"
pref.ws.session.window.count = "1"
pref.ws.session.window0.tab.count = "1"
pref.ws.session.window0.tab0.dest = ""
pref.ws.session.window0.tab0.file = ""
pref.ws.session.window0.tab0.type = "home"
pref.ws.session.window0.tab0.cnxType = "vmdb"
pref.ws.session.window0.tab0.focused = "FALSE"
pref.ws.session.window0.sidebar = "TRUE"
pref.ws.session.window0.sidebar.width = "200"
pref.ws.session.window0.statusBar = "TRUE"
pref.ws.session.window0.tabs = "TRUE"
pref.ws.session.window0.thumbnailBar = "FALSE"
pref.ws.session.window0.thumbnailBar.size = "125"
pref.ws.session.window0.thumbnailBar.view = "same-folder"
pref.ws.session.window0.placement.left = "156"
pref.ws.session.window0.placement.top = "156"
pref.ws.session.window0.placement.right = "1016"
pref.ws.session.window0.placement.bottom = "765"
pref.ws.session.window0.maximized = "FALSE"

**Comment by noplay** [comment]
Look like the file contains wrong intel

**Comment by grossmj** [comment]
One temporary workaround is to add the following to the preferences.ini file: `prefvmx.defaultvmpath=C:\Users\Admin\Documents\My Virtual Machines`

**Comment by AJNOURI** [comment]
Doesn't seem to change the behavior

![selection_025_21_10](https://user-images.githubusercontent.com/1716020/31849981-8f9c02d2-b64b-11e7-89de-181ac2acd1bc.jpg)

**Comment by grossmj** [comment]
Something is wrong with VMware now (unable to connect to host). You should revert to the original VM location and restart. I know from experience VMware does not like to be tweaked too much like that ;)

**Comment by grossmj** [comment]
I have improved the VM discovery process to check in both "My Virtual Machines" and "Virtual Machines in Documents.

**Comment by grossmj** [comment]
@AJNOURI I think I fixed the issue. Please re-open if you still have it.
