### ISSUE TITLE
Mismatch between number of interfaces in the template image and in the router instance ==>"Error while creating link: Internal server error"

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1203]
Wanted to increase the number of interfaces in the template (up to 5), but the instance in the canvas I erroneously set to 6 (shouldn't be possible)

![image](https://user-images.githubusercontent.com/1716020/31867760-d3bff5dc-b794-11e7-8bc6-09f961f440fa.png)

This led to error when trying to create a link with the excess interfaces:

> 2017-10-23 01:31:05 DEBUG http_client:618 Response error: Error transferring http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/bd297a3f-ca6f-4b61-93df-2c33357c5fad/links - server replied: Internal Server Error for http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/bd297a3f-ca6f-4b61-93df-2c33357c5fad/links (error: 401)
> 2017-10-23 01:31:05 WARNING link.py:223 Error while creating link: Internal server error http://192.168.0.146:8000/v2/compute/projects/bd297a3f-ca6f-4b61-93df-2c33357c5fad/qemu/nodes/5b89389e-b8e1-4c1a-906b-ca37ee4d4779/adapters/4/ports/0/nio
> 2017-10-23 01:31:05 DEBUG link:303 deleting link from R11 Gi0/4 to R22 Gi0/4

Maybe we could avoid this by not allowig user to set interface number for router on the canvas bigger than it template's interface number.

**Comment by ehlers** [comment]
In 2.0.4dev1 that works for me.

What I did:
- created a new topology
- moved 2 IOsv with 4 interfaces in the template into the project
- changed one IOSv to 5 interfaces
- connected the fifth interface (gi-0/4) of that IOSv to gi-0/0 of the unmodified IOSv

Works fine, no issues. In fact I've done that in the past, when I needed more interfaces within that project. I never had any issues with that.

**Comment by AJNOURI** [comment]
Weird... I could not reproduce it, though, back then, the issue was persistent (at least during the project session) the only solution was to make the  template interface > instance interface number.

I think, lots of errors I am observing are circonstanciel, maybe local to my PC, which I often push to the limit, especially RAM (GNS3 labs, VMs & lots of chrome )...
Cannot say for sure.

**Comment by ziajka** [comment]
Thanks @AJNOURI, when you are able to reproduce this issue let us know. So far I'm giving the flag "Waiting for more information".
