### ISSUE TITLE
Cannot see newly created project from REST API

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1207]
Even though I created a project (api-test2), created a device, started it, still this project doesn’t show in the GNS3 project directory, did I missed something?

When trying to open the new project, it is not in the project directory
![selection_003_29_10](https://user-images.githubusercontent.com/1716020/32142605-e3504d70-bc9a-11e7-8a64-5b65a836c8fd.jpg)

Is there a way to list and work on (create/start/... devices) the currently opened project in gui, from API?

**Comment by ehlers** [comment]
Did you give the 'path' parameter to the create project call? If not, it is created in the `~/GNS3/project/<project-id>` directory.

This works for me on GNS3 2.0.3:
```
#!/usr/bin/env python3

import os
import gns3api

api = gns3api.GNS3Api()
result = api.request('POST', '/v2/projects',
    {'name': 'test-project',
     'path': os.path.join(os.path.expanduser("~/GNS3/projects"), 'test-project')})
print(result)
```

**Comment by ehlers** [comment]
Even when I don't give the 'path' parameter, it's available in the GUI in the projects library.
![api-project](https://user-images.githubusercontent.com/896406/32173250-a094a67c-bd7e-11e7-98e6-80c30b8f4307.png)

**Comment by AJNOURI** [comment]
Thanks Ehlers,

After closer inspection of the JSON output, the project was there... well it was named by **id**


```
curl -X POST "http://192.168.0.146:8000/v2/projects" -d '{"name": "api-test2"}'
{
    "auto_close": true,
    "auto_open": false,
    "auto_start": false,
    "filename": "api-test2.gns3",
    "name": "api-test2",
    "path": "/home/ajn/GNS3/projects/6f1c4aaa-f820-4d30-9bc1-24b583910ddb",
    "project_id": "6f1c4aaa-f820-4d30-9bc1-24b583910ddb",
    "scene_height": 1000,
    "scene_width": 2000,
    "show_grid": false,
    "show_interface_labels": false,
    "show_layers": false,
    "snap_to_grid": false,
    "status": "opened",
    "zoom": 100

}
```

![image](https://user-images.githubusercontent.com/1716020/32196756-f7591568-bdc1-11e7-8e0f-0ffdc1017443.png)

Cannot see why some project directories are named by their id.

**Comment by grossmj** [comment]
Project are named by their id when they a on a remote server.

**Comment by AJNOURI** [comment]
ok @grossmj 
Still they are not humanly-readable, like in the screenshot I previously provided.
