### ISSUE TITLE
Different sha512sums value in version 2.0.3

### ISSUE THREAD

**Issue by rgdoliveira** [GNS3/gns3-server#1211]
Alpine Linux builds gns3-server and it downloads the 2.0.3 source from [github](https://github.com/GNS3/gns3-server/archive/v2.0.3.tar.gz)

We are rebuilding all the Alpine packages for 3.7 release but gns3-server failed to build when comparing the sha512sums. It was before:
sha512sums="a9927e414f6fc6558cecabd006f9d123752b0b6e5b88408a53a6d1f195d22047ffdc3e4ccc6e132d04135c434174aa4b58f29deae9e952f83ccc678037f25b8a  gns3-server-2.0.3.tar.gz"

And now:
sha512sums="0bbecba9c0b74846f458a7da7d8c041cf6320c5ce4b388bc1e8fd10a8dc52224282b537c309a5a0277bff78bd2c8a0f1df5a100b94f8321d2b9929ce3a88f06d  gns3-server-2.0.3.tar.gz

Does this tar.gz got any changes or it was uploaded again (or something like that)?

**Comment by rgdoliveira** [comment]
It seems a Github issue and it also happened with other projects that Alpine builds. You can close it if you want

**Comment by grossmj** [comment]
Indeed, we have had issues with Github recently. Let's close this. Thanks! :)
