### ISSUE TITLE
Unable to upgrade server to 2.1

### ISSUE THREAD

**Issue by sliddjur** [GNS3/gns3-server#1221]
I have 2.0.3 in ESXI VM. 

If I select version, then accept version 2.1.
Then back to main menu, then upgrade. I am still on 2.0.3 after reboot.

All settings seem to be reset, interface reset to DHCP etc...

How do I upgrade esxi vm to 2.1?

**Comment by grossmj** [comment]
@sliddjur this should work, can you try one more time please?

**Comment by sliddjur** [comment]
I did try twice. I also tried pressing upgrade twice. No success

**Comment by grossmj** [comment]
That's weird. I have no problem moving between versions with my GNS3 VM.

**Comment by grossmj** [comment]
Sorry, we couldn't reproduce the problem on our side. Please post on our community forum to ask for help and see if anyone who use ESX has the same issue.
