### ISSUE TITLE
GNS3 Hacking Documentation.

### ISSUE THREAD

**Issue by Zedonboy** [GNS3/gns3-server#1222]
I read API docs, its top notch, but i would love to see source code API tree and docs, actually i opened Gns-server source codes, i cant figure out where to add my codes. 

if you have any, python documentation please show me :-(

**Comment by grossmj** [comment]
Sorry we don't have such documentation.

**Comment by Zedonboy** [comment]
@grossmj i would love to contribute to that type of documentation.  do you have any HUD info you want to show before i start, 
because what am trying to do is look at the source code and API doc to figure out,  what the python source is actually doing......  (journey to the center of Gns Source Doc)
