### ISSUE TITLE
After upgrade to kubuntu 17.10 gns3 won't start

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1224]
From community forum:
https://gns3.com/qa/after-upgrade-to-kubuntu-17-10-g

Ubuntu Artful 17.10:

Issue installing gns3 2.1 from Documentation instructions:
https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html

----------

> Hi,
> I have upgraded to kubuntu 17.10 and also followed the instructions to install GNS3 from the following link:
> https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html
>  
> In the terminal when i type gns3, I get following error, Please help.
> :~$ gns3
> Traceback (most recent call last):
> File "/usr/bin/gns3", line 5, in 
> from pkg_resources import load_entry_point
> File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/pkg_resources/__init__.py", line 24, in 
> import types
> File "/usr/share/gns3/gns3-gui/lib/python3.5/types.py", line 166, in 
> import functools as _functools
> File "/usr/share/gns3/gns3-gui/lib/python3.5/functools.py", line 23, in 
> from weakref import WeakKeyDictionary
> File "/usr/share/gns3/gns3-gui/lib/python3.5/weakref.py", line 12, in 
> from _weakref import (
> ImportError: cannot import name '_remove_dead_weakref'
> Error in sys.excepthook:
> Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 62, in apport_excepthook
> import re, traceback
> File "/usr/lib/python3.5/traceback.py", line 5, in 
> import linecache
> File "/usr/share/gns3/gns3-gui/lib/python3.5/linecache.py", line 8, in 
> import functools
> File "/usr/share/gns3/gns3-gui/lib/python3.5/functools.py", line 23, in 
> from weakref import WeakKeyDictionary
> File "/usr/share/gns3/gns3-gui/lib/python3.5/weakref.py", line 12, in 
> from _weakref import (
> ImportError: cannot import name '_remove_dead_weakref'
> Original exception was:
> Traceback (most recent call last):
> File "/usr/bin/gns3", line 5, in 
> from pkg_resources import load_entry_point
> File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/pkg_resources/__init__.py", line 24, in 
> import types
> File "/usr/share/gns3/gns3-gui/lib/python3.5/types.py", line 166, in 
> import functools as _functools
> File "/usr/share/gns3/gns3-gui/lib/python3.5/functools.py", line 23, in 
> from weakref import WeakKeyDictionary
> File "/usr/share/gns3/gns3-gui/lib/python3.5/weakref.py", line 12, in 
> from _weakref import (
> ImportError: cannot import name '_remove_dead_weakref'

**Comment by AJNOURI** [comment]
By the way, issues with the release on 17.10

https://github.com/GNS3/gns3-gui/issues/2290

The packages released for 17.10, working back then for the beta, doesn't work anymore.
It reports dependency issues without possibility to install packages:

![image](https://user-images.githubusercontent.com/1716020/32950880-446d7f26-cba8-11e7-8edd-969087fb087c.png)

**Comment by ziajka** [comment]
Update for kubuntu case - with the fresh install there is no issue. Default there is python 3.6 but user has 3.5 so he has updated Kubuntu but we need to have an information from which version.

**Comment by ziajka** [comment]
Hi @AJNOURI ,
I've tried with the fresh install of Ubuntu 17.10 and also haven't experienced any issue.
Have you installed gns3-gui on the fresh copy? Or were you upgrading Ubuntu or GNS3? Many thanks!

Cheers,
Dominik

**Comment by zaki-chowdhury** [comment]
Can't install on kubuntu 17.10.
It says "Unable to locate package gns3-gui"

**Comment by grossmj** [comment]
> Can't install on kubuntu 17.10. It says "Unable to locate package gns3-gui"

I can see it there:
https://launchpad.net/~gns3/+archive/ubuntu/ppa?field.series_filter=artful

What are the steps you have done to try to install gns3-gui?

**Comment by z4kio** [comment]
sudo add-apt-repository ppa:gns3/unstable && sudo apt update && sudo apt install gns3-gui

**Comment by ziajka** [comment]
Hi @z4kio,
Could you try again:
`sudo add-apt-repository ppa:gns3/ppa
sudo apt update
sudo apt install gns3-gui
` ?
We've done some changes to related packages and everything seems to fine during the upgrade time.
Thank you,
Dominik

**Comment by z4kio** [comment]
![gns3](https://user-images.githubusercontent.com/4525622/34341556-d8190bf8-e9c3-11e7-81c0-ab278bad2bdf.png)

**Comment by ziajka** [comment]
Hi @z4kio ,
I've made small changes to packages. Could you test now?
Please let me also know if it helps.
Thank you,
Dominik

**Comment by grossmj** [comment]
@z4kio ping

**Comment by z4kio** [comment]
@grossmj hey,for some unexpected reason, I can't test it now or in few days.
and I will let you know if I test it on that system. 
sorry I've taken so long to reply!

**Comment by ziajka** [comment]
@z4kio Many thanks!

**Comment by grossmj** [comment]
I've tested on a fresh install of Kubuntu 17.10 and I was able to run GNS3 without any issues.
