### ISSUE TITLE
[GNS3 2.1.0rc3] Segmentation Fault 

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1225]
Source: community forum:
https://gns3.com/qa/gns3-2-1-0rc3-segmentation-fault

> Installed on Ubuntu 16.04.03 (inside HyperV), it was working very nicely but am getting segmentation faults more and more frequently over time.  I cannot tie them to any specific thing I do, though usually I have just done something like deleting a link or changing a node (as opposed to it just sitting and running). 
>  
> It's done it on two separate projects now.  The projects are all IOSvl2 or ASAv components (plus some GNS3 native), no other emulation.  The GNS3 install is from the ppa distribution not VM and not source-built.
>  
> I THINK that some of this may be that when it crashes, something remains running, as it seems much more likely to crash if I restart shortly after a prior crash.  Here's a typical message. I do not know that the first line is relevant, as it appears a lot, but include it just in case:.
>  
> QObject::setParent: Cannot set parent, new parent is in a different thread
> Fatal Python error: Segmentation fault
> Current thread 0x00007f2b31cb6700 (most recent call first):
> File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/main.py", line 289 in main
> File "/usr/bin/gns3", line 9 in <module>
> Segmentation fault (core dumped)
> 
> Note that it will sometimes run for a solid day without any error, then (for example) I just had four crashes in about 15 minutes.  After a restart after a crash it comes back to the same configuration (+/- the link I was changing, usually with the delete successful if the last thing I did was a delete).  I have seen no sign that anything is lost in a crash -- well, other than the 10 minutes or so it takes to get everything running again.
>  
> Any ideas?   Yes, I realize it's a beta.  Not complaining.

**Comment by Linwood-F** [comment]
Adding comment with my github account in case of questions, etc.  This is also failing on 2.1rc4 which I applied last night, I didn't see a 2.1 final in the 16.04 distros. 

In more testing it seems this relates to the NAT cloud.  It will not occur if the attached device (so far all ASAv in my case) is stopped when you delete the link, but if the device is running and you delete a link from ASAv to NAT then GNS3 exits.  There's also a startup message about a GNS3 "already running server" being killed.

I just tried connecting NAT to an IOSvL2 device, starting the link - no crash.

Went back to the ASAv device, created a link to NAT, started ASAv, crash.  So it seems pretty specific.

The ASAv I'm using is: vios_l2-adventerprisek9-m.03.2017.qcow2

I had some issue with the appliance, can't recall what, and think this is just a manual setup of the ASAv, so that could be related, but it seems to otherwise be working.  If details of it are required to reproduce let me know (and also what kind of details -- I'm pretty new to this).

**Comment by grossmj** [comment]
> In more testing it seems this relates to the NAT cloud. It will not occur if the attached device (so far all ASAv in my case) is stopped when you delete the link, but if the device is running and you delete a link from ASAv to NAT then GNS3 exits

Confirmed, I can reproduce this issue.

Thanks :+1:

**Comment by grossmj** [comment]
Very hard to debug. The problem seems to come from the GUI only and related to threads.

```
2017-11-20 16:30:49 INFO qt/__init__.py:298 "No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/12"
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffff495c440 in QPropertyAnimation::targetObject() const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

**Comment by grossmj** [comment]
This may be a Qt internal bug. I have tried with Qt 5.9.2 and no luck :(

**Comment by Linwood-F** [comment]
I'm also getting a somewhat similar error when exiting the program, even after stopping all devices.  It looks like this: 

(these three lines repeated 4-5 times - not sure how to tell that they are, but that there are three and I have three NAT clouds is suspicious) 

```
2017-11-20 08:17:08 INFO qt/__init__.py:298 "No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/15"
2017-11-20 08:17:08 INFO qt/__init__.py:298 "No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/14"
2017-11-20 08:17:08 INFO qt/__init__.py:298 "No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/13"
Fatal Python error: Segmentation fault

Current thread 0x00007f0047d3c700 (most recent call first):
  File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/local_server.py", line 548 in stopLocalServer
  File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/main_window.py", line 1079 in _finish_application_closing
  File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/main_window.py", line 1060 in closeEvent
  File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/main.py", line 289 in main
  File "/usr/bin/gns3", line 9 in <module>
Segmentation fault (core dumped)
```

**Comment by Linwood-F** [comment]
Some more experimentation seems to show it's going to fail in this way whether the ASAv is running or not, it seems relevant to it having been running.   So stopping it and then deleting the link also crashes.

**Comment by grossmj** [comment]
It seems that not logging Qt messages with log.info() has fixed this issue, at least on my side.

https://github.com/GNS3/gns3-gui/commit/3ddccf40a8d7cd89bdb734e593f5d67a4febc5cc

Let's keep this open until others confirm.

**Comment by grossmj** [comment]
@Linwood-F @AJNOURI  please re-open if you still have the problem on your side. Thanks!
