### ISSUE TITLE
Report Segmentation fault (core dumped) when running Olive12(Not GNS VM mode,win7，64bits)

### ISSUE THREAD

**Issue by angelyouyou** [GNS3/gns3-server#1226]
Report Segmentation fault (core dumped)  when running Olive12(Not GNS VM mode), old GNS3 version can startup ok, new version2.1 can not startup ok.
 
Segmentation fault (core dumped)
BAD_PAGE_FAULT: pid 293 (chown), uid 0: pc 0x8813eaea got a read fault at 0x8052000, x86 fault flags = 0x4
Trapframe Register Dump:
eax: 000007ff ecx: 00000003 edx: 00006e09 ebx: 8815c938
esp: bfb7db40 ebp: bfb7dbb8 esi: 0804b0e0 edi: 08051ffe
eip: 8813eaea eflags: 00080216
cs: 0033 ss: 003b ds: 003b es: 003b
fs: 003b trapno: 0000000c err: 00000004

**Comment by AJNOURI** [comment]
To traceback to community forum question:
https://community.gns3.com/qa/report-segmentation-fault-core-d

**Comment by grossmj** [comment]
Looks like it is Qemu that crashed. We cannot do anything especially with so little information.
