### ISSUE TITLE
[2.1.0dev8] when setting link delay: Error while updating link: bridge 'bridge0' doesn't exist

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1229]
When setting link delay (all devices stopped) ==> NOK

![image](https://user-images.githubusercontent.com/1716020/33097483-a4084190-cf0a-11e7-803b-c6f786e853c2.png)

When setting link delay (all devices running) ==> OK

But in the community forum a report about an error that could have the same root cause:
https://gns3.com/qa/receiving-error-while-trying-to-

If not, I'll make a new issue for it

> Decoding response from http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/settings response 200
> PUT http://192.168.0.146:8000/v2/projects/ba72ed37-9a91-4993-8f6d-8a752f640dc8/links/edaadfcc-4357-4a70-ab9f-57fae81e1abb {'nodes': [{'node_id': '5f3843ce-96eb-40cf-ad97-4ddd6d5b909d', 'adapter_number': 0, 'port_number': 0, 'label': {'text': 'eth0', 'x': 71, 'y': 60, 'rotation': 0, 'style': 'font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;'}}, {'node_id': '8351c346-73f4-4d9d-8795-0a6ef059b765', 'adapter_number': 0, 'port_number': 0, 'label': {'text': 'eth0', 'x': -5, 'y': -1, 'rotation': 0, 'style': 'font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;'}}], 'filters': {'frequency_drop': [0], 'packet_loss': [0], 'delay': [50, 0], 'corrupt': [0], 'bpf': ['']}, 'suspend': False}
> Response error: Error transferring http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/ba72ed37-9a91-4993-8f6d-8a752f640dc8/links/edaadfcc-4357-4a70-ab9f-57fae81e1abb - server replied: Conflict for http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/ba72ed37-9a91-4993-8f6d-8a752f640dc8/links/edaadfcc-4357-4a70-ab9f-57fae81e1abb (error: 206)
> Error while updating link: bridge 'bridge0' doesn't exist: 
> GET http://192.168.0.146:8000/v2/settings {}
> 

---------------

GNS3 version is 2.1.0dev8 
Python version is 3.6.1 (64-bit) with utf-8 encoding
Qt version is 5.8.0
PyQt version is 5.8.2
SIP version is 4.19.2

---------------

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie

---------------

**Comment by grossmj** [comment]
Fixed :+1:

**Comment by AJNOURI** [comment]
Thanks Jeremy!
