### ISSUE TITLE
[version 2.1] Issues communicating between devices on local server and devices on GNS3 VM

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1231]
Reproduced a reported issue on community forum:
https://gns3.com/qa/connect-iou-router-in-gns3-vm-to

-------------------

This is a test with dynamips routers:

- case1:  router on local -to- router on GNS3 VM ==> NOK 
- case2:  router on local -to- router on local ==> OK
- case3:  router on GNS3 VM -to- router on GNS3 VM ==> OK

![selection_007_26_11](https://user-images.githubusercontent.com/1716020/33237452-b8d8d90a-d274-11e7-9b2f-6ceb625e108e.jpg)

case 1: ping fails, checked interfaces UP/UP
![selection_005_26_11](https://user-images.githubusercontent.com/1716020/33237454-cd48c738-d274-11e7-916f-6e9052d4acd6.jpg)

Case1 wireshark on link shows only ARP traffic from local router

![selection_003_26_11](https://user-images.githubusercontent.com/1716020/33237461-e92e4720-d274-11e7-9319-133e8b12acc8.jpg)

Could have the same root problem as here 
https://github.com/GNS3/gns3-server/issues/1181

-----------------
GNS3 version is 2.1.0 (compiled)
Python version is 3.6.3 (64-bit) with utf-8 encoding
Qt version is 5.8.0
PyQt version is 5.8
SIP version is 4.19.5

**Comment by grossmj** [comment]
The local server and the VM must be on the same network. What are the IP addresses for both?

**Comment by AJNOURI** [comment]
Indeed Jeremy @grossmj , both addresses where not in the same network. 
I changed the local server IP to vmnet1 subnet IP.
Thanks.

![image](https://user-images.githubusercontent.com/1716020/33260498-4c87ae56-d360-11e7-8923-b8a4ef8b1698.png)

With all the choices and without any check or warnings, users could easily and silently fall into the same issue.

![selection_003_27_11](https://user-images.githubusercontent.com/1716020/33260674-dfe673f8-d360-11e7-9ade-216475b30026.jpg)


Because already GNS3 VM will default to vmnet1 or the first vbox interface, should we give the user the choice of the local server IP?
If the user choose local server IP in the same hypervisor subnet, the server won't be available to outside gns3 clients.
Otherwise,  it won't be possible to communicate with gns3 vm devices.

Shouldn't we for example default the local server to 0.0.0.0 (all interfaces), this way we avoid the previous mentioned issues?

**Comment by grossmj** [comment]
I have implemented a warning now.

**Comment by AJNOURI** [comment]
Thanks @grossmj
