### ISSUE TITLE
FYI: Alpine new py3-aiohttp 2.3 and shutdown issues

### ISSUE THREAD

**Issue by fcolista** [GNS3/gns3-server#1234]
Hi!
I've successfully upgraded the package of GNS3 2.1.0 on Alpine Linux.
Since Alpine has a different release cycle compared with GNS3, we often end up in having python3 packages too newer that does not met the requirements.

So I need to add a patch to drop some of the requirements...and so far it works (see: https://git.alpinelinux.org/cgit/aports/tree/community/gns3-server/dropped-requirements.patch?id=87775ed37366d80e492edff713c4c12de833f631).
With py3-aiohttp, I had the issue that GNS3 does not shutdown.

I've done another patch to make it work:

```
diff --git a/gns3server/web/web_server.py b/gns3server/web/web_server.py
index 8352134..53a8252 100644
--- a/gns3server/web/web_server.py
+++ b/gns3server/web/web_server.py
@@ -42,8 +42,8 @@ import gns3server.handlers
 import logging
 log = logging.getLogger(__name__)
 
-if not aiohttp.__version__.startswith("2.2"):
-    raise RuntimeError("aiohttp 2.2 is required to run the GNS3 server")
+if not aiohttp.__version__.startswith("2.3"):
+    raise RuntimeError("aiohttp 2.3 is required to run the GNS3 server")
 
 
 class WebServer:
diff --git a/gns3server/web/web_server.py b/gns3server/web/web_server.py
index 8352134..e999c11 100644
--- a/gns3server/web/web_server.py
+++ b/gns3server/web/web_server.py
@@ -101,7 +101,7 @@ class WebServer:
         if self._app:
             yield from self._app.shutdown()
         if self._handler:
-            yield from self._handler.finish_connections(2)  # Parameter is timeout
+            yield from self._handler.shutdown(2.0)  # Parameter is timeout
         if self._app:
             yield from self._app.cleanup()
```

Just posting here FYI, if you think that might be useful.
Thanks for this great software!

.: Francesco

**Comment by athmane** [comment]
I had similar issues with Fedora 27+ packages, I end up forcing older aiohttp in deps since I was not sure if it impacts other gns3 functionalities (beside shutting down).

**Comment by fcolista** [comment]
@athmane Yes, I don't know the backside too...but so far I didn't find other errors.
I should do a source audit about where aiohttp functions are used, but it's a huge work.
I think that @noplay or @grossmj have a better clue of the possibile caveats.
.: Francesco

**Comment by noplay** [comment]
I think it's fine

**Comment by ziajka** [comment]
Hi @fcolista,
Thanks for your help. We already have PR for an update, but it doesn't behave stable and needs further testing. Ref. https://github.com/GNS3/gns3-server/pull/1205
Kindest regards,
Dominik

**Comment by fcolista** [comment]
@ziajka thanks for the reply. Would you mind to explain what does in mean that does not behave stable?
Just a personal observation: aio-lib have released 5 stable versions of aiohttp since 20 Oct..
wondering how they can change the code so much to make it not fully compatible.
.: Francesco

**Comment by ziajka** [comment]
Hi Francesco,

During I was working on other task I tried to upgrade aiohttp to the newer
version. I don't remember exact issue, however something was wrong. It
could be wrong on our side. We will look on that in the next weeks.

Thanks and cheers,
Dominik

**Comment by ziajka** [comment]
It seems to be fine with 2.3.2, ref. https://github.com/GNS3/gns3-server/pull/1205/commits/a7412d1c879920c3b2c2871763aafbe6836d1ed7
