### ISSUE TITLE
Need to manually upgrade ubridge, when updating GNS3 from 2.0.3 to 2.1.0 in Mint

### ISSUE THREAD

**Issue by AJ-Coleman** [GNS3/gns3-server#1235]
In Mint 18.2, I can normally just upgrade GNS3 by running "sudo apt-get install gns3-gui gns3-server". 
Upgrading from 2.0.3 to 2.1 this time, I also needed to run "sudo apt-get install ubridge", in order to have the latest version of ubridge installed

**Comment by ziajka** [comment]
Hi @AJ-Coleman ,
Thanks for reporting. This should be fixed now.
Cheers,
Dominik
