### ISSUE TITLE
Legacy random error

### ISSUE THREAD

**Issue by AJ-Coleman** [GNS3/gns3-server#1236]
This has been a recurring thing since version 2.0 in Linux Mint 18, but I would randomly see one or more of the following messages in the gns3 console, when adding/deleting links or devices in a topology:

"No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/5"

In 2.1, it still occurs, but is a green pop-up on the right-side of the screen, which disappears after 10 seconds.  

Those DBus messages didn't always cause an issue with a running topology, unless it occurred alongside the dreaded "Waiting for 127.0.0.1:3080" message bar that would timeout after 3-5 minutes.

**Comment by grossmj** [comment]
They should not appear anymore in our next version (2.1.1).
