### ISSUE TITLE
[2.1 Release] - Fresh Install comes without gns3-iou package

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-server#1237]
Hi,

Not sure if this has already been addressed but I have a fresh installation of GNS3 2.1 on an Ubuntu 17.10 server, everything works fine except for IOU, i used to always build GNS3 from source or using pip3 but now the package gns3-iou for ubuntu is no longer available. 

Is there any plans to add this back in? Or is there another way of getting IOU support back?

Thanks in advance.

**Comment by ziajka** [comment]
Hi @gcasella,
We have just released IOU for Artful.
Hope it helps you.
Cheers,
Dominik
