### ISSUE TITLE
Creating multiple IOU nodes at once (shift+drag in GUI) assigns the same application id

### ISSUE THREAD

**Issue by ddragic** [GNS3/gns3-server#1239]
From community forum: https://gns3.com/qa/gns3-error-could-not-create-iol-

Looks like a regression from commit 6aa2afc. Adding IOU nodes one by one works, but adding many nodes at once (shift+drag) assigns the same application ID to all (or most) of the nodes which prevents them from running.

Probably a race condition, at the time of application id assignment the other nodes aren't yet created (get_next_application_id in compute/iou/utils/application_id.py).

**Comment by cioby23** [comment]
Indeed I confirm this bug. After adding and trying to start all IOL nodes using the Start/Resume All nodes button the following error popped up **could not create IOL bridge 'IOL-BRIDGE-513': PID 13200 already has a lock on ID 513: uBridge version 0.9.14 running with libpcap version 1.8.1**
Then I checked the project folder and the NETMAP file for each IOU node had the same ID number 513.

**Comment by grossmj** [comment]
Fixed, this was due to a concurrency problem.

**Comment by vint66** [comment]
Hi, Jeremy

I see same issue on 2.1.3 but for two different projects (it wasn't duplicated, it is simply two not related projects but created in 2.1.0 or .1 version). As result I can’t run two projects at the same time.

Project 1:
514:0/0    2:0/0
514:0/1    2:0/1
514:0/2    2:0/2

Project 2:
514:0/0    2:0/0
514:0/1    2:0/1
514:0/2    2:0/2

**Comment by grossmj** [comment]
I confirm, it is not possible to run 2 different projects containing IOU nodes on the same server.

There are IOU ID conflicts: "could not create IOL bridge 'IOL-BRIDGE-519': PID 15119 already has a lock on ID 519: uBridge version 0.9.14 running with libpcap version 1.7.4\nHypervisor TCP control server started (IP 172.16.1.1 port 52919)."

**Comment by grossmj** [comment]
Should be good now.

**Comment by kristoferus75** [comment]
i have gns3 2.1.4 with this fixes included but i get already this error :-(

**Comment by grossmj** [comment]
I cannot replicate the issue. What error message do you see? Can you describe the steps leading to the problem?

Thanks!

**Comment by kristoferus75** [comment]
Hi !

i have upgraded my lxc container alpine linux with gns3 from 2.0.4 to 2.1.4 and after that if i opened my gns3 map i get this error :
   
could not create IOL bridge 'IOL-BRIDGE-526': could not get lock on /tmp/netio1000/526: uBridge version 0.9.14 running with libpcap version 1.8.1
Hypervisor TCP control server started (IP 127.0.0.1 port 45965).

Thanks !

**Comment by grossmj** [comment]
Do you get the exact same error every time? Have you tried to reboot? Please check there aren't remaining uBridge or IOL processes running before you start GNS3.

**Comment by kristoferus75** [comment]
yes i have rebootet the lxc container but alwas the same error :-(

i see no ubridge processes

**Comment by grossmj** [comment]
Any process starting with i86bi_linux?

**Comment by kristoferus75** [comment]
yes if i start ./i86bi-linux-l3-adventerprisek9-15.2.2.15T.bin 555
the router start but in gns3 i habe no connectivity to other router !
