### ISSUE TITLE
[v2.1] (error: 206) Could not find free port for the uBridge hypervisor

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1244]
In a new installation, I am running everything on 2 remote servers:

When trying to start a topology of 2 containers (installed on the main remote server 192.168.0.138), it throws:

> [v2.1] (error: 206) Could not find free port for the uBridge hypervisor

> POST http://192.168.0.138:3080/v2/projects/23494ce8-4ff8-4f28-bf84-8e61788ce88a/nodes/start {}
> Response error: Error downloading http://admin@192.168.0.138:3080/v2/projects/23494ce8-4ff8-4f28-bf84-8e61788ce88a/nodes/start - server replied: Conflict for http://admin@192.168.0.138:3080/v2/projects/23494ce8-4ff8-4f28-bf84-8e61788ce88a/nodes/start (error: 206)
> Could not find free port for the uBridge hypervisor: [Errno 99] Cannot assign requested address
> GET http://192.168.0.138:3080/v2/settings {}
> Decoding response from http://admin@192.168.0.138:3080/v2/settings response 200
> GET http://192.168.0.138:3080/v2/settings {}

![selection_001_21_12](https://user-images.githubusercontent.com/1716020/34254470-7fe0d5bc-e64c-11e7-8225-1cd8d033cc7b.jpg)

![selection_011_21_12](https://user-images.githubusercontent.com/1716020/34254581-ff3e8228-e64c-11e7-8f27-50ffd9030879.jpg)

**Comment by grossmj** [comment]
What is the output of `ifconfig`? Has the network configuration changed while running GNS3?

**Comment by AJNOURI** [comment]
Hi Julien,
Just retested with the upgraded v2.1.2 and it works fine.

![selection_003_15_01](https://user-images.githubusercontent.com/1716020/34939922-eff61254-f9ed-11e7-968e-643a6d766828.jpg)

**Comment by grossmj** [comment]
I think there was an issue with the host the first time. Thanks for checking! :+1:
