### ISSUE TITLE
[v2.1] Error while creating link: Attachment (nat) already configured on network adapter 0. Please remove it or allow GNS3 to use any adapter.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1245]
The config is as follow:
- local GNS3 server
- GNS3 VM on ESXi as remote server

When trying to connect VMware VM to a switch installed on either local server or remote ESXi GNS3 VM I get this error:
Error while creating link: Attachment (nat) already configured on network adapter 0. Please remove it or allow GNS3 to use any adapter.

Same behavior with containers (gns3/openvswitch)

![selection_012_27_12](https://user-images.githubusercontent.com/1716020/34385769-32390874-eb25-11e7-8299-a9d2754b2498.jpg)

![image](https://user-images.githubusercontent.com/1716020/34385971-9a7135f0-eb26-11e7-9ab6-dd7a67b01fc6.png)

------------

GNS3 version is 2.1.0 (compiled)
Python version is 3.6.3 (64-bit) with utf-8 encoding
Qt version is 5.8.0
PyQt version is 5.8
SIP version is 4.19.5

GNS3 installed on Windows server 2012 R2
VMware 12

**Comment by AJNOURI** [comment]
!!! This happens only with VMware VM.!!! 
qemu and docker containers are linked normally.

**Comment by grossmj** [comment]
This is a protection to avoid overwriting existing adapter settings for a VMware VM. You can change this behaviour by ticking "Allow GNS3 to override non custom VMware adapter".

![node_properties](https://user-images.githubusercontent.com/4752614/34662181-04873c6a-f44f-11e7-97be-052a8ca41695.png)

**Comment by grossmj** [comment]
@AJNOURI Please re-open if this doesn't work for you.

**Comment by adarsh3610** [comment]
Error while creating link: Attachment 'nat' is configured on network adapter 0. Please stop VMware VM 'Kali-Linux-2019.4-vmware-amd64-1' to link to this adapter and allow GNS3 to change the attachment type.

**Comment by NetworkForce** [comment]
My issue was with "nat" connection.So,I found a way to resolve the issue by editing *.vmx file of GNS3 project and open it in Note++ then  putting # before lines. Like lines below:
ethernet1.connectiontype = "nat"
#ethernet1.wakeonpcktrcv = "FALSE"
#ethernet1.addresstype = "generated"
#ethernet1.pcislotnumber = "38"

**Comment by Myriuss** [comment]
how can I enable it on mac please? I can't find it on my switch configuration
