### ISSUE TITLE
Allow to accept a different md5 hash than the one in the appliance file.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1246]
Lot's of issues related to md5sum required in the appliance files and the md5sum of the files the users use (Whatever the source).

Can we somehow allow during appliance import to change the md5sum? Of course we can Warn the users of the security risks to have a hash different fro the original.

**Comment by ziajka** [comment]
Ref. https://github.com/GNS3/gns3-gui/pull/2404

@AJNOURI above is PR with this change. During import of appliance you have "Allow custom files" checkbox (upload files time). However there is a question. Is it more beneficial than just creation new version of appliance? Potentially it can be really risky to upload file with different MD5.

**Comment by ziajka** [comment]
@grossmj your thoughts are welcome here.

**Comment by grossmj** [comment]
> However there is a question. Is it more beneficial than just creation new version of appliance? Potentially it can be really risky to upload file with different MD5.

I think it is fine with a warning. The problem with creating new version of an appliance is it takes some time and knowledge, this is easy for us but not necessarily for beginners.

**Comment by AJNOURI** [comment]
Sorry @ziajka for the late reply.
I don't know for what reasons, lots of the appliance md5 hashes doesn't match, eventhough the files are the originals.
So this will make it easier for beginners to try these appliances without the need to dig into creating new appliances, we hope to balance the security risk with the warning.

**Comment by altmind** [comment]
I dont understand this dialog "This is not the correct file. Do you want to accept it at your own risk?"
Clicking yes does not import the image, so why asking? Is it a gui problem?

GNS 2.1.21
