### ISSUE TITLE
GNS3-API: GET method not implemented for specific link or drawing

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1249]
While it's possible to get the data of a specific node or project, it's not possible for links and drawings.

For the API endpoints [/v2/projects/{project_id}/links/{link_id}](http://api.gns3.net/en/latest/api/v2/controller/link/projectsprojectidlinkslinkid.html) and [/v2/projects/{project_id}/drawings/{drawing_id}](http://api.gns3.net/en/latest/api/v2/controller/drawing/projectsprojectiddrawingsdrawingid.html) no GET method is defined, only PUT and DELETE. Workaround is to get all links / drawing. Especially for drawings this can be quite inefficient as drawing can be large and having to load unneeded ones leads to a big overhead.

**Comment by ehlers** [comment]
Found another workaround (tested only with drawings): Use the PUT method with empty changes. But that triggers the project modification event.

**Comment by grossmj** [comment]
Fixed by PR https://github.com/GNS3/gns3-server/pull/1252
