### ISSUE TITLE
Class oriented GNS3 labbing

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1250]
The GNS3 server and the GUI are oriented for single user access.
Things get more complicated if the system is used for a class of student or a group of employers having access to the same topology, but through different projects.

What I have in mind is, the possibility to have a template project that can be duplicated into as many users as needed.
Maybe a very simple system to manage users: create, edit (username + password).
The admin can take a template project and make it available to users (through checklist)
Each user, will have to access the lab using his/her username+password.
After working on the project, the user can reload the template to reset all changes if needed.

That's only a blueprint, other suggestions are welcome.

What is your take guys?

**Comment by CapnCheapo** [comment]
I share a GNS3 server with about 6 other users at my workplace.  I like the idea of users and private/templated projects, but I also like the ability for multiple users to interact with the same project at the same time-- that is a feature we use often.

**Comment by srieger1** [comment]
Great idea! We have similar problems using GNS3 in our network lab at Fulda University of Applied Sciences. If you like, you can take a look at the interim solution we developed that acts as a proxy in front of GNS3 backends: https://github.com/srieger1/gns3-proxy. We're also thinking about further extensions to use GNS3 in classroom/course environments.

**Comment by grossmj** [comment]
We have started work for this on branch 3.0

**Comment by grossmj** [comment]
RBAC support has been added.
