### ISSUE TITLE
container install : ssl.CertificateError: hostname 'raw.githubusercontent.com' doesn't match 'dm1cme.on.xxxx.xx' 

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1262]
From GNS3 community forum:
https://gns3.com/qa/-certificateerror-mismatch-while

----------

> Hi,
> NOT able to install the Nwetwork Automation Appliance from my office. At home it work so I supposed methodology is OK but at the office I have the following :
> File "C:\Python36-x64\lib\ssl.py", line 331, in match_hostname
> ssl.CertificateError: hostname 'raw.githubusercontent.com' doesn't match 'dm1cme.on.xxxx.xx' 
>  
> So I wonder how to solve this problem as I cannot change the DNS information?
>  
> By the way, I also was able to add the Ansible appliance. So again methodology is not the bug for the appliance. I am conscient the requirements are quite different.
> I have on my workstation, 3 pythons directory: Python27, Python34 and Python36  under my C Drive to follow some courses. 
>  
> Any clue somebody?

-----------

**Comment by ziajka** [comment]
Ref. https://github.com/GNS3/gns3-gui/pull/2410/commits/c971cef31b2800b0515cb69b0eb93a688619fd74
