### ISSUE TITLE
Change the Base MAC for duplicated IOS device

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1264]
From community forum:
[https://gns3.com/qa/base-mac-not-incremented-when-du](https://gns3.com/qa/base-mac-not-incremented-when-du)

---------
Even though, this can be done manually on the dupicated router, it would be great to generate a new one automatically upon duplicate:

**Comment by grossmj** [comment]
Fixed, thanks!

**Comment by AJNOURI** [comment]
Thanks alot @grossmj.
