### ISSUE TITLE
Issues project opening & export after power down: cannot access files

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1265]
From community forum:
https://gns3.com/qa/save-project-2

GNS3 v2.0.3

----------------------
Hi.
I have GNS3 and Dynamips work on VM.
How I can correctly save project with router configs ?
 

> **Issue apers when power down on PC . Files on VM is corrupted.** And after open project I have error:
> Cannot access the private-config /opt/gns3/projects/78f49894-3ef1-46e0-bf8b-73a6fcfa9928/project-files/dynamips/3ed72e1b-7890-4a54-8f3b-22a3e44cb0d8/configs/i1_private-config.cfg: [Errno 2] No such file or directory: '/opt/gns3/projects/78f49894-3ef1-46e0-bf8b-73a6fcfa9928/project-files/dynamips/3ed72e1b-7890-4a54-8f3b-22a3e44cb0d8/configs/i1_private-config.cfg'

 
If I do export/import project I have this error:
 

> Can't move C:\Users\oleksii.zakharenko\GNS3\projects\VoliaCore\project-files\dynamips\dynamips_i8_stdout.txt: [WinError 32] process cannot have access to file 'C:\\Users\\oleksii.zakharenko\\GNS3\\projects\\VoliaCore\\project-files\\dynamips\\dynamips_i8_stdout.txt'

**Comment by grossmj** [comment]
@404Ghost99 is this issue blocking for you?

**Comment by 404Ghost99** [comment]
yes, this issue happen in every when i'm starting to export my gns3 lab

also, i found this error when i'm starting to open gns3 at the first time after reboted my computer "Timeout after 10 seconds for request http://user@127.0.0.1:3080/v2/version"
if i use gns doctor to find the probles is "WARNING The vmrun executable could not be found, VMware VMs cannot be used", meanwhile i didn't use any gnsvm or another vm like vbox / vmware, or whatever vm.. i'm ruuning gns3 in my local server.
my system in use is Ubuntu 16.04.5 LTS. Sorry for my bad english.
Thanks.

**Comment by iboygp** [comment]
found similar issue also, whenever i tried to export to portable project (which i always choose No in 'include base image to project?'), the portable filesize is as big as a portable project with images.

GNS3 2.1.9, running in Linux Mint Mate 18 64bit.

**Comment by grossmj** [comment]
@iboygp please look inside the portable project using a zip tool and check if the images are there.

Thanks.

**Comment by iboygp** [comment]
@grossmj hi Jeremy, i tried your suggestion and i found that the file consists of a big size of docker folder, not the IOS/IOU images

i use AJnouri's nginx container to emulate webserver in that project, so maybe i should switch to Toolbox appliance.

thanks for your reply.
