### ISSUE TITLE
[2.1.3] ImportError: cannot import name 'idnadata'

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1266]
Multiple reports in gns3.com about "ImportError: cannot import name 'idnadata'" in GNS3 application for Windows and OS X, maybe an issue with cx_Freeze?

Report from Alex Z, Jeremy Scantlebury, Marão Neto and gustavo pereira in https://www.gns3.com/discussions/gns3-crashing-at-startup-on-maco
https://www.gns3.com/qa/error-on-gns3server-exe-start-im
https://www.gns3.com/qa/gns3-not-connecting-to-a-local-s

**Comment by ehlers** [comment]
Adding package idna to build_exe_options should fix this, see https://github.com/anthony-tuininga/cx_Freeze/issues/228

**Comment by AJNOURI** [comment]
![selection_004_20_01](https://user-images.githubusercontent.com/1716020/35185671-6cb2fbd6-fe08-11e7-8de6-f621acf60f30.jpg)


![selection_005_20_01](https://user-images.githubusercontent.com/1716020/35185676-71f16b3c-fe08-11e7-860e-9117190e4b34.jpg)

**Comment by grossmj** [comment]
I think this happened because we unlocked yarl and multidict versions in https://github.com/GNS3/gns3-server/commit/34acb1f185a9d9a1869118a45ff554e73dc6f747

That is unfortunate, looks like we will have to release 2.1.4 very soon.

**Comment by grossmj** [comment]
Adding the "idna" to packages fixed the problem.

**Comment by grossmj** [comment]
Decided to keep version 2.1.3 since the problem was due to a packaging problem. Please download & install again.

**Comment by Michael-List** [comment]
@grossmj Just installed the "new" 2.1.3 version, it works like a charm. Thanks for the quick fix!
