### ISSUE TITLE
Code : Canonical OUI for QEmu MAC addresses

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#1267]
Hi

I try to have an uniq OUI for MAC Address of QEmu VM (for DHCP Server, for example).

I believe that the OUI for MAC Address of QEmu is "52:54:00" : [QEmu code](https://github.com/qemu/qemu/blob/master/net/net.c)

I propose to change in : gns3server/compute/qemu/qemu_vm.py
in the function :  def mac_address(self, mac_address):
replace : 
self._mac_address = "00:%s:%s:%s:%s:00" % (self.project.id[-4:-2], self.project.id[-2:], self.id[-4:-2], self.id[-2:])
by :
self._mac_address = "52:54:00:%s:%s:%s" % (self.id[-10:-8], self.id[-8:-6], self.id[-6:-4])

I use the ID of each VM to have an uniq MAC address

**Comment by grossmj** [comment]
I am ok for changing the OUI value however why don't you want the addresses to be sequential?

52:54:00:42:42:01
52:54:00:42:42:02
52:54:00:42:42:03

**Comment by Raizo62** [comment]
I don't like "01", "02", "03" because it is not realistic : my students risk to think that mac address are too linear, and that the last bytes are always 01, 02, 03.

End here, with 2 octets (42:42) you increase probability that 2 VM have the same MAC address. 
(and also, i hide a little 01 02 03 ;-) )

**Comment by grossmj** [comment]
> I don't like "01", "02", "03" because it is not realistic : my students risk to think that mac address are too linear, and that the last bytes are always 01, 02, 03.

I don't understand why you say it is not realistic, for instance take a Cisco switch and you will see that mac addresses are sequential.

```
Switch#show interfaces | include address
  Hardware is Fast Ethernet, address is 000f.24b7.1400 (bia 000f.24b7.1400)
  Hardware is Fast Ethernet, address is 000f.24b7.1402 (bia 000f.24b7.1402)
  Hardware is Fast Ethernet, address is 000f.24b7.1403 (bia 000f.24b7.1403)
  Hardware is Fast Ethernet, address is 000f.24b7.1404 (bia 000f.24b7.1404)
  Hardware is Fast Ethernet, address is 000f.24b7.1405 (bia 000f.24b7.1405)
...
``` 

> And here, with 2 bytes (42:42) you increase probability that 2 VM have the same MAC address.
(and also, i hide a little 01 02 03 ;-) )

It was just an example. Those 2 bytes will be randomized.

**Comment by Raizo62** [comment]
> I don't understand why you say it is not realistic, for instance take a Cisco switch and you will see that mac addresses are sequential.

It is truth for Cisco.
But, on desktop/laptop, this is rarely truth. And i use QEmu to emulate them :-)

> It was just an example. Those 2 bytes will be randomized. 

Yes, i have write "(42:42)" to show more precisely theses 2 bytes.
I wanted to say that with 3 randomized bytes, we have less probability to have same MAC address than with 2 randomized bytes.

**Comment by grossmj** [comment]
> It is truth for Cisco. But, on desktop/laptop, this is rarely truth. And i use QEmu to emulate them :-)

The problem is that we use Qemu to emulation IOSv and many other Cisco appliances... ;)

**Comment by Raizo62** [comment]
> The problem is that we use Qemu to emulation IOSv and many other Cisco appliances... ;)
 
Yes, it is also truth.
I won't ask you a special function to each case ;-)
Choose, i will not battle for randomize the last byte : i prefer that you implement the detection of plugged/unplugged interface on QEmu ;-)

**Comment by grossmj** [comment]
All good, we won't change anything then :+1:

**Comment by Raizo62** [comment]
Nothing ? and the 3 first bytes of the mac address (52:54:00:) ?

**Comment by grossmj** [comment]
We could do it but this would leave only 2 bytes that can be randomised (52:54:00:xx:xx:01, 52:54:00:xx:xx:02 etc.), this may not be enough.

**Comment by Raizo62** [comment]
Yes...it is why i use also the last byte :-(
Or to fixe only 52:54 : it is not really QEmu but it is more predictive

**Comment by grossmj** [comment]
What about just 52? ;) Now I wonder what we will achieve by changing this, do you want quickly recognise  MAC addresses that come from Qemu VMs?

**Comment by Raizo62** [comment]
> do you want quickly recognise MAC addresses that come from Qemu VMs?

Yes. In the case where these QEmu VMS are connected directly with the real network. 
For example, real DHCP server can provide IP with low lease (if the VM is stopping brutally)
The MAC address of VirtualBox VM are beginning by 08:00:27

**Comment by grossmj** [comment]
I think changing the first byte to 52 should be enough and would allow you to recognise MAC addresses belonging to Qemu VMs.

Using https://www.wireshark.org/tools/oui-lookup.html I can see that there could be a "conflict" with computers using Realtek 8029 based PCI cards (52:54:AB) however the chances are low. I think we can ignore Novell ;)

```
52:54:00 RealtekU	Realtek (UpTech? also reported)
52:54:4C Novell20	Novell 2000
52:54:AB RealtekA	REALTEK (a Realtek 8029 based PCI Card)
```

**Comment by Raizo62** [comment]
> What about just 52? ;)

I believed that you jokes ;-)
You have right (wireshark), in this case, to fix also the second byte will not change nothing...

**Comment by grossmj** [comment]
Okay, all good now :+1:
