### ISSUE TITLE
Replace asyncio.async with ensure_future because of deprecation 

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-server#1269]

**Comment by grossmj** [comment]
This was introduced in Python 3.4.4, therefore we must prevent the server to run with a lower version here: https://github.com/GNS3/gns3-server/blob/2.1/gns3server/run.py#L227

**Comment by ziajka** [comment]
Good point @grossmj

**Comment by ehlers** [comment]
Ubuntu 14.04 (trusty) comes with Python3 v3.4.3. The requirement for 3.4.4 excludes trusty, the GNS3VM needs an update to at least Ubuntu 16.04 (xenial) with Python3 v3.5.2.

**Comment by ziajka** [comment]
Thanks @ehlers! In case we won't update VM base image then I revert changes. However it might be worth to run on Xenial.

**Comment by ehlers** [comment]
At the time of the release of v2.2 the next ubuntu LTS version 18.04 should be available. So I think it's reasonable to remove support for 14.04 and upgrade the GNS3VM to 16.04. But there might be some reasons to keep support for 14.04.

**Comment by ziajka** [comment]
Exactly, as long as asyncio.async is not officially dropped then it's not really necessary to drop 3.5, we may always use this approach: 

https://github.com/aio-libs/aioredis/issues/101

Tursty is also in LTS for this year only:

https://www.ubuntu.com/info/release-end-of-life

So far I will leave it as it is, when we get too many issues during the development of this release then we revert this change.
