### ISSUE TITLE
Error when pulling docker container: Docker has returned an error: 500

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1272]
From the community forum:
https://gns3.com/qa/windows-ubuntu-docker

This error is generally related to the existing of a proxy which disrupt SSL; 
In this case the user doesn't haev a proxy.  Must be something else.

Any ideas?  

-------------------

- v2.1.2 , v2.1.3
- Windows

> Docker has returned an error: 500 Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by ziajka** [comment]
User has reported that problem is solved: https://gns3.com/qa/windows-ubuntu-docker
