### ISSUE TITLE
debian package should depends on xterm

### ISSUE THREAD

**Issue by dfroger** [GNS3/gns3-server#1273]
I installed `gns3` and `debian 9` using `apt install gns3`.

Opening a console on a switch silently failed, because `xterm` was not installed.

Would be nice to have an error message too, on the console or a pop-up.

Thanks!

**Comment by grossmj** [comment]
We won't add xterm as a dependency for our debian package however an error message will be show in our next release when xterm or any other terminal program cannot be executed: https://github.com/GNS3/gns3-gui/commit/42a4c89f206e1fe558c8e88525b826acda729583
