### ISSUE TITLE
Issue with BPF filter

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1285]
https://gns3.com/qa/-request-documentation-on-bfd-fo

**Comment by ehlers** [comment]
Tested with BPF filter "icmp" with Dynamips, IOU, QEMU (IOSv) and Docker devices.
![bpf](https://user-images.githubusercontent.com/896406/35739183-16975ee4-0831-11e8-9204-c700ae1c5218.png)
Issue can be reproduced with IOU, the other VMs are working as expected.

**Comment by grossmj** [comment]
I was suspecting IOU, thanks for checking :+1:

**Comment by jhonnyx82** [comment]
Thank you Jeremy (here the original poster in gns3.com).

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/ubridge/commit/fc400ed3c2ccb9f1e55f5d2bee80a73069f87d41

We will have to release uBridge 0.9.14
