### ISSUE TITLE
version 2.1.3

### ISSUE THREAD

**Issue by ADRIyas** [GNS3/gns3-server#1287]
```
=> Error while getting appliances list: Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 195, in control_schema
  File "C:\Python36-x64\lib\asyncio\coroutines.py", line 210, in coro
  File "./gns3-server\gns3server\handlers\api\controller\appliance_handler.py", line 51, in list
  File "./gns3-server\gns3server\web\response.py", line 104, in json
  File "./gns3-server\gns3server\controller\appliance.py", line 84, in __json__
KeyError: 'name'
```
Running in ...
- Windows 8.1
- 64bit

Thanks!

**Comment by grossmj** [comment]
Fixed, this will work in version 2.1.4.

**Comment by ADRIyas** [comment]
I cannot get this version 2 working. I reverted to using 1.3.1 which is working fine.
Appreciate for the time you spent on this. But will try some other time.

More power to GNS3!

**Comment by ADRIyas** [comment]
Noticed that everything its in GNS3 folder including the roaming. What I tried is installing it on a different folder (GNS3_2 in my case) which was asked during the installation.
Except for the Roaming folder that its still GNS3. And its getting/using the my existing GNS3 1.3.1.
Though, this might cause the issue?

Thanks again.

**Comment by grossmj** [comment]
Yes this is the issue. You should not use the roaming folder to install GNS3, this folder contains all GNS3 settings, whatever the version.

A file in %APPDATA%\GNS3 contains invalid data that made the error your reported. You can delete this directory before trying version 2.1.3 but make a backup in case you would like to go back to version 1.3.1.

**Comment by ADRIyas** [comment]
Sorry for the trouble sir. Its working. Cause was the folder probably the roaming folder. Its getting my old 1.3.13 folder and base folder under my windows users folder.

Its possible to when you choose different folder installation (ex. GNS3_2), it also changes the other folders to GNS3_2?

Thank you again. And am very sorry for the trouble.
