### ISSUE TITLE
Require uBridge 0.9.14 on Linux

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1288]
Reminder: update https://github.com/GNS3/gns3-server/blob/2.1/gns3server/ubridge/hypervisor.py#L141 (only for Linux) once deb package is released https://github.com/GNS3/gns3-build/issues/90

uBridge 0.9.14 allows packet filters to work for IOU nodes.

**Comment by ziajka** [comment]
voilà!

**Comment by grossmj** [comment]
Thanks. Fixed by https://github.com/GNS3/gns3-server/commit/a0f2dd374ed12e30b12979f6461ec6686abf317d
