### ISSUE TITLE
Cannot open a project: Parse error unexpected quote

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1290]
This happens only with this project. Nothing special with this one: a couple of connected and configured IOSv routers, the project is closed properly.

But cannot open it now:

![selection_002_10_02](https://user-images.githubusercontent.com/1716020/36061621-af35fdaa-0e5c-11e8-91f9-f98b3ff16dd7.jpg)

> 2018-02-10 11:46:14 DEBUG http_client:645 Response error: Error transferring http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/load - server replied: Conflict for http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@192.168.0.146:8000/v2/projects/load (error: 206)
> 2018-02-10 11:46:14 CRITICAL topology.py:222 Parse error: unexpected quote: 
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 11, in <module>
>     load_entry_point('gns3-gui===2.1.4dev1-a1cd34d', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4dev1_a1cd34d-py3.6.egg/gns3/main.py", line 293, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4dev1_a1cd34d-py3.6.egg/gns3/qt/__init__.py", line 272, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4dev1_a1cd34d-py3.6.egg/gns3/http_client.py", line 675, in _processError
>     callback(json.loads(body), error=True, server=server, context=context)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4dev1_a1cd34d-py3.6.egg/gns3/qt/__init__.py", line 272, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4dev1_a1cd34d-py3.6.egg/gns3/project.py", line 447, in _projectOpenCallback
>     self.project_creation_error_signal.emit(result["message"])
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4dev1_a1cd34d-py3.6.egg/gns3/topology.py", line 222, in _projectCreationErrorSlot
>     QtWidgets.QMessageBox.critical(self._main_window, "New project", message)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4dev1_a1cd34d-py3.6.egg/gns3/qt/__init__.py", line 117, in critical
>     LogQMessageBox._get_logger().critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> 

-------------------

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie

GNS3 version is 2.1.4dev1 
Python version is 3.6.1 (64-bit) with utf-8 encoding
Qt version is 5.8.0
PyQt version is 5.8.2
SIP version is 4.19.2

Linux gns3-iouvm 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

Debugging inf.
[error-opening-existing-project.zip](https://github.com/GNS3/gns3-server/files/1713310/error-opening-existing-project.zip)

**Comment by ziajka** [comment]
Hi @AJNOURI,
Thanks for reporting this. Can you maybe open this project in 2.1.3 version (not dev and not installed via cloning repo) with enabled "Send anonymous crash reports"? This will make that I have full stack trace what is happening there. In case this might be an issue, please send me project if possible (only definition of the project without images, etc.). 
Many thanks!

Cheers,
Dominik

**Comment by AJNOURI** [comment]
Using the following commands:
```
sudo add-apt-repository ppa:gns3/ppa
sudo apt-get update
sudo apt install gns3-gui
```

installs v2.0.3 version

![selection_004_16_02](https://user-images.githubusercontent.com/1716020/36303215-a8ca60b0-130b-11e8-9f3c-1a829a982382.jpg)
So I had to install it with clone:

```
git clone  https://github.com/GNS3/gns3-server
cd gns3-server
git tag -l
git checkout tags/v2.1.3
sudo python3 setup.py install

cd ~
git clone  https://github.com/GNS3/gns3-gui
cd gns3-gui
git tag -l
git checkout tags/v2.1.3
sudo python3 setup.py install 
```

And got the same result:
![selection_005_16_02](https://user-images.githubusercontent.com/1716020/36303868-eb4bb2d4-130d-11e8-9dda-c742757ede98.jpg)

With the option of crash reporting enabled:
![selection_007_16_02](https://user-images.githubusercontent.com/1716020/36303884-fcc487b6-130d-11e8-8d95-1ae971236e67.jpg)

**Comment by ziajka** [comment]
Hi @AJNOURI ,

Thank you!

Do you have 32-bit system? (re. v2.0.3 is only available). Please send me an output of:
`lsb_release -a`
and
`uname -a`

Are you able to send us a project (developers@gns3.net) ? It will speed up debugging.

Cheers,
Dominik

**Comment by AJNOURI** [comment]
Hi @ziajka ,
I already included them in the 1st report. I have a 64-bit system
I 've sent the zipped project directory. I couldn't export because the project cannot be opened:

**Comment by ziajka** [comment]
Hi @AJNOURI,
Thank you, It's not necessary to export it, enough is to send file from ~/GNS3 (for example), with .gns3 extension (without project-files directory).

**Comment by AJNOURI** [comment]
Hi @ziajka,
Here is the file in case you didn't receive it by email:
[eigrp1.zip](https://github.com/GNS3/gns3-server/files/1787514/eigrp1.zip)

**Comment by ziajka** [comment]
Note for us: Issue is with ubridge hypevisor, suggested solution:

- when filter is wrong, hypervisor ignores it and sends on output the warning (like prefixed: "Warning: ignoring filter 'aaa' due to: ")
- we can monitor output for pattern: "Warning: (.*)"
- send warning to the user

**Comment by grossmj** [comment]
@AJNOURI Now we are ignoring invalid BPF filters, you should be able to open your project.
