### ISSUE TITLE
Request to update putty from 0.62 to 0.70

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1293]
From the community forum:
https://gns3.com/qa/putty-outdated

-----------

After installing GNS3 version 2.1.3 Putty versie 0.62 is installed in the GNS3 folder.
 
The last version of Putty is versie 0.70.
 
When do you update the version of Putty?

**Comment by ziajka** [comment]
Seems to many things and questions are involved.

**Comment by grossmj** [comment]
This is a customize version for GNS3, see the about dialog in Putty

**Comment by ziajka** [comment]
Thanks @grossmj, exactly this part brings the most questions ;) If it is customized it means it was necessary to use different version and probably we cannot replace this binary.

**Comment by ziajka** [comment]
We won't update this as it's customized version and can be hard to merge changes (we cannot use directly the latest version), but perhaps we will come with different solution.
