### ISSUE TITLE
aiohttp 3.0.1 timeout comatibility

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-server#1296]
Ref. https://github.com/GNS3/gns3-server/issues/463

**Comment by grossmj** [comment]
We need to drop Python 3.4 to close this issue.

**Comment by grossmj** [comment]
Or maybe using async_timeout.timeout could be enough.

**Comment by grossmj** [comment]
aiohttp.Timeout has been removed from aiohttp version >= 3.x. Using async_timeout.timeout solved this issue.
