### ISSUE TITLE
NAT node not working in Ubuntu 16.04 localhost

### ISSUE THREAD

**Issue by adriano-pinaffo** [GNS3/gns3-server#1306]
Hello, Can anyone let me know why my nat node is not offering IP (DHCP Offer) to my client (R1) in my GNS topology? My simple topology is enclosed (with interface config and packet capture), but basically it's just my R1, fastethernet 0/0 connected to NAT Node.
The interface configuration is
```
ip address dhcp
duplex auto
speed auto
no shut
```

![screenshot from 2018-02-26 23-02-02](https://user-images.githubusercontent.com/28174227/36707842-d104b2ce-1b4e-11e8-95e5-39d73936ed81.png)

**Comment by grossmj** [comment]
I do not have any issue on my side. Maybe there is a problem with libvirt. Please can you type the following commands and post the outputs?

```
$ ifconfig virbr0
virbr0    Link encap:Ethernet  HWaddr 6a:02:7a:b3:76:4a  
          inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2287 (2.2 KB)  TX bytes:1566 (1.5 KB)
```


```
$ brctl show
bridge name	bridge id		STP enabled	interfaces
docker0		8000.02426f45a822	no		
virbr0		8000.6a027ab3764a	yes		gns3tap0-0
```

Thanks!

**Comment by grossmj** [comment]
@adriano-pinaffo ping

**Comment by grossmj** [comment]
No reply from OP, I assume an issue or conflict with libvirt.
