### ISSUE TITLE
GNS3 2.1.3 Crashing on startup

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1311]
From community forum:
[https://gns3.com/qa/gns3-2-1-3-crashing-on-startup](https://gns3.com/qa/gns3-2-1-3-crashing-on-startup)

---------------
 
I'm having a problem with GNS3 2.1.3 crashing on startup on my Intel NUC.
 
It's a clean install of Windows 10 professional with GNS 2.1.3 and VMware Workstation 14.0.0 running the GNS3 VM.
 
Below are the two entries from event log:
 
Entry 1:
 

> Faulting application name: gns3.exe, version: 2.1.3.0, time stamp: 0x5920c4b7
> Faulting module name: LIBEAY32.dll, version: 1.0.2.4, time stamp: 0x5773fdee
> Exception code: 0xc0000005
> Fault offset: 0x0000000000003863
> Faulting process ID: 0xdbc
> Faulting application start time: 0x01d3b142eda481bd
> Faulting application path: C:\Program Files\GNS3\gns3.exe
> Faulting module path: C:\Program Files\GNS3\PyQt5\Qt\bin\LIBEAY32.dll
> Report ID: bd08e785-c353-4f45-b105-4a2401321cce
> Faulting package full name: 
> Faulting package-relative application ID:

 
Entry 2:
 

> Fault bucket 1681532092561537571, type 4
> Event Name: APPCRASH
> Response: Not available
> Cab Id: 0
> Problem signature:
> P1: gns3.exe
> P2: 2.1.3.0
> P3: 5920c4b7
> P4: LIBEAY32.dll
> P5: 1.0.2.4
> P6: 5773fdee
> P7: c0000005
> P8: 0000000000003863
> P9: 
> P10:
> Attached files:
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFC0F.tmp.dmp
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFE73.tmp.WERInternalMetadata.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFE94.tmp.csv
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFEC4.tmp.txt
> These files may be available here:
> C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_gns3.exe_8193118ac5de6aa3786b2e9915e2f31d40cd3e_fe4a6f91_20590314

 
 
This setup works fine for me on a couple of other computers (one running Windows 10 Desktop and one running Server 2016 (nested virtualisation on ESXI 6.5).  Virtualisation is enabled and working on the CPU.  I've tried copying the LIBEAY32.dll from one of the working computers but no joy. 
 
There's not a lot of info on this error on the internet so I'm hoping someone can help.
 
Thanks in advance for any help.

**Comment by ziajka** [comment]
User informed about 2.2 nightly ver. Waiting for response.

**Comment by citizen-4** [comment]
Hi I've tried and failed to install 2.2 several times.  I'm not that familiar with python so I may be doing something wrong...

**Comment by citizen-4** [comment]
Ah right, I thought 2.2 was an update to 2.1.3 I was trying to run.  So, yes now I've installed 2.2 from the link you provided and it works - it requires the NPCAP driver installing (un-selected by default) but seems to be working now.

Thanks so much
