### ISSUE TITLE
Dynamips private config lost after closing project

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1313]
GNS3 version 2.1.4dev1 on Darwin (64-bit) with Python 3.6.4 Qt 5.9.3 and PyQt 5.9.2.

Using dynamips 3725 router, IOS 12.4(25d) on GNS3VM, same issue with 7200 router.

Starting the router and generating a private key is working fine. The private key is available in the GNS3VM.

```
gns3@gns3vm:/opt/gns3/projects/9418759f-1710-4ec1-a76c-3bb033500cf2/project-files/dynamips/363b48a2-1711-4bd0-9302-6bb2c0f502e0$ ls -l configs
total 8
-rw-rw---- 1 gns3 gns3 1923 Mar  4 11:32 i1_private-config.cfg
-rw-rw---- 1 gns3 gns3  904 Mar  4 11:32 i1_startup-config.cfg
```

Then I closed the project, opened it again and started the router. Now the router shows no private config and the private key is lost:

```
R1#dir nvram:
Directory of nvram:/

   54  -rw-         904                    <no date>  startup-config
   55  ----           0                    <no date>  private-config

57336 bytes total (56380 bytes free)
R1#
```

**Comment by grossmj** [comment]
Fixed, the private-config is correctly injected into the nvram when starting a router.
