### ISSUE TITLE
gns3-server 2.1.5 upgrade issues

### ISSUE THREAD

**Issue by happyharrysco1** [GNS3/gns3-server#1333]
Hi Guys, i upgraded my current gns3-server (2.1.0) to the latest version tonight and after completeing the upgrade i got the error message gns3-server is not installed ..... i check the logs and there was a python traceback pointing to /usr/local/lib/python3.4/dist-packages/async_timeout/__init__.py 

i removed the two additions of 'async' on line 48 and 51 and then gns3-server operates as expected again, i'm not sure if this is really your bug but i'm not sure where else to post it

**Comment by happyharrysco1** [comment]
looks like the markup on here takes double underscores to make text bold, obviously the filename has double underscores before and after init

**Comment by alexandrecorso** [comment]
https://github.com/GNS3/gns3-server/issues/1331
