### ISSUE TITLE
API: Identify appliance/template a node was created from

### ISSUE THREAD

**Issue by DragonWin** [GNS3/gns3-server#1334]
Hi

I'm trying to write a little program which will read a project's settings in order to re-create it from scratch. During my coding I have stumpled upon an issue that I can't seem to get around without user input.

**The Goal**
I would like to be able to re-create a lab with fresh appliances, by using the API to identify the project, nodes, links etc and then store the information. I would then be able to use the API to recreate the exact same L2 structure with fresh appliances. At the time the project is "stored" the program also connects the the node via telnet or the node's api and a backup of the configuration is sent to an ftp server.

**The reason**
Some appliances comes with a 14 day trial period (e.g. Fortinet), so my lab becomes unusable after that period, and if I need to test / Lab a similar thing again (or don't complete my first test / Lab within 14 days), I have to manually recreate it each time.

**The issue**
Using GNS3VM version: 2.1.4

When getting the nodes from the project I'm unable to identify which appliance the node was created from. I have multiple appliances with the same hda/hdb image, so I can't use that to identify the appliance. Also using snapshots is not ideal, as at that time the devices has been booted, or the L2 topology has changed during the testing.

**The Questions**
Q1) Is it possible to identify which appliance the node was generated from via the current API?
Q2) Is there a better way to do this? or is it possible to have the appliance / template UUID added to the node data?

Thanks,
Frank

**Comment by DragonWin** [comment]
Thank you, appreciating it getting put on the road-map :-)

**Comment by grossmj** [comment]
Implemented, now the node data contains an appliance_id field. Please note this is not retroactive.
