### ISSUE TITLE
[Enhancement] Please add gns3 internal user rights and migration option

### ISSUE THREAD

**Issue by g1augusto** [GNS3/gns3-server#1337]
Hi everyone,

Thanks for all the feature and bugfix but I need to ask you to include these two additions in future releases:

1) GNS3 needs an internal user management with permissions (someday could be linked to an external source like AD) 

GNS3 users rights and permissions: I believe that since the software is used and deployed as a multiuser service (like classes or shared LABs) there is usually one or more admins and several users, it cannot work if the users can modify the system (remove/add Images for instance) at least on remote servers

2) GNS3 needs an export/migration process to migrate a server or extend the server pool for the GNS3 "cluster", clients needs **always** to get updated config from the server, not the other way around

I noticed lack of options to migrate a gns3 server configuration from one machine to another, this is something that I am doing at the moment and I could see that somehow there has to be a 1:1 match between the VMs and hosts configured on the gui portions of the clients (gns3_gui.conf or gns3_gui.ini) and the remote server controller config file : gns3_controller.conf otherwise the gui rewrites the controller file of the remote server ( I would expect the other way around...). So if this could be included in an export process it may ease (also it could be applied for extending a remote server pool with more units)

**Comment by grossmj** [comment]
User authentication and authorization could be handle by an aiohttp middleware or lib like aiohttp_security: https://aiohttp-security.readthedocs.io/en/latest/

**Comment by grossmj** [comment]
A few notes about user management and authentication:

### Authentication

Users will be authenticated using JWT tokens and secure password hashing. Implementation details using FastAPI can be found at https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/ and https://www.strio.co/blog/authentication-guide-with-fastapi/

In summary: 

* A user gets a JWT token using his credentials by sending a request to a `authenticate` endpoint.

```
curl -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"username":"user123","password":"password123"}' https://localhost:3080/v3/authenticate 
```

* The user then use this token for all other endpoints requiring an authenticated user.

```
curl -H 'Accept: application/json' -H "Authorization: Bearer <token>" https://localhost:3080/v3/endpoint
```

### Rights 

We could have a few basic roles:

* admin, has access to everything and can manager users.
* user, has only access to the projects created by this user.
* maintainer, to manage appliances/templates.
* guest, for read only access to projects and connect to consoles without having to authenticate.

We could also have rights on an object level: projects, nodes. Attributes are used for what can be done on the object. Parents objects have priority (for instance, a project have priority over nodes in that project).

**Comment by grossmj** [comment]
RBAC support has been added.
