### ISSUE TITLE
Update requirements.txt for prompt-toolkit 

### ISSUE THREAD

**Issue by AlyssonOliveira** [GNS3/gns3-server#1346]
https://github.com/GNS3/gns3-server/blob/a13c23749546e0f8ac077509eb19787f4d663d1c/requirements.txt#L10

After a big refactoring of the internal architecture of [python-prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0.1/CHANGELOG#L7) the project must update to version 2.0 or hold 1.0.15

**Comment by grossmj** [comment]
Hi,

We already changed this on our 2.1 and 2.2 branches. We will check if we can upgrade to version 2.0.

**Comment by AlyssonOliveira** [comment]
I forgot to see that branches, I only saw the **master** and after to clone the master repo and run gns3server it continues broken. 

Thanks and I think you can close this issue

Best regards

**Comment by grossmj** [comment]
It's okay, we will eventually merge 2.2 to master. Same result than merging your PR ;) thanks!
