### ISSUE TITLE
Unable to leave projects running on Remote Main Server

### ISSUE THREAD

**Issue by m4shie** [GNS3/gns3-server#1352]
This is probably more of a feature request than a bug. 

The only way currently to leave a project running on a Remote Main Server is to ungracefully disconnect the last GUI client. Unfortunately if anyone is reconnecting to the server and shut down the client as normal the open projects will shut down as well.

So it would be very useful if it was possible to have a persistence setting for projects running on a Remote Main Server where the on/off/suspend status of each node is tracked. This way clients can connect and disconnect as now and run whatever projects they want while still let other projects remain running whenever the gns3-server is running. Also if each node status is tracked within the persistent projects, then those projects could be started back up after a server reboot and be at a state similar to before. This goes nicely hand in hand with the auto saving of the projects.

**Comment by grossmj** [comment]
Hi,

Have you tried to tick the "Leave this project running in the background when closing GNS3" setting accessible from File -> Edit project?

**Comment by m4shie** [comment]
Hi Jeremy,

That worked by ticking all the boxes. However it will not let you have say half the nodes power back on if only half of them were on before a server reboot.

It does however cover my needs to run a fully unattended project. :)
