### ISSUE TITLE
GNS3 Does Not Shutdown/Close Properly

### ISSUE THREAD

**Issue by jespino07** [GNS3/gns3-server#1355]
I recently upgraded my GNS3 client & GNS3 VM Server software to version 2.1.7 on my Mac. Mac is running MacOS Sierra 10.12.6.

Initially, everything seemed to be working and functioning as expected. I'm able to open locally stored topologies, startup my devices, shut them down, and switch through other locally stored topologies just fine.

However, I have a few GNS3 topologies that aren't locally stored/saved in GNS3 that I use for some of my CCIE studies. I can open these particular topologies just fine and startup the devices, but when I try to either close GNS3 or switch to a different topology in GNS3, the GNS3 client times out with the following error message:

"Error while getting compute list: Operation timeout"

I eventually have to force quit the GNS3 application for it to finally close out. Has anybody else experienced this issue before?? I was previously running GNS version 1.5.3 for both my client & Server VM software, and never encountered this issue. I've attached a screenshot that shows what I'm talking about. 

Now I'm starting to wish I never upgraded the GNS3 client and GNS3 Server VM. :-\

Any help is greatly appreciated! 

<img width="853" alt="screen shot 2018-06-13 at 11 47 22 pm" src="https://user-images.githubusercontent.com/28172403/41422412-7c1b4218-6fbe-11e8-93bc-9104a2ea5370.png">

**Comment by grossmj** [comment]
Please, can you post the content of `~/.config/GNS3/gns3_server.log `

Thanks!

**Comment by jespino07** [comment]
I checked the GNS3 VM Server and found that it doesn't have a file named "gns3_server.log" within the directory specified. However, my laptop contains the file mentioned, which I've attached below. 

Please let me know if you have any issues downloading the file attached. 

[gns3_server.log](https://github.com/GNS3/gns3-server/files/2103322/gns3_server.log)

Thank you!

**Comment by jespino07** [comment]
This issue is still persistent even after a project is successfully opened, started, and I'm logged into the routers. GNS3 seems to have deleted the routers from the GUI in my project, but I'm still consoled into the routers themselves at this time.



<img width="1466" alt="screen shot 2018-06-18 at 8 31 13 pm" src="https://user-images.githubusercontent.com/28172403/41571189-a5a3a5b8-7337-11e8-89cc-878360be8b05.png">


For whatever reason, the application continuously tries to startup the local GNS3 server and fails.

jespino$ netstat -na | egrep "3080"
tcp4       0      0  172.16.129.1.58044     172.16.129.1.3080      SYN_SENT
tcp4     419      0  172.16.129.1.3080      172.16.129.1.58020     CLOSE_WAIT
tcp4       0      0  172.16.129.1.58020     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.58011     CLOSE_WAIT
tcp4       0      0  172.16.129.1.58011     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.58010     CLOSE_WAIT
tcp4       0      0  172.16.129.1.58010     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.58005     CLOSE_WAIT
tcp4       0      0  172.16.129.1.58005     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.58002     CLOSE_WAIT
tcp4       0      0  172.16.129.1.58002     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.58001     CLOSE_WAIT
tcp4       0      0  172.16.129.1.58001     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.58000     CLOSE_WAIT
tcp4       0      0  172.16.129.1.58000     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57999     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57999     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57998     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57998     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57997     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57997     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57996     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57996     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57995     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57995     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57994     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57994     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57993     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57993     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57990     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57990     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57987     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57987     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57986     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57986     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57985     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57985     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57984     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57984     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57983     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57983     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57982     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57982     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57981     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57981     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57980     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57980     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57979     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57979     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57978     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57978     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57977     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57977     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57976     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57976     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57975     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57975     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57974     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57974     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57973     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57973     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57972     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57972     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57971     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57971     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57970     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57970     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57969     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57969     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57968     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57968     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57967     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57967     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57966     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57966     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57965     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57965     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57964     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57964     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57961     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57961     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57958     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57958     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57957     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57957     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57950     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57950     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57949     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57949     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57948     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57948     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57947     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57947     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57946     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57946     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57945     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57945     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57944     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57944     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57943     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57943     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57942     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57942     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57941     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57941     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57940     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57940     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57939     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57939     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57938     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57938     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57935     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57935     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57934     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57934     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57933     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57933     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57932     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57932     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57929     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57929     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57923     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57923     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57922     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57922     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57921     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57921     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57919     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57919     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57918     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57918     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57917     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57917     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57916     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57916     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57915     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57915     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57914     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57914     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57913     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57913     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57854     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57854     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57853     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57853     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57850     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57850     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57827     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57827     172.16.129.1.3080      FIN_WAIT_2
tcp4     417      0  172.16.129.1.3080      172.16.129.1.57810     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57810     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57809     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57809     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57808     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57808     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57807     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57807     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57806     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57806     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57805     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57805     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57804     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57804     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57803     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57803     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57802     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57802     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57801     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57801     172.16.129.1.3080      FIN_WAIT_2
tcp4      47      0  172.16.129.1.3080      172.16.129.1.57800     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57800     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57799     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57799     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57798     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57798     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57797     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57797     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57796     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57796     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57789     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57789     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57788     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57788     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57787     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57787     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57786     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57786     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57777     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57777     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57776     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57776     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57771     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57771     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57760     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57760     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57759     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57759     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57758     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57758     172.16.129.1.3080      FIN_WAIT_2
tcp4     419      0  172.16.129.1.3080      172.16.129.1.57757     CLOSE_WAIT
tcp4   57878      0  172.16.129.1.57666     172.16.129.130.3080    ESTABLISHED
tcp4       0      0  172.16.129.1.3080      172.16.129.1.57656     CLOSE_WAIT
tcp4       0      0  172.16.129.1.57656     172.16.129.1.3080      FIN_WAIT_2
tcp4       0      0  172.16.129.1.3080      172.16.129.1.57561     ESTABLISHED
tcp4       0      0  172.16.129.1.57561     172.16.129.1.3080      ESTABLISHED
tcp4       0      0  172.16.129.1.3080      *.*                    LISTEN

jespino$ netstat -na | egrep "3080" | wc -l
     206


<img width="977" alt="screen shot 2018-06-18 at 8 39 55 pm" src="https://user-images.githubusercontent.com/28172403/41571229-d4635178-7337-11e8-98a5-ab2cb9096391.png">



Here are my active connections to the emulated routers that I'm still logged into (even though the GNS3 GUI displays no routers and specifies "Please create a project", and a screenshot of R1 (port 5000), R2 (port 5001), R3 (port 5002), and R4 (port 5003):

jespino$ netstat -na | egrep "500[0-3]"
tcp4       0      0  172.16.129.1.5003      172.16.129.1.57775     ESTABLISHED
tcp4       0      0  172.16.129.1.57775     172.16.129.1.5003      ESTABLISHED
tcp4       0      0  172.16.129.1.5002      172.16.129.1.57774     ESTABLISHED
tcp4       0      0  172.16.129.1.57774     172.16.129.1.5002      ESTABLISHED
tcp4       0      0  172.16.129.1.5001      172.16.129.1.57773     ESTABLISHED
tcp4       0      0  172.16.129.1.57773     172.16.129.1.5001      ESTABLISHED
tcp4       0      0  172.16.129.1.5000      172.16.129.1.57772     ESTABLISHED
tcp4       0      0  172.16.129.1.57772     172.16.129.1.5000      ESTABLISHED
tcp4       0      0  172.16.129.1.5003      *.*                    LISTEN
tcp4       0      0  172.16.129.1.5001      *.*                    LISTEN
tcp4       0      0  172.16.129.1.5000      *.*                    LISTEN
tcp4       0      0  172.16.129.1.5002      *.*                    LISTEN

<img width="637" alt="screen shot 2018-06-18 at 8 37 01 pm" src="https://user-images.githubusercontent.com/28172403/41571183-9ad97d7e-7337-11e8-9535-69e8a44b1682.png">

**Comment by jespino07** [comment]
@grossmj , for testing purposes I've attached one of the labs, along with it's project files, I used to open just fine when my GNS3 Client & GNS3 VM Server were running version 1.5.3.

[lab5-new2.zip](https://github.com/GNS3/gns3-server/files/2115629/lab5-new2.zip)


Now that I've upgraded my client & server software to the latest version of 2.1.7, the projects that are NOT locally saved/stored in GNS3's default directories (like the one I've attached in the .zip folder), are either work, or don't work at all. Whereas on version 1.5.3, everything worked just fine .

**Comment by grossmj** [comment]
Please try again with latest 2.1.x version and comment if you still face the problem.

Thanks!
