### ISSUE TITLE
Increase udhcpc number of retries

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1356]
Noticed a recurring problem of containers not getting an IP because the dhcp server appliance (usually IOSv) doesn't start fast enough for the client.

Can we increase udhcpc number of retries from 5 to 10 for example? It looks like it was increased from 3 (default) wasn't it?

```
root@NetworkAutomation-1:~# /tmp/gns3/bin/udhcpc --help
BusyBox v1.24.2 (2016-06-14 20:55:53 UTC) multi-call binary.

Usage: udhcpc [-fbqRB] [-a[MSEC]] [-t N] [-T SEC] [-A SEC/-n]
	[-i IFACE] [-s PROG] [-p PIDFILE]
	[-oC] [-r IP] [-V VENDOR] [-F NAME] [-x OPT:VAL]... [-O OPT]...

	-i,--interface IFACE	Interface to use (default eth0)
	-s,--script PROG	Run PROG at DHCP events (default /gns3/etc/udhcpc/default.script)
	-p,--pidfile FILE	Create pidfile
	-B,--broadcast		Request broadcast replies
	-t,--retries N		Send up to N discover packets (default 3)
```

**Comment by grossmj** [comment]
Do you mean you want to increase more DHCP discover packets from network automation containers?

**Comment by ehlers** [comment]
I can't reproduce the issue.

Simple test:
Connect a docker image with enabled DHCP to  a cloud, which provides a DHCP server and suspend the link before starting the container:
![docker_dhcp](https://user-images.githubusercontent.com/896406/43511930-047c0274-957a-11e8-84af-d283faafb5d7.png)

Of course, when starting the container, the DHCP client in the container will not get an IP:
```
ipterm-1 console is now available... Press RETURN to get started.
udhcpc (v1.24.2) started
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
udhcpc failed to get a DHCP lease
No lease, forking to background
root@ipterm-1:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 1a:15:26:13:fc:88  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 27  bytes 8730 (8.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@ipterm-1:~#
```

But as the message `No lease, forking to background` indicates, the DHCP process doesn't give up, instead it goes into the background and continues trying to get an IP.

```
root@ipterm-1:~# ps ax
  PID TTY      STAT   TIME COMMAND
    1 pts/0    Ss     0:00 bash -i
   46 ?        Ss     0:00 /gns3/bin/busybox script -qfc while true; do TERM=vt1
   52 pts/1    Ss     0:00 /bin/bash -c while true; do TERM=vt100 /gns3/bin/busy
   53 pts/1    S+     0:00 /gns3/bin/busybox sh
   65 ?        Ss     0:00 udhcpc -R --timeout=1 --tryagain=1 -b -p /var/run/udh
   72 pts/0    R+     0:00 ps ax
root@ipterm-1:~#
```

When I resume the link, the container automatically gets it's IP.

```
root@ipterm-1:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.30.0.122  netmask 255.255.255.0  broadcast 172.30.0.255
        ether 1a:15:26:13:fc:88  txqueuelen 1000  (Ethernet)
        RX packets 9  bytes 1626 (1.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 45  bytes 14886 (14.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@ipterm-1:~#
```

**Comment by AJNOURI** [comment]
Yes @grossmj ,
@ehlers , through Wireshark it shows only those 5 attempts and no more.

**Comment by ehlers** [comment]
Even when using the NetworkAutomation container and an IOSv as a DHCP server I can't reproduce that. In my test the DHCP client in the container keeps on trying to get an IP address (wireshark shows it) and as soon as the IOSv is up, the client gets an IP.
![dhcp_networkautomation](https://user-images.githubusercontent.com/896406/43568557-371b23ac-9635-11e8-8979-a06dff9ee32c.png)

Furthermore increasing the retry count to 10 wouldn't help, the IOSv wouldn't boot in 10 seconds. You would need something like 100 or so. But then with an even slower booting DHCP server you have the same issue. In my opinion the real fix is to find out why the DHCP client stops asking for an IP address in your topology.

BTW: The NetworkAutomation container is one of the worst I've seen. As it makes /usr a persistent directory, on each start the saved /usr directory (500M) has to be copied into the container and on each stop it has to be saved.

**Comment by AJNOURI** [comment]
I'll try to investigate more the container when it happens (sporadically) and not only with the network automation container.
Related to network automation, we need to find a balance between adding more and more apps (required by users) to the image and allow to install them with persistency.

**Comment by grossmj** [comment]
Ping @AJNOURI

**Comment by AJNOURI** [comment]
@grossmj You can close this. I haven't experienced this issue since.

**Comment by grossmj** [comment]
Ok, thanks :+1:
