### ISSUE TITLE
Clean GNS3 close if one remote server is down 

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1357]
For testing purposes, I have killed one of the configured remote server while GNS3 is running.

When trying to close GNS3 GUI, it hangs for a while then propose to kill the local server because it cannot be stopped.

Is there a clean way to detect such event (remote server not responding) and properly close the project and the GUI if desired by the user?

![selection_005_16_06](https://user-images.githubusercontent.com/1716020/41499546-11cf21e8-7182-11e8-9f69-2a333c03b9b5.jpg)

**Comment by grossmj** [comment]
The controller will not wait for remote compute servers anymore when closing the current project/GNS3.
