### ISSUE TITLE
Windows appliance file

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1358]
Got this when trying to import Windows appliance

![selection_010_16_06](https://user-images.githubusercontent.com/1716020/41500741-d460d336-7197-11e8-8fd7-d601798e31ae.jpg)

In the file, GNS3 doesn't accept the value of some fields.

Removed the template sections

![selection_011_16_06](https://user-images.githubusercontent.com/1716020/41500743-e5ec7cae-7197-11e8-8292-221894c16c7c.jpg)

**Comment by ziajka** [comment]
Hi @AJNOURI, in "filesize" (line 75) you have value: `enter-file-size-here`. It should be a number, right now it's invalid structure.

**Comment by grossmj** [comment]
@AJNOURI ping :)

**Comment by AJNOURI** [comment]
@ziajka @grossmj .
Sorry guys for the late reply.
These lines are included in the downloaded template file, do anyone who is trying to import the machine will got this error.

So, should users replace these template expressions with values?
