### ISSUE TITLE
Validate the GNS3 VM network settings

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1359]
From the community forum:

https://gns3.com/qa/gns-virtual-2-1-8-not-starting

----------------

disabled antivirus and firewall, deleted vm image and re imported it still wont start, getting this errors:

> Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request GET /qemu/capabilities 

just wont let me add an image
rebooted the VM in VMware still the same issue , gns vm is greyed out

![image](https://user-images.githubusercontent.com/1716020/41593320-f0466a82-73bf-11e8-8b59-48c9d654ab2b.png)

----------------

- GNS3 2.1.8
- Windows 10
- vmware pro workstation version 12.5.9 build-7535481

**Comment by AJNOURI** [comment]
Might be the same root issue of reaching the compute:

In this case, when trying to save the project:

[https://gns3.com/qa/error-while-duplicating-timeout-](https://gns3.com/qa/error-while-duplicating-timeout-)

**Comment by satishdotpatel** [comment]
I am having same error, Please help.

**Comment by Prashobcv93** [comment]
Even I am having a similar problem. Any solutions?

**Comment by satishdotpatel** [comment]
I have VIRL too and that is also piece of crap!! i thought lets try GNS3
and i stuck here... i need beer now..

Thanks,

Satish Patel

**Comment by grossmj** [comment]
Looking at the screenshot I can see that the GNS3 GUI couldn't find the GNS3 VM (greyed out in the Servers summary pane). Please, can you post a screenshot of GNS3 VM preferences?

![gns3vm_preferences](https://user-images.githubusercontent.com/4752614/42704579-9b968338-868d-11e8-92ed-cc5098f8d40e.png)

**Comment by radladac** [comment]
![gns3 vm grey](https://user-images.githubusercontent.com/42018881/43560392-0076a88a-95c7-11e8-915d-537743b19035.png)
I'm having the same problem.  Here's a pic of my gns3 vm preferences

the gns3 vmware server gets started by gns3 when I open gns3.  The gns3vm says it's ON when I hover over it, but remains grey and can't connect to it with the GET request.

**Comment by grossmj** [comment]
Hi,

Try to disable any firewall or security suite if you run any.

**Comment by AxialV** [comment]
Had the same issue then found https://www.gns3.com/discussions/no-ip-address-gns3-vm-eth0.

I then tried the above by restoring defaults in my virtual network editor and it connected fine.  Probably used a sledge hammer to crack a nut, but I was done with the previous labs and needed to get this working.

Hope it helps

**Comment by radladac** [comment]
Thanks all!  I appreciate the input.

firewall is off, antivirus is off, windows defender is disabled so unless there's another thing to turn off, it's not that.  

AxialV, can you describe the process of 'restoring defaults in my virtual network editor"?  I use both oracle VirtualBox and Vagrant.  I wondered if some of their settings were in my way

**Comment by grossmj** [comment]
Make sure you ping the GNS3 VM from your host (cmd.exe, then ping).

**Comment by grossmj** [comment]
We will add more checks and improve error reporting for the GNS3 VM in the next release.

**Comment by grossmj** [comment]
Now we can see reason why the GNS3 VM cannot start in the server summary however checks for VMware networking config and a better error reporting is going to have to wait version 2.2, this will be easier because of the new controller notification stream.

**Comment by grossmj** [comment]
Check is implemented in https://github.com/GNS3/gns3-server/blob/2.2/gns3server/controller/gns3vm/__init__.py#L340 however need to wait for have a functional GNS3 VM running 2.2 to confirm everything works as expected.

**Comment by DixonCrabtree** [comment]
Hello! How do I solve such error " Error while getting the list of remote images: Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request GET /qemu/images"

**Comment by grossmj** [comment]
Users will see a warning message if the GNS3 VM and the local server are not on the same IP network.

**Comment by odaah** [comment]
If it makes any difference, I had a similar error where the GNS3 VM was grayed out. I was signed into my client VPN and disabling it solved it for me.

**Comment by abhinsh6** [comment]
> Make sure you ping the GNS3 VM from your host (cmd.exe, then ping).

Great it worked man....thanks

**Comment by dominickrick** [comment]
for me is not working, I restore the network setting on VMware, also I've reinstall VMware and GNS3 from scratch and I can ping my VM but still nothing happening, can someone give me a hand here.

![image](https://user-images.githubusercontent.com/51834441/59530001-7b910280-8eb0-11e9-89d0-1a33720462b2.png)

**Comment by grossmj** [comment]
Do you see any message if you hover on GNS3 VM in Servers summary?

**Comment by dominickrick** [comment]
I just FIXED the issue, I had the latest version of GNS3 which is 2.1.21 and on that version apparently there is a bug, I installed the version 2.1.19 and also didnt work, but when I installed version 2.1.20 start working just right away.

FYI, make sure to configure the network card interface on GNS3 for vmware and also the PC on vmware is on one of those NIC

**Comment by gnubyte** [comment]
> it sounding that you have firewall setup in your setup. verify that and try disconnecting to your VPN connectivity if you have connected to office network

Was not firewall on OSX. this happened either way however I think it can be correlated with below:

> If it makes any difference, I had a similar error where the GNS3 VM was grayed out. I was signed into my client VPN and disabling it solved it for me.

This was the problem. If the connection is greyed out the compute for GNS3 is unavailable. The default interface host-only-adapter needs to be set at 192.168.56.101 and GNS3 needs to be configured to see that IP.

**Comment by heldigard** [comment]
The solution for me was:

Go To VMWARE -> Virtual Editor Network -> Restore Defaults
Use the same version of GNS3 VM of the GNS3 Installed in Windows.
Turn On the VMware Machine before open GNS3. Now is green.

**Comment by vairavarajarp** [comment]
All the problem resolved once I installed the new version of GNS3 v2.2.7...

**Comment by Janwillem25** [comment]
Uuuurghhh, Wasted a good two hours researching this issue which I also had on my new setup running v2.2.14 on VMware workstation 15.5. Did all the above mentioned suggestion multiple times and in many variations without joy.

Even was so bold to manually add the VM as an external server. Showed up, but status remained grey. :-( 

Then it suddenly hit me: BANG!
![Capture](https://user-images.githubusercontent.com/72268968/94942111-1f535700-04d6-11eb-8b22-8c8836a79192.PNG)

The default port used in the client to connect to the VM is 3080. Changed the port in the preferences and happy days.

Please match the default settings on the VM and the GUI so not to waste time and get frustrated.

**Comment by h8handles** [comment]
two years later and it is still a problem........where are those checks?
I've done all the above going to nuke it all and start over I guess

**Comment by h8handles** [comment]
going to try the above last resort.....
