### ISSUE TITLE
Unable to Create a Link to connect a Window VM

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1365]
From community forum:
https://gns3.com/qa/unable-to-create-a-link-to-conne

--------------
Windows 10
GNS3 2.1.8

---------------

got an issue when I trying to connect my Window VM to any Router or Switch (IOSv).
 
I have a Window 10 VM create in VMware (Also tried in VirtualBox) and followed the steps like Edit - Preferences - New VMware VM - and ticked allow GNS3 to use any configured VMware Adapter
 
Then When I trying to Add a link from this Window VM to any other IOSv devices, there is Error : 
 
Error while creating link: "192.168.1.74/['255.255.255.0']" does not appear to be an IPv4 or IPv6 network
 
![image](https://user-images.githubusercontent.com/1716020/42007727-f278589c-7a81-11e8-8b07-f21dd28455f3.png)

 
I have tried to integrate both VirtualBox and VMware VM into GNS3 (2.1.8), buy all got some error to connect to any other appliance.

**Comment by grossmj** [comment]
It seems to be a bug with VMware 14. User downgraded to VMware 12 and the problem went away.
