### ISSUE TITLE
VPCS console issue relatd to IPv6 SLAAC

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1372]
VPCS console stops and don't start anymore as soon as **_ip auto_** (IPv6 SLAAC) command is issued.

> 2018-07-19 00:05:11 DEBUG telnet_console:110 Starting telnet console in thread "xfce4-terminal --tab -T "%d" -e "telnet %h %p""
> 2018-07-19 00:05:11 DEBUG telnet_console:88 Telnet console 192.168.0.146:5000 closed

**Comment by grossmj** [comment]
This looks like a bug in VPCS. What other device your VPCS node is connected to and what is the configuration of this device?

Thanks,

**Comment by AJNOURI** [comment]
It is connected to an IOSv l3 router configured for NAT66.

The router inside interface is enabled for IPv6 "ipv6 enable" as well as "ipv6 nat66 inside"

**Comment by grossmj** [comment]
IOSvL3 doesn't seem to have nat66. I have tried with CSR and XRv as well. What am I missing?

**Comment by grossmj** [comment]
Ping @AJNOURI

**Comment by grossmj** [comment]
I also configured IPv6 SLAAC between an IOSv router and VPCS. I didn't find an issue.

R1

```
Router(config)#int g0/0
Router(config-if)#ipv6 add 2001::1/64
Router(config-if)#ipv6 add FE80::1 link-local
Router(config-if)#no shut
Router(config-if)#exit
Router(config)#ipv6 unicast-routing
```

VPCS

```
PC-1> ip auto
GLOBAL SCOPE      : 2001::2050:79ff:fe66:6800/64
ROUTER LINK-LAYER : 0c:79:17:a2:de:00

PC-1> show ipv6

NAME              : PC-1[1]
LINK-LOCAL SCOPE  : fe80::250:79ff:fe66:6800/64
GLOBAL SCOPE      : 2001::2050:79ff:fe66:6800/64
ROUTER LINK-LAYER : 0c:79:17:a2:de:00
MAC               : 00:50:79:66:68:00
LPORT             : 10002
RHOST:PORT        : 127.0.0.1:10003
MTU:              : 1500

PC-1> ping 2001::1 

2001::1 icmp6_seq=1 ttl=64 time=1.778 ms
2001::1 icmp6_seq=2 ttl=64 time=1.545 ms
2001::1 icmp6_seq=3 ttl=64 time=1.507 ms
2001::1 icmp6_seq=4 ttl=64 time=1.598 ms
2001::1 icmp6_seq=5 ttl=64 time=1.514 ms
```

**Comment by AJNOURI** [comment]
@grossmj Sorry for the delay.
YEs you are right, it was CSR1000v not IOSv. My apologies.

Well, I couldn't reproduce the issue.  Redone the lab from the scratch and ... it works, I am confused.

![selection_001_24_08](https://user-images.githubusercontent.com/1716020/44582788-ff9fbf80-a7a2-11e8-80d0-79f5336dc564.jpg)

Sorry again Jeremy for the waisted time :-/
You can close the issue.

**Comment by grossmj** [comment]
No worries, thanks for the feedback! :+1:

**Comment by Network2020** [comment]
hi Team,

      how can i set ipv6 gateway address in tiny core linux or VPCS.
