### ISSUE TITLE
Packet capture with NPCAP and dynamips is proceeding but forbidden to read

### ISSUE THREAD

**Issue by yoctozepto** [GNS3/gns3-server#1376]
Software versions:
GNS3 2.1.8
NPCAP 0.99-r7
Windows 7 (64-bit)

When running local server packet capture with dynamips, the packets seem to be captured (the file is created and its size grows) but the file cannot be opened and the stream to Wireshark is empty. The following line is logged:

```
2018-07-24 09:53:24 ERROR link.py:318 Could not stream PCAP file: error 403: forbidden to open tmp/captures/R1_FastEthernet00_to_R2_FastEthernet00.pcap on compute
```

**Comment by grossmj** [comment]
This is due to a problem when using npcap: https://github.com/nmap/nmap/issues/997

We recommend to use winpcap until this problem is solved.

**Comment by yoctozepto** [comment]
Thanks for pointing me to the real issue.

**Comment by b-ehlers** [comment]
While I can reproduce this issue with npcap v0.93 (on Windows Server 2008R2), the latest npcap v0.9982 is working fine here. Looks like somebody upstream has fixed it.

**Comment by grossmj** [comment]
Thanks for letting us know :+1:
