### ISSUE TITLE
Features request for any version of GNS3

### ISSUE THREAD

**Issue by g1augusto** [GNS3/gns3-server#1382]
Hi Everyone,

Thanks for your support and commitment, let me just list here some features I would like to see in future releases of GNS3

- Cluster management
  - This to link different instances of GNS3 on local or remote servers

- tunneling between remote nodes

  - this should provide confidentiality on and simplify the cluster connectivity, could be used any TAP for Windows or Linux

- User management

  - Centralized AD/LDAP/RADIUS or at least internal user management could allow the server to be exposed to anyone

- User quota

  - Once users are in the system it could be granted quotas in terms of time for the lab or Hardware resources

**Comment by peters79** [comment]
Hi,

Thank you to GNS3 team for all their effort.
I wanted to request to add the possibility of attaching a file (PDF, Word, etc.)to the project.
