### ISSUE TITLE
[2.1.9] Extend interface naming scheme for VMs

### ISSUE THREAD

**Issue by jhonnyx82** [GNS3/gns3-server#1394]
Hi Everyone,

I am currently working on some labs with Cisco Firepower (FTDv) and unfortunately the naming of the interfaces is non-linear, let me give you an example from Cisco specs ([https://www.cisco.com/c/en/us/td/docs/security/firepower/quick_start/kvm/ftdv-kvm-qsg.html#pgfId-3326093](url))

- 1 Management interface (required)
- 2 Diagnostic interface (required)
- 3 Inside interface (required)
- 4 Outside interface (required)
- 5-10 Data interfaces (optional)

This means that the first 2 interfaces are meant for management, and practically it changes also the internal interface numbering, is it possible to define a different name for more interface than only the first one ?

Thanks

**Comment by cioby23** [comment]
Hi @jhonnyx82 this is already implemented and it should be available in the next GNS3 release 2.2.
Please see here https://github.com/GNS3/gns3-gui/issues/2361

**Comment by grossmj** [comment]
Indeed, this is already implement in the next GNS3 release 2.2
