### ISSUE TITLE
v2.1.9 :  deprecated asyncio.async

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1395]
From the community forum:
https://gns3.com/qa/gns3-2-1-9-python-3-7

---------------------

Enviroment
Manjaro Linux (Arch-based)
Python 3.7.0
$ gns3 --version 
2.1.9

-------------

I don't know here is correct place, but I've installed GNS3 2.1.9 by pip3 and by git but I get errors.

when I try to start gns3 I get the error below
 

> $ gns3
> 2018-08-26 03:56:10 INFO root:126 Log level: INFO
> 2018-08-26 03:56:10 INFO main:259 GNS3 GUI version 2.1.9
> 2018-08-26 03:56:10 INFO main:260 Copyright (c) 2007-2018 GNS3 Technologies Inc.
> 2018-08-26 03:56:10 INFO main:262 Application started with /bin/gns3
> 2018-08-26 03:56:15 ERROR local_server:487 Local server process has stopped
> 2018-08-26 03:56:15 ERROR local_server:489 Traceback (most recent call last):
> File "/bin/gns3server", line 11, in <module>
> load_entry_point('gns3-server==2.1.9', 'console_scripts', 'gns3server')()
> File "/usr/lib/python3.7/site-packages/gns3server/main.py", line 82, in main
> from gns3server.run import run
> File "/usr/lib/python3.7/site-packages/gns3server/run.py", line 32, in <module>
> from gns3server.web.web_server import WebServer
> File "/usr/lib/python3.7/site-packages/gns3server/web/web_server.py", line 139
> asyncio.async(self.shutdown_server())
> ^
> SyntaxError: invalid syntax

when I try to start gns3server in terminal I get the same error
 
 

> $ gns3server 
> Traceback (most recent call last): 
> File "/bin/gns3server", line 11, in 
> load_entry_point('gns3-server==2.1.9', 'console_scripts', 'gns3server')() 
> File "/usr/lib/python3.7/site-packages/gns3_server-2.1.9-py3.7.egg/gns3server/main.py", line 82, in main 
> from gns3server.run import run 
> File "/usr/lib/python3.7/site-packages/gns3_server-2.1.9-py3.7.egg/gns3server/run.py", line 32, in 
> from gns3server.web.web_server import WebServer 
> File "/usr/lib/python3.7/site-packages/gns3_server-2.1.9-py3.7.egg/gns3server/web/web_server.py", line 139 
> asyncio.async(self.shutdown_server()) 
> ^ 
> SyntaxError: invalid syntax
> 

 
Searching in [Python Docs](https://docs.python.org/3.6/library/asyncio-task.html#asyncio.async) I saw asyncio.async is a deprecated function.
 
So I tried to fix with commands below:
 
```
cd /usr/lib/python3.7/site-packages/gns3server/
sudo grep -rli 'asyncio.async' * | sudo xargs -i@ sed -i 's/asyncio.async/asyncio.ensure_future/g' @
```
 
OK, now I can run GNS3 with an IOS image but when I try run a qemu image (Juniper or ASR), run VPCS instance or try to link any device I get an error and I dont figure out a fix yet. Can someone try to help me?
 
[Server log](https://www.dropbox.com/s/9idecx045a0rtt1/gns3server.log?dl=0%20because) because I can not get to attach it here.

run gns3 debug mode and try to start a qemu image
 

> 2018-08-26 04:26:41 DEBUG http_client:533 GET http://127.0.0.1:3080/v2/settings {}
> 2018-08-26 04:26:41 DEBUG http_client:695 Decoding response from http://admin@127.0.0.1:3080/v2/settings response 200
> 2018-08-26 04:26:45 DEBUG node:421 JuniperMX-1 is starting
> 2018-08-26 04:26:45 DEBUG http_client:533 POST http://127.0.0.1:3080/v2/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/nodes/285aee44-086f-47d9-b7bf-651128252747/start {}
> 2018-08-26 04:26:46 DEBUG http_client:533 GET http://127.0.0.1:3080/v2/settings {}
> 2018-08-26 04:26:47 DEBUG http_client:645 Response error: Error transferring http://admin@127.0.0.1:3080/v2/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/nodes/285aee44-086f-47d9-b7bf-651128252747/start - server replied: Internal Server Error for http://admin@127.0.0.1:3080/v2/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/nodes/285aee44-086f-47d9-b7bf-651128252747/start (error: 401)
> 2018-08-26 04:26:47 ERROR node:433 error while starting JuniperMX-1: Internal server error http://127.0.0.1:3080/v2/compute/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/qemu/nodes/285aee44-086f-47d9-b7bf-651128252747/start
> 2018-08-26 04:26:47 CRITICAL graphics_view.py:1553 Internal server error http://127.0.0.1:3080/v2/compute/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/qemu/nodes/285aee44-086f-47d9-b7bf-651128252747/start
> Stack (most recent call last):
> File "/bin/gns3", line 11, in <module>
> load_entry_point('gns3-gui==2.1.9', 'gui_scripts', 'gns3')()
> File "/usr/lib/python3.7/site-packages/gns3/main.py", line 294, in main
> exit_code = app.exec_()
> File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 272, in partial
> return func(*args, **kwargs)
> File "/usr/lib/python3.7/site-packages/gns3/http_client.py", line 675, in _processError
> callback(json.loads(body), error=True, server=server, context=context)
> File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 272, in partial
> return func(*args, **kwargs)
> File "/usr/lib/python3.7/site-packages/gns3/node.py", line 434, in _startCallback
> self.server_error_signal.emit(self.id(), result["message"])
> File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 287, in func_wrapper
> return func(*args, **kwargs)
> File "/usr/lib/python3.7/site-packages/gns3/graphics_view.py", line 1553, in _displayNodeErrorSlot
> QtWidgets.QMessageBox.critical(self._main_window, name, message.strip())
> File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 117, in critical
> LogQMessageBox._get_logger().critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> 2018-08-26 04:26:47 DEBUG http_client:695 Decoding response from http://admin@127.0.0.1:3080/v2/settings response 200
> 2018-08-26 04:26:51 DEBUG http_client:533 GET http://127.0.0.1:3080/v2/settings {}
> 2018-08-26 04:26:51 DEBUG http_client:695 Decoding response from http://admin@127.0.0.1:3080/v2/settings response 200
> 2018-08-26 04:26:56 DEBUG http_client:533 GET http://127.0.0.1:3080/v2/settings {}

 
run gns3 debug mode and try to start a VPCS instance
 

> 2018-08-26 04:27:31 DEBUG http_client:533 GET http://127.0.0.1:3080/v2/settings {}
> 2018-08-26 04:27:31 DEBUG http_client:695 Decoding response from http://admin@127.0.0.1:3080/v2/settings response 200
> 2018-08-26 04:27:32 DEBUG node:421 PC-1 is starting
> 2018-08-26 04:27:32 DEBUG http_client:533 POST http://127.0.0.1:3080/v2/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/nodes/dfc601e1-4419-4a80-ab2b-27e3a76f85e1/start {}
> 2018-08-26 04:27:33 DEBUG http_client:533 GET http://127.0.0.1:3080/v2/computes {}
> 2018-08-26 04:27:33 DEBUG http_client:645 Response error: Error transferring http://admin@127.0.0.1:3080/v2/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/nodes/dfc601e1-4419-4a80-ab2b-27e3a76f85e1/start - server replied: Internal Server Error for http://admin@127.0.0.1:3080/v2/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/nodes/dfc601e1-4419-4a80-ab2b-27e3a76f85e1/start (error: 401)
> 2018-08-26 04:27:33 ERROR node:433 error while starting PC-1: Internal server error http://127.0.0.1:3080/v2/compute/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/vpcs/nodes/dfc601e1-4419-4a80-ab2b-27e3a76f85e1/start
> 2018-08-26 04:27:33 CRITICAL graphics_view.py:1553 Internal server error http://127.0.0.1:3080/v2/compute/projects/a9547715-f0bf-4df2-b0e5-c690cba9860b/vpcs/nodes/dfc601e1-4419-4a80-ab2b-27e3a76f85e1/start
> Stack (most recent call last):
> File "/bin/gns3", line 11, in <module>
> load_entry_point('gns3-gui==2.1.9', 'gui_scripts', 'gns3')()
> File "/usr/lib/python3.7/site-packages/gns3/main.py", line 294, in main
> exit_code = app.exec_()
> File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 272, in partial
> return func(*args, **kwargs)
> File "/usr/lib/python3.7/site-packages/gns3/http_client.py", line 675, in _processError
> callback(json.loads(body), error=True, server=server, context=context)
> File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 272, in partial
> return func(*args, **kwargs)
> File "/usr/lib/python3.7/site-packages/gns3/node.py", line 434, in _startCallback
> self.server_error_signal.emit(self.id(), result["message"])
> File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 287, in func_wrapper
> return func(*args, **kwargs)
> File "/usr/lib/python3.7/site-packages/gns3/graphics_view.py", line 1553, in _displayNodeErrorSlot
> QtWidgets.QMessageBox.critical(self._main_window, name, message.strip())
> File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 117, in critical
> LogQMessageBox._get_logger().critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> 2018-08-26 04:27:33 DEBUG http_client:695 Decoding response from http://admin@127.0.0.1:3080/v2/computes response 200
> 2018-08-26 04:27:36 DEBUG http_client:533 GET http://127.0.0.1:3080/v2/settings {}
> 2018-08-26 04:27:36 DEBUG http_client:695 Decoding response from http://admin@127.0.0.1:3080/v2/settings response 200
> 2018-08-26 04:27:41 DEBUG http_client:533 GET http://127.0.0.1:3080/v2/settings {}
> 2018-08-26 04:27:41 DEBUG http_client:695 Decoding response from http://admin@127.0.0.1:3080/v2/settings response 200

**Comment by grossmj** [comment]
Support for Python 3.7 has been added yesterday and will be available in GNS3 2.1.10 which will be released within the next 2 weeks. https://github.com/GNS3/gns3-gui/issues/2566
