### ISSUE TITLE
What kernel modules are required by ubridge?

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#1400]
Corresponding thread: https://gns3.com/qa/ubridge-permission-error-when-co

I think that ubridge require a set of kernel modules that were not shared with the Linux Container. Could you guys tell us which kernel modules are required?

**Comment by grossmj** [comment]
@adosztal does this answer your question?

**Comment by adosztal** [comment]
Yes, thank you. Sorry for forgetting the feedback.
