### ISSUE TITLE
docker vnc console: if x11vnc crashes no console access until the project is reopened

### ISSUE THREAD

**Issue by ddragic** [GNS3/gns3-server#1401]
x11vnc process sometimes crashes for me - unrelated to gns3, should be fixed in x11vnc v0.9.15, but I'm still on 0.9.14 (https://github.com/LibVNC/x11vnc/issues/61) - when this happens console access to gui docker containers is lost until x11vnc is started again either by closing and reopening the project or manual starting it with appropriate parameters. This happens without any warning from GNS3.

GNS3 should monitor the x11vnc process, and probably Xvfb, and restart them on crash or at least warn the user that it happened.

**Comment by grossmj** [comment]
Now users will be informed the that x11vnc process has crashed.
