### ISSUE TITLE
Dynamips hypervisor process has stopped, return code: -8

### ISSUE THREAD

**Issue by Orobas-Obama** [GNS3/gns3-server#1408]
I am Chinese！

Forgive me for this English.

When I import IOS

This mistake has been happening all the time.

I'm sure I installed Dynamips.

**Comment by grossmj** [comment]
What IOS filename have you tried to use?

**Comment by grossmj** [comment]
What is the file name of your IOS image? For example: c3660-a3jk9s-mz.124-25d.bin

Thanks!

**Comment by Orobas-Obama** [comment]
c3660-jk9o3s-mz.124-15.T5.bin
Isn't America at six in the morning?
Thinks

**Comment by Orobas-Obama** [comment]
Why don't you go to bed?

**Comment by grossmj** [comment]
I am a robot and I don't sleep. What you on Windows? Have you tried another IOS image?

**Comment by Orobas-Obama** [comment]
emmm……   ：）
I really hope that I can't understand English.
I just want to concern for
If you offend to you
I feel very sorry
My English is very bad.
Yes, I am running GNS3 on windows，running server on Ubuntu14.04LTS（GNS VM）。
I have Other IOS。
But I haven’t tried to import yet.
Because I thought this has nothing to do with IOS.Problem of C/S。My guess，Let me try other IOS

**Comment by grossmj** [comment]
No offence taken, I was just joking.

Yes please try another IOS, sometime IOS can make the emulator crash.
