### ISSUE TITLE
Leverage the new VMware workstation REST API

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1416]
Check how we could leverage the API to replace the use of vmrun

**Comment by ehlers** [comment]
The REST API is very nice, but in my opinion it has some (small) drawbacks:
- It's very new, it's introduced with Workstation 15 and Fusion 11. Fusion 10 already had a REST API, but  I don't know how compatible that is.
- The API has to be started manually by starting the vmrest program. The GNS3 server could start vmrest, but I don't think that this is it's job. The REST API service should be started by VMware

According to https://docs.vmware.com/en/VMware-Workstation-Player/15/rn/player-15-release-notes.html the REST API is also included in the player version and as the VIX component is not mentioned as a prerequisite, so I assume that VIX is not needed. That's a big plus.

**Comment by grossmj** [comment]
Thanks for your input. We will most likely have this as an experimental option if we implement it, this is definitely interesting for player version :+1:

**Comment by ehlers** [comment]
I just tested the REST API on my Fusion 10 (API v1.0.0), Workstation 15/Fusion 11 are using API V1.2. According to https://blogs.vmware.com/workstation/2018/09/workstation-15-is-here.html the API V1.2 adds "new controls to manage NAT port forwarding and MAC to IP DHCP bindings", so the API v1.0 from Fusion 10 should be fine as well.

When opening the API URL in a browser you can easily print the API documentation, just use File/Print.  
Here the documentation from my Fusion 10: [VMware Fusion 10 REST API.pdf](https://github.com/GNS3/gns3-server/files/2437634/VMware.Fusion.10.REST.API.pdf)


Here a nice blog post: https://www.starwindsoftware.com/blog/how-does-rest-api-work-in-vmware-fusion-and-vmware-workstation

**Comment by grossmj** [comment]
> My conclusion: The current REST API doesn't have enough features to be useful in GNS3.

Thanks for researching this, indeed I was afraid their API wouldn't have enough features to be useful for us. Let's hope they are going to improve it in the near future.

**Comment by ehlers** [comment]
Lack of features is one thing, that should improve over time.

But I assume/fear, that VMware will restrict the Player API to the functions the Player officially offers. Then the Player will no longer be a good choice for GNS3. As long as it's possible to use these features with vmrun, that will be the preferred way. But I read, that Player 15 has some issues in this area. Maybe VMware is limiting vmrun also in the Player.

**Comment by grossmj** [comment]
Apparently VMware hasn't released a standalone vmrun version that works for Player 15: https://gns3.com/community/discussion/gns3-doesn-t-work-on-vmware-play

**Comment by grossmj** [comment]
I have reported this on VMware forum too: https://communities.vmware.com/message/2807189

**Comment by grossmj** [comment]
Our focus is now on Qemu and we won't improve the VMware/VirtualBox support.
