### ISSUE TITLE
Add Swagger UI for controller API

### ISSUE THREAD

**Issue by ghost** [GNS3/gns3-server#1417]
Using [Swagger UI](https://swagger.io/tools/swagger-ui/) allows users/developers new to the GNS3 API to easily test it's functionality. Additionally they get an up-to-date documentation.

**Comment by grossmj** [comment]
I found aiohttp-swagger which seems good and could make an integration easy: https://aiohttp-swagger.readthedocs.io/en/latest/

**Comment by grossmj** [comment]
VIRL2 has an API documentation based on Swagger: https://www.youtube.com/watch?v=5xUvqDMxH3g&t=200s

**Comment by ziajka** [comment]
Ref. https://github.com/GNS3/gns3-server/issues/1686

**Comment by grossmj** [comment]
We have Swagger Ui now, please see https://github.com/GNS3/gns3-server/issues/1686 for details.
