### ISSUE TITLE
Expose GNS3 reserved TCP/UDP ports via API

### ISSUE THREAD

**Issue by sumkincpp** [GNS3/gns3-server#1420]
Currently TCP/UDP ports reserved by GNS3 are available only via html endpoint `/compute`.

Would be great to know about reserved GNS3 ports via API
 - At first for single server via `/v2/settings`
 - For all registered computes via `/v2/computes` or `/v2/computes/{compute_id}`

**Comment by grossmj** [comment]
@sumkincpp thank you for your post however I am not sure I got what you mean. Are you talking about the TCP/UDP ports that GNS3 uses?

**Comment by sumkincpp** [comment]
@grossmj Yes, this ones. They are referenced in [gns3server/templates/compute.html](https://github.com/GNS3/gns3-server/blob/master/gns3server/templates/compute.html)

**Comment by grossmj** [comment]
@sumkincpp 

I will create a new endpoint for this: `/v2/computes/{compute_id}/ports`.

Here is an example, this can be changed again later:

```
curl "http://172.16.1.1:3080/v2/computes/local/ports"

{
    "console_port_range": [
        5000,
        9999
    ],
    "console_ports": [
        5000,
        5001,
        5002,
        5003
    ],
    "udp_port_range": [
        10000,
        20000
    ],
    "udp_ports": [
        10000,
        10001,
        10002,
        10003,
        10004,
        10005
    ]
}
```

One thing is are you interested in all ports used by a compute? For instance some of the UDP ports in this example are bound to 127.0.0.1 and others to 172.16.1.1 because we have local UDP tunnels to uBridge and then other UDP tunnels between uBridge instances.

**Comment by sumkincpp** [comment]
@grossmj Very nice! If I understand correctly with current behavior all ports from different endpoints are shown and it's better to show all ports. Initially I've been interested only in all used tcp console ports.

Also, I have idea of `"console_port": 'auto'` for nodes in project schema. This construct will dynamically allocate a tcp port based on current tcp ports usage.

**Comment by sumkincpp** [comment]
@grossmj Ok, this is completely reasonable if port reallocation works. I've probably hitted a bug with it some time and solved it by changing console ports of the project. Sadly, I hadn't saved any details about that.
