### ISSUE TITLE
Check host binding at start

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#1422]
1. By default, the GNS3 VM uses a host-only adapter to communicate with the host.
2. All GNS3 servers must be in the same subnet. (still?)

I think a few issues ([like this](https://gns3.com/qa/error-when-connecting-to-the-g-8)) could be avoided if GNS3 checked the at start whether the host binding IP is set to the host-only adapter, when using GNS3 VM. It should raise a warning* when the host binding is different.

\* With a "Don't show me this again" checkbox. ;)

**Comment by grossmj** [comment]
I agree about a check whether the host binding IP is set to the host-only adapter, when using GNS3 VM :+1: This will be implemented by https://github.com/GNS3/gns3-server/issues/1359
