### ISSUE TITLE
DOCKER VM: _fix_permissions garbles permissions

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1428]
GNS3 server v2.1.11 on debian linux

Test scenario:
- Add a docker VM which uses volumes (I used ipterm) to a project
- Start docker VM
- Create a lot of files in the volume (e.g. `for ((i=0;i<1000;i++)); do echo $i > $i; done`)
- Stop docker VM

The permissions of the files are stored in a .gns3_perms file in the volume. But only about 100 files have the correct owner, the others have the user and owner of the gns3 user (1000:1000 in my case).

```
$ grep ":0:0:" root/.gns3_perms | wc
    147     147    2637
$ grep ":1000:1000:" root/.gns3_perms | wc
    858     858   20514
```

I've added a log message to _fix_permissions:
```
diff --git a/gns3server/compute/docker/docker_vm.py b/gns3server/compute/docker/docker_vm.py
index ad24a987..5dfa19c9 100644
--- a/gns3server/compute/docker/docker_vm.py
+++ b/gns3server/compute/docker/docker_vm.py
@@ -482,6 +482,8 @@ class DockerVM(BaseNode):
         """
 
         state = yield from self._get_container_state()
+        log.info("Docker container '{name}' fix ownership, state = {state}".format(
+            name=self._name, state=state))
         if state == "stopped" or state == "exited":
             # We need to restart it to fix permissions
             yield from self.manager.query("POST", "containers/{}/start".format(self._cid))
```

Then the stop of the container gives the following log:

```
2018-10-16 13:36:29 INFO base_node.py:553 Stopping uBridge hypervisor 0.0.0.0:37195
2018-10-16 13:36:29 INFO hypervisor.py:204 Stopping uBridge process PID=56173
2018-10-16 13:36:29 INFO docker_vm.py:486 Docker container 'ipterm-1' fix ownership, state = running
2018-10-16 13:36:29 INFO docker_vm.py:690 Docker container 'ipterm-1' [ehlers/ipterm:latest] stopped
2018-10-16 13:36:29 INFO helpers.py:534 192.168.1.10 [16/Oct/2018:11:36:29 +0000] "POST /v2/compute/projects/42d80bcc-4e01-4e76-b420-c515c3f4597e/docker/nodes/e4963c60-0b4f-444e-b939-68d144532eb6/stop HTTP/1.1" 204 246 "-" "Python/3.6 aiohttp/2.3.10"
2018-10-16 13:36:29 INFO docker_vm.py:486 Docker container 'ipterm-1' fix ownership, state = exited
2018-10-16 13:36:35 INFO docker_vm.py:690 Docker container 'ipterm-1' [ehlers/ipterm:latest] stopped
```

`_fix_permissions` is called twice. The first time should be fine, the docker VM is running and the permissions will be saved. But on the second time the VM is stopped, so _fix_permissions starts it again. During the startup phase, where the permissions are restored, the permissions are saved. That will garble the permissions.

I think, this was introduced when fixing issue https://github.com/GNS3/gns3-gui/issues/2181. And for a small number of files it works well. But for a bigger number of files the parallel running of the initialization script `gns3server/compute/docker/resources/init.sh` and `_fix_permissions` makes things worse.

**Comment by grossmj** [comment]
I added a quick fix which is to use _fix_permissions only if the VM state is "running". This seems to work:

```
grep ":0:0:" root/.gns3_perms | wc
   1003    1003   17963
```

However I haven't tested more than this and I suspect I may be missing something...

**Comment by ehlers** [comment]
Indeed, you missed https://github.com/GNS3/gns3-gui/issues/2181. When a docker container is stopped within docker, the permissions are not restored. Then the files of the docker volume are no longer accessible by GNS3.

**Comment by grossmj** [comment]
Stop() is called twice when stopping a Docker VM, once with the API call and once after the container exited (https://github.com/GNS3/gns3-server/blob/2.1/gns3server/compute/docker/docker_vm.py#L649). I have added a flag to avoid calling fix_permissions() twice.

I have tested both cases (stop in GNS3 and stop within Docker) and everything seems to worked as intended.

**Comment by ehlers** [comment]
Looks good, thanks. Close it?

**Comment by grossmj** [comment]
:+1: Thanks for the confirmation.
