### ISSUE TITLE
Issue upgrading from 2.1.10 to latest dev (yarl and aiohttp)

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1430]
Trying to upgrade from 2.1.10 to the latest by cloning and installing and compiling from github.

```
sudo rm -R gns3-server
sudo rm -R gns3-gui
git clone -b 2.1 https://github.com/GNS3/gns3-server
cd ~ 
git clone -b 2.1 https://github.com/GNS3/gns3-gui
cd ~/gns3-server
sudo python3 setup.py install --record ~/gns3-server-files.txt
cd ~/gns3-gui
sudo python3 setup.py install --record ~/gns3-gui-files.txt

```

But when starting gns3 it shows:

> aiohttp 1.3.5 has requirement yarl<0.10,>=0.9.8, but you'll have yarl 1.2.0 which is incompatible.

1.2.0 >= 0.9.8 isn't it?

Tried to reinstall aiohttp:

`sudo pip install aiohttp`

Which has removed what it consider the "wrong" yarl version and installed the "good" one.

> Collecting yarl<0.10,>=0.9.8 (from aiohttp)
>   Using cached https://files.pythonhosted.org/packages/87/71/3b1b6c01e3a2837edf3aa189f7fb53597134d5c23c07ef2846527348c147/yarl-0.9.8-cp34-cp34m-manylinux1_x86_64.whl
> Installing collected packages: yarl
>   Found existing installation: yarl 1.2.0
>     Uninstalling yarl-1.2.0:
>       Successfully uninstalled yarl-1.2.0
> Successfully installed yarl-0.9.8

But when starting gns3:

> 2018-10-22 00:46:02 ERROR local_server:492 Local server process has stopped
> 2018-10-22 00:46:02 ERROR local_server:494 Traceback (most recent call last):
>   File "/usr/local/bin/gns3server", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
>     @_call_aside
>   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
>     ws.require(__requires__)
>   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'yarl>=0.11' distribution was not found and is required by gns3-server

Now it requires yarl >=0.11  ?!?!?!

**Comment by cioby23** [comment]
@AJNOURI the requirements file https://github.com/GNS3/gns3-server/blob/master/requirements.txt it seems is outdated.
You need to use yarl version 1.2.x and aiohttp version 2.3.x. I'm using these versions with Python 3.7 and it works fine:
pip freeze | grep -E 'yarl|aiohttp'
aiohttp==2.3.9
yarl==1.2.6

**Comment by grossmj** [comment]
The correct requirements files for 2.1 is located on the 2.1 branch: https://github.com/GNS3/gns3-server/blob/2.1/requirements.txt

Requirements have been simplified for next major version of GNS3 (2.2)

**Comment by AJNOURI** [comment]
Thanks guys,
For now, the below versions work for me: (gns3 v2.1.11)

```
pip freeze | grep -E 'yarl|aiohttp'
aiohttp==1.3.5
aiohttp-cors==0.5.1
yarl==0.9.8
```

I'll try later to install the versions mentioned by @cioby23
