### ISSUE TITLE
Unable to upload qcow2 onto Ubuntu 16 remote server

### ISSUE THREAD

**Issue by yfquek** [GNS3/gns3-server#1432]
Remote GNS3 server with Ubuntu 16 is working fine with regular Cisco images. But while I try to upload Juniper vSRX qcow2 image onto the GNS3 server, the following error occurs.
![image](https://user-images.githubusercontent.com/20177737/47281196-678c4e00-d60c-11e8-82fe-a504f4bdcbdf.png)

Running Juniper vSRX qcow2 image on local server was not a problem, but when it comes to Ubuntu 16 remote server, the upload fails.
I have tried uploading other images such as Cisco IOU and real IOS which supports Dynamips without any issues.

**Comment by grossmj** [comment]
Looks like this is similar to https://gns3.com/community/discussion/iosv-software-will-not-transfer-

**Comment by grossmj** [comment]
I could not reproduce the problem. Can you provide step by step way to do it? Have you created the template manually in the preferences? Do you get the errors when you drop the template onto the scene?

![remote_server](https://user-images.githubusercontent.com/4752614/50036774-3a876680-ffd1-11e8-861f-8315f1d0805e.png)

![remote_server_2](https://user-images.githubusercontent.com/4752614/50036773-3a876680-ffd1-11e8-8a33-dd728a129477.png)

**Comment by grossmj** [comment]
@yfquek ping
