### ISSUE TITLE
PPA for Ubuntu 18.10

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#1440]
Original thread: https://gns3.com/community/discussion/gns3-ppa-for-ubuntu-18-10
Could you create add Ubuntu 18.10 to the GNS3 PPA? Thank you in advance.

**Comment by sliddjur** [comment]
Perfect. I just want to say I did this to successfully start gns3 on ubuntu 18.10.

Download all amd64 deb files from bionic and installed manually. I solved dependency issues with apt --fix-broken install.


BUT now that I went back to the PPA, I see you just uploaded to cosmic?  @grossmj

**Comment by grossmj** [comment]
@sliddjur indeed, I have just uploaded to the PPA. Only the ubridge package is missing, there is some issues to upload it.

**Comment by grossmj** [comment]
All packages for Cosmic are available on the PPA now: https://launchpad.net/~gns3/+archive/ubuntu/ppa?field.series_filter=cosmic
