### ISSUE TITLE
No data returned from 127.0.0.1:56039 after sending command 'hypervisor version  uBridge process running: True 

### ISSUE THREAD

**Issue by iamkammysafi** [GNS3/gns3-server#1453]
Hello,

Whenever I open new Project in gns3 it poops the below message : 
No data returned from 127.0.0.1:56039 after sending command 'hypervisor version 
uBridge process running: True 
![image](https://user-images.githubusercontent.com/25552848/48455564-803bee00-e7dd-11e8-9673-8f4cf9bbd3bc.png)

and i also installed the Gns3 version 2.1.11 but still face the the issue , please help!

Regards,
Kamran

**Comment by cioby23** [comment]
@iamkammysafi There is already an bug opened for this issue. Check here: https://github.com/GNS3/gns3-server/issues/1289. You can close this one and check the other thread for updates.
