### ISSUE TITLE
Local vs non-local server

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-server#1460]
Related partially to #2261 and #2256 
I think I brought this up already in some email thread, but the discussion didn't get far.

I believe the current setup is very confusing, especially on the GUI side:
There is a concept of main server which can be local and remote.
There are GNS3 VMs that can be virtual box/vmware or remote.

Now some features will work on one combination and will fail on another. For example, setting running the project in the background will not work if you use local main server and then close the GUI. There are also issues when you try exporting the project from one place to another.
Every so often people come for help to me, and these different options are confusing to people, which results in frustration.

While I understand the reason we have "main server" and remote server or VM, I think it would be better to have a clear separation of entities, which are:

GNS3 controller is responsible for all GNS3 project management side: it knows about the projects, can start and stop them, change settings. It also knows about every compute node and probably it also should be able to synchronize the images available on different compute nodes (on-demand or automatically) to avoid problems.
Controller itself should be something lightweight and standalone (does not require the server like it is now). I would love to use my macbook as a controller without GNS3 server running and my compute would be somewhere remote.
I'd argue that controller should be even separated from GUI and could be run as a daemon.

GNS3 compute node or nodes - can be whatever you want, local, remote or gns3-vm (which is technically a remote server where the hypervisor start/stop is controlled by gui)

While scalability should be supported, the majority of users still use a single compute, hence the user experience should be more focused on them.

With that said, there should be also clear separation of Controller and Compute in GUI.

**Comment by grossmj** [comment]
Current differences between local and non-local server:

A non-local server is:

- Forbidden to use a path outside image directory
- Forbidden to create/use a path outside project directories.
- Forbidden to create or update Qemu images with an absolute path.
- Forbidden to shutdown the controller
- Forbidden to load a .gns3 file
- Forbidden to import a project from portable archive
- Forbidden to duplicate a project
- Forbidden to change the compute project directory path
