### ISSUE TITLE
Long CLI command issue with containers

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#1471]
Original thread: https://gns3.com/community/discussion/network-automation-appliance-cli

If I start a Container and access its console from GNS3, long lines overwrite themselves. If I start the same image on my Linux box, everything works fine (left is the local, right is in GNS3):
![screenshot from 2018-10-31 14-55-43](https://user-images.githubusercontent.com/16632791/47793280-3d2e4500-dd1e-11e8-846d-da175435f183.png)

I'm not sure where the issue is. Does the container's CLI inherit something from my local box that is not passed when it's started from GNS3? Should I add some parameters to the container or the root of the problem is how GNS3 spawns the terminal?

Both containers are ran by the same Docker daemon.

**Comment by grossmj** [comment]
This is fixed but not if multiple consoles are connected to the same Docker container. I didn't find a way to handle this case.

**Comment by CDWAdamMason** [comment]
![image](https://user-images.githubusercontent.com/39139135/49196189-90141000-f34f-11e8-952b-088edf7b4bf5.png)

Seems to be, at least for me, happening whenever I reach the bottom line of the console session.
