### ISSUE TITLE
aiohttp 3.2.1 causes image upload to fail in 2.2

### ISSUE THREAD

**Issue by kazkansouh** [GNS3/gns3-server#1474]
OS: Ubuntu/Linux
Version: 2.2 6a2d1e9b337b416eda1522c0ee491b19cbd76b7c
Python: 3.6.5
Libraries installed from requirements.txt, i.e.
```
jsonschema>=2.4.0
aiohttp==3.2.1
aiohttp-cors==0.7.0
Jinja2>=2.7.3
raven>=5.23.0
psutil>=3.0.0
zipstream>=1.1.4
prompt-toolkit==1.0.15
async-timeout==3.0.1
distro>=1.3.0
```

While trying the 2.2 development version an issue was identified where when adding an appliance and uploading an image to the server it would not complete (server was on local host). It would transfer the first approx 46MB very fast, then go very slow and then display a loss of synchronisation message after a few minutes. The image I was uploading was c7200-adventerprisek9-mz.152-4.M7.image

After investigation, the issue appeared to be located when the image was being forwarded from `http://127.0.0.1:3080/v2/computes/local/dynamips/images/....` namespace to the `http://127.0.0.1:3080/v2/compute/dynamips/images/....` namespace. The second namespace would continuously display "TCP Window Full" in a tcpdump after the first 46MB, and then trickle 128 bytes at a time.

Moreover, this appears to be related to the version of aiohttp used. In version 3.3.1 a patch was applied that changed the default iterator used for the StreamReader. Before this version (e.g. 3.2.1 used by 2.2 branch), the iterator was reading the binary stream as lines (delimited by 0x0A), each line would become a chunk. Lots of small chunks being sent with both the sender and receiver in the same program (maybe just same event loop?) would cause the serious performance hit. After the commit in 3.3.1, the iterator for StreamReader chunks data in as large as possible chunks by default. The commit in question is https://github.com/aio-libs/aiohttp/commit/5afccb1e2f43b390f7d20ac230eab29663d590dc

While looking into this issue, I created a small script to experiment with different settings. If needed, it can be found on gist: https://gist.github.com/kazkansouh/e0da42009e9879cf5a55bfe03bcd4089

I'm just raising this issue here so there is a record of this problem and analysis in case its of use. I assume the easiest fix will be to bump the version of aiohttp used. Or if that is not feasible at the moment, a possible workaround could be to directly specify the iterator used. See above gist for an example of how that can be done.

Hope this is of help, and thanks for making the software.

**Comment by cioby23** [comment]
From the requirements list the current aiohttp version for GNS3 should be **aiohttp>=2.2.0,<2.4.0**. You can check here: https://github.com/GNS3/gns3-server/blob/master/requirements.txt
Not sure if the requirements will change after 2.2 release.

**Comment by kazkansouh** [comment]
> From the requirements list the current aiohttp version for GNS3 should be **aiohttp>=2.2.0,<2.4.0**. You can check here: https://github.com/GNS3/gns3-server/blob/master/requirements.txt
> Not sure if the requirements will change after 2.2 release.

Just to confirm this issue is related to the 2.2 branch, where the requirements.txt file has been updated to use aiohttp 3.2.1. I have not experienced this issue with the main branch (or 2.1) that uses aiohttp 2.x.

**Comment by grossmj** [comment]
Thanks for all the information. The reason we do not use a more recent version of aiohttp is because we get "ConnectionResetError: Cannot write to closing transport" errors when stopping the GNS3 server.

We can upgrade once this is solved.

**Comment by grossmj** [comment]
@kazkansouh

Please test and let me know if everything works on your side.

Thanks.

**Comment by kazkansouh** [comment]
@grossmj 

Thankyou for taking a look at this. It works as expected, the image uploads without issue.
