### ISSUE TITLE
[Solved] QEMU appliance 'status' is not shown as 'started' when using bridge on remote GNS3 server

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1477]
I'm using installation of GNS3 2.1.11 where I have few remote servers.
I need to copy large files into my QEMU appliance. Using ubridge proved to be very slow, and I fount in the net that this is a known problem. The net also suggest to improve the ubridge performance by creating a bridge on the remote GNS3 server and attach eth0 to the bridge. Now, when connecting QEMU appliance to a cloud, I can choose the created bridge.
This solution indeed solved by slow copy problem. However, I encountered a new problem where appliance 'status' flag is not updated correctly. The status remain red/stopped, even though the QEMU VM is actually running.
 
The problem I faced was when I created the bridge on a 'remote' server, I didn't yet check the same on a 'main' server. I suspect that the main server does not reflect the correct status returned to him by the remote server.

Some additional info:
1. I have a QEMU appliance and two remote GNS3 servers running 2.1.11 which I've installed from the remote-install.sh script
2. I've ported the same image to the to both servers. On the main server I run the appliance and I see in the GUI it is started (green icon near the appliance)

On the second remote server I've configured a bridge by editing: /etc/network/interfaces

source /etc/network/interfaces.d/*
auto lo
iface lo inet loopback

auto br0
iface br0 inet dhcp
bridge_ports ens160
bridge_stp off
bridge_maxwait 0
bridge_fd 0

 
I've imported the same image to this remote server. Now when I'm starting the QEMU appliance it is running in the server, I can see it in the process list and the logs, but the GUI is not giving any indication (remain red)

 

 

I used Wireshark to capture the HTTP stream on the client side for both appliances 'start' requests:

Both requests returened OK 200

The request to start the QEMU appliance on the main server retured JSON object 

"status": "started" while the start respond on the remote server returned 

"status": "stopped"

 

I used tcpdump on the remote server to capture response to the main server and it seems that the returned status is 'started'.

 

I used tcpdump on the main server to capture response to the client and it seems that the returned status is 'stopped'.

 

 

Why is the main server does not reflacting the correct JSON status value responded by the remote server?

Why is it happening only on bridge configuration?

How can I work around it?

**Comment by grossmj** [comment]
Node events (like start, stop and suspend) are received from the GNS3 server with a HTTP stream or WebSocket stream depending on the version of Qt installed (Websocker for Qt >= 5.6.0). What is your Qt version?

For some reason the information that the node has started doesn't reach your GUI. To confirm this, you can try to see events using curl and wsdump.

For the HTTP stream:

```
curl "http://localhost:3080/v2/projects/6ed35e3a-c43d-4131-a921-98e81e926bbf/notifications"
```

For the Websocket stream:

```
wsdump "ws://localhost:3080/v2/projects/6ed35e3a-c43d-4131-a921-98e81e926bbf/notifications/ws"
```

Replace ```6ed35e3a-c43d-4131-a921-98e81e926bbf``` by your project ID, you can find it in the project directory in the .gns3 file.

You should see something similar to this when starting a node:

```
{"action": "node.updated", "event": {"command_line": "/usr/bin/vpcs -p 5005 -m 0 -i 1 -F -s 10000 -c 10001 -t 127.0.0.1 startup.vpc", "compute_id": "local", "console": 5004, "console_auto_start": false, "console_host": "127.0.0.1", "console_type": "telnet", "custom_adapters": [], "first_port_name": null, "height": 60, "label": {"rotation": 0, "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;", "text": "PC1", "x": -3, "y": -43}, "name": "PC1", "node_directory": "/home/grossmj/GNS3/projects/test/project-files/vpcs/5ac7d104-ba84-41ca-aaa9-61015802f514", "node_id": "5ac7d104-ba84-41ca-aaa9-61015802f514", "node_type": "vpcs", "port_name_format": "Ethernet{0}", "port_segment_size": 0, "ports": [{"adapter_number": 0, "data_link_types": {"Ethernet": "DLT_EN10MB"}, "link_type": "ethernet", "name": "Ethernet0", "port_number": 0, "short_name": "e0"}], "project_id": "6ed35e3a-c43d-4131-a921-98e81e926bbf", "properties": {}, **"status": "started"**, "symbol": ":/symbols/vpcs_guest.svg", "template_id": "7bc24950-e35a-49f8-87c6-034f5bd71332", "width": 60, "x": -671, "y": -167, "z": 1}}
```

**Comment by doronbl** [comment]
I could not find at traces of installed QT in my remote servers. How can I test the version?
I will test the suggested curl and add the results. However, I did similar test by sniffing using tcpdump the HTTP respond of the start request.
What I have noticed is that the 'remote' server reply with status equal to started, while eventually the main server reply with status set to stopped.

Note: to my best understanding, the client send the request to man server, which delegate the request to the appropriate remote server to initialize the VM. So the client response comes from the main server.

**Comment by grossmj** [comment]
> I could not find at traces of installed QT in my remote servers. How can I test the version?

This is on the client side, Qt is used by the GNS3 GUI to connect to the stream from the GNS3 server. The server sends events to the GUI. Depending on the Qt version the stream can be HTTP or WebSockets.

> Note: to my best understanding, the client send the request to man server, which delegate the request to the appropriate remote server to initialize the VM. So the client response comes from the main server.

The client send the request to start a node and the server will reply that the node has started however the GUI uses the information from the server stream to know the status of a node (started, stopped, suspended).

**Comment by doronbl** [comment]
From the client: This program uses Qt version 5.9.1.
I run the suggested command on the main server - could not find such output

However, this is the JSON I get in the response on the main server when capturing with tcpdump:
HTTP/1.1 200 OK
Server: Python/3.5 GNS3/2.1.11
X-Route: /v2/projects/{project_id}/nodes/{node_id}/start
Connection: close
Content-Type: application/json
Content-Length: 3573
Date: Thu, 29 Nov 2018 11:18:28 GMT

{
    "command_line": "/usr/bin/qemu-system-i386 -name 7.5.004-134-1 -m 3072M -smp cpus=4 -enable-kvm -boot order=c -drive file=/opt/gns3/projects/4097b70a-4d00-4962-bc0d-acd0cbed141e/project-files/qemu/0dbaf48a-a0c1-4020-9edf-b1ba70b80eba/hda_disk.qcow2,if=virtio,index=0,media=disk -kernel /opt/gns3/images/QEMU/kernel -append root=/dev/vda console=ttyS0 -uuid 0dbaf48a-a0c1-4020-9edf-b1ba70b80eba -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:37865,server,nowait -net none -device e1000,mac=0c:14:1e:0e:ba:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device e1000,mac=0c:14:1e:0e:ba:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -nographic",
    "compute_id": "7ddad2ff-8f3a-4a92-b800-21403fb4f459",
    "console": 5000,
    "console_host": "<Some IP of the remote server running the VM>",
    "console_type": "telnet",
    "first_port_name": "eth0",
    "height": 45,
    "label": {
        "rotation": 0,
        "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
        "text": "7.5.004-134-1",
        "x": -28,
        "y": -25
    },
    "name": "7.5.004-134-1",
    "node_directory": "/opt/gns3/projects/4097b70a-4d00-4962-bc0d-acd0cbed141e/project-files/qemu/0dbaf48a-a0c1-4020-9edf-b1ba70b80eba",
    "node_id": "0dbaf48a-a0c1-4020-9edf-b1ba70b80eba",
    "node_type": "qemu",
    "port_name_format": "eth{port1}",
    "port_segment_size": 0,
    "ports": [
        {
            "adapter_number": 0,
            "data_link_types": {
                "Ethernet": "DLT_EN10MB"
            },
            "link_type": "ethernet",
            "name": "eth0",
            "port_number": 0,
            "short_name": "eth0"
        },
        {
            "adapter_number": 1,
            "data_link_types": {
                "Ethernet": "DLT_EN10MB"
            },
            "link_type": "ethernet",
            "name": "eth1",
            "port_number": 0,
            "short_name": "eth1"
        }
    ],
    "project_id": "4097b70a-4d00-4962-bc0d-acd0cbed141e",
    "properties": {
        "acpi_shutdown": false,
        "adapter_type": "virtio-net-pci",
        "adapters": 2,
        "bios_image": "",
        "bios_image_md5sum": null,
        "boot_priority": "c",
        "cdrom_image": "",
        "cdrom_image_md5sum": null,
        "cpu_throttling": 0,
        "cpus": 4,
        "hda_disk_image": "1800kvmpackage_75004.qcow2",
        "hda_disk_image_md5sum": "13046080540ebcfedab59f21dbc3a3eb",
        "hda_disk_interface": "virtio",
        "hdb_disk_image": "",
        "hdb_disk_image_md5sum": null,
        "hdb_disk_interface": "ide",
        "hdc_disk_image": "",
        "hdc_disk_image_md5sum": null,
        "hdc_disk_interface": "ide",
        "hdd_disk_image": "",
        "hdd_disk_image_md5sum": null,
        "hdd_disk_interface": "ide",
        "initrd": "",
        "initrd_md5sum": null,
        "kernel_command_line": "root=/dev/vda console=ttyS0",
        "kernel_image": "kernel",
        "kernel_image_md5sum": "8d0798cd433e58ac7bab573052c4f811",
        "legacy_networking": false,
        "linked_clone": true,
        "mac_address": "0c:14:1e:0e:ba:00",
        "options": "-nographic",
        "platform": "i386",
        "process_priority": "realtime",
        "qemu_path": "/usr/bin/qemu-system-i386",
        "ram": 3072,
        "usage": ""
    },
    "status": "stopped",
    "symbol": ":/symbols/router.svg",
    "width": 66,
    "x": -95,
    "y": -39,
    "z": 0
}


Again, the respond from the remote server show status started:
HTTP/1.1 200 OK
X-Route: /v2/compute/projects/{project_id}/qemu/nodes/{node_id}/start
Server: Python/3.5 GNS3/2.1.11
Connection: close
Content-Type: application/json
Content-Length: 2276
Date: Thu, 29 Nov 2018 11:27:55 GMT

{
    "acpi_shutdown": false,
    "adapter_type": "virtio-net-pci",
    "adapters": 2,
    "bios_image": "",
    "bios_image_md5sum": null,
    "boot_priority": "c",
    "cdrom_image": "",
    "cdrom_image_md5sum": null,
    "command_line": "/usr/bin/qemu-system-i386 -name 7.5.004-134-1 -m 3072M -smp cpus=4 -enable-kvm -boot order=c -drive file=/opt/gns3/projects/4097b70a-4d00-4962-bc0d-acd0cbed141e/project-files/qemu/0dbaf48a-a0c1-4020-9edf-b1ba70b80eba/hda_disk.qcow2,if=virtio,index=0,media=disk -kernel /opt/gns3/images/QEMU/kernel -append root=/dev/vda console=ttyS0 -uuid 0dbaf48a-a0c1-4020-9edf-b1ba70b80eba -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:46006,server,nowait -net none -device virtio-net-pci,mac=0c:14:1e:0e:ba:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device virtio-net-pci,mac=0c:14:1e:0e:ba:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -nographic",
    "console": 5000,
    "console_type": "telnet",
    "cpu_throttling": 0,
    "cpus": 4,
    "hda_disk_image": "1800kvmpackage_75004.qcow2",
    "hda_disk_image_md5sum": "13046080540ebcfedab59f21dbc3a3eb",
    "hda_disk_interface": "virtio",
    "hdb_disk_image": "",
    "hdb_disk_image_md5sum": null,
    "hdb_disk_interface": "ide",
    "hdc_disk_image": "",
    "hdc_disk_image_md5sum": null,
    "hdc_disk_interface": "ide",
    "hdd_disk_image": "",
    "hdd_disk_image_md5sum": null,
    "hdd_disk_interface": "ide",
    "initrd": "",
    "initrd_md5sum": null,
    "kernel_command_line": "root=/dev/vda console=ttyS0",
    "kernel_image": "kernel",
    "kernel_image_md5sum": "8d0798cd433e58ac7bab573052c4f811",
    "legacy_networking": false,
    "mac_address": "0c:14:1e:0e:ba:00",
    "name": "7.5.004-134-1",
    "node_directory": "/opt/gns3/projects/4097b70a-4d00-4962-bc0d-acd0cbed141e/project-files/qemu/0dbaf48a-a0c1-4020-9edf-b1ba70b80eba",
    "node_id": "0dbaf48a-a0c1-4020-9edf-b1ba70b80eba",
    "options": "-nographic",
    "platform": "i386",
    "process_priority": "realtime",
    "project_id": "4097b70a-4d00-4962-bc0d-acd0cbed141e",
    "qemu_path": "/usr/bin/qemu-system-i386",
    "ram": 3072,
    "status": "started",
    "usage": ""
}

**Comment by doronbl** [comment]
Some update:
I've tested bridge configuration on a main server. When bridge is configured on the main server appliance status is updated correctly. So the problem is related to data transfer between the remote server response and the main server response to the GUI.

**Comment by grossmj** [comment]
Is the remote server on the same IP network as your GUI? Is there any firewall between the GUI and the remote server?

**Comment by doronbl** [comment]
Both the main and the remote servers are on the same subnet (IP network), but the GUI is on a different subnet (IP network).
I assume there is a firewall between the GUI and the servers, but I can't tell for sure (it is my enterprise network).
Between the remote servers there is no firewall.

**Comment by doronbl** [comment]
I have found the problem. It seems that after such change reboot to them 'main' server is required.
After rebooting the main server everything comes back to normal.

**Comment by grossmj** [comment]
Thanks for troubleshooting this. I will have a look if we can avoid the main server to be rebooted :+1:
