### ISSUE TITLE
ASR9000v on GNS3 totally disfunctional

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1479]
Hi guys

Something weird is happening with this appliance. Not sure how to fix it but here are the symptoms
https://i.imgur.com/kRLA9sZ.png

I have two IOSXR routers (AS9000v) connected together using Gi0/0/0/0-3 (three parallel link, no port channel)
I brought up all three interfaces, I configured CDP on all of them, this was a step by step process, bringing up one pair after the other. Gi0/0/0/0 on each router first , then Gi0/0/0/1 and last Gi0/0/0/2 on both routers

At config level I assigned 1.1.1.1/23 to Gi0/0/0/0 on one router and 1.1.1.2/24 to Gi0/0/0/0 on the other router and I run a continuous ping. I started a sniffing session on each of the three links
For the first two links absolutely no traffic was observed
Only on the third pair I could see the traffic (shown in the above picture) Pay attention to what the sniffer says it is sniffing and see what CDP is showing in the packet capture
It looks like the interfaces are shuffled around somehow
I am running xrv9k-full9-x-6.5.1.qcow2

**Comment by 1001QAdotNET** [comment]
It might have something to do with the fact the appliance template has 7 interfaces but the device has just 5 (including the management here)

**Comment by 1001QAdotNET** [comment]
no even considering that the interfaces are shuffled ...it seems that somehow magically Gi0/0/0/0 is moved to Gi0/0/0/2 in gn3

**Comment by 1001QAdotNET** [comment]
it seems that you need to stick with the number of interfaces in the template (7) but the interfaces are mapped as following:
GNS3 GUI               ASR9000
0                             Mgmt
1                             ?
2                             0/0/0/0
3                              0/0/0/1
4                              0/0/0/2
5                              0/0/0/3

Here is what it looks like or R1 (interfaces connected one to one to R2)

RP/0/RP0/CPU0:R1#show cdp neighbors 
Fri Dec  7 16:32:50.026 UTC
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater
 
Device ID       Local Intrfce    Holdtme Capability Platform  Port ID
R2              Gi0/0/0/0        172     R          IOS-XRv 9 Gi0/0/0/0       
R2              Gi0/0/0/3        124     R          IOS-XRv 9 Gi0/0/0/3       
R2              Gi0/0/0/2        120     R          IOS-XRv 9 Gi0/0/0/2       
R2              Gi0/0/0/1        176     R          IOS-XRv 9 Gi0/0/0/1       
RP/0/RP0/CPU0:R1#bash
Fri Dec  7 16:33:02.845 UTC
[R1:~]$ ifconfig | grep Link
Gi0_0_0_0 Link encap:Ethernet  HWaddr 0c:e1:fc:a9:27:03  
          inet6 addr: fe80::ee1:fcff:fea9:2703/64 Scope:Link
Gi0_0_0_1 Link encap:Ethernet  HWaddr 0c:e1:fc:a9:27:04  
          inet6 addr: fe80::ee1:fcff:fea9:2704/64 Scope:Link
Gi0_0_0_2 Link encap:Ethernet  HWaddr 0c:e1:fc:a9:27:05  
          inet6 addr: fe80::ee1:fcff:fea9:2705/64 Scope:Link
Gi0_0_0_3 Link encap:Ethernet  HWaddr 0c:e1:fc:a9:27:06  
          inet6 addr: fe80::ee1:fcff:fea9:2706/64 Scope:Link
Mg0_RP0_CPU0_0 Link encap:Ethernet  HWaddr 0c:e1:fc:a9:27:00  
          inet6 addr: fe80::ee1:fcff:fea9:2700/64 Scope:Link

ASR9000v will bring up only 5 of them which are then mapped like above 4 regular interfaces and one management interface

Trying to adjust the template to start counting from 0/0/0/{port 2} ended up with just the management port on the device

I think this template needs to be reviewed. It beats me how to fix it

**Comment by adosztal** [comment]
I could only do a workaround. So far we only had cases where the 1st interface had a greater sequence number (e.g. the first visible interface was eth2, which we named eth{port2}). Now it's the other way around: the 4th "physical" interface is called Gi0/0/0/0.

I kept the first interface the mgmt, then renamed the rest to NIC{0}, and added the following note to the usage instructions:
> The interfaces are mapped the following way:
> - NIC0: unused
> - NIC1: unused
> - NIC2: Gi0/0/0/0
> - NIC3: Gi0/0/0/1
> - NICn: Gi0/0/0/(n-2)

**Comment by adosztal** [comment]
On the long run changing the first_port_name to a list would help but that would need lots of changes in the code, and I'm aware that you guys have other tasks with higher priority and this is the only appliance requiring this.

**Comment by grossmj** [comment]
Thanks, I will push this down the line since we cannot do it in 2.1

**Comment by 1001QAdotNET** [comment]
> You're right, I found this @ [Cisco](https://www.cisco.com/c/en/us/td/docs/routers/virtual-routers/configuration/guide/b-xrv9k-cg/b-xrv9k-cg_chapter_01000.html#concept_921C07E3903E4A47A30E8504C6E81AA5):
> 
> > Each time Cisco IOS XRv 9000 Router is booted, the first NIC is used as the management Ethernet interface of the virtual router, the second and third NICs are used by the virtual router internally. These three NICs must be E1000 vNICs. The rest of the NICs are mapped to the data plane as line interfaces.
> 
> I'll update the appliance.
This is wrong.
If you read this https://www.cisco.com/c/en/us/td/docs/routers/virtual-routers/configuration/guide/b-xrv9k-cg/b-xrv9k-cg_chapter_011.pdf  you will see that the last three interfaces must be NE1000 ...int their example the first three are virtio-net-pci

Not sure how to pass that in the advanced options of the template

**Comment by 1001QAdotNET** [comment]
Hmmm I just came across another doc that shows something else

https://www.cisco.com/c/dam/en/us/td/i/300001-400000/360001-370000/364001-365000/364659.tif/_jcr_content/renditions/364659.jpg
