### ISSUE TITLE
Newer versions of Arista cEOS will not load.

### ISSUE THREAD

**Issue by msmithh** [GNS3/gns3-server#1483]
Can't run new docker image for cEOS (4.21,0F) Arista appliance will not load coming up with errors

Trying 127.0.0.1... 
Connected to 127.0.0.1. 
Escape character is '^]'. 
cEOS-1 console is now available... Press RETURN to get started. 
systemd 201 running in system mode. (+PAM +LIBWRAP +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ) 
Detected virtualization 'other'. 

Welcome to Linux! 

Set hostname to <cEOS-1>. 
Failed to install release agent, ignoring: No such file or directory 
Cannot add dependency job for unit systemd-udev-settle.service, ignoring: Unit systemd-udev-settle.service failed to load: No such file or directory. 
See system logs and 'systemctl status systemd-udev-settle.service' for details. 
Cannot add dependency job for unit systemd-udev-trigger.service, ignoring: Unit systemd-udev-trigger.service failed to load: No such file or directory
. See system logs and 'systemctl status systemd-udev-trigger.service' for details. 
Cannot add dependency job for unit systemd-udevd.service, ignoring: Unit systemd-udevd.service failed to load: No such file or directory. See system l
ogs and 'systemctl status systemd-udevd.service' for details. 
Cannot add dependency job for unit systemd-udevd-control.socket, ignoring: Unit systemd-udevd-control.socket failed to load: No such file or directory
. See system logs and 'systemctl status systemd-udevd-control.socket' for details. 
Cannot add dependency job for unit systemd-udevd-kernel.socket, ignoring: Unit systemd-udevd-kernel.socket failed to load: No such file or directory. 
See system logs and 'systemctl status systemd-udevd-kernel.socket' for details. 
Cannot add dependency job for unit iptables.service, ignoring: Unit iptables.service failed to load: No such file or directory. See system logs and 's
ystemctl status iptables.service' for details. 
Cannot add dependency job for unit ip6tables.service, ignoring: Unit ip6tables.service failed to load: No such file or directory. See system logs and 
'systemctl status ip6tables.service' for details. 
Cannot add dependency job for unit getty.target, ignoring: Unit getty.target failed to load: No such file or directory. See system logs and 'systemctl
status getty.target' for details. 
Cannot add dependency job for unit display-manager.service, ignoring: Unit display-manager.service failed to load: No such file or directory. See syst
em logs and 'systemctl status display-manager.service' for details. 
Found ordering cycle on local-fs.target/start 
Walked on cycle path to fedora-storage-init.service/start 
Walked on cycle path to ssdinit.service/start 
Walked on cycle path to local-fs.target/start 
Breaking ordering cycle by deleting job fedora-storage-init.service/start 
Job fedora-storage-init.service/start deleted to break ordering cycle starting with local-fs.target/start 
[  OK  ] Listening on Syslog Socket. 
        Starting Apply net.conf.ipv*.all workaround... 
[  OK  ] Reached target Remote File Systems. 
        Starting Load legacy module configuration... 
[  OK  ] Reached target Paths. 
[  OK  ] Reached target Timers. 
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe. 
[  OK  ] Listening on Delayed Shutdown Socket. 
[  OK  ] Set up automount Arbitrary Executable File Formats F...utomount Point. 
        Starting Setup Virtual Console... 
[  OK  ] Reached target Encrypted Volumes. 
        Mounting Debug File System... 
        Mounting Huge Pages File System... 
        Mounting FUSE Control File System... 
        Mounting Configuration File System... 
[  OK  ] Reached target Swap. 
        Mounting Temporary Directory... 
tmp.mount: Directory /tmp to mount over is not empty, mounting anyway. 
[  OK  ] Reached target Local File Systems (Pre). 
        Starting Configure read-only root support... 
        Starting Load Random Seed... 
        Starting Mount EOS local filesystems... 
[  OK  ] Mounted Configuration File System. 
[  OK  ] Mounted Debug File System. 
[  OK  ] Started Setup Virtual Console. 
[  OK  ] Mounted FUSE Control File System. 
[  OK  ] Mounted Huge Pages File System. 
[  OK  ] Mounted Temporary Directory. 
[  OK  ] Started Configure read-only root support. 
[  OK  ] Started Load legacy module configuration. 
[  OK  ] Started Apply net.conf.ipv*.all workaround. 
        Starting Apply Kernel Variables... 
[  OK  ] Started Apply Kernel Variables. 
[  OK  ] Started Mount EOS local filesystems. 
[  OK  ] Reached target Local File Systems. 
        Starting Mark the need to relabel after reboot... 
        Starting Recreate Volatile Files and Directories... 
        Starting Arista stuff from rc.sysinit... 
[  OK  ] Started Mark the need to relabel after reboot. 
[  OK  ] Started Recreate Volatile Files and Directories. 
[  OK  ] Started Load Random Seed. 
[  OK  ] Reached target System Initialization. 
[  OK  ] Listening on D-Bus System Message Bus Socket. 
[  OK  ] Reached target Sockets. 
[  OK  ] Reached target Basic System. 
        Starting strongSwan IPsec IKEv1/IKEv2 daemon using ipsec.conf... 
[  OK  ] Started strongSwan IPsec IKEv1/IKEv2 daemon using ipsec.conf. 
        Starting Watchdog service.... 
[  OK  ] Started Watchdog service.. 
        Starting waagent check service. This service starts ...dded to et1.... 
[  OK  ] Started waagent check service. This service starts w... added to et1.. 
        Starting Command Scheduler... 
[  OK  ] Started Command Scheduler. 
        Starting Displays the welcome banner... 
        Starting Machine Check Exception Logging Daemon... 
        Starting D-Bus System Message Bus... 
[  OK  ] Started D-Bus System Message Bus. 
        Starting Login Service... 
[  OK  ] Started Machine Check Exception Logging Daemon. 
[  OK  ] Started Displays the welcome banner. 
[  OK  ] Started Login Service. 
Reloading. 
[  OK  ] Started Arista stuff from rc.sysinit. 
        Starting Mount and initialize the SSD device for use by Arista.... 
[  OK  ] Started Mount and initialize the SSD device for use by Arista.. 
        Starting System Logging Service... 
[  OK  ] Started System Logging Service. 
        Starting BootExtension systemd service.... 
        Starting SsuRestore systemd service.... 
[  OK  ] Started BootExtension systemd service.. 
        Starting SYSV: read prefdl and save it as /etc/prefdl... 
[  OK  ] Started SsuRestore systemd service.. 
[  OK  ] Started SYSV: read prefdl and save it as /etc/prefdl. 
        Starting SYSV: find out if I am deprecated and store...c/deprecated... 
        Starting SYSV: Removes any pkgs not needed by this p...etnsd launch... 
[  OK  ] Started SYSV: find out if I am deprecated and store ...etc/deprecated. 
[  OK  ] Started SYSV: Removes any pkgs not needed by this pl... netnsd launch. 
        Starting SYSV: TimeAgent maintain clocks in shared memory.... 
        Starting SYSV: ConnMgr initiate socket connection to Sysdb... 
[  OK  ] Started SYSV: ConnMgr initiate socket connection to Sysdb. 
[  OK  ] Started SYSV: TimeAgent maintain clocks in shared memory.. 
        Starting SYSV: ProcMgr is an Arastra tool that keeps...ons running.... 
[  OK  ] Started SYSV: ProcMgr is an Arastra tool that keeps ...emons running.. 
        Starting SYSV: Eos system stage 1 init script (runs ... as early as... 
        Starting watchdog service. This service stops watchd...ore ProcMgr.... 
[  OK  ] Started watchdog service. This service stops watchdog before ProcMgr.. 
EosStage1.service: control process exited, code=exited status=1 
[FAILED] Failed to start SYSV: Eos system stage 1 init script...T, as early as. 
See 'systemctl status EosStage1.service' for details. 
Unit EosStage1.service entered failed state. 
        Starting SYSV: EosCloudInit is used in vEOS for runn...S, Azure,..)... 
[  OK  ] Started SYSV: EosCloudInit is used in vEOS for runni...AWS, Azure,..). 
        Starting SYSV: Install test FDLs if any when running Autotest... 
[  OK  ] Started SYSV: Install test FDLs if any when running Autotest. 
        Starting NorCal systemd service.... 
NorCal.service: main process exited, code=exited, status=1/FAILURE 
[FAILED] Failed to start NorCal systemd service.. 
See 'systemctl status NorCal.service' for details. 
Unit NorCal.service entered failed state. 
        Starting SYSV: Exclusive ssh service for internal mgmt i/f... 
[  OK  ] Started SYSV: Exclusive ssh service for internal mgmt i/f. 
        Starting SYSV: Adjusts the oom_score_adj score of no...sses so that... 
[  OK  ] Started SYSV: Adjusts the oom_score_adj score of non...cesses so that. 
        Starting SYSV: Eos system init script (runs after PO...ore ProcMgr)... 
EosStage2.service: control process exited, code=exited status=1 
[FAILED] Failed to start SYSV: Eos system init script (runs a...efore ProcMgr). 
See 'systemctl status EosStage2.service' for details. 
Unit EosStage2.service entered failed state. 
        Starting SYSV: NorCal Post script... 
[  OK  ] Started SYSV: NorCal Post script. 
        Starting Arista Aaa agent. On failure, only root login is enabled.... 
Completing EOS initialization (press ESC to skip): 

Operating System: Linux mint 19
GNS3 Software Version: GNS3 2.1.11

**Comment by ehlers** [comment]
With cEOS-4.21.0F Arista slightly changed the installation instructions. The parameter EOS_PLATFORM for newer versions needs to be "ceoslab", while v4.20.5F needs "ceossim".

Furthermore with newer cEOS images you can't no longer login on the console. When the cEOS is fully booted, you need to start an auxiliary console and issue the `Cli` command.

I just created a pull request to update the usage description in the arista-ceos appliance, should be done in the next days.

You don't need to wait for that and re-import the new appliance. Just remove your old docker container with `docker rmi ceosimage:GNS3`. Then follow the new description, except that you don't have to re-import the ceos image (`docker import`).

```
Download:
Create a (free) Arista account and login.
Then navigate to Support / Software Download and download the cEOS-lab image.

Installation:
Copy the image to your GNS3VM (or other Linux) server, then run the following commands:

cEOS-4.21.0F and newer, replace <version> by the cEOS version:
docker import cEOS-lab.tar.xz ceosimage:<version>
echo "rm /etc/systemd/system/getty.target.wants/getty@tty1.service" | \
docker run --name=ceos-container -e CEOS=1 -e container=docker -e EOS_PLATFORM=ceoslab -e SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1 -e ETBA=1 -e INTFTYPE=eth -i ceosimage:<version> sh
docker commit --change='CMD ["/sbin/init"]' --change='VOLUME /mnt/flash' ceos-container ceosimage:GNS3
docker rm ceos-container

cEOS-4.20.5F:
docker import cEOS-lab.tar.xz ceosimage:4.20.5F
echo "rm /etc/systemd/system/getty.target.wants/getty@tty1.service" | \
docker run --name=ceos-container -e CEOS=1 -e container=docker -e EOS_PLATFORM=ceossim -e SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1 -e ETBA=1 -e INTFTYPE=eth -i ceosimage:4.20.5F sh
docker commit --change='CMD ["/sbin/init"]' --change='VOLUME /mnt/flash' ceos-container ceosimage:GNS3
docker rm ceos-container

Usage:
Start an auxiliary console on the cEOS and issue the "Cli" command.
Only cEOS-4.20.5F: Login on the console with username "admin".
```

**Comment by grossmj** [comment]
Done in https://github.com/GNS3/gns3-registry/pull/384, thanks @ehlers!
