### ISSUE TITLE
Issue when configuring GNS3 VM; GNS3 not detecting VM/timeout

### ISSUE THREAD

**Issue by Skuld9029** [GNS3/gns3-server#1486]
Using VMware Workstation version 15.0.2 build-10952284
Using GNS3 version 2.1.11

Going through the Setup Wizard, I chose to run modern IOS, configure the local server settings (127.0.0.1:3080), and the connection to the local server is successful. However, the issue happens when I get  to the GNS3 VM part. I hit next with the default settings with the VM that GNS3 finds, and when I get to the summary page it gets stuck saying "Waiting for http://127.0.0.1:3080"
![image](https://user-images.githubusercontent.com/45955877/50128222-301fd380-0242-11e9-9fad-99e9906312a7.png)

It then opens up VMware workstation and the VM with these settings: 
![image](https://user-images.githubusercontent.com/45955877/50128272-5e9dae80-0242-11e9-86ff-c7b34ae142c6.png)

For some reason, GNS3 does not detect the VM opening and ends up timing out with this error:
![image](https://user-images.githubusercontent.com/45955877/50128899-dcfb5000-0244-11e9-91bf-76b7aa9a338d.png)

**Comment by grossmj** [comment]
Sorry, VMware Workstation Player 15 is currently not supported (see https://gns3.com/community/discussion/gns3-doesn-t-work-on-vmware-play for details). Please use VMware Workstation Player 15 along with VIX version 1.17.
