### ISSUE TITLE
2.2 : bug : dynamips and usage variable

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#1495]
Hi

When i add a new device based on dynamips, i have this error message :

`2019-01-11 16:24:54 ERROR template_manager.py:126 Error while adding/updating template: JSON schema error adding template with JSON data '{'slot1': '', 'console_type': 'telnet', 'sparsemem': True, 'disk1': 0, 'iomem': 5, 'system_id': 'FTX0945W0MY', 'slot2': '', 'name': 'c3725', 'startup_config': 'ios_base_startup-config.txt', 'ram': 128, 'exec_area': 64, 'category': 'router', 'symbol': ':/symbols/router.svg', 'idlesleep': 30, 'template_type': 'dynamips', 'nvram': 256, 'private_config': '', 'image': 'c3725-adventerprisek9-mz.124-25d.image', 'mac_addr': '', 'slot0': 'GT96100-FE', 'usage': '', 'default_name_format': 'R{0}', 'auto_delete_disks': True, 'compute_id': 'local', 'wic1': '', 'wic2': '', 'disk0': 0, 'idlemax': 500, 'console_auto_start': False, 'mmap': True, 'wic0': '', 'platform': 'c3725', 'template_id': '96450e68-93bd-4ef2-b197-9adfde18bd57', 'idlepc': '0x602467a4'}': Additional properties are not allowed ('usage' was unexpected)
`

**Comment by grossmj** [comment]
Should be fixed now. Thanks for reporting this :+1:
