### ISSUE TITLE
Windows 10 v1803 Unable to create udp nio GNS3  v2.1.11

### ISSUE THREAD

**Issue by NikolaiMironov** [GNS3/gns3-server#1498]
Hello,
 I am new to GNS3 and I've started using it recently. Now I am at the point where I have to connect my devices in the topology. Unfortunately, GNS3 gives me this error, when I try to  connect two routers with a gigabit link.

Error while creating link: Dynamips error when running command 'nio create_udp udp-15fa2f71-fe03-4e90-a712-862436b8375b 10034 127.0.0.1 10035': unable to create UDP NIO

You can see what is the problem bellow.
![gns3 probs](https://user-images.githubusercontent.com/22328145/51084212-c6a2c000-172e-11e9-9f7b-f70eba015b4d.png)

P.S. I am not using GNS 3 VM and my UDP ports are 10000 to 20000. I have also read other threads with similar problems, but couldn't make it work.

Best regards !

**Comment by grossmj** [comment]
Do you have any anti-virus or other security suite running on your OS?
