### ISSUE TITLE
Docker has returned an error: 400 OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/gns3/init.sh\": stat /gns3/init.sh: no such file or directory": unknown

### ISSUE THREAD

**Issue by myob-brad** [GNS3/gns3-server#1503]
[DEBUG 1.zip](https://github.com/GNS3/gns3-server/files/2785015/DEBUG.1.zip)
I am starting an issue because I’ve Googled and Googled and can’t find anything on this error anywhere else. If I’m missed something please forgive.

I’ve got basic Linux experience and I’ve never filed a bug report so please bare with me. I read the policies for filing a new issue and I’m doing my best to abide.

Host operating system:
Fedora 29 running with KDE Plasma 5
Running latest GNS3 2.1.11 
I’m including the command line that I ran to install and enable the following:
GNS 3
Wireshark
Dynamips/VPCS
KVM/QEMU
Docker

URL Where I utilized step by step instructions
https://computingforgeeks.com/how-to-install-gns3-on-fedora-29-fedora-28/

Step 1: Install Dependency packages and Wireshark
Install dependency packages required for building your GNS3 environment:
sudo dnf -y install git gcc cmake flex bison
sudo dnf -y install elfutils-libelf-devel libuuid-devel libpcap-devel
sudo dnf -y install python3-tornado python3-netifaces python3-devel python-pip python3-setuptools python3-PyQt4 python3-zmq

Install Wireshark 

sudo dnf -y install wireshark
Step 2: Install GNS3 GUI and Server
Start the installation by ensuring GNS3 backend server and the frontend interface packages are installed:

sudo dnf -y install gns3-server gns3-gui
Step 3: Install Dynamips and vpcs
git clone https://github.com/GNS3/dynamips
cd dynamips
mkdir build
cd build
cmake ..
sudo make install

Confirm binary location:
$ which dynamips
/usr/local/bin/dynamips

Install vpcs:
wget http://sourceforge.net/projects/vpcs/files/0.8/vpcs_0.8b_Linux64/download
mv download vpcs
chmod +x vpcs
sudo cp vpcs /usr/local/bin/
Confirm vpcs version:
$ vpcs -v
For more information, please visit wiki.freecode.com.cn.

Step 4: Add support for KVM / QEMU (Optional)

Followed instructions at this link How to install KVM on Fedora 29 / Fedora 28
Step 6: Add Support for Docker (Optional)
By default, GNS3 allows you to use Docker containers while building network labs. But first, you need docker engine installed and running so that you can create Docker Containers. Use our official guide to Install Docker on your system:
How to install Docker on Fedora 29 / Fedora 28
Step 1: Update your system
We always start our installations by updating and upgrading OS packages. On Fedora, this can be easily done by running the command:
sudo dnf -y update
It is recommended to reboot your system after an upgrade
sudo reboot
Step 2: Add the Docker repository to Fedora 29/28
After upgrading system packages and rebooting the server, proceed to add Fedora repository to your system
sudo dnf -y install dnf-plugins-core
Add the repository:
cat >/etc/yum.repos.d/docker-ce.repo<<EOF
[docker-ce-stable]
name=Docker CE Stable
baseurl=https://download.docker.com/linux/fedora/28/x86_64/stable
enabled=1
gpgcheck=1
gpgkey=https://download.docker.com/linux/fedora/gpg
EOF
This command will set up the stable Docker repository.
Step 3: Install the latest Docker Engine on Fedora 29 / 28
Now that you have your repository ready, install the latest stable release of Docker on your machine by running:
sudo dnf -y install docker-ce
Docker will be installed but not started. To start the docker service, run:
sudo systemctl start docker
Enable it to start on boot:
sudo systemctl enable docker
The docker group is created, but no users are added to the group. Add your user to this group to run docker commands without sudo.
sudo usermod -aG docker $(whoami)
You can verify the version of Docker installed by running:
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:25:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:26:30 2018
  OS/Arch:          linux/amd64
  Experimental:     false
Step 4: Pull Test docker image
The last step is to test your installation by downloading a test docker container.
$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
4fe2ade4980c: Pull complete 
Digest: sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
Status: Downloaded newer image for alpine:latest
Verify that Docker CE is installed correctly by running the alpine image.
$ docker run -it --rm alpine /bin/sh
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
v3.8.1-58-gb11ab10a64 [http://dl-cdn.alpinelinux.org/alpine/v3.8/main]
v3.8.1-42-ge6bc061baf [http://dl-cdn.alpinelinux.org/alpine/v3.8/community]
OK: 9546 distinct packages available
/ # exit

After installing and starting/enabling Docker, I rebooted the pc.

Whenever I try to place one of my docker units, such as:

Chromium or Ubuntu Docker Guest they give me the following error.

Docker has returned an error: 400 OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/gns3/init.sh\": stat /gns3/init.sh: no such file or directory": unknown

I’ve searched all over Google and no hits on this error.
I have seen a few similar to this but none of those were while using GNS3.

Being a basic Linux user I don’t know if this is a Docker issue or a GNS3 issue or both so I would appreciate any help.
Thank you

Let me know if there is anything else needed that would be helpful in tracking this down.
If you do need something else I would respectfully request a quick tip on how to do it as a reminder I'm still at basic level with Linux and using Fedora for the first time so it's a new distro for me.

**Comment by ArnyD** [comment]
I have the same problem on Fedora 29 Desktop
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:43 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by ArnyD** [comment]
I solved this problem.

The missing files are:

/usr/lib/python3.6/site-packages/gns3server/compute/docker/resources/init.sh
/usr/lib/python3.6/site-packages/gns3server/compute/docker/resources/bin/busybox
/usr/lib/python3.6/site-packages/gns3server/compute/docker/resources/etc/udhcpc/default.script

You can fined them on https://github.com/GNS3/gns3-server

**Comment by grossmj** [comment]
The problem seems to be with how the GNS3 packages were built by the third party (we do not distribute packages for Fedora). One solution could be to install the server and gui using pip.
