### ISSUE TITLE
GNS3 not installing on Debian Stretch

### ISSUE THREAD

**Issue by leribe** [GNS3/gns3-server#1505]
Hi Guys, 
Can you please help or point us in a right direction, can't install GNS3 on Debian stretch, rebuilded my machine 9 months and lived to regret it as i could not re-install GNS3.

Error Message:
Setting up gns3-server (2.1.12~xenial1) ...
cp: cannot stat '/usr/bin/python3.5': No such file or directory
cp: cannot stat '/usr/bin/python3.5': No such file or directory
WARNING: Some error occured while updating /usr/share/gns3/gns3-server/bin/python3
Setting up gns3-gui (2.1.12~xenial1) ...
cp: cannot stat '/usr/bin/python3.5': No such file or directory
cp: cannot stat '/usr/bin/python3.5': No such file or directory
WARNING: Some error occured while updating /usr/share/gns3/gns3-gui/bin/python3

Starting GNS3
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Current thread 0x00007f7adb718740 (most recent call first):
Aborted

**Comment by grossmj** [comment]
What instructions have you used to install GNS3?

**Comment by grossmj** [comment]
@leribe I suppose you managed to install using the bionic repo.

**Comment by leribe** [comment]
Thanks Jeremy, used pip install and got it working, appreciated.
