### ISSUE TITLE
Error when pulling docker container: Docker has returned an error: 500 

### ISSUE THREAD

**Issue by garmaxx** [GNS3/gns3-server#1506]
I finally solved this hope it helps others

Well the answer is your GNS3 VM is not able to access the internet
You have make sure that your VM is getting an internet connection. How to test this is to spin up 
windows VM machine. if your windows VM is not getting an internet connection you can solve this by watching this video.

https://www.youtube.com/watch?v=kLbn6eCMxAU&t=267s

ok now on your GNS3VM you need have three adapters 

Host only 
Nat 
Custom(VMnet0)

now spin up gns3 drop Network automation appliance or Ubuntu it should connect to the internet then pull 
relevant info.

Hope this helps

**Comment by garmaxx** [comment]
My problem was not being able to spin up Network Automation appliance every time I drop the device on the GNS3 work area I was getting this error:500

**Comment by grossmj** [comment]
I will see if we can check for Internet connection or give a more meaningful error message.

**Comment by shahumang18** [comment]
Hi Grossmj,

I am still having an issue adding ipterm docker to GNS3. I am using GNS3 VM on ESXi. Can you please help me with my issue?
