### ISSUE TITLE
Dynamips Error on Linux

### ISSUE THREAD

**Issue by leribe** [GNS3/gns3-server#1509]
Can you please assist in resolving dynamips errors on Linux

1. Getting this error when i run idle finder
Dynamips hypervisor process has stopped, return code: -11
C7200 'Ghost': generic_nvram_extract_config: Unknown error -61605

2. After installation, have dynamips ver 0.2.19 installed, however, getting this error, when starting router device.
Dynamips hypervisor process has stopped, return code: -11
Error: Could not send Dynamips command 'vm get_status "AUTOIDLEPC"' to 127.0.0.1:40401: Connection lost, process running: False

#dpkg -l |grep dynamips
dynamips 0.2.19-1~bionic1

**Comment by grossmj** [comment]
Hi,

Can you try to set the timezone manually with for instance `ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime` or by using `sudo dpkg-reconfigure tzdata`?

Let me know if this fixes the issue.

Thanks!

**Comment by leribe** [comment]
Thanks Jeremy, works, thanks again. You a star
