### ISSUE TITLE
Fix for dynamips error

### ISSUE THREAD

**Issue by leribe** [GNS3/gns3-server#1510]
Hi Jeremy,

On Linux, the issue with dynamips not working if not on new york timezone, can be resolved by starting the application on that timezone as below, so people don't need to change their system timezone. Small contribution, if it may help, benefited alot from the application. 

:~# TZ=America/New_York gns3 &

**Comment by grossmj** [comment]
Thanks, I will also consider if we can do something in Dynamips itself using tzset().

https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxbd00/rttzs.htm

**Comment by grossmj** [comment]
Now we set a timezone directly from inside Dynamips if none is configured or UTC/GMT is set, see https://github.com/GNS3/dynamips/issues/91 for details.

I am going to release Dynamips 0.2.20. Hopefully this is the last time we have a problem with this.
