### ISSUE TITLE
[2.2a1] GNS3-VM Nested Virtualization QEMU rejecting PMU MSR accesses

### ISSUE THREAD

**Issue by EB-athila** [GNS3/gns3-server#1512]
Getting the following error messages when setting "-cpu host" QEMU option and the appliance doesn't start:

_=> QEMU process has stopped, return code: -6
Start QEMU with /usr/bin/qemu-system-x86_64 -name R2 -m 3072M -smp cpus=1 -enable-kvm -machine smm=off -boot order=c -device ahci,id=ahci0,bus=pci.0 -drive file=/opt/gns3/projects/c44209e8-969c-4dec-a018-fbc01b8378a5/project-files/qemu/02fac6fb-f16a-4bce-9fd9-e9a18d3864c7/hda_disk.qcow2,if=none,id=drive-sata-disk0,index=0,media=disk -device ide-drive,drive=drive-sata-disk0,bus=ahci0.0,id=drive-sata-disk0 -uuid 02fac6fb-f16a-4bce-9fd9-e9a18d3864c7 -serial telnet:127.0.0.1:5003,server,nowait -monitor tcp:127.0.0.1:40047,server,nowait -net none -device e1000,mac=0c:78:a5:64:c7:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -device e1000,mac=0c:78:a5:64:c7:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10005,localaddr=127.0.0.1:10004 -device e1000,mac=0c:78:a5:64:c7:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -device e1000,mac=0c:78:a5:64:c7:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10009,localaddr=127.0.0.1:10008 -nographic **-cpu host**

Execution log:
**qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
qemu-system-x86_64: /build/qemu-Eap4uc/qemu-2.11+dfsg/target/i386/kvm.c:1807: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.**_

Found two workarounds at "https://bugs.launchpad.net/qemu/+bug/1661386"
1. Set "Virtualize CPU performance counters" option in VMware Workstation.
2. Set PMU off in QEMU/KVM option "-cpu host,pmu=off"

===========================================================
GNS3 VM (GUEST):
 GNS3 server version: 2.2.0a1
 VM version: 0.10.15
 Ubuntu version: Bionic
 Qemu version: 2.11.1
 KVM support available: True
 vRAM: 8GB
 vCPUs: 2.

HOST:
CPU: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
RAM: 16GB
VMware® Workstation 14 Pro 14.1.3 build-9474260
Windows 7 Professional, 64-bit 6.1.7601, Service Pack 1

**Comment by grossmj** [comment]
What appliance have your tried to run?

**Comment by grossmj** [comment]
@EB-athila ping

**Comment by EB-athila** [comment]
@grossmj 
Sorry for the delay. The appliance is the csr1000v, and I tried it because I got an error message about CPU does not support AES-NIS acceleration without the 'cpu' flag.

I do not have this issue with GNS3 VM 2.1.12, QEMU 2.5.0.

**Comment by grossmj** [comment]
We will ship Qemu 3.1.0 in the GNS3 VM for version 2.2 alpha 2, let's see if the problem still occurs.

**Comment by EB-athila** [comment]
Checked with version 2.2a5 and it's working.
