### ISSUE TITLE
The STABLE PPA is set to push out the 2.2.0Alpha 1 build and not 2.1.12

### ISSUE THREAD

**Issue by m4shie** [GNS3/gns3-server#1513]
Anyone running Linux/GNS3VM will have their systems nuked next time an auto update is happening as the current Alpha release of 2.2.0 is installed instead of 2.1.12 when people are using the PPA intended for stable builds.

Can this be fixed ASAP before your entire userbase have their GNS3 setups destroyed?

**Comment by ziajka** [comment]
Thank you @m4shie. It has been already fixed.
