### ISSUE TITLE
Is it possible possible to move projects from one server to the other by copying files?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1518]
Hi guys

I have like 70G of files and I would like to migrate my GNS3 server (VMware VM ) to a bare bone server that I just built.
I think there is a way to move them via GUI but that means to install the gui on a local machine in a remote lab which is not possible. I do not want to get the files from the source server to my laptop and then move them to the new server
Maybe a nice feature would be to switch the primary server and allow project files movement between servers in the same "swarm"

**Comment by grossmj** [comment]
You should be able to just copy the files to the new server in the ~/GNS3/projects directory and the GNS3 server will find them when you restart it. You can confirm that by opening a web browser and going to `http://127.0.0.1:3080/v2/projects` (replace with the correct IP for your server).

Then, to open from the GUI (connected to the server of course), go to new blank project and to the "Projects library", then double click on the project you wish to open.

**Comment by grossmj** [comment]
Please comment back if you encounter a problem.
