### ISSUE TITLE
Question: Export project failed if cloud object exists

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1519]
1. I have GNS3 2.1.11 setup with remote server
2. Create simple topology which include cloud object

Click 'Export portable project'
Error is shown:
ExportProjectWorker thread stopping with an error: Projects with a cloud node cannot be exported
Projects with a cloud node cannot be exported
Why cloud can't be exported?

Doron

**Comment by grossmj** [comment]
Because clouds are usually mapped to Ethernet and TAP interfaces that have different names depending on users' systems (Windows, many Linux flavors). However we should find a solution for this or allow the export with a warning maybe.

**Comment by grossmj** [comment]
Now we allow cloud nodes to be exported. An error message will be displayed if an Ethernet or TAP interface doesn't exist on the system.
