### ISSUE TITLE
Question: How Export/Import works under the hood

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1520]
Hi,

I'm working with remote server configuration. In latest GNS3 versions 2.1.11 or up, how export/import portable project is working under the hood?
Few questions to direct an answer:
1) What makes the export to be portable? I mean, in what portable project differ from a non portable project?
 2) It seems that the server name of the source GNS3 server does not have to be the same like in the target. What objects are portable and which are not (the image for example should exist on the target host in case I do not include the base images)
3) I was able to export topology that span over 2 remote servers and import it into a destination environment with only one remote server. What will happen if I will have destination also with two remote servers? How GNS3 will select which appliance will run on which remote server?
4) Why can't I export a cloud?

Doron

**Comment by grossmj** [comment]
Hi,

> 1. What makes the export to be portable? I mean, in what portable project differ from a non portable project?

The main difference is that a non portable project is made of various files (images, disk files, temporary files etc.) that can sometimes spread out on multiple different computers. Non portable projects are not intended to be shared.

An exportable project however is made to be shared, all the necessary files are put into a zip file with the .gns3project extension. Remote files are downloaded from servers and images can also be optionally included. Snapshots, packet capture files, symbolic links and various temporary files are not exported. The .gns3 file is also modified (i.e. all compute_id references are set to "local") to allow for an easier import.

> 2. It seems that the server name of the source GNS3 server does not have to be the same like in the target. What objects are portable and which are not (the image for example should exist on the target host in case I do not include the base images)

The following nodes cannot be exported: VMware and VirtualBox as well as cloud node in version 2.1.x (2.2 will allow cloud nodes to be exported).

> 3. I was able to export topology that span over 2 remote servers and import it into a destination environment with only one remote server. What will happen if I will have destination also with two remote servers? How GNS3 will select which appliance will run on which remote server?

All nodes will be run on the local server by default when the portable project is imported (we want to change this).

> 4. Why can't I export a cloud?

We changed that for version 2.2: https://github.com/GNS3/gns3-server/issues/1519

Finally, please note that we want to refactor how projects are imported/exported, especially regarding the speed. See https://github.com/GNS3/gns3-server/issues/1349 for details.

Do not hesitate to comment on what improvements you would like to see for project export/import.

Thanks!

**Comment by doronbl** [comment]
10x for the detailed explanation.
Just to make sure I understand you correctly:
When exporting project that spans multiple remote servers, all appliances will be assigned with compute_id references set to "local" - This is to verify they will be importable on any destination GNS3 installation.
This in turn means that even if I have GNS3 installation with several remote servers configured, import will result ALL appliances running on the main server only?

As an improvement for import process, I can suggest that the user will be asked to confirm default 'local' settings, or else get a list of all appliances and suggest his remote server placement for each appliance.

**Comment by grossmj** [comment]
> When exporting project that spans multiple remote servers, all appliances will be assigned with compute_id references set to "local" - This is to verify they will be importable on any destination GNS3 installation.
This in turn means that even if I have GNS3 installation with several remote servers configured, import will result ALL appliances running on the main server only?

Correct, this is the current behavior.

> As an improvement for import process, I can suggest that the user will be asked to confirm default 'local' settings, or else get a list of all appliances and suggest his remote server placement for each appliance.

We definitely want to change this, for instance by displaying a dialog to solve complex cases.
