### ISSUE TITLE
Reinitialize node MAC addresses when duplicating a project

### ISSUE THREAD

**Issue by cmessin1** [GNS3/gns3-server#1522]
All,

I have GNS3 server deployed on Ubuntu 16.04.  This is not the VM but a direct repository install.

The machine has 2 physical interfaces and each interface is mapped to 1 bridge: br0 and br1.

I am having an issue with cloud.  GNS3 has created two tap interfaces: GNS3TAP0-0 and GNS3TAP1-0.  I assume this is because I have two BRs.  The problem is that both GNS3TAP0-0 and GNS3TAP1-0 keep getting bridged to BR0.  This is causing a forwarding loop.  I don't actually need GNS3TAP1-0 at all as I am not currently using BR1.

I can manually remove GNS3TAP1-0 from BR0 with "brctl ifdel" but it keeps coming back.  I am not sure if it just happens over time or only when I make a change to a cloud adapter.  I need to do more testing but can't until the current use case is complete.

Does anyone know where the mapping is coming from an if there is a easy fix via a config file?

**Comment by cmessin1** [comment]
Please disregard.  Now I understand, each project get's its own tap.  My issue was not a forwarding loop but because I duplicated a project I ended up with duplicate MACs.  Would be nice to have a way to address this automatically but I was able to manually fix by changes all of the base MACs.

**Comment by grossmj** [comment]
Nodes should get different (random) base MACs. What kind of nodes have you used? (Qemu, Dynamips etc.). Also, what is the version of GNS3?

Thanks.

**Comment by cmessin1** [comment]
I am running 2.1.11.  Nodes are all QEMU.  The base MACs change when I duplicate within a project but if I duplicate an entire project they stay the same.  I have to manually increment all of them.

I have been closing the project and duplicating from the project list window.

**Comment by grossmj** [comment]
Thanks, I am going to fix this problem.

**Comment by grossmj** [comment]
Fixed. Thanks for reporting this issue!
