### ISSUE TITLE
portable project error exporting 20+ gig files using the GUI attached to a bare metal server

### ISSUE THREAD

**Issue by qcdebug** [GNS3/gns3-server#1524]
Cannot export project: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\Users\Miranda\AppData\Local\Temp\tmpwik_jfxx\tmp72j5wvd5'

At the time of the error, the written file size is 22,861,928,986 bytes. It also appears to fail about the same byte range every time though I did see one fail at about 19GB as well in the times I've been checking the sizes.

This is connecting to a remote GNS3 bare metal server which is also set as a VM.  I've tried with base images and without base images and I have the same failure show up.  I'm curious if it has something to do with a timeout that the server is executing when the exports take too long. 

I'm also not sure if this should be filed under gns3-server or gns3-gui since I'm currently using a local server to export my project to a portable file so that I can change it to remote server hosts everything and restore the project (I can't find any other way to do this).

**Comment by grossmj** [comment]
Hi,

What version of GNS3 have you used?

**Comment by qcdebug** [comment]
Hi,Both .11 and .12MirandaOn Feb 20, 2019 3:54 AM, Jeremy Grossmann <notifications@github.com> wrote:Hi,
What version of GNS3 have you used?

**Comment by grossmj** [comment]
Do you have any Dynamips node in your project?

**Comment by qcdebug** [comment]
No, I do not.  It's all QEMU. 
![image](https://user-images.githubusercontent.com/47701719/53185223-345ec900-35c4-11e9-893f-90a248d0172b.png)

**Comment by cioby23** [comment]
By looking at this picture it appears that the Core and Client switches are standard ethernet switches and in this case they use dynamips in the backend (unless you use Qemu nodes behind and changed the symbol)

**Comment by grossmj** [comment]
@cioby23 gave me an idea. Can you try to export the same project without the core and client switches. This would validate that the problem come from Dynamips.

Thanks!

**Comment by qcdebug** [comment]
This is why I included a picture.   I appreciate the correction cioby23, I'm still very much learning all of this.  The system does not fault on that though, it's in the middle of writing one of the large 200G images and it crashes.    

grossmj,  absolutely!  Give me a minute to shutdown all the systems and I'll strip the switches and links to try again.

**Comment by qcdebug** [comment]
The process is running,  I should know here in about 20 minutes if it's going to succeed or not.

**Comment by grossmj** [comment]
Thanks! :+1:

**Comment by qcdebug** [comment]
Well, it's acting differently now.  I've tested it twice and it appears to write ~10GB of the export file (both tests were a different size) and GNS3 exits on me (is that intentional?) whereas it would crash before with an access error but stay open.    This is also trying to export off of bare metal instead of the local server with remote project.   Let me try the other way quick and see what that does.

**Comment by qcdebug** [comment]
This is going to take more time than expected, in my mucking around to get it running on bare metal I've apparently corrupted the original gns3 config that was running using a VM.   I'll have to recreate it but in the meantime, the above issue is happening with the current project.   It is writing the portable project but aborts part of the way through it and appears to be as it's compressing large files.   One project had just part of the images in it the other had a couple image files and part of the projects directory.    Let me know what help you need from me here.  I want to make sure this isn't something like an unoptimized connection or server timeout I can change before we put too much time into it.

**Comment by cioby23** [comment]
Similar issues were reported by others in the past and a new request was opened for it https://github.com/GNS3/gns3-server/issues/1349
This is set to be part of the new 2.2 release. Maybe this would help solve the import/export issue for large projects.

**Comment by grossmj** [comment]
I found multiple issues with the export (for instance the server cannot process requests while it is exporting a project. Also, the speed could be greatly improved by choosing the compression type or no compression at all). To summarise, there is a major refactor work needed regarding how we handle import/export. I am going to close this for now to focus on https://github.com/GNS3/gns3-server/issues/1349

**Comment by qcdebug** [comment]
I take this to mean you don't need anything from me on this aspect then?

**Comment by grossmj** [comment]
Correct. Only if you can test if everything works once we release our first
beta for 2.2 version. Thanks!

**Comment by qcdebug** [comment]
Sure!  Let me know and I'll give it a shot!
