### ISSUE TITLE
GNS3 VM grey out under server summary 

### ISSUE THREAD

**Issue by gapfriend** [GNS3/gns3-server#1528]
1. Description of issue and screenshots

I have been using GNS VM since last 6 months and today when I started, GNS VM showing grey out under servers summary. 

2. Steps you performed leading to the issue

Try different IPs to connect in host binding drop down menu but none of them is working. I understand loopback 127.0.0.1 supposed to be connected but no luck yet 

 Disable all FWs just in case, still no change

I tried to access GNS VM IP from my local browser but I cannot connect it.

**Comment by grossmj** [comment]
> I tried to access GNS VM IP from my local browser but I cannot connect it.

If your browser cannot, then the GNS3 Ui is unlikely to connect to the GNS3 VM. Have you tried to ping from you host OS?

**Comment by grossmj** [comment]
This doesn't appear to be a bug with GNS3. Please can you ask for help on https://gns3.com/community

Thank you.

**Comment by khanzia05** [comment]
i have gns3 2.2.8 and gns3vm2.2.5,  VMware workstation  player12.1. when i open gns3 gns3vm is opening automatically but showing grayed out. when i take cursor to grayed out gns3vm it popup is saying discovering or connecting to gns3vm.

I am able to do ssh to gns3vm.

Please help.

**Comment by raynerts** [comment]
I also have gns3 2.2.8, gns3 vm 2.2.8, VMware workstation 14, Pro, when I open gns3 it launch de gns3VM but stay in gray.

Thanksss

**Comment by nameinsoft** [comment]
> I also have gns3 2.2.8, gns3 vm 2.2.8, VMware workstation 14, Pro, when I open gns3 it launch de gns3VM but stay in gray.

this is my problem too is still gray too if u solve this plz email me 

nameinsoft@gmail.com 

this problem on my nerve.
