### ISSUE TITLE
gns3server API not returning list of VirtualBox VMs

### ISSUE THREAD

**Issue by jbieniasz** [GNS3/gns3-server#1531]
Hi,

I have a GNS3 server on remote GCP node (great tutorial: https://binarynature.blogspot.com/2018/08/gns3-v2-google-compute-engine.html) and I wanted to set using of VirtualBox also there. I installed VirtualBox from command line using 
https://www.virtualbox.org/wiki/Linux_Downloads and https://www.howtoforge.com/tutorial/running-virtual-machines-with-virtualbox-5.1-on-a-headless-ubuntu-16.04-lts-server/

Next, I used https://docs.gns3.com/1f6uXq05vukccKdMCHhdki5MXFhV8vcwuGwiRvXMQvM0/index.html to set `/etc/gns3/gns3_server.conf` with VirtualBox input:

```
vboxmanage_path = /usr/bin/VboxManage
vbox_user = root
```

First issue was detected with GNS3 GUI. It is not listing the VMs under remote server when I tried to add VirtualBox VMs in Preferences. I started to debug gns3server API myself to see where the problem is.

Indeed, executing `curl -X GET -H 'User-Agent: Python/3.6 aiohttp/2.3.10' -v -i 'http://loca
lhost:3080/v2/compute/virtualbox/vms'`  on server node locally returns an empty JSON array `[]`. However, log file (path `/var/log/gns3/gns3.log`) has these lines:

```
2019-02-23 13:01:05 INFO __init__.py:112 Executing VBoxManage with command: /usr/bin/VBoxManage --nologo list vms
2019-02-23 13:01:05 INFO helpers.py:534 127.0.0.1 [23/Feb/2019:13:01:05 +0000] "GET /v2/compute/virtualbox/vms HTTP
/1.1" 200 197 "-" "Python/3.6 aiohttp/2.3.10"
```
(root is added to `vboxusers`)

From the log I see that API request issued the shell command `/usr/bin/VBoxManage --nologo list vms` which is correct. I checked it manually and the result is as expected - one VM is present. This result should be packed as JSON part of 200 OK response, but it is not.

Could someone help me, if I did something wrong in configuration or is it a bug?
 
Best regards
JB

**Comment by grossmj** [comment]
One reason may be that the vmname contains the word `<inaccessible>`.

Can you post the result of `/usr/bin/VBoxManage --nologo list vms`? Can you execute this command with the same user you run GNS3 with?

Thanks

**Comment by jbieniasz** [comment]
1. how to check under which user GNS3 runs?
2. Results - I tried different combinations under my user logged from GCP (login based on email) and `root` user.
```
$ sudo vboxmanage list vms
"alpine" {ef848483-ad64-42ca-8ee0-587b8ce5f24a}
```

```
$ sudo su - root
$ sudo vboxmanage list vms
"alpine" {ef848483-ad64-42ca-8ee0-587b8ce5f24a}
```

**Comment by jbieniasz** [comment]
If you can, this issue can be removed. The problem was with users, privileges and registration of vms. Everything is ok now.

**Comment by grossmj** [comment]
Thanks for the feedback :+1:
