### ISSUE TITLE
Enhancement: Add total RAM and CPU to the 'Servers Summary'

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1532]
Today the 'Servers Summary' panel show only the free percentage of RAM and CPU. While this is valuable, it does not give any idea about the total HW resources (RAM/CPU) this server holds.
This makes it hard to understand the affect of adding  additional appliances and to manage placement when having more than a single remote server.

The total HW resources can be added even as simple as hover text for the server entry.

If this could be add, showing free/total disk allocated to gns3 can also be valuable for monitoring the remote server.

10x,
Doron

**Comment by grossmj** [comment]
Implemented.
