### ISSUE TITLE
Question: How can I get QEMU appliance IP address without logging in via console/telnet

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1535]
Hi,

I need to get the running appliances IP address. At the moment the only way I was able to do it is via console/telnet. I wish to check the IP without logging in.
I've trying to use libvirt or other command line utilities from the GNS3 server it seems that QEMU/KVM is not able to even see a running appliance.

The flowing command returned empty:
virsh list --all

Doron

**Comment by grossmj** [comment]
Do you want the guest IP address?

**Comment by doronbl** [comment]
I want to get the appliance running on top of (inside) GNS3 server.
Guest is a little bit confusing as my GNS3 is a guest by itself.

**Comment by grossmj** [comment]
You can get node information using our API http://api.gns3.net/en/2.1, for instance list the projects with
`curl 'http://127.0.0.1:3080/v2/projects'`, then get a project_id  and use `curl 'http://127..0.1:3080/v2/projects/65b352c4-f3df-4410-8d94-bea75d7e7e75/nodes'` to list all the nodes belonging to that project.

However, you won't get any information to what is inside a particular node (like the IP address and other settings). We have had the idea to use libguestfs http://libguestfs.org/ to expose some details but never implemented it. Additionally, I have seen that a Qemu guest agent available: https://pve.proxmox.com/wiki/Qemu-guest-agent and could possibly allow guest information to be exposed via our API.

**Comment by grossmj** [comment]
@doronbl any comments or questions?

**Comment by doronbl** [comment]
@grossmj Yes, I have.
Going back to my initial question: Why 'virsh list --all' command return empty lis?

I've found the below detailed description:
https://unix.stackexchange.com/questions/366823/how-to-determine-the-name-of-a-running-qemu-virtual-machine

From my POV, running qemu directly prevent me from having reach API to manage/monitor the VM.
In my case, I would like to get the VM IP address. I also don't wan, or cant adding hooks into my VMs specially to manage it using quest agent.

Can we run the VMs using some other fancy utility?

Doron

**Comment by grossmj** [comment]
Indeed, we do not use libvirt to run Qemu VMs. One of the reason is because we need to be able to run on Windows, macOS and Linux.

We have an opened issue to support libvirt: https://github.com/GNS3/gns3-server/issues/429

**Comment by grossmj** [comment]
Let's consider this for version 2.3
