### ISSUE TITLE
ACPI Shutdown Timeout should be configureable

### ISSUE THREAD

**Issue by neffs** [GNS3/gns3-server#1536]
The timeout for shutdown via ACPI in qemu is fixed to 30 seconds. This may not be enough for all applications. In my case a management appliance takes about 60 seconds to shut down.
It should be increased and/or be configureable in the appliance template.

**Comment by grossmj** [comment]
I will bump the timeout to 120 seconds in 2.1.13 and will see if we can allow this value to be configurable in version 2.2

**Comment by grossmj** [comment]
I think it is safe to close this since nobody complained about this, 120 seconds should be more than enough.
