### ISSUE TITLE
Virtualized Intel VT-x/EPT is not supported on this platform

### ISSUE THREAD

**Issue by ibbulbul** [GNS3/gns3-server#1538]
I am using G41M combo mother board with Intel core 2 quad Q9400 processor. This processor is supported Intel VT-X and VT-D. But when I run Vmware it shows "Virtualized Intel VT-x/EPT is not supported on this platform". I try to solve it many ways. I have used vmware v12 and v14. but same problem has occured. can any one tell me please what is the issue. I also updated bios but same problem remains. Please give a solution. I am suffering lot.

**Comment by cioby23** [comment]
Your CPU Intel core 2 quad Q9400 does not have support for Intel® VT-x with Extended Page Tables (EPT). It's an very old CPU. EPT table support was introduced beginning with Intel Core i3 i5 i7 series so there isn't much you can you if you require this but to upgrade the CPU.

**Comment by ibbulbul** [comment]
This CPU is supported VT-x and VT-d but not EPT. As your speech EPT also need for this solution of problem.

**Comment by SpockIsCoding** [comment]
My CPU is Intel(R) Core(TM) i5-12500H  and I've the same problem

**Comment by AnzeuS** [comment]
I create
