### ISSUE TITLE
Error in Running GNS3

### ISSUE THREAD

**Issue by parminder1514** [GNS3/gns3-server#1542]
Please help me out from this issue.. I am running GNS3 on Parrot Linux . GNS3 giving the following error when running from terminal.

$gns3
Traceback (most recent call last):
  File "/usr/local/bin/gns3", line 7, in <module>
    from gns3.main import main
  File "/usr/local/lib/python2.7/dist-packages/gns3/main.py", line 178
    print("".join(lines), file=sys.stderr)
                              ^

**Comment by grossmj** [comment]
Don't use Python 2.7. GNS3 will only run with Python 3.4 and above. Please post on https://community.gns3.com/community for requesting help. Thank you.
