### ISSUE TITLE
no inet IP on virbr0 > arch custom installation

### ISSUE THREAD

**Issue by stkac** [GNS3/gns3-server#1544]
Hi, I have gns3-server **2.1.14** running on an Arch server (user: gns3 group: gns3) and libvirt with all the dependencies what it need. Even i added the user [gns3] to the libvirt group.

each time when I start the client, I need destroy and create the default virbr0 for get IP and NAT service on the node.

```
# ifconfig virbr0
virbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 46:1a:86:36:a0:da  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41  bytes 14618 (14.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# virsh net-destroy default
Network default destroyed

[root@server gns3]# virsh net-start default
Network default started

# ifconfig virbr0
virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 10.0.0.255
        ether 52:54:00:97:72:75  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```
**but when I stop and close the client, inet IP gone and need start over again...**

Someone know how fix it?

Thanks in advance,

**Comment by grossmj** [comment]
Sorry, I do not know the answer. You may want to try on https://gns3.com/community, you can get help from other GNS3 users there.
