### ISSUE TITLE
Raw sockets support not enabled in uBridge on Fedora

### ISSUE THREAD

**Issue by zccing** [GNS3/gns3-server#1546]
Hello, I'm trying to connect the virtual switch Cisco to the real network. GNS3 issued the following error:

Error while sending command 'bridge add_nio_linux_raw b15db0fd-d81a-4246-84d7-d5efe2f11f09-0 "ens3"': Unknown command 'add_nio_linux_raw': uBridge version 0.9.14 running with libpcap version 1.9.0-PRE-GIT (with TPACKET_V3)
Hypervisor TCP contrl server started (IP 0.0.0.0 port 42161).
UDP tunnel connecting from local port 10012 to IPv4 addresss 127.0.0.1 on port 10013

$ uname -a
Linux gns3 4.20.13-200.fc29.x86_64 #1 SMP Wed Feb 27 19:42:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ gns3server --version
2.1.11
$ ubridge -v
ubridge version 0.9.14
$ nmcli connection show
NAME           TYPE        DEVICE     
ens3              ethernet    ens3       
gns3tap0-0    tun            gns3tap0-0 
virbr0             bridge       virbr0

**Comment by grossmj** [comment]
Have you compile uBridge yourself?

**Comment by zccing** [comment]
@grossmj I installed it via 'dnf'.

**Comment by grossmj** [comment]
Try the following command:

setcap cap_net_admin,cap_net_raw=ep /usr/local/bin/ubridge

**Comment by zccing** [comment]
I executed the command, but I still get an error.
`$  **setcap cap_net_admin,cap_net_raw=ep /usr/bin/ubridge**

unable to set CAP_SETFCAP effective capability: Operation not permitted
$ **sudo setcap cap_net_admin,cap_net_raw=ep /usr/bin/ubridge/**`

The `ubridge` command for the fedora distribution is in the `/usr/bin/` directory.
`$ **rpm -ql ubridge**

/usr/bin/ubridge
/usr/lib/.build-id
/usr/lib/.build-id/52
/usr/lib/.build-id/52/c69bbad32caec6339da1e4c26e36c21720a734
/usr/share/doc/ubridge
/usr/share/doc/ubridge/README.rst
/usr/share/licenses/ubridge
/usr/share/licenses/ubridge/LICENSE`

**Comment by zccing** [comment]
I executed the command, but I still get an error.
`$ setcap cap_net_admin,cap_net_raw=ep /usr/bin/ubridge

unable to set CAP_SETFCAP effective capability: Operation not permitted
$ sudo setcap cap_net_admin,cap_net_raw=ep /usr/bin/ubridge/`

The ubridge command for the fedora distribution is in the /usr/bin/ directory.
`$ rpm -ql ubridge

/usr/bin/ubridge
/usr/lib/.build-id
/usr/lib/.build-id/52
/usr/lib/.build-id/52/c69bbad32caec6339da1e4c26e36c21720a734
/usr/share/doc/ubridge
/usr/share/doc/ubridge/README.rst
/usr/share/licenses/ubridge
/usr/share/licenses/ubridge/LICENSE`

**Comment by grossmj** [comment]
It looks like uBridge was not compiled with raw socket support hence why you get `Unknown command 'add_nio_linux_raw'`

https://github.com/GNS3/ubridge/blob/master/Makefile#L59
https://github.com/GNS3/ubridge/blob/634062b90d106af7af368d50182029ecfb9d4f19/src/hypervisor_bridge.c#L483

I recommend you uninstall the version install via 'dnf' and manually compile uBridge. Download the source from https://github.com/GNS3/ubridge/archive/v0.9.14.tar.gz and follow the instructions on https://github.com/GNS3/ubridge#installation

Also, what version of Fedora are you on? I would want to check why the uBridge package does not come with the RAW socket support.

**Comment by grossmj** [comment]
I tested on Fedora 29 and indeed uBridge installed via "dnf" does not support RAW sockets. I will contact the package maintainer.

**Comment by zccing** [comment]
ok,Thank you

**Comment by grossmj** [comment]
I will re-open to remind me to contact the package maintainer.

**Comment by athmane** [comment]
This update [1] should fix the issue, basically CFLAGS are overridden during build with hardened flags, now I simply appended the additional flag there.

[1] https://bodhi.fedoraproject.org/updates/FEDORA-2019-8be456c50a

Here's a test:
```


[athmane@devel2 ~]$ rpm -q ubridge
ubridge-0.9.14-3.fc29.x86_64

[athmane@devel2 ~]$ echo -e 'hypervisor cmd_list bridge\n \003;' | nc localhost 2232
101 list (min/max args: 0/0)
101 set_pcap_filter (min/max args: 1/2)
101 reset_packet_filters (min/max args: 1/1)
101 delete_packet_filter (min/max args: 2/2)
101 add_packet_filter (min/max args: 2/10)
101 stop_capture (min/max args: 1/1)
101 start_capture (min/max args: 2/3)
101 add_nio_ethernet (min/max args: 2/2)
101 add_nio_tap (min/max args: 2/2)
101 add_nio_unix (min/max args: 3/3)
101 delete_nio_udp (min/max args: 4/4)
101 remove_nio_udp (min/max args: 4/4)
101 add_nio_udp (min/max args: 4/4)
101 rename (min/max args: 2/2)
101 reset_stats (min/max args: 1/1)
101 get_stats (min/max args: 1/1)
101 show (min/max args: 1/1)
101 stop (min/max args: 1/1)
101 start (min/max args: 1/1)
101 delete (min/max args: 1/1)
101 create (min/max args: 1/1)
100-OK


[athmane@devel2 ~]$ rpm -q ubridge
ubridge-0.9.14-5.fc31.x86_64

[athmane@devel2 ~]$ echo -e 'hypervisor cmd_list bridge\n \003;' | nc localhost 2232
101 list (min/max args: 0/0)
101 set_pcap_filter (min/max args: 1/2)
101 reset_packet_filters (min/max args: 1/1)
101 delete_packet_filter (min/max args: 2/2)
101 add_packet_filter (min/max args: 2/10)
101 stop_capture (min/max args: 1/1)
101 start_capture (min/max args: 2/3)
101 add_nio_linux_raw (min/max args: 2/2)    <============
101 add_nio_ethernet (min/max args: 2/2)
101 add_nio_tap (min/max args: 2/2)
101 add_nio_unix (min/max args: 3/3)
101 delete_nio_udp (min/max args: 4/4)
101 remove_nio_udp (min/max args: 4/4)
101 add_nio_udp (min/max args: 4/4)
101 rename (min/max args: 2/2)
101 reset_stats (min/max args: 1/1)
101 get_stats (min/max args: 1/1)
101 show (min/max args: 1/1)
101 stop (min/max args: 1/1)
101 start (min/max args: 1/1)
101 delete (min/max args: 1/1)
101 create (min/max args: 1/1)
100-OK


```

**Comment by grossmj** [comment]
@athmane that's great. Thanks for the update and fixing this :+1:
