### ISSUE TITLE
Feature Request: Avoid Download and Import of image  steps when importing new QEMU appliance

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1552]
Hi Team,

When working with remote server configuration and with QEMU appliance, assuming I have a download URL in the appliance template, I do not see why GNS3 should first download the appliance image locally and than imported to the remote server.
If I have URL, why not asking the remote server to perform the download/import and avoid the additional hope of downloading the image to the local 'Downloads' directory?

Doron

**Comment by grossmj** [comment]
Indeed, there is some improvement to do. Images could be downloaded directly on the remote server excepting if the image must be downloaded from a restricted website like Cisco CCO.

**Comment by doronbl** [comment]
In this case, the user should be able to perform 'import' in case the server does not have a way to download the image.
Anyway, today there is a 'Download' option regardless of the ability to download the image. So this will also fail for restricted websites.
My suggestion is to move the 'Download' to the server side, and leave an import option.

When moving to this new way of work, all images imported should go to the 'main' server only. From there, remote servers should further download the required image when an appliance is placed by the user. Meaning, the main server image location should act as an image store for other remote servers.

**Comment by ibarrere** [comment]
I too am in favor of this. There is quite a bit of latency between me and the remote server, and my VPN throughput to the remote server is not great. My usual workflow is initiating a download from the Cisco website, copying the URL during the download negotiation phase, stopping the download, then pulling the file with wget on the remote server (only works if your source public IP is the same as the remote server). Being able to simply specify a location on the remote server for an image would be great.
