### ISSUE TITLE
iourc_path in gns3_server.conf not working on 2.2.0a2

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-server#1555]
2.2.0a2
GNS3vm and Lubuntu installed gns3 both has this problem.
I had set the “iourc_path = something” in section [IOU] in gns3_server.conf 
But it seems the gns3server ignore it ,and now it only can be used by gns3 gui set the iou license on client side.
the gns3_server.conf  I put to /home/myusername/.config/GNS3/gns3_server.conf

**Comment by grossmj** [comment]
I didn't find any issue. The GNS3 server will default to one of the following file if it cannot open the one specified by `iourc_path`

* iourc file in a temporary directory which is the content of the iourc sent by the controller/GUI.
* One in the home directory: `~/.iourc`
* iourc file in the node directory, for instance `project-files/iou/bd9d5076-7ba8-457c-a6c9-e26dfd85c84b/iourc`

**Comment by superwolfboy** [comment]
> I didn't find any issue. The GNS3 server will default to one of the following file if it cannot open the one specified by `iourc_path`
> 
> * iourc file in a temporary directory which is the content of the iourc sent by the controller/GUI.
> * One in the home directory: `~/.iourc`
> * iourc file in the node directory, for instance `project-files/iou/bd9d5076-7ba8-457c-a6c9-e26dfd85c84b/iourc`

I found the problem, maybe it is my problem.
On version 2.2.0a2
On GNS3 GUI client, Click Preferences - ios on Unix,and **uncheck** "Checek valid IOU license key“ （iou license text box is empty this moment). It is working fine. Means when the iou license text box empty AND "Check valid IOU license key" is checked, the problem will appear even if the iourc_patch is specified.

And then I do more test:
On version 2.1.15
iourc_path is specified, leave iou license textbox empty, and **check** "Check valid IOU license key", It is still working.

So maybe there is some logical differences between these two versions.

**Comment by grossmj** [comment]
@superwolfboy which behaviour you think is the best?

**Comment by grossmj** [comment]
> On GNS3 GUI client, Click Preferences - ios on Unix,and uncheck "Checek valid IOU license key“ （iou license text box is empty this moment). It is working fine. Means when the iou license text box empty AND "Check valid IOU license key" is checked, the problem will appear even if the iourc_patch is specified.

I have changed that, the problem will not appear if the iourc_path setting is configured.

**Comment by superwolfboy** [comment]
I am very sorry that I did not login the github for a long time cause alway outside this month .
The behaviour as 2.1.15 is better that you already do is better I think.
Thank you very much.
