### ISSUE TITLE
Question: Upgrade remote server

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1557]
Hi Team,

What is the procedure of upgrading remote server which was installed using remote-install.sh script?

I'm using version 2.1.11

Doron

**Comment by grossmj** [comment]
I think I simple `sudo apt-get update && apt-get upgrade` should be enough to upgrade GNS3 itself or you may re-run the remote-install.sh script.

**Comment by grossmj** [comment]
@doronbl let us know if this has worked as expected. I will close this for now. Thanks :+1:

**Comment by doronbl** [comment]
@grossmj   re-run the remote-install.sh did the work
I've rebooted the host after the installation to make sure all is freshly loaded
