### ISSUE TITLE
Question: How to install a specific version of server on bare metal

### ISSUE THREAD

**Issue by cmessin1** [GNS3/gns3-server#1560]
I have a situation where I cannot upgrade a server an client currently but need to deploy another server with the same version (2.1.11)

Could anyone give me a hint on how to get that exact version deployed on Ubuntu?

Thanks.

**Comment by cioby23** [comment]
You can use **pip3 install gns3-server==2.1.11** on Ubuntu.

**Comment by cmessin1** [comment]
Got it.  Thanks.
