### ISSUE TITLE
Cannot connect to VirtualBox host only network adapter

### ISSUE THREAD

**Issue by CameronNemo** [GNS3/gns3-server#1563]
GNS3 complains that there is no netmask set for the interface `vboxnet0`, even though there is a netmask.

GNS3 2.1.14, latest macOS

```
$ ifconfig vboxnet0
vboxnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00
	inet 172.28.128.1 netmask 0xffffff00 broadcast 172.28.128.255
```

**Comment by grossmj** [comment]
Are you trying to connect to a cloud with vboxnet0 configured?

**Comment by CameronNemo** [comment]
Yes.

**Comment by grossmj** [comment]
Sorry, this does not work: https://github.com/GNS3/gns3-server/issues/990

An alternative solution is to create a bridge and add vboxnet0 to it.

**Comment by gaertner-mike** [comment]
> Sorry, this does not work: #990
> 
> An alternative solution is to create a bridge and add vboxnet0 to it.

Does anyone have an example for this? 

I added a bridge interface and added vboxnet0; even added a ip address and netmask just to test it, also tried several variations bridging vboxnet0 to any other interfaces 

same result :

```
Interface bridge1 has no netmask, interface down?
```

```
bridge1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
         options=3<RXCSUM,TXCSUM>
	ether f6:5c:89:dc:41:01 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: vboxnet1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 20 priority 0 path cost 0
	member: en0 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	media: autoselect
	status: active
```
