### ISSUE TITLE
Start/Resume on multiple devices has intermittent failures

### ISSUE THREAD

**Issue by TomCos** [GNS3/gns3-server#1564]
Hey Team,

Will try to explain this as clear as I can.  I have some projects that have anywhere from 5-25 devices, most IOU (L2 and L3), but some Micro Core Linux as well.  When I drag/select a specific few, or when I click the Start/Resume all button, usually one or two of them will refuse to start.  I can click on that specific device and right click start again, but nothing.  Left click just opens the config menu.  Trying to open the console on it spits out a "node needs to be started" error.  The only way I can get it to start is to shut **all** they devices down and try again.  The result is either everything will go smoothly, or another one will not start, so have to try again.

More than happy to provide more data, but right now I'm only seeing this log (for example) on the devices that won't start:

192.168.174.1 [25/Mar/2019:04:07:33 +0000] "POST /v2/compute/projects/928bf6a2-905d-48db-9979-c7ada6d30e03/iou/nodes/d0956201-97ba-43c9-b764-1f0d6216ffff/start HTTP/1.1" 200 959 "-" "Python/3.6 aiohttp/2.3.10"

Nothing else though.  Let me know what other logs I can send over, no issue.  Been having the issue since 2.1.12, but not sure if it's directly related to that release (I have no data to prove it is).

**Comment by grossmj** [comment]
Thanks for posting. I have a few questions: What is your operating system? Do you use the GNS3 VM?

**Comment by TomCos** [comment]
Of course, sorry I should have included that information.  Windows 10 Professional x64 Build 1809, but the issue was occurring before 1809 as well.  Yes I am using the GNS3 VM, which is up to date, both the GUI and VM are running 2.1.15, but same story, been happening for a while.  I assume I've kept the VM running up to date.  I only update it through the basic GUI.  Assuming that's correct, it's still running 14.04.6 LTS.

**Comment by TomCos** [comment]
Ok so been trying to generate some useful data here.  Found something that is definitely useful.

When clicking start on all of them, it looks like the router is still starting in the background, but GNS3 is not seeing it.  I noticed the process was in the list for one of them that wouldn't start.  I had an old SecureCRT session for it still up, just disconnected.  When I reconnected it, it connected to the router.  In the GNS3 GUI however, like I said originally, it still thinks it's down.  Double clicking it brings up the configuration menu and right clicking and asking to open the terminal just generates a "This node must be started before a console can be opened" error.

Now that's something!  Thinking about it though, I have seen similar behavior of the opposite, but didn't think they were related until now.  Every once in a while, when I press the stop all button, even though everything is shut down, the GUI will keep spitting out a, for example, "Host1 is stopping" progress bar that never finishes.  It won't go away and re-appears every few seconds, so I assume it probably can't tell the device actually stopped, similarly to it not seeing the device has actually started.

Hope this helps.  Let me know which logs, if any, I can provide,  Actually sounds like it might be an front end issue.

**Comment by grossmj** [comment]
I suspect a connection issue with the Websocket notification system that let the GUI know about events. I will see if I can fix this in 2.2 since I am afraid to break something in 2.1.x

**Comment by grossmj** [comment]
I have added some code on how we handle WebSocket to received notifications (a node a started, stopped etc.)

Also, this may have fixed the issue too: https://github.com/GNS3/gns3-gui/issues/2765

Let's monitor this in the next release of version 2.2. Please comment back here if you still experience issues.
