### ISSUE TITLE
In upload handler missing host on "Files on" line

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#157]
Just a small cosmetic glitch:

Starting with 1.3.0 the upload handler (http://ip:8000/upload) doesn't display the host on the header line of the file list. The "Files on" header line just looks a little bit strange.

I changed line 43 in handlers/upload_handler.py from
```
        response.template("upload.html", files=uploaded_files)
```
to
```
        response.template("upload.html", files=uploaded_files, gns3_host=request.host)
```

**Comment by noplay** [comment]
Thanks!
