### ISSUE TITLE
telnet embedded shell support broken.

### ISSUE THREAD

**Issue by Jean-Daniel** [GNS3/gns3-server#1574]
commit 60ac6d2dfeecef9fbf59018ba69d3e4e9b9673de broke support for embed_shell (embed_shell.py).

The embed shell connection factory does not support the new callback argument (so calling the factory raise an exception because 3 positional parameters are passed to a function taking only 2 parameters), and the window_size_changed() method returns None causing an exception when trying to yield from the result.

**Comment by grossmj** [comment]
Fixed, thanks for catching this.
