### ISSUE TITLE
Discussion about legacy Cisco ASA support

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1579]
We have dropped the legacy Cisco ASA support in version 2.2 however some users pointed out the following:

> This is the only way to emulate ASA multi-context as it is not supported on ASAv. Can this feature be retained?

Should we still support legacy ASA because of this?

**Comment by adosztal** [comment]
On one hand, it is great for power users who have deeper knowledge of GNS3. On the other hand, beginners find it confusing and we get a lot of support questions where the answer is "run ASAv".

What about keeping it but doing one or more of the following:
- A huge warning when someone tries to add or import legacy ASA.
- Keep it "hidden" and make it available only after checking a checkbox in the preferences.
- Ask the user during install if they want to enable it and make "no" the default option.

**Comment by grossmj** [comment]
Legacy ASA support is back, still with a big warning ;)
