### ISSUE TITLE
Communication to QEMU monitor flaky with backport of Qemu link plugged/unplugged feature

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-server#1582]
GNS3 v2.1.16 on Linux and macOS

I need to stay on v2.1, but the qemu link plugged/unplugged feature was too good to miss, so I backported it. It  includes the commits c7875f93a3b55ac4642d85793e017dfd8b9155a7, cde30f8f53cadebfd50b56b75aa1156079578d3d and a40fdb3641de792b36820fa91af90fad563eea90.  Please note, that the link suspension changes are not included.
Backport from 2.2: [qemu_detect_link_plugged_unplugged.patch.txt](https://github.com/GNS3/gns3-server/files/3085606/qemu_detect_link_plugged_unplugged.patch.txt)

This is mainly for my private use. I don't recommend it for general use, as it's a too big change for a stable release.

But I found an issue with this backport. The connection to the qemu monitor is closed faster than the transmission/execution of the commands. Therefore only some commands are executed. Of course, this could be just an issue of the backport, but it could also affect v2.2. That's the reason for creating this issue.

My solution is to wait for the echo of the command, before the next command is sent or the connection is closed. That way I get a stable command execution, tested on Linux and macOS.

For `_control_vm` it's easy: read the welcome message, send the command, then read the next line with the command echo. `_control_vm_commands` is a bit trickier as a command can output a variable number of lines. Therefore the lines are read until the command is found in the input.

Here my patch after applying the backported patch:
```
diff --git a/gns3server/compute/qemu/qemu_vm.py b/gns3server/compute/qemu/qemu_vm.py
index 9f990819..ae7294a7 100644
--- a/gns3server/compute/qemu/qemu_vm.py
+++ b/gns3server/compute/qemu/qemu_vm.py
@@ -1047,7 +1047,9 @@ class QemuVM(BaseNode):
                 return result
 
             try:
+                yield from reader.readline()    # welcome message
                 writer.write(command.encode('ascii') + b"\n")
+                yield from reader.readline()    # echo of the command
             except OSError as e:
                 log.warn("Could not write to QEMU monitor: {}".format(e))
                 writer.close()
@@ -1084,7 +1086,15 @@ class QemuVM(BaseNode):
             for command in commands:
                 log.info("Execute QEMU monitor command: {}".format(command))
                 try:
-                    writer.write(command.encode('ascii') + b"\n")
+                    cmd_byte = command.encode('ascii')
+                    writer.write(cmd_byte + b"\n")
+                    while True:
+                        line = yield from asyncio.wait_for(reader.readline(),
+                                                           timeout=3)
+                        if not line or cmd_byte in line:
+                            break
+                except asyncio.TimeoutError:
+                    log.warning("Missing echo of the command")
                 except OSError as e:
                     log.warning("Could not write to QEMU monitor: {}".format(e))
             writer.close()
```

**Comment by grossmj** [comment]
@b-ehlers I am ok to backport this feature but I am currently away and haven't had time to do it.

**Comment by b-ehlers** [comment]
If you like you can use this backport, but that was not the intention for creating this issue. The backport shows some anomalies, that might happen also in the v2.2 implementation. So this is meant as a hint to have a look at the 2.2 version.

**Comment by cioby23** [comment]
I have did some tests with the Qemu plugged/unplugged feature on the latest 2.2.0a5 release for IOSvL3 and IOSvL2 images and I saw that by default only 2 or 3 ports go in downstate after turning on the devices and all other ports remain in up state. I'm not sure if this issue is related to @b-ehlers findings.

**Comment by grossmj** [comment]
Looks like did something in version 2.2 to tackle the same problem by waiting to be connected to the Qemu monitor: https://github.com/GNS3/gns3-server/blob/2.2/gns3server/compute/qemu/qemu_vm.py#L1036

Anyway, I have implemented your patch since it ensures commands are executed. I don't know if this is going to help for the problem reported by @cioby23 though since I couldn't reproduce it. Let's see after the next release.

**Comment by cioby23** [comment]
I just did some new tests with the latest version 2.2.0 beta 1 and the Qemu plugged/unplugged feature works as expected.
By default when I start an IOSvL2 image all ports are in down state. After I connect two ports on different IOSvL2 images both ports go in up/up state.

**Comment by grossmj** [comment]
Great, thanks for the feedback :)
