### ISSUE TITLE
GNS3 server log rotation

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1586]
Hi team,

I would like asking a new feature of GNS3 server log rotation and retention. At the moment it seems that GNS3 server is writing to the same log file without monitoring its size. On one of my setups the log reached 4G:
```
ls -lh /var/log/gns3/gns3.log
-rw-rw---- 1 gns3 gns3 4.2G Apr 25 03:54 /var/log/gns3/gns3.log
```

I would like to suggest:
log rotation - active log file will be closed after X configurable size
log retention - only X number historical of logs will be kept on the system
log compression - inactive (historical) logs will be kept in compressed mode to save disk resources

Doron

**Comment by grossmj** [comment]
Implemented, now you have the following parameters when you start the GNS3 server ```--logmaxsize=100000000 --logbackupcount=10 --logcompression```

Default max size for one log file is 1GB, should we have less?

**Comment by doronbl** [comment]
@grossmj I think 1G is too large. Most of the text editors either vi or Nptepad++ will take some time to open such big file.
I think 5mega or 10mega should be more than enough. Do not forget you have the backup count which enable you to practically have any history window you would like even on small size files.

**Comment by grossmj** [comment]
@doronbl agreed, 1G is too large. I will switch to 10M.

**Comment by b-ehlers** [comment]
Two bugs:

> gns3server/run.py
> `"logmaxsize": config.get("logfile", 10000000),  # default is 10MB`

The option "logfile" is used to define the logmaxsize, I assume the option "logmaxsize" is meant.

> gns3server/web/logger.py
> `def init_logger(level, logfile=None, max_bytes=1000000000, backup_count=10, compression=True, quiet=False):`

The parameter max_bytes should be set also to the new default log size of 10MB.

**Comment by grossmj** [comment]
@b-ehlers thanks, I have fixed these 2 bugs.
