### ISSUE TITLE
Receiving "405: Method Not Allowed" when trying to get a list of cloud nodes or switch nodes

### ISSUE THREAD

**Issue by MiniMe4GH** [GNS3/gns3-server#1593]
Hiy guys

I am toying with the REST APIs and I am having problems with adding cloud nodes and ethernet_switch nodes.
Even if the call succeeds (I get back the objects just created) the above type of nodes do not show up in the gui
Moreover, when I try to retrieve the nodes in that category for that project I get a "405 Method not allowed" for bot types

I am using GET, Postman and this type of link
http://10.9.225.22:3080/v2/compute/projects/2ad90c71-526c-4fd8-8c78-d7193c14fd1d/cloud/nodes

if it maters here is what I am seeing at the server end
2019-05-31 13:45:50 INFO helpers.py:534 10.9.225.254 [31/May/2019:13:45:50 +0000] "GET /v2/compute/projects/2ad90c71-526c-4fd8-8c78-d7193c14fd1d/cloud/nodes HTTP/1.1" 405 212 "-" "PostmanRuntime/7.13.0"

**Comment by grossmj** [comment]
Looks like you should have used the controller API. Please use a POST method to create a new node: http://api.gns3.net/en/2.2/curl.html#create-nodes

**Comment by MiniMe4GH** [comment]
If I try this URL
http://10.9.225.22:3080/v2/projects/2ad90c71-526c-4fd8-8c78-d7193c14fd1d/cloud/nodes
I get a 404 not found

**Comment by grossmj** [comment]
> If I try this URL
http://10.9.225.22:3080/v2/projects/2ad90c71-526c-4fd8-8c78-d7193c14fd1d/cloud/nodes
I get a 404 not found

This should work:

```curl -X POST "http://localhost:3080/v2/projects/b59365d4-2533-4961-b791-589f728f24ca/nodes" -d '{"name": "My cloud", "node_type": "cloud", "compute_id": "local"}'```

> The other thing that I do not understand is why you can't use templates to create these things (the built in ones) In this respect the API does not seem consistent

I am going to look at this and fix it.

**Comment by grossmj** [comment]
What version of GNS3 have you used?

**Comment by MiniMe4GH** [comment]
OK it worked...I got really confused by the compute and controller APIs and I never clicked on the Endpoints link to get to read that page

**Comment by grossmj** [comment]
I agree, it could be better. We plan to redo the API documentation using something like https://swagger.io/

**Comment by MiniMe4GH** [comment]
Please close this one I think I am good now, once you pointed me to the warning on this page
http://api.gns3.net/en/2.2/endpoints.html#compute-endpoints

You guys could add that warning at the top of the documentation. The reader starts reading from top to bottom but then in the process it might branch the reading to other things ...in my case all was smooth till I got to create clouds and then I missed the "Endpoints page" that get into details and I landed in the api folder on github where the warning is not there so I kept rambling in the weeds  till you got me out :-) 

So to improve the documentation that warining should sit on the first page

**Comment by MiniMe4GH** [comment]
> What version of GNS3 have you used?

I am using 2.16 bare bone install (no VM)  on Ubuntu 18.04 LTS

**Comment by grossmj** [comment]
I am going to keep this one opened for now so I remember to change the documentation. Thanks :+1:

**Comment by ziajka** [comment]
Ref: https://github.com/GNS3/gns3-server/issues/1686
