### ISSUE TITLE
REST API: What is the difference between projects defined at controller level and at compute level?

### ISSUE THREAD

**Issue by MiniMe4GH** [GNS3/gns3-server#1594]
REST API: What is the difference between projects defined at controller level and at compute level?
Which one should I use?

**Comment by grossmj** [comment]
Please only use the API at the controller level. The computer level is internal only.

**Comment by grossmj** [comment]
http://api.gns3.net/en/2.2/endpoints.html#compute-endpoints

> Warning These endpoints should be considered low level and private. They should only be used by the controller or for debugging purposes.
