### ISSUE TITLE
Missing fix in version 2.1.20 - wrong keyserver port

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1596]
Hi,

In the past I have opened a bug regarding remote-install.sh script keyserver port, due to which master now have the following line:
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A2E3EF7B

While in version 2.1.20 the line does not include port 80:
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A2E3EF7B

So the installation is failing due to firewall rules.
I could not find the bug opened for this issue before.

We need to merge this change to v2.1.20 or any other version.
Also, if we missed this bug merge, which other bug fixes are missing as well??

Doron

**Comment by grossmj** [comment]
> We need to merge this change to v2.1.20 or any other version.

Done, however we have always used the script on the master branch in our documentation so I think there was no consequences that this was not done on the 2.1 and 2.2 branches.

> Also, if we missed this bug merge, which other bug fixes are missing as well??

For reference, this was the change done in August 2018 on the master branch, so all is good, we haven't missed bug fixes :)

https://github.com/GNS3/gns3-server/commit/57cb457b5ded356bab617693908624d2c62652f2#diff-116c7b63cb02224e9c891eee25a02d2b
