### ISSUE TITLE
Question: ubridge.log log size is getting very big (+4G)

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1598]
Hi Team,

On one of our systems we have seen that ubridge.log can grow to very large size (beyond 4G). When looking at the file content it seems to include packet sniffing content (dump).

Is the content of the file due to user direct actions, or is it default behavior. How can we avoid this content from being logged?

Doron

**Comment by grossmj** [comment]
> the file content it seems to include packet sniffing content (dump).

Packet sniffing is only enabled if debug mode has been enabled for the GNS3 server. Have you started the GNS3 server with the debug parameter?

**Comment by doronbl** [comment]
@grossmj Yes, server was running with debug mode

**Comment by grossmj** [comment]
Ok, I think we should reduce the debug level for uBridge (no packets dump) when debug mode is activated for the GNS3 server.

**Comment by grossmj** [comment]
Done
