### ISSUE TITLE
Error running gns3-server

### ISSUE THREAD

**Issue by amankumarjain** [GNS3/gns3-server#160]
File "/usr/local/lib/python2.7/dist-packages/gns3_server-1.3.2.dev1-py2.7.egg/gns3server/server.py", line 73
    server = yield from self._loop.create_server(handler, self._host, self._port, ssl=ssl_context)

**Comment by noplay** [comment]
Python 2.7 is not supported. You need to install it with python 3.

**Comment by noplay** [comment]
Python 3.4 is the best option. Python 3.3 should work.

**Comment by amankumarjain** [comment]
ok, do i need to install dynamips before installing gns-server??

**Comment by noplay** [comment]
No, you can use the server with just VPCS, Virtualbox or iou

**Comment by amankumarjain** [comment]
Is it possible to manage this server without installing gns3-gui? 
actually gns3-gui throwing a lot of error during its execution.

**Comment by noplay** [comment]
Not really. Which distribution are you using? We have install instructions for some of them.

**Comment by amankumarjain** [comment]
I am using Ubuntu 14.04

**Comment by amankumarjain** [comment]
So, first i have to install gns-gui, ok let me check again, btw thank you.

**Comment by noplay** [comment]
The readme of both project contain install instructions for Ubuntu:
https://github.com/GNS3/gns3-gui#linux-debian-based
https://github.com/GNS3/gns3-server#linux-debian-based

I hope it can help you

On Mon, Apr 27, 2015 at 11:15 PM, Aman Kumar Jain <notifications@github.com>
wrote:

> So, first i have to install gns-gui, ok let me check again, btw thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-server/issues/160#issuecomment-96824085>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by amankumarjain** [comment]
After successfull installation of gns3-server no user with name gns has created, upstart file is using a user, but there is no such user.

**Comment by noplay** [comment]
you need to change the user for one of your system.

On Mon, Apr 27, 2015 at 11:52 PM, Aman Kumar Jain <notifications@github.com>
wrote:

> After successfull installation of gns3-server no user with name gns has
> created, upstart file is using a user, but there is no such user.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-server/issues/160#issuecomment-96831354>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by amankumarjain** [comment]
but there is no gns user, do i have to create it manually, because gns-server script dont created any such user in my system

**Comment by amankumarjain** [comment]
GNS-GUI inatlled successfully, but now there is some issue in upstart file

**Comment by noplay** [comment]
You need to modifi the upstart script in order to use your user.
Le 28 avr. 2015 00:00, "Aman Kumar Jain" <notifications@github.com> a
écrit :

**Comment by amankumarjain** [comment]
ok thats fine, thats mean there is no such gns3 user.
How i will know what HTTP REST request gns3-gui make to server, because i am creating a web based UI to interact with gns3-server.

**Comment by amankumarjain** [comment]
Hello,
Where to find HTTP Rest request data.

**Comment by noplay** [comment]
This should help you:
https://community.gns3.com/community/connect/community-blog/blog/2015/04/27/reverse-gns-3-communication-between-client-and-server

On Tue, Apr 28, 2015 at 6:09 AM, Aman Kumar Jain <notifications@github.com>
wrote:

> Hello,
> Where to find HTTP Rest request data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-server/issues/160#issuecomment-96904473>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by amankumarjain** [comment]
Thank you :+1:
