### ISSUE TITLE
i386 architecture will be dropped starting with Ubuntu 19.10

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#1601]
https://lists.ubuntu.com/archives/ubuntu-devel-announce/2019-June/001261.html

This will be an issue for IOU support.

**Comment by grossmj** [comment]
Thanks for the heads up. This could be a solution around it: https://github.com/GNS3/gns3-gui/issues/1508

**Comment by b-ehlers** [comment]
As long as Ubuntu 18.04 is supported (April 2023), GNS3 could use their 32 bit libraries. Just a handful of libraries are needed. See <https://git.bernhard-ehlers.de/ehlers/gns3-docker-images/src/branch/master/iou-base/debian-get_libc-i386> which libs are used for the dockerized IOU, the same are needed for a non-Docker solution. We just need to fetch these libs from a distribution, that still supports i386, it even doesn't need to be Ubuntu (although I would choose Ubuntu as they support i386).

**Comment by adosztal** [comment]
They changed their mind: https://ubuntu.com/blog/statement-on-32-bit-i386-packages-for-ubuntu-19-10-and-20-04-lts
