### ISSUE TITLE
VirtualBox nested virtualization warning message

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1610]
Show a warning message that nested virtualization is not supported for VirtualBox only for version below 6.0 and if processor is not AMD.

Remove the warning on GUI side: https://github.com/GNS3/gns3-gui/blob/2.1/gns3/dialogs/setup_wizard.py#L144

**Comment by grossmj** [comment]
The server could detect the version of VMware and the type of CPU (Intel vs AMD), then give a warning  that nested virtualization is not enabled.

**Comment by cioby23** [comment]
VirtualBox nested virtualization for Intel CPUs will be supported in VirtualBox 6.1 which is close to release. Change Log
https://forums.virtualbox.org/viewtopic.php?f=15&t=95711

**Comment by grossmj** [comment]
@cioby23 great news! thanks :+1:

**Comment by b-ehlers** [comment]
VirtualBox 6.1.0 is released (2019-12-10). According to the [changelog](https://www.virtualbox.org/wiki/Changelog-6.1) it supports Intel CPUs starting with 5th generation Core i, codename Broadwell. As my CPU is older, I can't test it.
