### ISSUE TITLE
Is it possible to use the APIs to add ports to the Ethernet hub or switch?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1615]
There is no option to configure the template to increase the number of interfaces. The only way to do it is manually but... I am working to automate a lab :-) So I either change the template prior to adding the appliance or add more ports via APIs

**Comment by grossmj** [comment]
This will be easier using GNS3 version 2.2. First, you must create a custom Ethernet hub or switch.

Here is an example:

```
curl -X POST "http://127.0.0.1:3080/v2/templates" -d '{"compute_id": "local", "name": "My hub template", "template_type": "ethernet_hub"}'
{
    "builtin": false,
    "category": "switch",
    "compute_id": "local",
    "default_name_format": "Hub{0}",
    "name": "My hub template",
    "ports_mapping": [
        {
            "name": "Ethernet0",
            "port_number": 0
        },
        {
            "name": "Ethernet1",
            "port_number": 1
        },
        {
            "name": "Ethernet2",
            "port_number": 2
        },
        {
            "name": "Ethernet3",
            "port_number": 3
        },
        {
            "name": "Ethernet4",
            "port_number": 4
        },
        {
            "name": "Ethernet5",
            "port_number": 5
        },
        {
            "name": "Ethernet6",
            "port_number": 6
        },
        {
            "name": "Ethernet7",
            "port_number": 7
        }
    ],
    "symbol": ":/symbols/hub.svg",
    "template_id": "3ff046e7-c082-4dc4-95e9-b6a40b828052",
    "template_type": "ethernet_hub"
}
```

Then you can change the number of ports by adding or removing items from the ports_mapping entry:

Hub template with 8 port:

```
curl -X PUT "http://127.0.0.1:3080/v2/templates/3ff046e7-c082-4dc4-95e9-b6a40b828052" -d '{"ports_mapping": [{"name": "Ethernet0", "port_number": 0}, {"name": "Ethernet1", "port_number": 1}, {"name": "Ethernet2", "port_number": 2}, {"name": "Ethernet3", "port_number": 3}, {"name": "Ethernet4", "port_number": 4}, {"name": "Ethernet5", "port_number": 5}, {"name": "Ethernet6", "port_number": 6}, {"name": "Ethernet7", "port_number": 7}, {"name": "Ethernet8", "port_number": 8}]}'
```

Hub template with 1 port:

```
curl -X PUT "http://127.0.0.1:3080/v2/templates/3ff046e7-c082-4dc4-95e9-b6a40b828052" -d '{"ports_mapping": [{"name": "Ethernet0", "port_number": 0}]}'
```

**Comment by 1001QAdotNET** [comment]
From what you are saying it is not clear if this is currently possible for GNS2.2 or it will be implemented
I do not see the call documented in the github docs for APIs Could you please clarify? I am currently running on GNS32.21
BTW is there any way to upgrade the Linux in the VM I am currently on 16.xx LTS 
![image](https://user-images.githubusercontent.com/17384308/62008066-ee81d000-b122-11e9-9152-6dd085c13a8b.png)

**Comment by grossmj** [comment]
What I described is for version 2.2 and these instructions will not work for version 2.1.x

I don't recommend you upgrade your current VM. What you could do is download the GNS3 VM for version 2.2 beta 4 and then switch to version 2.1 inside the VM.
