### ISSUE TITLE
How do I troubleshoot a cloud to a switch connection that is not working anymore?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1620]
Hi guys

I am using the built in switch as a breakout switch to connect the management ports of my appliances to the real network. Form time to time that link seems to not work anymore and the only remedy I could find was to delete it and then add it back ...
What could be causing this and how can it be prevented?

**Comment by grossmj** [comment]
This is more likely due to the cloud node. Please confirm that it works again if you delete and recreate the link to the cloud?

**Comment by 1001QAdotNET** [comment]
yes deleting and recreating the link restores connectivity

**Comment by grossmj** [comment]
I have implemented new feature to reset a link.
