### ISSUE TITLE
Configure security -youget the option to configure it but not to disable it (via the server side menu)

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1622]
When you ssh into your server you get that menu , one of the options is Security
There you can configure a password but there is no way to disable security
Changes in the security there (server side) don't seem to reflect in the client when you go to see the server settings

**Comment by grossmj** [comment]
Server authentication should be disabled if you answer "no" to this question:

![disable_security](https://user-images.githubusercontent.com/4752614/62079054-7bfb1800-b228-11e9-9c66-bea758934714.png)

> Changes in the security there (server side) don't seem to reflect in the client when you go to see the server settings

Correct, the security settings must be manually configured on client side.
