### ISSUE TITLE
Are the templates available via API in GNS3 2.1.21

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1623]
I am seeing this in the doc section 
https://github.com/GNS3/gns3-server/blob/master/docs/api/examples/controller_get_templates.txt

but when I make this call via postman using GET

http://1.1.1.1:3080/v2/templates  
with the right user and password it fails with 404 
it I replace templates with projects that works

**Comment by grossmj** [comment]
Managing templates using the API is a new feature of version 2.2

**Comment by 1001QAdotNET** [comment]
OK I am now seeing that I can download 2.2 ...so I guess the API doc is in sync with the latest version. Thanks I am moving to that version
