### ISSUE TITLE
Is CPU throttling something that I can expect to use with a qemu machine these days?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1624]
I have not used this is a while but I seeing the CPUs on my 16 cores server (ESXI 6.5) taking turns with going 100% utilization
A top command run within the VM shows me the gns3server at 100% utilization
I am running one CSR1000v and a Linux qemu machine, each one with one vCPU. Plenty of memory on the server (64G)
![image](https://user-images.githubusercontent.com/17384308/62014453-1d259800-b16f-11e9-96a9-5dc80d0d4d36.png)

**Comment by 1001QAdotNET** [comment]
Looking twice I am seeing that when the appliance is intensively using the CPU it is the qemu that should hit the roof so the throttling won't solve my problem

How to I troubleshoot the gns3.server process that is going nuts here?

**Comment by 1001QAdotNET** [comment]
for anybody passing by...one of the issues was the gns3.server process going up 100% when sniffing (this is because I was sniffing a link conencted to the external network)

**Comment by grossmj** [comment]
> for anybody passing by...one of the issues was the gns3.server process going up 100% when sniffing (this is because I was sniffing a link conencted to the external network)

Can you confirm if this is this only for links connected to a external network?

**Comment by 1001QAdotNET** [comment]
only for links connected to the external network!

**Comment by grossmj** [comment]
The explanation is probably that there is a lot of data on the external network and doing packet sniffing results in a high CPU usage. The GNS3 server has to stream the packet capture file back to the client using a WebSocket.
