### ISSUE TITLE
Sticky nodes when added via API

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1626]
https://files.slack.com/files-pri/T03LV31CA-FLJCXPSQJ/gns3.gif  ◄ animated gif here
not all of them are sticky just the switch and the cloud nodes
![image](https://user-images.githubusercontent.com/17384308/62170827-cc42aa80-b2fa-11e9-8225-4122040f165d.png)

**Comment by 1001QAdotNET** [comment]
if I use a customized template for the switch it is not sticky anymore

**Comment by grossmj** [comment]
Please, do you have the API requests you used to create the cloud and switch nodes?

**Comment by grossmj** [comment]
2 methods are available to create a node.

1. Create a node from a template using this API call: `/projects/{project_id}/templates/{template_id}` (see http://api.gns3.net/en/2.2/curl.html#using-a-template)

2. Manually create a node using this API call: `/projects/{project_id}/nodes` (see http://api.gns3.net/en/2.2/api/v2/controller/node/projectsprojectidnodes.html#post-v2-projects-project-id-nodes)

Example using method number 1 to create a new switch based on a builtin appliance:

```
curl -X POST "http://localhost:3080/v2/projects/d55712c4-4e8a-4a1a-ad06-db9e131f524a/templates/1966b864-93e7-32d5-965f-001384eec461" -d '{"compute_id": "local", "x": -400, "y": -250}'
```

Example using method number 2 to manually create a new switch:

```
curl -X POST "http://localhost:3080/v2/projects/d55712c4-4e8a-4a1a-ad06-db9e131f524a/nodes" -d '{"compute_id": "local", "console_type": "none", "name": "My Ethernet switch", "node_type": "ethernet_switch", "x": -400, "y": -250}'
```

and a new cloud node:

```
curl -X POST "http://localhost:3080/v2/projects/d55712c4-4e8a-4a1a-ad06-db9e131f524a/nodes" -d '{"compute_id": "local", "name": "Cloud1", "node_type": "cloud", "x": -300, "y": -150, "symbol": "cloud.svg"}'
```

I noticed you incorrectly passed the "x", "y" and "symbol" params in the API call. I modified your script to change that:

```
def add_cloud(self,cloud_name):
        print ("Adding cloud interface" )
        #print(lab.serverurl+"projects/"+self.project_id.strip()+"/nodes")
        node_details={"name": cloud_name, "node_type":"cloud", "compute_id": "local", "x": -400, "y": -250, "symbol": "cloud.svg"}
        r = requests.post(lab.serverurl+"projects/"+self.project_id.strip()+"/nodes",json=node_details,auth=(self.username,self.password))

        return r

```

Please try the above and let me know if this works. Thanks.

**Comment by 1001QAdotNET** [comment]
yes the above change in the code solved the issue, thank you
