### ISSUE TITLE
IOU: Current method for calculating extra padding is unreliable

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-server#1627]
While the current method (extra padding between startup-config and private-config if IOS <= 15.0 or when the NVRAM size is at least 128 KByte) works pretty good, it’s not always correct.

For details see <https://git.b-ehlers.de/ehlers/IOUtools/issues/1>.

The IOUtools in <https://git.b-ehlers.de/ehlers/IOUtools> have been updated.

As up to now nobody complained about this, I see no need to hurry to update GNS3.

**Comment by grossmj** [comment]
Done, thanks a lot for the scripts! :)
