### ISSUE TITLE
Is just me or now the API to get the templates returns appliances and vice versa?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1628]
Either I need more sleep or you guy mixed something up in the APIs, my calls to  http://192.168.1.227:3080/v2/appliances return templates and calls to http://192.168.1.227:3080/v2/templates return appliances

This is for v2.2

**Comment by grossmj** [comment]
We better define the use of some terms when using GNS3. Details can be found on http://api.gns3.net/en/2.2/glossary.html 

To summarize: appliances are used to create templates with predefined settings, many appliances require users to provide images (IOS, vIOS, vmdk disks etc.). Templates are customizable and are used to create nodes with the same set of settings, nodes are run using various simulators or emulators (Dynamips, Qemu, VMware etc.)

http://192.168.1.227:3080/v2/appliances returns all the appliances as seen in https://github.com/GNS3/gns3-registry/tree/master/appliances

http://192.168.1.227:3080/v2/templates returns all the templates that you created and were migrated from an older version. These templates are used to create nodes.

**Comment by 1001QAdotNET** [comment]
Even we are clear on terminology the returned data changed. You know I was 2.1.16 and 
this is the format returned by 2.1.16 for appliances
{
        "appliance_id": "1966b864-93e7-32d5-965f-001384eec461",
        "builtin": true,
        "category": "switch",
        "compute_id": null,
        "default_name_format": "{name}-{0}",
        "name": "Ethernet switch",
        "node_type": "ethernet_switch",
        "platform": null,
        "symbol": ":/symbols/ethernet_switch.svg"
    }

The same call for 2.2 returns something totally different, most notable for me was the absence of appliance_id key from the dictionary .... so unfortunately for me I will have to change my code.

**Comment by grossmj** [comment]
Yep sorry, I confirm this is something we have broken in version 2.2 due to our review on terminology.
