### ISSUE TITLE
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1639]
Context:

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.2 LTS
> Release:	18.04
> Codename:	bionic
> 
> 
> $ gns3 --version
> 2.1.21
> 
> 
> $ qemu-system-x86_64 --version
> QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.14)
> Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

I Use terminator console to open multiple connections to the devices through telnet to the consoles, so I can type multiple commands simultaneously on multiple devices:

As soon as I type CTRL-C on terminator (to get out to the user mode on Arista/Cisco) The fololowing happens:

GNS3 breaks and tries to exit with this error qemu error:

> => QEMU process has stopped, return code: -9
> Start QEMU with /usr/bin/qemu-system-x86_64 -name Arista-Spine-1 -m 2048M -smp cpus=1 -enable-kvm -machine smm=off -boot order=d -cdrom /home/ajn/GNS3/images/QEMU/Aboot-veos-serial-8.0.0.iso -drive file=/home/ajn/GNS3/projects/Arista_MLAG1/project-files/qemu/96f22154-bca6-402e-96b8-554585d2d4a1/hda_disk.qcow2,if=ide,index=0,media=disk -uuid 96f22154-bca6-402e-96b8-554585d2d4a1 -serial telnet:127.0.0.1:5010,server,nowait -monitor tcp:127.0.0.1:40527,server,nowait -net none -device e1000,mac=0c:d4:a1:d4:a1:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device e1000,mac=0c:d4:a1:d4:a1:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -device e1000,mac=0c:d4:a1:d4:a1:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10005,localaddr=127.0.0.1:10004 -device e1000,mac=0c:d4:a1:d4:a1:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -device e1000,mac=0c:d4:a1:d4:a1:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10009,localaddr=127.0.0.1:10008 -device e1000,mac=0c:d4:a1:d4:a1:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10011,localaddr=127.0.0.1:10010 -device e1000,mac=0c:d4:a1:d4:a1:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10013,localaddr=127.0.0.1:10012 -device e1000,mac=0c:d4:a1:d4:a1:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:10015,localaddr=127.0.0.1:10014 -device e1000,mac=0c:d4:a1:d4:a1:08,netdev=gns3-8 -netdev socket,id=gns3-8,udp=127.0.0.1:10017,localaddr=127.0.0.1:10016 -device e1000,mac=0c:d4:a1:d4:a1:09,netdev=gns3-9 -netdev socket,id=gns3-9,udp=127.0.0.1:10019,localaddr=127.0.0.1:10018 -device e1000,mac=0c:d4:a1:d4:a1:0a,netdev=gns3-10 -netdev socket,id=gns3-10,udp=127.0.0.1:10021,localaddr=127.0.0.1:10020 -device e1000,mac=0c:d4:a1:d4:a1:0b,netdev=gns3-11 -netdev socket,id=gns3-11,udp=127.0.0.1:10023,localaddr=127.0.0.1:10022 -device e1000,mac=0c:d4:a1:d4:a1:0c,netdev=gns3-12 -netdev socket,id=gns3-12,udp=127.0.0.1:10025,localaddr=127.0.0.1:10024 -nographic
> 
> Execution log:
> qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
> 
> QEMU process has stopped, return code: -9
> Start QEMU with /usr/bin/qemu-system-x86_64 -name Arista-Spine-1 -m 2048M -smp cpus=1 -enable-kvm -machine smm=off -boot order=d -cdrom /home/ajn/GNS3/images/QEMU/Aboot-veos-serial-8.0.0.iso -drive file=/home/ajn/GNS3/projects/Arista_MLAG1/project-files/qemu/96f22154-bca6-402e-96b8-554585d2d4a1/hda_disk.qcow2,if=ide,index=0,media=disk -uuid 96f22154-bca6-402e-96b8-554585d2d4a1 -serial telnet:127.0.0.1:5010,server,nowait -monitor tcp:127.0.0.1:40527,server,nowait -net none -device e1000,mac=0c:d4:a1:d4:a1:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device e1000,mac=0c:d4:a1:d4:a1:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -device e1000,mac=0c:d4:a1:d4:a1:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10005,localaddr=127.0.0.1:10004 -device e1000,mac=0c:d4:a1:d4:a1:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -device e1000,mac=0c:d4:a1:d4:a1:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10009,localaddr=127.0.0.1:10008 -device e1000,mac=0c:d4:a1:d4:a1:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10011,localaddr=127.0.0.1:10010 -device e1000,mac=0c:d4:a1:d4:a1:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10013,localaddr=127.0.0.1:10012 -device e1000,mac=0c:d4:a1:d4:a1:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:10015,localaddr=127.0.0.1:10014 -device e1000,mac=0c:d4:a1:d4:a1:08,netdev=gns3-8 -netdev socket,id=gns3-8,udp=127.0.0.1:10017,localaddr=127.0.0.1:10016 -device e1000,mac=0c:d4:a1:d4:a1:09,netdev=gns3-9 -netdev socket,id=gns3-9,udp=127.0.0.1:10019,localaddr=127.0.0.1:10018 -device e1000,mac=0c:d4:a1:d4:a1:0a,netdev=gns3-10 -netdev socket,id=gns3-10,udp=127.0.0.1:10021,localaddr=127.0.0.1:10020 -device e1000,mac=0c:d4:a1:d4:a1:0b,netdev=gns3-11 -netdev socket,id=gns3-11,udp=127.0.0.1:10023,localaddr=127.0.0.1:10022 -device e1000,mac=0c:d4:a1:d4:a1:0c,netdev=gns3-12 -netdev socket,id=gns3-12,udp=127.0.0.1:10025,localaddr=127.0.0.1:10024 -nographic
> 
> Execution log:
> qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
> 
> QEMU process has stopped, return code: -9
> Start QEMU with /usr/bin/qemu-system-x86_64 -name Arista-Spine-1 -m 2048M -smp cpus=1 -enable-kvm -machine smm=off -boot order=d -cdrom /home/ajn/GNS3/images/QEMU/Aboot-veos-serial-8.0.0.iso -drive file=/home/ajn/GNS3/projects/Arista_MLAG1/project-files/qemu/96f22154-bca6-402e-96b8-554585d2d4a1/hda_disk.qcow2,if=ide,index=0,media=disk -uuid 96f22154-bca6-402e-96b8-554585d2d4a1 -serial telnet:127.0.0.1:5010,server,nowait -monitor tcp:127.0.0.1:40527,server,nowait -net none -device e1000,mac=0c:d4:a1:d4:a1:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device e1000,mac=0c:d4:a1:d4:a1:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -device e1000,mac=0c:d4:a1:d4:a1:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10005,localaddr=127.0.0.1:10004 -device e1000,mac=0c:d4:a1:d4:a1:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -device e1000,mac=0c:d4:a1:d4:a1:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10009,localaddr=127.0.0.1:10008 -device e1000,mac=0c:d4:a1:d4:a1:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10011,localaddr=127.0.0.1:10010 -device e1000,mac=0c:d4:a1:d4:a1:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10013,localaddr=127.0.0.1:10012 -device e1000,mac=0c:d4:a1:d4:a1:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:10015,localaddr=127.0.0.1:10014 -device e1000,mac=0c:d4:a1:d4:a1:08,netdev=gns3-8 -netdev socket,id=gns3-8,udp=127.0.0.1:10017,localaddr=127.0.0.1:10016 -device e1000,mac=0c:d4:a1:d4:a1:09,netdev=gns3-9 -netdev socket,id=gns3-9,udp=127.0.0.1:10019,localaddr=127.0.0.1:10018 -device e1000,mac=0c:d4:a1:d4:a1:0a,netdev=gns3-10 -netdev socket,id=gns3-10,udp=127.0.0.1:10021,localaddr=127.0.0.1:10020 -device e1000,mac=0c:d4:a1:d4:a1:0b,netdev=gns3-11 -netdev socket,id=gns3-11,udp=127.0.0.1:10023,localaddr=127.0.0.1:10022 -device e1000,mac=0c:d4:a1:d4:a1:0c,netdev=gns3-12 -netdev socket,id=gns3-12,udp=127.0.0.1:10025,localaddr=127.0.0.1:10024 -nographic
> 
> Execution log:
> qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
> 
> QEMU process has stopped, return code: -9
> Start QEMU with /usr/bin/qemu-system-x86_64 -name Arista-Spine-1 -m 2048M -smp cpus=1 -enable-kvm -machine smm=off -boot order=d -cdrom /home/ajn/GNS3/images/QEMU/Aboot-veos-serial-8.0.0.iso -drive file=/home/ajn/GNS3/projects/Arista_MLAG1/project-files/qemu/96f22154-bca6-402e-96b8-554585d2d4a1/hda_disk.qcow2,if=ide,index=0,media=disk -uuid 96f22154-bca6-402e-96b8-554585d2d4a1 -serial telnet:127.0.0.1:5010,server,nowait -monitor tcp:127.0.0.1:40527,server,nowait -net none -device e1000,mac=0c:d4:a1:d4:a1:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device e1000,mac=0c:d4:a1:d4:a1:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -device e1000,mac=0c:d4:a1:d4:a1:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10005,localaddr=127.0.0.1:10004 -device e1000,mac=0c:d4:a1:d4:a1:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -device e1000,mac=0c:d4:a1:d4:a1:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10009,localaddr=127.0.0.1:10008 -device e1000,mac=0c:d4:a1:d4:a1:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10011,localaddr=127.0.0.1:10010 -device e1000,mac=0c:d4:a1:d4:a1:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10013,localaddr=127.0.0.1:10012 -device e1000,mac=0c:d4:a1:d4:a1:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:10015,localaddr=127.0.0.1:10014 -device e1000,mac=0c:d4:a1:d4:a1:08,netdev=gns3-8 -netdev socket,id=gns3-8,udp=127.0.0.1:10017,localaddr=127.0.0.1:10016 -device e1000,mac=0c:d4:a1:d4:a1:09,netdev=gns3-9 -netdev socket,id=gns3-9,udp=127.0.0.1:10019,localaddr=127.0.0.1:10018 -device e1000,mac=0c:d4:a1:d4:a1:0a,netdev=gns3-10 -netdev socket,id=gns3-10,udp=127.0.0.1:10021,localaddr=127.0.0.1:10020 -device e1000,mac=0c:d4:a1:d4:a1:0b,netdev=gns3-11 -netdev socket,id=gns3-11,udp=127.0.0.1:10023,localaddr=127.0.0.1:10022 -device e1000,mac=0c:d4:a1:d4:a1:0c,netdev=gns3-12 -netdev socket,id=gns3-12,udp=127.0.0.1:10025,localaddr=127.0.0.1:10024 -nographic
> 
> Execution log:
> qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]

![Sélection_011](https://user-images.githubusercontent.com/1716020/63227941-74f27480-c1ec-11e9-808b-b8ff14d56c5e.png)

I have to close GNS3 and restart it .

Any hint?

**Comment by grossmj** [comment]
Looks like you don't use the GNS3 VM. You could try to use our backported Qemu version 3.1.0 for Ubuntu 18.04.

If you wish to do so, please install our ppa then upgrade

```
sudo -E add-apt-repository -y ppa:gns3/qemu
apt update
apt upgrade
```

**Comment by grossmj** [comment]
> As soon as I type CTRL-C on terminator (to get out to the user mode on Arista/Cisco)

Actually, looks like that terminator send a KILL signal to Qemu when you type CTRL-C. I am not sure we can do something about that.

**Comment by grossmj** [comment]
@AJNOURI Have you tried with another terminal application?

**Comment by Rocket-Wolf** [comment]
$ **sudo qemu-system-x86_64 -m 512 -enable-kvm -usb -device usb-host,hostbus=1,hostaddr=7**
**_output:_** qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]

Interesting that this failure/error message occurs for so many various unrelated reasons where the solution is for the user to change something to fix it. 

Could we perhaps look into the cause of the error in the code? I'd really like to use Ventoy, but right now it fails in an epic manner and I can not recommend it to anyone.

**Comment by Rocket-Wolf** [comment]
So I eliminated the warning message with the erroneous ECX.svm [bit 2] message by simply adding -cpu host to the command and changing 512 to 2048.

Now I only get the single error as follows: 
**$ sudo qemu-system-x86_64 -m 2048 -enable-kvm -cpu host -usb -device usb-host,hostbus=1,hostaddr=8**
**output:** libusb: error [udev_hotplug_event] ignoring udev action bind

**Comment by Gelma** [comment]
> So I eliminated the warning message with the erroneous ECX.svm [bit 2] message by simply adding -cpu host to the command and changing 512 to 2048.
> 
> Now I only get the single error as follows:
> **$ sudo qemu-system-x86_64 -m 2048 -enable-kvm -cpu host -usb -device usb-host,hostbus=1,hostaddr=8**
> **output:** libusb: error [udev_hotplug_event] ignoring udev action bind

Thanks a lot!

**Comment by alvinsmith-eroad** [comment]
> -cpu host

thank you. just added `-cpu host`
