### ISSUE TITLE
[2.2.0 B4] Unable to upgrade ESXi VM from 2.2.0 B4 to 2.2.0 RC3

### ISSUE THREAD

**Issue by DragonWin** [GNS3/gns3-server#1640]
Hi,

When I try to upgrade using the "GUI" I get this permission error. I also tried to upgrade to RC1 with the same issue.

<pre>
100 19777  100 19777    0     0   244k      0 --:--:-- --:--:-- --:--:--  244k
+ sudo mv /tmp/gns3welcome.py /usr/local/bin/gns3welcome.py
+ sudo chmod 755 /usr/local/bin/gns3welcome.py
+ set +e
+ [[ ! -d gns3-server ]]
+ cd gns3-server
+ git reset --hard HEAD
fatal: Unable to create '/home/gns3/gns3-server/.git/index.lock': Permission denied
ERROR DURING THE UPGRADE PROCESS PLEASE, TAKE A SCREENSHOT IF YOU NEED SUPPORT
</pre>

I'm assuming it should be possible to upgrade from b4 to RC3? If so what do I need to do to fix it ?

Thanks,

**Comment by grossmj** [comment]
Please start a shell in the GNS3 VM and type the following command:

```sudo rm -rf /home/gns3/gns3-server/```

Then start the upgrade again.

**Comment by DragonWin** [comment]
Hi Jeremy,

Thank you for the fast response :-)

The command solved the update issue, I did get a warning when the pip install -U -r requirements.txt was executed. However everything seems to work just fine.

<pre>
+ sudo pip3 install -U -r requirements.txt
The directory '/home/gns3/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/gns3/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
</pre>

Regards,
DraognWin

**Comment by grossmj** [comment]
No worries. Looks like the upgrade script has been launched with root rights which messed up things. Anyway, everything seemed to work fine for you.
