### ISSUE TITLE
Error while installing gns3-server

### ISSUE THREAD

**Issue by zieyaz** [GNS3/gns3-server#1642]
Please help.. i have this error when i trying installing gns3-server.. the error said that cannot find jsonschema 3.2.0

$sudo python3 setup.py install
!
Installed /usr/local/lib/python3.6/dist-packages/gns3_server-2.2.0dev16_9559748f-py3.6.egg
Processing dependencies for gns3-server===2.2.0dev16-9559748f
Searching for jsonschema==3.2.0
**Reading https://pypi.org/simple/jsonschema/
No local packages or working download links found for jsonschema==3.2.0
error: Could not find suitable distribution for Requirement.parse('jsonschema==3.2.0')**

I try to upgrade jsonschema but still same and not find the same version as requirement (*3.2.0)

$ jsonschema --version
3.0.2

**Comment by grossmj** [comment]
My bad, we forgot to merge some changes from our 2.2 branch to master. Please download again and this time you should be able to install.
