### ISSUE TITLE
Dynamips error when running command 'nio create_udp gns3 2.1.21

### ISSUE THREAD

**Issue by mbonardi** [GNS3/gns3-server#1645]
gns3 Version 2.1.21
everything was working fine but suddendly appeared:

Dynamips error when running command 'nio create_udp udp-520d2a72-7520-478d-ae3e-0e97ad207014 10002 127.0.0.1 10003
': unable to create UDP NIO

in attachment the .gns3 file

any idea how to fix it ?

[ENI-RR-NEW.txt](https://github.com/GNS3/gns3-server/files/3550892/ENI-RR-NEW.txt)

**Comment by mbonardi** [comment]
It seems the problem appears when connecting a type "local" dynamips router to a type "vm".
My firewall has disabled

**Comment by grossmj** [comment]
What are the IP addresses for your local server and GNS3 VM?

**Comment by mbonardi** [comment]
... it was the last windows update ......

**Comment by mbonardi** [comment]
... are on the same subnet GNS3 VM 192.168.211.128  Local server 192.168.211.1 .. However, as in my previous comment, I rolled back the last windows update and everything started working again 
... Thank you for your interest.

**Comment by mbonardi** [comment]
Hi Jeremy, good morning.

VmWare is running on the same PC as the local server (same subnet /24).

The issue was related to the connection between local and vm dynamips devices (Qemu, Gns3 switches, clouds were working).

I rolled back the last windows update and … magic everything started working again.

FYI In attachment a schema of my project:

 

Have a good day

Thank you

Massimo

 

Da: Jeremy Grossmann <notifications@github.com> 
Inviato: giovedì 29 agosto 2019 16:31
A: GNS3/gns3-server <gns3-server@noreply.github.com>
Cc: mbonardi <mbonardi@tiscali.it>; Author <author@noreply.github.com>
Oggetto: Re: [GNS3/gns3-server] Dynamips error when running command 'nio create_udp gns3 2.1.21 (#1645)

 

What are the IP addresses for your local server and GNS3 VM?

**Comment by Deadmaus2630** [comment]
I have the same problem please some solution I am new in this and well my pc is also new and this error appears in other PCs it opens normal, but in mine not

**Comment by Deadmaus2630** [comment]
I have the same problem please some solution I am new to this and well my pc is also new and this error appears in other PCs it opens, but not mine

**Comment by b-codex** [comment]
Solution : change the default UDP port range to be 20000 - 30000.

**Comment by nisarga-nn** [comment]
Solution: I faced the same issue surprisingly uninstalling Nvidia GeForce Experience from your PC will resolve the issue. It has worked for many people facing this same issue.

**Comment by TurhanErgene** [comment]
> Solution : change the default UDP port range to be 20000 - 30000.

changing the range to 3000 to 5000 fixed in my case

**Comment by Humam-Asaad** [comment]
**issues**:  Dynamips error when running command 'nio create_udp udp-520d2a72-7520-478d-ae3e-0e97ad207014 10002 127.0.0.1 10003
': unable to create UDP NIO 
i work with it perfectly but when i close it to continue tomorrow and try to open the project it has appeared this problem

it works with me version 2.2.60 and maybe works on feature version, **the problem it is not related to version** 
solution is changing the rang of UDP port start form 3000 and end with 5000
**the path of file: C:\Users\UsernameOfYourUser\AppData\Roaming\GNS3\2.2**
and open the file name is : **gns3_server.ini**
the defaulted is as following:
udp_start_port_range = 10000
udp_end_port_range = 20000
https://docs.gns3.com/docs/using-gns3/administration/gns3-server-configuration-file

**### change it to like this to solve current issue:**
udp_start_port_range = 3000
udp_end_port_range = 5000 this you can set it 20000
