### ISSUE TITLE
AttributeError: Cannot set attribute '%s'

### ISSUE THREAD

**Issue by mrdude** [GNS3/gns3-server#1646]
I'm seeing this bug on GNS3 version 2.1.21. 

In `gns3server/controller/node.py`, if `Node.__init__()` is unable to set an attribute on a node, it should log an error and raise an exception. The line that performs the logging (line 103) is using a mix of old- and new-style string interpolation, meaning that the name of the attribute that couldn't be set is never logged:

> Cannot set attribute '%s'

It's a pretty small bug, but it's making it difficult to debug a script I'm writing that uses the GNS3 controller API.

Not sure if it's been fixed in an unreleased develop branch, but if I find some time in the near future I'll look into it and submit a PR for this myself.

**Comment by grossmj** [comment]
Fixed. Thanks :+1:
