### ISSUE TITLE
Best way to create nodes using the API?

### ISSUE THREAD

**Issue by davidban77** [GNS3/gns3-server#1650]
Hello team! - I have a question

I have started some work for automated labs using the API (great job BTW!) and so far I have used the `Nodes` endpoint to do that. Just had another look at the docs and found that you can create a node from the `Templates` endpoint! - it was exactly the kind of call that I was looking for when I first started [gns3fy](https://github.com/davidban77/gns3fy), since the target I was looking for was to derive a device configuration based on a template already present on the server.

Now, are there any big differences one should be aware between these 2 approaches?:
- [Using the Nodes enpoint](http://api.gns3.net/en/2.2/api/v2/controller/node/projectsprojectidnodes.html#post-v2-projects-project-id-nodes)
- [Using the Templates endpoint](http://api.gns3.net/en/2.2/api/v2/controller/template/projectsprojectidtemplatestemplateid.html#post-v2-projects-project-id-templates-template-id)

**Comment by grossmj** [comment]
The only big difference is that you must have first created a template before you can use the templates endpoint. A new node will be created using the template data.

Using the nodes endpoint, you have to pass all required data every time.

I hope this answers your question.

**Comment by grossmj** [comment]
Also please note that the `templates` endpoints only exist since GNS3 version 2.2

**Comment by davidban77** [comment]
Yep it did answer the question, so thanks @grossmj !
