### ISSUE TITLE
Issue renaming ATM switch

### ISSUE THREAD

**Issue by davidban77** [GNS3/gns3-server#1651]
Although I don't use it too much though, I thought it would be good to report it.

The ATM Switch reports `unknown module atm` on dynamips when trying to rename it:

```
HTTPError: 409: Dynamips error when running command 'atm rename "ATMswitch-1" "rte13"
': Unknown module 'atm'
```

The ATM switch is already created though.

**Comment by grossmj** [comment]
Must be a typo on our side. The module should be `atmsw`: https://github.com/GNS3/dynamips/blob/master/README.hypervisor#L39

I will fix this right now. Thanks for reporting!

**Comment by grossmj** [comment]
Fixed
