### ISSUE TITLE
ADD https authentication / login

### ISSUE THREAD

**Issue by BedoM** [GNS3/gns3-server#1652]
Hello,

Can you add https authentication / login for gns3-vm / gns3 remote server

for port 3080

Thank you

**Comment by b-ehlers** [comment]
https was removed from GNS3 in v2.1, see commits https://github.com/GNS3/gns3-gui/commit/56ebfc7fd0918c3d6b579a3dc18bdd8bca8bd912 and https://github.com/GNS3/gns3-server/commit/89394ba7e0a1708c2263920cf76aa6ec5b8828c1.

**Comment by grossmj** [comment]
I remember that we dropped it because of dependency issues, we may need to review that again.

**Comment by b-ehlers** [comment]
Found the issue that caused https to be removed: https://github.com/GNS3/gns3-server/issues/1022

**Comment by grossmj** [comment]
I have added back SSL support in the client (with some improvements). There are probably a few more things to improve.

For production, use a certificate from Let's Encrypt (free!) or any other SSL certificate company.

For local servers or just testing out, create a self-signed certificate using a custom CA (Certificate Authority).

Examples:

https://gist.github.com/fntlnz/cf14feb5a46b2eda428e000157447309
https://gist.github.com/cecilemuller/9492b848eb8fe46d462abeb26656c4f8
https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development (macOS)

Then configure gns3_server.conf (on the OS that will run the GNS3 server), make sure protocol is set `https` and ssl to `True` as well as the paths for certfile and certkey are correct.

```
protocol = https
ssl = True
certfile = /home/user/.config/GNS3/ssl/gns3_localhost.crt
certkey = /home/user/.config/GNS3/ssl/gns3_localhost.key
```

Finally, add your custom CA certificate to your system certificate store (on the OS that will run the GNS3 client).

Example on Ubuntu: https://www.techrepublic.com/article/how-to-install-ca-certificates-in-ubuntu-server/

On Windows, simply right click the CA certificate file and select 'Install Certificate'.

Now you should be able to connect to the GNS3 server using SSL without any error.
