### ISSUE TITLE
Syntax error: EOL while scanning string literal

### ISSUE THREAD

**Issue by rohitchormale** [GNS3/gns3-server#1654]
When I tried to install gns3-server from master branch, I found below issue. 

`SyntaxError: EOL while scanning string literal`. 

This issue is coming because of [this line](https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/qemu/qemu_vm.py#L1643), where single quote is not closed. Apparently on branch 2.2, I am not able to see this issue. 

As I am not aware of exact development process, I am raising this issue assuming regression. Kindly close if this is not case or already fixed/pipelined.

**Comment by grossmj** [comment]
Thanks for catching this. I will fix that soon :+1:
