### ISSUE TITLE
GNS3VM

### ISSUE THREAD

**Issue by arvinvelarde** [GNS3/gns3-server#1658]
Im having this error when I started my GNS3 
"The GNS3 VM (192.168.88.0/24) is not on the same network as the local server (127.0.0.0/8), please make sure the local server binding is in the same network as the GNS3 VM"

Please help

**Comment by grossmj** [comment]
You should configure the local GNS3 server to be on the same network as the GNS3 VM. Go to Preferences in GNS3 -> Server and select an address IP (Host binding option) that is on the same network, in your case an IP starting with 192.168.88.x

![Screenshot from 2019-09-25 17-12-34](https://user-images.githubusercontent.com/4752614/65587029-bd553d00-dfb7-11e9-9cac-53130bb27daf.png)

Restart GNS3 once this is changed.

**Comment by arvinvelarde** [comment]
thank you
