### ISSUE TITLE
Error with console type in Ethernet switch schema

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1659]
The error is likely to be in other node types.

https://gns3.com/community/discussion/unable-to-load-projects-since-re

**Comment by grossmj** [comment]
Fixed

**Comment by TheBitAdviser** [comment]
Issue is ongoing for me and many others.

**Comment by grossmj** [comment]
This will be fixed when we release version 2.2.1 in a couple of weeks

**Comment by TheBitAdviser** [comment]
Thanks, is there a workaround for the time being?

**Comment by grossmj** [comment]
One workaround for now is to edit your .gns3 file in the project directory and replace

"console_type": null,

by

"console_type": "none",

**Comment by TheBitAdviser** [comment]
Unfortunately this hasn't been working for me. I'll just have to wait until the next version is released.

**Comment by hatim342** [comment]
> One workaround for now is to edit your .gns3 file in the project directory and replace
> 
> "console_type": null,
> 
> by
> 
> "console_type": "none",

how do i edit the file

**Comment by jasonpeterson444** [comment]
I second that question. Hoping this work around will work even for the latest GNS3 version. I do not know how to edit (or know how to find) the .gns3 file. Do you mean the project file?
