### ISSUE TITLE
Debian Buster support

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#1660]
Request from the forum to build packages for Debian Buster: https://gns3.com/community/discussion/installation-on-debian-linux

Note: Just my 2 cents but I think we should limit the binaries to LTS releases; there are too many versions to support right now.

**Comment by grossmj** [comment]
> Request from the forum to build packages for Debian Buster: https://gns3.com/community/discussion/installation-on-debian-linux

The post is gone. Have you tested the latest release on Debian Buster?

**Comment by grossmj** [comment]
I installed a fresh Debian Buster and ran the following commands:

```
apt update
apt install python3-pip python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtwebsockets
pip3 install gns3-server
pip3 install gns3-gui
```

Everything works as expected.

**Comment by adosztal** [comment]
No, I haven't and the poster in that thread didn't provide any further specs. We can close this.
