### ISSUE TITLE
QEMU link detection flaky on last port

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-server#1666]
Version: 2.2.0

Community: https://gns3.com/community/discussion/iosv-images-acpi-link-detection
Related issue: https://github.com/GNS3/gns3-server/issues/1582

I can reproduce it. Just put an IOSv as the only node in a project (so all links are unconnected) and start it. I'm using `vios-adventerprisek9-m.vmdk.SPA.156-2.T`, in the forum `vios-adventerprisek9-m.vmdk.SPA.157-3.M3` was used. In my tests it works fine with 4 (unconnected interfaces), with 5 interfaces the last one stays up.

The QEMU monitor shows, that only the first 4 interfaces were set to down:

```
gns3@gns3vm:~$ telnet 127.0.0.1 46423
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
QEMU 3.1.0 monitor - type 'help' for more information
(qemu) info history
info history
0: 'set_link gns3-0 off'
1: 'set_link gns3-1 off'
2: 'set_link gns3-2 off'
3: 'set_link gns3-3 off'
4: 'info history'
(qemu)
```

Even after https://github.com/GNS3/gns3-server/issues/1582 the communication between GNS3 and the QEMU monitor is not reliable. In `_control_vm_commands` after sending a command it waits for one line of input. But when connecting to the monitor a welcome line is sent by the monitor. So the readline() doesn't wait for the echo of the command, it waits for the welcome message. Likewise later commands wait for the echo of the previous command. When issuing the last command it waits for the echo of the second last command and then closes the session to the monitor. That may result in the last command not being executed.

Here my patch to wait for the command echo:

```
diff --git a/gns3server/compute/qemu/qemu_vm.py b/gns3server/compute/qemu/qemu_vm.py
index 52a979e3..b3cad9f0 100644
--- a/gns3server/compute/qemu/qemu_vm.py
+++ b/gns3server/compute/qemu/qemu_vm.py
@@ -1173,8 +1173,12 @@ class QemuVM(BaseNode):
             for command in commands:
                 log.info("Execute QEMU monitor command: {}".format(command))
                 try:
-                    writer.write(command.encode('ascii') + b"\n")
-                    await asyncio.wait_for(reader.readline(), timeout=3)  # echo of the command
+                    cmd_byte = command.encode('ascii')
+                    writer.write(cmd_byte + b"\n")
+                    while True:
+                        line = await asyncio.wait_for(reader.readline(), timeout=3)  # echo of the command
+                        if not line or cmd_byte in line:
+                            break
                 except asyncio.TimeoutError:
                     log.warning("Missing echo of command '{}'".format(command))
                 except OSError as e:
```

With that patch all 5 links are set to down.

**Comment by grossmj** [comment]
Patch applied, thanks :+1:
