### ISSUE TITLE
Better not to fork when using systemd

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-server#1678]
I wasn't aware of [remote-install.sh](https://github.com/GNS3/gns3-server/blob/master/scripts/remote-install.sh) until now.  I notice it includes the following:

```
[Systemd]
Type=forking
...
ExecStart=/usr/bin/gns3server --log /var/log/gns3/gns3.log \
     --pid /var/run/gns3/gns3.pid --daemon
```

However, systemd works much better when it directly supervises the child - i.e. remove `Type=forking` and the `--pid` and `--daemon` options.  `systemctl status` shows the process and all its descendents (e.g. ubridge and qemu); `journalctl -xe` shows its error output; you can add `Restart=on-failure` so that if it crashes with a non-zero exit code systemd will notice and automatically restart it, and so on.

For comparison, here's what I have been installing as `/etc/systemd/system/gns3-server@.service`

```
[Unit]
Description=GNS3 network simulator
After=network-online.target
Wants=network-online.target
Conflicts=shutdown.target

[Service]
User=%i
Restart=on-failure
RestartSec=5
ExecStart=/usr/bin/gns3server

[Install]
WantedBy=multi-user.target
```

The '@' in the service means that it is a parameterized (multi-instance) unit, and I'm using the instance for the userid.  So:

```
systemctl start gns3-server@ubuntu
systemctl enable gns3-server@ubuntu
```

will cause gns3server to run for the `ubuntu` user, now and on next boot.

You don't need to copy the multi-instance stuff, but running gns3server directly with ExecStart and without forking works extremely well and I recommend doing that.

**Comment by grossmj** [comment]
Thanks for finding this.

The service installed in the GNS3 VM will need to be changed too. Here is what we have now:

```
[Unit]
Description=GNS3 server

[Service]
Type=forking
User=gns3
Group=gns3
PermissionsStartOnly=true
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ExecStartPre=/bin/mkdir -p /var/log/gns3 /var/run/gns3
ExecStartPre=/bin/chown -R gns3:gns3 /var/log/gns3 /var/run/gns3
ExecStart=/usr/local/bin/gns3server --log /var/log/gns3/gns3.log --logcompression \
 --pid /var/run/gns3/gns3.pid --daemon
Restart=on-abort
PIDFile=/var/run/gns3/gns3.pid

[Install]
WantedBy=multi-user.target
```

**Comment by grossmj** [comment]
What is best between `Restart=on-abort` and `Restart=on-failure`?

**Comment by candlerb** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

* "on-abort" only restarts if process was killed by a signal - could be SIGABRT, SIGSEGV etc (exit code 128 to 255 = 128 + signal number)
* "on-failure" also restarts if the process exits normally with any non-zero exit code (1 to 127)

With "on-failure" there's a risk that if gns3server fails to start because of a configuration error, it will be restarted in an infinite loop.  That's why I'd also add "RestartSec=5", otherwise the default is to restart every 100ms!

You can set `RestartPreventExitStatus=X Y` if you know that exit codes X and Y are permanent errors which shouldn't cause a restart.

**Comment by candlerb** [comment]
So I'd choose "on-failure" because that includes Python exceptions.

```
$ echo 'raise RuntimeError("boo")' | python3; echo $?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: boo
1
```

**Comment by grossmj** [comment]
I have made the changes for the GNS3 VM and remote install script.

**Comment by vint66** [comment]
I also had an issue with too many files opened (in case you have huge lab)
I end up with option below

**Comment by candlerb** [comment]
Thanks for the pointer.  It seems like an extreme value you've chosen - the default is 1024 soft (4096 hard), and with a 50 node emulation I'm nowhere near that.  However I've added `LimitNOFILE=16384` to give plenty of headroom.

**Comment by grossmj** [comment]
I will add `LimitNOFILE=16384` to the service file :+1:
