### ISSUE TITLE
Check for issues on Mac OS Catalina

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1680]
https://gns3.com/community/discussion/can-t-run-gns3-2-2-0-on-mac-os-c

**Comment by adosztal** [comment]
New report: https://gns3.com/community/discussion/gns3-2-2-2-for-mac-not-working

**Comment by benali125** [comment]
same issue here after updating Mac OS Catalina to 10.15 
GNS3 disapeared and under GNS3 VM says Not Found this is bizzare

**Comment by grossmj** [comment]
I installed macOS 10.15 in a VM, installed GNS3 and didn't detect anything wrong. I haven't tested the GNS3 VM though.

**Comment by benali125** [comment]
Not sure what happened 
In VMware fusion the message I got was image not found 
But any way got it installed and running like a charm

**Comment by adosztal** [comment]
I only had issues with VMware Fusion after the Catalina upgrade but that was solved by re-installing it. No issues with GNS3 inself or the GNS3 VM.

**Comment by adosztal** [comment]
New thread: https://gns3.com/community/discussion/gns3-2-2-3-for-mac-still-not-wor
I asked the reporter to provide debug outputs.

**Comment by benali125** [comment]
I wasn’t sure what happened after the updates to Catalina 15.1 
So I upgraded my VMware to 15.5 pro and reinstalled GNS3 everything is working fine

**Comment by adosztal** [comment]
@grossmj, could you take a look at the debug output in the forum thread?

**Comment by grossmj** [comment]
Apparently Apple wants to stop everything from working if it is not approved by them... Well more work for us I guess :/

https://www.winytips.com/installer-cant-be-opened-because-apple-cannot-check-it-for-malicious-software/

**Comment by grossmj** [comment]
Our next release will be notarize. I have tested on latest build and everything works well.

To try yourself:

Delete any previous config in `~/.config/GNS3` then download and install https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2019-12-23/2.2/GNS3-2.2.4dev1.dmg/download
