### ISSUE TITLE
[2.2.0vm] Cannot upgrade GNS3 VM 2.2.0 to 2.2.1

### ISSUE THREAD

**Issue by EB-athila** [GNS3/gns3-server#1683]
Cannot upgrade GNS3 VM from 2.2.0 to 2.2.1

Steps to reproduce @ GNS3 VM Menu:
1. Upgrade
2. Ok to "Take snapshot before..." message box.
3. Option: 2.2.1
4. Following message presented:
![image](https://user-images.githubusercontent.com/21137156/68099855-3723f480-fe9b-11e9-8f37-d2e93d1263d5.png)

System Info:
Windows 10 1903
VMware Workstation Pro 15.5
GNS3 VM 0.10.18
GNS3 Server 2.2.0

Thanks.

**Comment by grossmj** [comment]
Thanks, I fixed the upgrade script. Please try again, this should work this time.
