### ISSUE TITLE
Use Swagger for API documentation & testing

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1686]
Redo the API documentation.

Interesting articles:

https://dmax.blog/how_to_easily_build_modern_web_apis_with_python_and_aiohttp
https://medium.com/@olotintemitope/how-to-generate-your-api-documentation-in-20-minutes-4e0072f08b94
https://stoplight.io/api-documentation-guide/basics/

Also, for API testing:

https://taverntesting.github.io/

**Comment by adosztal** [comment]
What about using Swagger?

**Comment by grossmj** [comment]
That's the plan using the aiohttp-apispec package (https://pypi.org/project/aiohttp-apispec/#description). Still need to research this topic because it is still a bit blurry how to do that. Maybe we use another module or solution...

**Comment by ziajka** [comment]
Option for using OpenAPI3: https://pypi.org/project/aiohttp-swagger3/ or https://github.com/cr0hn/aiohttp-swagger

**Comment by grossmj** [comment]
More options I am evaluating now:

* https://github.com/playpauseandstop/rororo
* https://github.com/jibrelnetwork/jibrel-aiohttp-swagger
* https://github.com/aamalev/aiohttp_apiset
* https://github.com/quantmind/aio-openapi
* https://github.com/aiohug/aiohug
* https://github.com/maximdanilchenko/aiohttp-apispec

I also looked at another Framework, FastAPI: https://fastapi.tiangolo.com/ which look really polished and comes with everything we need.

**Comment by grossmj** [comment]
Starting from version 3.0, GNS3 uses FastAPI instead of aiohttp for its back-end (migration ongoing). One advantage of FastAPI is the automatically generated API documentation. Right now this documentation is accessible on the `/docs` endpoint of the controller.
