### ISSUE TITLE
upgrade from 2.1.14 to 2.2.3 - how to convert gns3_controller.conf

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-server#1694]
Hi, i've upgraded a gns3server on raw hardware ubuntu 19.04. I can't figure out how to migrate my gns3_controller.conf. I see the new versioning is being written to ~/.config/GNS3/2.2. I've tried updating the version string and moving to that dir but it keep getting clobbered. I tried chmoding to root and setting perm to 444. This prevented it from being clobbered but none of the templates are showing in gui.

BTW the install was done via pip3.

**Comment by spikefishjohn** [comment]
I just noticed the format of this file is completely different at least while viewing the cloud object. 

Is there a conversion tool by chance?

**Comment by spikefishjohn** [comment]
After much searching and then pondering python stuff i just brute forced re-creating. The old controller file i need to do everything.

**Comment by grossmj** [comment]
The upgrade should have been automatic. There is a bug migrating the gns3_controller.conf file.
