### ISSUE TITLE
Nxosv 9000 issues with VMware VM

### ISSUE THREAD

**Issue by hydysan** [GNS3/gns3-server#1697]
Hello,

i have nxosv9000 running on my PC with VM in virtualbox, and everything is running great, but because of the performance issues i had to migrate it to server with much more resources. Because of some problems with VT-x (nested virtualization) i have to run GNS3 VM in VMware Workstation Player 15. All images that i have running with no problem at all on my new GNS set-up, just nxosv9000 have some problems (tried more image versions but no success) booting up and gives me error like this:

Sysconf checksum failed. Using default values
WARNING: No BIOS Info found
Sysconf checksum failed. Using default values
Sysconf checksum failed. Using default values
Sysconf checksum failed. Using default values
ATE0Q1&D2&C1S0=1
Standalone chassis
check_bootmode: grub2pxe: grub failed, launch ipxe
Trying to load ipxe
Loading Application:
/Vendor(429bdb26-48a6-47bd-664c-801204061400)/UnknownMedia(6)/EndEntire
cannot load imageFailed to launch ipxe
Came back to grub, now load efi shell
Trying to load efishell
Loading Application:
/Vendor(429bdb26-48a6-47bd-664c-801204061400)/UnknownMedia(6)/EndEntire
cannot load imageFailed to launch shell
Trying to read config file /boot/grub/menu.lst.local from (hd0,4)
Filesystem type is ext2fs, partition type 0x83
Trying to read config file /boot/grub/menu.lst.local from (hd0,5)
Filesystem type is ext2fs, partition type 0x83
Sysconf checksum failed. Using default values

Any suggestions?

Thanks a lot.

**Comment by grossmj** [comment]
Please try to post on gns3.com to see if anyone has experienced the same issue as you. Thanks!
