### ISSUE TITLE
"Legacy networking" with recent Qemu versions

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1699]
Apparently "Legacy networking" is broken with recent versions of Qemu: https://gns3.com/community/discussion/qemu-system-x86_64-invalid-param

**Comment by b-ehlers** [comment]
I've got some additional issues with the argument handling of a more recent QEMU, in my case it's Debian Buster with QEMU version 3.1.0.

In my case GNS3 doesn't allow me to enable "Legacy networking" with that QEMU version, so I don't get the error message shown in the community thread. But I don't think, that's an error of GNS3, newer QEMU just don't support the legacy way of configuring the network interfaces.

But when I use the "Legacy paravirtualized Network I/O (virtio)" adapter in non-legacy mode I get:
`qemu-system-x86_64: -device virtio,mac=0c:f7:ec:f5:c8:00,netdev=gns3-0: 'virtio' is not a valid device model name`

A similar issue arises on some hard disk adapter types, namely scsi, sd and mtd. Then I get:

```
scsi:    qemu-system-x86_64: -drive file=/.../hda_disk.qcow2,if=scsi,index=0,media=disk,id=drive0: machine type does not support if=scsi,bus=0,unit=0
sd:      qemu-system-x86_64: -drive file=/.../hda_disk.qcow2,if=sd,index=0,media=disk,id=drive0: machine type does not support if=sd,bus=0,unit=0
mtd:     qemu-system-x86_64: -drive file=/.../hda_disk.qcow2,if=mtd,index=0,media=disk,id=drive0: machine type does not support if=mtd,bus=0,unit=0
```

For SCSI I found this entry in the Changelog of QEMU 2.12: <https://wiki.qemu.org/ChangeLog/2.12>:

> The deprecated way of configuring SCSI devices with "-drive if=scsi" on x86 has been removed. Use an appropriate SCSI controller together "-device scsi-hd" or "-device scsi-cd" and a corresponding "-blockdev" parameter instead.

So it looks as the QEMU argument handling of GNS3 needs some overhaul.

**Comment by grossmj** [comment]
> In my case GNS3 doesn't allow me to enable "Legacy networking" with that QEMU version, so I don't get the error message shown in the community thread. 

I fixed a problem that the GUI wasn't sending anything to the server when enabling the "legacy networking mode"

> But when I use the "Legacy paravirtualized Network I/O (virtio)" adapter in non-legacy mode I get:
qemu-system-x86_64: -device virtio,mac=0c:f7:ec:f5:c8:00,netdev=gns3-0: 'virtio' is not a valid device model name

I think we kept "virtio" for really old Qemu versions that are included with GNS3. I added more recent NIC though:  "e1000-82544gc", "e1000-82545em", "e1000e" and "rocker".

> For SCSI I found this entry in the Changelog of QEMU 2.12: https://wiki.qemu.org/ChangeLog/2.12

I fixed SCSI and added the nvme disk interface.

I don't really know what to do with the "sd" and "mtd" disk adapter types since the Qemu documentation and forums isn't clear at all. I am gonna push this for a later version of GNS3.

**Comment by b-ehlers** [comment]
Just tested the modified scsi disk interface (PR https://github.com/GNS3/gns3-server/pull/1714). It works, but only with raw images. All the other image types, for example qcow2 and vmdk, no longer work. I noticed the addition of `format=raw` also for sata, nvme and the commented sd disk interface. So is GNS3 deprecating qcow2 in favor for raw? That will increase disk space  significantly.

**Comment by grossmj** [comment]
Good catch, no we have no intention to deprecate qcow2.

**Comment by b-ehlers** [comment]
The simplest fix seems to be to remove `format=raw` from the qemu options of the disk interfaces.

**Comment by grossmj** [comment]
> The simplest fix seems to be to remove format=raw from the qemu options of the disk interfaces.

This should be good now. Thanks.

**Comment by andrej-korshikov** [comment]
Related issue: https://github.com/GNS3/gns3-gui/issues/1969
Unsetting **Use the legacy networking mode** and selecting **Legacy paravirtialized Network I/O (virtio)** leads to `'virtio' is not a valid device model name` error with modern QEMU.
