### ISSUE TITLE
Windows 10 build 1903 & loopback interfaces

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1701]
Looks like the major Windows 10 build 1903 update has broken something with loopback interfaces (thanks Microsoft!). Now many users are complaining they cannot use loopback interfaces with GNS3.

https://gns3.com/community/discussion/-there-is-no-internet-connection
https://gns3.com/community/discussion/gns3-does-not-connect-to-loopbac
https://gns3.com/community/discussion/can-not-access-to-devices-in-gns

This is another major reason for use to move to a VM + web interface model. It has become extremely problematic to get around all the anti-virus, VMware (vmrun) issues and other OS problems.

**Comment by grossmj** [comment]
I can confirm only installing npcap will prevent communication with local loopbacks. Current workaround seems to install winpcap after installing npcap.

**Comment by grossmj** [comment]
It seems this also brought back to looped back packet issue: https://gns3.com/community/discussion/intermittent-pings

**Comment by grossmj** [comment]
The next release installer will install winpcap after npcap for Windows 10 and above. This is a workaround while waiting to find a permanent solution.

**Comment by ColdIce1** [comment]
WinPcap solved my connection issues to the VM as well.
Win 10 1903 build. Latest [KB4532693](https://support.microsoft.com/nb-no/help/4532693/windows-10-update-kb4532693) from February installed.
