### ISSUE TITLE
GNS3 Crashes and does not open again

### ISSUE THREAD

**Issue by TayYuanGeng** [GNS3/gns3-server#1704]
Was doing my emulation half way and it suddenly closes. The virtual machine running on vmware however is still running. Tried reopening GNS3 and all I saw was:
![image](https://user-images.githubusercontent.com/50003738/70850714-51081c80-1ec8-11ea-88f7-30bfbb169421.png)
Tried clicking on it several times but it doesn't show the topology or the landing page that I am supposed to see.
Rebooted my computer and tried again but it doesn't work. It does activate the virtual machine connected to gns3 but the landing page is no longer visible
![image](https://user-images.githubusercontent.com/50003738/70850727-8a408c80-1ec8-11ea-8efb-eac1e08b1156.png)

**Comment by TayYuanGeng** [comment]
Nvm, idk was it a bug but what I did was to right click on the white screen on the first picture and 'maximise' kaboom, it comes back up again. And also I remember clearly that I did nothing but just clicking on a VPC to delete it before it happens.

**Comment by grossmj** [comment]
I suspect there is a bug when deleting one or more nodes. We will need to investigate this...

**Comment by PranavBhattarai** [comment]
In **Ubuntu 19.10** with **VM Workstation 15 Pro**; I have experienced this hang up multiple times.

4 out of 10 times, there is only one while underscore waiting for GNS3 to show its menus.
![Screencast from 24-03-20 10_15_01 PM +0545](https://user-images.githubusercontent.com/32763112/77452570-3118bb00-6e1e-11ea-88d1-15de1eabf9ba.gif)

At last, I have no other option but to shutdown using VMware option; which I think is what we call **force shutdown**. @grossmj Do you have anything to say about these glitches? Or is it happening to me only?
