### ISSUE TITLE
[REST API] I'm unable to update SVGs through the REST API 

### ISSUE THREAD

**Issue by Krlosromero** [GNS3/gns3-server#1706]
Hi guys,

Following you API documentation on Drawings:

https://gns3-server.readthedocs.io/en/latest/api/v2/controller/drawing/projectsprojectiddrawings.html#post-v2-projects-project-id-drawings

I have noted that the POST or UPDATE Methods for the drawing endpoints doesn't recognise the parameter added on the SVG.  ( specifically the coordinates of the drawing as well the size of the drawing)

the results are that:
1 .- the drawing are NOT showing in the GNS3 client, nor the web GUI
2 .-  when I try to update an existing diagram (added by hand, it just doesn't update)
3 .- when you run the GET drawings method (they show the drawing instances but not on the GUI)
I have tried to post the drawing with the same parameters like in your example without sucess.

I'm running GNS3 server version 2.2.2

my POST method for adding a new drawing is something like:

```http://192.168.222.128:3080/v2/projects/4322064b-509d-4f53-8f85-ad4ba8cdc4fc/drawings```

where the body of the message is as follows:

```
{
 "svg": "<svg height=\"210\" width=\"500\"><line x1=\"0\" y1=\"0\" x2=\"200\" y2=\"200\" style=\"stroke:rgb(255,0,0);stroke-width:2\" /></svg>",
 "x": 100,
 "y": 200,
 "z": 0
 }
```

then I receive an affirmative response from the Server

```
{
    "drawing_id": "8e77ed95-c741-49b3-9d42-8015fbbfba69",
    "locked": false,
    "project_id": "4322064b-509d-4f53-8f85-ad4ba8cdc4fc",
    "rotation": 0,
    "svg": "<svg height=\"210\" width=\"500\"><line x1=\"0\" y1=\"0\" x2=\"200\" y2=\"200\" style=\"stroke:rgb(255,0,0);stroke-width:2\" /></svg>",
    "x": 100,
    "y": 200,
    "z": 0
}
```
And eventhough the API response seems to be correct, this is not reflected visually on the Web GUI or Gns3 Client.

Please let us know what do you think on this.

Thanks

**Comment by grossmj** [comment]
Can you do a request with this body instead:

```
{"svg": "<svg height='500' width='500'><circle cx='250' cy='250' r='210' fill='#fff' stroke='#000' stroke-width='8' /></svg>", "x": -500, "y": -500, "z": 0}
```

It seems there is a bug with the web-ui not displaying the SVG. Can you confirm this?

**Comment by Krlosromero** [comment]
Hello Jeremy, 

posted your SVG and still cannot see the circle on the web GUI or GNS3 Client.

again, the response from the GNS3 server seems to be OK, 
```
{
    "drawing_id": "712939f7-d44c-4df4-85a6-f4cb33a67332",
    "locked": false,
    "project_id": "4322064b-509d-4f53-8f85-ad4ba8cdc4fc",
    "rotation": 0,
    "svg": "<svg height='500' width='500'><circle cx='250' cy='250' r='210' fill='#fff' stroke='#000' stroke-width='8' /></svg>",
    "x": -500,
    "y": -500,
    "z": 0
}
```

And I can also see that the drawing was created in the project by using the get-drawing endpoint.

```
{
        "drawing_id": "712939f7-d44c-4df4-85a6-f4cb33a67332",
        "locked": false,
        "project_id": "4322064b-509d-4f53-8f85-ad4ba8cdc4fc",
        "rotation": 0,
        "svg": "<svg height='500' width='500'><circle cx='250' cy='250' r='210' fill='#fff' stroke='#000' stroke-width='8' /></svg>",
        "x": -500,
        "y": -500,
        "z": 0
}
```

Hope this helps,

Thanks
