### ISSUE TITLE
Renaming IOL hostname replaces %h only in a single place

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-server#1707]
Hello
here is the config I am using in the template for IOL devices:
```
hostname %h
...
interface Ethernet0/0
 ip address dhcp hostname %h
 no shutdown
!
```
If I add a device from the template, change its hostname to R415 for example, the resulting config will be:
```
hostname R415
...
interface Ethernet0/0
 ip address dhcp hostname <auto-generated name from template, e.g. R1>
 no shutdown
!
```
instead of 
```
hostname R415
...
interface Ethernet0/0
 ip address dhcp hostname R415
 no shutdown
!
```

**Comment by grossmj** [comment]
This is the line that causes the problem: https://github.com/GNS3/gns3-server/blob/2.2/gns3server/compute/iou/iou_vm.py#L328

Basically, we only replace when the line starts with `hostname <name>`. I will fix that so it doesn't have to be a new line.

**Comment by dmfigol** [comment]
thank you!
