### ISSUE TITLE
[API] Accept hostname when creating a device from template

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-server#1708]
Unfortunately, this [endpoint](https://gns3-server.readthedocs.io/en/2.2/api/v2/controller/template/projectsprojectidtemplatestemplateid.html) does not allow to set the hostname together with the coordinates, would it be possible to add it as an optional parameter?
Thanks!

**Comment by grossmj** [comment]
Added an optional "name" parameter.
