### ISSUE TITLE
Error while creating link: Attachment 'nat' is configured on network adapter 0. Please stop VMware VM 'Kali-Linux-2019.4-vmware-amd64-1' to link to this adapter and allow GNS3 to change the attachment type.

### ISSUE THREAD

**Issue by adarsh3610** [GNS3/gns3-server#1716]
Error while creating a link: Attachment 'nat' is configured on network adapter 0. Please stop VMware VM 'Kali-Linux-2019.4-VMware-amd64-1' to link to this adapter and allow GNS3 to change the attachment type.
the issue in VMware to gns3

**Comment by grossmj** [comment]
Please tick the "Allow GNS3 to override non custom VMware adapter" in your VM template.

![Screenshot from 2020-03-03 13-42-49](https://user-images.githubusercontent.com/4752614/75746343-f0fd7580-5d54-11ea-91e6-9e0f67042028.png)
