### ISSUE TITLE
How to able to access MySQL workbench from my PC to gns3 (VM) Network Automation mysql

### ISSUE THREAD

**Issue by mohammedtalo** [GNS3/gns3-server#1717]
Dear All

 

Hope this message reach you well and thank you for the help in advance

 

I am running GNS3 through VM workstation that hosts Network Automation

 

Inside Network Automation i am installing Mysql Server and i want to be able to connect from My Windows ( Local Pc) to Network Automation that hosts MySQL Server

 

Why i am doing that, I am doing python code that run and fetch some data and store it inside mysql 

to be able to have better visualization i need that tool

 

Moreover , i have one small issue is that, after installing mysql server and logging off and then logging again, it got deleted it everytime.

 

Please Help 

 

Operating System: Windows 10, Network Automation and VM workstation
GNS3 Software Version: 2.2.3

Operating System: Windows 10, Network Automation and VM workstation
GNS3 Software Version: 2.2.3

**Comment by grossmj** [comment]
Sorry we are unable to help with this issue. Please post on the GNS3 community for help. Thanks.
