### ISSUE TITLE
Make a clear doc about dependencies

### ISSUE THREAD

**Issue by PiAil** [GNS3/gns3-server#1719]
Hello,

I'd like to install GNS3 from source, but I cannot find satisfactory information about the dependencies to use with, and their usefulness in GNS3.

I think that there are at least QEMU, uBridge, libvirt, Wireshark, Dynamips and maybe more.
I'd like to understand the one that are mandatory, **and why** (or better, the list of things I will not be able to do without those dependencies).

A general guidance on how to install them and link them will GNS3 would be great too ( for instance, should I modify some GNS3 config files ? Or, when I compile uBridge, there is no ubridge group, so should I create one and add my gns3 user to it, in a similar way this is done when installing from repository ?)

I'm not sure if this is the right place to ask this, but I think that it would be nice to find those informations in this Github.

**Comment by b-ehlers** [comment]
A short overview:

## Development Tools
Python 3.6+, C-Compiler, make, cmake.

## GNS3 GUI

PyQt5, either part of the linux distribution or install it from PyPi The other python dependencies are automaticallx installed during the gns3-gui installation.

For connecting to the nodes by telnet, a graphical telnet client is required. On Linux that's a terminal emulator like xterm, gnome-terminal, konsole plus the telnet program. For connecting to nodes with a GUI, a VNC client is required, optionally a SPICE client can be used for qemu nodes.

For using packet captures within GNS3 the wireshark program should be installed. It's recommended, but if you don't need that functionality you can go without it.

## GNS3 Server

The python dependencies are automaticallx installed during the gns3-server installation.

uBridge is required, it interconnects the nodes.
dynamips is required for the internal switches and hubs.
VCPS is recommended, it is a builtin device that is always present in the GUI.
qemu is recommended for linux, as most device type are based on qemu, for example IOSv.
linux-only: libvirt is recommended, as it's needed for the NAT cloud
linux only: docker is optional, some devices are based on docker.
linux-only: i386-libraries of libc and libcrypto are optional, only needed for IOU images

**Comment by grossmj** [comment]
That's a great start, thanks @b-ehlers! Also, off topic but can you contact me on developers@gns3.net please? (I don't have your email address).

**Comment by grossmj** [comment]
I have added a bit more explanation to the README pages. I feel we would need to review and add more information at some point.

Also, you can have a look at how we install dependencies and add some tweaks on Linux for our GNS3 VM: https://github.com/GNS3/gns3-vm/blob/bionic-stable/config/install.sh
