### ISSUE TITLE
Error during installation from source

### ISSUE THREAD

**Issue by jakubkameleon** [GNS3/gns3-server#1722]
Could I ask for help? I traing install gns3-server on my Debian 10 from source. I have some problems.

`Installed /usr/local/lib/python3.7/dist-packages/gns3_server-2.2.5-py3.7.egg
Processing dependencies for gns3-server==2.2.5
Searching for psutil==5.6.3
Reading https://pypi.org/simple/psutil/
Downloading https://files.pythonhosted.org/packages/1c/ca/5b8c1fe032a458c2c4bcbe509d1401dca9dda35c7fc46b36bb81c2834740/psutil-5.6.3.tar.gz#sha256=863a85c1c0a5103a12c05a35e59d336e1d665747e531256e061213e2e90f63f3
Best match: psutil 5.6.3
Processing psutil-5.6.3.tar.gz
Writing /tmp/easy_install-w7rnfaaw/psutil-5.6.3/setup.cfg
Running psutil-5.6.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-w7rnfaaw/psutil-5.6.3/egg-dist-tmp-x274iu7g
/tmp/easy_install-w7rnfaaw/psutil-5.6.3/temp/tmpjziqzpw0.c:1:10: fatal error: linux/ethtool.h: No such file or directory
 #include <linux/ethtool.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by grossmj** [comment]
Have you found a solution?
