### ISSUE TITLE
Issue with VNC Process Crashing

### ISSUE THREAD

**Issue by djjohnmerry** [GNS3/gns3-server#1725]
Since moving to Version 2.2 whenever I use a console to VNC to a server such as the webterm server.

The vnc process has stopped with return code 2 for node 'webterm-1'. Please restart this node. - in the console.

and the VNC errors as "connection has been gracefully closed".

The machine I am using for example is the webterm server.

I am running bare metal in AWS on a i3.metal with KVM on everything else is fine

Any ideas of the possible issue?

**Comment by cioby23** [comment]
I also experienced this issue many times and I could not find a solution for this yet.
I'm not sure if this is Docker related or GNS3. I also tried to use the latest VNC client but no luck and I think this only happens only on Windows client, on Linux if works fine.

**Comment by grossmj** [comment]
What VNC client do you use?

In the GNS3 VM, the servers looks for tigervnc-standalone-server (recommended), if it is not available the server will look for Xvfb + x11vnc

**Comment by cioby23** [comment]
The GNS3 server is not installed on GNS3 VM but on a standalone Ubuntu 18.04 running on bare metal. I have checked and I was running x11vnc on the server side. 
I removed it and installed tigervnc-standalone-server and so far I did not received any messages similar to this one 'The vnc process has stopped with return code 2 for node 'webterm-1'. Please restart this node.'
It's possible that x11vnc might be the culprit.

**Comment by grossmj** [comment]
> It's possible that x11vnc might be the culprit.

I think that was the reason we moved to tigervnc: https://github.com/GNS3/gns3-server/issues/1438

I am closing this, please comment back if you still experiencing issues using tigervnc.
