### ISSUE TITLE
Add Xvnc command to the VNC servers list

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-server#1728]
Currently TigerVNC package in Ubuntu uses a specific name for the VNC server binary called **Xtigervnc** which I think is only specific to Debian/Ubuntu based distros.
I use TigerVNC on ArchLinux and the VNC server binary is called **Xvnc** as on the application docs. So far in order to use TigerVNC on ArchLinux I made a symbolic link pointing to Xvnc binary location.
sudo ln -s /usr/bin/Xvnc /usr/bin/Xtigervnc
Please add Xvnc binary to the path list here so it can be used by other Linux distros
https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/docker/docker_vm.py#L567
and here
https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/docker/docker_vm.py#L570

**Comment by grossmj** [comment]
Implement in https://github.com/GNS3/gns3-server/commit/afbbf7a5244663d96a938c0c014bfb1919841abc

Thanks :+1:
