### ISSUE TITLE
Dynamips hypervisor process has stopped, return code: -11

### ISSUE THREAD

**Issue by madjidcr77** [GNS3/gns3-server#1734]
when i try to start any router (1700,2600,3600,7200) it doesn't and it say :
'Ghost': generic_nvram_extract_config: Unknown error -61605
Could not send Dynamips command 'vm set_ghost_status "R1" 2' to 127.0.0.1:51861: [Errno 32] Broken pipe, process running: False
 my OS is Kali linux 2020

**Comment by grossmj** [comment]
What is your Dynamips version and the IOS image filenames your have tried?

**Comment by madjidcr77** [comment]
i solved the issue thanks !

**Comment by ojasdeshpande10** [comment]
Same issue plss help with the resolve

**Comment by ojasdeshpande10** [comment]
> when i try to start any router (1700,2600,3600,7200) it doesn't and it say :
> 'Ghost': generic_nvram_extract_config: Unknown error -61605
> Could not send Dynamips command 'vm set_ghost_status "R1" 2' to 127.0.0.1:51861: [Errno 32] Broken pipe, process running: False
> my OS is Kali linux 2020

my router image file is this one c3745-advipservicesk9-mz.124-25d.image

**Comment by atanwar21** [comment]
Same issue on Ubuntu Linux 20.10  - Unable to start c7200 router

error while starting R1: Could not send Dynamips command 'vm set_ghost_status "R1" 2' to localhost:52661: [Errno 32] Broken pipe, process running: False

Please support

**Comment by ManBenit** [comment]
> Same issue on Ubuntu Linux 20.10 - Unable to start c7200 router
> 
> error while starting R1: Could not send Dynamips command 'vm set_ghost_status "R1" 2' to localhost:52661: [Errno 32] Broken pipe, process running: False
> 
> Please support

I have the same exactly this problem, please support.
