### ISSUE TITLE
remote-install.sh installs version 2.1.21 instead of the latest stable version

### ISSUE THREAD

**Issue by MheniMerz** [GNS3/gns3-server#1736]
Hi,

I'm trying to install a remote GNS3 server and I'm using the following commands on an Ubuntu 16.04 server.

```
cd /tmp
curl https://raw.githubusercontent.com/GNS3/gns3-server/master/scripts/remote-install.sh > gns3-remote-install.sh
sudo bash gns3-remote-install.sh --with-iou --with-i386-repository
```
the script runs great and I get a GNS3 installed successfully at the end, however when checking the version I get the following.
```
user@gns3vm:~$ gns3server --version
2.1.21
```
which poses a problem when trying to connect with the latest gns3 GUI

**Comment by grossmj** [comment]
Version 2.1.21 is the last version supported on Ubuntu 16.04 because GNS3 version 2.2.x requires Python >= 3.5.3

However it is still possible to install using these instructions for example:

```
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install -y python3.6 python3.6-dev python3.6-venv
sudo python3.6 -m ensurepip --upgrade
sudo python3.6 -m pip install gns3-server==2.2.7
sudo python3.6 -m pip install gns3-gui==2.2.7
```

Hope this answers your question.
