### ISSUE TITLE
Create a module that coordinates access to cpu_percent()

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1738]
See https://github.com/GNS3/gns3-server/commit/3df348ac2a7cc8950ccd952d8d0ec67a1ef45bd5#commitcomment-38451576

**Comment by b-ehlers** [comment]
PR https://github.com/GNS3/gns3-server/pull/1745

**Comment by grossmj** [comment]
Thanks for the PR! :+1:
