### ISSUE TITLE
Implement NIO User mode/SLIRP in the cloud

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#174]
To explicitly connect Qemu VMs to user mode networking back-ends instead of automatically connecting unused ports.

**Comment by grossmj** [comment]
Ok, we will name it NIO NAT (nio_nat).

**Comment by grossmj** [comment]
@ehlers I've implemented NIO NAT for Qemu VMs.

**Comment by ehlers** [comment]
Looks really good, also with VirtualBox.

In the sources of nio_nat.py I see that the __str__ method returns "NIO_TAP", I assume it should be "NIO_NAT".
