### ISSUE TITLE
Create capability for server to refresh template

### ISSUE THREAD

**Issue by fadlytabrani** [GNS3/gns3-server#1743]
I have successfully created a cluster of 4 GNS3 server nodes, replicating all settings and images using csync2. My only issue right now when the file /etc/gns3/gns3_controller.conf has been replicated to all nodes, I have to restart all services to ensure the templates are reloaded. This causes all active projects to stop. Could we add a functionality to "reload" services like httpd? i.e 

`systemctl reload gns3`

**Comment by fadlytabrani** [comment]
Similar to #1676

**Comment by grossmj** [comment]
I think to support this we need to add `ExecReload=/bin/kill -s HUP $MAINPID` to gns3.service file and support SIGHUP to reload all settings in the GNS3 server.

**Comment by grossmj** [comment]
The server can now reload templates, appliances and new projects by sending SIGHUP to its PID or using `systemctl reload gns3.service`

**Comment by grossmj** [comment]
We should also add an API endpoint to reload the server (this would be secured once we implement user management & security support).
