### ISSUE TITLE
Debian packages for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by zapotah** [GNS3/gns3-server#1746]
The ppa repository does not contain a binary package for 2.2.7 on ubuntu 20.04 and the source package tar does not have up-to-date dependencies for building from the source package.

**Comment by zapotah** [comment]
opened here since the official documentation points to the ppa

**Comment by younabobo** [comment]
This applies to both gns3-server and gns3-gui

**Comment by grossmj** [comment]
Looks like the build failed on our ppa because of a missing dependency: `dh-virtualenv`

https://launchpad.net/~gns3/+archive/ubuntu/ppa/+builds?build_text=&build_state=all

dh-virtualenv is not available for Ubuntu 20.04: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=dh-virtualenv&searchon=names

I am going to research why and if there is an alternative.

**Comment by grossmj** [comment]
https://github.com/spotify/dh-virtualenv/issues/298

**Comment by grossmj** [comment]
I don't know why `dh-virtualenv` isn't available on Ubuntu 20.04 LTS. I suspect we won't be the only ones facing that issue in the next few weeks...

**Comment by zapotah** [comment]
This has most likely got to do with python 2 deprecation in 20.04. Python 2.7 is still available but basically the paths et al have been changed and package names changed so that most dependencies with apt are likely broken.

Likely the source and such config scripts are somehow still pointing to python2 and some package dependencies there so that dh-virtualenv fails to compile itself.
https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-Clear-Python2

**Comment by zapotah** [comment]
I will test building dh-virtualenv with the following: https://dh-virtualenv.readthedocs.io/en/1.1/howtos.html#building-packages-for-python3

**Comment by zapotah** [comment]
after mucking about a lot today with this, i managed to get dh-virtualenv to compile after modifying debian/control to include the python3 dependencies instead of python2 and editing debian/rules to include python3 references and adding --buildsystem=pybuild to the dh arguments. In addition the path to debhelper has either changed or is no longer shipped as part of python3 base and is found instead in /usr/share/dh-python/.
Thus bin/dh_virtualenv:27 needs to be changed
sys.path.insert(1, '/usr/share/python/') <-original
sys.path.insert(1, '/usr/share/dh-python/') <-changed
bin/dh_virtualenv:29 needs to be adjusted to reflect path change as well
from debpython.debhelper import DebHelper <-original
from dhpython.debhelper import DebHelper <-changed


Even after managing to get dh-virtualenv to compile and install, the gns3-server source package has python2 package dependencies and it does not compile the package properly. My expertise with debian packaging and build debugging ends here as there is no clear error that would indicate what fails to build when issuing "debuild -us -uc" or what fails at the packaging step of the build process.

**Comment by zapotah** [comment]
In the meantime, adjusting the script to install from pip, instead install only the gns3-server dependencies and fixing docker installation to point to focal default package docker.io due to docker not having released newer packages for focal just yet. Adjust the systemd unit file to point gns3server to /usr/local/bin/gns3server and everything seems to be peachy.

**Comment by grossmj** [comment]
I am sure this is going to be fixed fairly soon since we aren't the only ones facing that problem. Backup plan would be to build a patched version of dh-virtualenv and use that to build the gns3 packages on our PPA.

**Comment by PranavBhattarai** [comment]
I can help in some ways please do let me know. Meanwhile, I **CANNOT** use GNS3.

![Screenshot from 2020-05-14 13-07-33](https://user-images.githubusercontent.com/32763112/81905071-edebf480-95e3-11ea-829e-d810660f0562.png)

**Comment by grossmj** [comment]
We got rid of dh-virtualenv to build the Debian package for Ubuntu 20.04 LTS however the packages will only be available once we release version 2.2.9 scheduled for June 3rd.

**Comment by grossmj** [comment]
dh-virtualenv has been converted to Python 3: https://github.com/spotify/dh-virtualenv/pull/300

Now I think I will try use dh-virtualenv again to create the Debian packages for Ubuntu 20.04 LTS

**Comment by grossmj** [comment]
I packaged v2.2.9 for Ubuntu 20.04 LTS using dh-virtualenv 1.2-dev1, which is in our dev PPA on https://launchpad.net/~gns3/+archive/ubuntu/dev

The packaged v2.2.9 is available in our unstable PPA repository and everything works as expected: https://launchpad.net/~gns3/+archive/ubuntu/unstable?field.series_filter=focal

So, next release we will be back to the post v2.2.9 way of packaging GNS3 for Debian (using dh-virtualenv).
