### ISSUE TITLE
aiohttp-cors-0.7.0 and python 3.8

### ISSUE THREAD

**Issue by oniGino** [GNS3/gns3-server#1748]
Hi, I'm your maintainer for Gentoo,

In order to keep gns3 in portage tree we need gns3-server to build against python3.8 AFAICT that's impossible due to aiohttp-cors-0.7.0 which doesn't appear to support python 3.7 or python 3.8.
we have a patch for 3.7, but moving forward, not sure what to do here.

**Comment by grossmj** [comment]
I am running gns3server with Python 3.8, aiohttp-cors-0.7.0 is installed and I couldn't see any issues.

There is no apparent restrictions to use aiohttp-cors with Python 3.7 and 3.8
https://github.com/aio-libs/aiohttp-cors/blob/v0.7.0/setup.py

Please, can you provide more details regarding the problem you are facing?

**Comment by cioby23** [comment]
I'm also running GNS3 on Archlinux using Python 3.8 and aiohttp-cors-0.7.0 for several months and did not encountered any issue yet.

**Comment by grossmj** [comment]
@oniGino any update?

**Comment by oniGino** [comment]
Sorry for the delay, we are able to build on 3.8 without issue
