### ISSUE TITLE
Changes in requirements.txt broke setup.py

### ISSUE THREAD

**Issue by nuqleo** [GNS3/gns3-server#1751]
Hello,

Changes in requirements.txt from gns3-server 2.2.8 broke setup.py

$ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
error in gns3-server setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'; python'"

setup.py with requirements.txt from 2.2.7 succeeded.

I have installed python 3.8.2, python3-jsonschema-3.2.0, python3-setuptools-46.1.3

**Comment by grossmj** [comment]
This may be due to the following lines in requirements.txt:

```
jsonschema==3.2.0; python_version >= '3.8'  # pyup: ignore
jsonschema==2.6.0; python_version < '3.8'  # pyup: ignore
```

What Linux distro do you have? Also, what is your pip version?

```
python3 -m pip --version
pip 19.2.3 from /home/grossmj/.local/lib/python3.6/site-packages/pip (python 3.6)
```

Thanks.

**Comment by grossmj** [comment]
Updating setuptools should solve that issue, try this and then reinstall GNS3:

```
sudo python3 -m pip install --upgrade pip setuptools
```

**Comment by nuqleo** [comment]
Linux distro is Fedora 32.  
https://copr-be.cloud.fedoraproject.org/results/nucleo/gns3/fedora-32-x86_64/01372421-gns3-server/gns3-server.spec

**Comment by nuqleo** [comment]
python3-setuptools in Fedora Rawhide is 46.1.3, this is latest version https://pypi.org/project/setuptools/ but it fails.

**Comment by grossmj** [comment]
I have no issue installing the latest GNS3 server in a clean Docker container running Fedora 32:

I installed python3-pip, python3-devel and gcc using dnf then installed GNS3 with `pip3 install gns3-server`

```
python3 -m pip --version
pip 19.3.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```

`python3 setup.py build` also works after downloading the sources from git.

**Comment by nuqleo** [comment]
Maybe something differs when 'python3 setup.py build' started by hands and in Fedora koji automatic buildsystem where only python modules from system packages can be used.
This lines with causing the problem "; python..." in git the same as in 2.2.8
jsonschema==3.2.0; python_version >= '3.8'  # pyup: ignore
jsonschema==2.6.0; python_version < '3.8'  # pyup: ignore

**Comment by grossmj** [comment]
`jsonschema==2.6.0` is only required for our Windows and macOS builds (frozen apps) where we can control the version of Python. So I moved that requirement in our build process and only left `jsonschema==3.2.0` in requirements.txt

That should solve this issue.
