### ISSUE TITLE
Some tests fail with Python 3.8

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#1752]
Debian bullseye 11.0
gns3-server 2.2.8
python 3.8.3rc1
pytest-4.6.9
py-1.8.1
pluggy-0.13.0
flaky-3.6.1

```
python3.8 setup.py install
py.test -vv
```
leads to this log
[gns3-server_2.2.8-11.0_amd64_tests.log](https://github.com/GNS3/gns3-server/files/4598315/gns3-server_2.2.8-11.0_amd64_tests.log)

I will try the same on Ubuntu focal LTS.

These test issues do not prevent gns3 server from running fine with a common usage.

**Comment by grossmj** [comment]
Indeed, lot of errors running tests with Python 3.8. Thanks for catching that.

**Comment by jean-christophe-manciot** [comment]
Ubuntu 20.04 focal LTS
gns3-server 2.2.8
python 3.8.2
pytest-4.6.9
py-1.8.1
pluggy-0.13.0
cov-2.8.1
timeout-1.3.3
flaky-3.6.1
```
python3.8 setup.py install
py.test -vv
```
leads to some test issues as well:
[gns3-server_2.2.8-20.04_amd64_tests.log](https://github.com/GNS3/gns3-server/files/4598175/gns3-server_2.2.8-20.04_amd64_tests.log)

The list of all PASSED/FAILED tests is exactly the same.
There are only a few significant differences in the tests log
[gns3-server_2.2.8-11-20.04_amd64_tests_diffs.log](https://github.com/GNS3/gns3-server/files/4598308/gns3-server_2.2.8-11-20.04_amd64_tests_diffs.log)

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/pull/1782
