### ISSUE TITLE
Error when listing Hyper-V VMs

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1755]
```
File "./gns3-server\gns3server\web\route.py", line 198, in control_schema
File "./gns3-server\gns3server\handlers\api\controller\gns3_vm_handler.py", line 52, in get_vms
File "./gns3-server\gns3server\controller\gns3vm\_init_.py", line 261, in list
File "./gns3-server\gns3server\controller\gns3vm\hyperv_gns3_vm.py", line 188, in list
AttributeError: 'NoneType' object has no attribute 'SystemName'
```

![gns3vm](https://user-images.githubusercontent.com/4752614/81555747-421a8d00-93c8-11ea-8756-44dadde03647.jpg)

**Comment by radyphan** [comment]
any update regarding this issue? i have been face this issue as well.

**Comment by grossmj** [comment]
Please try this: add your Windows account to the Hyper-V admin group and then try again.

![Screenshot from 2020-05-18 12-39-58](https://user-images.githubusercontent.com/4752614/82170833-bdb69580-9904-11ea-9c46-6d98dd807629.png)

Also, please open Powershell, execute this command `gwmi -namespace root\virtualization\v2 Msvm_VirtualSystemManagementService -computername .` and let me know the outcome.

Thanks

**Comment by grossmj** [comment]
You can also try this if you have Python installed:

First make sure the wmi module is installed, for instance: `C:\Users\GNS3\AppData\Local\Programs\Python\Python36\Scripts\pip.exe install wmi`

Than execute the following script:

```
import wmi

wmiServerConnection = wmi.WMI(namespace=r"root\virtualization\v2")
print(wmiServerConnection.Msvm_VirtualSystemManagementService())
```

**Comment by piotrpekala7** [comment]
@grossmj Output:
[<_wmi_object: b'\\\\DVB-KRA-PPEK-00\\root\\virtualization\\v2:Msvm_VirtualSystemManagementService.CreationClassName="Msvm_VirtualSystemManagementService",Name="vmms",SystemCreationClassName="Msvm_ComputerSystem",SystemName="DVB-KRA-PPEK-00"'>]

**Comment by piotrpekala7** [comment]
> Also, please open Powershell, execute this command gwmi -namespace root\virtualization\v2 Msvm_VirtualSystemManagementService -computername . and let me know the outcome.

@grossmj Output:
__GENUS                  : 2
__CLASS                  : Msvm_VirtualSystemManagementService
__SUPERCLASS             : CIM_VirtualSystemManagementService
__DYNASTY                : CIM_ManagedElement
__RELPATH                : Msvm_VirtualSystemManagementService.CreationClassName="Msvm_VirtualSystemManagementService",Name="vmms",SystemCreationC
                           lassName="Msvm_ComputerSystem",SystemName="DVB-KRA-PPEK-00"
__PROPERTY_COUNT         : 28
__DERIVATION             : {CIM_VirtualSystemManagementService, CIM_Service, CIM_EnabledLogicalElement, CIM_LogicalElement...}
__SERVER                 : DVB-KRA-PPEK-00
__NAMESPACE              : root\virtualization\v2
__PATH                   : \\DVB-KRA-PPEK-00\root\virtualization\v2:Msvm_VirtualSystemManagementService.CreationClassName="Msvm_VirtualSystemManag
                           ementService",Name="vmms",SystemCreationClassName="Msvm_ComputerSystem",SystemName="DVB-KRA-PPEK-00"
AvailableRequestedStates :
Caption                  : Hyper-V Virtual System Management Service
CommunicationStatus      :
CreationClassName        : Msvm_VirtualSystemManagementService
Description              : Service for creating, manipulating, and managing virtual systems
DetailedStatus           :
ElementName              : Hyper-V Virtual System Management Service
EnabledDefault           : 2
EnabledState             : 2
HealthState              : 5
InstallDate              : 20190102085111.000000-000
InstanceID               :
Name                     : vmms
OperatingStatus          :
OperationalStatus        : {2}
OtherEnabledState        :
PrimaryOwnerContact      :
PrimaryOwnerName         :
PrimaryStatus            :
RequestedState           : 12
Started                  : True
StartMode                :
Status                   : OK
StatusDescriptions       : {The service is running normally}
SystemCreationClassName  : Msvm_ComputerSystem
SystemName               : DVB-KRA-PPEK-00
TimeOfLastStateChange    : 20200311171621.000000-000
TransitioningToState     :
PSComputerName           : DVB-KRA-PPEK-00

**Comment by piotrpekala7** [comment]
after adding windows account to hyper-v admin group the problem still exists

**Comment by radyphan** [comment]
Follow every step you shown above, but unfortunatly it still Error the same page.

**Comment by grossmj** [comment]
Sentry issue: [GNS3-SERVER-2EN](https://sentry.io/organizations/gns3/issues/1527911753/?referrer=github_plugin)

**Comment by grossmj** [comment]
Let's see the problem happens in the next release.

**Comment by tali1974** [comment]
Hi. How can i download GNS3 2.2.10 for windows ?

**Comment by grossmj** [comment]
> Hi. How can i download GNS3 2.2.10 for windows ?

Version 2.2.10 is scheduled to be released on June 3.

**Comment by venilev** [comment]
Adding my windows account to the Hyper-V group solved the issue. You have to make sure you reboot your machine in order for this to work!

**Comment by grossmj** [comment]
@venilev thanks for the info :+1: 

@tali1974 @piotrpekala7 @radyphan 

Please can you test using version 2.2.9 and let me know if you still get the error message? Thanks.

**Comment by piotrpekala7** [comment]
@grossmj yes, it works correctly in 2.2.9
