### ISSUE TITLE
Cannot export project: [WinError 32]

### ISSUE THREAD

**Issue by msett** [GNS3/gns3-server#1756]
Hello,

I Have the following error each time I want to export a portable project in gns3 :
Cannot export project: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\setta\\AppData\\Local\\Temp\\tmp967xhkh8\\tmpw435aaz4'

the gns3 client is running in win10 and the server is locally running in vmware workstation 
both the client and the server is 2.2.8 

Thank you so much for your reply.

Best regards,
M Sett

**Comment by grossmj** [comment]
Unfortunately I cannot reproduce the problem. What type of nodes does your project contain?

Besides this, I would recommend using the GNS3 VM.
