### ISSUE TITLE
MissingSectionHeaderError: File contains no section headers.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#176]
https://app.getsentry.com/gns3/gns3-server/group/63010522/

```
MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\ranafsi\\AppData\\Roaming\\GNS3\\gns3_server.ini', line: 1
'{\n'
(2 additional frame(s) were not displayed)
...
  File "./gns3-server\gns3server\handlers\api\config_handler.py", line 38, in reload
  File "./gns3-server\gns3server\config.py", line 126, in reload
  File "./gns3-server\gns3server\config.py", line 138, in read_config
  File "C:\Python34-64bit\lib\configparser.py", line 672, in read
  File "C:\Python34-64bit\lib\configparser.py", line 1058, in _read
```

**Comment by grossmj** [comment]
Catching configparser.Error should do it.

**Comment by grossmj** [comment]
Have you tested how the server reacts with the same gns3_server.ini (containing just "{")?

**Comment by noplay** [comment]
It's invalid. But the file is not a JSON it's an ini file.

On Tue, May 5, 2015 at 5:33 PM, Jeremy Grossmann <notifications@github.com>
wrote:

> Have you tested how the server reacts with the same gns3_server.ini
> (containing just "{")?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-server/issues/176#issuecomment-99117697>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>
