### ISSUE TITLE
gns3vm grayed out

### ISSUE THREAD

**Issue by khanzia05** [GNS3/gns3-server#1760]
i have gns3 2.2.5 and gns3vm2.2.5, VMware workstation player12.1. when i open gns3 gns3vm is opening automatically but showing grayed out. when i take cursor to grayed out gns3vm it popup is saying discovering or connecting to gns3vm. 

I DISABLED FIREWALL ALSO

I am able to do ssh and ping  to gns3vm.
![image](https://user-images.githubusercontent.com/38636056/82480697-cf10c500-9af1-11ea-93f4-c2034ee21666.png)

![image](https://user-images.githubusercontent.com/38636056/82480776-ed76c080-9af1-11ea-8a9a-366fc58a2231.png)

![image](https://user-images.githubusercontent.com/38636056/82480844-0d0de900-9af2-11ea-88f5-915c5f2787d4.png)

![image](https://user-images.githubusercontent.com/38636056/82481044-58c09280-9af2-11ea-9ef2-687ed75aa176.png)
![image](https://user-images.githubusercontent.com/38636056/82481508-08960000-9af3-11ea-8b77-e42272ecf07f.png)
![image](https://user-images.githubusercontent.com/38636056/82481518-0d5ab400-9af3-11ea-8dce-28162a3cf1fd.png)

Please help.

**Comment by khanzia05** [comment]
if anyone can help and understand what could be the issue while troubleshooting when i selected localhost in gns3--server-host binding to 127.0.0.1 i got connection refused. i moved it back to localhost and gns3vm become green. the whole day i shut down my PC number of times and it work. but again in afternoon i opened the system and it is not working.

**Comment by khanzia05** [comment]
Hi,

I observed my Virtual adapters were getting APIPA IP. Rebooted the PC multiple times and now the got ip and GNS3VM is green.

anyone any idea why they were getting APIPA IP.

**Comment by grossmj** [comment]
Please see my comments on https://gns3.com/community/discussion/gns3-vm-showing-grey

This should help.

**Comment by grossmj** [comment]
I am going to close this for now. Please try with version 2.2.9 and post back if you still have issues.
