### ISSUE TITLE
Reinitializing node MAC addresses when duplicating projects causes issues.

### ISSUE THREAD

**Issue by fadlytabrani** [GNS3/gns3-server#1762]
When duplicating projects, node mac addresses are reinitialized. Linux network devices such as Vyos that we use extensively detects the MAC change, instantiates a new interface name. This makes all configurations invalid. 

This behaviour was changed after the following issue was raised -> #1522 

To correct the previous issue, the fix should have been to reinitialise cloud nodes only instead of all nodes in the project.

**Comment by grossmj** [comment]
> To correct the previous issue, the fix should have been to reinitialise cloud nodes only instead of all nodes in the project.

As commented on https://github.com/GNS3/gns3-server/pull/1763, this isn't that simple. One alternative would be to provide the option to reset MAC addresses when an user export or import a project.

For instance, VMware and VIrtualBox have the option to reset the MAC addresses when you import a VM as an OVA. This is probably the best solution.

**Comment by fadlytabrani** [comment]
This option should be presented during duplication and exporting of projects. 

![image](https://user-images.githubusercontent.com/1628412/82726861-3e70f980-9d2a-11ea-99b5-cf96c1717459.png)

![image](https://user-images.githubusercontent.com/1628412/82726874-56e11400-9d2a-11ea-8ca5-0fd031fbf86c.png)

**Comment by grossmj** [comment]
I have added the option for exporting and duplicating a project.
