### ISSUE TITLE
Qemu VM + SPICE does not start

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-server#1772]
Environment:
OS: ArchLinux
GNS3 version: 2.2.9
Qemu version: 5.0.0

I'm trying to start a Linux VM using Spice+agent as the console type and the machine fails to start. Below is the error from the console.

**QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-x86_64 -name ArchLinux-1 -m 1536M -smp cpus=1 -enable-kvm -machine smm=off -boot order=c -drive file=/home/cioby/GNS3/projects/untitled/project-files/qemu/72f08bc8-ad6a-44f0-b81d-3df1ede9aa82/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0 -uuid 72f08bc8-ad6a-44f0-b81d-3df1ede9aa82 -spice addr=::,port=5018,disable-ticketing -vga qxl -monitor tcp:127.0.0.1:43773,server,nowait -net none -device virtio-net-pci,mac=0c:61:e1:aa:82:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -nographic

Execution log:
qemu-system-x86_64: warning: Spice: ../spice-0.14.3/server/reds.c:2620:reds_init_socket: getaddrinfo(::,5018): Address family for hostname not supported
qemu-system-x86_64: warning: Spice: ../spice-0.14.3/server/reds.c:3512:do_spice_init: Failed to open SPICE sockets
qemu-system-x86_64: failed to initialize spice server**

The culprit is this addr parameter from the spice command spice **addr=::**. If I change it to 127.0.0.1 it works fine. I have noticed that a while ago a similar issue happened and was partially fixed here https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/qemu/qemu_vm.py#L1539

I just found that the recommended way to connect to spice channels is to use Unix sockets instead of relying on the network stack on the host system.

For more details check here:
https://wiki.archlinux.org/index.php/QEMU#Enabling_SPICE_support_on_the_host

**Tip**: Using Unix sockets instead of TCP ports does not involve using network stack on the host system. It does not imply that packets are encapsulated and decapsulated to use the network and the related protocol. The sockets are identified solely by the inodes on the hard drive. It is therefore **considered better for performance.** Use instead -spice unix,addr=/tmp/vm_spice.socket,disable-ticketing.

**Comment by grossmj** [comment]
Agreed, using Unix sockets should be better. Thanks for the details!

**Comment by b-ehlers** [comment]
But Unix sockets work only locally. If the QEMU VM doesn't run on the system, where the viewer is running, you need TCP networking. Even though sockets are faster I suggest to keep the more flexible TCP connection.

**Comment by cioby23** [comment]
I agree that TCP networking is required to connect from remote client using SPICE.
I have found why I experienced the above error. I had IPv6 disabled, I guess a did some troubleshooting a while ago and forgot it disabled.
Once I have enabled it back it works fine.

I started a Qemu VM from command line and I removed the addr parameter from -spice option (**-spice addr=::,port=5018,disable-ticketing**)and I still was able to start successfully the VM.

I do not understand why it was required to set the console_host variable to IPv6 localhost ::1 instead to listen on any available address IPv4 or IPv6.

https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/qemu/qemu_vm.py#L1547

I think this should check all 3 possible situations IPv4 only, IPv6 only and IPv4 + IPv6 on.

**Comment by grossmj** [comment]
> I do not understand why it was required to set the console_host variable to IPv6 localhost ::1 instead to listen on any available address IPv4 or IPv6.

I think this is because of a bug in Qemu: https://github.com/GNS3/gns3-gui/issues/2352

**Comment by grossmj** [comment]
I am not sure how to fix this issue. Should we test if IPv6 is not enabled and throw an error explicitly saying that IPv6 must be enable in order to use SPICE?

**Comment by cioby23** [comment]
Nowadays all operating systems are Idual stack IP enabled (IPv4 + IPv6) so in case IPv6 is disabled for some reason a message can displayed to notify the user that IPv6 is required when using SPICE for console access.
Right now the error message **getaddrinfo(::,5018): Address family for hostname not supported** is very generic and does not tell you why the Qemu machine cannot start when using SPICE for console connection.

**Comment by grossmj** [comment]
Thanks, I added an explicit error message.
