### ISSUE TITLE
Error After Upgrade to 2.2.9

### ISSUE THREAD

**Issue by yuljk** [GNS3/gns3-server#1776]
Hi guys - After upgrading the GNS VM from version 2.2.8 to 2.2.9 I receive the following error:

 /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
 RequestsDependencyWarning)

Many thanks

**Comment by cioby23** [comment]
@yuljk this has already been discussed here https://github.com/GNS3/gns3-server/issues/1773
It's not GNS3 related but more an incompatibility between python-requests and chardet module installed on the Ubuntu server.
You can remove python-requests and the warning will dissapear.
