### ISSUE TITLE
Disable check for nested virtualization only working on Intel CPUs

### ISSUE THREAD

**Issue by Larswa** [GNS3/gns3-server#1777]
So ... after the latest Fast Ring Windows build version 19640, Microsoft FINALLY enabled nested virtualization on AMD Ryzen Cpus. 

As seen in the screenshots, I am running a Ryzen 9 3900X and In hyperV KVM is supported. Yeay!!

![image](https://user-images.githubusercontent.com/1431240/84211311-5af78a80-aabb-11ea-83c8-0e03b36c7917.png)

![image](https://user-images.githubusercontent.com/1431240/84211416-9e51f900-aabb-11ea-9afd-49ed6dc3f693.png)

But I am still unable to hook up GNS to this VM, as I am still getting "Error while listing vms: GNS3VM : An Intel  processor is required by Hyper-V to support nested virtualization."

Well ... no longer baby!!   Yeay!  :-D   

So how do we work around this limitation, while not all are brave enough to go on the windows Fast Ring builds?

**Comment by Larswa** [comment]
Yeah ... I can see this is hard coded in the `controller/gns3vm/hyperv_gns3_vm.py`

``` 
if conn.Win32_Processor()[0].Manufacturer != "GenuineIntel":
            raise GNS3VMError("An Intel processor is required by Hyper-V to support nested virtualization")
```

Could this maybe be softened up somehow?   Maybe check for windows build numbers below 16400?  


Also check this thread for verification of AMD nested virtualization being enabled for this build. 
https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1276

**Comment by grossmj** [comment]
Thanks guys, AMD is now allowed on Windows 10 build 19640 or later. This will work in our next release, version 2.2.10.

**Comment by Larswa** [comment]
Hi @grossmj    ... thanks for adding the quick buildnumber check. 

To make it work with no hassels we need one more change.  Along with the hyper-v images that are downloaded is a small 4-5 lines powershell script that creates the new machine, enables nested virtualization in the hyperv machine and attaches the disks and so on ...

The New-Vm command needs to look like this to support nested virtualization with AMD:

`new-vm [The machine name] -Version 9.3`

The default VM version is 9.0 and this does not support nested virt, so we need the version parameter to ensure the machine is working. Most users out of the box probably doesn't know how to tweak this, so if we could get that change in there, that would be good. 

I couldn't see where the Hyper-v images lives, otherwise I would just have done this in a pull request.

**Comment by grossmj** [comment]
@Larswa I think you are referring to this script: https://github.com/GNS3/gns3-vm/blob/bionic-stable/create-vm.ps1

I will change this:

`New-VM -Name "GNS3 VM" -Generation 1 -MemoryStartupBytes 1GB -SwitchName "Default Switch"`

to this:

`New-VM -Name "GNS3 VM" -Generation 1 -Version 9.3 -MemoryStartupBytes 1GB -SwitchName "Default Switch"`

**Comment by Larswa** [comment]
Looks good! That worked for me locally.

**Comment by grossmj** [comment]
For info, I have improved the create vm script to do more checks and only try to use VM version 9.3 for AMD processors with Windows 10 build >= 19640.

```
# Create the GNS3 VM with nested virtualization support
$Manufacturer = (Get-WMIObject win32_Processor).Manufacturer
$WindowsVersion = ([environment]::OSVersion.Version).Major
$BuildNumber = ([environment]::OSVersion.Version).Build
$SwitchName = "Default Switch"
if ($Manufacturer -eq "GenuineIntel") {
  if ($WindowsVersion -eq 10 -and $BuildNumber -lt 14393) {
    Write-Error "Hyper-V with nested virtualization is only supported on Windows 10 Anniversary Update (build 10.0.14393) or later" -ErrorAction Stop
  }
  New-VM -Name "GNS3 VM" -Generation 1 -MemoryStartupBytes 1GB -SwitchName $SwitchName
}
ElseIf ($Manufacturer -eq "AuthenticAMD") {
  if ($WindowsVersion -eq 10 -and $BuildNumber -lt 19640) {
    Write-Error "Windows 10 (build 10.0.19640) or later is required by Hyper-V to support nested virtualization with AMD processors" -ErrorAction Stop
  }
  New-VM -Name "GNS3 VM" -Generation 1 -Version 9.3 -MemoryStartupBytes 1GB -SwitchName $SwitchName
}
Else {
    Write-Error "Hyper-V with nested virtualization does not support $Manufacturer processors" -ErrorAction Stop
}
```

**Comment by grossmj** [comment]
There is something confusing me, should we check for build 19640 or 19645?

Microsoft has announced nested virtualization support for AMD there:

https://blogs.windows.com/windowsexperience/2020/06/10/announcing-windows-10-insider-preview-build-19645/

**Comment by Larswa** [comment]
19640. I know it says in the release notes for 19645 that and
virtualization had been implemented but it made it into 19640.

Sent from my phone

lør. 13. jun. 2020 05.15 skrev Jeremy Grossmann <notifications@github.com>:

**Comment by grossmj** [comment]
@Larswa perfect, thanks for the confirmation :+1:

**Comment by dw5304** [comment]
confirmed working.
