### ISSUE TITLE
GNS3 VM imported in HyperV not visible in GUI (AMD) Insider preview 19645

### ISSUE THREAD

**Issue by dw5304** [GNS3/gns3-server#1778]
In windows insider preview 19645 nested virtualization has been added for AMD Ryzen cpu's
creating a vm with 
 New-VM -Name "GNS3 VM" -Generation 1 -MemoryStartupBytes 1GB -SwitchName "Default Switch" -Version 9.3

will allow you to start GNS3 with the exposedvirtualizationextensions set to true.
however the gns3 gui does not show the vm in the drop down to be selected.
I have looked over the other bugs and I can confirm that my user name is in Hyper-v admins group and have been able to run the python script to prove the vm is listed.
PS C:\Users\owner\Downloads\gns3-server-master> C:\Python38\python.exe .\test.py
GNS3 VM

one of the other python script that was asked to be ran came back saying only supported on intel hardware. As this used to be true but no longer is...
PS C:\Users\owner\Downloads\gns3-server-master> C:\Python38\python.exe .\test.py
Traceback (most recent call last):
  File ".\test.py", line 23, in <module>
    raise Exception("An Intel processor is required by Hyper-V to support nested virtualization")
Exception: An Intel processor is required by Hyper-V to support nested virtualization

be aware going to localhost returns nothing

**Comment by cioby23** [comment]
This issue has been reported already here https://github.com/GNS3/gns3-server/issues/1777 and it's fixed.
The fix should be available in the next release 2.2.10.

**Comment by dw5304** [comment]
so just to confirm if I was to download the source things should work?
if so will do some testing here shortly.

**Comment by grossmj** [comment]
> so just to confirm if I was to download the source things should work?

You can try our latest nightly build, this should work (I haven't tested since I don't have an AMD processor).

https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2020-06-13/2.2/GNS3-2.2.2020-06-13-all-in-one.exe/download
