### ISSUE TITLE
2.2.9 : web-ui : console : don't show the last line

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#1779]
Hi

With the web-ui, the console don't show the last line. I don't see what i'm typing into the web console. The last line is hidden.

I have this issue with gns3server installed from master source, or with "pip3 install" on Debian Buster (Backport). 
If i use "GNS3 VM", i have no problem.

**Comment by grossmj** [comment]
Do you have a screenshot please?

Also, please post future issues related to the web-ui on https://github.com/GNS3/gns3-web-ui/issues

Thanks :)

**Comment by Raizo62** [comment]
Hard to capture what i can't see ;-)

![Firefox_Screenshot_2020-06-14T09-51-14 762Z](https://user-images.githubusercontent.com/7449584/84590286-8967c380-ae35-11ea-865b-0d71a5150e11.png)

here, i don't see the prompt after my command.

**Comment by grossmj** [comment]
Thanks, to summarize:

* It works when using the web-ui in the GNS3 VM with version 2.2.9.
* It *does not* work when using the web-ui bundled on gns3-server master branch.

**Comment by Raizo62** [comment]
Yes, it is that.
On my own VM, i have installed from github the master branch gns3-server, and with "pip3 install gns3server"

**Comment by Raizo62** [comment]
I suppose that the problem is in a package of Debian Buster (Backport).
if you can't reproduce it, tell me. Perhaps I do something wrong.

**Comment by Raizo62** [comment]
- In the precedent posts, the gns3server was on a VM(LiveRaizo) started in VirtualBox.
- I have started gns3server on the same OS on a true PC. The problem disappeared. But, i have already do this test on an other PC/browser and i have see the bug.

**Comment by grossmj** [comment]
Please try with the next release (v2.2.13) and let us know if you still have the problem.

**Comment by Raizo62** [comment]
No, sorry. I still to see the problem.
Strangely, only if gns3server is on VirtualBox.
If the gns3server is on real computer, the display of web console is ok
(If the info is useful, I use Firefox)

**Comment by grossmj** [comment]
I have installed the latest GNS3 VM in VirtualBox on Windows. I tested with both Firefox and Chrome and I could see the last line in the web console. I don't know what is wrong, maybe some display issue? Have you tried with the GNS3 VM in VirtualBox on a different computer/screen?

**Comment by Raizo62** [comment]
I have release a new version of LiveRaizo ( https://sourceforge.net/projects/live-raizo/files/ )

If you start LiveRaizo in VirtualBox and you can't reproduce, perhaps the problem comes from my screen/....

**Comment by grossmj** [comment]
I have tested with LiveRaizo and haven't seen any issues.

**Comment by grossmj** [comment]
I will close this for now since it is apparently not an issue with the web-ui. Please comment back if you experience issues on other screens.

**Comment by Raizo62** [comment]
Could you test with this config of VirtualBox ? 
[Fail - Test Live Raizo.ova.txt](https://github.com/GNS3/gns3-server/files/5366774/Fail.-.Test.Live.Raizo.ova.txt) (.ova renamed to .txt)

gns3server is started with the command : fast-gns3-server
The name of the project is "untitled"

As soon as i open the web console, i have a grey bar
