### ISSUE TITLE
Qemu Mips for gns3

### ISSUE THREAD

**Issue by dw5304** [GNS3/gns3-server#1780]
getting an error "Hardware acceleration can only be used with the following qemu executables:qemu-system-x86_64, qemu-system-i386, qemu-kvm" looking to find out how to disable it from attempting to run with hardware acceleration.

qemu binary qemu-system-mipsel

**Comment by b-ehlers** [comment]
Sad enough you don't tell us, what GNS3 version you are using and on what OS you want to run this QEMU VM, so we have to speculate. I assume, that you are using GNS3 v2.2 and want to run the VM on a linux server, maybe in the GNS3VM. If that's not true, you should ignore the following.

GNS3 uses the configuration file `gns3_server.conf` for the server, it's located in $HOME/.config/GNS3/2.2. In the Qemu section parameter `enable_hardware_acceleration` specifies, if you want to use hardware acceleration, parameter `require_hardware_acceleration` specifies, if hardware acceration must be used. Both parameters default to true.

`require_hardware_acceleration` causes issues in your case, as it requires hardware acceleration for all QEMU processor types. As ARM is not the native processor type, it can't run accelerated and therefore GNS3 refuses to run it.

I suggest to change the Qemu section in gns3_server.conf to the following:
```
[Qemu]
; !! Remember to add the gns3 user to the KVM group, otherwise you will not have read / write permssions to /dev/kvm !!
enable_hardware_acceleration = True
require_hardware_acceleration = False
```

That way it will use hardware acceleration when possible, but doesn't require it. That allows you to run foreign processor types like ARM.

After changing gns3_server.conf you must restart the gns3server.
