### ISSUE TITLE
GNS3 2.2.9 ethernet hub does not transfer any packet

### ISSUE THREAD

**Issue by kbanzai** [GNS3/gns3-server#1783]
GNS3 2.2.9 ethernet hub does not transfer any packet.
The figure shows my network topology.
I put a built-in ethernet hub between two switches.
<img width="184" alt="Screen Shot 2020-06-18 at 15 12 13" src="https://user-images.githubusercontent.com/3622662/85002516-ef36b100-b18f-11ea-8089-16b9bbd5cab4.png">

I tried to ping from SW1 to SW2, but it failed.
Both switches are Cisco IOSvL2 15.2.1.
Here is the result of `show int gig 0/0` after running `ping 192.168.0.2 repeat 10000000 size 1000 timeout 0` on SW1 (192.168.0.2 is SW2's IP address).
Both interfaces do not receive any packet.

> ####SW1####
SW1#show int gig 0/0
GigabitEthernet0/0 is up, line protocol is up (connected)
Hardware is iGbE, address is 0c6c.bf2b.1900 (bia 0c6c.bf2b.1900)
MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
reliability 255/255, txload 1/255, rxload 1/255
Encapsulation ARPA, loopback not set
Keepalive set (10 sec)
Auto Duplex, Auto Speed, link type is auto, media type is RJ45
output flow-control is unsupported, input flow-control is unsupported
ARP type: ARPA, ARP Timeout 04:00:00
Last input never, output 00:00:01, output hang never
Last clearing of "show interface" counters never
Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0
Queueing strategy: fifo
Output queue: 0/0 (size/max)
5 minute input rate 0 bits/sec, 0 packets/sec
5 minute output rate 0 bits/sec, 0 packets/sec
0 packets input, 0 bytes, 0 no buffer
Received 0 broadcasts (0 multicasts)
0 runts, 0 giants, 0 throttles
0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
0 watchdog, 0 multicast, 0 pause input
836 packets output, 66212 bytes, 0 underruns
0 output errors, 0 collisions, 2 interface resets
0 unknown protocol drops
0 babbles, 0 late collision, 0 deferred
0 lost carrier, 0 no carrier, 0 pause output
0 output buffer failures, 0 output buffers swapped out

>####SW2####
SW2#show int gig 0/0
GigabitEthernet0/0 is up, line protocol is up (connected)
Hardware is iGbE, address is 0c6c.bf70.8e00 (bia 0c6c.bf70.8e00)
MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
reliability 255/255, txload 1/255, rxload 1/255
Encapsulation ARPA, loopback not set
Keepalive set (10 sec)
Auto Duplex, Auto Speed, link type is auto, media type is RJ45
output flow-control is unsupported, input flow-control is unsupported
ARP type: ARPA, ARP Timeout 04:00:00
Last input never, output 00:00:01, output hang never
Last clearing of "show interface" counters never
Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0
Queueing strategy: fifo
Output queue: 0/0 (size/max)
5 minute input rate 0 bits/sec, 0 packets/sec
5 minute output rate 0 bits/sec, 0 packets/sec
0 packets input, 0 bytes, 0 no buffer
Received 0 broadcasts (0 multicasts)
0 runts, 0 giants, 0 throttles
0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
0 watchdog, 0 multicast, 0 pause input
727 packets output, 57200 bytes, 0 underruns
0 output errors, 0 collisions, 2 interface resets
0 unknown protocol drops
0 babbles, 0 late collision, 0 deferred
0 lost carrier, 0 no carrier, 0 pause output
0 output buffer failures, 0 output buffers swapped out

The same problem also occurs with routers(Cisco IOSv 15.7(3)M3) and Nexus switches(Cisco NX-OSv7.3.0).
After I replaced the ethernet hub to a Cisco IOSvL2 switch, I could ping from SW1 to SW2.
Thus, the ethernet hub causes this problem.

 

My environment is as follows:
GNS3 VM version: 2.2.9
Host OS: Mac OS 10.15.5
Host machine: iMac 2019
Processor: 3.6 GHz 8-Core Intel Core i9(I allocated 8 logical core to GNS3 VM)
Memory: 40 GB 2667 MHz DDR4(I allocated 16GB to GNS3 VM)

These are running-config of two switches.
[SW1.txt](https://github.com/GNS3/gns3-server/files/4797668/SW1.txt)
[SW2.txt](https://github.com/GNS3/gns3-server/files/4797669/SW2.txt)

**Comment by grossmj** [comment]
This is strange, it works if I use 2 VPCS nodes:

![Screenshot from 2020-06-26 22-15-19](https://user-images.githubusercontent.com/4752614/85858332-99e74900-b7fa-11ea-9e1c-6a03a9dc21bd.png)

Is the Hub on the same host as the switches?
