### ISSUE TITLE
gns3 web server impersonation bug

### ISSUE THREAD

**Issue by joemhiggins** [GNS3/gns3-server#1786]
I have a specific post by Julien Duponchelle a few years ago which stated if there is a problem with GNS3, then we want to hear about it and where the problem is posted is not important.

In any event, the impersonation bug which has existed for a few years now on the gns3.com web page appears to be caused by another user looking at "my" profile. I then take on the identity of that user in my posts.

In the ensuing link, I have 4 - 7 posts that were attributed to Nik Elz.
https://gns3.com/community/discussion/fix-to-gns3-vm-greyed-out-gns3-v

The posts by "Nik Elz" were taken down. My username joe higgins that is associated with my email address was wiped out. I had to create a new username joseph higgins.

I hated learning HTML 10 years ago. It is not fun. I do not know what language web pages are built in nowadays. I know I would not find it fun to fix the bug. But the bug, needs to be fixed as a high priority.

Close out this ticket and just move it to whatever person is responsible for fixing the webpage.

**Comment by joemhiggins** [comment]
Chris Bradt reported the same thing happened to him in the same post. But my gut feeling is still that it is another GNS3 user looking at my profile that causes the impersonation to be created.

**Comment by b-ehlers** [comment]
The GNS3 community website is totally insecure. About every month I'm logged in as a foreign person. As soon as I notice that, I'm logging out. As a consequence I'm deleting my account (including my posts) regulary to minimize the impact if anyone takes over my account.

This has already been reported in the community website long ago, nothing has changed.

**Comment by joemhiggins** [comment]
I am well aware that this has been reported numerous times. But 2 years is too much.

But at least your post does solve one mystery. I thought you removed your posts so you would not be following a thread that can last 3 to 5 years.

I understand why no one would want to fix it. Coding web pages was horrible when I learned it year ago.

**Comment by joemhiggins** [comment]
Well, in light of my ensuing post in which "nothing should be deleted" and "new features are allowed". Then I suggest, off the to of my head, that they move to adding a 2 feature authentication option - like other websites have - to  a gns3 poster's profile. In uploading a post, then a poster would have to verify the 2 feature authentication if they have that option enabled.

If the GNS3 developers can figure out how to add a new feature to a .gns3 file, then the web developers can learn from them.

**Comment by grossmj** [comment]
I know the GNS3 community website isn't without bugs. That being said, there is a totally new community website which should be released in 2-3 weeks.

**Comment by stevenyuen** [comment]
@joemhiggins Thanks for posting this issue.

For some context, we had seen this issue quite some time ago. We contacted the affected users privately while patching the issue, and they mentioned they were no longer experiencing the issue. Thanks for bringing this to our attention.

@grossmj is correct - a completely rewritten version of the community will be deployed in the next 3 weeks - this includes the authentication process. Two-factor authentication is also high on our priority list, and we expect to roll it out shortly after rolling out the new community. It will be available to all community users who opt to use it.

As this is a security matter, we will be deleting this issue shortly.
