### ISSUE TITLE
GNS3 VM loses connectivity to GUI

### ISSUE THREAD

**Issue by fmlacerda** [GNS3/gns3-server#1795]
Hi! 

I am working on a simulation with several routers, switches and 3 virtual machines that are part of the topology, connected to the switches using VMnet host virtual ports. All is working well, except that after 20 to 30 minutes the GNS3 VM loses connectivity and I have to close everything and restart GNS3, VMs and so on. All devices running in GNS3 VM.

All this is running in a nested environment (not sure if that may somehow influence this issue).

Any clue how to make it more stable?

VMware ESXi 5.5
     Windows 10 (32GB Ram, 16vCores)
         GNS3 GUI
         VMware Workstation: 15.5.5
              GNS3_VM: 2.2.10
              Win10(pc used in the topology)
              Win2019(server used in the topology)
              CUCM 10.5(server used in the topology)

**Comment by fmlacerda** [comment]
I just want to provide an update on this. After adjusting the windows clients Power Settings (display/sleep) to "never" these virtual machines and its connectivity to GNS3 are more stable.

**Comment by grossmj** [comment]
@fmlacerda thanks for the info. We are aware they are issues with GNS3 when PC go to sleep mode, we need to investigate this more.
