### ISSUE TITLE
Issue Duplicating Large Projects

### ISSUE THREAD

**Issue by morton-a** [GNS3/gns3-server#1797]
Hello all,

I have noticed that when I duplicate large projects they fail due to the first Virtual Hard Disk - **/dev/sda1** - being used as a stage for the transfer before finally being moved to the relevant path on **/dev/sdb1**: the issue appears to be that **/dev/sda1** is used for the duplication process whilst by default it only has limited space.  Increasing the size of /dev/sda1 appears to be an inefficient process, as it is not used for project or image storage.

I have not tried to resolve the issue by making /dev/sda1 larger, but I assume this would be a temporary fix.  That being said /dev/sda1 may be intentionally used for the duplication process.  Below is a excerpt of storage on /dev/sda1 as the transfer is in progress (at 51% capacity) and then after it has failed returning back to 16% capacity:
![GNS3_StorageDuringTransfer](https://user-images.githubusercontent.com/68322920/87521319-2065ac80-c67c-11ea-9fb2-7eb809bdf1fc.png)

**Excerpt of Error Log (from GNS3 Console):**
![GNS3_ConsoleErrorMessage](https://user-images.githubusercontent.com/68322920/87521318-1fcd1600-c67c-11ea-9fa6-ff5a8c2b2bb5.png)
Apologies if I have not adhered to some forum etiquette, as this is my first post on Github.

**Comment by gpn005** [comment]
I second this issue. Same scenario.

**Comment by grossmj** [comment]
Looks like this is the same issue as listed in https://github.com/GNS3/gns3-gui/issues/2909

**Comment by grossmj** [comment]
Thanks, fixed in https://github.com/GNS3/gns3-server/commit/37c7202aa00c429e1e546ea703a841099c70c658

This will work with version 2.2.12.
