### ISSUE TITLE
Cannot upgrade GNS3 VM (ESXi) 2.2.7 to 2.2.11

### ISSUE THREAD

**Issue by jasonh701** [GNS3/gns3-server#1803]
When trying to upgrade my GNS3 VM from 2.2.7 to 2.2.11 I get an error at the end of the upgrade process stating the aiofiles, jsonschema, psutil, and py-cpuinfo are incompatible. 

I've attached a screenshot of the error messages along with a log file of the upgrade procedure. 

Please let me know if you need anything else from me. Thx!

[GNS3 VM error.pdf](https://github.com/GNS3/gns3-server/files/4991606/GNS3.VM.error.pdf)

[GNS3 Upgrade.txt](https://github.com/GNS3/gns3-server/files/4991607/GNS3.Upgrade.txt)

**Comment by grossmj** [comment]
I downloaded the GNS3 VM for version 2.2.7 and upgraded to 2.2.11, I didn't see any issue. Start a shell and try the following command: `sudo python3 -m pip install --upgrade --ignore-installed six`, then proceed to upgrade again using the menu.

**Comment by jasonh701** [comment]
Hey Jeremy,

Thanks for getting back to me. I just tried the upgrade again with the recommended command but got to the same error message at the end of the upgrade procedure.

gns3@gns3vm:~$ sudo python3 -m pip install --upgrade --ignore-installed six
Downloading/unpacking six
  Downloading six-1.15.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six
Cleaning up...

[cid:image003.png@01D66649.F4536480]

Please let me know if there’s any information you’d like me to gather or anything else you suggest I try.

Thanks again!
Jason

**Comment by grossmj** [comment]
This is very strange. Please use this command `sudo python3 -m pip uninstall gns3-server` and try to upgrade again.

**Comment by jasonh701** [comment]
Hey Jeremy,

I’m a little hesitant to run that command for fear I’ll lose all of my projects. Is it safe to assume that my projects will remain intact if I run that command?

Thanks!
Jason

**Comment by grossmj** [comment]
> I’m a little hesitant to run that command for fear I’ll lose all of my projects. Is it safe to assume that my projects will remain intact if I run that command?

Uninstalling GNS3 will not remove any projects however it could be prudent to created a snapshot of the VM just in case.

**Comment by jasonh701** [comment]
Hey Jeremy,

I uninstalled the GNS3 server using the command you provided then went through the upgrade procedure again and saw the same error. I’ve attached the upgrade log for your review.

I also have a 2.2.7 GNS3 server VM installed on a different machine on VMWare Workstation Pro. When I attempted to upgrade that VM, it gave me the same error. Not sure if there’s something specific to my environment but I’m thinking I’m just going to delete the VM and reinstall with a whole new OVA. Thoughts?

Thanks,
Jason

**Comment by grossmj** [comment]
> Not sure if there’s something specific to my environment but I’m thinking I’m just going to delete the VM and reinstall with a whole new OVA. Thoughts?

I don't really understand what is wrong, if you can I would suggest to reinstall a new OVA for the latest GNS3 release. You can then transfer your projects from the old GNS3 VM to the new one.
