### ISSUE TITLE
Getting error as "fail update installation: DLL load failed: The specified module could not be found" in gns3 ver 2.2.11

### ISSUE THREAD

**Issue by arocky05** [GNS3/gns3-server#1807]
I have downloaded latest gns3 ver 2.2.11 from gns3 official site & have installed it. 

But while launching it, getting error as "fail update installation: DLL load failed: The specified module could not be found" in gns3 ver 2.2.11

My base system config is :

OS: Windows 10 pro 64 bit

RAM: 8 GB

Processor: Intel i5

**Comment by grossmj** [comment]
@arocky05 have you install Python on your computer?
