### ISSUE TITLE
Remove Python 3.3 support?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#181]
I think the 1.4 is a big gap in features. We already introduce a major dependencies changes with QT5. It can be a good time for remove Python 3.3 support.

Reason for that: the support of asyncio is not reliable in 3.3 and we see random failure in tests.

Also from our crash report we have almost no users with Python 3.3. And soon we will need to support Python 3.5.

Debian is shipped with python 3.4. Ubuntu is shipped with Python 3.4 and has never distribute the 3.3.

The only potential issue is Fedora 20 shipped  with Python 3.3:
https://apps.fedoraproject.org/packages/python3
But fedora 21 and fedora 22 use Python 3.4

**Comment by grossmj** [comment]
I see nothing against that. Let's keep monitoring if we have users using Python 3.3 and take a decision before releasing our first alpha/beta for 1.4.

**Comment by noplay** [comment]
aiothttp as also a discussion about that:
https://github.com/KeepSafe/aiohttp/issues/352
