### ISSUE TITLE
Proxmox, GNS3 and Opterons 62xx: qemu-system-x86-64 error failed to set msr 0xe1 to 0x0

### ISSUE THREAD

**Issue by tallos673** [GNS3/gns3-server#1812]
OS: Proxmox 6.1-2  or 6.2-1, qemu version 5+, Ubuntu 20.04 guest (native GNS3) or GNS3-VM.ova in qcow2.
CPU - host/amd64
GNS3 - all versions - from 2.1 to 2.12-beta-dev
Arista vEOS - all versions - from 4.15 to 4.24 and different Aboot-serial-iso
Nested Virtualization is enabled following documentaion
from here https://pve.proxmox.com/wiki/Nested_Virtualization
I have KGPE-D16 and 2x6276 Opteron's
I can't run well any Arista veOS images on EVE-NG or GNS3.
On EVE-NG it stuck at loading initrd/kernel
On GNS3 it wont start.

```
qemu-system-x86_64 error failed to set msr 0xe1 to 0x0
and this
kvm_buf_set_msrs
```
```
root@eve-ng:/opt/unetlab/addons/qemu# ls
veos-4.15.0F  veos-4.20.1F  veos-4.21.1.1F  veos-4.24.1.1F

root@pve:~# kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

root@pve:~# pveversion 
pve-manager/6.2-10/a20769ed (running kernel: 5.4.44-2-pve)
```

Any ideas how to fix? or AMD really bad choice for virtual network lab?

Also found this
https://bugs.launchpad.net/qemu/+bug/1661386

Screen from guest

![photo_2020-08-16_22-48-22](https://user-images.githubusercontent.com/69766865/90342685-e4bf5900-e012-11ea-821d-ca8b31f9c399.jpg)

**Comment by cristian-ciobanu** [comment]
Check this issue for a workaround https://github.com/GNS3/gns3-server/issues/1774#issuecomment-639396742 this is not a GNS3 issue

**Comment by tallos673** [comment]
@cristian-ciobanu it doesn't help :( 

```
root@pve:~# cat /sys/module/kvm/parameters/ignore_msrs
Y
```

**Comment by tallos673** [comment]
@cristian-ciobanu screenshot
![photo_2020-08-16_22-50-07](https://user-images.githubusercontent.com/69766865/90342771-5e574700-e013-11ea-8ebb-86027cbb6d48.jpg)

**Comment by tallos673** [comment]
> Check this issue for a workaround [#1774 (comment)](https://github.com/GNS3/gns3-server/issues/1774#issuecomment-639396742) this is not a GNS3 issue

This is QEMU bug i think.

https://bugs.launchpad.net/qemu/+bug/1661386
https://git.qemu.org/?p=qemu.git;a=commitdiff;h=0b368a10c71af96f6cf

**Comment by tallos673** [comment]
```
QEMU also could fail if KVM exposes less fixed counters then 3. It could
happen if host system run inside another hypervisor, which is tweaking
PMU-related CPUID. To prevent possible fail, number of fixed counters now is
obtained in the same way as number of GP counters.
```

**Comment by nosy** [comment]
Another Arista Bug linked on Intel Platform
https://github.com/GNS3/gns3-web-ui/issues/967
