### ISSUE TITLE
Could not find guest IP address for GNS3 VM [HyperV + v2.2.12]

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-server#1813]
After migrating to 2.2.12 when I try to add GNS3 vm the following error appears: Could not find guest IP address for GNS3 VM, vm in hyperv also upgraded to v2.2.12

**Comment by piotrpekala7** [comment]
@grossmj do you need more information?

**Comment by grossmj** [comment]
Correct, looks like there is an issue since Hyper-V cannot see the IP address.

![Selection_003](https://user-images.githubusercontent.com/4752614/92101560-7228e880-ee1c-11ea-9e10-f0f3e5c69386.png)

**Comment by piotrpekala7** [comment]
@grossmj can I help you with that? I need it working in some tasks in web UI

**Comment by grossmj** [comment]
To fix this, start a shell in the VM and type the following commands:

```
sudo apt update
sudo apt install linux-virtual linux-cloud-tools-virtual linux-tools-virtual
sudo update-initramfs -u
sudo reboot
```

**Comment by grossmj** [comment]
Once working you should see something like this:

![Screenshot from 2020-09-03 22-55-41](https://user-images.githubusercontent.com/4752614/92120800-aad6bb00-ee38-11ea-8556-9483c406a837.png)

**Comment by piotrpekala7** [comment]
thanks, it works!

**Comment by gmuretto** [comment]
Hi Grossmj, I tried those commands in the VM shell. I restarted it be I still cannot see the IP address in the Hyper-V networking session. I am running 2.2.14 GNS3 server version. Any help? Thanks

**Comment by Infor-Master** [comment]
same situation as gmuretto under 2.2.14 as well...

**Comment by grossmj** [comment]
Have you tried this command? `sudo apt-get install "linux-cloud-tools-$(uname -r)"`

**Comment by Infor-Master** [comment]
grossmj, the command worked. got an ip now. on 2.2.14

configured GNS3 to acess the vm from Hyper-V directly (was using remote as a temporary solution)

however, gns3 still says "cannot connect to compute 'GNS3 VM (GNS3 VM)' with request POST /projects

i do notice the vm starting and shuting down as GNS3 orders it
