### ISSUE TITLE
Cisco IOU BGP Peering Issue

### ISSUE THREAD

**Issue by jzpian** [GNS3/gns3-server#1814]
Deployed a new lab in GNS3 2.2.12 and running into odd issues with Cisco IOU images. I'm using the i86bi-linux-l3-adventerprisek9-ms.155-2.T image and when the router boots up, the BGP neighbors have an uptime of 
584942417y18w. 

See output below:

ROUTER1#sh ip bgp all sum                            
For address family: VPNv4 Unicast
BGP router identifier 1.1.1.1, local AS number 4567
BGP table version is 9, main routing table version 9

Neighbor        V           AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
**1.1.1.2         4        1234       6       9        9    0    0 58494241        0**

ROUTER1#sh ip bgp vpnv4 vrf VRF1  neighbor 1.1.1.2
BGP neighbor is 1.1.1.2,  vrf VRF1,  remote AS 1234, external link
  BGP version 4, remote router ID 32.119.176.222
  BGP state = Established, up for 584942417y18w
  **Last read 584942417y18w, last write 584942417y18w, hold time is 180, keepalive interval is 60 seconds**

Eventually, the neighbor relationship fails. 

This issue does not occur in GNS 2.1.x branch.

This may be a similar issue related to the following report bug:

https://github.com/GNS3/gns3-gui/issues/2884

Below are the lab environment specs:

 - OS: Windows 10 (Client)
 - GNS3 version 2.2.12
 - GNS3 VM 2.2.12 (VMWARE ESXi) 

I have tried to reboot the GNS3 VM multiple times and the issue appears every time.

**Comment by grossmj** [comment]
@jzpian please can you post a screenshot of your topology + the startup-config for all nodes?

Thanks :+1:

**Comment by grossmj** [comment]
Something worth trying would be to test with the GNS3 VM but not running it on VMware ESXi (with VMware workstation for instance). I have noticed some other users reported similar issues and they all share on common thing, they run their projects on ESXi. Maybe this is a wrong assumption but if it does then it would help a lot to isolate the problem. Thanks.

**Comment by jzpian** [comment]
@grossmj  I went ahead and installed GNS 2.12.13 on a fresh Ubuntu 18 VM on the same ESXi server. Both the new and existing topologies that I was previously running on 2.1 did not experience the issue that I reported. Could the issue be related with Ubuntu 20 that is bundled in the GNS3 VM?

**Comment by grossmj** [comment]
@jzpian I don't think so and we still use 18.04 LTS in the VM.

**Comment by grossmj** [comment]
@jzpian I am closing this now. Please re-open/comment if you face that problem again.
