### ISSUE TITLE
It is possible to turn off KVM support in the gns3_server.conf | Cannot Disable KVM

### ISSUE THREAD

**Issue by alex22sok** [GNS3/gns3-server#1815]
Running GNS3VM on AWS EC2 Ubuntu without KVM support and would like to disable KVM. Connecting from Mac GNS3 GUI, using OpenVPN. 

Constantly getting the same error, when trying to start the Qemu Node.
`
=> error while starting appdconsole-1: KVM acceleration cannot be used (/dev/kvm doesn't exist). It is possible to turn off KVM support in the gns3_server.conf by adding enable_kvm = false to the [Qemu] section.`

![image](https://user-images.githubusercontent.com/30569586/92278906-77f2fc80-eef6-11ea-8502-e0bd15a7cfc2.png)

• Have tried to use old syntax of disabling, which is 

```
[Qemu]
enable_kvm = false
```

• Also, have tried to use a new version of the same, per [Qemu Mips for gns3](https://github.com/GNS3/gns3-server/issues/1780)
```
-bash:$ cat .config/GNS3/2.2/gns3_server.conf
[Server]
path = /Applications/GNS3.app/Contents/MacOS/gns3server
ubridge_path = /Applications/GNS3.app/Contents/MacOS/ubridge
host = 10.8.0.1
port = 3080
images_path = /Users/user1/GNS3/images
projects_path = /Users/user1/GNS3/projects
appliances_path = /Users/user1/GNS3/appliances
additional_images_paths =
symbols_path = /Users/user1/GNS3/symbols
configs_path = /Users/user1/GNS3/configs
report_errors = True
auto_start = False
allow_console_from_anywhere = False
auth = False
user = admin
password = 69W0ezDThRK2hiXKPwaxBiau3c5qcaZkNicjHJcy1PHzK1qeC4f3hvMbELJ6eRfq
protocol = http
console_start_port_range = 5000
console_end_port_range = 10000
udp_start_port_range = 10000
udp_end_port_range = 20000
[Qemu]
enable_hardware_acceleration = False
require_hardware_acceleration = False

```
• Didn't help. Not possible to ignore that message, unfortunately...

Client Env:
• OS: MacOS 10.15.5
• gns3gui : 2.2.13, running on MacOS

GNS3VM Env, remote:
• OS: Ubuntu 18.04.5 LTS
• gns3server : 2.2.13

**Comment by grossmj** [comment]
@alex22sok 

It looks like you have done this configuration on macOS (client side). You need to do it on the server itself, in the GNS3 VM.

**Comment by alex22sok** [comment]
@grossmj 
Yes, you are correct. After creating `gns3_server.conf` with the

**Comment by AlfredoSobrinho** [comment]
> @grossmj Sim você está correto. Depois de criar `gns3_server.conf`, no próprio servidor GNS3VM, com a entrada abaixo anexada, o problema é resolvido:
> 
> ```
> [Qemu]
> enable_hardware_acceleration = False
> require_hardware_acceleration = False
> ```

funcionou, obrigado

**Comment by samratcis** [comment]
> @grossmj Yes, you are correct. After creating `gns3_server.conf`, on the GNS3VM Server itself, with the below input appended, the issue is resolved:
> 
> ```
> [Qemu]
> enable_hardware_acceleration = False
> require_hardware_acceleration = False
> ```

Thanks, it worked for me on MAC M1 chips with Gns3 VMfusion

**Comment by rudolphos** [comment]
Where exactly does gns3_server.conf should be created in Windows ?
It's very difficult to find help regarding these rare errors.

**Comment by grossmj** [comment]
The `gns3_server.conf` is located in `%APPDATA%\GNS3\2.2` by default.

**Comment by rudolphos** [comment]
I'm on Windows and the file extension is `ini ` file not `conf` for some reason, despite GNS3 referring to `conf`.
![image](https://github.com/GNS3/gns3-server/assets/4366810/890e9cd3-8adf-4c8f-8384-9f6cb093227b)

Added to `gns3_server.ini`:
```
[Qemu]
enable_kvm = false
enable_hardware_acceleration = False
require_hardware_acceleration = False
```
Didn't work..
Later added same lines in GNS3 VM to file gns3_server.conf in GNS3 and home directory and didn't work...

**Comment by Joao-Pedro-Bautista** [comment]
> @grossmj Yes, you are correct. After creating `gns3_server.conf`, on the GNS3VM Server itself, with the below input appended, the issue is resolved:
> 
> ```
> [Qemu]
> enable_hardware_acceleration = False
> require_hardware_acceleration = False
> ```

man i fucking love you thanks

**Comment by acaldir** [comment]
.config/GNS3/2.2/gns3_server.conf  = here is the file that you want to add the following commands if you can not see the file. open the home page and press CTRL + H or you can use the terminal "vi" command before use this command "sudo apt install vim" to edit the file 

[Qemu]
enable_hardware_acceleration = False
require_hardware_acceleration = False

Thank you guys 

it works on me

**Comment by fsbops** [comment]
> .config/GNS3/2.2/gns3_server.conf = here is the file that you want to add the following commands if you can not see the file. open the home page and press CTRL + H or you can use the terminal "vi" command before use this command "sudo apt install vim" to edit the file
> 
> [Qemu] enable_hardware_acceleration = False require_hardware_acceleration = False
> 
> Thank you guys
> 
> it works on me

Thank you.

**Comment by Christoglou** [comment]
THERE IS A SOLUTION AND IS VERY EASY . I HAD THIS PROBLEM AND I SOLVE IT , GO TO CONTROL PANEL PROGRAMS AND FUTURES --- TURN WINDOWS FUTURES ON OF AND UNCLICK VIRTUAL MACHINE PLATFORM AND WINDOWS HYPERVISOR PLATFORM THEN RESTART THE COMPUTER AFTER THAT DISABLE MEMORY INTEGRITY IN WINDOWS SECURITY IN CORE SECTION AND THEN GO TO REGISTRY TAKE THIS PATH Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard AND THEN ADD NEW PUT THIS NAME EnableVirtualizationBasedSecurity AND SET THE VaLUE TO 0 RESTART THE VIRTUAL BOX OR VM WORKSTATION AND THE CLIENT GNS3 RESTART THE PC AND YOU ARE ALL SET

**Comment by Christoglou** [comment]
@AlexCichon  see the comment  i wrote above you

**Comment by AllenSlaghuis** [comment]
hi guys. i have the issue and even when i put the lyns in the conf it still does not fix it. i hav a unconpatable cpu so need to bypass the kvm
