### ISSUE TITLE
Can't start Tiny Core Linux 11.1

### ISSUE THREAD

**Issue by vasiliyaltunin** [GNS3/gns3-server#1817]
When i try to start 11.1 i have this error:

QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-i386 -name TinyCoreLinux11.1-1 -m 96M -smp cpus=1 -enable-kvm -boot order=c -drive file=/opt/gns3/projects/6660c3bc-6a09-4d1f-a0d4-7d2ab84393f4/project-files/qemu/be7bb006-7d7a-4918-9579-c3474dcae26a/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0 -uuid be7bb006-7d7a-4918-9579-c3474dcae26a -vnc 0.0.0.0:0 -monitor tcp:127.0.0.1:40893,server,nowait -net none -device e1000,mac=0c:93:f4:e2:6a:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:20021,localaddr=127.0.0.1:20020 -vga std -device usb tablet

Execution log:
qemu-system-i386: -drive file=/opt/gns3/projects/6660c3bc-6a09-4d1f-a0d4-7d2ab84393f4/project-files/qemu/be7bb006-7d7a-4918-9579-c3474dcae26a/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0: Could not open backing file: Could not open backing file: Could not open '/home/gns3/GNS3/images/QEMU/empty30G.qcow2': No such file or directory

I checked and there no folder /home/gns3/GNS3/images/QEMU/ on server

I use GNS3 2.2.11

I think there error in template.

**Comment by vasiliyaltunin** [comment]
I was able to run this appliance

I created folder on server

/home/gns3/GNS3/images/QEMU/ 

then download this file 

https://sourceforge.net/projects/gns-3/files/Empty%20Qemu%20disk/empty30G.qcow2/download

and put it into this folder

After that i go to template settings of Tiny Core lInux and change:

RAM to 256Mb couse it crush on start complains memory with 96Mb, may be you can set lower value, but i just fine with this value.

Then i go to Advanced tab and change Options to 

-vga virtio

i delete usb part, couse qemu complains about it and i dont which driver i need to use.

So now it runs, but mouse act weird when i move mouse inner cursor did not follow and some time move different direction

I think .gnsa file needed to be updated.

**Comment by vasiliyaltunin** [comment]
I try to change Options to

-nographic -usbdevice tablet -vga std -nodefaults

But ,mouse problem still there...

**Comment by vasiliyaltunin** [comment]
Also i change Qemu binary to

/usr/bin/quemu-system-x86_64(v3.1.0)

Because with x86 i have error:

Error while sending command 'bridge create QEMU-be7bb006-7d7a-4918-9579-c3474dcae26a-0': bridge 'QEMU-be7bb006-7d7a-4918-9579-c3474dcae26a-0' already exist: uBridge version 0.9.18 running with libpcap version 1.8.1
Hypervisor TCP control server started (IP 0.0.0.0 port 36849).
UDP tunnel connecting from local port 20021 to IPv4 address 127.0.0.1 on port 20020
UDP tunnel connecting from local port 20022 to IPv4 address 127.0.0.1 on port 20023
Destination NIO listener thread for QEMU-be7bb006-7d7a-4918-9579-c3474dcae26a-0 has started
Source NIO listener thread for QEMU-be7bb006-7d7a-4918-9579-c3474dcae26a-0 has started
QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-i386 -name TinyCoreLinux11.1-1 -m 96M -smp cpus=1 -enable-kvm -boot order=c -drive file=/opt/gns3/projects/6660c3bc-6a09-4d1f-a0d4-7d2ab84393f4/project-files/qemu/be7bb006-7d7a-4918-9579-c3474dcae26a/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0 -uuid be7bb006-7d7a-4918-9579-c3474dcae26a -vnc 0.0.0.0:0 -monitor tcp:127.0.0.1:40753,server,nowait -net none -device e1000,mac=0c:93:f4:e2:6a:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:20021,localaddr=127.0.0.1:20020 -vga std -device usb-tablet

Execution log:
qemu-system-i386: -device usb-tablet: No 'usb-bus' bus found for device 'usb-tablet'

QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-i386 -name TinyCoreLinux11.1-1 -m 256M -smp cpus=1 -enable-kvm -boot order=c -drive file=/opt/gns3/projects/6660c3bc-6a09-4d1f-a0d4-7d2ab84393f4/project-files/qemu/be7bb006-7d7a-4918-9579-c3474dcae26a/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0 -uuid be7bb006-7d7a-4918-9579-c3474dcae26a -vnc 0.0.0.0:0 -monitor tcp:127.0.0.1:44203,server,nowait -net none -device e1000e,mac=0c:93:f4:e2:6a:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:20021,localaddr=127.0.0.1:20020 -nographic -usbdevice tablet -vga std -nodefaults

Execution log:
qemu-system-i386: -usbdevice tablet: '-usbdevice' is deprecated, please use '-device usb-...' instead
qemu-system-i386: -device e1000e,mac=0c:93:f4:e2:6a:00,netdev=gns3-0: failed to find romfile "efi-e1000e.rom"

This node must be started before a console can be opened

**Comment by b-ehlers** [comment]
Tiny Core Linux image v11.1 is just a waste of time.
* The RAM size is 96MB is way too low, 256MB is a more reasonable size
* The image depends on another image: `/home/gns3/GNS3/images/QEMU/empty30G.qcow2`, that is not installed. You may download it from <https://sourceforge.net/projects/gns-3/files/Empty%20Qemu%20disk/> and install it into that directory, then the appliance should start
* it uses a very basic Xwindows server, that is not able to synchronize your mouse pointer. Working with that is no fun.

You may try v6.4~2, but that has also some issues
* The software is quite old
* While it boots with 96MB RAM, that is also quite low. I recommend to increase it to 256MB
* The virtio disk interface doesn't work, at least not with QEMU 3.1. It boots only to the command line. Use disk interface ide or scsi.
* The appliance file says, that the image is named linux-tinycore-6.4-2.img and the upload creates that file. But the template wants image linux-tinycore-linux-6.4-2.img (with two linux in it's name). After correcting that it finally works.

**Comment by b-ehlers** [comment]
The tinycore has several issues, so I can't recommend using it.

Version 11.1, see messages from @vasiliyaltunin:

* The image `linux-tinycore-11.1.qcow2` depends on `/home/gns3/GNS3/images/QEMU/empty30G.qcow2`. This has to be installed manually, otherwise the node will not start.
  ```
  # qemu-img info linux-tinycore-11.1.qcow2
  image: linux-tinycore-11.1.qcow2
  file format: qcow2
  virtual size: 30G (32212254720 bytes)
  disk size: 32M
  cluster_size: 65536
  backing file: /home/gns3/GNS3/images/QEMU/empty30G.qcow2
  Format specific information:
      compat: 1.1
      lazy refcounts: false
      refcount bits: 16
      corrupt: false
  ```
* The memory size of 96MB is too low, it needs at least 160MB to start. I suggest to set the memory size to 256MB.
* It uses the very basic Xvesa software. That doesn't synchronize the mouse pointer position, what makes it very hard using it. I suggest to use the Xorg software instead.

Version 6.4~2 has also some issues:
* It downloads image `linux-tinycore-linux-6.4-2.img`, but that got upload as `linux-tinycore-6.4-2.img`. The template still wants to use the original name `linux-tinycore-linux-6.4-2.img`. Therefore creating a node will fail, in the template the image has to be changed to `linux-tinycore-6.4-2.img`.
* With the virtio disk interface the Linux OS boots only in CLI mode, using ide or sata works
* While it boots with 96MB of RAM, almost all is in use. I recommend to increase the ram size.

**Comment by Benaattia** [comment]
1- Change Path Of Backing File: /home/gns3/GNS3/images/QEMU/empty30G.qcow2

sudo qemu-img rebase -f qcow2 -u -b /opt/gns3/images/QEMU/empty30G.qcow2 linux-tinycore-11.1.qcow2

More information: [https://blog.programster.org/qemu-img-cheatsheet](https://github.com/GNS3/gns3-registry/issues/url)

2- Upgrade template memory to 256 MB
