### ISSUE TITLE
gns3 vmdk reboots immediately when starting imported nodes.

### ISSUE THREAD

**Issue by rjt** [GNS3/gns3-server#1819]
![XenOrchestra-GNS3-20200914-192102](https://user-images.githubusercontent.com/360343/93151370-5d244300-f6c1-11ea-9ee8-a90dbb40f8ee.png)

Using the generic ethernet switch and virtual PCs,  there is no problem starting these nodes and they will run for weeks without issue. 
But when starting an Arista node or vyos or we suspect about any non-native node, the gns3-server VM will reboot immediately.  

We import the vmware ESXi gns3server vmdk into [XCP-ng 8.1](https://xcp-ng.org/) using [XenOrchestra](https://xen-orchestra.com/xoa) or "[XCP-ng Center](https://github.com/xcp-ng/xenadmin/releases/tag/v20.04.00.32)". 
We install the tools 
We enable passthru.  
Change nic from RealTek to intel e1000.
"Virtualization: xen"
"xen-hvm"
"KVM support available: True"
Test an all native node project runs fine.
While watching the imported gns3server console, attempt to fire up an imported node.
Watch the gns3server reboot.
Nothing under /var/logs/
dmesg --ctime does not have anything.  

Is there a way to increase verbosity?
There must be a way to sync / flush everything to disks every 1/2 second or so in the hopes we can see something under /var/log/ ?
Is there an option to stop the machine at a bugcheck instead of having it automatically reboot?

GNS3 community posting [XCP-NG/xen Server not possible?](https://www.gns3.com/community/featured/xcp-ng-xen-server-not-possible) initiated March 20, 2019.  
XCP-ng.org forum posting ["GNS3-VM on xcp-ng"](https://xcp-ng.org/forum/topic/3474/gns3-vm-on-xcp-ng)
[April 8th entry on gns3-vm project](https://github.com/GNS3/gns3-vm/issues/145#issue-596433106)
[XO Hub Template: what do you want next?](https://xcp-ng.org/forum/topic/2023/xo-hub-template-what-do-you-want-next)
[XCP-ng: A turnkey open source virtualization platform](https://github.com/xcp-ng/xcp)

GNS3 versions tested 2.9, 2.10, 2.11, 2.12, 2.14

**Comment by grossmj** [comment]
Strange, looks similar to https://github.com/GNS3/gns3-gui/issues/2815

**Comment by grossmj** [comment]
We don't officially support running the GNS3 VM on Xen but I am curious why it crashes.

**Comment by rjt** [comment]
I will try 2.2.16 asap and get back.
