### ISSUE TITLE
The New Hyper-V based GNS3 VM WMI issue

### ISSUE THREAD

**Issue by IbrmHaymour** [GNS3/gns3-server#1822]
In the recent versions of GNS3 a Hyper-V based GNS3 VM was introduced, this was good news for me where I can take with me a full network simulator hosted on my windows 10 laptop to demo locations without the need for either VMWare workstation or Virtual Box installed to host the GNS3 VM, a very good step ahead, GNS3 Team. 
So, I’ve given it a try and installed that VM, which works perfectly and well serving my needs; until I’ve decided to go and add another virtual network adapter to it, i.e. an external one to be used by cloud object to connect the VM to my network. Now GNS3 server on my laptop, starts the VM and failing to connect to it, oh what had happened I’ve only added a virual adapter!!!!?????
Digging into the problem and reviewing GNS3 server log it appeared that hyperv_gns3_vm.py is fetching the second external IP address assigned by DHCP, despite the fact that the external VM adapter was added after the internal one, noting that I’ve previously configured GNS3 VM in a separate vlan with different subnet (internal one), which is the recommended practice by the way.
So why this is happening? 
**The Issue:**
Digging further I’ve found that if you set the action when closing GNS3 in Preferences-GNS3 VM to keep GNS3 VM running and restart GNS3 the problem disappeared and every this is running perfectly!!!??
Thus, I’ve decided to dig further, get the source of GNS3 server from GitHub and look into the code, yes, I consider myself an expert in C, C++ and C# but I know Python very well as I’ve done some projects for ISP’s to integrate their switches with ERP.
Now I am have a well-structured Python code with requirements clear and existed as text files “thanks GNS3 Team for excellent work”, loaded the GNS3 server code to my development env “Visual Studio 2019”, a quick review of the code revealed that Windows Management Instrumentation (WMI) is used to communicate with Hyper-V, thus say OK I’ve done a good work in that domain previously I need to get the code debugged, so I’ve copied  hyperv_gns3_vm.py, base_gns3_vm.py and gns3_vm_error.py to a separate project to ease the debugging and created GNS3Fixes.py to call the start function from HyperVGNS3VM class, meanwhile setting break points for debugging.
The results shown that: if start function is called when GNS3 VM is running the IP address assigned to ip_address property of the HyperVGNS3VM class instance is correct, but if start function is called when GNS3 VM is if not running (shutdown) the IP address is assigned wrong value (the external adapter IP), so I’ve decided to add a 3rd adapter and execute the same procedure, the same thing occur the IP address of the 2nd adapter (External) is reflected, the I’ve removed the External adapter, added it as 3rd adapter and  retry the operation again, here the IP reflected correspond also to second adapter in rank i.e. not the external one so something fishy going around here let me see the  _set_state function.
**The Couse of the issue:**
Upon reviewing _set_state function which is executed asynchronously it appeared that this function creates a WMI Job to start GNS3 VM utilizing WMI RequestStateChange method and wait for that job to finish then return directly if no exception is thrown, from my knowledge WMI registry which use a special and enhanced JET engine is populated with virtual network adapters through Linux Integration Tools (LIS) which needs time to do that (approximately 0.3 s or more depending on the Hyper-V host hardware and configuration involved), thus upon continue of start function execution it will grape the 2nd adapter in most cases as the first adapter i.e. start fetching virtual adapters before full population to WMI.
The proof of this concept is so obvious when _set_state function was delayed for some time after the WMI job executed successfully where everything works as expected.
**The Solution:**
The solution of this problem is simple an easy to be implemented in code where another function is created in HyperVGNS3VM class which delays the execution until the virtual adapters are fully populated to WMI registry and is supposed to be called after the successful execution of _set_state function

_Attached is hyperv_gns3_vm.py with the issue fixed_

[hyperv_gns3_vm.zip](https://github.com/GNS3/gns3-server/files/5264506/hyperv_gns3_vm.zip)

**Comment by IbrmHaymour** [comment]
Good thanks;

**Comment by grossmj** [comment]
Thanks a lot for this contribution! :+1:
