### ISSUE TITLE
Could not retrieve symbol

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#1824]
Hi

With GNS3 branch 2.2 and a new config, the log of gns3server shows a lot of error messages : 
```
2020-10-01 17:44:21 WARNING symbols.py:135 Could not retrieve symbol '%3A/symbols/affinity/square/blue/xml.svg'
2020-10-01 17:44:21 WARNING symbols.py:135 Could not retrieve symbol '%3A/symbols/affinity/square/gray/xml.svg'
2020-10-01 17:44:21 WARNING symbols.py:135 Could not retrieve symbol '%3A/symbols/affinity/square/red/xml.svg'
```

and on GNS3-gui, the Affinity symbols are like computer.svg

**Comment by grossmj** [comment]
Are you talking about 2.2 or 3.0 branch? 3.0 is still very much "work in progress"...

**Comment by Raizo62** [comment]
i am talking about 2.2

**Comment by Raizo62** [comment]
Perhaps a bug in GNS3 or from an update in python ?
Or of me but i don't see what i did.
Could you reproduce ?

**Comment by grossmj** [comment]
How have you installed GNS3?

**Comment by Raizo62** [comment]
from source, and i use my "old" script to build and install it.

**Comment by Raizo62** [comment]
The file xml.svg exists here :

```
file /usr/local/lib/python3.7/dist-packages/gns3server/symbols/affinity/square/red/xml.svg
/usr/local/lib/python3.7/dist-packages/gns3server/symbols/affinity/square/red/xml.svg: SVG Scalable Vector Graphics image
```

**Comment by grossmj** [comment]
Do you have issues only with the xml.svg symbol?

**Comment by Raizo62** [comment]
no, it is an example. I have a problem with all symbols except classic

**Comment by Raizo62** [comment]
I send you an iso to see the bug

**Comment by grossmj** [comment]
Last commit should fix the issue.

**Comment by Raizo62** [comment]
It works :-) Thanks :-)
