### ISSUE TITLE
Possibly wrong defaults for images_path, configs_path, appliances_path

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-server#1829]
I found the following lines where the default values for images_path, configs_path and appliances_path default to `~/GNS3/projects` if unset:

```
./gns3server/controller/__init__.py:        images_path = os.path.expanduser(server_config.get("images_path", "~/GNS3/projects"))
./gns3server/controller/__init__.py:        images_path = os.path.expanduser(server_config.get("configs_path", "~/GNS3/projects"))
./gns3server/controller/appliance_manager.py:        appliances_path = os.path.expanduser(server_config.get("appliances_path", "~/GNS3/projects"))
```

In the [first case](https://github.com/GNS3/gns3-server/blob/master/gns3server/controller/__init__.py#L269), I would expect the default value to be `~/GNS3/images`

In the [second case](https://github.com/GNS3/gns3-server/blob/master/gns3server/controller/__init__.py#L279), which is in function `configs_path()`, I was expecting `~/GNS3/configs`.  It would also be clearer to change the variable name from `images_path` to `configs_path`.

In the [third case](https://github.com/GNS3/gns3-server/blob/master/gns3server/controller/appliance_manager.py#L73), I was expecting the default to be `~/GNS3/appliances`.

Am I right?

I note that in other places, `images_path` defaults to what I would expect:

```
./gns3server/utils/images.py:    general_images_directory = os.path.expanduser(server_config.get("images_path", "~/GNS3/images"))
./gns3server/utils/images.py:    img_dir = os.path.expanduser(server_config.get("images_path", "~/GNS3/images"))
./gns3server/utils/images.py:    img_dir = os.path.expanduser(server_config.get("images_path", "~/GNS3/images"))
./conf/gns3_server.conf:images_path = /home/gns3/GNS3/images
```

Appliances and configs don't appear to have defaults anywhere else, but examples show that they would normally be in their own directories rather than in the projects directory:

```
./scripts/remote-install.sh:appliances_path = /opt/gns3/appliances
./conf/gns3_server.conf:appliances_path = /home/gns3/GNS3/appliances
```

```
./scripts/remote-install.sh:configs_path = /opt/gns3/configs
```

**Comment by candlerb** [comment]
Ah, this explains why my projects directory has these text files mixed in with it!

```
$ ls ~/GNS3/projects/
3ec99e2d-8e87-4e49-8ed4-3a63f0c39ac3  dd17577a-a39a-4d2b-b765-f76a736018cc  iou_l2_base_startup-config.txt
538fd89a-e9f8-4f1c-bb2c-4988d7e9b29d  ea9f662b-a2d7-41f6-abd8-3c6ec6bda608  iou_l3_base_startup-config.txt
82dd474b-121e-4dec-b898-f48e58b4b335  ff58952d-4de0-485a-9ea2-7486d03045ff  vpcs_base_config.txt
9c556c5e-a029-4eb6-907c-8913ae6dc28f  ios_base_startup-config.txt
acd55262-4ceb-495b-9245-87177e799f7c  ios_etherswitch_startup-config.txt
```

**Comment by grossmj** [comment]
Fixed, thanks :+1:
