### ISSUE TITLE
[API]Created device but not visible in the project

### ISSUE THREAD

**Issue by roman-so** [GNS3/gns3-server#1832]
Device ethernet_switch created with API but not visible in any GUI(desktop and web) but GET request to the node created return the successful information
![ticket_24 10 2020](https://user-images.githubusercontent.com/59204786/97087800-fcc3e200-162c-11eb-9d98-2fd8b91e70b8.jpg)

```
`xxx@dev:~/virt$ curl -i -X GET 'http://x.x.x.x:80/v2/compute/projects/a2e67072-e111-4eba-8514-82dd170805ba/ethernet_switch/nodes/1f77c72d-8204-4b01-9310-4c9fc4f9824d'
HTTP/1.1 200 OK
Connection: close
X-Route: /v2/compute/projects/{project_id}/ethernet_switch/nodes/{node_id}
Server: Python/3.6 GNS3/2.2.14
Content-Type: application/json
Content-Length: 1326
Date: Sat, 24 Oct 2020 19:08:40 GMT

{
    "console": 5016,
    "console_type": "telnet",
    "name": "S2",
    "node_id": "1f77c72d-8204-4b01-9310-4c9fc4f9824d",
    "ports_mapping": [
        {
            "name": "Ethernet0",
            "port_number": 0,
            "type": "access",
            "vlan": 1
        },
        {
            "name": "Ethernet1",
            "port_number": 1,
            "type": "access",
            "vlan": 1
        },
        {
            "name": "Ethernet2",
            "port_number": 2,
            "type": "access",
            "vlan": 1
        },
        {
            "name": "Ethernet3",
            "port_number": 3,
            "type": "access",
            "vlan": 1
        },
        {
            "name": "Ethernet4",
            "port_number": 4,
            "type": "access",
            "vlan": 1
        },
        {
            "name": "Ethernet5",
            "port_number": 5,
            "type": "access",
            "vlan": 1
        },
        {
            "name": "Ethernet6",
            "port_number": 6,
            "type": "access",
            "vlan": 1
        },
        {
            "name": "Ethernet7",
            "port_number": 7,
            "type": "access",
            "vlan": 1
        }
    ],
    "project_id": "a2e67072-e111-4eba-8514-82dd170805ba",
    "status": "started"
}`
```

**Comment by b-ehlers** [comment]
From <https://gns3-server.readthedocs.io/en/stable/endpoints.html#compute-endpoints>:
> **Warning:** These endpoints should be considered low level and private. They should only be used by the controller or for debugging purposes.

Take this warning serious, do **N O T** use  the compute API calls (starting with`/v2/compute/`). Use only the controller API, see <https://gns3-server.readthedocs.io/en/stable/endpoints.html#controller-endpoints>.

Creating new nodes is done with [/v2/projects/{project_id}/nodes](https://gns3-server.readthedocs.io/en/stable/api/v2/controller/node/projectsprojectidnodes.html), but be aware, that this is one of the most complex tasks within the GNS3 API. I suggest to start with something easier.

Some tips and tricks: <https://www.b-ehlers.de/blog/posts/2019-08-12-gns3-api-tips-tricks/>.
