### ISSUE TITLE
User isolation

### ISSUE THREAD

**Issue by k4kfh** [GNS3/gns3-server#1835]
I'm doing some academic work that would really benefit from user isolation (on a very large scale). I know that there is gns3-proxy, and that is an option, but I'd rather just add the feature to GNS3 if it's a manageable amount of work.

I'm not very familiar with this codebase. Could some experienced folks give your opinion on this idea? Is it going to be a 10 year process that requires fundamental changes? Or fairly do-able? I am trying to decide whether it will be more work to implement an elaborate system around gns3-proxy, or simply add the feature to GNS3 directly.

**Comment by grossmj** [comment]
We are already working on this on branch 3.0, version 3.0 will have a new API, new architecture etc. and will support user management with a RBAC model, authentication, HTTPS etc. The main goal is to allow GNS3 to be used in a classroom environment.

We expect to have a fairly strong base early next year. Please do not hesitate to share your ideas and/or would like to contribute.

**Comment by k4kfh** [comment]
Awesome! Thanks for the information. I'd love to help out as much as I can.

Is there a particular issue I should start trying to tackle, or just go straight for the RBAC? Also, do I need anything out of the ordinary set up for my dev environment?

**Comment by grossmj** [comment]
We already have started work on the RBAC part, it will be added to the 3.0 server branch in time. Once we have done that you will be able to try and give us your ideas and contribute. In the meantime you may want to have a look at FastAPI, this is what we are using to run GNS3 starting with version 3.0: https://fastapi.tiangolo.com/

Regarding the authentication, the API will support OAuth2. Once we have that in place, it shouldn't too hard to add support additional authentication methods.

**Comment by grossmj** [comment]
RBAC support has been added.
