### ISSUE TITLE
Issue shutting down server under Python 3.9

### ISSUE THREAD

**Issue by lynxx131** [GNS3/gns3-server#1841]
I'm using Fedora 33 running their RPM build of GNS3 server (2.2.15) which they appear to build against Python 3.9.

When I try to stop the server I get the below error:

```
ERROR base_events.py:1738 Task exception was never retrieved
future: <Task finished name='Task-26' coro=<WebServer.shutdown_server() done, defined at /usr/lib/python3.9/site-packages/gns3server/web/web_server.py:100> exception=AttributeError("type object '_asyncio.Task' has no attribute 'all_tasks'")>
Traceback (most recent call last):
   File "/usr/lib/python3.9/site-packages/gns3server/web/web_server.py", line 141, in shutdown_server
     for task in asyncio.Task.all_tasks():
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
```

It appears in Python 3.9 `asyncio.Task.all_tasks()` became just `asyncio.all_tasks()` and after manually changing this the server appears to shut down as normal.

I have my own RPM build of 2.2.16 and the issue is reproducible in that build also.

**Comment by grossmj** [comment]
Thanks, we will fix this soon.

**Comment by tirkarthi** [comment]
I have created https://github.com/GNS3/gns3-server/pull/1842 as a potential fix

**Comment by grossmj** [comment]
Fixed thanks to @tirkarthi
