### ISSUE TITLE
permission problem when update to gns2.2.17

### ISSUE THREAD

**Issue by nhannht** [GNS3/gns3-server#1848]
https://github.com/sameersbn/docker-bind/issues/108#issue-760371540

I don't know where is better to put this issues
I use this repo above to host BIND9-dns server in my gns topology. Everything work very smooth util I update gns to newer version. And it just broken. I guest the problem is laying in the new update

![image](https://user-images.githubusercontent.com/69144096/101641146-fc0fcf80-3a63-11eb-8ba2-93f9b1ac9531.png)
Note that if I run this images normally outside gns with docker-cli like `docker run --rm -it sameersbn/docker-bind` it still working with no problem. 

- Not just this images, another popular images BIND in alpine have an issues that dont recognize /etc/bind/named.conf.

**Comment by grossmj** [comment]
How did you update GNS3?
