### ISSUE TITLE
GNS3 2.2.17: link to cloud device stops functioning, says "bridge (long hash) doesn't exist"

### ISSUE THREAD

**Issue by QiweiWen** [GNS3/gns3-server#1849]
As the title describes, it's been observed that with GNS3 server 2.2.17, network access to a cloud device intermittently breaks, requiring the link to be deleted and inserted again to restore functionality.

However, sometimes, deleting the links fails with this message:
```
2020-12-10 13:05:57 ERROR link:337 Error while deleting link: Error while sending command 'bridge delete 5352902e-f27c-4101-ab99-6c6c82d94c8c-5': bridge '5352902e-f27c-4101-ab99-6c6c82d94c8c-5' doesn't exist: uBridge version 0.9.18 running with libpcap version 1.9.1 (with TPACKET_V3)
Hypervisor TCP control server started (IP 0.0.0.0 port 33087).
UDP tunnel connecting from local port 20008 to IPv4 address 127.0.0.1 on port 20009
Source NIO listener thread for 5352902e-f27c-4101-ab99-6c6c82d94c8c-6 has started
Destination NIO listener thread for 5352902e-f27c-4101-ab99-6c6c82d94c8c-6 has started
```

Restarting the GUI to connect to the same server, the link disappears on the GUI. Attempting to insert that link again results in some message along the line of "Link already exists".

Restarting the GNS3 server is required to recover from this state.

**Comment by QiweiWen** [comment]
This behaviour is seen with Ubuntu 20.04. Everything is installed from the GNS3 apt repository.

This seems to be reliably reproducible like so:
1. connect a few virtual devices to a real switch through the cloud device
2. bring down all of the connected ports **at the real switch's end**, bring them back up
3. observe that networking through all the cloud ports stop working.
4. try deleting and re-inserting some links, and observe that networking comes back in those links.
5. observe that deleting and re-inserting some links fail with the above message.

**Comment by grossmj** [comment]
I think uBridge (the process is charge of interconnecting devices) crashes because a frame larger than 1500 bytes is received (see https://github.com/GNS3/gns3-gui/issues/1867 for details why). Make sure that the real switch doesn't send frames by lowering the MTU to 1470 bytes for instance. Please let us know if this helps.

Note that we have plans to replace the network back-end in the future which will solve this issue.

**Comment by QiweiWen** [comment]
Hi Jeremy,

I'm pretty sure the issue is not jumble frames but, precisely, the cloud switch powering down its ports. Is the issue not reproducible in your environment?

**Comment by grossmj** [comment]
No one else has reported a similar problem. Closing for now.
