### ISSUE TITLE
Mod_security - application firewall of apache not working

### ISSUE THREAD

**Issue by nhannht** [GNS3/gns3-server#1853]
- Can edit config file
- If add wrong rules in config file and use `apachectl restart` will be warning error
- But no rule work, HTTP request/response still flow as normal.
- Nothing was logged in modsec_audit.log and modsec_debug.log 
- I forget to told that I use apache in docker in gns
- Mod security work as expect in normal environment, like docker with docker in host machine

**Comment by grossmj** [comment]
Not sure I understand what is the problem. Please can you provide more details of what the issue is and how it is related to GNS3? Thanks.

**Comment by nhannht** [comment]
Wait me please, don't close this issue. I was working in another problem.
I will answer soon

**Comment by nhannht** [comment]
I will close it for temporary. With me to keep this issues open too long without answer is considered very impolite.
