### ISSUE TITLE
No data returned from localhost:49244 after sending command 'hypervisor version ', uBridge process running: True

### ISSUE THREAD

**Issue by neerajyadav794** [GNS3/gns3-server#1854]
Hi
Opening GNS3'project (2.2.17, Win10 x64) after one month i see suddenly this stupid error:

No data returned from localhost:49244 after sending command 'hypervisor version ', uBridge process running: True

What is that ? I'm not able to use PC and not even connect by cables.
Sir Please help to resolve this problem.

Note : I Recive multiple error , please check the attachment & please help to resolve 

> [this.]([url](url))
![Capture](https://user-images.githubusercontent.com/75973563/103120068-2389ad80-469c-11eb-9710-cad89df24f56.PNG)
![Capture1](https://user-images.githubusercontent.com/75973563/103120070-25537100-469c-11eb-860a-eaf5a6e02f1e.PNG)

**Comment by grossmj** [comment]
Do you still have the messages after rebooting your PC?

**Comment by neerajyadav794** [comment]
Yes problem is same even after reboot

**Comment by mgarland12** [comment]
have the same problem after a few weeks.Cant open projects or run vpcs Reinstalled and rebooted twice.Same thing!

**Comment by neerajyadav794** [comment]
Still same problem.

**Comment by mgarland12** [comment]
Yes.Just tried to open a project again and received thissame error again but has different port number.This worked Monday of this week and ? No data returned from localhost:51644 after sending command 'hypervisor version
', uBridge process running: True
