### ISSUE TITLE
Option to disable WebUI

### ISSUE THREAD

**Issue by brentstewart** [GNS3/gns3-server#1857]
From a security perspective, if webui is unused it would be nice to be able to turn it off.  For the VM build, it would be nice to have an option in the menu.

**Comment by b-ehlers** [comment]
From a security perspective the WebUI doesn't open a new attack vector.

It's just a website, that runs javascript on your local browser, which issues some GNS3 API requests to let you interact with the GNS3 server. It doesn't offer more than a GNS3 GUI client using a remote connection to your server or using direct API requests.

You can even install the WebUI files on to a normal web server and use that to access any GNS3 server in the world, where you can access the API, even when the WebUI is diabled on the server. Well almost, you have to disable CORS to get this working.

The critical point is the API interface. If an attacker can access that, he has full control of the GNS3 server.

**Comment by grossmj** [comment]
We working on adding users management in version 3.0 where you will have to authenticate with the server in order to use web-ui and/or the API.
