### ISSUE TITLE
error while starting R1: Could not send Dynamips command 'vm set_ghost_status "R1" 2' to localhost:52661: [Errno 32] Broken pipe, process running: False

### ISSUE THREAD

**Issue by atanwar21** [GNS3/gns3-server#1858]
Unable to start router c7200, 
error while starting R1: Could not send Dynamips command 'vm set_ghost_status "R1" 2' to localhost:52661: [Errno 32] Broken pipe, process running: False

Linux : Ubuntu 20.10

gns3 versions:
dynamips/groovy,now 0.2.21-1~groovy1 amd64 [installed]
gns3-gui/groovy,now 2.2.17~groovy1 amd64 [installed]
gns3-iou/groovy,now 0.0.2~groovy8 amd64 [installed]
gns3-server/groovy,now 2.2.17~groovy1 amd64 [installed]

Please support

**Comment by grossmj** [comment]
What c7200 image have you used?
