### ISSUE TITLE
Packets are not properly forwarded between nodes

### ISSUE THREAD

**Issue by imadhsissou** [GNS3/gns3-server#1859]
**GNS3 version and operating system:**

- Client : GNS3 version 2.2.17 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
- Server : 

![alt text](https://media.mcdn.co/embedded/600a16913379d30e151e7a8c?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9tZWRpYS5tY2RuLmNvL2VtYmVkZGVkLzYwMGExNjkxMzM3OWQzMGUxNTFlN2E4YyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MzMxNjg4NzM4ODB9fX1dfQ__&Key-Pair-Id=APKAJDKBVMGXNCXPKSSQ&Signature=L1RqUrUkKK~OsazgDeQYs~CoeAqitxZXar3WCFSxkAp4OP8KkKvNp~lGdQMqwcOeDcrg8OZMZq2HaLV1q1ia2EnzaSBzfeehx9lD7CdVkzOMo41N0nqaueJKeqbUb6s-TQ0Vj2G42pq14VkAsoDqE8GeKlux3oUaRcX1rd97K9frtoTJFQjHpXcOs0oiDWbKttArbq1yaVmWwCQG-hCTudTNMev4hvMsqWymTkVGcM5-rid6gonTUM~FAZfzCnFMMyU-8l5UM8HLjlcjLfJVCh51azN9MySk9uWgyrmxvxAH1cm7-9XHXHZIRf2FAzzoXWIcfu-55D8c7Ak7xuWClw__)

**Describe the bug:**

I can't ping between two directly linked nodes, tried XRv, IOSv and CSRv1000, all failed !

However, I noticed after troublshooting that the interface that is **attached second** when creating the link in GNS3 GUI doesn't send or recieve any traffic, I launched a ping from both sides, and did a packet capture on the link and I was able to see ARP Requests sourced from the interface A (attached first) but not from interface B (attached second), deleted the link and created it again, but this time starting from interface B, and I was able to see ARP Request from interface B but not from A.

I replicated the same scenario using the Web UI and noticed the same behaviour.

**Images**

Cisco CSR1000v 17.03.01a
Cisco IOS XRv 6.3.1
Cisco IOSv 15.9(3)M2

**To Reproduce**

Create a simple topology with simple subnet to test a ping.

I can provide more details if needed.

**_UPDATE:_**

I'm using a remote server.

I recreated the same topology with the same images directly from the built-in Web UI in GNS3 VM Server and everything worked fine.

**Comment by imadhsissou** [comment]
I created this issue on` gns3-server` since I'm not really sure if this is a GUI/UI problem or it is from the server side.

**Comment by cristian-ciobanu** [comment]
Try to use diferrent interface drivers like e1000, virtio, vmxnet for your devices and test again. I think I encountered such a issue a while ago. 
Once I changed for example virtio to e1000 ping started to work fine, If I remember correctly.

**Comment by imadhsissou** [comment]
When I change the driver and reboot the device interfaces don't show up at all, I tried many combinations with no luck !

**Comment by sachinites** [comment]
what is the resolve of this issue, i am seeing this issue exactly on GNS3 - 2.2.39.
