### ISSUE TITLE
After upgrade /projects empty

### ISSUE THREAD

**Issue by StefanB123** [GNS3/gns3-server#1862]
Okay so I started the shell because I wanted to check whether all docker processes were up and running.
Then when I tried to exit I got the request that I should execute

`Please run 'sudo gns3restore' in case the menu is no longer showing`

I assumed that this is the command to restore the menu again.
So I did that and then it started to upgrade the system (I assume) or roll it back possible.
After the restart I tried to start anything on a GNS3 project and it literally refused with the following error:

`Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request POST /projects
error while deleting OpenvSwitchmanagement-1: DELETE /projects/12c3dc99-9ccc-49b2-8295-91b9c1f988b0/docker/nodes/212eca1a-fd22-4875-8f9f-14481e6f57e3 not found`

This happened with everything I tried (VPCs, router, etc.).
So I went again into the shell and found that the directory `/projects` doesn't exist.

So if the command `sudo gns3restore` actually rolls the system back it should be more clear and if not then it shouldn't delete the `/projects` directory.

I was able to fix it by rebooting the system once more which somehow fixed it but still this shouldn't happen.

OS: Linux arch 5.10.8-arch1-1 #1 SMP PREEMPT Sun, 17 Jan 2021 22:07:13 +0000 x86_64 GNU/Linux
GNS3 server version: 2.2.17
VM version: 0.10.28
ubuntu version: bionic
qemu verison: 3.1.0

Steps to reproduce:
> start a project and have a few nodes
> start shell in the gns3vm
> execute `sudo gns3restore`
> after restart try to start, delete or change the nodes

**Comment by grossmj** [comment]
I didn't get any issue with the latest VM. However, this VM is based on Ubuntu 20.04 LTS.

**Comment by grossmj** [comment]
Let me know if you still have the problem with the latest GNS3 VM. Thanks.
