### ISSUE TITLE
gns3 error "Dynamips identifier 1 is already used by another router"

### ISSUE THREAD

**Issue by Schroeterchris123** [GNS3/gns3-server#1863]
I'm not sure if this is the right area to post this but I'm having some trouble starting up one of my projects.

The problem is whenever I import my portable project inside GNS3 I receive a message saying "Dynamips identifier 1 is already used by another router"

The current version I'm running is GNS 2.2.17 but this same exact issue was noticed on 2.2.16 before I upgraded.

Does anyone happen to know how to fix this error? 

I've seen that this issue was brought up before on this site but it was on a much older version of gns3.

Any help is greatly appreciated!

![1](https://user-images.githubusercontent.com/78328136/106403714-03b57a00-63fe-11eb-80a5-ed3dc3fe7589.JPG)

![2](https://user-images.githubusercontent.com/78328136/106403730-0e700f00-63fe-11eb-8a02-2169331e706c.JPG)

**Comment by grossmj** [comment]
Please can you post the content of the .gns3 file stored inside your project? Thanks.

**Comment by Schroeterchris123** [comment]
> Please can you post the content of the .gns3 file stored inside your project? Thanks.

Thanks for replying grossmj I've attached the .gns3 file to this message. 
Please let me know if there is anything else you'll need me to do or try.

[CCNP Project issue.zip](https://github.com/GNS3/gns3-server/files/5989534/CCNP.Project.issue.zip)

**Comment by grossmj** [comment]
I don't really know what happened. I fixed your project, please give it a try:

[CCNP.Project.issue.zip](https://github.com/GNS3/gns3-server/files/5993805/CCNP.Project.issue.zip)

**Comment by Schroeterchris123** [comment]
> I don't really know what happened. I fixed your project, please give it a try:
> 
> [CCNP.Project.issue.zip](https://github.com/GNS3/gns3-server/files/5993805/CCNP.Project.issue.zip)

Wow thanks alot man!!

What ever you did fixed it. Did you have to modify something ?

**Comment by grossmj** [comment]
No worries, I made sure the dynamips_id is unique.
