### ISSUE TITLE
gns3 won't work on MacBook Pro after upgrade to Big Sur.

### ISSUE THREAD

**Issue by hanumatbalbeera** [GNS3/gns3-server#1864]
Hi GNS Community/developers,

Greetings....

I'd like to draw your attention on petty issue however that has become a nightmare for me. I've got MacBook Pro 15 with an i9 and 16Gigs of RAM 2019. I was using gns3 with the same system even since I bought it. how ever the day I upgraded to Mac OS Big Sur, the nightmare started. at first the GNS vm would show up being greyed out
<img width="1680" alt="Screenshot 2021-01-06 at 2 55 40 PM" src="https://user-images.githubusercontent.com/77899496/107874108-433f9400-6edd-11eb-8022-e2f6c4498431.png">

 but now I don't even get anything ( screen shots attached)
<img width="1680" alt="Screenshot 2021-02-14 at 3 59 14 PM" src="https://user-images.githubusercontent.com/77899496/107874200-df699b00-6edd-11eb-9787-f8a0fcc7afc3.png">
<img width="1679" alt="Screenshot 2021-02-14 at 3 59 32 PM" src="https://user-images.githubusercontent.com/77899496/107874204-e5f81280-6edd-11eb-8930-9aca4148f0db.png">
<img width="1680" alt="Screenshot 2021-02-14 at 4 00 01 PM" src="https://user-images.githubusercontent.com/77899496/107874205-e8f30300-6edd-11eb-98dc-a66de0efea76.png">

and to add some icing on the cake the gns VM get to grub
<img width="1130" alt="Screenshot 2021-02-14 at 4 02 38 PM" src="https://user-images.githubusercontent.com/77899496/107874258-37080680-6ede-11eb-802e-e3a9eb8956c9.png">

can someone in the world plz help me before I either throw off the MacBook Pro from 4 story or throw myself off :-)

I even tried to restore the MacBook Pro to its factory setting and tried the older configuration I used to use and which worked for me...even then I got the same results and I'm wondering why????? so finally I upgraded back to Big Sur when I saw gns3 2.2.17 and saw some people claiming that it works on MacBook Pro Big Sur....but that didn't work either....

I've tried virtual box as well but the gns3 vm gets the same results and gets me to grub screen. and that's it..

urgent help is needed so I can start to practice and study for my ccnp R&S and CCIE R&S and get a job so I could support myself and my 7 rescued pets...the lockdown due to covid has really brought down a lot of people worldwide including me...so please consider this an urgent and alarming situation for me and help.  
 

Thanks and Regards,
Rishi

**Comment by grossmj** [comment]
Looks like you have something blocking the connection from the client to the server. Can you try to turn off the macOS firewall to see?

![Screenshot from 2021-02-15 13-53-32](https://user-images.githubusercontent.com/4752614/107905199-f2dc3b00-6f9d-11eb-9b21-a8cbc328b13d.png)

**Comment by jnatschev** [comment]
one thing that helped me with macos big sur, gns3-gui 2.2.17, gns3-server 2.2.17, vmware fusion 12.1.0/gns3 vm 2.2.27 was to quit gns3-gui (which includes gns3-server), mv $HOME/.config/GNS3 $HOME/.config/GNS3-backup, then start gns3-gui again. this forced the recreation configuration files in a new $HOME/.config/GNS3 directory.

all the best...

**Comment by hanumatbalbeera** [comment]
Hi Jeremy,

Greetings my friend.....

I've been tracking the Mac firewall too eversincme the issue came up but my Mac firewall is on turned-off state and I keep it that way only. since I guess I can deal with the threats and have successfully dealt with them in the past. even right now its turned off, I'm attaching an image.
<img width="821" alt="Screenshot 2021-02-16 at 2 54 12 PM" src="https://user-images.githubusercontent.com/77899496/108043738-76ae2a00-7067-11eb-8c80-c6542ac9e633.png">

my dear brother I've never felt so helpless even in my life when it comes to dating with IT issues coz one way or the other I have solved and got things working..but for this...bro I've done what not....but this doesn't seems to move an inch.

I want to thank you for considering my issue and taking the time out to help me out....wanna thank you from the bottom of my heart..hope we'll get to the core of this issue and resolve it soon.

thanks and best regards,
rishi

**Comment by hanumatbalbeera** [comment]
> one thing that helped me with macos big sur, gns3-gui 2.2.17, gns3-server 2.2.17, vmware fusion 12.1.0/gns3 vm 2.2.27 was to quit gns3-gui (which includes gns3-server), mv $HOME/.config/GNS3 $HOME/.config/GNS3-backup, then start gns3-gui again. this forced the recreation configuration files in a new $HOME/.config/GNS3 directory.
> 
> all the best...

Hi John,

greetings...

thanks for your suggestions my friend, the thoughts came into my mind as well when I first started encountering this issue. and have tried deleting all folders or files related to gns from the root directory as well...however even after getting the MacBook cleaned (with that I mean absolutely clean after getting the MacBook to factory setting and then upgraded to Big Sur, with gns3 being the first software installation with no other software's whatsoever....i'm wondering  how could this be that nothing is working even after trying all under the sun....but thanks John for coming to help, I really appreciate and requesting you to stand by since we have Jeremy from GNS with us here as well trying too get to the core of this issue, once resolved we might be able to learn something new out of this..

Thanks and Best Regards,
Rishi

**Comment by hanumatbalbeera** [comment]
HI Jeremy,

bro I tried everything as usual downloaded the gns3 2.2.18 and the gns3 vm 2.2.18 to use with vm ware fusion 12.1.0. however I'm getting the same results.
<img width="1138" alt="Screenshot 2021-02-17 at 1 20 57 AM" src="https://user-images.githubusercontent.com/77899496/108115026-92ddb580-70bf-11eb-933d-e8325d8ca1f9.png">
<img width="1680" alt="Screenshot 2021-02-17 at 1 23 00 AM" src="https://user-images.githubusercontent.com/77899496/108115045-97a26980-70bf-11eb-8287-2e3215e8015c.png">
<img width="1680" alt="Screenshot 2021-02-17 at 1 25 22 AM" src="https://user-images.githubusercontent.com/77899496/108115054-9a9d5a00-70bf-11eb-9026-8c91103c2751.png">

my MacBook is as good as stock with no third party softwares installed. 
apart from the basic operating system Big Sur and the softwares that come with it, I only have brackets for web dev coding.
I've always used brackets, gns3, and VMware and nothing else in my MacBook..

would you like to take a remote session of my MacBook and see for yourself if I'm doing anything unusual.. thus damn thing has really shaken my head and my confidence in solving issues as I'm not able to understand as to what is stopping gns3 to work when in the past it worked like a charm...please suggest anything brother...

Thanks and Best Regards,
Rishi

**Comment by hanumatbalbeera** [comment]
> > one thing that helped me with macos big sur, gns3-gui 2.2.17, gns3-server 2.2.17, vmware fusion 12.1.0/gns3 vm 2.2.27 was to quit gns3-gui (which includes gns3-server), mv $HOME/.config/GNS3 $HOME/.config/GNS3-backup, then start gns3-gui again. this forced the recreation configuration files in a new $HOME/.config/GNS3 directory.
> > all the best...
> 
> Hi John,
> 
> greetings...
> 
> thanks for your suggestions my friend, the thoughts came into my mind as well when I first started encountering this issue. and have tried deleting all folders or files related to gns from the root directory as well...however even after getting the MacBook cleaned (with that I mean absolutely clean after getting the MacBook to factory setting and then upgraded to Big Sur, with gns3 being the first software installation with no other software's whatsoever....i'm wondering how could this be that nothing is working even after trying all under the sun....but thanks John for coming to help, I really appreciate and requesting you to stand by since we have Jeremy from GNS with us here as well trying too get to the core of this issue, once resolved we might be able to learn something new out of this..
> 
> Thanks and Best Regards,
> Rishi

Hi John,

this is what I get when I tried mv $HOME/.config/GNS3 $HOME/.config/GNS3-backup, 

<img width="1024" alt="Screenshot 2021-02-17 at 2 26 13 AM" src="https://user-images.githubusercontent.com/77899496/108120687-ad1b9180-70c7-11eb-8cb9-9c7a196d3ce4.png">

bro this is getting pain in the wrong place now :-)

don't know what the heck to do with this..

thanks and best regards,
Rishi

**Comment by hanumatbalbeera** [comment]
HI Jeremy,

greetings my friend.....

I wanted to share how far I got with the damn issue....

I narrowed down to the two thieves that were using port 80 in my Mac
thief #1 - IMDPersistenceAgent Process
Thief #2- adprivcyd.

both these were using port 80 and blocking the connection due to which gns3 wasn't able to connect to local server.
I'm sorry I couldn't score the screenshots for you as I was to much into it and just wanted to kill something and found these two and killed the processes manually.

then restarted gns3 and finally after so many days I was able to see the local server light to be green. how ever it wasn't connecting to the gns3 vm so I tried another trick going into gas preferences and server tab there I changed host binding from local host to 0.0.0.0 (pic attached)
<img width="1680" alt="Screenshot 2021-02-19 at 1 00 01 AM" src="https://user-images.githubusercontent.com/77899496/108410804-dbc37480-724d-11eb-8428-02c45e54d93b.png">

now I have the GNS light turned to green as well. 
As you can see in the screen shot.

How ever I'm not able to drag and drop the devices in the work area.

CAN YOU HELP ME WITH THAT NOW BROTHER....lol

its like jumping off a plane with a chute but getting stuck on a tree...(can you believe that)

Jeremy I need your help asap bro....plz plz plz

Thanks and Best Regards,
Rishi

**Comment by hanumatbalbeera** [comment]
> Looks like you have something blocking the connection from the client to the server. Can you try to turn off the macOS firewall to see?
> 
> ![Screenshot from 2021-02-15 13-53-32](https://user-images.githubusercontent.com/4752614/107905199-f2dc3b00-6f9d-11eb-9b21-a8cbc328b13d.png)


HI Jeremy,

greetings my friend.....

I wanted to share how far I got with the damn issue....

I narrowed down to the two thieves that were using port 80 in my Mac
thief #1 - IMDPersistenceAgent Process
Thief #2- adprivcyd.

both these were using port 80 and blocking the connection due to which gns3 wasn't able to connect to local server.
I'm sorry I couldn't score the screenshots for you as I was to much into it and just wanted to kill something and found these two and killed the processes manually.

then restarted gns3 and finally after so many days I was able to see the local server light to be green. how ever it wasn't connecting to the gns3 vm so I tried another trick going into gas preferences and server tab there I changed host binding from local host to 0.0.0.0 (pic attached) just tried for the heck of it.
Screenshot 2021-02-19 at 1 00 01 AM

now I have the GNS light turned to green as well.
As you can see in the screen shot.

How ever I'm not able to drag and drop the devices in the work area.

CAN YOU HELP ME WITH THAT NOW BROTHER....lol

its like jumping off a plane with a chute but getting stuck on a tree...(can you believe that)

Jeremy I need your help asap bro....plz plz plz

Thanks and Best Regards,
Rishi

EDIT: sorry I forgot to mention that the gns3 vm is still getting me to grub screen(
Screenshot 2021-02-19 at 1 15 16 AM
Pic attached)

Also see this
Screenshot 2021-02-19 at 1 28 04 AM

ive also noticed something about Big Sur that it randomly assigns port to application...like I just restarted gns3 and wasn't able to get the local server listed only. then I went back to activity monitor found another application using port 80, killed it and then restarted gns3 and was able to get back the local server and the light turned to green

and the gns3 vm IP is 192.168.73.2 and network add 192.168.73.0/24 and the local server IP is 127.0.0.1 network:127.0.0.0/8 now when I try to bind the local server to the ip same as of gns3 vm from the preferences it still doesn't do any good and I'm not able to drag and drop the device in the working panel

please suggest me something that can be done to get this right.
Hi Jeremy,

still awaiting your response. hope you received the above comments and the screenshots I shared.

Best regards,
Rishi
