### ISSUE TITLE
When creating node of type ethernet_switch console type is expected

### ISSUE THREAD

**Issue by cheungtitus** [GNS3/gns3-server#1873]
When creating a node following spec states only 'compute_id', 'name', and 'node_type' are mandatory.
http://api.gns3.net/en/2.2/api/v2/controller/node/projectsprojectidnodes.html#post-v2-projects-project-id-nodes

Whilst some nodes such as cloud won't have console but some such as ethernet_switch does and is expecting console_type to be passed in.

**Version**
GNS3 server 2.2.17

**How to reproduce**
Submit following to end point http://{gns3-ip}:3080/v2/projects/{project-id}/nodes
```
{
  "compute_id": "local",
  "name": "switch",
  "node_type": "ethernet_switch"
}
```

**Result**
```
{
    "message": "Bad request http://127.0.0.1:3080/v2/compute/projects/{project-id}/ethernet_switch/nodes {\n    \"message\": \"None is not one of ['telnet', 'none']\\n\\nFailed validating 'enum' in schema['properties']['console_type']:\\n    {'description': 'Console type', 'enum': ['telnet', 'none']}\\n\\nOn instance['console_type']:\\n    None\",\n    \"method\": \"POST\",\n    \"path\": \"/v2/compute/projects/{project_id}/ethernet_switch/nodes\",\n    \"request\": {\n        \"node_id\": \"{node_id}\"\n    },\n    \"status\": 400\n}",
    "method": "POST",
    "path": "/v2/projects/{project_id}/nodes",
    "request": {
        "node_type": "ethernet_switch"
    },
    "status": 400
}
```

**Comment by grossmj** [comment]
Fixed. This will work in version 2.2.19
