### ISSUE TITLE
Mac Big Sur, Fusion 12, GNS3 2.2.18 - Build networks and connecting to GNS3 Server issue

### ISSUE THREAD

**Issue by andyjsparkes** [GNS3/gns3-server#1874]
I am running Mac BigSur 11.2 and the most recent version of gns3 2.2.18. GNS3 server is running inside fusion 12.1.0

I am unable to run any kind of a virtual environment. 
Symptoms:

If i dont start the gns3 vm, it nolonger starts when gns3 app is first loaded on my mac.
If I close gns3, the server still shutsdown indicating there is a link.

I can open a project with devices or create a blank project, but regardless of new project or old i can't add any new devices to the network map.
If i open a previous project that does contain devices, they appear to start and although a console appears to open, nothing appears to run. This includes QEMU, vm or the original IOS device types.

I have tested access to the local instance on port 8030 and it looks good.
I have tested access to the gns3 vm and i get a response via ssh or http.

A tcpdump from my mac shows 2 way communication. 
A tcpdump from the gns3 server only shows packets from the mac, but not the return.

I have disabled firewall on my mac and reenabled. 
I have disabled the firewall from System preferences on my mac tested and reenabled without a change in state. 
Both gns3 and fusion have full disk access.

**Comment by grossmj** [comment]
Support for VMware Fusion is currently broken on Big Sur: https://github.com/GNS3/gns3-server/issues/1868#issuecomment-790395513

**Comment by grossmj** [comment]
Should have been fixed since v2.2.22
