### ISSUE TITLE
MacOS Big Sur and VMware Fusion 12.1: WebClient Application window never appears

### ISSUE THREAD

**Issue by wtibben** [GNS3/gns3-server#1875]
I am pleased with Web UI option for GNS3. However, I cannot get the WebClient Pack app to open.  I am using Mac Book Pro (Dual Core Processor Intel I5 RAM=16MB) with  Big Sur 11.2.2.  I use VMWave Fusion 12.1 Pro for the GNS3 VM version 2.2.18. 

I open the app  using control key to subvert Apple security block but the WebClient Application window never appears.  The GNS3 WebClient icon does not appear in the Dock and it does not appear in the list when I go to "force quit". However,, if I drag the DMG file to the Applications folder to re-install I am informed a copy already exits (OK) and it is running.

I'm wondering if this is a Big Sur problem - I cannot compare as I have just recently began to use Web UI access. Any assistance would be greatly appreciated!

**Comment by grossmj** [comment]
@wtibben I have rebuilt the WebClient application. It should work on Big Sur now, please download from https://github.com/GNS3/gns3-webclient-pack/releases/tag/v1.0.0b3

Let us know if it works on your side. Thanks :+1:

**Comment by wtibben** [comment]
Hi Jeremy,

Sorry to say that I can’t get past the screen where options are listed for Telnet, VNC, SPICE and Packet Capture.

Clicking on Apply or reset has not impact. I click on close and the program seems to close down.

Will

**Comment by grossmj** [comment]
> Sorry to say that I can’t get past the screen where options are listed for Telnet, VNC, SPICE and Packet Capture.

This is normal, you can only configure the application paths. Then when you use the web-ui, click on a running node and select "Open console", the webclient launcher will open your console application.

**Comment by wtibben** [comment]
Oops. Thanks for the reminder….

Things are starting to happen.  I will touch base once I have tried a few things.

**Comment by wtibben** [comment]
Thanks Jeremy,

Seems to working now thanks!

Terminal telnet works well.

VNC -  Not sure if this part of your brief but I find that Chicken wont open. Error message is:

Cannot start command '/Applications/Chicken.app/Contents/MacOS/Chicken 192.168.155.6:5901': [Errno 2] No such file or directory: '/Applications/Chicken.app/Contents/MacOS/Chicken': '/Applications/Chicken.app/Contents/MacOS/Chicken’


I can open Chicken separately and enter in the relevant ip address and port.  This will work on occasions but then Chicken crashes.  I have been looking at Royal TSX to see if that will work better.


Similarly Wireshark has issues.  Wireshark app opens up but doesn’t load the file which has the wireshark capture file. So if you have any documentation about how to make sense of this I would appreciate it.

Regards

Will

**Comment by grossmj** [comment]
`/Applications/Chicken.app/Contents/MacOS/Chicken`

Looks like the WebClient does not like spaces in the path...

**Comment by grossmj** [comment]
Chicken of the VNC doesn't seem to be supported anymore and doesn't work on macOS Big Sur. So I tried to use Royal TSX:

Download Royal TSX, move it to `/Applications` and launch.

![Screenshot from 2021-05-13 14-35-27](https://user-images.githubusercontent.com/4752614/118081429-7faa5f80-b3fa-11eb-94ed-62d26966bdb7.png)

Then install the VNC plugin.

![Screenshot from 2021-05-13 14-37-45](https://user-images.githubusercontent.com/4752614/118081451-85a04080-b3fa-11eb-8ea4-34fc41855ac8.png)

Configure the VNC command to be launched in the WebClient.

![Screenshot from 2021-05-13 14-35-47](https://user-images.githubusercontent.com/4752614/118081457-8933c780-b3fa-11eb-990f-daae5481b7c0.png)

Finally, console to a running node that has been configured with `vnc` console type. Royal TSX VNC should start.

**Comment by wtibben** [comment]
Thanks Jeremy,

Royal TSX opens without any issues.
Wireshark also opens and captures traffic with no issues.

Thanks for providing these pointers. Certainly saved me time.

Will

**Comment by wtibben** [comment]
Hi Jeremy,

Just one more observation.  I find that Chrome seems to work best with the web client in comparison to Firefox. This observation applies to both Windows 10 and Mac.  Are you interested in further updates? One example is that I discovered Wireshark open up fine with GNS3 switch but does not seem to work if I replace the GNS3 switch with a qemu Cisco image.

Thanks for your assistance

Will

**Comment by grossmj** [comment]
>  Are you interested in further updates? 

Definitely, please can you open a new issue on https://github.com/GNS3/gns3-web-ui/issues with your observation? Please try to add screenshots when relevant.

Thanks :)
