### ISSUE TITLE
"Sync appliance files" doesn't work for renamed/deleted appliances

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-server#1876]
The "Sync appliance files" commits seem to only add and update appliances, but doesn't delete them.

In the gns3-registry commit https://github.com/GNS3/gns3-registry/commit/69676a4a4e9d85ea5652820fc5b9da4969d3c0a8 the appliance `Raspian.gns3a` got updated and renamed to `raspian.gns3a`. That results in a gns3-server commit 17b56ac7cb179fae3861b251ae31d418eaec6509, which adds `raspian.gns3a` as a new appliance, but doesn't delete the old `Raspian.gns3a`.

So actually in this gns3-server repository we have two raspian appliances, the actual `raspian.gns3a` and the outdated `Raspian.gns3a`.

**Comment by grossmj** [comment]
Good catch!

**Comment by grossmj** [comment]
Fixed.
