### ISSUE TITLE
GNS VM Server on VirtBox Crashes VERR EM INTERNAL Error

### ISSUE THREAD

**Issue by aantu014** [GNS3/gns3-server#1883]
Everytime I start a QEMU/KVM device in GNS3 the VM crashes. I have already reinstalled the VM's and GNS3 and still gives me the problem. Others have experience a similar problem.

https://forums.virtualbox.org/viewtopic.php?f=6&t=102011

**Comment by aantu014** [comment]
[VBox.log](https://github.com/GNS3/gns3-server/files/6268107/VBox.log)

**Comment by vittore** [comment]
+1

**Comment by grossmj** [comment]
> https://forums.virtualbox.org/viewtopic.php?f=6&t=102011

Apparently the issue has been solved by VirtualBox 6.1.20. Please comment back if you still face issues however I doubt we can do something about these kind of errors.
