### ISSUE TITLE
MacOS BigSur-GNS3 Client issue

### ISSUE THREAD

**Issue by jtravlos** [GNS3/gns3-server#1886]
MacOS BigSur 11.2.3
VM Fusion Pro 12.1.1
GNS3 2.2.7
Both the Mac firewall and Norton firewall are disabled

When I open GNS3 client, the icon shows in the dock, but there is no application window opens.
When I right click on the icon in the dock, it says 'Application not responding'.  
When I go to Force Quit the application, it also says the GNS3 application is not responding. 

Is there any solutions to resolve this?

**Comment by grossmj** [comment]
Do you have a Mac with M1 chip or Intel?

**Comment by jtravlos** [comment]
It's an Intel i7.  Here are the rest of the specs:

Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	429.80.1.0.0
  SMC Version (system):	2.45f5

**Comment by grossmj** [comment]
You must upgrade to at least version 2.2.17 which added support for macOS BigSur.
