### ISSUE TITLE
Use a stock BusyBox for the Docker Integration

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-server#1890]
For the Docker integration GNS3 injects its special busybox binary <https://github.com/GNS3/busybox> into the docker container. That gives us full control over the injected binary.

But that has some drawbacks:

* The binary is available only for the x86_64 architecture, it doesn't work on processors of other types. This is also the subject of issue <https://github.com/GNS3/gns3-server/issues/970>.
* The binary is quite old and mainly unmaintained, it might have some security bugs.
* Distributions prefer full source packages, they typically don't welcome binary blobs.

For example Alpine solves this by replacing the busybox binary by their own static busybox binary for non-x86_64 architectures, see <https://gitlab.alpinelinux.org/alpine/aports/-/blob/3.13-stable/community/gns3-server/APKBUILD#L28>. I think some other distributions behave similar.

I suggest to switch to "normal" busybox binaries. That could be the static busybox package, provided by the distribution. Alternatively the busybox binary can be extracted out of the official busybox docker image: `docker run --rm -v "<absolute local path>:/host" -u "$(id -u):$(id -g)" busybox sh -c 'cp -L /bin/busybox /host/ && touch -r /bin/busybox /host/busybox'`

The main difficulty with this are the special options for `udhcpc`, that the GNS3-busybox is using, see <https://github.com/GNS3/busybox/blob/gns3_build/gns3_build/README.md>. I managed to apply these options also to the stock busybox by using a wrapper script for udhcpc:

```
diff --git a/gns3server/compute/docker/resources/bin/udhcpc b/gns3server/compute/docker/resources/bin/udhcpc
new file mode 100755
index 00000000..fe1410a6
--- /dev/null
+++ b/gns3server/compute/docker/resources/bin/udhcpc
@@ -0,0 +1,8 @@
+#!/gns3/bin/busybox sh
+
+SCRIPT="/gns3/etc/udhcpc/default.script"
+EXTRA=""
+
+[ "$(cat "/proc/$PPID/comm" 2>/dev/null)" = ifup ] && EXTRA="-t 3 -T 2 -A 1 -b"
+
+exec /tmp/gns3/bin/udhcpc -s "$SCRIPT" $EXTRA "$@"
```

I made one modification: I changed the paraneter `-T`/`--timeout` from 1 to 2, but that be easily reverted.

**Comment by b-ehlers** [comment]
@grossmj You are fast!!! But I suggest to change this in v3.0 to keep v2.2 stable.

**Comment by grossmj** [comment]
Indeed, 3.0 is wiser :+1:

**Comment by b-ehlers** [comment]
First problem.

The busybox-static packages of Ubuntu (tested focal) and Debian (tested buster + bullseye) don't include the `script` function, which is used by the Docker auxiliary console.  The busybox Docker image includes the `script` function.

So either the auxiliary console must be changed to run without using `script` or the busybox binary must be extracted from the busybox Docker image.

**Comment by b-ehlers** [comment]
`script` is also missing in Alpine's busybox, so if we want to use the busybox provided by a distribution, we need to get rid of it.

The use of `script` was added in issue <https://github.com/GNS3/gns3-server/issues/472>. Before that issue the auxiliary console was very basic. The input/output to the shell was just a pipe, so no terminal capabilities were available. So when we revert that change, we will loose these capabilities again. But as an emergency console it's still useful.

I you wat to check it out, here my patch, tested with busybox-static from debian bullseye:

```
diff --git a/gns3server/compute/docker/docker_vm.py b/gns3server/compute/docker/docker_vm.py
index 940aeab6..0aef4105 100644
--- a/gns3server/compute/docker/docker_vm.py
+++ b/gns3server/compute/docker/docker_vm.py
@@ -510,13 +510,13 @@ class DockerVM(BaseNode):
         # https://github.com/GNS3/gns3-gui/issues/1039
         try:
             process = await asyncio.subprocess.create_subprocess_exec(
-                "docker", "exec", "-i", self._cid, "/gns3/bin/busybox", "script", "-qfc", "while true; do TERM=vt100 /gns3/bin/busybox sh; done", "/dev/null",
+                "docker", "exec", "-i", self._cid, "/gns3/bin/busybox", "sh", "-c", "while true; do /gns3/bin/busybox sh -i; done",
                 stdout=asyncio.subprocess.PIPE,
                 stderr=asyncio.subprocess.STDOUT,
                 stdin=asyncio.subprocess.PIPE)
         except OSError as e:
             raise DockerError("Could not start auxiliary console process: {}".format(e))
-        server = AsyncioTelnetServer(reader=process.stdout, writer=process.stdin, binary=True, echo=True)
+        server = AsyncioTelnetServer(reader=process.stdout, writer=process.stdin, binary=False, echo=False)
         try:
             self._telnet_servers.append((await asyncio.start_server(server.run, self._manager.port_manager.console_host, self.aux)))
         except OSError as e:
```

**Comment by b-ehlers** [comment]
Alternatively the `script` function can be moved from the container to the GNS3 server. Then script is not longer needed in the containers busybox, instead it must be installed on the server. On Debian/Ubuntu script is included in the bsdutils package, which is always installed. In other Linux variants script might not be installed by default, but it should be easily available.

The big advantage over my previous suggestion is, that the terminal capabilities are fully available.

```
diff --git a/gns3server/compute/docker/docker_vm.py b/gns3server/compute/docker/docker_vm.py
index 940aeab6..0385324b 100644
--- a/gns3server/compute/docker/docker_vm.py
+++ b/gns3server/compute/docker/docker_vm.py
@@ -510,7 +510,7 @@ class DockerVM(BaseNode):
         # https://github.com/GNS3/gns3-gui/issues/1039
         try:
             process = await asyncio.subprocess.create_subprocess_exec(
-                "docker", "exec", "-i", self._cid, "/gns3/bin/busybox", "script", "-qfc", "while true; do TERM=vt100 /gns3/bin/busybox sh; done", "/dev/null",
+                "script", "-qfc", f"docker exec -i -t {self._cid} /gns3/bin/busybox sh -c 'while true; do TERM=vt100 /gns3/bin/busybox sh; done'", "/dev/null",
                 stdout=asyncio.subprocess.PIPE,
                 stderr=asyncio.subprocess.STDOUT,
                 stdin=asyncio.subprocess.PIPE)
```

Even better would be to use PTY instead of pipes for running "docker exec", then `script` would be no longer needed. But in some early tests, I wasn't able to use PTY with asynio.

**Comment by b-ehlers** [comment]
The vty solution is not usable, the telnet process for the auxiliary console is not stopped, when the node is stopped.

I suggest to go back to the [local script](https://github.com/GNS3/gns3-server/issues/1890#issuecomment-834306213) solution.

**Comment by b-ehlers** [comment]
Fixed the issue in the vty solution. When the remote end of a pipe gets closed, a read() return EOF, while ptys raise an OSError. As the OSerror wasn't handled, the telnet process to the auxiliary console was not closed.

The following patch includes also handling that case: [stock_busybox-pty-patch.txt](https://github.com/GNS3/gns3-server/files/6515025/stock_busybox-pty-patch.txt)

But for me the main question is: Do we really want the pty solution? It is Linux only and relative complex. The local script solution is far simpler, but is also Linux-only. Currently GNS3 supports Docker only on Linux, so that's no issue. An OS independent solution would need to implement docker-exec in python, but that's currently not needed.

**Comment by grossmj** [comment]
I have opened a PR but couldn't test: https://github.com/GNS3/gns3-server/pull/1908

**Comment by b-ehlers** [comment]
As I'm still on v2.2 I can't test as well. But I'm using exactly these changes in v2.2 and here they are working well.

Just one small formatting issue, as `"/dev/null"` is an argument to the script command I would split the line
```
       `         f"docker exec -i -t {self._cid} /gns3/bin/busybox sh -c 'while true; do TERM=vt100 /gns3/bin/busybox sh; done'", "/dev/null",
```
into two
```
                f"docker exec -i -t {self._cid} /gns3/bin/busybox sh -c 'while true; do TERM=vt100 /gns3/bin/busybox sh; done'",
                "/dev/null",
```

But we haven't discussed one important point: Where to get the busybox binary from and how to inject it into a docker container?

My current idea:
The current busybox binary gets deleted from the resources directory.
At installation time a statically linked busybox binary is copied into the resources directory.

For a package installation it's quite easy. The statically linked busybox is defined as a dependency. The installation script knows it's location and copies it to the resources directory.

But for an installation via setup.py or pip it's more complicated. I suggest, that setup.py searches for `busybox-static`, `busybox.static` and `busybox` in the PATH. If it finds one, it checks via `ldd`, if it's a statically linked binary (ldd should return an error). If everything is fine, the binary is copied to the resources directory, otherwise an error is shown.

**Comment by b-ehlers** [comment]
An update to the udhcpc wrapper script: It needs to remove a "-n" argument, otherwise udhcpc will stop asking for new leases after the initial 3 tries. Standard busybox binaries are including the "-n" argument in ifup to the udhcpc call.

The removal of "-n" is a bit sloppy, it doesn't do a full getopts parsing. Instead it just looks for the "-n" string.

```
diff --git a/gns3server/compute/docker/resources/bin/udhcpc b/gns3server/compute/docker/resources/bin/udhcpc
new file mode 100755
index 00000000..16c064d0
--- /dev/null
+++ b/gns3server/compute/docker/resources/bin/udhcpc
@@ -0,0 +1,15 @@
+#!/gns3/bin/busybox sh
+
+SCRIPT="/gns3/etc/udhcpc/default.script"
+
+if [ "$(cat "/proc/$PPID/comm" 2>/dev/null)" = ifup ]; then
+	# remove "-n" argument
+	for arg do
+		shift
+		[ "$arg" = "-n" ] || set -- "$@" "$arg"
+	done
+	# add default parameters
+	set -- -t 3 -T 2 -A 1 -b "$@"
+fi
+
+exec /tmp/gns3/bin/udhcpc -s "$SCRIPT" "$@"
```

**Comment by b-ehlers** [comment]
Here an updated udhcpc wrapper script using getopts. Long options are not supported, ifup uses only the short ones.
[udhcpc_getopts](https://github.com/GNS3/gns3-server/files/6642126/udhcpc_getopts.txt)

But that's quite complex, I'm unsure if that is really useful.

**Comment by grossmj** [comment]
> But that's quite complex, I'm unsure if that is really useful.

So maybe first solution (https://github.com/GNS3/gns3-server/issues/1890#issuecomment-859528813) is enough? ;)

**Comment by b-ehlers** [comment]
> > But that's quite complex, I'm unsure if that is really useful.
> 
> So maybe first solution ([#1890 (comment)](https://github.com/GNS3/gns3-server/issues/1890#issuecomment-859528813)) is enough? ;)

Yes, that's my idea as well. This part of the udhcpc wrapper is only used to modify the predefined options issued by ifup. And I hope we can rely on the builders of the busybox package, that they format the options in a sane way.

**Comment by b-ehlers** [comment]
Ref <https://github.com/GNS3/gns3-server/issues/1890#issuecomment-853745931>:

I have added a function to setup.py, that copies the system busybox into `gns3server/compute/docker/resources/bin/` before running the setup. I have no idea, if that is the right way to way and what side effects that may have.

```
diff --git a/setup.py b/setup.py
index 7b7b2459..d89b2c22 100644
--- a/setup.py
+++ b/setup.py
@@ -15,7 +15,10 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+import os
 import sys
+import shutil
+import subprocess
 from setuptools import setup, find_packages
 from setuptools.command.test import test as TestCommand
 
@@ -39,6 +42,27 @@ class PyTest(TestCommand):
         sys.exit(errcode)
 
 
+BUSYBOX_PATH = "gns3server/compute/docker/resources/bin/busybox"
+
+def copy_busybox():
+    if not sys.platform.startswith("linux"):
+        return
+    if os.path.isfile(BUSYBOX_PATH):
+        return
+    for bb_cmd in ("busybox-static", "busybox.static", "busybox"):
+        bb_path = shutil.which(bb_cmd)
+        if bb_path:
+            if subprocess.call(["ldd", bb_path],
+                               stdin=subprocess.DEVNULL,
+                               stdout=subprocess.DEVNULL,
+                               stderr=subprocess.DEVNULL):
+                shutil.copy2(bb_path, BUSYBOX_PATH, follow_symlinks=True)
+                break
+    else:
+        raise SystemExit("No static busybox found")
+
+
+copy_busybox()
 dependencies = open("requirements.txt", "r").read().splitlines()
 
 setup(
```

**Comment by grossmj** [comment]
> I have added a function to setup.py, that copies the system busybox into gns3server/compute/docker/resources/bin/ before running the setup. I have no idea, if that is the right way to go and what side effects that may have.

Alternatively, would it be possible to search for busybox and copy to `gns3server/compute/docker/resources/bin/ ` (if not already there) in `init.sh`?

https://github.com/GNS3/gns3-server/blob/3.0/gns3server/compute/docker/resources/init.sh

**Comment by b-ehlers** [comment]
> I guess the only thing left if to add busybox-static as a dependency to our gns3-server Debian package?

No, busybox-static is needed, when setup.py is running, for the Debian package that's during build time. The gns3-server.deb doesn't need the busybox-static as a dependency, it already includes it. But for users building gns3-server from pip/source the requirement for busybox-static needs to be documented.

> Alternatively, would it be possible to search for busybox and copy to `gns3server/compute/docker/resources/bin/ ` (if not already there) in `init.sh`?

No, init.sh already runnings within the docker container (without access to the host filesystem) with that busybox.static as shell. So init.sh is too late. What would be possible is, to copy the static busybox within the gns3server docker module, before the docker image is started.

**Comment by grossmj** [comment]
> The gns3-server.deb doesn't need the busybox-static as a dependency, it already includes it.

I am a bit confused, do you mean busybox is already included in `gns3server/compute/docker/resources/bin` ?

**Comment by b-ehlers** [comment]
> > The gns3-server.deb doesn't need the busybox-static as a dependency, it already includes it.
> 
> I am a bit confused, do you mean busybox is already included in `gns3server/compute/docker/resources/bin` ?

`setup.py` first copies the static busybox to `gns3server/compute/docker/resources/bin`. So you have the same situation as before this changes, `gns3server/compute/docker/resources/bin` contains a static busybox. Then `setup.py` runs its normal installation function, which copies the python code and the resources (including the static busybox) to the installation directories.

**Comment by grossmj** [comment]
Ok but what happens in the case of a PPA installation? setup.py isn't executed. So how will GNS3 find busybox? (I deleted gns3server/compute/docker/resources/bin/busybox from the repository earlier).

**Comment by b-ehlers** [comment]
Warning: The following is just theory, based on the PPA build log file, for example <https://launchpadlibrarian.net/551710005/buildlog_ubuntu-focal-amd64.gns3-server_2.2.23~focal1_BUILDING.txt.gz>

During PPA building the source is unpacked to `/<<PKGBUILDDIR>>`. Then later during `Processing /<<PKGBUILDDIR>>` I guess that directly or indirectly `setup.py` is called. That installs gns3-server into a temporary directory, at that time the static busybox gets also copied. So during building the PPA package building, a static busybox is needed as a build requirement. The contents of the temporary directory, where the gns3-server is installed, is then used to create the DEB package.

During installation of the PPA package the busybox binary is part of the DEB, the same way it currently is. The difference is only, that it is not the GNS3 specific busybox, but the busybox from the PPA build environment.

As I said, that's just theory. No idea if that will work that way.

**Comment by grossmj** [comment]
I tried to build a package built from the PR branch https://github.com/GNS3/gns3-server/pull/1908

https://launchpadlibrarian.net/553206282/buildlog_ubuntu-bionic-amd64.gns3-server_3.0.0dev3~bionic1_BUILDING.txt.gz

It looks like setup.py is called but unfortunately the build failed. I think because no busybox binary was found. I tried to add busybox has a dependency but same result. I am going to search for an alternative.

**Comment by b-ehlers** [comment]
I tested the ubuntu package creation of gns3-server v2.2.26 for focal:

I downloaded the source from <https://launchpad.net/~gns3/+archive/ubuntu/ppa/+sourcefiles/gns3-server/2.2.26~focal1/gns3-server_2.2.26~focal1.tar.gz>. Then I started the docker image `ubuntu:focal` and built the package (`apt-get install build-essential`, `apt-get build-dep .`, `dpkg-buildpackage -us -uc -b`), which works.

Finally I patched the source as in PR https://github.com/GNS3/gns3-server/pull/1908, slightly changed for v2.2. I got the same error message as you did, when building via PPA. I tried to get a better error output by using print() and sys.exit() in setup.py, but that didn't change anything. So I have no idea, how to get better diagnostics.

Then I added  busybox-static to the Build-Depends in debian/control, now it looks like this:
```
Build-Depends: debhelper (>= 9), python3, python3-setuptools, python3-dev, dh-virtualenv, python-setuptools, busybox-static
```
This time the build succeeds, but I can't test it. At least the busybox binary in the gns3-server package is the same as the static busybox in the build environment:
```
root@d8be5b933962:~# dpkg -c gns3-server*.deb | grep busybox
-rwxr-xr-x root/root   2172376 2021-10-08 12:38 ./usr/share/gns3/gns3-server/lib/python3.8/site-packages/gns3server/compute/docker/resources/bin/busybox
root@d8be5b933962:~# ls -l /bin/busybox 
-rwxr-xr-x 1 root root 2172376 Nov 11  2020 /bin/busybox
```

**Comment by grossmj** [comment]
I tried a new build based on Ubuntu 20.04 and this time it worked: https://launchpad.net/~gns3/+archive/ubuntu/ppa/+build/22279056

Not sure what I missed the first time... Anyway, I am going to try this build and will merge https://github.com/GNS3/gns3-server/pull/1908 once I confirm everything works as intended

**Comment by b-ehlers** [comment]
In your build from [Aug 12](https://github.com/GNS3/gns3-server/issues/1890#issuecomment-897438483) you haven't added busybox-static to `Build-Depends`. The build log doesn't show it in the line starting with "Merged Build-Depends:", while it is shown in the build log in the latest build. Maybe you added busybox to the `Depends:` line.

**Comment by grossmj** [comment]
I tested the Debian package in a VM and could run Docker containers without any issue. I will merge the PR now, thanks again for your help with it 👍
