### ISSUE TITLE
GNS3 VM 2.2.21 Upgrade failure

### ISSUE THREAD

**Issue by weardj** [GNS3/gns3-server#1893]
I attempted to upgrade my GNS3 VM to 2.2.21 and I get the following error. 

_fatal: Unable to create '/home/gns3/gns3-server/.git/index.lock' : Permission denied_

I haven't made any changes to file permissions that I'm aware of. I attached a screenshot as well. Its running on ESXi 6.7u3. Currently running 2.2.20. 

![Capture4](https://user-images.githubusercontent.com/1319795/117869483-d849f300-b268-11eb-91b6-ff1dfc37c3ad.PNG)

**Comment by grossmj** [comment]
Here is a workaround. Start a shell and execute the following command: `sudo rm -rf /home/gns3/gns3-server`. Then you should be able to upgrade.

**Comment by grossmj** [comment]
Should be fixed now. Thanks.
