### ISSUE TITLE
ubridge errors not visible in logs

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-server#1895]
When running gns3-server with the web UI, I found an issue that if an error occurs in ubridge, it appears to be silently skipped without any error being visible either in the gns3-server stdout logs, or in the web UI.

The specific case that triggered this was running gns3-server in a container, where I had omitted to pass `/dev/net/tun` through.   On running a project, the node started but without a tap interface on the virbr0 bridge.  By adding some debugging I can see that a 206 error is returned by the ubridge hypervisor; the code is detecting this an raising a UbridgeError exception, but it is then not being reported.

For this particular case, I was able to get reports through to stdout by adding some explicit logging:

```
--- /usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/compute/builtin/nodes/cloud.py.orig	2021-05-10 13:16:28.000000000 +0000
+++ /usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/compute/builtin/nodes/cloud.py	2021-05-13 20:49:52.796517609 +0000
@@ -401,8 +401,9 @@
             await self.start()
             await self._add_ubridge_connection(nio, port_number)
             self._nios[port_number] = nio
         except (NodeError, UbridgeError) as e:
+            log.warning('add_nio _add_ubridge_connection error: {error}'.format(error=e))
             await self._stop_ubridge()
             self.status = "stopped"
             self._nios[port_number] = nio
             self.project.emit("log.error", {"message": str(e)})
```

which shows:

```
2021-05-13 20:40:03 WARNING cloud.py:406 add_nio _add_ubridge_connection error: Error while sending command 'bridge add_nio_tap "f46e1ad0-4d48-4326-a2f8-6dfeeae7749d-0" "gns3tap0-0"': unable to create NIO TAP for bridge 'f46e1ad0-4d48-4326-a2f8-6dfeeae7749d-0': uBridge version 0.9.18 running with libpcap version 1.8.1
Hypervisor TCP control server started (IP 0.0.0.0 port 45135).
UDP tunnel connecting from local port 20001 to IPv4 address 127.0.0.1 on port 20000
create_nio_tap: unable to open TAP device gns3tap0-0 (No such file or directory)
```

Now, I do notice the "self.project.emit" already in the code.  I don't know anything about the notification mechanism, but I wonder if it is something which requires the GNS3 desktop GUI to see?  Perhaps such error messages ought to go to the log, as well as to the notification system (in case there are no subscribers)?

**Comment by b-ehlers** [comment]
While the GNS3 log can be enhanced, and your case is a good example of that, please keep in mind, that also node specific log files exist. For any node specific problem it is a good idea to have a look into these logs as well. They are located in the node specific directory within the project directory on the GNS3 compute server.

To locate them you can right-click on a node and select "Show in file manager". For non-local devices you then have to connect to the GNS3 server and change to the node path to view these logs.

For my tools extension I wrote a small python script, that shows these node specific logs, see <https://git.b-ehlers.de/ehlers/gns3-tools-python/src/branch/master/nodes_log/nodes_log.py#L71>

**Comment by candlerb** [comment]
Thank you.  By node logs I presume you mean `/var/lib/GNS3/projects/<UUID>/project-files/qemu/<UUID>/*.log` ?  I did actually check those.

Recreating this scenario, I find only the following:

```
# ls
hda_disk.qcow2  hdb_disk.qcow2  qemu-img.log  qemu.log  ubridge.log

# head -n -0 *.log
==> qemu-img.log <==
Formatting '/var/lib/GNS3/projects/4fc65798-3e74-4255-8ee2-60ff392d4edf/project-files/qemu/e7bed246-b768-488a-b43c-7ca4f613cc81/hdb_disk.qcow2', fmt=qcow2 size=131072 backing_file=/var/lib/GNS3/images/QEMU/noc-hdb-20200727-abb285a3.img cluster_size=65536 lazy_refcounts=off refcount_bits=16

==> qemu.log <==
Start QEMU with /usr/bin/qemu-system-x86_64 -name noc ...snip rest...

Execution log:

==> ubridge.log <==
uBridge version 0.9.18 running with libpcap version 1.8.1
Hypervisor TCP control server started (IP 0.0.0.0 port 46239).
UDP tunnel connecting from local port 20003 to IPv4 address 127.0.0.1 on port 20002
UDP tunnel connecting from local port 20000 to IPv4 address 127.0.0.1 on port 20001
Source NIO listener thread for QEMU-e7bed246-b768-488a-b43c-7ca4f613cc81-0 has started
Destination NIO listener thread for QEMU-e7bed246-b768-488a-b43c-7ca4f613cc81-0 has started
```

I thought maybe the error would end up in ubridge.log, but it didn't.  From a user's point of view, it's a silent failure to create gns3tap0-0.

**Comment by grossmj** [comment]
Fixed, thanks :+1:
