### ISSUE TITLE
Windows and Ubuntu Appliance won't boot - GNS3 MacOS

### ISSUE THREAD

**Issue by niyidrums** [GNS3/gns3-server#1896]
I downloaded both Ubuntu and Windows appliances, got the softwares downloaded from the directed websites and was able to install it into GNS3. I am using GNS3 on MacOS with GNS3 VM running on VMware Fusion. At first when I tried importing the software for Windows7w/IE11-1, it complained about the MD5 not matching, I edited the appliance  and added the correct MD5 and that sorted the import. 

Installation went well and I'm able to drag and drop appliance into my topology but the appliances won't boot up (windows and ubuntu). I thought it was the windows software I was using, then I downloaded Windows10w/Edge-1, MD5 was fine, but still won't boot up. I was using apple VNC at first, then changed that to TSX based on recommendation that it's better to do VNC with either Chicken for VNC or TSX. I tried to use Chicken for VNC, but can't find an updated one that works with my current OS version.

I tried increasing the RAM of the appliance but that seem to do anything. 

Appreciate if someone can help out... Probably there is something I'm missing.

I've attached all snapshots and below are the versions of softwares:

MacOS: V11.3.1 (20E241)
GNS3: 2.2.20
VMware Fusion

Thanks.

**Comment by grossmj** [comment]
Sorry, no answers here. Please try on the community forum.
