### ISSUE TITLE
GNS3 ERROR: make sure GNS3 and VMware run under the same user

### ISSUE THREAD

**Issue by sciencenerd** [GNS3/gns3-server#1901]
Hello.

I'm getting an error trying to connect to a GNS3 VM. 

`Failed to connect to GNS3 VM (GNS3 VM): GNS3VM: Error while executing VMware command: vmrun has returned an error: unknown`

Try to run ‘/Applications/VMware Fusion.app/Contents/Library/vmrun’ - T fusion checkToolsState '/Users/anwar/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx' in a terminal to see more details And make sure GNS3 and VMware run under the same user. 

When I try and run this command, all that is returned is " unknown"

```
MacBook-Pro:Library anwar$ pwd
/Applications/VMware Fusion.app/Contents/Library
MacBook-Pro:Library anwar$ vmrun -T fusion checkToolsState '/Users/anwar/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx'
unknown
```

- Fusion: 12.1.1
- Operating System: Big Sur 11.2.3
- GNS3 Software Version: GNS3 2.2.20

**Comment by grossmj** [comment]
Looks like there is an issue with your installation.

Can you try to manually start the GNS3 VM using vmrun?

`vmrun -T fusion start '/Users/anwar/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx'`

**Comment by sciencenerd** [comment]
That doesn't appear to make a difference. 

I tired to manually start the GNS3 VM using the following: `vmrun -T fusion start /Users/anwar/Virtual\ Machines.localized/GNS3\ VM.vmwarevm `

This started the VM, but connection to the GNS3 was still trying to be established:
<img width="351" alt="Screen Shot 2021-06-06 at 7 36 48 AM" src="https://user-images.githubusercontent.com/6733048/120924778-ee49a880-c69a-11eb-8639-8d3bb235ebd5.png">
<img width="994" alt="Screen Shot 2021-06-06 at 7 36 38 AM" src="https://user-images.githubusercontent.com/6733048/120924781-f275c600-c69a-11eb-9112-b463e3195178.png">

This eventually failed to connect with the initial error message reported. I then re-ran the above process after applying the update to VMware (12.1.1 > 12.1.2). However, the update didn't appear to make a difference either.

**Comment by grossmj** [comment]
That's strange, it seems something is preventing GNS3 to get the guess IP address. Please try `vmrun -T fusion getGuestIPAddress '/Users/anwar/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx'` after the VM has started.

**Comment by sciencenerd** [comment]
I ran the command `vmrun -T fusion start '/Users/anwar/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx'` and encountered the following error: `The VMware Tools are not running in the virtual machine: /Users/anwar/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx` 

I was able to resolve the error following the directions posted by another user [here](https://gns3.com/community/featured/vmware-tools-are-not-installed-i). I was then able to run the original command which populated an IP address of `192.168.1.37` 

Below is the full output of both of the above commands: 
`MacBook-Pro:~ anwar$ vmrun -T fusion getGuestIPAddress '/Users/anwar/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx'
Error: The VMware Tools are not running in the virtual machine: /Users/anwar/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx`
`MacBook-Pro:~ anwar$ vmrun -T fusion getGuestIPAddress '/Users/anwar/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx'
192.168.1.37`
`MacBook-Pro:~ anwar$ `

**Comment by grossmj** [comment]
Workaround is to manually start the VM and configure the GUI to use the VM as the main server.

![Screenshot from 2021-12-25 11-06-05](https://user-images.githubusercontent.com/4752614/147374961-47aeba5a-08d3-42e0-b75d-3ccae7504bd0.png)
