### ISSUE TITLE
GNS3 Server with vmware nodes on it does not working after the update

### ISSUE THREAD

**Issue by mvarchdev** [GNS3/gns3-server#1915]
Hello. Here is the error from the log:

error while starting WIN_SERVER: Internal server error http://localhost:3080/v2/compute/projects/1a223735-a7eb-466c-9247-673ad9c0deec/vmware/nodes/8738a564-6976-4d97-8b7f-36abf2b77c5e/start
Internal server error http://localhost:3080/v2/compute/projects/1a223735-a7eb-466c-9247-673ad9c0deec/vmware/nodes/8738a564-6976-4d97-8b7f-36abf2b77c5e/start

What can it be?

**Comment by DrKaoliN** [comment]
I'm getting the same error, without any further explanations, when trying to start a VMware End Device from the GNS3 topology. It's weird because this used to work one year ago on the same machine.

**Comment by grossmj** [comment]
This is a bug in version 2.2.22. Please revert back to version 2.2.21 or use one of the recent nightly build available on https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/

**Comment by hikingpig** [comment]
Hi, found line 369 and 370 in `gns3-server/compute/vmware caused the bugs. v2.2.21 doesn't have them.
```py
        self._vmnets_info = vmnet_interfaces.copy()
        vmnet_interfaces = list(vmnet_interfaces.keys())
```

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/issues/1919

**Comment by charles-steiger** [comment]
> Hi, found line 369 and 370 in `gns3-server/compute/vmware/__init__.py` caused the bugs. v2.2.21 doesn't have them.
> 
> ```python
>         self._vmnets_info = vmnet_interfaces.copy()
>         vmnet_interfaces = list(vmnet_interfaces.keys())
> ```
> 
> So I just commented them out.

I truly appreciate this workaround as I was struggling to downgrade my GNS3 Linux GUI.

Take care!

**Comment by aymenzarour** [comment]
> Hi, found line 369 and 370 in `gns3-server/compute/vmware/__init__.py` caused the bugs. v2.2.21 doesn't have them.
> 
> ```python
>         self._vmnets_info = vmnet_interfaces.copy()
>         vmnet_interfaces = list(vmnet_interfaces.keys())
> ```
> 
> So I just commented them out.

hey, can u put the all the right path of this file
