### ISSUE TITLE
Docker support for Nvidia GPUs and/or allow docker custom flags

### ISSUE THREAD

**Issue by g1augusto** [GNS3/gns3-server#1923]
Hi Everyone,

I am working on a topology and I need to use Linux graphical desktops for which I would like to pass my Nvidia GPU CUDA enabled, this looks possible by using **nvidia-docker** in place of **docker** command or at least using **--runtime=nvidia** while calling docker application to launch the container.

Can these options be made available for GNS3 ?
Thank you

I apologize in case I didn't do correctly my homework.

**Comment by grossmj** [comment]
We have a similar request https://github.com/GNS3/gns3-gui/issues/3143 however we need to consider it due to security concerns.

**Comment by g1augusto** [comment]
I was thinking of linking **nvidia-docker** to **docker** but I find that not so elegant solution
