### ISSUE TITLE
Reloading gns3server

### ISSUE THREAD

**Issue by llevier** [GNS3/gns3-server#1926]
Hello,

Because I dont rely on gns3server, I need to reload gns3 projects upon a new appearing clone.

Of course, kill SIGHUP gns3server can be done, but it is less practical comparing to a simple API call on any GNS3 host.

Could it be possible to have a API call to reload gns3servers

thanks in advance :-)

**Comment by grossmj** [comment]
Done, the `/v2/reload` endpoint (POST) has been added. The controller will then reload all the files.

**Comment by grossmj** [comment]
Done, the `/v2/reload` endpoint (POST) has been added. The controller will then reload all the files.
