### ISSUE TITLE
Duplicate MAC addresses with IOSvL2 (SVI/VLAN interfaces)

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-server#1929]
## Problem description

This was a very horrible issue to debug, and it's something that potentially GNS3 can prevent.

Here's the background.  I have a moderately large topology, with 56 devices.  There are six groups of 7 IOSvL2 switches each sharing a layer2 domain (campus), plus some other devices.

Here are the MAC addresses assigned by GNS3:

```
$ grep mac_address project.gns3  | sort | uniq -c
      1                     "mac_address": "00:9a:20:00:32:00",
      1                     "mac_address": "00:9a:20:12:ec:00",
      1                     "mac_address": "00:9a:20:13:46:00",
      1                     "mac_address": "00:9a:20:15:2a:00",
      1                     "mac_address": "00:9a:20:18:bb:00",
      1                     "mac_address": "00:9a:20:19:eb:00",
      1                     "mac_address": "00:9a:20:1a:a2:00",
      1                     "mac_address": "00:9a:20:20:02:00",
      1                     "mac_address": "00:9a:20:2e:30:00",
      1                     "mac_address": "00:9a:20:42:88:00",
      1                     "mac_address": "00:9a:20:43:9f:00",
      1                     "mac_address": "00:9a:20:44:5f:00",
      1                     "mac_address": "00:9a:20:44:e3:00",
      1                     "mac_address": "00:9a:20:4a:41:00",
      1                     "mac_address": "00:9a:20:4d:c2:00",
      1                     "mac_address": "00:9a:20:57:cf:00",
      1                     "mac_address": "00:9a:20:65:fd:00",
      1                     "mac_address": "00:9a:20:75:a6:00",
      1                     "mac_address": "00:9a:20:8c:6c:00",
      1                     "mac_address": "00:9a:20:91:8c:00",
      1                     "mac_address": "00:9a:20:98:ea:00",
      1                     "mac_address": "00:9a:20:b4:04:00",
      1                     "mac_address": "00:9a:20:b5:6b:00",
      1                     "mac_address": "00:9a:20:c0:c9:00",
      1                     "mac_address": "00:9a:20:ca:49:00",
      1                     "mac_address": "00:9a:20:de:07:00",
      1                     "mac_address": "00:9a:20:df:58:00",
      1                     "mac_address": "00:9a:20:e3:1a:00",
      1                     "mac_address": "00:9a:20:f0:ba:00",
      1                     "mac_address": "00:9a:20:f3:67:00",
      1                     "mac_address": "0c:9a:20:03:85:00",
      1                     "mac_address": "0c:9a:20:1f:91:00",
      1                     "mac_address": "0c:9a:20:27:f5:00",
      1                     "mac_address": "0c:9a:20:32:c6:00",
      1                     "mac_address": "0c:9a:20:37:41:00",
      1                     "mac_address": "0c:9a:20:4f:97:00",   <<< edge1-b1.campus5
      1                     "mac_address": "0c:9a:20:4f:af:00",   <<< core1.campus5
      1                     "mac_address": "0c:9a:20:5c:fc:00",
      1                     "mac_address": "0c:9a:20:67:7f:00",
      1                     "mac_address": "0c:9a:20:72:b2:00",
      1                     "mac_address": "0c:9a:20:73:d6:00",
      1                     "mac_address": "0c:9a:20:76:7c:00",
      1                     "mac_address": "0c:9a:20:86:57:00",
      1                     "mac_address": "0c:9a:20:92:e3:00",
      1                     "mac_address": "0c:9a:20:99:06:00",
      1                     "mac_address": "0c:9a:20:9c:43:00",
      1                     "mac_address": "0c:9a:20:a5:2a:00",
      1                     "mac_address": "0c:9a:20:af:b2:00",
      1                     "mac_address": "0c:9a:20:b5:32:00",
      1                     "mac_address": "0c:9a:20:c3:d9:00",
      1                     "mac_address": "0c:9a:20:c5:0d:00",
      1                     "mac_address": "0c:9a:20:c7:e4:00",
      1                     "mac_address": "0c:9a:20:cf:ed:00",
      1                     "mac_address": "0c:9a:20:d3:a9:00",
      1                     "mac_address": "0c:9a:20:d5:d0:00",
      1                     "mac_address": "0c:9a:20:df:fa:00",
```

They are unique, but I have highlighted two of them which share the same 4 byte prefix.  This will become important as you'll see shortly.

One of the layer2 domains (campus5) includes these devices:

```
core1 -------- dist1-b1 ------ edge1-b1
172.25.10.1    172.25.10.2     172.25.10.3
```

The IP addresses are assigned to a vlan interface, `interface Vlan10` on each device.

The problem: although dist1-b1 and edge1-b1 can ping each other, core1 and edge1-b1 cannot ping each other.  They are unable to resolve ARP entries for each other.

After a lot of head scratching, I eventually found the problem:

```
core1.campus5#sh int vlan10
Vlan10 is up, line protocol is up 
  Hardware is Ethernet SVI, address is 0c9a.204f.800a (bia 0c9a.204f.800a)
```

```
edge1-b1.campus5#sh int vlan10
Vlan10 is up, line protocol is up 
  Hardware is Ethernet SVI, address is 0c9a.204f.800a (bia 0c9a.204f.800a)
```

The two switches have the *same* MAC address on their VLAN interface!!

It seems Cisco IOSvL2 has a hard-coded assumption that device MAC addresses are unique up to the first 4 octets.  Therefore, it can make a MAC address for interface "vlan10" by replacing the bottom two octets with 0x800a (0x8000 + the VLAN number)

For comparison, here are the Gi0/0 interfaces:

```
core1.campus5#sh int gi0/0
GigabitEthernet0/0 is up, line protocol is up (connected) 
  Hardware is iGbE, address is 0c9a.204f.af00 (bia 0c9a.204f.af00)
```

```
edge1-b1.campus5#sh int gi0/0
GigabitEthernet0/0 is up, line protocol is up (connected) 
  Hardware is iGbE, address is 0c9a.204f.9700 (bia 0c9a.204f.9700)
```

(The other two devices which share a prefix, `00:9a:20:44`, are in different campus layer2 domains, so they don't interfere with each other).

Now that I understand this problem, I can manually fix the MAC addresses in my project.gns3.  I am not sure what happens if someone imports a portable project: a quick test suggests that the MAC addresses in the project are retained, not randomized, which is good.  There is an option when exporting a project to reset the MAC addresses, so this problem could recur if that's used.

## Proposal

I think it would be better if GNS3 assigned its MAC addresses so that the top 4 bytes are unique between devices.

In my project, GNS3 has used MAC addresses of the form `0[0c]:9a:20:XX:YY:00`. It seems other projects use different prefixes, which makes sense - you want to be able to run two projects simultaneously and have a low risk of collision.

**Comment by grossmj** [comment]
Excellent, we are going to change this for the next release :+1:

**Comment by grossmj** [comment]
> I think it would be better if GNS3 assigned its MAC addresses so that the top 4 bytes are unique between devices.

I checked and here is what we have to generate a device MAC address
 
https://github.com/GNS3/gns3-server/blob/2.2/gns3server/compute/qemu/qemu_vm.py#L618

First byte is always `0c`, second and third are generated based on the project UUID and the fourth and fifth bytes are based on the node UUID.

Do you have any suggestion how to generate MAC addresses?

**Comment by candlerb** [comment]
Questions/thoughts:

1. Is there any code in GNS3 which checks that the node UUIDs are unique in the low 16 bits, and ditto for project UUIDs?  Or does GNS3 just rely on a low probability of collision?

    With 2<sup>16</sup> available node MAC addresses in a project, the "[birthday paradox](https://en.wikipedia.org/wiki/Birthday_problem)" says that you only need 2<sup>8</sup> nodes to have a ~50% probability of at least one collision.  That's a large project, but certainly realistic.

    An ideal algorithm would allocate a different MAC address if the chosen one collides with one already within the project.  However the existing code doesn't seem to have enough visibility of the global project state to be able to do that.

2. I think that collisions *between* projects are less important than collisions *within* a project: not everyone runs multiple projects concurrently, and even if you do, you're unlikely to bridge them together at layer 2.

3. As I understand it, the [first byte of a MAC address](https://en.wikipedia.org/wiki/Organizationally_unique_identifier#Format) is: `x x x x` `x x U/L I/G`

    U/L = Universal (0) or Local (1)
    I/G = Individual (0) or Group (1), i.e. multicast

    I believe the U/L bit should be set to 1 for locally assigned IDs (as libvirt does, with "52"). Choosing "0c" potentially clashes with universal addresses: for example, 0C:02:BD is allocated to Samsung and 0C:11:67 is allocated to Cisco.

With those in mind, here are my suggestions.

### Proposal 1: simplest / minimum change

* Take first and second bytes from the project ID, and third and fourth bytes from the node ID. Fifth and sixth are zero.
* In the first byte, ensure the lowest two bits are `10` (by ORing with 0x02 and ANDing with 0xfe)

This behaves more or less the same as today, in terms of likelihood of collision.  All MAC addresses for a project share the same 2-byte prefix.

However you still have a significant collision probability within a project, unless GNS3 is also ensuring that node UUIDs within a project are unique in the lowest 16 bits.

### Proposal 2: lower collision rate and GNS3 prefix

* Take the first byte as a fixed value for GNS3, e.g. `3d`
* Take the second, third and fourth bytes from the node UUID
* Don't use the project UUID at all!

You now need around 2<sup>12</sup> nodes in a project before there's a reasonable chance of a MAC address conflict.  (There's also a chance of MAC address conflicts *between* projects, but we care less about that; and in any case you'd need a large shared layer 2 domain between projects before it became significant)

All MAC addresses in your network which derive from GNS3 are easily recognisable from the first byte.  MAC addresses within a project no longer share a common prefix, but I think that's a small loss.

I like this approach.

### Proposal 3: zero collision

* Allocate MAC address as per either proposal 1 or proposal 2
* Check that no other node in the same project has the same prefix
* If there is, keep incrementing the MAC address until there is no collision

This is the safest approach, but needs more work in GNS3 core to implement.

**Comment by candlerb** [comment]
I remembered to check one other thing: there are different algorithms for creating uuids, and not all are random.  However the code uses `uuid.uuid4`, and in algorithm 4, all apart from the top few bits are [pseudo-random](https://datatracker.ietf.org/doc/html/rfc4122.html#section-4.4).  So that's fine.

**Comment by grossmj** [comment]
Wow, thanks so much for this detailed post. Love it :+1:

> GNS3 just rely on a low probability of collision?

Yes it does, the MAC address allocation is done on the compute level and without checking what has already been allocated. To ensure no collision when having multiple computes, this would have to be done on by the controller instead (this is your proposal 3).

I think the best is the zero collision option but it would have to be done in version >= 3.0 but I haven't checked how complex this could be to do.  In the meantime, we could implement proposal 2 for version 2.2

**Comment by candlerb** [comment]
Sounds good to me, and it's a one-line change to the code you referenced previously.

**Comment by grossmj** [comment]
PR https://github.com/GNS3/gns3-server/pull/1932 opened. Please let me know if I missed anything. Thanks :+1:
