### ISSUE TITLE
Dynamips TypeError: async() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#193]
https://app.getsentry.com/gns3/gns3-server/group/65878062/

```
TypeError: async() takes 1 positional argument but 3 were given
(2 additional frame(s) were not displayed)
...
  File "./gns3-server\gns3server\modules\dynamips\__init__.py", line 385, in create_nio
  File "./gns3-server\gns3server\utils\interfaces.py", line 67, in get_windows_interfaces
  File "C:\Python34-64bit\lib\site-packages\win32com\client\dynamic.py", line 247, in __getitem__
  File "C:\Python34-64bit\lib\site-packages\win32com\client\util.py", line 37, in __getitem__
  File "C:\Python34-64bit\lib\site-packages\win32com\client\util.py", line 53, in __GetIndex
```

**Comment by grossmj** [comment]
Similar issue: https://app.getsentry.com/gns3/gns3-server/group/66651640/

**Comment by grossmj** [comment]
We suspect an implementation problem in Python3 with asyncio and the Proactor event loop on Windows. We will test with newer versions of Python to see either this is fixed or we get more details.

**Comment by grossmj** [comment]
Maybe there is an incompatibility with win32com module. We should try to run this code in an executor for instance.

**Comment by grossmj** [comment]
Actually we have the same error in other places. I hope Python 3.5 will solve the problem.

**Comment by noplay** [comment]
Ok I move the issue to 1.4 we will not change a Python version for 1.3

**Comment by grossmj** [comment]
Still waiting for PyQt guys to release a version that supports Python 3.5 on Windows.

**Comment by noplay** [comment]
Planned for Qt 5.6 :(

**Comment by grossmj** [comment]
Qt 5.6 is schedule for March 1st.

**Comment by noplay** [comment]
So two month to wait for pyqt :(

**Comment by cioby23** [comment]
PyQt 5.6 released :)
https://www.riverbankcomputing.com/news/pyqt-56

**Comment by noplay** [comment]
Yeah and we build with it let's close this finally :)  We will reopen if we get new crash report

**Comment by grossmj** [comment]
Hopefully Python 3.5 fixes this otherwise no idea what would fix that.
