### ISSUE TITLE
GNS3: Internal server error while starting Tiny core linux 

### ISSUE THREAD

**Issue by cece89** [GNS3/gns3-server#1936]
Hello everyone, 

I get this error in GNS3's console when i'm trying to load TinyCore pLus from GNS3: "Internal server error http://localhost:3080/v2/compute/projects/7414ab1e-9273-42f3-b531-e983ce824cbe/vmware/nodes/38d8aa3d-1da4-462e-b202-af2c41bc1691/start".
GNS3 VM has been loading without issue in gns3. But impossible to start tinyCore from gns3. But when Tiny Core is running on vmware and i start to run it from gns3 interface, GNS3 prompt me that the virtual machine is already running.

I need your help please. I'm using GNS3 2.2.22 and tinycore plus with vmware workstation pro 12.5.9.

**Comment by cece89** [comment]
I've just read that the issue is from this version of gns3, i mean 2.2.22 so i'm downloading the 2.2.8 version and comes back to you

**Comment by grossmj** [comment]
@cece89 anything new?

**Comment by cece89** [comment]
The issue is solved after GNS 2.1.21 installation. Thanks very much!

**Comment by vannelamou-dev** [comment]
J'ai rencontré le même problème.

<img width="501" height="138" alt="Image" src="https://github.com/user-attachments/assets/63630ec1-7bce-43d4-bf34-5cd3f4df0fc9" />

Voici les étapes pour résoudre :
- aller dans help - GNS3 Doctor.

<img width="548" height="249" alt="Image" src="https://github.com/user-attachments/assets/ce1a0279-402e-48ce-b75a-27f44cba9e5d" />

- Une vérification de GNS 3 va être lancée pour vérifier si tout fonctionne correctement
- chez moi il y'avait un problème avec npcap qui n'était pas installé, je suis juste allé sur le site officiel et je l'ai installé

<img width="607" height="420" alt="Image" src="https://github.com/user-attachments/assets/ffd50016-709b-4a71-95db-991af4ec9ed9" />

- Ensuite je suis revenu faire le diagnostic avec GNS Doctor et il n'y avait pas plus de problème.

<img width="608" height="424" alt="Image" src="https://github.com/user-attachments/assets/2aa699d0-1bf1-417a-8f00-cf2eebe7c8e6" />
