### ISSUE TITLE
Could not validate qcow2 image

### ISSUE THREAD

**Issue by smart2128** [GNS3/gns3-server#1946]
Hi,
I left a working lab with 4 different qcow2 images a week ago.
Coming back home, I updated Arch packages and started again the lab, receiving the following error:

Could not use qcow2 disk image 'XXXXXX' for hda: Could not validate the image

I tried downgrading GNS3 (2.2.24 -> 2.2.23) and QEMU (6.1.0 -> 6.0.0), but I'm still getting the same error

Please, could you give any hint in order to fix the issue?

Thank you in advance,
Vincenzo

**Comment by smart2128** [comment]
I found the issue.
There was a problem with backing file's path.

**Comment by grossmj** [comment]
> There was a problem with backing file's path.

Ok no worries. The "Could not validate the image" message indicates that the file format could not be recognised. Qcow2 files for instance must start with a 'magic' header.

**Comment by aldysaputratanjung** [comment]
i also get the same problem

**Comment by aldysaputratanjung** [comment]
what's the solution

**Comment by Ventresca68** [comment]
Same here with Ubuntu 20.04.3 LTS and GNS3 binaries from gns3-ubuntu-ppa-bionic.
On a working gns3 (same software, different host hardware) I exported a project and imported it on another server.
On the second GNS3 host I get the error when starting the image.
If I start it manually with: qemu-system-x86_64 -hda switch_image.qcow2, it runs with no issues.

**Comment by grossmj** [comment]
@Ventresca68 we fixed the issue, please upgrade to GNS3 v2.2.25.

**Comment by Ventresca68** [comment]
@grossmj  Updated now, all work fine! Many Thanks! :)
