### ISSUE TITLE
Disk usage only reported for root partition

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1947]
![disk_usage](https://user-images.githubusercontent.com/4752614/131612434-d40c1d80-e722-49d2-ba35-1a50fa9fb8ae.png)

```
Filesystem     1K-blocks      Used Available Use% Mounted on
udev            98989432         0  98989432   0% /dev
tmpfs           19806996      1748  19805248   1% /run
/dev/sda2       41022688  13885844  25023308  36% /
tmpfs           99034976         0  99034976   0% /dev/shm
tmpfs               5120         0      5120   0% /run/lock
tmpfs           99034976         0  99034976   0% /sys/fs/cgroup
/dev/sda3      438352408 416015640         0 100% /opt
/dev/loop0         56832     56832         0 100% /snap/core18/2074
/dev/loop1         56832     56832         0 100% /snap/core18/2128
/dev/loop3         69248     69248         0 100% /snap/lxd/20326
/dev/loop5         33152     33152         0 100% /snap/snapd/12704
/dev/loop4         72064     72064         0 100% /snap/lxd/21029
/dev/loop6         33152     33152         0 100% /snap/snapd/12883
tmpfs           19806992         0  19806992   0% /run/user/1000
```

`/opt` is full which prevents users to save their projects.

This is because we currently use https://psutil.readthedocs.io/en/latest/#psutil.disk_usage with '/' 

https://github.com/GNS3/gns3-server/blob/4e61cc811e3847331f112a572689aaba2f703c01/gns3server/handlers/api/compute/server_handler.py#L64

So this issue is expected, fortunately psutil recently added https://psutil.readthedocs.io/en/latest/#psutil.disk_partitions which should allow us to return the disk usage for all partitions.

**Comment by grossmj** [comment]
After thinking a bit more about this, for security purposes, is it desirable to report the disk usage of all partitions? Maybe limiting to the partition that contains the GNS3 projects would be a solution?

**Comment by lurendrejer** [comment]
I'd go for ALL to begin with, maybe the ability to change this via gns3_server.cfg down the line.

I'm testing a few things regarding the /projects -folder and might end up putting it on a dedicated partition alltogether.

**Comment by grossmj** [comment]
> I'd go for ALL to begin with, maybe the ability to change this via gns3_server.cfg down the line.

This would be similar to what we do for the host network interfaces. By default we list everything but this can be restricted by configuring `allowed_interfaces` in https://github.com/GNS3/gns3-server/blob/2.2/conf/gns3_server.conf#L56 👍

**Comment by lurendrejer** [comment]
> > I'd go for ALL to begin with, maybe the ability to change this via gns3_server.cfg down the line.
> 
> This would be similar to what we do for the host network interfaces. By default we list everything but this can be restricted by configuring `allowed_interfaces` in https://github.com/GNS3/gns3-server/blob/2.2/conf/gns3_server.conf#L56 👍

Yup - I have about a thousand suggestions to what I would like to hide/limit in the conf-file already - I'm looking forward to the 3.0 releases :)

**Comment by grossmj** [comment]
> Yup - I have about a thousand suggestions to what I would like to hide/limit in the conf-file already - I'm looking forward to the 3.0 releases :)

Looks like this is the opportunity to try the new GitHub discussions: https://github.com/GNS3/gns3-server/discussions/1948 Feel free to add your suggestions there 👍 Thanks

**Comment by grossmj** [comment]
Should we show disk usage for physical devices only (e.g. hard disks, cd-rom drives, USB keys) and ignore all others (e.g. pseudo, memory, duplicate, inaccessible filesystems)?

This is the choice we have using psutil https://psutil.readthedocs.io/en/latest/#psutil.disk_partitions

**Comment by lurendrejer** [comment]
> Should we show disk usage for physical devices only (e.g. hard disks, cd-rom drives, USB keys) and ignore all others (e.g. pseudo, memory, duplicate, inaccessible filesystems)?
> 
> This is the choice we have using psutil https://psutil.readthedocs.io/en/latest/#psutil.disk_partitions

Servers have all sorts of stupid built in flash devices that serves no purpose in such a list.
I'd say, go for what you are doing in your example.
I am not an expert on graphical interfaces - but keeping things simple must be an important part of it. (just look at Cisco VIRL 1.x)

**Comment by grossmj** [comment]
In v2, the server will report the disk usage for the partition that contains the default project directory as specified in server.conf (projects_path setting or ~/GNS3/projects if not set)

We will add detailed disk usage info in v3 instead.

**Comment by grossmj** [comment]
This will be implemented by https://github.com/GNS3/gns3-server/issues/1954
