### ISSUE TITLE
qemu-img: warning: Deprecated use of backing file without explicit backing format

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#1964]
Hi

On Debian Buster, i have theses warnings in "qemu-img.log"

```
qemu-img: warning: Deprecated use of backing file without explicit backing format (detected format of qcow2)
Formatting '/home/user/projects/untitled/project-files/qemu/4751eff8-7515-48a2-bcc0-a298771cd77d/hda_disk.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=2147483648 backing_file=/opt/raizo/user/OS/QEMU/vios_l2-adventerprisek9-m.SSA.high_iron_20180619.qcow2 backing_fmt=qcow2 lazy_refcounts=off refcount_bits=16
```

or

```
qemu-img: warning: Deprecated use of backing file without explicit backing format (detected format of raw)
Formatting '/home/user/projects/untitled/project-files/qemu/bbeabedd-9ca3-4710-b592-af8afbc9d1a5/hda_disk.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=4294967296 backing_file=/opt/raizo/user/OS/QEMU/VM-Raizo.raw lazy_refcounts=off refcount_bits=16
```

**Comment by grossmj** [comment]
Fixed

**Comment by bkaczynski** [comment]
Can I fix it by myself at my installation?

**Comment by andrej-korshikov** [comment]
@bkaczynski I've edited just one line in the `qemu_vm.py` file, on my platform it's in the `GNS3/lib/python3.9/site-packages/gns3server/compute/qemu` folder.
Line 1683 (after edit):
`command = [qemu_img_path, "create", "-o", "backing_file={}".format(disk_image), "-f", "qcow2", "-F", "qcow2", disk]`
See that `"-F", "qcow2",`? It makes the trick.

**Comment by asmkaiser** [comment]
> @bkaczynski I've edited just one line in the `qemu_vm.py` file, on my platform it's in the `GNS3/lib/python3.9/site-packages/gns3server/compute/qemu` folder. Line 1683 (after edit): `command = [qemu_img_path, "create", "-o", "backing_file={}".format(disk_image), "-f", "qcow2", "-F", "qcow2", disk]` See that `"-F", "qcow2",`? It makes the trick. I should warn you, all my images are `qcow2`, so it's quite safe for me to hardcode the type. Your mileage, as usual, may vary.

Thanks man , you saved my 4$$ .

However I am getting this error "Backing file specified without backing format" while running the VM
