### ISSUE TITLE
Integrated Affinity symbol set is outdated (missed 14 new icons, no green and naked icons)

### ISSUE THREAD

**Issue by andrej-korshikov** [GNS3/gns3-server#1968]
**GNS3 version and operating system:**
 - OS: `Arch Linux` (Linux laptop 5.13.13-zen1-1-zen # 1 ZEN SMP PREEMPT Thu, 26 Aug 2021 19:14:35 +0000 x86_64 GNU/Linux)
 - GNS3 version `2.2.24`
 - no GNS3 VM or remote server

**To Reproduce**
1. Look at sub-directories of `gns3server/symbols/affinity`. There are 50 files in each one.
2. Look at https://github.com/ecceman/affinity. There are 64 symbols in each variant (except naked). For example, there is new `router2` icon (old symbol is like `+`, and new one is like `X`). And there are green and naked variants (naked symbols don't have borders around them).

**Comment by grossmj** [comment]
I have updated the symbols in https://github.com/GNS3/gns3-server/pull/1967 and I have chosen to use https://github.com/svg/svgo to optimize them instead of inkscape.

**Comment by andrej-korshikov** [comment]
@grossmj What do you think about "naked" symbols? Do you think they are useless in GNS3?

**Comment by grossmj** [comment]
> What do you think about "naked" symbols? Do you think they are useless in GNS3?

They are harder to resize and yes I don't think they are useful in GNS3.

**Comment by grossmj** [comment]
PR merged. I think I haven't missed anything, if so please let me know.
