### ISSUE TITLE
GNS3 server segfault on OSX

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#197]
https://community.gns3.com/thread/8632?et=notification.send

**Comment by noplay** [comment]
It seem related to the allow any host option

**Comment by noplay** [comment]
This crash everytime:
```
/Applications/GNS3.app/Contents/Resources/server/Contents/MacOS/gns3server" --host 192.168.84.120 --port 8000 --local --allow
```

**Comment by grossmj** [comment]
This reminds me that we have not tested that option since 1.2.3...

**Comment by noplay** [comment]
It seem a bug inside py2app argv_emulation options.

When command line it too long it's segfault :(

**Comment by grossmj** [comment]
Way to suck Py2app....

**Comment by noplay** [comment]
Ok it's the number of argument the issue... If we drop one it's work
