### ISSUE TITLE
Not able to make a link because "ports used up" 

### ISSUE THREAD

**Issue by chunji08** [GNS3/gns3-server#1973]
Hi there, 
I have created a GNS3 project on AWS EC2 that is of such picture:   Cloud() -> Cisco C7200 router -> multiple layer of Ethernet Switches -> hundreds of VM nodes. These networked nodes will be used in my separate project. 

But today, when  I was to add an extra end node, and try to have switch linked to that node, I have received a failure. 

This is my API call to make that link: 

**curl -s -X POST http://172.16.253.1:3080/v2/projects/935e2f61-eed3-4e17-9d64-110284d01727/links -d4c91-8044-8d69bb46ab5f", "port_number": 3},{"adapter_number": 0, "node_id": "333829ea-5095-4d04-8f09**

And this is the response I received: 
**{
    "message": "Could not find a free port between 20000 and 30000 on host 0.0.0.0, last exception: None
    "status": 409
}**

I guess it has reached some ceiling as it said no more free port.  Does anyone know if there is a way to work around to bypass this ? 

My GNS3 is of version 2.2.24. 

Thanks, 

Jack

**Comment by grossmj** [comment]
@chunji08 Indeed, looks like you used all the available ports in the default range.

To change the default port range, edit the GNS3 server config file which is located by default in `~/.config/GNS3/2.2/gns3_server.conf` and add the following:

```
; First port of the range allocated for inter-device communication. Two ports are allocated per link.
udp_start_port_range = 20000
; Last port of the range allocated for inter-device communication. Two ports are allocated per link
udp_end_port_range = 30000
```

**Comment by chunji08** [comment]
Hi grossmj, 
Thanks for the tips.  

In my environment, I have located the gns3_server.conf file in this dir: 
> gns3@gns3vm:/etc/gns3$ ls -l /etc/gns3/
> total 8
> -rw-r--r-- 1 gns3 gns3 3492 Aug 26 18:29 gns3_controller.conf
> -rwx------ 1 gns3 gns3  339 Sep 15 17:42 **gns3_server.conf**
> 

And have made such changes in the **gns3_server.conf** file: 

> gns3@gns3vm:/etc/gns3$ more gns3_server.conf
> [Server]
> host = 172.16.253.1
> port = 3080
> images_path = /opt/gns3/images
> projects_path = /opt/gns3/projects
> appliances_path = /opt/gns3/appliances
> configs_path = /opt/gns3/configs
> report_errors = True
> ; First port of the range allocated for inter-device communication. Two ports are allocated per link.
> **udp_start_port_range = 20000**
> ; Last port of the range allocated for inter-device communication. Two ports are allocated per link
> **udp_end_port_range = 40000**
> 
> 
> [Qemu]
> enable_hardware_acceleration = True
> require_hardware_acceleration = True
> 

After that done, what else should I do to have it taking into effect in an open project ? 

Thanks, 

Chun Ji

**Comment by grossmj** [comment]
> After that done, what else should I do to have it taking into effect in an open project ?

It should work after you reload the project or the server.

**Comment by grossmj** [comment]
@chunji08 do you still have the problem?

**Comment by chunji08** [comment]
I still can not make it working.  

I have my PC rebooted => Have made the OVPN connection which is pointing to the EC2 Host => Have started the GNS3 process on my PC, which is of version 2.2.24 => Was able  to locate my existing project in GNS3 UI,  which is built on EC2=> try to create an extra link between the switch and my end port, but it still fails as it is showing starting and ending ports are between 20000 and 30000.  

![image](https://user-images.githubusercontent.com/11307533/134042713-0d677660-4337-406b-b4b6-571812a8d1f1.png)

To me, it is as if my updated gns3_server.conf is not being used during the runtime. 

Thanks, 

Chun Ji

**Comment by grossmj** [comment]
Indeed, looks like the server hasn't loaded the config file, you should see something like this when you manually start the server

```
$ python3 -m gns3server
2021-09-22 17:06:21 INFO run.py:219 GNS3 server version 2.2.26dev1-5ece4850
2021-09-22 17:06:21 INFO run.py:221 Copyright (c) 2007-2021 GNS3 Technologies Inc.
2021-09-22 17:06:21 INFO run.py:224 Config file /home/me/.config/GNS3/2.2/gns3_server.conf loaded
2021-09-22 17:06:21 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2021-09-22 17:06:21 INFO run.py:243 Running with Python 3.8.10 and has PID 22852
```

Try to check if the config is in `~/.config/GNS3/2.2`

**Comment by chunji08** [comment]
Hi Jeremy, 
It seems your gns3 environment is quite different, comparing to mine. 

Here are the details. 
1) After my clean-installation of GNS3 VM, here is some piece of hierarchy of my gns3 VM host when I log in. 
```
gns3@gns3vm:/opt$ tree -a -L 4 gns3
gns3
├── .bash_history
├── .bash_logout
├── .bashrc
├── .config
│   ├── GNS3
│   │   └── 2.2
│   └── htop
│       └── htoprc
├── .emacs.d
│   └── auto-save-list
├── .profile
├── GNS3
│   └── symbols
│       └── E2.png
├── appliances
├── configs
│   ├── ios_base_startup-config.txt
│   ├── ios_etherswitch_startup-config.txt
│   ├── iou_l2_base_startup-config.txt
│   ├── iou_l3_base_startup-config.txt
│   └── vpcs_base_config.txt
├── images
│   ├── IOS
│   │   ├── c7200-advipservicesk9-mz.152-4.S5.image
│   │   └── c7200-advipservicesk9-mz.152-4.S5.image.md5sum
│   └── QEMU
│       ├── FEXT-200F
│       │   └── image-esx-64
│       ├── config.img
│       └── config.img.md5sum
└── projects
    ├── 236781dc-f74c-48db-8d33-d947a2d66bbd
    │   ├── project-files
    │   │   └── images
    │   └── untitled.gns3
    └── 935e2f61-eed3-4e17-9d64-110284d01727
        ├── Pro-2.2.24.gns3
        └── project-files
            ├── builtin
            ├── dynamips
            ├── images
            └── qemu

```

and : 
```
gns3@gns3vm:/etc$ tree -a -L 4 gns3
gns3
├── gns3_controller.conf
└── gns3_server.conf

```
As you can see, the directory of /opt/gns3/.config/GNS3/2.2/  is totally empty, and the gns3_server.conf is located under /etc/gns3. 

2) Now When I started my GNS3 project, I have hit this 20000 ~ 30000 port range restriction. 

3) After I have the "/etc/gns3/gns3_server.conf" updated with the customized setting, the issue stays, 

4) Then I purposely copied the gns3_server.conf file to this dir: /opt/gns3/.config/GNS3/2.2/..,  I still receive this error message. 

Are you sure the GNS3 is referring to the settings in a gns3_server.conf  file during the runtime? How did it get the 20000/30000 range at first place, or it is hard code ? 

Thanks, 

Chun Ji

**Comment by grossmj** [comment]
In the GNS3 VM, the location of the file should be `/home/gns3/.config/GNS3/2.2/gns3_server.conf`

![Screenshot from 2021-10-07 14-53-06](https://user-images.githubusercontent.com/4752614/136320072-886ec8de-d73f-4231-8152-3dce9806da74.png)

This is where you need to add:

```
udp_start_port_range = 20000
udp_end_port_range = 40000
```
