### ISSUE TITLE
Python pip installed GNS3 Server Doesn't Find QEMU Binary

### ISSUE THREAD

**Issue by abotelho-cbn** [GNS3/gns3-server#1974]
Server OS: AlmaLinux 8
Client OS: Fedora 34
Python version: 3.9

Dedicated gns3 user created. Added gns3 user to qemu and kvm groups.

Here is the server config:
```
[root@gns3host1 2.2]# cat gns3_server.conf 
[Server]
; IP where the server listen for connection
host = 10.20.8.31
; HTTP port for controlling the servers
port = 8443
; Path where images of devices are stored
images_path = /home/gns3/GNS3/images
; Path where user project are stored
projects_path = /home/gns3/GNS3/projects
; Send crash to the GNS3 team
report_errors = True
; First port of the range allocated to devices telnet console
console_start_port_range = 2001
; Last port of the range allocated to devices telnet console
console_end_port_range = 5000
; First port of the range allocated to communication between devices. You need two port by link
udp_start_port_range = 10000
; Last port of the range allocated to communication between devices. You need two port by link
udp_end_port_range = 20000
; Boolean for enabling HTTP auth
auth = True
; Username for HTTP auth
user = gns3
; Password for HTTP auth
password = gns3

[Qemu]
enable_kvm = True
; Require KVM to be installed in order to start VMs (Linux only, has priority over require_hardware_acceleration)
require_kvm = True
; Enable hardware acceleration (all platforms)
enable_hardware_acceleration = True
; Require hardware acceleration in order to start VMs (all platforms)
require_hardware_acceleration = False
```
Here is the issue I see on the client side:
![image](https://user-images.githubusercontent.com/81174902/133465187-6f751e4a-f8c1-4bbf-aedc-4160e9659e4f.png)

Is there an environment variable or symlink I can set? How does GNS3 detect the QEMU binary to begin with?

**Comment by abotelho-cbn** [comment]
It looks like GNS3 just isn't looking in the right spot on EL-based distros.

I had to create a symlink, specifically
`ln -s /usr/libexec/qemu-kvm /usr/bin/qemu-kvm`
for it to recognize QEMU was installed at all.

Possible patch? Realistically GNS3 should only have to look in /usr/libexec as well as the currently configured /usr/bin. This would go a long away in helping people get AlmaLinux/Rocky Linux/CentOS going using the pip package.

**Comment by grossmj** [comment]
> It looks like GNS3 just isn't looking in the right spot on EL-based distros.

GNS3 looks for Qemu using the PATH environment variable. Is `/usr/libexec` in there?

**Comment by abotelho-cbn** [comment]
That makes sense.

`[gns3@gns3host1 ~]$ env | grep PATH
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin`
It doesn't appear so. I don't have access to an Ubuntu machine at the moment. Would you happen to know if /usr/libexec is in the default Ubuntu PATH?

**Comment by grossmj** [comment]
> Would you happen to know if /usr/libexec is in the default Ubuntu PATH?

Not on my Ubuntu 20.04

**Comment by grossmj** [comment]
`/usr/libexec` includes internal binaries that are not intended to be executed directly by users or shell scripts, I think this is the reason why it is not included in PATH.

Not sure if it is up to the users or the package to add a symlink to `/usr/libexec/qemu-kvm` or if we should check for it on our side...
