### ISSUE TITLE
Create read-only API to get server configuration

### ISSUE THREAD

**Issue by fadlytabrani** [GNS3/gns3-server#1976]
Can you add an API endpoint to expose the server configuration settings? 

I'm trying to discover the configuration settings of a server mainly what has been declared in /etc/gns3/gns_server.conf

[```
Server]
host = 0.0.0.0
port = 3080
images_path = /mnt/nvme0n1p1/gns3_images
projects_path = /mnt/nvme0n1p1/gns3_projects
appliances_path = /opt/gns3/appliances
configs_path = /opt/gns3/configs
report_errors = False
allowed_interfaces = virbr0
```

**Comment by grossmj** [comment]
> Can you add an API endpoint to expose the server configuration settings?

I am afraid this isn't very secure to expose the server config in the API, this would be fine for 2.2.x but not for 3.0 which will be a lot more secure.
