### ISSUE TITLE
Docker container with Ubuntu stops immediately after starting in GNS3 (Version 2.2.29) 

### ISSUE THREAD

**Issue by balajig** [GNS3/gns3-server#2001]
Ubuntu Docker container stops immediately after starting in GNS3. The issue is seen with GNS3 Version 2.2.27. The same docker container works if its run without GNS3. 

This is similar to what has been reported earlier 

https://gns3.com/community/featured/gns3-1-5-4-ubuntu-container-stop

The above link does not work either and it does not seem to be that the issue is fixed in the recent releases.

**Comment by grossmj** [comment]
Do you see any error message in GNS3?

**Comment by balajig** [comment]
No. I dont see any error.  When i try to open the console or Auxillary console, the window immediately closes

**Comment by grossmj** [comment]
Which Ubuntu image do you use?

**Comment by balajig** [comment]
I tried with Ubuntu 20.04. On top of this image, i have FRR running.

**Comment by balajig** [comment]
On looking @ the docker logs i see the following 

docker logs 288d3ece9899
su: unknown user frr:frr

The docker container when executed separately works fine. But the same docker container stops immediately after starting. The above mentioned error is seen when i tried starting it from inside gns3

The docker image is built using the Dockerfile in the below path 

https://github.com/FRRouting/frr/blob/master/docker/ubuntu20-ci/Dockerfile

Kindly let me know if anything more is required. I would be more than happy to provide the same

**Comment by bijouben05** [comment]
> I tried with Ubuntu 20.04. On top of this image, i have FRR running. FRR has Dockerfiles for building Ubuntu and Debian. Debian 10 works fine . Ubuntu has this issue. The same Ubuntu image when started with normal docker (without GNS), works fine and i am able to launch multiple instances too.

I have the same issue, the docker image works fine on ubuntu but shutdown right after starting on GNS3....!!!

**Comment by balajig** [comment]
Thanks @bijouben05 for your reply. With the existing Debian 10 DockerFile which is supplied with FRR, i can run the daemons using apt-get but if i have to run my build of FRR, i am not able to do it. Do you have a DockerFile where in you are able to compile FRR and load that in Debian 10. Do you mind sharing it please in case if you have. Thanks
