### ISSUE TITLE
gns-server-2.2.27: tests fails - test_docker_vm.py::test_stop[pyloop] - AssertionError: assert False

### ISSUE THREAD

**Issue by mm1ke** [GNS3/gns3-server#2003]
Hi,

With version 2.2.27 one of the test is failing for me. 2.2.26 works still fine:
The output from the test looks as following:

_____________________________________________________________ test_stop[pyloop] _____________________________________________________________

vm = <gns3server.compute.docker.docker_vm.DockerVM object at 0x7f6a577f7340>

    async def test_stop(vm):
    
        mock = MagicMock()
        vm._ubridge_hypervisor = mock
        vm._ubridge_hypervisor.is_running.return_value = True
        vm._fix_permissions = MagicMock()
    
        with asyncio_patch("gns3server.compute.docker.DockerVM._get_container_state", return_value="running"):
            with asyncio_patch("gns3server.compute.docker.Docker.query") as mock_query:
                await vm.stop()
                mock_query.assert_called_with("POST", "containers/e90e34656842/stop", params={"t": 5})
        assert mock.stop.called
        assert vm._ubridge_hypervisor is None
>       assert vm._fix_permissions.called
E       AssertionError: assert False
E        +  where False = <MagicMock id='140094714046640'>.called
E        +    where <MagicMock id='140094714046640'> = <gns3server.compute.docker.docker_vm.DockerVM object at 0x7f6a577f7340>._fix_permissions

tests/compute/docker/test_docker_vm.py:959: AssertionError
------------------------------------------------------------ Captured log setup -------------------------------------------------------------
WARNING  gns3server.config:config.py:228 No configuration file could be found or read
DEBUG    gns3server.compute.port_manager:port_manager.py:51 Console port range is 5000-10000
DEBUG    gns3server.compute.port_manager:port_manager.py:56 UDP port range is 20000-30000
DEBUG    asyncio:selector_events.py:59 Using selector: EpollSelector
DEBUG    gns3server.compute.port_manager:port_manager.py:215 TCP port 5000 has been allocated
DEBUG    gns3server.compute.port_manager:port_manager.py:215 TCP port 5001 has been allocated
DEBUG    gns3server.compute.base_node:base_node.py:118 Docker: test [ce0f5a62-387b-4f72-aeb7-a2e5b4dff3fb] initialized. Console port 5000
INFO     gns3server.compute.docker.docker_vm:docker_vm.py:1058 Docker container "test" [ce0f5a62-387b-4f72-aeb7-a2e5b4dff3fb]: number of Ethernet adapters changed to 1
DEBUG    gns3server.compute.docker.docker_vm:docker_vm.py:110 Docker: test [ubuntu:latest] initialized.
------------------------------------------------------------- Captured log call -------------------------------------------------------------
INFO     gns3server.compute.base_node:base_node.py:669 Stopping uBridge hypervisor <MagicMock name='mock.host' id='140094712253504'>:<MagicMock name='mock.port' id='140094712285984'>
INFO     gns3server.compute.docker.docker_vm:docker_vm.py:793 Docker container 'test' [ubuntu:latest] stopped
============================================================= warnings summary ==============================================================
gns3server/utils/__init__.py:63
  /mnt/data/tmp/gns3-server-2.2.27/gns3server/utils/__init__.py:63: DeprecationWarning: invalid escape sequence \.
    version_infos = re.split('(\.|[a-z]+)', version)

gns3server/utils/interfaces.py:49
  /mnt/data/tmp/gns3-server-2.2.27/gns3server/utils/interfaces.py:49: DeprecationWarning: invalid escape sequence \{
    connection = r"SYSTEM\CurrentControlSet\Control\Network\{4D36E972-E325-11CE-BFC1-08002BE10318}" + "\{}\Connection".format(guid)

gns3server/utils/interfaces.py:95
  /mnt/data/tmp/gns3-server-2.2.27/gns3server/utils/interfaces.py:95: DeprecationWarning: invalid escape sequence \c
    service = locator.ConnectServer(".", "root\cimv2")

gns3server/compute/qemu/__init__.py:221
  /mnt/data/tmp/gns3-server-2.2.27/gns3server/compute/qemu/__init__.py:221: DeprecationWarning: invalid escape sequence \s
    match = re.search("version\s+([0-9a-z\-\.]+)", output)

gns3server/compute/vmware/__init__.py:700
  /mnt/data/tmp/gns3-server-2.2.27/gns3server/compute/vmware/__init__.py:700: DeprecationWarning: invalid escape sequence \M
    return ['{}\My Virtual Machines'.format(documents_folder), '{}\Virtual Machines'.format(documents_folder)]

gns3server/compute/vmware/__init__.py:700
  /mnt/data/tmp/gns3-server-2.2.27/gns3server/compute/vmware/__init__.py:700: DeprecationWarning: invalid escape sequence \V
    return ['{}\My Virtual Machines'.format(documents_folder), '{}\Virtual Machines'.format(documents_folder)]

gns3server/web/route.py:167: 349 warnings
  /mnt/data/tmp/gns3-server-2.2.27/gns3server/web/route.py:167: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    func = asyncio.coroutine(func)

../../../../usr/lib/python3.9/site-packages/_pytest/config/__init__.py:1233
  /usr/lib/python3.9/site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: ignore
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

tests/controller/test_export_project.py::test_export_with_ignoring_snapshots[pyloop]
  /usr/lib/python3.9/site-packages/aiohttp/test_utils.py:560: RuntimeWarning: coroutine 'AsyncioBytesIO.close' was never awaited
    gc.collect()

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================== short test summary info ==========================================================
FAILED tests/compute/docker/test_docker_vm.py::test_stop[pyloop] - AssertionError: assert False
========================================== 1 failed, 879 passed, 357 warnings in 162.67s (0:02:42) ==========================================

**Comment by grossmj** [comment]
Fixed, thanks 👍
