### ISSUE TITLE
No package metadata was found for gns3-server

### ISSUE THREAD

**Issue by taostart** [GNS3/gns3-server#2004]
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 33, in <module>
    sys.exit(load_entry_point('gns3-server==2.2.27', 'console_scripts', 'gns3server')())
  File "/usr/bin/gns3server", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gns3-server

**Comment by taostart** [comment]
This doesn't look like a dependency issue

**Comment by grossmj** [comment]
How have you installed gns3server?

**Comment by toro-** [comment]
I had the same issue with GNS3 version 2.2.28 (installed from AUR on Manjaro). 

I had just done an system update (which included a Kernel bump) and the issue began happening. Restarted machine to ensure that latest kernel was loaded and that GNS3 wasn't looking for something there.

Message changed after the reboot to say that basically [sdk](https://pypi.org/project/sentry-sdk/) was missing. Tried to install that via pip but pip was not found either (strangely as I had been using it a few short days ago).

Eventually managed to get that "installed" by doing "python -m ensure pip --upgrade". pip still would not run from command line, so did "python -m pip install sentry-sdk" at which point the package was installed, but complained that pip was not up to date. Did "python -m pip install --upgrade pip" to fix that.

GNS3 server now runs without issue.

Hope that helps someone.
