### ISSUE TITLE
Mac OS X: Ethernet NIO loops back send packets

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#201]
GNS3 1.3.3, OS: Mac OS X 10.9.5

During testing the interconnection to an external device (https://community.gns3.com/thread/8695) I found a strange issue on Mac OS X with the Ethernet NIO.

Topology:
![nio_en0](https://cloud.githubusercontent.com/assets/896406/7877811/dc958f14-05df-11e5-975c-83496214c41b.png)

All packet send from the GNS3 side are looped back. It's easy to see by "show cdp neighbor", the router sees himself as it's neighbor.

A wireshark trace within GNS3 sees all packets doubled, one time when it's send and a second time echoed back.
![sniff_gns3](https://cloud.githubusercontent.com/assets/896406/7877847/4d966f1c-05e0-11e5-9fb6-aeb9a27e137d.png)

A sniff on the ethernet link shows, that each send packet is really only once on the line.
![sniff_en0](https://cloud.githubusercontent.com/assets/896406/7877893/c0fc4314-05e0-11e5-9cda-094ddf9ec6b2.png)

This doesn't happen in Linux, tested with Debian 8 (Jessie).

If this can't be fixed, because it's a "feature" in OS X, then the Ethernet NIO is hardly usable for me. This looped backed packets make it impossible to connect a switch to the Ethernet NIO. Luckily the TAP NIO works as expected.

**Comment by noplay** [comment]
I'm afraid of a bug in Dynamips...

**Comment by noplay** [comment]
I set milestone 1.3.4 because it's an actual bug, but I doubt we can fix it quick.

**Comment by ehlers** [comment]
Have you tried, if this bug is also in OS X 10.10 ?

I don't need a quick fix, I now use the TAP NIO. But it took me some time to analyze, why the Ethernet NIO works fine with routers but not with switches. If it's a general problem in OS X, maybe we can issue some warning.

**Comment by noplay** [comment]
I also got the LOOP packet :(

**Comment by grossmj** [comment]
I do not remember having any issue on OSX with NIO Ethernet... and I believe the code corresponding to it has never changed. So what changed? Maybe we should try with an older version of Dynamips?

**Comment by ehlers** [comment]
I just tested 0.8.7 on my iMac with OS X 10.9.5: I have the same problem there. A router sees itself as the CDP neighbor and Wireshark shows double packets (one sent and one echoed back).

**Comment by ehlers** [comment]
I had a deeper look in dynamips and I think I slowly understand what happens:

In common/gen_eth.c the device is opened with PCAP_D_INOUT, which captures all packets received and sent from this device. So when a GNS3 devices sends a packet with gen_eth_send on Mac OS X it receives it's own packet at gen_eth_recv. Within Linux there seems to be a filter, that suppresses that.

I changed gen_eth.c to use PCAP_D_IN, which captures only incoming packets, and recompiled v0.2.12 on Mac OS X. That way the echo is gone.

But that has a drawbacks: GNS3 doesn't see the traffic of other applications on the same host.

On Linux and Mac OS X you can't communicate between GNS3 and the local machine via the Ethernet NIO (see the 4th topic in the old GNS3 FAQ at http://forum.gns3.net/topic18.html). So you don't loose that much.

But (in theory, I haven't tested) it should be possible to have another application on the same host that also uses libpcap and communicates via the Ethernet NIO with GNS3. Changing gen_eth.c to use PCAP_D_IN will break this communication.

Furthermore the capture within GNS3 of the ethernet NIO doesn't show all packets, the packets from other applications on the same hosts are not shown. Of cause, a capture directly on the device (outside GNS3) shows all packets.

So I don't really know, what to do.
- Changing dynamips is quite critical and results in some restrictions. Maybe the changes could be made only for OS X (```#ifdef __APPLE__```)
- Leave it at the current status makes the ethernet NIO unusable for switches in MAC OS X

Anyway here my quick and dirty change to dynamips:
```
--- a/common/gen_eth.c
+++ b/common/gen_eth.c
@@ -46,7 +46,8 @@ pcap_t *gen_eth_init(char *device)
    if (!(p = pcap_open_live(device,2048,TRUE,10,pcap_errbuf)))
       goto pcap_error;
 
-   pcap_setdirection(p,PCAP_D_INOUT);
+//   pcap_setdirection(p,PCAP_D_INOUT);
+   pcap_setdirection(p,PCAP_D_IN);
 #ifdef BIOCFEEDBACK
    {
      int on = 1;
```

**Comment by ehlers** [comment]
I re-tested 0.8.7 but this time not with the default dynamips 0.2.12, but with 0.2.8RC3 and it works !!!

Then I looked into the dynamips source and the next commit after 0.2.8RC3 is https://github.com/GNS3/dynamips/commit/eebe3a68626cdaa1057445e3cfac184ea0971498 , which changes the PCAP_D_IN to PCAP_D_INOUT:
```
-   /* Accept only incoming packets */
-   pcap_setdirection(p,PCAP_D_IN);
+   pcap_setdirection(p,PCAP_D_INOUT);
```

**Comment by grossmj** [comment]
@ehlers you rock! I was about to tell you I have had no issues when I connected my Mac Book Pro to Cisco switches using NIO Ethernets while studying for my CCIE... but that was before 0.2.8RC3 ;)

**Comment by grossmj** [comment]
I think the fix should be to use ```PCAP_D_INOUT``` only if ```BIOCFEEDBACK``` is defined, otherwise we just use ```PCAP_D_IN````

**Comment by ehlers** [comment]
I just looked around my linux installation (Debian 8.0) and I haven't found anything like BIOCFEEDBACK in whole /usr/include, not even in /usr/include/pcap/bpf.h . As Linux has no problem with PCAP_D_INOUT, we don't have to fall back to PCAP_D_IN even though it doesn't support BIOCFEEDBACK. So the #ifdef construct might be a little bit more complex.

**Comment by grossmj** [comment]
Ok let's use ```#ifdef __APPLE__``` then ;)

**Comment by ehlers** [comment]
Oh, I didn't meant to argue against ```#ifdef BIOCFEEDBACK```, I just wanted to say that Linux may need special attention.

It could look like that (untested):
```
#if defined(__linux__)
   pcap_setdirection(p,PCAP_D_INOUT);
#elif defined(BIOCFEEDBACK)
   pcap_setdirection(p,PCAP_D_INOUT);
   {
     int on = 1;
     ioctl(pcap_fileno(p), BIOCFEEDBACK, &on);
   }
#else
   pcap_setdirection(p,PCAP_D_IN);
#endif
```

But an ```#ifdef __APPLE__``` is fine for me as well. I'm completely relaxed, how it's implemented.

**Comment by noplay** [comment]
I have implemented it with the #ifdef _APPLE
