### ISSUE TITLE
Timeout warning message when adding large image before the start of GNS3

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-server#2010]
**Describe the bug**
When I add a new large image into GNS3/images/QEMU while GNS3 is not running, during the next start timeout warning messages are shown.

**GNS3 version and operating system:**
 - OS: macOS 10.13.6 (High Sierra) and Linux Debian 10 (Buster)
 - GNS3 version 2.2.13 and 2.30dev2
 - No GNS3 VM

**To Reproduce**
1. Stop GNS3, if running
2. Copy large image file (several GB) into a GNS3 image direcotory, for example GNS3/images/QEMU
3. Start GNS3

**Screenshot**
![error_messages](https://user-images.githubusercontent.com/49040325/92473328-d6f89000-f1da-11ea-9d6f-6030b2dee26c.png)

**Additional context**
I assume, that during startup the GNS3 server is calculating MD5sums for all images without an existing MD5sum. After that it starts processing API requests. As the MD5 calculation can take quite some time, the server doesn't react on first few seconds, what leads to this warning message.

**Comment by grossmj** [comment]
I have made changes. The server won't block while calculating the MD5 checksum for images. Also, I have added the possibility to add new images while the server is running.
