### ISSUE TITLE
exception thrown when attempting to add label/shapes/drawings

### ISSUE THREAD

**Issue by jbrown8380** [GNS3/gns3-server#2014]
This issue is submitted in reference to the following post in the gns3 community forum:  https://gns3.com/exception-thrown-when-attempting-to-add-label-shapes-drawings

This issue appears to be a duplicate issue of the following:  https://gns3.com/community/featured/bug-crash-with-text-label

General issue description:

GNS3 version: 2.2.26
Host: Fedora 35 linux

When I attempt to add a note, draw a rectangle, or add a picture, I receive the following error message:

Use Help -> GNS3 Doctor to detect common issues.

=> ****** Exception detected, traceback information saved in /home/jbrown/.config/GNS3/2.2/exceptions.log ******
PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 474, in mousePressEvent
    note = self.createDrawingItem("text", pos.x(), pos.y(), 2)
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1639, in createDrawingItem
    item = TextItem(pos=QtCore.QPoint(x, y), z=z, rotation=rotation, locked=locked, project=self._topology.project(), drawing_id=drawing_id, svg=svg)

TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'

The first time I tried, it complained about not having access to Sentry SDK.  So I installed sentry-sdk with "pip3 install --upgrade sentry-sdk".  The installation appeared to be successful.  Now I'm getting the error message mentioned above.

Please see the attached exceptions.log file:
[exceptions.log](https://github.com/GNS3/gns3-server/files/7770390/exceptions.log)

**Comment by cristian-ciobanu** [comment]
A similar issue has been reported few days ago in the GUI github repo https://github.com/GNS3/gns3-gui/issues/3276 so I think this is a duplicate.

**Comment by jbrown8380** [comment]
I would agree with that.  I'll go ahead and close this issue then.
