### ISSUE TITLE
README.rst - no working link in Windows section

### ISSUE THREAD

**Issue by ova-work** [GNS3/gns3-server#2022]
> Windows
> Please use our **all-in-one installer** to install the stable build.

https://community.gns3.com/community/software/download   - this link is not working.

Sorry! The page you are looking for
could not be found.
Please check that the link is correct. Otherwise, the page might have been moved, renamed, deleted, or may require you to be logged in to see it.

**Comment by grossmj** [comment]
Fixed, thanks 👍
