### ISSUE TITLE
help to do a patch to use systemctl/journalctl in docker VM ?

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#2026]
Hi

On LiveRaizo, i look to temporary transform the QEmu VM Debian in Docker VM.
so it will be lighter to use LiveRaizo in Virtualbox, for example.

But, in class room, i use often systemctl/journalctl to configure and debug service.
And, by default, systemctl doesn't work in docker. 

To do it, the most easy method that i found is : 
```
docker run --name centos.server -ti -d --privileged=true centos "/usr/sbin/init"
docker exec --tty --interactive centos.server /bin/bash
```

I have see that you afraid from risk [here](https://github.com/GNS3/gns3-gui/issues/3143)

I want to do a litlle patch on gns3 for LiveRaizo, but i didn't find the file where you are doing a "docker run" (the `docker exec` is in "gns3server/compute/docker/docker_vm.py")
Could you say the file or the function where i can add this :  "--privileged=true" and "/sbin/init" ?
I hope that it is not more complicated.

**Comment by b-ehlers** [comment]
In GNS3 the docker images are already started with the option `--privileged=true`. The `/usr/sbin/init` command can be added as the "Start command" in the docker template.
![docker_centos_systemd](https://user-images.githubusercontent.com/49040325/150505036-f0e28ba0-1cae-497d-bf36-8a72a6134c20.png)

The console of the docker node will always show the output of the init command, without a shell allowing to enter commands. But you can use the auxiliary console (right-click on the node -> Auxiliary console) to get a shell window.

If you have experience with systemd you might be able to add a systemd configuration, that starts a shell on `/dev/pts/0`, the console device of the docker node. Then you might me able to use the regular node console also for shell access. But I don't have systemd knowledge and can't help you with that.

**Comment by b-ehlers** [comment]
To answer your question about where to change the docker node creation (even though I don't think that's needed):

GNS3 uses the Docker API to interact with Docker, not the command line. The nodes creation is done in gns3server/compute/docker/docker_vm.py function create(). The `params` structure defines the default parameter for the docker node creation.

https://github.com/GNS3/gns3-server/blob/03f8ea9a6efb1241a5a328afdf86f87b9380eb56/gns3server/compute/docker/docker_vm.py#L331-L348

**Comment by Raizo62** [comment]
Thank you @b-ehlers :-)

Your `/usr/sbin/init` in "Start command" works and asks me a login, then i doesn't need to use Auxiliary console :-)
I will investigate more

Thank you also for the Docker API information
