### ISSUE TITLE
Do we still support the nodes running in case of project is  closed ? 

### ISSUE THREAD

**Issue by chunji08** [GNS3/gns3-server#2028]
I have this issue to report in my working environment.  https://www.gns3.com/community/support/nodes-stop-running-after-project-is-closed 

Does anyone know if this feature is still valid ?

Thanks 

Jack

**Comment by chunji08** [comment]
I have just done the further investigation.  In theory, the setting value of "when_exit" from "gns3_controller.conf" file could be  either "stop", "suspended" or "keep", but in the in "gns3server/controller/gns3vm/__init__.py" file, I done see any logic for "keep" scenario: 
 
```
    async def exit_vm(self):

        if self.enable:
            try:
                if self._settings["when_exit"] == "stop":
                    await self._stop()
                elif self._settings["when_exit"] == "suspend":
                    await self._suspend()
            except GNS3VMError as e:
                log.warning(str(e))
``` 

And do we know what we are unit-testing here in the test_controller.py file: 
```
async def test_keep_vm(controller):
    """
    Keep GNS3 VM if configured
    """

    controller.gns3vm.settings = {
        "enable": True,
        "engine": "vmware",
        "when_exit": "keep",
        "vmname": "GNS3 VM"
    }

    controller.gns3vm.current_engine().running = True
    with asyncio_patch("gns3server.controller.gns3vm.vmware_gns3_vm.VMwareGNS3VM.suspend") as mock:
        await controller.stop()
        assert not mock.called
```

Thanks, 

Jack

**Comment by grossmj** [comment]
Hi Jack, this code is for the GNS3 VM, not the projects. I will check if the feature still work.

**Comment by grossmj** [comment]
Have you ticked the "Leave this project running in the background when closing GNS3" setting? (In File -> Edit project)

![Screenshot from 2022-02-10 22-05-13](https://user-images.githubusercontent.com/4752614/153401107-32d7ae72-d84c-4c22-8158-fd3023b280d0.png)
