### ISSUE TITLE
A workaround to get GNS3 VM working on Mac with M1 processor or silicon based Mac's

### ISSUE THREAD

**Issue by samstillwater** [GNS3/gns3-server#2030]
As known that the Gns3 vm cannot work on the silicon based mac or with M1 processor  even though the vmware fusion for arm processor is downloaded as the Gns3 vm is not an arm processor based VM though it will run fine on the intel based VM. Though the intel based vmware fusion will run fine in the arm environment through rosseta 2 but the I cannot get the gns3 vm to run in the VMware fusion as it repeatedly says transport pipe broken, can this issue be fixed or we need a arm based gns3 vm.

**Comment by grossmj** [comment]
We have a version of the GNS3 VM for ARM (experimental), there are many limitations as explained in https://github.com/GNS3/gns3-gui/discussions/3261

Best at the moment is to run the classic GNS3 VM using UTM even if it means everything will run a lot slower... but this is acceptable. Please see https://github.com/GNS3/gns3-gui/issues/3257 for details.
