### ISSUE TITLE
Lab Upload Hang

### ISSUE THREAD

**Issue by ctbradt** [GNS3/gns3-server#2032]
I've been trying to upload a project to the Lab page.  I hit the Upload, select the file and it appears to be uploading but just spins forever.  Looking at Windows Task Manager it looks like the file may upload but something never really finishes.  Is there an issue with Lab repository?   I've tried both Firefox and Chrome.

I was able to upload another lab back in January, so it appears something has changed/broken since then.

![Lab-Upload](https://user-images.githubusercontent.com/99346826/153235141-dcc38b51-921e-4271-b6ec-1248cc3c1780.jpg)

Thanks ...

**Comment by grossmj** [comment]
I will have our webmasters look at it.

**Comment by ctbradt** [comment]
Any progress?

**Comment by grossmj** [comment]
Sorry I haven't got any response from them yet.

**Comment by grossmj** [comment]
@ctbradt do you have the file you are trying to upload? thanks
