### ISSUE TITLE
docker config : add gns3 variables in Environment variables

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#2033]
Hi

In the config interface of a docker VM, to set the Environment variables, can you add the use of the variables of GNS3 (examples : %vm-name%, %project-path%, ...) ?

Thank you

**Comment by grossmj** [comment]
%vm-name%, %vm-id%, %project-id%, %project-path% are now supported

**Comment by Raizo62** [comment]
Thanks :-)
