### ISSUE TITLE
WebUI + Wireshark

### ISSUE THREAD

**Issue by iam-thehelp** [GNS3/gns3-server#2041]
Hello,

I am having an issue launching Wireshark through the GNS3 WebUI. I receive errors and I am not sure how to correct this problem.
### _*No issues while using the GNS3 App*_

<img width="588" alt="WebUI Error" src="https://user-images.githubusercontent.com/101709761/158574459-77348ff5-a67f-4f88-b1e3-3aeb8d1a713b.png">
<img width="399" alt="WebUI choice" src="https://user-images.githubusercontent.com/101709761/158574518-b9c9ba8c-973b-4c8c-8007-0c551d7b85ec.png">
<img width="419" alt="PCAP Error" src="https://user-images.githubusercontent.com/101709761/158574561-7130c278-ea2f-4e7e-b04b-51352486fd9a.png">

Infos:
Client OS: macOS & Windows 10
Web browser: Mozilla, Chrome, Safari
GNS3 VM version: 2.2.26
GNS3 WebClient Pack: 1.0.0b3
Wireshark version: 3.6.2
IOU images:
  - i86bi-linux-l3-adventerprisek9-15.4.2T4.bin
  - i86bi-linux-l2-ipbasek9-15.1a.bin

Any help/info would be greatly appreciated. Thanks!

**Comment by grossmj** [comment]
Looks like this is the same issue as https://github.com/GNS3/gns3-web-ui/issues/1298

**Comment by grossmj** [comment]
This is going to be fixed in https://github.com/GNS3/gns3-web-ui/pull/1302 Thanks 👍
