### ISSUE TITLE
Docker : /etc/network/interfaces and missing configurations

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#2052]
Hi

1. In Docker VM, the file "/etc/network/interfaces" generated by GNS3 doesn't contain a config for loopback :

```
auto lo
iface lo inet loopback
```

2. In Debian, the file "/etc/network/interfaces" contains a config to load others configs
`
source /etc/network/interfaces.d/*
`
Then, In Docker VM, GNS3 must create an empty folder "/etc/network/interfaces.d/"

**Comment by grossmj** [comment]
> In Docker VM, the file "/etc/network/interfaces" generated by GNS3 doesn't contain a config for loopback :

I don't think this is necessary, if I add the following lines in `/etc/network/interfaces`

```
auto lo
iface lo inet loopback
```
then I get `ip: RTNETLINK answers: File exists` when starting the container.

Also, the loopback is up and ready without having to add these lines.

```
root@UbuntuDockerGuest-1:~# ifconfig 
...

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

> Then, In Docker VM, GNS3 must create an empty folder "/etc/network/interfaces.d/"

I will add this.

**Comment by Raizo62** [comment]
1.  I believe that to create the empty folder `/etc/network/interfaces.d` is a little useless if you don't add the line `source /etc/network/interfaces.d/*` in the "/etc/network/interfaces"
2. You are right. Add "iface lo inet loopback" in "/etc/network/interfaces.d" does an error if the docker VM doesn't start with systemd. It is strange : how add automatically an IP to loopback ? (it is only a question. Now i don't need it)

**Comment by Raizo62** [comment]
> It is strange : how add automatically an IP to loopback ? (it is only a question. Now i don't need it)

On a recent Linux, the line "iface lo inet loopback" is not necessary to have the loopback interface.
And, the IP is on a subinterface of lo with the keyword "static"

**Comment by grossmj** [comment]
> I believe that to create the empty folder /etc/network/interfaces.d is a little useless if you don't add the line source /etc/network/interfaces.d/* in the "/etc/network/interfaces"

I get the `ifup: can't open '/etc/network/interfaces.d/*': No such file or directory` error if I put `source /etc/network/interfaces.d/*` in `/etc/network/interfaces`. So I will put it anyway but commented by default.

**Comment by Raizo62** [comment]
You are right : i have also this error if the start command is not "/usr/sbin/init" :-(
