### ISSUE TITLE
bug with the names with quote in Docker VM with systemd

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#2054]
Hi

I import the docker image "centos" :
`docker pull centos`

In the config of GNS3, i create a template with this image.
In "start command", i set "/usr/sbin/init"

In the lab, i put this template with the name "with'quote"
I start it
I use the auxiliary console to access to the VM

I display the name with the command `hostname`
The name is "withquote", without the '

If i boot the VM with an empty "start command", the name keeps "with'quote"

**Comment by grossmj** [comment]
I did some tests and couldn't find the issue.

![Screenshot from 2022-04-21 14-31-11](https://user-images.githubusercontent.com/4752614/164402128-bd5f3a5d-0c85-4826-9941-142fffb6083b.png)

**Comment by Raizo62** [comment]
To use systemd, as "start command", use : `/usr/sbin/init`
(So, for console access, use "Auxiliary console")

**Comment by Raizo62** [comment]
If your "start command" is "/bin/bash", you can't use the command of systemd : systemctl/journalctl

**Comment by Raizo62** [comment]
source : [man hostname](https://man7.org/linux/man-pages/man7/hostname.7.html)
```
Each element of the hostname must be from 1 to 63 characters long
and the entire hostname, including the dots, can be at most 253
characters long.  Valid characters for hostnames are [ASCII(7)](https://man7.org/linux/man-pages/man7/ascii.7.html)
letters from a to z, the digits from 0 to 9, and the hyphen (-).
A hostname may not start with a hyphen.
```
It must be the same with QEmu VM.

**Comment by grossmj** [comment]
I agree, I will implement this.

**Comment by grossmj** [comment]
I have created a PR for this: https://github.com/GNS3/gns3-gui/pull/3340

However I am concerned about restricting users who want to name their nodes using non-ascii characters etc. Maybe we should introduce a `hostname` property which would be used inside Qemu, Docker etc. and keep the current name to be shown in the GUI?

Also, the checks are done in the GUI. It would make much more sense to have this in the API on the server side.

**Comment by Raizo62** [comment]
> However I am concerned about restricting users who want to name their nodes using non-ascii characters etc. Maybe we should introduce a hostname property which would be used inside Qemu, Docker etc. and keep the current name to be shown in the GUI? Similar to what Docker has: https://docs.docker.com/engine/api/v1.41/#operation/ContainerCreate

Why not...with variables to know hostname and gui-name in the config of GNS3-gui, and the API.

Which name do you use if at least 2 VM have a name with only non-ascii characters ?
