### ISSUE TITLE
Allow async-timeout >=4.0.2

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#2057]
- gns3-server (Pypi) depends on async-timeout 3.0.1.
- redis (Pypi) 4.2.2 has requirement async-timeout>=4.0.2

Since I cannot [run gns3 from a python3 virtual env](https://github.com/GNS3/gns3-gui/issues/3311), is it possible to upgrade async-timeout version requirement?

**Comment by jean-christophe-manciot** [comment]
Nice! I suppose you meant 2.2.32.1 due to [this issue](https://github.com/GNS3/gns3-gui/issues/3324).

**Comment by grossmj** [comment]
Correct :)
