### ISSUE TITLE
Could not find NPF id for interface eth2

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2061]
gns3 version 2.2.31, virtualbox 6.1 windows 10 pro

The error message printed to GNS3 users.
=> Could not find NPF id for interface eth2

This should be closer to the root problem than 
https://github.com/GNS3/gns3-server/issues/2060

But it is the same scenario.

The scenario is I had a working project on this machine, this vm and this gns3.
I exported that project.
I closed gns3
I imported that project

I tried 2 versions of the export.
all default, all default again, and I checked the box with the mac address (whatever it said with Mac address I checked it)
First the diagram and then the problems.

![red-cloud](https://user-images.githubusercontent.com/85327995/165823422-d307c152-f110-4666-8c13-e43b72968774.PNG)

Basically, the pings from inside the GNS3 topology are failing when I try to ping the outside...
and maybe when I try to start can wireshark on the link between the GNS3 cloud and the docker is turned off., GNS3 tells me there is "no active devices running" - or something like that
and maybe when I try to delete the link between the GNS3 cloud and the docker, which I did, and I try to add it back in, I get "Could not find NPF id for interface eth2"

The full selected snippet is:
2022-04-28 16:50:44 INFO base_node.py:655 Starting new uBridge hypervisor 192.168.56.1:4626
2022-04-28 16:50:44 INFO hypervisor.py:169 starting ubridge: ['C:\\Program Files\\GNS3\\ubridge.EXE', '-H', '192.168.56.1:4626']
2022-04-28 16:50:44 INFO hypervisor.py:171 logging to C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-003\project-files\builtin\eb1be634-446f-4739-b241-010892f089ca\ubridge.log
2022-04-28 16:50:44 INFO hypervisor.py:179 ubridge started PID=3492
2022-04-28 16:50:44 INFO base_node.py:658 Hypervisor 192.168.56.1:4626 has successfully started
2022-04-28 16:50:44 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on 192.168.56.1:4626 after 0.1014 seconds
2022-04-28 16:50:45 INFO cloud.py:215 Cloud "Cloud1" [eb1be634-446f-4739-b241-010892f089ca] has been created
2022-04-28 16:50:45 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:44 +0000] "POST /v2/compute/projects/37190090-b236-4d27-849b-39383c1a8b3e/cloud/nodes HTTP/1.1" 201 2007 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:50:46 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:46 +0000] "POST /v2/compute/projects/37190090-b236-4d27-849b-39383c1a8b3e/ports/udp HTTP/1.1" 201 243 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:50:46 INFO cloud.py:399 Cloud "Cloud1" [eb1be634-446f-4739-b241-010892f089ca]: NIO NIO UDP bound to port 2
2022-04-28 16:50:46 ERROR cloud.py:405 Cannot add NIO on cloud "Cloud1": Could not find NPF id for interface eth2
2022-04-28 16:50:46 INFO base_node.py:669 Stopping uBridge hypervisor 192.168.56.1:4626
2022-04-28 16:50:46 INFO hypervisor.py:208 Stopping uBridge process PID=3492

I am in cloud.py now on line 405, but I am only up to hello_world.py and
there is really not much on npf and npcap and I do not see any "pipes" using "ProcessExplorer" and ProcessExplorer is ridiculously complicate.

2022-04-28 16:50:46 ERROR cloud.py:405 is a FATAL error in my opinion.

Full gns3_server.log should be attached.

[gns3_server.log](https://github.com/GNS3/gns3-server/files/8585536/gns3_server.log)

I will take a look at the python and ubridge code for an hour or so and that's about it.

**Comment by josephmhiggins** [comment]
"This" is a whole big thing because brand new gns3 users always want to ping 8.8.8.8
That's the first thing they want to do *grumble*

Now, if I can get a working gns3-endhost and a working gns3-cloud and a working gns3 export of that project then I can immediately deal with:
1. exporting my wmware configuration, as that seems to be based on netadapter names, but
2. I am new to virtualbox and from what I see it is that their network configuration is netadapter descriptions. If Oracle uses descriptions as a key, then it becomes a major problem because descriptions for network adapters on Windows 10 are in a .sys file and people, whom I consider authoritative sources say that you are not allowed to modify a .sys file. I need a variable that is available to me via powershell and Rename-NetAdapter is permitted and available for VMware.
3. As far as Hyper-V goes, I know nothing about Hyper-V.

**Comment by josephmhiggins** [comment]
I did the export from the working file again.
I exported it to 
docker-cloud-export-check-includebaseimages-uncheck-includesnapshots-uncheck-reset-macaddresses.gns3project

with the name self-explanatory

I imported it to
/test-imports/docker-cloud-export-check-includebaseimages-uncheck-includesnapshots-uncheck-reset-macaddresses.gns3project

The cloud node has a Red square.
That is definitely an ERROR/FATAL ERROR because that Red square is far too difficult to detect - even though it is right in the middle of the topology *shrug*

2022-04-30 12:13:42 INFO cloud.py:399 Cloud "Cloud1" [73bfb8fe-1607-48e3-94e9-762181d1330d]: NIO NIO UDP bound to port 2
2022-04-30 12:13:42 ERROR cloud.py:405 Cannot add NIO on cloud "Cloud1": Could not find NPF id for interface eth2
2022-04-30 12:13:42 INFO base_node.py:669 Stopping uBridge hypervisor 192.168.56.1:15786
2022-04-30 12:13:42 INFO hypervisor.py:208 Stopping uBridge process PID=18808

There is not any error message in the GNS3 GUI.
If I delete link and add the link, then I should get the:
Could not find NPF id for interface eth2

But I think my troubleshooting is over for this.

I am getting a little confused with 4 open tickets...so I will not open a new ticket for the bug with
putting debug 2 in the console with Virtualbox as a hypervisor that drives gns3 nuts..........

**Comment by josephmhiggins** [comment]
And you need an enhancement - that's another ticket that I will not open yet.

    "imported": true

FATAL ERROR ON IMPORT of project - suggest deleting everything associated with imported project.

**Comment by josephmhiggins** [comment]
And here is the png showing the Console Dock with no messages:
![docker-cloud-export-check-includebaseimages-uncheck-includesnapshots-uncheck-reset-macaddresses](https://user-images.githubusercontent.com/85327995/166105958-4650a81d-2c5d-479b-a201-d2fe619e16cd.PNG)

**Comment by josephmhiggins** [comment]
2059, 2060 all extend from the red dot on the Cloud which throws no error...i did it again in almost perfectly with a dated timeline.
[docker-cloud-export.docx](https://github.com/GNS3/gns3-server/files/8597366/docker-cloud-export.docx)

**Comment by josephmhiggins** [comment]
oh, here's the bug.
the cloud before exported is compute_id vm
the cloud after imported is "compute_id": "local",

...This time I used Ean's new --profile command to start gns3, but I believe it was there before because I learned about after I published this bug...........But I will do it again using the old manual way.
Here's me starting the gns3 vm with the --profile in the .docx
PS > start-process -FilePath 'C:\Program Files\GNS3\gns3.exe' -ArgumentList "--profile Vbox"

PS > start-sleep 90

PS > Test-NetConnection 192.168.56.101 -Port 80


..the cloud before exported is compute_id vm
        "nodes": [
            {
                "compute_id": "vm",
                "console": null,
                "console_auto_start": false,
                "console_type": "none",
                "custom_adapters": [],
                "first_port_name": null,
                "height": 71,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "Cloud1",


the cloud after imported is "compute_id": "local",
        "nodes": [
            {
                "compute_id": "local",
                "console": null,
                "console_auto_start": false,
                "console_type": "none",
                "custom_adapters": [],
                "first_port_name": null,
                "height": 71,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "Cloud1",
                    "x": 54,
                    "y": -25
                },

but the gns3-endhost after import is  "compute_id": "vm",
            {
                "compute_id": "vm",
                "console": 5003,
                "console_auto_start": false,
                "console_type": "telnet",
                "custom_adapters": [],
                "first_port_name": null,
                "height": 59,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "gns3-endhost-1",
                    "x": -23,
                    "y": -25
                },

I will put a fix on this after I relearn C, figure out ubridge, and learn python!!!

**Comment by josephmhiggins** [comment]
Yeah...I am handicapped by this problem and I can not help Steve Daley.

https://gns3.com/community/featured/trying-to-connect-my-gns3-network-to-the-internet

                "compute_id": "local",
- snip -
                    "text": "Cloud1",
- snip -
                "name": "Cloud1",

So this problem does not help me, per se.
Daley is using dynamips - which I do not support - so I can not manually upload configurations and .gns files.
This does not hurt me. This hurts ability to help new GNS3 users.

I, however, did not check if the lab is a failure. I do not think I have to because the Cloud is Red.
Everything works perfectly find in that lab.


![daley-to-github](https://user-images.githubusercontent.com/85327995/167318424-72088e90-48f5-490f-9209-eea1989695ff.PNG)

**Comment by josephmhiggins** [comment]
The situation has changed. ubridge -e is the same.
But I just started gns3 and the cloud is green.

C:\WINDOWS\system32>cd C:\Program Files\GNS3

C:\Program Files\GNS3>ubridge.exe -e
Network device list:

  rpcap://\Device\NPF_{0AB5181E-FD45-4DEE-AE9F-15A7FE09C3ED} => Network adapter 'Intel(R) 82576 Gigabit Dual Port Network Connection' on local host
  rpcap://\Device\NPF_{2EDFC498-330C-41D7-9EA6-6430B9524BD0} => Network adapter 'Realtek Ethernet Controller' on local host
  rpcap://\Device\NPF_{B52FEFF4-2D22-4BDF-888F-FD477110450C} => Network adapter 'Intel(R) 82576 Gigabit Dual Port Network Connection' on local host
  rpcap://\Device\NPF_{94F125AB-71DE-4AF4-B6A7-62E4A5EF8494} => Network adapter 'Broadcom NetLink (TM) Gigabit Ethernet Driver' on local host
  rpcap://\Device\NPF_{CDCDE860-F9FC-4780-9D04-24C8F0F8E260} => Network adapter 'Intel(R) 82576 Gigabit Dual Port Network Connection' on local host
  rpcap://\Device\NPF_{AC712734-FE6C-4799-A587-03065472C820} => Network adapter 'Intel(R) 82576 Gigabit Dual Port Network Connection' on local host


C:\Program Files\GNS3>REM project steve open; nothing is started
Edit: "nothing means means I started no VMs".

C:\Program Files\GNS3>ubridge.exe -e
Network device list:

  rpcap://\Device\NPF_{0AB5181E-FD45-4DEE-AE9F-15A7FE09C3ED} => Network adapter 'Intel(R) 82576 Gigabit Dual Port Network Connection' on local host
  rpcap://\Device\NPF_{2EDFC498-330C-41D7-9EA6-6430B9524BD0} => Network adapter 'Realtek Ethernet Controller' on local host
  rpcap://\Device\NPF_{B52FEFF4-2D22-4BDF-888F-FD477110450C} => Network adapter 'Intel(R) 82576 Gigabit Dual Port Network Connection' on local host
  rpcap://\Device\NPF_{94F125AB-71DE-4AF4-B6A7-62E4A5EF8494} => Network adapter 'Broadcom NetLink (TM) Gigabit Ethernet Driver' on local host
  rpcap://\Device\NPF_{CDCDE860-F9FC-4780-9D04-24C8F0F8E260} => Network adapter 'Intel(R) 82576 Gigabit Dual Port Network Connection' on local host
  rpcap://\Device\NPF_{AC712734-FE6C-4799-A587-03065472C820} => Network adapter 'Intel(R) 82576 Gigabit Dual Port Network Connection' on local host


C:\Program Files\GNS3>

My gns3_server.log is immaculate.
I renamed my gns3_server.log to gns3_server-jeremy.log
So I have my log.
There is no error in the gns3_server-jeremy.log about any NPF id.

The GNS3 cloud has a green square. I have not and will not proceed any further at this time.
It is not in my diary if I closed out GNS3 after exporting a project.

**Comment by josephmhiggins** [comment]
I did it again.
It does not work.
This is the 8th time I am doing this.
At this point, I am just confusing myself.
Exporting a project on Windows 10 Pro with gns3 2.2.31 and Virtualbox 6.1.34 and then importing it does not work.
The cloud is RED.
Again, I am not powering up and trying a ping through the cloud.
A much, much better and a much cleaner project is just an ethernet switch and a GNS3 Cloud.
I can not change the project anymore. It is STEVE.
It cannot be export to my host and then reimported back into GNS3.

With a Windows - gui - it is so much better to do all of this the way that David Bombal does it - with a video.
So this should be a *close* approximation of my planning. The short of it is that it does not work and the
GNS3 Cloud changes from GREEN to RED.

20220510_223226 I will have gns3 closed
20220510_223300 I will run in administrator mode in CMD ubridge.exe -e 
20220510_223306 I will wait unti the GNS3 VM becomes green
20220510_223324 I will run in administrator mode in CMD ubridge.exe
20220510_223333 I will open a open a project named STEVE
20220510_223350 I will ensure the cloud is green
20220510_223402 I will name the file as C:\Users\joe_I7\EXPORTED-PROJECT-AND-THE-ORIGINAL-NAME-IS-STEVE.gns3project

20220510_223422 I will close gns3
20220510_223443 I will run in administrator mode in CMD ubridge ubridge.exe -e
20220510_223448 I will start gns3
20220510_223524 I will wait until the GNS3 VM becomes green
20220510_223536 I will run in administrator mode in CMD ubridge.exe
20220510_223554 I will import the project as as C:\Users\joe_I7\GNS3\Projects\EXPORTED-PROJECT-AND-THE-ORIGINAL-NAME-IS-STEVE\EXPORTED-PROJECT-AND-THE-ORIGINAL-NAME-IS-STEVE 
20220510_223618 I will take a picture of it and name the picture C:\Users\joe_I7\GNS3\Projects\EXPORTED-PROJECT-AND-THE-ORIGINAL-NAME-IS-STEVE\EXPORTED-PROJECT-AND-THE-ORIGINAL-NAME-IS-STEVE.gns3project.png

If I had a video, I would not upload it.
But it does not work.

I have thought for the last 3 months the best thing some new a gns3 user that would want to learn python and be involved in gns3 would be to write a
test_something.py

You can not break anything buy coding a:
test_exportproject_on_windows10_virtualbox.py

**Comment by josephmhiggins** [comment]
Please note:
The original gns3 who had a problem has overcome his difficulties with the help of John Fleming.

But, the big hitter is still there.
The big hitter is
docker gns3-endhost and gns3 cloud
The new gns3 users always want to ping 8.8.8.8
And I see no way in the world that kind of test should be put in a running version of gns3.
It "gns3-endhost and gns3 cloud" must be in the gns3 marketplace as a project.
But those 2 things:, gns3-endhost and gns3 cloud must be guaranteed to work.

**Comment by josephmhiggins** [comment]
This is a philosophical decision.
Should the gns3 community help new gns3 users who can not ping 8.8.8.8
After 3 or 4 years, I have reached the opinion that GNS3 should create a project where new GNS3 users will succeed.
That project I believe is:
docker gns3-endhost and gns3 cloud

**Comment by grossmj** [comment]
> I have reached the opinion that GNS3 should create a project where new GNS3 users will succeed.

Do you mean a pre-configured way to access Internet?

**Comment by josephmhiggins** [comment]
Do you mean a pre-configured way to access Internet?

**No.**

A better edit would be:
I have reached the opinion that gns3.com should have a project in the GNS3 marketplace to reach the internet where new GNS3 users can easily succeed and the GNS3 community can help troubleshoot if the new gns3 user fails. That project I have identified is a "gns3-docker" and the GNS3 cloud.

The GNS3 community, more or less, does not have the skills to troubleshoot a "pre-configured way to access Internet".

This edit is valid:
"I will have to investigate this on my own because this could be an extremely rare problem that is isolated to my Windows10 physical host."

I think I know what the root cause is. But, I will have to investigate it and I am not going to say what I think it is.
