### ISSUE TITLE
Error when connecting to server after upgrading to 2.2.32.1

### ISSUE THREAD

**Issue by jedk2** [GNS3/gns3-server#2063]
After upgrading both the gns3 gui and server, the client gives the following error on startup and cannot open any projects or build a new one. In my case, the gui is local on a mac and is connecting to a remote server, but other users have seen the same thing in varying environments.

```
gns3@gns3vm:~$ gns3server --v
2.2.32.1
```

![Screen Shot 2022-04-29 at 2 01 52 PM](https://user-images.githubusercontent.com/104635754/165998732-e13381de-05ee-47e4-ae1a-ed9c06cfdebd.png)

```=> Cannot open a .gns3 file on a remote server, please use a portable project (.gns3p) instead
Client version 2.2.32 is not the same as server (controller) version 2.2.32.1
Error while getting templates list: Client version 2.2.32 is not the same as server (controller) version 2.2.32.1
Error while getting compute list: Client version 2.2.32 is not the same as server (controller) version 2.2.32.1
```

Please reference the GitHub thread for more details. # https://www.gns3.com/community/support/issues-after-upgrading-to-2-2-32-1

**Comment by DevDorrejo** [comment]
Same issue, this need take priority

**Comment by tomhaslett** [comment]
Same!

**Comment by grossmj** [comment]
Do you use the GNS3 VM or a remote server?

The workaround for now is just to downgrade to v2.2.32 since v2.2.32.1 only has minor dependency fix only relevant when using the server and the GUI on the same Linux host.

To downgrade, please type: `python3 -m pip install gns3-server==2.2.32`

**Comment by DevDorrejo** [comment]
> Do you use the GNS3 VM or a remote server?
> 
> The workaround for now is just to downgrade to v2.2.32 since v2.2.32.1 only has minor dependency fix only relevant when using the server and the GUI on the same Linux host.
> 
> To downgrade, please type: `python3 -m pip install gns3-server==2.2.32`
> 

If I use VM, did i need to downgrade the gui too?, And the dependency error can be ignore?

**Comment by PranavBhattarai** [comment]
@grossmj In Fedora 36, I got got this error:

```  ⟹  sudo dnf update
[sudo] password for pranav:
Last metadata expiration check: 0:24:25 ago on Sun 15 May 2022 09:14:12 AM +0545.
Dependencies resolved.

 Problem: cannot install the best update candidate for package gns3-server-2.2.31-2.fc36.noarch
  - nothing provides python3.10dist(distro) >= 1.7 needed by gns3-server-2.2.32-1.fc36.noarch
=======================================================================================================================================
 Package                          Architecture                Version                               Repository                    Size
=======================================================================================================================================
Skipping packages with broken dependencies:
 gns3-server                      noarch                      2.2.32-1.fc36                         updates                      5.2 M

Transaction Summary
=======================================================================================================================================
Skip  1 Package

Nothing to do.
Complete!
```
Is this related?!

**Comment by arif0raza** [comment]
Error while getting templates list: Client version 2.2.44.1 is not the same as server (controller) version 2.2.38
