### ISSUE TITLE
Dynamips hypervisor process has stopped, return code: -11

### ISSUE THREAD

**Issue by rvuttham06** [GNS3/gns3-server#2064]
Getting the below error when trying to "ssh" from one router to another router in gns3.

Could not send Dynamips command 'vm set_ghost_status "R3" 2' to 0.0.0.0:33489: Connection lost, process running: False
Could not send Dynamips command 'vm get_status "R3"' to 0.0.0.0:33489: [Errno 32] Broken pipe, process running: False

Series : c7200
image: c7200-jk9s-mz.124-13b.image

Thank You.

**Comment by grossmj** [comment]
Looks like Dynamips has crashed. What OS do you use? You may have to try another IOS image.
