### ISSUE TITLE
Hiding/removing default nodes (Switch, NAT, framerelay, etc)

### ISSUE THREAD

**Issue by lurendrejer** [GNS3/gns3-server#2074]
I would really like to see the ability to remove the default nodes, serverside.

We use edited versions of each of them (icons, allowed interfaces on NAT/Bridge, etc.) but the original nodes i still present in the interface, including their 'wrong' icons and configuration.

**Comment by grossmj** [comment]
Implemented, you can configure this in the server config.

```
[Server]
; Enable the built-in templates
enable_builtin_templates = False
```

**Comment by lurendrejer** [comment]
Perfect, thank you so much.
When will 33 be out? the spice-upgrade and this setting really makes a difference.

**Comment by lurendrejer** [comment]
aah, june22 - didn't know i could se a due-date on the milestone.

Thanks again :)
