### ISSUE TITLE
GNS3 2.2.33.1 needs to be re-released.

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-server#2078]
I'm getting giu version mismatch util I update version.py. I'm using PPA on raw Linux to assert dominance. 

https://github.com/GNS3/gns3-server/blob/1b32ef7854d9943af57a2e1d89c40fdf884dbbdf/gns3server/version.py#L27

```python
__version__ = "2.2.33.1"
__version_info__ = (2, 2, 33, 0)
```

Changing version_info to 2,2,33,1 fixes the complaints.

```python
__version_info__ = (2, 2, 33, 1)
```
Edit: correction the incorrect version on bug report. Oops.

**Comment by grossmj** [comment]
Have you updated both the GUI and the server?

https://github.com/GNS3/gns3-gui/blob/v2.2.33.1/gns3/version.py

**Comment by spikefishjohn** [comment]
I updated the Linux install via apt tied to PPA and updated the windows fat client. 

Doesn't the version.py show "version" is 2.2.33.1 but "version_info" show 2.2.33.0 or am I mis-understanding how that is used?

**Comment by grossmj** [comment]
version_info is not that important and a positive number in the fourth number is considered development.


# __version_info__ is a four-tuple for programmatic comparison. The first
# three numbers are the components of the version number. The fourth
# is zero for an official release, positive for a development branch,
# or negative for a release candidate or beta (after the base version
# number has been incremented)

> I updated the Linux install via apt tied to PPA and updated the windows fat client.

I assume it is working now? Thanks :)

**Comment by spikefishjohn** [comment]
Yeah, its been a long day. Really odd. I'll revert the change and see if the error comes back.

**Comment by spikefishjohn** [comment]
: |

No errors after revert. Closing case!
