### ISSUE TITLE
Is the Gns3 Version 3.0 a1 Created to Run gns3 VM on a different remote machine 

### ISSUE THREAD

**Issue by aksplease** [GNS3/gns3-server#2093]
hi ,Jeremy,

i am not able to connect Gns3 3.0 a1 version with Gns3 Vm running in VMWARE in same windows machine (win-11/vmware workstation 16.4.2 ).
so is this version build to connect gns3 vm running on a different server machine ?

![image](https://user-images.githubusercontent.com/11521667/183157984-57b99967-5f4e-4157-baf9-ca181e572ca3.png)
![Error-1](https://user-images.githubusercontent.com/11521667/183158132-3ccb6a79-ee9b-47c8-a2eb-bb54ad233a6d.jpg)
![Error-2](https://user-images.githubusercontent.com/11521667/183158141-ca2b0690-d9c1-4569-8050-49083c789a4a.jpg)

**Comment by grossmj** [comment]
It should work, what have you configured in the preferences?

You should have something similar to this:

![Screenshot from 2022-08-28 16-44-59](https://user-images.githubusercontent.com/4752614/187079939-08337832-d386-4372-8165-8825f1edc65c.png)
