### ISSUE TITLE
Snmpd on the gns3 vm for gns3 version 3 please

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2095]
I messed up this post by not following the "suggestion template. Sorry.

it up. This should be a suggestion:

/etc/rc.d/init.d/snmpd status
bash: /etc/rc.d/init.d/snmpd: No such file or directory
service snmpd status
Unit snmpd.service could not be found.

re: https://github.com/GNS3/gns3-server/issues/2092

I would need "snmpd" on the gns3 vm to handle situations like 2092.
I do have a "GNS3-VM-exp" (i.e. exp is for experimental), but I am not putting snmpd on my main gns3 vm.

As far as putting snmpd on the main GNS3 VM that is distributed to thousands of gns3 users is concerned, that is not my call.

But, if snmpd is running on the main gns3 vm, then I should be able to obliterate 2092 in an effortless fashion.

So, as far as OID value: 1.3.6.1.2.1.2.2.1.1, I might need some public access to whatever ports a node is running on. When i mean public access, it has to be an official documented way to access what a port a node is running in, as opposed to me going in and reverse engineering something.

Edit: Hrmmmm...I will go with GNS3-VM-snmpd for now. Yeah. That's the way for me to go.

**Comment by josephmhiggins** [comment]
Dragging in two gns3-endhost I get

sudo netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:45085           0.0.0.0:*               LISTEN      59472/ubridge       
tcp        0      0 0.0.0.0:44519           0.0.0.0:*               LISTEN      59719/ubridge   

Well, maybe such a public function exists to get....
oh...i will check the docs on that:
https://gns3-server.readthedocs.io/en/stable/endpoints.html

**Comment by josephmhiggins** [comment]
No, it is too much of a security risk to add snmpd to 1000s of gns3 vm's.

Yes, the port number a node on an interface uses is not accessible in the gns3 api documentation for nodes or links.
I would **need** a 'get' function in the gns3 code to get me the port number an interface is using.

**Comment by josephmhiggins** [comment]
Hold.

let me put 2 ubuntu devices (ubuntu-ssh-snmpd) in a gns3 project on a gns3 vm in vmware workstation on windows 10 and reverse engineer the network to get the tcp ports. i will just manually get the tcp port numbers.

then let me see if i can get powershell to inspect the devices remotely and get the input and output rate with something like
new-object -com
i have never done it before but i think i can figure out how to do it in under 8 hours.

**Comment by josephmhiggins** [comment]
Oh, I will use new-object -comobject as a backup.
I will grab the snmp data directly via the gns3 cloud and ssh.......well I hope so anyway.

**Comment by grossmj** [comment]
Ok, let me know if you need snmpd on the GNS3 VM, I guess I could just add it...

**Comment by josephmhiggins** [comment]
Some gns3 users get upset in the community over security. They might get upset. gns3-vm-snmpd is perfectly fine for me.

**Comment by josephmhiggins** [comment]
and the gns3 vm console is expensive real estate so i would not add it into the gns3 vm console menu.

**Comment by spikefishjohn** [comment]
> Ok, let me know if you need snmpd on the GNS3 VM, I guess I could just add it...

Could always add it but not start it.

I don't run the VM but couldn't you always just add it via apt as well assuming the GNS3 VM has internet access?

**Comment by josephmhiggins** [comment]
oh yeah, i forgot that some people do not have access with their gns3 vm.
if you think it will not hurt anything to add snmp and not start it, then that would be safe.
i have internet access.

**Comment by grossmj** [comment]
> if you think it will not hurt anything to add snmp and not start it, then that would be safe.

Done :)
