### ISSUE TITLE
lots of failing tests with pytest-asyncio-0.19.0

### ISSUE THREAD

**Issue by mm1ke** [GNS3/gns3-server#2096]
Hi,

I'm having some troubles with the gns3 tests with the latest `pytest-asyncio` (0.19.0 to be precise). Many tests start to fail with errors like `AttributeError: 'coroutine' object has no attribute '_create_netmap_config'`. Running these tests with `pytest-asyncio-0.18.3` works without any failed tests.
I had a look at the changes for `pytest-asyncio` and the only breaking changed seemed to be the change to use `strict mode` by default, see: https://github.com/pytest-dev/pytest-asyncio/pull/380
Another hint in this direction seems to be: https://github.com/pytest-dev/pytest-asyncio/issues/390
However, i really have no idea if that is the case here, but i hope this can be fixed somehow, otherwise i would need to restrict the pytest-asyncio version on gentoo. While it would work as a temporally fix, it's also frowned up and only would make it more difficult in the future.

Our bug report with additional information can be found here: https://bugs.gentoo.org/863770

**Comment by grossmj** [comment]
Thanks for reporting this. My quick guess is that we haven't explicitly marked all the tests that are coroutines with `@pytest.mark.asyncio` and now the strict mode enforces it.

I will check soon and fix this soon.

**Comment by seifertm** [comment]
Sorry that the pytest-asyncio update causes trouble, but it was necessary.

The old behavior (_legacy mode_) caused compatibility problems for projects that wanted to support multiple async frameworks. We deprecated legacy mode at the beginning of this year and switched the default mode to _strict_ in v0.19, which requires tests and fixtures to be explicitly marked.

Here's the relevant section in the docs:
https://github.com/pytest-dev/pytest-asyncio/tree/v0.19.0#modes

**Comment by grossmj** [comment]
@mm1ke is this issue for version 3.0 or 2.2.x?

@seifertm no worries, we understand :)

**Comment by mm1ke** [comment]
@grossmj this happens with 2.2.x

**Comment by grossmj** [comment]
Fixed for both 3.0 and 2.2.x
