### ISSUE TITLE
GNS 3.0 server Error adding metadata-usb-re.img

### ISSUE THREAD

**Issue by zorklabs** [GNS3/gns3-server#2097]
During adding new vMX image according to instruction https://docs.gns3.com/docs/how-to-guides/importing-vmx-and-vqfx-into-gns3/#importing-the-split-vm-public-releasestrials-of-vmx
I'm unable to add metadata-usb-re.img
```
2022-08-17 06:55:43 INFO gns3server.utils.images:319 Writing image file to '/root/GNS3/images/metadata-usb-re.img'
2022-08-17 06:55:43 ERROR gns3server.api.server:90 Controller error: Could not save image 'metadata-usb-re.img': Could not detect image type, please make sure it is a valid image
```

Also, as other metadata* images.

**Comment by grossmj** [comment]
Currently, we only allow qcow2 and vmdk images for Qemu images. I am not sure we should allow 'raw' images since, unlike qcow2/vmdk, we cannot detect if this is a valid image or not.

One workaround would be to convert your images to use qcow2 using `qemu-img convert`

**Comment by grossmj** [comment]
> That excludes 32 appliances from the registry, including Cisco IOSv

We allow raw images when installing appliances.

**Comment by grossmj** [comment]
The idea behind not allowing raw images is to prevent users to upload files to the controller that aren't meant to run in GNS3 as this could be considered a security problem. Am I overthinking?

**Comment by grossmj** [comment]
> With 2.x there were no limitations, so I am concerned that not allowing raw images might surprise some users and maybe even limit the functionality. But maybe the security advantages might outweight these limitations. As I'm still using v2.2.x I have not enough knowledge to help with this decision.

I agree with you, I think I will leave it as an option for the server/controller admin and allow raw images by default.

One alternative could be to automatically try to convert an uploaded raw image to qcow2 and reject if it fails. What do you think of this idea?

**Comment by Raizo62** [comment]
On LiveRaizo, i convert the Debian Image VM  from qcow to "raw" format because I relied on this [discussion](https://serverfault.com/questions/677639/which-is-better-image-format-raw-or-qcow2-to-use-as-a-baseimage-for-other-vms)

> I think I will leave it as an option for the server/controller admin and allow raw images by default.

It will be a good idea :-)

**Comment by grossmj** [comment]
> One alternative could be to automatically try to convert an uploaded raw image to qcow2 and reject if it fails. What do you think of this idea?

This doesn't work. You can actually convert anything (i.e. a PDF file) to a qcow2 image using qemu-img. There are no magic check that it is a valid RAW image... We have to allow raw images by default
