### ISSUE TITLE
Qemu binary field is empty for New QEMU VM template (CentOS Stream 8)

### ISSUE THREAD

**Issue by rodrigodesf** [GNS3/gns3-server#2100]
Hi,
I´m trying to create a new QEMU VM template, but when asking for choosing Qemu binary, the field (Qemu binary) is empty.

my system: 
$ cat /etc/redhat-release
CentOS Stream release 8

qemu-kvm version:
$ /usr/libexec/qemu-kvm --version
QEMU emulator version 6.2.0 (qemu-kvm-6.2.0-12.module_el8.7.0+1140+ff0772f9)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

GNS3 version: 2.2.33.1

Thank you.

**Comment by grossmj** [comment]
What is the content of your $PATH environment variable?
