### ISSUE TITLE
GNS3v3: add new template

### ISSUE THREAD

**Issue by llevier** [GNS3/gns3-server#2105]
Hello,

I selected debian from GNS3 market place. It requires 2 files:
Debian version 11.4
- debian-11-genericcloud-amd64-20220711-1073.qcow2
- debian-cloud-init-data.iso

I click on download to get both files. Then I import the 1st one (qcow2). While importing, I click on 'import' of the 2nd one, it requests the file name, ok, but at the end only the first one is imported and reclicking, nothing happens.

**Comment by grossmj** [comment]
Is it in the web-ui?

**Comment by grossmj** [comment]
Got no issue, maybe we already fixed this, please try again when we release v3.0.0a3. Thanks.
