### ISSUE TITLE
Projects with a linked virtualbox clone node cannot not be exported. Please use Qemu instead.

### ISSUE THREAD

**Issue by giadagabriele** [GNS3/gns3-server#2112]
I'm on Ubuntu and I wanted to export a GNS3 project but I have this problem... I searched on the web and it seems that nobody knows how to fix it

**Comment by grossmj** [comment]
Well, it just means what is says. You cannot export projects that have VirtualBox or VMware nodes. This is a technical limitation that has no fix at the moment.

I will encourage you to use Qemu based appliances.
