### ISSUE TITLE
Enhancement: gns3_server and profile_active

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2115]
1. I learned how to pull out the gns3_server.ini data from each of the sections that exist in gns3 version 2.2.31. This took a few hours to learn how to do. But when I tried to help a gns3 user running gns3 2.2.34 with VMware player on Windows 11 and I was using gns3 2.2.31 with VMware player 2.2.31 on Windows 10, I learned the format of gns3_server.ini changed was changed and **there was no entries in the CHANGELOG that I could discern that mentioned that change in formatting.**
2. But, the gns3_server.ini in gns3 version 2.2.31 is blatantly an illegal design because all the VMware stuff is scrambled across the gns3*.ini files. The easiest mistake to spot was the variable vmrun_path. That variable should have never been created because Windows is the definitive source on vmrun_path
3. Per Ean, I will let all that slide until gns3 version 3.0.
4. But, the gns3 design as far as the profile looks to be completely invalid - and at this time, I see no reason why this should not exist in some form or another, even in gns3 version > 3.0: gns3 --profile-active
5. However it gets tricky because I *think* there is another variable that is required. Maybe: gns3 --profile-type. I *think* profile-type might need to exist because maybe --profile-active could be null. Someone with some skill would have to look at whether or not --profile-type is valid or how to design it.

As far as me reading gns3_*.ini, when there is no documentation on that stuff, hrmmm, me I would redesign all those files and encode them; e.g. base64 encoding would be enough to implicitly tell users not to illegally read the gns3 developers undocumented configuration files.

My reading of the files and the undocumented files and missing variables just means I have to throw a wrapper in my scripts when getting information from gns3 executables.

In some form or another, I am confident that this is required: gns3 --profile-active

**Comment by josephmhiggins** [comment]
Actually, if all the gns3* configuration files are encrypted - e.g. unreadable, then only the gns3 controller knows all the keys and values. Then --profile-active would not be valid because I would not open up the API until profile-active -notequal to null. Hrmmm.

**Comment by eantowne** [comment]
1. I agree that configuration file key-value pairs documentation should be available and kept updated as changes happen.
2. The existence of the value should not be an issue assuming that the value is being sourced from the operating system. This sourcing should be happening in code, value stored in config. The question then becomes how often should this value be validated and when during the software startup process.
4/5. What is the purpose of the `--profile-active` and `profile-type` that you are proposing? Are these simply parameters that pass the current profile? Specifically, as for `type` are you proposing different types of profiles, and if so, what is the differentiator?

Obfuscating the contents of a configuration file serves no purpose but to make things more difficult. Documenting said configuration files would be the better path. Even without documentation, nothing is served by obfuscating the configuration, and just adds another cycle of processing to the methods for reading the configuration file in order to accomplish encoding changes. It does not stop a nosy user from trying to figure things out.

As an added thought, intentionally designing an application to obfuscate things like configuration files somewhat flies in the face of FOSS concepts, and heads towards proprietary.

These are just my opinions and thoughts.

**Comment by spikefishjohn** [comment]
> I learned how to pull out the gns3_server.ini data from each of the sections that exist in gns3 version 2.2.31. This took a few hours to learn how to do. But when I tried to help a gns3 user running gns3 2.2.34 with VMware player on Windows 11 and I was using gns3 2.2.31 with VMware player 2.2.31 on Windows 10, I learned the format of gns3_server.ini changed was changed and there was no entries in the CHANGELOG that I could discern that mentioned that change in formatting.

If you think something changed in those files it would be helpful to show a before and after.

**Comment by eantowne** [comment]
Ok, I would need to install and compare actual configs generated depending on Player vs. WS to see what the issue is, or is it that something is missing from one? I see the [VMware] block for the WS, but is this what actually happens or what is proposed?

The reason I ask is that while vmrun (VIX API) is not installed by default with Player, it can be installed separately. So then player should also require the [VMware] block.

**Comment by josephmhiggins** [comment]
"vmrun (VIX API) is not installed by default with Player" - It is installed by default with VMware Player 16.2.4
I never installed anything but VMware-player-full-16.2.4-20089737.exe to install vmware player and make it work with gns3.

The vmware block was removed in > 2.2.31 - and I think should have been removed - by the developers

" I would need to install and compare actual configs generated depending on Player vs. WS to see what the issue is" - yeah, me too but that is more based on
https://gns3.com/community/featured/vmware-player-vs-vmware-ws-for-gns3


I have to go afk. This is enough for now

**Comment by josephmhiggins** [comment]
At the core of the "suggestion" is that there have been about 2,000 posts, with respect to VMware - in some form or another - and I have written about 250 replies.

So...I have been trying to figure out why the gns3 developers have not gotten intimately involved with those 2,000 posts during the last 3 years. If the gns3 architect decides that the gns3 developers should not help new gns3 users  because it is architecture decision to let new gns3 users figure things out on their own, well, that is their call. I have struggled this dilemma for 3 years whether to get involved.

When I started coding my powershell script(s), about a month ago, I reached the conclusion that the gns3 developers were not against helping new gns3 users, but rather, the gns3 developer team did not have the resources to deal with new gns3 users having problems with vmware. I reached this conclusion before I saw the change in gns3_server.ini - which confirmed my conclusion. (Oh, the variable vmrun_path on mac may be valid in gns3_server.ini - i know nothing about a mac. But the variable vmrun_path on windows is completely illegal)

Gns3 users, and vmware itself, are very clever in finding new ways to hose up vmware for gns3. The hitters in the last 4 years are, with my statements as SWAGs,
1. there was a bug in vmware workstation 15 somewhere, and no gns3 user ever troubleshot this, that forced a gns3 user to disable/enable vmnets; I have never seen this bug personally and I only suspect that it was vmware ws 15 with no proof
2. (this is not a SWAG) Windows Device Manager Error code 31 when upgrading to vmware ws 16 from vmware ws 15 - I know about this - I have tracked this down in CIM Win32_PnPEntity class; I will obliterate this (there is a bug in Windows .NET documentation - I have it documented); this is very close to iron-tight.
3. a possible "new" one with putting the GNS3 VM on OneDrive,
4. oh, a suspect new one in that a Windows ACL points out that gns3 is owned by the account built-in adminstrators - this has thrown me for a loop I do not know what that means for gns3 is owned by the account built-in administrators. Julien wrote years ago that gns3 was not supposed to be run in admin mode. I will have to investigate this. This is very complicated and a long story.
5. oh yeah, and as far as hyper-v and vmware conflicting somehow; I have no idea how hyper-v works and I will not be able to learn how it works for the rest of the year.

So, my powershell script can troubleshoot things, if and only if, I get some action with
"gns_server --some_variable" or something like that anyway - for all the key value pairs in gns3_gui/server/controller.

I do not want to read flat files - I view that as illegal.

**Comment by josephmhiggins** [comment]
I looked at it again. I can do everything on my own with powershell and vmware player and the vmware rest api.

With vmware workstation....if they only have the vm named GNS3 VM, then I can do everything that I want to do with powershell and the vmware rest api.

I do not think anyone has multiple copies of the gns3 vm like me. (Strictly speaking, they have to be archived/moved within..."24 hours" so as not to hose up a backup.

There are other things that are illegal (in gns3 controller), but per Ean, I will wait for 3.0

I think I will close this out after I rethink it because illegal designs are not user impacting.

**Comment by josephmhiggins** [comment]
Yep.
I think I have everything I need to do what I want to do.
I will deal with gns3 version 3.0 and vmware 17 when it comes along.
I found the vmware15 bug.
I will deal with microsoft bad documentation about CIM_LogicalDevice (or learn c# to investigate if it is a powershell bug that causes ConfigErrorCode and ConfigManagerUserConfig to not be found via Get-Member in -Namespace root\standardcimv2 -ClassName CIM_LogicalDevice, but it appears in Namespace root/cimv2 -ClassName Win32_PnPEntity).
As far as anything else is concerned, I do not know python so there is nothing I can do.
