### ISSUE TITLE
Block Enhancement: timestamp in gns3 config files

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2116]
Embedding a timestamp in any of the gns3 config files would cause a nightmare.
Do not embed timestamps in the the gns3 config files.

So, I will explain. I have a pre-gns3 and a post-gns3 in my powershell script to start gns3.
Long story, but I partially explain here before I explain it another thread I will post for a requested enhancement.
My post-gns3 backs up all the gns3 config files and the gns3 log files (dealing with the gns3 log files is another thread that I am not prepared to write up now).
My post-gns3 causes many, many unnecessary files to be backed up. I figured out how to solve this problem around 8 months ago and promptly forget the solution.

But the solution is found in "Windows PowerShell Best Practices" by Ed Wilson, Chapter 1. The book text, follows, and is tangential to how I will solve my problem - if and only if no timestamps are included in the config files - "Not every device is backed up each day. I have no way of knowing what the latest time stamp will be in each recursive directory"

For my script:
the file hashes of the config files can be determined in pre-gns3 and then calculated post-gns3. Consequently, I will only have to backup the config files that have changed.

This is a very, veryt big deal to me.

**Comment by eantowne** [comment]
Pardon my query, but but what are you asking for?

The title of this issue intimates that you are asking for timestamps to be added to GNS3 config files. You then go on to state that doing so would be a nightmare (I agree by the way).

**Comment by josephmhiggins** [comment]
Oh, suggest a new title for the post and I will try to change the title - but I do not know how to change a title of the post on github so it might take me a while to do that.

**Comment by eantowne** [comment]
The title itself is not the issue. (heh "issue", see what I did there?). What is the "Issue" (bug, problem, enhancement) that you are asking for the Devs to examine? If you are simply trying to have a conversation, [Discussions](https://github.com/GNS3/gns3-server/discussions) might be a better avenue.

Your submitted issue does not articulate any specific enhancement that you are asking the Devs to implement.

- Issue
- Discussion
- Recommendation

**Comment by josephmhiggins** [comment]
Oh.
Discussions. Hrmm. I never read that. Okay. Let me thing how I will handle this thread.

**Comment by josephmhiggins** [comment]
This thread has been "moved" to Discussions with a new title per Ean: https://github.com/GNS3/gns3-server/discussions/2118

@Ean, I read the titles of the posts in the Discussions; they are not great titles either.

The title over there is good enough for me.

This is closed.
