### ISSUE TITLE
Suggestion: For Windows, offer an option to put the gns3 config files and log files outside of %home%\AppData

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2117]
This is a big deal.

One of the ways you can restore Windows wipes out all the data in %home%\AppData
One of the other ways you can restore Windows does not wipe out all the data in %home%\AppData

The solution shows up when you upgrade/install Van Dyke SecureCrt. The software asks you where you want to install the SecureCrt config files. The default will be somewhere in  %home%\AppData and the other directory is of your choosing.

Well, needless to say, I once chose to restore Windows in a way that wiped out all my AppData (but I was backing up my gns3 config files in a script in powershell so they were all safe), but it wiped out scrores of Securecrt data. The securecrt data was created the wrong way and someone in the GNS3 community, circa Feb 2022, explained how to use Perl to deal with this problem. In short, with powershell and securecrt and the gns3 api, I will easily be able to solve this problem.

The problem is backups of %home%

A backup, even on a daily basis, of %home% which includes Appdata takes about **hours and hours** to do on Windows 10 because older Windows 10 uses junction points - unless someone spends about 4 hours to remove all the junction points (I removed all my junction points in Appdata).

A daily backup of %home%, excluding the directory where the GNS3 VM and AppData takes **15 seconds**.

Obviously, if I download a new VM template before I make a backup, makes the backup take 3 or 4 minutes.

Van Dyke Software permits the storing of Securecrt config data outside of Appdata; GNS3 should follow suit.

As far as backing up any Firefox, Chrome bookmarks or any other program when a Windows user makes a backup, that dilemma is of no concern to me in this post and I will deal with that, maybe ...someday, in the GNS3 Community.

**Comment by eantowne** [comment]
While I agree that having the ability to change from the default location would be helpful, I am not sure that it is an issue for the vast majority of GNS3 users. This does not mean it is not something the Devs should consider, just not overly impr

Based on your other post and this post, I am going to assume that you are having issues with managing backups of all things GNS3. I am guessing you are using powershell to simply copy relevant files. Have you considered getting/using backup software that can do incremental/differential backups? Are your powershell scripts making use of the archive bit?

**Comment by josephmhiggins** [comment]
My robocopy takes 15 seconds to backup my entire home directory, besides AppData.
The old windows 10 vesion uses junction points.

So with junction points in AppData still resident, to backup a file in %appdata%\gns3, robocopy does this - and this will not be exactly right because I will go by memory - robocopy goes to

%appdata%\gns3,
then it goes to 
%appdata%\gns3\gns3
then it goes to
%appdata%\gns3\gns3\gns3
then it goes to
%appdata%\gns3\gns3\gns3\gns3
then it goes to 
%appdata%\gns3\gns3\gns3\gns3\gns3
then it finally gets to
%appdata%\.....32 * gns3\some_file
and it backs up that file
then it goes back to
%appdata%\gns3\next_file
and goes down 32 directories to save the next_file

That takes a long, long, long time.

As far as setting the archive bit, I can not test that to see if it would have prevented that because I spent 4 hours deleting all my junction points.

I am extremely confident my robocopy works perfectly.

**Comment by josephmhiggins** [comment]
To delete all the junction points - again this is not exactly right, I had to go to all the directories and then go down to 
appdata\31 * somedir
and them remove 32 * somedir
and then to up to 30 * somedir
and them remove 31 * somedir
.etc
That took a long, long time to do.

**Comment by josephmhiggins** [comment]
This will be a won't fix because I can handle this with a pre-gns3 and a post-gns3 AND the gns3 configuration files can be in about 5 or 6 different directories....there is no sense adding another place where the gns3 configuration files can be.
