### ISSUE TITLE
Installtion from sources on ubuntu importlib.metadata.PackageNotFoundError: gns3-server

### ISSUE THREAD

**Issue by elico** [GNS3/gns3-server#2124]
I am installing gns3-server on couple linux distros from sources on a similar Makefile script like this one:
https://gist.github.com/elico/e4c29f3a7c640511bd8bcfcf9c4ff087

Basically I am cloning the repo, building and trying to start the service.

When I am trying to start the gns3server I am receiving the next error:
```
# /usr/bin/gns3server
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 33, in <module>
    sys.exit(load_entry_point('gns3-server==2.2.34', 'console_scripts', 'gns3server')())
  File "/usr/bin/gns3server", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: gns3-server
```

It does work when I am installing the gns3-server package from pip

The main difference between the installation from sources to the installation from pip is that the next directories are not preset:
```
/usr/local/lib/python3.8/dist-packages/gns3_server-2.2.34.dist-info/
/usr/local/lib/python3.8/dist-packages/gns3server/
```

This is the installation output( Was too long to quote):
https://gist.githubusercontent.com/elico/68ef7a3f5ce8de56f2d5acee6edb48b5/raw/d7072ac5c413e4c2403cdb9a1aac3de8a6209c52/stdout

**Comment by grossmj** [comment]
Do you still have the issue? No sure what the problem is but you should install the gns3 packages like this:

`cd gns3-server && python3 -m pip install -r requirements.txt && python3 -m pip install .`

**Comment by elico** [comment]
@grossmj I will try to verify with the new version.
You can see what I am using at the script at:
https://gist.github.com/elico/e4c29f3a7c640511bd8bcfcf9c4ff087#file-makefile-L28

**Comment by elico** [comment]
@grossmj This indeed works now.
The docs should be fixed/upgraded.

Thanks!

* this should be closed when the docs will be updated.

**Comment by grossmj** [comment]
No worries, which page of the docs should be updated?

**Comment by grossmj** [comment]
@elico ping :)

**Comment by elico** [comment]
@grossmj Lets close this issue since I couldn't find this specific document.

**Comment by elico** [comment]
@grossmj I have found the docs which mentioned the wrong way of installing the package:
https://github.com/GNS3/gns3-server/blob/master/README.rst

look for the install and you will see "setup.py" which shouldn't be there.
