### ISSUE TITLE
Image management does not detect images properly in GNS3 3.0.0 alpha 2

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-server#2126]
**Describe the bug**
Image management does not detect images properly in GNS3 3.0.0 alpha 2

**GNS3 version and operating system (please complete the following information):**

OS: ArchLinux
GNS3 version: 3.0.0 alpha 2
GNS3 server and GUI are running on same machine (bare metal)

**To Reproduce
Steps to reproduce the behavior:**

I have my images organized under different folders inside GNS3/images/ named Qemu,VirtualBox,VMware,IOL,Docker

1. Start gns3server manually from CLI
2. After some time I see the server use some autodiscovery process to detect all the images located under GNS3/images folder
3. The process scans also the Docker folder located under GNS3/images/Docker which has my Docker images and it detects all binary files in there as IOU images.
4. In GNS3 GUI go to File --> Image Management.
5. On the Images dialog box I see a hundreds of Linux binary/executable files being detected as IOU images.
![image](https://user-images.githubusercontent.com/7124193/194723677-39d39183-e1ec-47b0-afe3-0960ecba8b06.png)

**Comment by grossmj** [comment]
> After some time I see the server use some autodiscovery process to detect all the images located under GNS3/images folder

Maybe we should not have an autodiscovery? An user triggered discovery with a final validation of what images to keep could be a solution but this harder to implement.

OR

We restrict the auto discovery to only scan the `GNS3/images/QEMU`, `GNS3/images/IOS` and `GNS3/images/IOU` directories. Much easier to implement.

**Comment by josephmhiggins** [comment]
Lil dangerous here.
17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso

Is not a very descriptive filename.

Win2k16_14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US.ISO
Is too long of a filename.

So I promptly changed the filename to:
W2016

and recorded the entry in a spreadsheet.
Then I lost the spreadsheet. So, I got mad for breaking a rule and deleted all my images to ensure I never did that again.

The .gnsa files have a user friendly name and it knows the filenames. GNS3 users should not be going in the directory that are under control of the gnsa file, e.g. the GNS3/images/ (and btw, one of my books says it is illegal to put the .md5sum file in the same directory as the files they have the md5 hash for - but that's another story).

I do not know the purpose of File - Image Management; it looks bogus.

One caveat is, I never thought about Docker images. I know almost nothing about Dockers.

**Comment by grossmj** [comment]
> We restrict the auto discovery to only scan the GNS3/images/QEMU, GNS3/images/IOS and GNS3/images/IOU directories. Much easier to implement.

I implemented this and also added an option to disable image discovery entirely
