### ISSUE TITLE
Problems with GNS3, and VirtualBox 7. Project corrupted

### ISSUE THREAD

**Issue by txutxifel** [GNS3/gns3-server#2132]
I upgrade Virtualbox to version 7 and I got a lot of problems.  I have some MV added.
it I try to open an  project a got this kind of error:

![Screenshot_20221023_085950](https://user-images.githubusercontent.com/4577294/197379620-b56c1758-3afc-44e7-bb80-d20f65395b2c.png)

I tried to find a solution "differential disk" are unregistered in Virtualbox, so MV cant start. Another example:

Working in a proyect:
![uuid2](https://user-images.githubusercontent.com/4577294/197379704-6a93765f-f1b9-4f97-9ee3-9403ff759a7b.png)

If a close the project, differential disk are missing:

![uuid](https://user-images.githubusercontent.com/4577294/197379717-9416e31a-66b4-4eed-8048-2c9ea31f0060.png)

**Comment by grossmj** [comment]
I installed VirtualBox 7 and I cannot see any issue. Was it working better before version 7?

Also, have you selected the "Use a linked base VM" in your VirtualBox templates?

![Screenshot from 2023-01-18 08-50-37](https://user-images.githubusercontent.com/4752614/213053970-1a8f286c-5ae0-4859-8027-8ab422ac7741.png)

**Comment by txutxifel** [comment]
First, 
thanks for answering.

I did more tests.
#######################################
This happend to me always in Windows (11)  always.  
Yesterday I did an upgrade from Virtualbox 6.1.40 to Virtualbox 7.06 (newly released) and upgrade to 2.3.36.  Proyects worked in 6.1.40.

With the upgrade, I lost all "differential disk" in vmware.

![Captura de pantalla 2023-01-18 091152](https://user-images.githubusercontent.com/4577294/213121482-5c37377a-3d5a-4703-9934-6eac6489cffc.png)
#######################################33
I also have same proyect in Linux, and its more stable, but now ( virtualbox 7.06) crash  always with same MV, i have always this error and I have to  readded it.

![Screenshot_20230118_094937](https://user-images.githubusercontent.com/4577294/213125748-649cbb6e-c2a6-4766-93ba-73cccfcf20c1.png)

#########################################

In general, I don't know what happened. 

I work as a teacher, and I use GNS3 in my classes.  Most  of my students don't have any problem. One, got all their proyects corrupted  (with 6.1.40 too). 

###########################################
Yes, there are all linked

![Screenshot_20230118_095548](https://user-images.githubusercontent.com/4577294/213127003-f30d50b1-d7e7-4998-80d0-7c1049fb5ac4.png)


Thanks

**Comment by josephmhiggins** [comment]
virtualbox 7.0.6 and virtualbox 7.0.8 on windows 10 had so many problems that I uninstalled it.
7.0.10 looks very impressive.
the virtualbox community is extremely impressive.
i would suggest an upgrade on virtuablox and opening a ticket with the virtualbox folks so they could look at your virtualbox logs.

**Comment by txutxifel** [comment]
Thanks for answering!

I finally change to virtualization all in a server. My students have access a GNS3 machine  (QEMU) with all images inside, so I didn't try in a long time.

I hope anyone have same problem

Cheers

**Comment by grossmj** [comment]
Thanks again for reporting this. Qemu is definitely the way to go since VirtualBox VMs as a linked base VM has always been experimental. I am going to close this for now. Maybe someday we put more efforts to support VirtualBox, we prefer to focus on having a strong Qemu support at the moment.
