### ISSUE TITLE
docker image fails to start

### ISSUE THREAD

**Issue by zccing** [GNS3/gns3-server#2134]
**The following English is machine translation, you can refer to the picture to understand, I am very sorry to cause you trouble**

I can't start the docker image whose User is a number  
![image](https://user-images.githubusercontent.com/35253469/202229385-32feb3e0-50a1-4089-bfd7-dbb293ed53ae.png)
![image](https://user-images.githubusercontent.com/35253469/202234449-20c5db32-8288-4b14-b29e-2016f02541e7.png)

I try to add `GNS3_USER=$(cat /etc/passwd | grep ${GNS3_USER-root} | awk -F: '{print $1}')` to the penultimate line of [https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/docker/resources/init.sh](https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/docker/resources/init.sh), and the docker image can be normal;

![image](https://user-images.githubusercontent.com/35253469/202231158-49eecb64-62fa-4e4e-820c-33300b4fe358.png)

Please check if this is a bug, thanks

**Comment by zccing** [comment]
I modified it again

```sh
case "$GNS3_USER" in
  [1-9][0-9]*)
    export GNS3_USER=$(cat /etc/passwd | grep ${GNS3_USER-root} | awk -F: '{print $1}')
    ;;
  *)
    ;;
esac
```

![image](https://user-images.githubusercontent.com/35253469/202463648-21fba007-2258-42e8-89df-f46c21c109d3.png)

**Comment by grossmj** [comment]
Thanks a lot for your contribution, I have added your code.
