### ISSUE TITLE
Bug when use remote gns3server listening on IPv6 ::

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#2143]
Hi

I use the last GNS3 v2 (on 2 LiveRaizo)

On the Linux Server with the IPv6 2001:db8:10::1/64, i start gns3server with the command `/usr/bin/python3 /usr/bin/gns3server -A -L --host ::`

On the Linux Client with the IPv6 2001:db8:10::2/64, i configure gns3-gui to use the remote Server

On the Client, i put a VPCS, i have no error, and i can start it

Now, i put a Cisco router. I have an error and this log : 

> 2022-12-10 12:10:12 INFO __init__.py:303 Creating new hypervisor :::42191 with working directory /home/user/projects/66e164b8-1ff0-4500-a2b8-37742d697d33/project-files/dynamips
> 2022-12-10 12:10:12 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i1_log.txt', '-H', '42191']
> 2022-12-10 12:10:12 INFO hypervisor.py:129 Dynamips process logging to /home/user/projects/66e164b8-1ff0-4500-a2b8-37742d697d33/project-files/dynamips/dynamips_i1_stdout.txt
> 2022-12-10 12:10:12 INFO hypervisor.py:136 Dynamips process started PID=2345
> 2022-12-10 12:10:12 INFO __init__.py:305 Hypervisor :::42191 has successfully started
> 2022-12-10 12:10:19 INFO web_log.py:206 2001:db8:10::2 [10/Dec/2022:12:10:19 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.36.dev2"
> 2022-12-10 12:10:22 ERROR route.py:221 Node error detected: DynamipsError
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/gns3server/web/route.py", line 200, in control_schema
>     await func(request, response)
>   File "/usr/local/lib/python3.9/dist-packages/gns3server/handlers/api/compute/dynamips_vm_handler.py", line 72, in create
>     vm = await dynamips_manager.create_node(request.json.pop("name"),
>   File "/usr/local/lib/python3.9/dist-packages/gns3server/compute/base_manager.py", line 259, in create_node
>     await node.create()
>   File "/usr/local/lib/python3.9/dist-packages/gns3server/compute/dynamips/nodes/router.py", line 213, in create
>     self._hypervisor = await self.manager.start_new_hypervisor(working_dir=self.project.module_working_directory(self.manager.module_name.lower()))
>   File "/usr/local/lib/python3.9/dist-packages/gns3server/compute/dynamips/__init__.py", line 306, in start_new_hypervisor
>     await hypervisor.connect()
>   File "/usr/local/lib/python3.9/dist-packages/gns3server/compute/dynamips/dynamips_hypervisor.py", line 90, in connect
>     raise DynamipsError("Couldn't connect to hypervisor on {}:{} :{}".format(host, self._port, last_exception))
> gns3server.compute.dynamips.dynamips_error.DynamipsError: Couldn't connect to hypervisor on ::1:42191 :[Errno 111] Connect call failed ('::1', 42191, 0, 0)
> 2022-12-10 12:10:22 INFO web_log.py:206 ::1 [10/Dec/2022:12:10:12 +0000] "POST /v2/compute/projects/66e164b8-1ff0-4500-a2b8-37742d697d33/dynamips/nodes HTTP/1.1" 409 401 "-" "Python/3.9 aiohttp/3.8.3"
> 2022-12-10 12:10:22 INFO web_log.py:206 2001:db8:10::2 [10/Dec/2022:12:10:12 +0000] "POST /v2/projects/66e164b8-1ff0-4500-a2b8-37742d697d33/templates/990676ac-97ce-4d54-a607-bc9ea1457322 HTTP/1.1" 409 368 "-" "GNS3 QT Client v2.2.36.dev2"

**Comment by grossmj** [comment]
This doesn't work because of a security issue:

See https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/dynamips/hypervisor.py#L207L213 and https://github.com/GNS3/dynamips/issues/62

Hopefully we can fix that problem for the next release.

**Comment by grossmj** [comment]
Fixed
