### ISSUE TITLE
reconsider importlib_resources dependency

### ISSUE THREAD

**Issue by mm1ke** [GNS3/gns3-server#2147]
Hi,

I was looking into updating gns3-{server,gui} for gentoo. However, i've noticed some dependency changes. Usually that's not a problem but the newly introduced importlib_resources made me some headaches.
The package itself would be available on gentoo, however only for python 3.8.
Now i was curious and looked a bit more into it. Please bare in mind, this is only how i see it right now - not sure if that is correct.
As far as i see the package importlib_resources are only backports of newer python versions for older ones. This means, this dependency would lock gns3-server on python3.8. Not what we want at all..

Is there any reason why importlib_resources is requirement?
I've checked the sources and made a patch to use  pythons internal implementation, which looks as following:
```
diff --git a/gns3server/controller/__init__.py b/gns3server/controller/__init__.py
index 5c5236b9..25ba4f67 100644
--- a/gns3server/controller/__init__.py
+++ b/gns3server/controller/__init__.py
@@ -22,7 +22,7 @@ import uuid
 import socket
 import shutil
 import aiohttp
-import importlib_resources
+import importlib.resources
 
 from ..config import Config
 from .project import Project
@@ -284,7 +284,7 @@ class Controller:
                     if not os.path.exists(os.path.join(dst_path, filename)):
                         shutil.copy(os.path.join(resource_path, filename), os.path.join(dst_path, filename))
             else:
-                for entry in importlib_resources.files('gns3server.configs').iterdir():
+                for entry in importlib.resources.files('gns3server.configs').iterdir():
                     full_path = os.path.join(dst_path, entry.name)
                     if entry.is_file() and not os.path.exists(full_path):
                         log.debug(f"Installing base config file {entry.name} to {full_path}")
diff --git a/gns3server/controller/appliance_manager.py b/gns3server/controller/appliance_manager.py
index d15fc69b..7cd826e9 100644
--- a/gns3server/controller/appliance_manager.py
+++ b/gns3server/controller/appliance_manager.py
@@ -21,7 +21,7 @@ import json
 import uuid
 import asyncio
 import aiohttp
-import importlib_resources
+import importlib.resources
 import shutil
 
 from .appliance import Appliance
@@ -99,7 +99,7 @@ class ApplianceManager:
                     if not os.path.exists(os.path.join(dst_path, filename)):
                         shutil.copy(os.path.join(resource_path, filename), os.path.join(dst_path, filename))
             else:
-                for entry in importlib_resources.files('gns3server.appliances').iterdir():
+                for entry in importlib.resources.files('gns3server.appliances').iterdir():
                     full_path = os.path.join(dst_path, entry.name)
                     if entry.is_file() and not os.path.exists(full_path):
                         log.debug(f"Installing built-in appliance file {entry.name} to {full_path}")
diff --git a/gns3server/utils/get_resource.py b/gns3server/utils/get_resource.py
index b4b599bd..6214ea46 100644
--- a/gns3server/utils/get_resource.py
+++ b/gns3server/utils/get_resource.py
@@ -19,7 +19,7 @@ import atexit
 import logging
 import os
 import sys
-import importlib_resources
+import importlib.resources
 
 from contextlib import ExitStack
 resource_manager = ExitStack()
@@ -37,8 +37,8 @@ def get_resource(resource_name):
     if hasattr(sys, "frozen"):
         resource_path = os.path.normpath(os.path.join(os.path.dirname(sys.executable), resource_name))
     else:
-        ref = importlib_resources.files("gns3server") / resource_name
-        path = resource_manager.enter_context(importlib_resources.as_file(ref))
+        ref = importlib.resources.files("gns3server") / resource_name
+        path = resource_manager.enter_context(importlib.resources.as_file(ref))
         if os.path.exists(path):
             resource_path = os.path.normpath(path)
     return resource_path
```

This would eliminate the importlib_resources dependency. gns3-server starts as expected and tests pass too...

Now my skills with python are really basic and i have no idea if these changes have any implications, but otherwise i don't see how i can update gns3-server on gentoo.

**Comment by grossmj** [comment]
Hi,

Didn't you get an issue with calling `importlib.resources.files()`? This is because according the Python doc, it was only introduced in the Python 3.9 stdlib: https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files

> Is there any reason why importlib_resources is requirement?

The goal is to make it easier to manage and not rely on the Python stdlib because as shown above, one of the importlib function we use is only available in Python >= 3.9

So by only using `importlib_resources` >= 1.3, we are sure it would work in all the Python versions we support (3.6 to 3.11)

See https://pypi.org/project/importlib-resources/

**Comment by mm1ke** [comment]
> Hi,
> 
> Didn't you get an issue with calling `importlib.resources.files()`? This is because according the Python doc, it was only introduced in the Python 3.9 stdlib: https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files
> 
> > Is there any reason why importlib_resources is requirement?

Probably because i'm only having python 3.10 and 3.11 installed?
FYI, on gentoo only python 3.8 and newer are available, and python 3.8 and 3.9 is already considered deprecated for gentoo (and thus it should be avoid to push new packages with these versions).

> 
> The goal is to make it easier to manage and not rely on the Python stdlib because as shown above, one of the importlib function we use is only available in Python >= 3.9
> 
> So by only using `importlib_resources` >= 1.3, we are sure it would work in all the Python versions we support (3.6 to 3.11)
> 
> See https://pypi.org/project/importlib-resources/

I see why you want to use it. Out of curiosity, how does this work with newer python versions.
Since they have their own implementation, wouldn't gns3 always try to use python <3.9, since these version don't have their implementations and thus would use importlib_resources? Or can a newer python version use these backports as well even though it has its own implementations?
Is there some way to decide that if a user has a newer python version, choose to use the internal implementation?

At least on gentoo i cannot install the dependency without pulling a old python version (with all it's dependencies) and still let gns3 run with a newer python version - it would be restricted to 3.8.
Besides that i think i already would have problems with the other dependencies (since python 3.8,3.9 get already phased out). And I'm pretty sure no dev would push my updates.

I could also use the patch in order to use the newer implementations and thus support newer python versions only, but i think it would be nice to find a better solution for the package.

**Comment by grossmj** [comment]
> I see why you want to use it. Out of curiosity, how does this work with newer python versions.
Since they have their own implementation, wouldn't gns3 always try to use python <3.9, since these version don't have their implementations and thus would use importlib_resources? Or can a newer python version use these backports as well even though it has its own implementations?

Newer versions of Python can use the backport but you are right, they can just use their own implementation. So now I only install the backport for Python <= 3.9 (`importlib-resources>=1.3; python_version <= '3.9'`)

This should solve your dependency problem on Gentoo. Let me know if you still have an issue after we have released the next version (2.2.36)

**Comment by mm1ke** [comment]
Sorry for the late reply.

That sounds good but i'm not sure if that would fix the issue completely. 
Unless there is some logic in the sources, newer python versions would still error since the sources still call `importlib_resources.files` instead of `importlib.resources.files`?
Or do i miss something here?

**Comment by grossmj** [comment]
That should be alright because the stdlib importlib is used if the back-ported one isn't installed.
 https://github.com/GNS3/gns3-server/blob/d0141c351b8eac5a8b19355574074a44b44f359e/gns3server/controller/__init__.py#L26L29

**Comment by mm1ke** [comment]
Ahh, yes, that should be good then. Sorry, i didn't saw the actual commit.

**Comment by grossmj** [comment]
No worries, let me know if I have solved your issue :)

**Comment by nuqleo** [comment]
importlib.resources is available in python 3.9, so maybe instead of <= '3.9' should be < '3.9' in
```
importlib-resources>=1.3; python_version <= '3.9'
```

**Comment by grossmj** [comment]
@nuqleo 

This is correct when reading the doc however the is a bug in importlib-resources when running with Python 3.9

```
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/__init__.py", line 298, in install_resource_files
    for entry in importlib_resources.files(f'gns3server.{resource_name}').iterdir():
  File "/usr/lib/python3.9/importlib/resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "/usr/lib/python3.9/importlib/_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "/usr/lib/python3.9/importlib/_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "/usr/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by nuqleo** [comment]
In CentOS 8 with python 3.6.8 available package python3- importlib-resources but no such package in CentOS 9 with python 3.9.16.
Is 'import importlib_resources' actually works with python 3.9?

**Comment by grossmj** [comment]
I have updated the way we access the resources in PR https://github.com/GNS3/gns3-server/pull/2290 and it works now. We can now have `importlib-resources>=1.3;  python_version <= '3.9'`

Thanks 👍

**Comment by nuqleo** [comment]
gns3-gui also have in requirements.txt
```
importlib-resources>=1.3; python_version <= '3.9'
```

**Comment by grossmj** [comment]
This should have been changed already in https://github.com/GNS3/gns3-gui/commit/10afb5a8deb25b85c26c38d1f9639ba833dd0000
