### ISSUE TITLE
GNS3 template: specify "on close" option

### ISSUE THREAD

**Issue by giangi** [GNS3/gns3-server#2148]
Hello,

I cannot seem to find any GNS3 template exemplifying how to set the "On close" (node `on_close` option), or any reference of such setting in schemas. This was already asked in GNS3/gns3-registry#441, which is marked closed by @grossmj , but I did not find any clue on the implementation.

It seems to me that this would be useful, e.g. to pre-set the value to sending ACPI shutdown for appliances that support it, e.g. to better guarantee data integrity by performing a cleaner shutdown.

Is there something I missed?

**Comment by grossmj** [comment]
> Is there something I missed?

No we may have just forgot to add it. It should be good now.

Thanks! 👍
