### ISSUE TITLE
[2.2.36, 3.0] Docker VMs: DHCP addresses are not assigned to the interface

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-server#2159]
GNS3 version: 2.2.36 and 3.0
For Docker VMs DHCP addresses are requested (when told to do so), but not assigned to the interface.

Reason: The stock busybox patch (PR #1908 and #2154) doesn't run the udhcpc wrapper script in /gns3/bin, but directly executes the stock busybox udhcpc binary. That's because the wrapper script is not set executable.
Fix: In the gns3-server source `chmod +x gns3server/compute/docker/resources/bin/udhcpc`, then reinstall

**Comment by dkrasnove** [comment]
Thanks, I was wondering why all my Docker containers stopped working. Is there a quick workaround for 2.2.36?
