### ISSUE TITLE
Import/Export for IOU nvrams

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#216]
https://community.gns3.com/ideas/1769

**Comment by grossmj** [comment]
Implemented in https://github.com/GNS3/gns3-server/commit/ca331ae2a5efbe36ce1c7f3200adfbac40d0c3d1

Some in depth testing will be needed.

@ehlers let me know if you make changes to https://github.com/ehlers/IOUtools

Thanks a lot for this! it offers much more flexibility to play with IOU.
