### ISSUE TITLE
GNS3 Bug?

### ISSUE THREAD

**Issue by mgarland12** [GNS3/gns3-server#2161]
Yes.Just tried to open a project again and received this same error again but has different port number.This worked Monday of this week and ? Reinstalled twice No data returned from localhost:51644 after sending command 'hypervisor version
', uBridge process running: True.Help!!

**Comment by grossmj** [comment]
Is this something you are experiencing only in this version? Does your project contain cloud connections?

**Comment by mgarland12** [comment]
Just a 3-tier lab  downloaded from gns3 lab. Teresa is one edge router but no claudia. Washington configuring triste Last Monday and tiene yesterday this
