### ISSUE TITLE
Server appliance list empty on clean install on Linux

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-server#2168]
OS: Linux Mint 21.1 (also noticed on Pop-OS)
Kernel: 5.15.0-58-generic
GNS3 Version: 2.2.36
Installation method: PPA

Clean install of gns3-gui via PPA, when an attempting to import a new appliance via Template(from server), there are no entries in the list. Clicking "Update from online registry" resolves the issue. The registries .gns3a files are installed however in:
`/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/appliances/`

Steps to reproduce:

- Clean install of GNS3 via PPA on Ubuntu based distro
- Start GNS3 client
- Click File
- Click New Template
- Click Next (Install an appliance form the GNS3 server)
- No entries listed under any category

![no-appliances-1](https://user-images.githubusercontent.com/66289315/212772634-08b02ed5-2996-4ff3-a6ef-5e3bf92f0db3.png)

![new-template-after-registry-update](https://user-images.githubusercontent.com/66289315/212772655-9337f026-fff5-4898-804b-708bb15e29d4.png)

**Comment by grossmj** [comment]
Fixed. Thanks 👍
