### ISSUE TITLE
Mark VMware and VirtualBox support as deprecated in v3.0

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#2172]

**Comment by grossmj** [comment]
@eantowne, users will be warned when creating a new VMware or VirtualBox template in v3.

![Screenshot from 2023-02-05 10-05-52](https://user-images.githubusercontent.com/4752614/216797988-5a2dccd2-748f-4984-a857-2a6df99648de.png)

![Screenshot from 2023-02-05 10-04-57](https://user-images.githubusercontent.com/4752614/216797992-cdf75357-81c5-422a-a6c8-75e91b45650a.png)

![Screenshot from 2023-02-05 09-47-56](https://user-images.githubusercontent.com/4752614/216797993-3409a5a3-03cd-480c-85cf-cdeb3bfada69.png)

![Screenshot from 2023-02-05 09-43-41](https://user-images.githubusercontent.com/4752614/216797995-2d88b73b-06e8-48b5-8d38-57c24271bbdc.png)

**Comment by eantowne** [comment]
There are probably more than a few people cursing me right now.

**Comment by josephmhiggins** [comment]
As I just wrote, the point of demarcation is the gns3 cloud.
This is a good design choice.

**Comment by grossmj** [comment]
> Regarding deprecated features, will I [we] still be able to create cloud nodes that run on the local computer and use the VMnet interfaces?

Starting with version 3.0, the GNS3 server will only run on Linux. That means cloud nodes will only work on Linux too (in the GNS3 VM or a remote Linux computer).

I would recommend staying with version 2.2.x if your lab requires access to local VMnets ouside the GNS3 VM.
