### ISSUE TITLE
HTTP2 Support

### ISSUE THREAD

**Issue by wangziyao318** [GNS3/gns3-server#2173]
It would be nice to have a config option in `gns3_server.conf` to use HTTP2 when HTTPS is enabled. HTTP2 would surely improve the network performance between GNS3 server and client.

**Comment by grossmj** [comment]
In version 3.0, we use Uvicorn, which is an HTTP server, to serve our REST API. Uvicorn stated they won't support HTTP/2: https://github.com/encode/uvicorn/issues/47 however I think it would be easy for us to use other HTTP servers like hypercorn which supports HTTP/2 and even draft HTTP/3, see https://github.com/pgjones/hypercorn or any other Python  ASGI HTTP server.
