### ISSUE TITLE
Bug in vmware pro 16.2.1, et. al. may affect vmware_vm.py

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2176]
These gns3 community posts
https://gns3.com/community/featured/not-able-to-connect-via-local-machine-to-gns3-network-using-vm-player-17-and-gns-2-2-35-1
https://gns3.com/community/featured/hello-i-have-a-problem-with-my-gns3-sesion-are-freezening-after-config-and-going-back-to-the-sesion

I escalated to the vmware community here:
https://communities.vmware.com/t5/VMware-Workstation-Pro/workstation-pro-16-2-1-shows-incrorrect-ethernet3-connectiontype/m-p/2952403#M179901

Simply put:
I configured a host-only network that was using the same subnet as my loopback address, so my setup in vmware gui shows

vmnet0 bridged

vmnet1 host-only

vmnet8 nat

vmnet 2 host-only

But, in the vmx file it i showed

ethernet0.connectionType = "hostonly"
ethernet1.connectionType = "nat"
ethernet3.connectionType = "custom"

it should say
ethernet0.connectionType = "hostonly"
ethernet1.connectionType = "nat"
ethernet3.connectionType = "hostonly"

vmware_vm.py in gns3 2.2.34 and 2.2.37 i using
connection_type = "ethernet{}.connectiontype".format(adapter_number)

My vmx file shows:
ethernet3.connectionType = "custom"

vmrun.exe shows:
C:\Program Files (x86)\VMware\VMware Workstation>vmrun.exe listHostNetworks
Total host networks: 3
INDEX  NAME         TYPE         DHCP         SUBNET           MASK
1      vmnet1       hostOnly     true         192.168.15.0     255.255.255.0
2      vmnet2       hostOnly     false        192.168.0.0      255.255.255.0
8      vmnet8       nat          true         192.168.83.0     255.255.255.0

C:\Program Files (x86)\VMware\VMware Workstation>

vmrun.exe is correct.
GNS3 VM.vmx is incorrect.

I can not read python, but this function looks to be the problem.
def _set_network_options(self):

**Comment by josephmhiggins** [comment]
I think more than one bridged interface does not work.
I manually set each bridge to a different interface and packets from the wrong interface appear, sometimes incessantly.
That looks to be a gns3 bug.

Vmware; the vmare.log is not helpful at all.

I go through the cloud and Virtual Network Adapters constructed by VMware.
The VMnet numbers do not change.

As far as the vmx file is concerned, there is no documentation on it.
Everything works here with Wireshark running on all interface.

![image](https://user-images.githubusercontent.com/85327995/216749355-f7b5865a-88aa-4374-9172-c71c311df5ff.png)

I do not think anytime should be wasted on this before 3.0 because I do not know how a bridged interface will work in 3.0

I will close it in a few days if, in Windows, Virtual Network Adapter Vmnet2 suddenly jumps to Virtual Network Adapter Vment3

**Comment by eantowne** [comment]
>Everything works here with Wireshark running on all interface.

So is this incorrect labeling of the "type" actually causing the issues being described in the two community posts you reference?

- Do both posts have an **additional** "Host-only" vmnet connected to a loopback? 
    - I am not sure why anyone would do this anyway as the host machine **already** has network access to the VM via the preconfigured "Host-only" network, which also gives a path for "cloud" node access to topology inside GNS3 project). I assume this is some artifact from old David Bombal videos that do not relate to the current iteration of GNS3 using the VM.
- Is this an issue with GNS3 or the hypervisor being used by the user, or perhaps the user having some non-standard implementation that is causing issues?

For the record, I am not saying this is not an issue. I am just trying to ensure that the parameters of the issue are clear.

**Comment by josephmhiggins** [comment]
Umm, the vmx file is constructed by vmware.
They can label the vmnet anything they want in a text file; it's their text file.
To find out what a vmnet is, you have to compare this:

![image](https://user-images.githubusercontent.com/85327995/216778099-e1a85040-7f2e-483e-9881-f67177d15601.png)

to this:

![image](https://user-images.githubusercontent.com/85327995/216778117-15063df8-9201-423c-9ed0-4e956083d893.png)

and this:

![image](https://user-images.githubusercontent.com/85327995/216778134-d9ffd898-ff7d-4189-befa-a98ef6a1a2f5.png)

It's the vmware design of their gui that is troubling and the vmware.log is nothing like gns3_server.log
The vmware.log is indecipherable and to decipher it, I would have to put in a loop, via a script,
load-vmware-xinterfaces.gns3
load-empty.gns3

There are 2 culprits. The gns3 users are using a non-standard configuration and
it appears, for vmware-vms that do not go through the cloud, the vmnets are in "vmwarespace".
Consequently, it appears the gns3 developers can not detect how a vmnet is constructed
so they can not alter the vmnet.
So, the gns3 developers have to break the vmnet and create a new one, or
they have to change the gui to have an invisible cloud.
The gns3 developers have said they are making no changing to the gui.
The gns3 developers could do something like this for any vm in the gui
VM7 - eth0 -- vmnet7
But again no changes to the gui.
Or they could have done something like in the gui
Cloud7 - e2 -- vmnet
But again no changes to the gui.

Comments are permitted in the .ini files.
Vmware does not delete old interfaces in their vmx files, so that is very confusing.

The order which you add interfaces to vmnet also will affect the vmx file and should affect the gns3 cloud.

The order to add interfaces in gns3 for vmware should be:
vmware default, that covers vmnet1 and vmnet8
bombal default, the vmnet bridged to the internet lan connection
gloria default, vmnet2 host-only (custom) which can be used as a "loopback" interface.

At this time, I have to look at if bridging to a loopback even works.
Gloria's concept was great but bridging to a loopback may not work and i have to test it.
And...even it does work, that implementation requires bridging a virtual interface to a virtual interface, that's silly.

People may be looking at bridge to a loopback because of all the "gns3 - windows - loopback" very old videos on youtube.

The .ini files are permitted to have comments ( ; is the comment delimiter)
I can have brand new gns3 install and copy gns3_server.ini to gns3_server_commented.ini and put comments in.

Hopefully, the .vmx files will permit comments in them. I will try it out.



The implementation requirement to change the vmnet by the developers with a vmware-vm looks to be caused by the gns3 users not wanting to use the cloud.

This is definitely not a developer issue per se.

**Comment by josephmhiggins** [comment]
Gloria wanted a vmnet interface bridged a "loopback" because she wanted to do SDN.
She may or may not only have had a wifi adapter that would go down and not enable to do SDN.
Her concept is good.
I am judging it as now the defacto standard vmware design for gns3 < 3.0

**Comment by josephmhiggins** [comment]
This is not a gns3 developer problem
