### ISSUE TITLE
3.0.0alpha 3 - controller can't connect to remote- API auth failure

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-server#2183]
I noticed I can't get a controller to connect to a remote on 3.0.0 alpha 3. I keep getting auth failure. I see basic auth info is being sent.

Debugs  (gns3server -d) don't show anything other then 401 message
`INFO h11_impl.py:480 10.1.12.62:3089 - "GET /capabilities HTTP/1.1" 401`

If I login chrome and hit open the webui it opens fine. 

If I go to 
`http://10.1.18.54:3080/v3/compute/capabilities`
I get 401. I'm thinking maybe this is an issue with roles. I've tied with the default admin user and its still getting the same issue. I tried adding the / permission to admin that i think allows all access as well.

![image](https://user-images.githubusercontent.com/31658656/218262552-fdde98d1-8a7e-44ab-adf5-af35e9da4449.png)

![image](https://user-images.githubusercontent.com/31658656/218262569-3fc21541-1efd-4572-a32d-ec408a64953e.png)

![image](https://user-images.githubusercontent.com/31658656/218262580-0e33e118-3ee3-4ce0-a189-926f02bdffee.png)

**Comment by grossmj** [comment]
> `http://10.1.18.54:3080/v3/compute/capabilities`

The reason you get is because communication between the controller and computes is protected by HTTP basic  authentication.

This is configurable in the `gns3_server.conf` file:

```
; Username for compute HTTP authentication.
compute_username = gns3
; Password for compute HTTP authentication.
compute_password = gns3
```

It must be configured and the same on both the controller and any compute you use.
