### ISSUE TITLE
The file c7200_i0_log.txt is created in the current directory, when using a dynamips device

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-server#2191]
**Describe the bug**
Starting with GNS3 v2.2.37 the file `c7200_i0_log.txt` is created in the current directory, when using a dynamips device.

**GNS3 version and operating system:**
 - OS: Linux Debian 11
 - GNS3 version 2.2.37
 - No GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**
1. Start GNS3
2. Open or create a project with a dynamips device in it
4. The default directory now contains a file named `c7200_i0_log.txt`

**Additional context**

In commit https://github.com/GNS3/gns3-server/commit/c57b0cbb5365d3a5c8bc35235ccd0a5eda7ebd54 the new function `dynamips_version` starts dynamips without any options. That creates this  `c7200_i0_log.txt`. I was able to suppress the creation of that file by setting the invalid platform `-P none`.

Dynamips then shows the following output:

```
$ dynamips -P none
Cisco Router Simulation Platform (version 0.2.23-amd64/Linux stable)
Copyright (c) 2005-2011 Christophe Fillot.
Build date: Jan  2 2023 09:20:46

Invalid platform type 'none'
```

Here the changes in `gns3server/compute/dynamips/__init__.py`:

```
diff --git a/gns3server/compute/dynamips/__init__.py b/gns3server/compute/dynamips/__init__.py
index 73e896e7..c7287638 100644
--- a/gns3server/compute/dynamips/__init__.py
+++ b/gns3server/compute/dynamips/__init__.py
@@ -273,7 +273,7 @@ class Dynamips(BaseManager):
         """
 
         try:
-            output = await subprocess_check_output(dynamips_path)
+            output = await subprocess_check_output(dynamips_path, "-P", "none")
             match = re.search(r"Cisco Router Simulation Platform \(version\s+([\d.]+)", output)
             if match:
                 version = match.group(1)
```

**Comment by grossmj** [comment]
Thanks for catching this! 👍
