### ISSUE TITLE
gns3.com documentation

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2195]
With gns3 3.0 coming out, the gns3.com documentation is outdated.
I have edited with VBA Word primarily for formatting changes, and extremely minor content changes , 48 commercial books as follows:

PS> gci -path .\ -filter *.pptx -Recurse -ErrorAction SilentlyContinue | Select-Object Name

Name                                                              
Ansible Up and Running.pptx                                             
CCDE Study Guide.pptx                                                   
CCNP and CCIE Enterprise Core.pptx                                      
Cisco Firepower Threat Defense.pptx                                     
Cisco ISE for BYOD and Secure Unified Access.pptx                       
Cisco Next-Generation Security Solutions.pptx                           
Designing for Cisco Network Service Architectures-i7.pptx               
Hyperconverged Infrastructure Data Centers.pptx                         
Integrated Security Technologies and Solutions - Volume I.pptx          
Integrated Security Technologies and Solutions - Volume II.pptx         
Network Automation Made Easy.pptx                                       
C# 9 and .NET 5 – Modern Cross-Platform Development.pptx                
Enterprise Application Development with CSharp 9 and .NET 5.pptx        
Git for Programmers.pptx                                                
Practical Git.pptx                                                      
Hardware and Software Support for Virtualization.pptx                   
Mastering KVM Virtualization.pptx                                       
Mastering KVM Virtualization - Second Edition.pptx                      
Hands-on Booting.pptx                                                   
Windows PowerShell Best Practices.pptx                                  
Mastering Windows PowerShell Scripting.pptx                             
PowerShell Cookbook - 4th Edition.pptx                                  
Powershell for SysAdmins.pptx                                           
Mastering PowerShell Scripting - Fourth Edition.pptx                    
Mastering Ubuntu Server Third Edition.pptx                              
Ubuntu Linux Unleashed 2021 Edition.pptx                                
Ubuntu Unleashed 2019 Edition.pptx                                      
Pro Vim.pptx                                                            
mastering_vba_for_microsoft_office_2016.pptx                            
Essential Visual Studio 2019.pptx                                       
Getting Started With Visual Studio 2019.pptx                            
Visual Studio 2019 Tricks and Techniques.pptx                           
Visual Studio Code for Python Programmers.pptx                          
Visual Studio Extensibility Development.pptx                            
Mastering VMware vSphere 6.7.pptx                                       
PowerCLI Cookbook.pptx                                                  
VMware Certified Professional Exam 2V0-21.19.pptx                       
VMware vSphere 6.x DC Design Cookbook Second Edition.pptx               
VMware vSphere Design - 2nd Edition.pptx                                
VMware vSphere Power CLI Reference - Second Edition.pptx                
Group Policy - Third Edition.pptx                                       
Troubleshooting with the Windows Sysinternals Tools.pptx                
Windows 10 Troubleshooting.pptx                                         
Windows Internals, Seventh Edition.pptx                                 
Windows Internals, Seventh Edition, Part 2.pptx                         
Windows Server 2019 Inside Out.pptx                                     
Windows Server Automation with PowerShell Cookbook - Fourth Edition.pptx
Practical Packet Analysis - 3rd Edition.pptx                            

PS> (gci -path .\ -filter *.pptx -Recurse -ErrorAction SilentlyContinue | Select-Object Name).count
48

The gns3.com documentation, as it stands now, is unfixable.
I recommend a push-pull technique and push gns3 < 3.0 back into a "deprecated" stage.

I recommend at "Heading 2" (this might be hard to understand because that is a Microsoft Word phrase)
Preface (heading 2)
   "I want to thank my mom and dad. I want to thank Julien Duponchelle, Bernhard Ehlers.........etc."
Introduction (heading 2)
   "The documentation is presently designed into the follow sections:
   Chapter 1 - choosing a remote server or local server and operating system (heading 2)
   Chapter 2 to x - local server options based on operating system and hypervisor (all heading 2)
   Chapter x + 1 to y remote server options (all heading 2)

ughh...not so easy
..
All the old gns3 edition < 3.0 have to be pushed back to a Heading 2 at the end of the gns3.com 3.0 documentation. So, the end of the gns3.com 3.0 will point to the 2.0 deprecated documentation.

Oh well, some of the gns3 2.0 can be upgraded but some of it is unfixable.
   
Edit: There is nothing I can do with designing the sections. The sections should not be introduced into the middle of the book. The sections must be introduced in the Introduction. @JeremyGrossman, I view this is entirely your responsibility to design the sections. I see no way for me to provide any assistance at this time.

**Comment by eantowne** [comment]
@josephmhiggins 

- This Git repository is the wrong place for issues related to the GNS3 documentation.
- GNS3 Documentation is located in the following repository: [mother/gns3-docs](https://github.com/mother/gns3-docs)

On to your "issue".

>The gns3.com documentation, as it stands now, is unfixable.
- Nothing is beyond fixing. Is there work to be done, yes. Could the documentation structure use a re-work, maybe. "Unfixable", no.

>I recommend a push-pull technique and push gns3 < 3.0 back into a "deprecated" stage.
- Even once version 3.0 is in release, versions prior to 3.0 are still valid and will be used by **many** users for  quite some time.
- You deprecate features or syntax, documentation is archived, there is a difference.

>I recommend at "Heading 2" (this might be hard to understand because that is a Microsoft Word phrase)

- Formatting online documentation presented via web pages is not the same as formatting material for a book.
- The documentation is written in Markdown, and the documentation generally follows a consistent style.

What is the purpose of listing a bunch of MS .pptx files? Is this some sort of resume to prove that you know what you are talking about?

>@JeremyGrossman, I view this is entirely your responsibility to design the sections. I see no way for me to provide any assistance at this time.
- To tag Jeremy in the issue, you would use @grossmj.
- I really do not think that Jeremy needs you to point out to him anything that may or may not be his responsibility.
- If you do not feel that you can help, then don't, but if that is the case, you could have made this issue submission considerably shorter:

`GNS3 documentation requires updates to address changes coming in version 3.0.`
Done, does not even need a body.
