### ISSUE TITLE
busybox missing from path in setup.py

### ISSUE THREAD

**Issue by getzincl** [GNS3/gns3-server#2201]
Busybox is not located at "gns3server/compute/docker/resources/bin/busybox" in the setup.py install script.

I installed this on rhel 9 by installing the EPEL repository, installing busybox, and then pointing a symbolic link at its location.

**Comment by grossmj** [comment]
`gns3server/compute/docker/resources/bin/busybox` has been removed. Users have to install the busybox that comes with their distro.
