### ISSUE TITLE
Wireshark Host requires authentication

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2205]
same, as https://github.com/GNS3/gns3-gui/issues/3357
"Hum, do you have the "protect server with password" option ticked in the server preferences? If yes, can you try without it?"

completely reproducible. it fails when I have the "protect server with password" option ticked
it works when  I have the "protect server with password" option unticked

pcap_stream.py says        self._user = ""  #TODO: finish user authentication support

so...

gns3 2.2.38
GNS3 WebClient launcher version 1.0.0b4
windows 10 host
hypervisor vmware workstation pro 16.2.1

**Comment by grossmj** [comment]
We have this opened in https://github.com/GNS3/gns3-webclient-pack/issues/1
