### ISSUE TITLE
GNS3 cannot connect to GNS3 VM

### ISSUE THREAD

**Issue by Angelique8023** [GNS3/gns3-server#2206]
Both VMware Fusion and SecureCRT are working fine, whenever I open the GNS3, 
- it pops out "uBridge requires root permissions to interact with network interfaces. Set root permissions to uBridge? All admin users on the system will be able to read packet from the network interfaces.", 

- after inputting the password to autherize, it fails with prompts "Could not execute command "osascript -e 'do shell script "chown root:admin /Applications/GNS3.app/Contents/MacOS/ubridge && chmod 4750 /Applications/GNS3.app/Contents/MacOS/ubridge" with administrator privileges'": Command '['osascript', '-e', 'do shell script "chown root:admin /Applications/GNS3.app/Contents/MacOS/ubridge && chmod 4750 /Applications/GNS3.app/Contents/MacOS/ubridge" with administrator privileges']' returned non-zero exit status 1."

- so the "GNS3VM" server shows in grey in server summary, I can only use local server to test.

A newbie for GNS3, appreciate if anyone can help me out. Thanks in advance.

<img width="980" alt="Screenshot 2023-03-20 at 1 06 45 PM" src="https://user-images.githubusercontent.com/53931732/226251788-af57391c-de5a-4fd2-b218-ccdf880218f2.png">
<img width="1332" alt="Screenshot 2023-03-20 at 12 52 36 PM" src="https://user-images.githubusercontent.com/53931732/226251787-18a86a7a-95c4-4df3-bb11-23f1e8f9bfa7.png">

**Comment by Angelique8023** [comment]
Error while creating node from template: Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request POST /projects
Error while getting the list of remote images: Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request GET /dynamips/images
Error while uploading image '/Users/angelique/GNS3/images/IOS/c3640-a3js-mz.124-23.image': Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request POST /dynamips/images/c3640-a3js-mz.124-23.image

**Comment by grossmj** [comment]
Is the GNS3 app in `/Applications`?

**Comment by Angelique8023** [comment]
>  @



> Is the GNS3 app in `/Applications`?

Yes, ii's umder the path MacintoshHD/Applications/GNS3.app

**Comment by Angelique8023** [comment]
@grossmj Yes, ii's umder the path MacintoshHD/Applications/GNS3.app

**Comment by Angelique8023** [comment]
@josephmhiggins Thank you for your information. I tried the suggested steps, but the error shows "0:140: execution error: chown: /Applications/GNS3.app/Contents/MacOS/ubridge: Operation not permitted (1)" following inputting the codes "  sudo osascript -e 'do shell script "chown root:admin /Applications/GNS3.app/Contents/MacOS/ubridge && chmod 4750 /Applications/GNS3.app/Contents/MacOS/ubridge"'  " in Terminal. 


But I could not understand what [Kokouvi Koumassi] suggested as below: 

[Nemanja Poznanovic](https://gns3.com/-/profile/5f75edbfb12edf6584f007ae)
Nov 15 2022 at 4:48am
It says



 execution error: chown: /Applications/GNS3.app/Contents/MacOS/ubridge: Operation not permitted (1)



Help please!


[Kokouvi Koumassi](https://gns3.com/-/profile/5aea6a4d88d27666d409647a)
Nov 15 2022 at 12:46pm[edited]
Can you please copy/paste the command you ran here? In my case, I have already "Terminal" enabled under "Development Tools", then I just copied/pasted:



sudo osascript -e 'do shell script "chown root:admin /Applications/GNS3.app/Contents/MacOS/ubridge && chmod 4750 /Applications/GNS3.app/Contents/MacOS/ubridge"'

Then "ls -l /Applications/GNS3.app/Contents/MacOS/ubridge" looks like this

==

❯ ls -l /Applications/GNS3.app/Contents/MacOS/ubridge

-rwsr-x---@ 1 root  admin  99472 10 Nov 09:40 /Applications/GNS3.app/Contents/MacOS/ubridge

==


[Kokouvi Koumassi](https://gns3.com/-/profile/5aea6a4d88d27666d409647a)
Nov 17 2022 at 12:20pm
I believe iTerm and Terminal also need to be enabled under App Management

**Comment by hyeonk3328** [comment]
[Angelique8023](https://github.com/Angelique8023).  have you fixed this?  I have exactly same issue and wonder if you fixed it. If you did. can you please share ?

**Comment by hyeonk3328** [comment]
I just got it.  Just add iterm or your terminal to System Setting[Preferences] : privacy & security : Full Disk Access

**Comment by Angelique8023** [comment]
> I just got it. Just add iterm or your terminal to System Setting[Preferences] : privacy & security : Developer Tools

@hyeonk3328 sadly it doesn't work for my issue, I added gns3&terminal&VMware to Full disk access and developer tools, the error is still there 
<img width="961" alt="image" src="https://user-images.githubusercontent.com/53931732/229349455-76af406f-88d2-40db-bbe0-9a49a61edca1.png">

**Comment by Angelique8023** [comment]
@grossmj help plssss TT... any advice, plz

**Comment by sazzadcyber** [comment]
Same problem no fix yet?

**Comment by sazzadcyber** [comment]
I got this fix and it worked for me


https://gns3.com/community/discussions/install-error-macos-ventura

**Comment by sazzadcyber** [comment]
To bypass it, we need to grant Terminal "Full Disk Access". As shown in the picture, go to Privacy & Security -> Full Disk Access and enable the terminal you want to use.



Then, run the following command in the Terminal, as implied by GNS3:



sudo osascript -e 'do shell script "chown root:admin /Applications/GNS3.app/Contents/MacOS/ubridge && chmod 4750 /Applications/GNS3.app/Contents/MacOS/ubridge"'

**Comment by Angelique8023** [comment]
> 

Thanks for sharing but still not working for me...

it says 
"Error while getting the list of remote images: Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request GET /dynamips/images
Error while getting the list of remote images: Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request GET /dynamips/images
Error while uploading image '/Users/angelique/GNS3/images/IOS/c3640-a3js-mz.124-23.image': Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request POST /dynamips/images/c3640-a3js-mz.124-23.image"

the GNS3 VM server did not work so the router cannot be added under the GNS3 VM but works on the MAc local server

crycrycry...

**Comment by Angelique8023** [comment]
@sazzadcyber Thanks for sharing but still not working for me...

it says
"Error while getting the list of remote images: Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request GET /dynamips/images
Error while getting the list of remote images: Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request GET /dynamips/images
Error while uploading image '/Users/angelique/GNS3/images/IOS/c3640-a3js-mz.124-23.image': Cannot connect to compute 'GNS3 VM (GNS3 VM)' with request POST /dynamips/images/c3640-a3js-mz.124-23.image"

the GNS3 VM server did not work so the router cannot be added under the GNS3 VM but works on the MAc local server

crycrycry...

**Comment by rimara123** [comment]
Please try, mine is working

% sudo -su

root# chown root:admin /Applications/GNS3.app/Contents/MacOS/ubridge && chmod 4750 /Applications/GNS3.app/Contents/MacOS/ubridge

**Comment by jonyejin** [comment]
@sazzadcyber 's method has worked for me - however I had to run it in "Basic Terminal" instead of "iTerm2". (Or add Iterm2 in Disk Access list.) Easy mistake to make!

**Comment by bit-and-coffee** [comment]
I solved it this way.
1. switch to root user from mac terminal
2. Execute the following command on the terminal
chown root:admin /Applications/GNS3.app/Contents/MacOS/ubridge
chmod 4750 /Applications/GNS3.app/Contents/MacOS/ubridge

The environment is as follows
OS:ventura
GNS3:2.2.40.1

**Comment by grossmj** [comment]
The uBridge permissions issue will be solved in the next release (v2.2.41)
