### ISSUE TITLE
Cannot start containers

### ISSUE THREAD

**Issue by tomas05h** [GNS3/gns3-server#2217]
Hello there!

Starting docker containers fails with:

Docker has returned an error: 400 failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/gns3/init.sh": stat /gns3/init.sh: no such file or directory: unknown

I'm in an updated ubuntu 22.04
Latest gns3 installed 2.2.38 following https://docs.gns3.com/docs/getting-started/installation/linux/
templates with qemu images works just fine inside gns3
docker containers outside of gns3 works just fine

I saw #2069 but it was for a previous version of gns3 and closed a long time ago.

Any ideas?
Thanks!

**Comment by gustavoberman** [comment]
I was helping @tomas05h 
It was a preinstalled docker vía snap that made some interfering 
The install document didn't took that into account 
Had to do:
snap remove docker

**Comment by grossmj** [comment]
Doc changed in https://github.com/mother/gns3-docs/pull/72
