### ISSUE TITLE
Authentication breaks manually started local server support

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#222]
This is because we use urllib to check for an already running local server and since there is no authentication the connection gets HTTP error 401 (Unauthorized) and the GUI ends up starting a local server itself.

https://github.com/GNS3/gns3-gui/blob/master/gns3/http_client.py#L160

Also, changing the server IP address in the preferences restart the local server but after all requests are unauthorized.

**Comment by noplay** [comment]
I make a fix for the start issue. But I think one day we should think about dropping urllib. It's error prone to have this
