### ISSUE TITLE
Docker: HTTP tunnel stops working

### ISSUE THREAD

**Issue by Kentzo** [GNS3/gns3-server#2224]
The issue can be reliably reproduced with the [ntopng-2](https://www.gns3.com/marketplace/appliances/ntopng-2) appliance.

After you open the HTTP console, the web ui works for about 10-20 seconds and then breaks. Further attempts to reconnect will hang indefinitely.

**Comment by grossmj** [comment]
HTTP console support was missing. I have added it in https://github.com/GNS3/gns3-web-ui/commit/37e6921ffbada8503754dcf82e46c8ff69576927

Please try again after we release v2.2.40

**Comment by Kentzo** [comment]
I was not using the web-ui though, just the GNS3 app. The console action opened the browser and used the right http address which loaded appliance's web UI. It just stopped responding after 10-20 seconds. However, it remained available when accessed directly using the IP of appliance's docker instance (via curl from within the VM and via browser from the host since I bridge the second adapter of GNS3-VM).

**Comment by grossmj** [comment]
Thanks, I am gonna have a closer look.

**Comment by grossmj** [comment]
> The issue can be reliably reproduced with the [ntopng-2](https://www.gns3.com/marketplace/appliances/ntopng-2) appliance.

Quick question not related to this issue, did you update the appliance file to use the `ntop/ntopng:stable` image instead of `ntop/ntopng:latest`? Thanks.

**Comment by Kentzo** [comment]
Had to modify the template to use the stable tag as the latest tag is not available anymore.

**Comment by grossmj** [comment]
> Had to modify the template to use the stable tag as the latest tag is not available anymore.

Ok thanks, no problem with the default credentials?

**Comment by grossmj** [comment]
This is considered fixed since version 2.2.40. Please comment back if there is still an issue. Thanks.
