### ISSUE TITLE
Not able to add any new devices via gui, but able to via web-ui.

### ISSUE THREAD

**Issue by georgemilev91** [GNS3/gns3-server#2242]
Hello, 
Recently i have noticed that i am not able to add new devices via the gui, but i can via the webui. Ubuntu 23.04, 2.2.4.0.1/. I have attached a screencast of the issue. GNS3 does not show any errors or whatsoever.
[Screencast from 2023-06-12 16-38-33.webm](https://github.com/GNS3/gns3-server/assets/80395563/267a813a-d2a9-4ce4-b34d-c37fd62d3416)

**Comment by grossmj** [comment]
@georgemilev91 how have you installed GNS3, just using our PPA packages? thanks

**Comment by georgemilev91** [comment]
> @georgemilev91 how have you installed GNS3, just using our PPA packages? thanks

Hello, yes, following the guide from the website. :) I have done this at least 3-4 times and everytime the outcome is the same....

**Comment by georgemilev91** [comment]
I have tried, no debugs are shown when i try to drag and drop something from the gui, but from the webui i have logs:
![image](https://github.com/GNS3/gns3-server/assets/80395563/ea4cad34-0cb5-4094-8503-d1ff82c58dd6)

**Comment by grossmj** [comment]
Very strange, please can you make a quick video showing that behavior while the debug is activated? Thanks :+1:

**Comment by georgemilev91** [comment]
> Very strange, please can you make a quick video showing that behavior while the debug is activated? Thanks 👍

Hey, sure thing in the evening I will make a screencast of this

**Comment by georgemilev91** [comment]
Here you go.
[Screencast from 2023-06-20 18-03-37.webm](https://github.com/GNS3/gns3-server/assets/80395563/2051e6ba-1e41-415e-ab73-a3694964af7c)

**Comment by georgemilev91** [comment]
Hi Jeremy, would you please let me know if you have had the chance to look into this? Not that i cannot use gns3, but to be honest it's pretty annyoing like this. :)

**Comment by georgemilev91** [comment]
Hello Jeremy, I would like to share with you that this morning i decided to try again and now it's working, there were some recent updates on the ubuntu, more than one, but i have nod paid attention what it was...

**Comment by grossmj** [comment]
> Hello Jeremy, I would like to share with you that this morning i decided to try again and now it's working, there were some recent updates on the ubuntu, more than one, but i have nod paid attention what it was...

Hum very strange, that would indicate a bug/problem in one of our dependency...

I have added some debug messages and I am suspecting an issue with the drop event (mime type).

If it ever happens again, please can you try the latest development version of the GUI? Thanks :+1:

```
git clone https://github.com/GNS3/gns3-gui
git checkout 2.2
cd gns3-gui
python3 -m venv venv
source venv/bin/activate
python3 -m pip install -r requirements.txt
python3 -m pip install PyQt5
python3 -m gns3
```

**Comment by georgemilev91** [comment]
> > Hello Jeremy, I would like to share with you that this morning i decided to try again and now it's working, there were some recent updates on the ubuntu, more than one, but i have nod paid attention what it was...
> 
> Hum very strange, that would indicate a bug/problem in one of our dependency...
> 
> I have added some debug messages and I am suspecting an issue with the drop event (mime type).
> 
> If it ever happens again, please can you try the latest development version of the GUI? Thanks +1
> 
> ```
> git clone https://github.com/GNS3/gns3-gui
> git checkout 2.2
> cd gns3-gui
> python3 -m venv venv
> source venv/bin/activate
> python3 -m pip install -r requirements.txt
> python3 -m pip install PyQt5
> python3 -m gns3
> ```

Hello, yes, if it happens again i will run the provided commands and let you know for the outcome. Thanks!
