### ISSUE TITLE
Boot loop when launching Qemu appliance router template

### ISSUE THREAD

**Issue by rudolphos** [GNS3/gns3-server#2245]
Windows 10. Using VirtualBox 7.0.8 GNS3 VM and GNS3 2.2.40.1.
Current GNS3 VM configuration:
![image](https://github.com/GNS3/gns3-server/assets/4366810/0706609e-3d0f-4247-b4b9-1df08167be8f)

Boot loop:
![ezgif com-gif-maker](https://github.com/GNS3/gns3-server/assets/4366810/8d01206d-e994-4066-928e-49b37c34d295)

This particular loop is caused after launching MikroTik CHR template:
```
iPXE (http://ipxe.org) 00:06.0 CD00 PCI2.10 PnP PMM 3FF8C5F0 3FECC5F0 CD00
iPXE (http://ipxe.org) 00:07.0 CE00 PCI2.10 PnP PMM 3FF8C5F0 3FECC5F0 CE00
iPXE (http://ipxe.org) 00:0A.0 D100 PCI2.10 PnP PMM 3FF8C5F0 3FECC5F0 D100
iPXE (http://ipxe.org) 00:08.0 CF00 PCI2.10 PnP PMM 3FF8C5F0 3FECC5F0 CF00
iPXE (http://ipxe.org) 00:0B.0 D200 PCI2.10 PnP PMM 3FF8C5F0 3FECC5F0 D200
iPXE (http://ipxe.org) 00:09.0 D000 PCI2.10 PnP PMM 3FF8C5F0 3FECC5F0 D000
iPXE (http://ipxe.org) 00:0C.0 D300 PCI2.10 PnP PMM 3FF8C5F0 3FECC5F0 D300
Booting from Hard Disk...
Load system
SeaBIOS (version 1.13.0-1ubuntu1.1)
Machine UUID 862c7d93...
Booting from Hard Disk...
```

Edit:
I changed Configure template > HDD tab > Disk interface: `virtio` to `IDE`, but it also had no effect. The boot loop continued.

**Comment by grossmj** [comment]
Which Qemu template?

**Comment by rudolphos** [comment]
MikroTik CHR 7.8 (chr-7.8.img)

**Comment by grossmj** [comment]
I have updated our appliance file to include v7.10.1 and I had no issues booting this version.

![Image](https://github.com/GNS3/gns3-server/assets/4752614/6d43c892-80cc-40fb-aa02-1b020f269fa0)

I haven't tried with the VM though, my Qemu version is 6.2.0 and the VM is 4.2.1

**Comment by grossmj** [comment]
Tried on the VM, version 7.10.1 worked.

![Screenshot from 2023-07-06 18-05-33](https://github.com/GNS3/gns3-server/assets/4752614/702073ad-3037-4e27-964e-7e7c95b672ef)
