### ISSUE TITLE
How to find the best value of idlepc with web ui?

### ISSUE THREAD

**Issue by wkshare** [GNS3/gns3-server#2249]
I use gns3 UI, but i don't understand how to setting idlepc and how to ...

Do you have any docs to explain it?

**Comment by josephmhiggins** [comment]
i thought the need to run idlepc was fixed about 5 years ago.
Are you running the gns3 vm?
I have not run idlepc in about 9 years.

**Comment by grossmj** [comment]
Sorry, this is not supported in the web-ui yet. Please use the desktop GUI for this.
