### ISSUE TITLE
`allowed_interfaces` server configuration not respected by cloud node

### ISSUE THREAD

**Issue by jessetane** [GNS3/gns3-server#2256]
When creating a link to a cloud node, the port list includes host interfaces that are disallowed by the server configuration's `allowed_interfaces` setting. Selecting a port that is not allowed does not generate any error in the ui but crashes a gns3server subprocess called ubridge.

**Comment by grossmj** [comment]
Please do you have screenshots? thanks.

**Comment by grossmj** [comment]
Also, what is your `allowed_interfaces` setting?

**Comment by jessetane** [comment]
I noticed you transferred this issue from the web_ui, but I think it might be important to note here that I am only using the web_ui and not the native client.

Anyhow, my config looks like this: `allowed_interfaces = br0`. I went to grab you some screenshots and I noticed that now it appears to be working correctly and only shows `br0` in the port list dropdown. That seemed strange so I figured I would just comment the line in my config e.g. `; allowed_interfaces = br0` and restart the server to see if there was any difference, but there was not - none of the other interfaces on the host machine show up as they did before I originally added this config.

So what's happening here? Does the web_ui javascript get rebuilt to take this config into account or something? And that rebuild happens at some time other than server start up? Let me know if there is anything else I can try to help debug.

**Comment by grossmj** [comment]
> So what's happening here? Does the web_ui javascript get rebuilt to take this config into account or something? And that rebuild happens at some time other than server start up? Let me know if there is anything else I can try to help debug.

It should work however you have to restart the GNS3 server itself after changing `allowed_interfaces`.
