### ISSUE TITLE
Could not detect format for disk image - QEMU - Qcow2

### ISSUE THREAD

**Issue by SamuelLasgi** [GNS3/gns3-server#2260]
GNS3 Version: GNS3 v2.2.40

Operating System: Windows

Community link: https://gns3.com/community/support/could-not-detect-format-for-disk-image-qemu-qcow2

Hello,

Since few weeks I've got below errors while booting some devices :

Could not detect format for disk image: /home/gns3/GNS3/images/QEMU/csr1000v-universalk9.16.12.03-serial.qcow2

error while starting CiscoIOSv15.6(2)T-1: Could not detect format for disk image: /home/gns3/GNS3/images/QEMU/vios-adventerprisek9-m.vmdk.SPA.156-2.T

Could not detect format for disk image: /home/gns3/GNS3/images/QEMU/vios-adventerprisek9-m.vmdk.SPA.156-2.T

May you please guide me to the resolution or let me know, should you need any add. infos.

Thank you.

Sam.

**Comment by grossmj** [comment]
Hi,

I think you have downloaded a corrupted image. I downloaded the same version as you and found no issue running it in GNS3:

```
qemu-img info csr1000v-universalk9.16.07.01-serial.qcow2 
image: csr1000v-universalk9.16.07.01-serial.qcow2
file format: qcow2
virtual size: 8 GiB (8589934592 bytes)
disk size: 844 MiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false
```

![Image](https://github.com/GNS3/gns3-server/assets/4752614/c4ffa38b-cf67-4e29-b34b-c319e9bdd1c3)

![Image](https://github.com/GNS3/gns3-server/assets/4752614/8275baab-da98-414f-9b43-5c09e909ae05)
