### ISSUE TITLE
SSL error on Ventura ?

### ISSUE THREAD

**Issue by FlyingThaCat** [GNS3/gns3-server#2264]
GNS3 management console.
Running GNS3 version 2.2.41 on Darwin (64-bit) with Python 3.9.5 Qt 5.15.2 and PyQt 5.15.7.
Copyright (c) 2006-2023 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Error while getting appliances list: Could not read appliances information from GitHub: Cannot connect to host api.github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]

**Comment by grossmj** [comment]
Thanks for the report. Do you have a proxy or anything that could interfere with the SSL connection to GitHub?

**Comment by FlyingThaCat** [comment]
nope

**Comment by grossmj** [comment]
This may be due to a expired root certificate or similar issue. I am going to investigate. Please make sure your system is up-to-date as well.

**Comment by FlyingThaCat** [comment]
okay, and I'm already try some solution like added some certificates and still doesn't work

**Comment by grossmj** [comment]
Please can you try to run this command in a terminal?

`curl https://api.github.com/repos/GNS3/gns3-registry/contents/appliances`

Thanks.

**Comment by FlyingThaCat** [comment]
![Screenshot 2023-08-05 at 9 12 29 PM](https://github.com/GNS3/gns3-server/assets/95353217/e1a85958-fc2c-4382-9aba-171afa16daf2)
it run successfully

**Comment by grossmj** [comment]
Please can you try this development version https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2023-08-07/2.2/GNS3-2.2.42.dev3.dmg/download and let me know if it solves the issue on your side?

Thanks.

**Comment by grossmj** [comment]
Latest build: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2023-08-08/2.2/GNS3-2.2.42.dev4.dmg/download

I tested on macOS Ventura and eveything seems to work well now. I am going to release v2.2.42 in a next few days.
