### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by lvalero** [GNS3/gns3-server#227]
Hello,

every time i make a snapshot a folder named NAME_initial_files is created besides the "project-files" folder, if i let it here all routers starts with blank config, if i delete the folder all routers take the good configuration

gns3 1.3.4 / IOL

Regards

**Comment by lvalero** [comment]
Actually my project file name is "INE_vr_initial.gns3",under INE_v5_initial-files directory i have "snapshots" but at the same level i have "project-files" directory with another "snapshots" folder, it seems to be a duplicate one

**Comment by lvalero** [comment]
sorry for adding info, but actually the 2 snapshots directory are not exactly the same, i think that there was a change in snapshots handling between 2 versions, and i have that file for quite a long time.

**Comment by grossmj** [comment]
Most likely a compatibility issue with an older version of GNS3.
