### ISSUE TITLE
gns3-server Python 3.12 support?

### ISSUE THREAD

**Issue by mm1ke** [GNS3/gns3-server#2273]
Hi,

I saw with the latest version `gns3` got Python 3.12 support.
I've looked into it but for me it seems it's still missing in `setup.py`
Furthermore, in the git log i saw that Python 3.12 was added with 1ced862c08b5a0623d9ae0f320567c9ae9d86c5b but was immediately remove with 88a1cef21f52a27dacd2df39212b7296c3b819b6
Was that a mistake?

Regards

**Comment by grossmj** [comment]
Hi,

> Furthermore, in the git log i saw that Python 3.12 was added with https://github.com/GNS3/gns3-server/commit/1ced862c08b5a0623d9ae0f320567c9ae9d86c5b but was immediately remove with https://github.com/GNS3/gns3-server/commit/88a1cef21f52a27dacd2df39212b7296c3b819b6

The reason I revert this commit it is that GitHub Actions couldn't find Python 3.12: https://github.com/GNS3/gns3-server/actions/runs/5705040394/job/15459256647#step:3:7 

Only version 3.12.0-rc.1 can be used at the moment but I would prefer to wait for the final version.

**Comment by mm1ke** [comment]
Hello @grossmj 
Thanks for the clarification. As i'm packaging gns3 for gentoo i'll wait too for the final support.

**Comment by grossmj** [comment]
Waiting on aiohttp to release v3.9 with support for Python 3.12: https://github.com/aio-libs/aiohttp/issues/7639

**Comment by grossmj** [comment]
Python 3.12 should be supported now. We are using aiohttp 3.9.0b0 while waiting for the final release.
