### ISSUE TITLE
Bug: Gns3 v2.2.42 "update from online registry" not working

### ISSUE THREAD

**Issue by chifu1234** [GNS3/gns3-server#2284]
Hi guys,
I'm using gns3 v2.2.42. When I click on "update from online registry", I get the following error on the Client:
```
Error while getting appliances list: Client error
```
And on the Server:
```
WARNING route.py:236 Client error
web_log.py:206 xxx.xxx.xxx.xxx [xx/xx/xxxx:xx:xx:xx +0000] "GET /v2/appliances?update=yes&symbol_theme=classic HTTP/1.1" 408 249 "-" GNS3 QT Client v2.2.42"
```
I could not find anything regarding this issue. Do you happen to know how I should debug this issue? My Instance is a freshly installed instant. The Instance is running inside a corporate network. Thus, it uses a forward proxy to connect to the outside.

Cheers and many thanks, Kevin

**Comment by chifu1234** [comment]
I could fix it with downgrading to 2.2.32

**Comment by grossmj** [comment]
Hi,

HTTP error 408 means timeout. Do you have a proxy or anything on your network that could block a request to GitHub?

**Comment by chifu1234** [comment]
Sorry you are right. I had a network because somehow we had two network interfaces inside the gns3-vm. Thanks for ur help. Can confirm that with version v2.2.42 everthing works as expected.
