### ISSUE TITLE
Cannot upload GNS3 appliances

### ISSUE THREAD

**Issue by MaziUche** [GNS3/gns3-server#2295]
I installed GNS3 on Ubuntu with KVM emulator. The installation was successful but the image appliances I uploaded are not working.

I am using virt-manager for managing the virtual machines.
below is a screenshot of my virt-manager with GNS3 VM running. The VM console is running and a ip address is displayed. (console screenshot not available)
![troblesshooting virt-man-dis](https://github.com/GNS3/gns3-server/assets/26911000/d1d01f61-179d-4203-b6c8-ceebe4bd7540)

### I can access the web interface
![trblshooting webgns3](https://github.com/GNS3/gns3-server/assets/26911000/abc4eb8d-870d-4b33-b079-a8f90179cb14)

### Aruba switche image
I download the .ova image from Aruba website, extracted the .vmdk file and converted it to qcow2 using _qemu-img_
I then uploaded through
_edit/preference/Qemu VMs._

When I powered up a switch in a topology, this happen
![trbleshotign - new-aruba 1](https://github.com/GNS3/gns3-server/assets/26911000/f261bb65-a52d-4603-8e4d-bd6bb6e25e96)
then after a blank screen with a blinking prompt.

### Below are my Qemu VM settings
![tbleshoting new-Aruba](https://github.com/GNS3/gns3-server/assets/26911000/61e501a5-ce3f-42d8-89c6-f6f1ad2775f7)

![troubleshooting aruba-test](https://github.com/GNS3/gns3-server/assets/26911000/411754ee-fd9f-4e4e-940c-a9f15f328a99)
![trouble shooting](https://github.com/GNS3/gns3-server/assets/26911000/a54b405e-53ac-4dea-a3f1-314837d3b6f0)

Even going though 
file / import appliance/ upload the gns3a file i got from GNS3 website / install appliance on main server / image 

will give me this error
![error message- arubaOS-CX](https://github.com/GNS3/gns3-server/assets/26911000/993220b0-b35b-4aea-987f-50ba1e92ed8d)

Please can someone help me out.
My main goal is to upload .qcow2 appliances on the GNS3 and run them, since am using KM-Qemu emulation for the GNS3 VM.
If is possible to use other vm files like .vmdk to run appliances on KVM i would be happy to know how.

Thank you in anticipation.

**Comment by grossmj** [comment]
Hi,

I looks like the Aruba appliance doesn't have enough RAM to run: `cannot set up guest memory 'pc.ram': Cannot allocate memory`. Maybe try to reduce the amount of memory in the template settings or allocate more memory for the GNS3 VM.

![Screenshot from 2023-10-24 15-33-17](https://github.com/GNS3/gns3-server/assets/4752614/3cc70fb9-5998-45fb-b4bb-9d74dfae83c3)
