### ISSUE TITLE
"ip cef" should be changed to "no ip cef" in IOU default configs

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-server#2298]
Just noticed, `iou_l2_base_startup-config.txt` and `iou_l3_base_startup-config.txt` both contains `ip cef` command. While it is totally correct for real gear, on IOU it may lead to weird [routing problems](https://www.reddit.com/r/gns3/comments/xjz7fa/routing_does_not_work/). Just caught this bug once again. One quote from myself on that reddit: "Interesting fact, buggy IOU image with `ip cef` can, for example, pass ping and silently drop TCP traffic. There were posts ... on reddit ..., and even on Cisco's Learning Network (despite the fact that IOU isn't official thing)."

So, in my opinion, it is better to put `no ip cef` in GNS3 IOU example configs (with some comment like `! Try to change this if your routing does not work`). From my understating `ip cef` on IOU is more buggy than `no ip cef`. What do you think?

**Comment by grossmj** [comment]
Done, thanks 👍
