### ISSUE TITLE
Whats the properway to do networking on the host

### ISSUE THREAD

**Issue by Eldiabolo21** [GNS3/gns3-server#2302]
Hi people, 

So when I started using gns3 i noticed that appliances which connect to the outside via the "Cloud" are limited to roughly 120kbit/s. 
A colleague found out this seems to be related to the fact, that gns3 binds directly to the interface of the host.
When I configure a bridge on the host, gns3 binds to this one and speed will be whatever is available. 

However, upgrades fail when a bridge i is present, also see #2222 
If the configuration is restored to the slow one, update goes through, and bridge can be reconfigured afterwards. 

Of course this is no way to run gns3 and updates. So I'm wondering should I not configure bridges, is there a different way to ensure proper bandwidth beyond the host? I couldn't find anything in the docs. Or does the upgrade script need to be fixed? 

Thanks you!
Best
Fabian

**Comment by Xatrekak** [comment]
I add a second NIC to the GNS3 server, enable it without DHCP, and use that second interface to connect appliances to the cloud node.

**Comment by spikefishjohn** [comment]
I run GNS3 with 1 interface trunked.

I bridge to vlans for access to the GNS3 process or to give a VM access to a general access VM network. I if I want a GNS3 node to be configured as a trunk then i bridge them to the pychical interface.

```
bridge trunk   == eth0
bridge gns3    == eth0.10 (vlan 10)
bridge compute == eth0.20 (vlan 20)
```

bridge gns3 is where I assign IP for general access to the server.
