### ISSUE TITLE
gns3server.modules.dynamips in ghost_ios_support RuntimeError: generator ignored GeneratorExit

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#231]
https://app.getsentry.com/gns3/gns3-server/group/66533652/

```
RuntimeError: generator ignored GeneratorExit
  File "./gns3-server\gns3server\web\route.py", line 140, in control_schema
  File "./gns3-server\gns3server\handlers\api\dynamips_vm_handler.py", line 76, in create
  File "./gns3-server\gns3server\modules\dynamips\__init__.py", line 356, in ghost_ios_support
```

**Comment by noplay** [comment]
I'm not sure about this error. But from what I read I think we catch GeneratorExit when we should not catch it.

Perhaps here:
https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/dynamips/__init__.py#L130

Or here:
https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/dynamips/__init__.py#L154

**Comment by grossmj** [comment]
GeneratorExit directly inherits from BaseException instead of Exception since it is technically not an error. Anyway, I catch it where suggested now.
