### ISSUE TITLE
gns3-server - cannot download gns3-netifaces

### ISSUE THREAD

**Issue by ak2766** [GNS3/gns3-server#232]
I've just tried to build the latest GNS3 Server but I'm failing with the following error:
<pre>
Installed /usr/local/lib/python3.4/dist-packages/gns3_server-1.3.5dev1-py3.4.egg
Processing dependencies for gns3-server==1.3.5dev1
Searching for gns3-netifaces>=0.10.4.1
Reading https://pypi.python.org/simple/gns3-netifaces/
Download error on https://pypi.python.org/simple/gns3-netifaces/: [Errno 104] Connection reset by peer -- Some packages may not be found!
Couldn't find index page for 'gns3-netifaces' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for gns3-netifaces>=0.10.4.1
error: Could not find suitable distribution for Requirement.parse('gns3-netifaces>=0.10.4.1')
</pre>

When I visit the PYPI site, I can see file - <pre>gns3-netifaces-0.10.4.1.tar.gz</pre> - so don't understand why it can't be found!

Cheers,
ak.

<b>UPDATE</b>: I've downloaded the file manually via Firefox and was able to build/install gns3-server.  When trying to download the file via curl (wget had similar issues) - I got the following SSL error:
<pre>
$ curl -v -O https://pypi.python.org/packages/source/g/gns3-netifaces/gns3-netifaces-0.10.4.1.tar.gz#md5=b0d7847d5ceeca95dbe31d5c1df86468
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 103.245.222.223...
* Connected to pypi.python.org (103.245.222.223) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* Unknown SSL protocol error in connection to pypi.python.org:443 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to pypi.python.org:443 
</pre>

**Comment by noplay** [comment]
It seem you have trouble to connect to pypi. Are you behind an enterprise/school proxy?

But no incident on pypi status page:
https://status.python.org/

I close the issue because it's not specific to GNS3.

**Comment by ak2766** [comment]
Hi noplay.

I'm not behind a proxy.  However, I've just found out that when I specify --tlsv1.2 to curl, it manages to download the file!

I do agree, though, that this appears to be an issue specific to my configuration.  Will update if/when I find root cause!

Cheers,
ak.

**Comment by noplay** [comment]
You are under linux ?

**Comment by ak2766** [comment]
Yes - Ubuntu 14.04.2 LTS:
<pre>
$ apt-cache policy curl wget openssl | egrep 'curl|wget|openssl|Installed|Candidate'
curl:
  Installed: 7.35.0-1ubuntu2.5
  Candidate: 7.35.0-1ubuntu2.5
wget:
  Installed: 1.15-1ubuntu1.14.04.1
  Candidate: 1.15-1ubuntu1.14.04.1
openssl:
  Installed: 1.0.1f-1ubuntu2.12
  Candidate: 1.0.1f-1ubuntu2.12
</pre>

ak.
