### ISSUE TITLE
Juniper vQFX on GNS3 VM and GNS3 Server does not pass traffic for neither L2 or L3

### ISSUE THREAD

**Issue by lvpinole** [GNS3/gns3-server#2331]
Juniper vQFX (all versions) on GNS3 VM and GNS3 Server version 2.2.44.1 does not pass traffic for neither L2 or L3

Hello Developers,
I think I run into a GNS3 bug. I have tried to get the Juniper vQFX to work on GNS3, but the vQFX does not pass any L2 neither L3 traffic.  At first I tried on a GNS3 VM (running on both Fusion and ESXi): ping from one vQFX switch to the other vQFX switch (L3 traffic) won't work.  Then I just simply try to ping from VPC1 to VPC2 in the same vlan connect to the same vQFX switch, the ping also failed. I  test it out the vQFX out on GNS3 Server installed on a bare metal, which does not work either.
I have no problem with getting the vQFX to run on EVE NG. So I believe it must be a GNS3 bug.  I am prefer to use GNS3 over EVE NG because of the GUI is easy to use, and GNS3 works on both MAC and Windows.  
Hopefully, you can help fix the issue.  Thank you very much.
Long

**Comment by spikefishjohn** [comment]
If your still running eve-ng can you provide the output of 
```bash
ps -axwu | grep qemu 
```
and show the qemu line from the qemu process running in a working state?

**Comment by lvpinole** [comment]
Hi John,

Thank you so much for following up.

I finally got it working on GNS3.  I notice when I spring up the vQFX for the first time and after configured the ports and IP address, the vQFX often does not pass traffic at all.   However, after configured the vQFX switches and commit the configuration, I run the command request system reboot.  When the switch comes back up, it will be working correctly.  Sometimes, I have to reboot it twice with the command request system reboot to get the vQFX to work.

Once again thank you very much for making the GNS3 such a wonderful tool.  It not only helps me learn a lot, but also helps me building a virtual testing environment for my job as a network engineer.


Long Vu

**Comment by grossmj** [comment]
Excellent, thanks for the info 👍
