### ISSUE TITLE
Maybe is worth to wait to Ubuntu 24.04 LTS to launch GNS 3.0?

### ISSUE THREAD

**Issue by q2dg** [GNS3/gns3-server#2333]
Last Ubuntu LTS will provide most updated packages (I'm thinking of Podman, for instance).
Is it worthy the wait?
Thanks!

**Comment by grossmj** [comment]
Thanks, we will release a new GNS3 VM once 24.04 LTS is out.

**Comment by q2dg** [comment]
Thanks! I'll close this issue then ,as you have planned this. Thanks!
