### ISSUE TITLE
Effectively avoiding mouse offset issues in QEMU

### ISSUE THREAD

**Issue by z5241248** [GNS3/gns3-server#2335]
Adding the following sentence can effectively avoid the mouse offset issue in QEMU, and the current testing situation is good

command.extend(['-machine', 'usb=on', '-device', 'usb-tablet'])

![图片1](https://github.com/GNS3/gns3-server/assets/56920068/2f3ff4b1-7005-4814-9ac1-acc319d2bdbc)

**Comment by grossmj** [comment]
> command.extend(['-machine', 'usb=on', '-device', 'usb-tablet'])

Maybe we should only add this when the console is set to "vnc" or "spice"?

**Comment by z5241248** [comment]
Yes, thank you very much.

I only tested on VNC, but after adding this sentence, using Spire did not result in any errors. We can add a judgment before that.

```python
# avoiding mouse offset
if self._console_type == "vnc":
    command.extend(['-machine', 'usb=on', '-device', 'usb-tablet'])
return command
```

![1](https://github.com/GNS3/gns3-server/assets/56920068/9405757d-ca1b-4ca5-9016-1d2d97df0127)

**Comment by grossmj** [comment]
Merged, thanks 👍
