### ISSUE TITLE
Please release an "ISO installer" version of GNSVM besides the disk-centric images

### ISSUE THREAD

**Issue by q2dg** [GNS3/gns3-server#2348]
Thanks!

**Comment by eantowne** [comment]
There are additional methods for installation provided by the development team and listed docs.gns3.com.

However to be more specific in your request:

Are you requesting an .iso for bare metal installation resulting the equivalent of the GNS3 VM, but bare metal? Or something else?

**Comment by q2dg** [comment]
YES, exactly! That's what I'd like to do: install GNSVM on a bare metal machine to serve several client systems in a classroom. Thanks!

**Comment by eantowne** [comment]
I believe the intent from the developers is that if you want to install on bare-metal:

- Install Ubuntu server from Ubuntu server .iso
- Install GNS3 server via PPA (or pip) https://docs.gns3.com/docs/getting-started/installation/linux
- Install docker engine (if desired) https://docs.docker.com/engine/install/ubuntu/
- enable service to auto-start GNS3 server process

Profit!

The idea being that the VM is an all-in-one (ish) solution for those on a laptop/desktop. Server install can be customized as to need. This also gives the option of you using a different Linux distro (conceivably) if you so desire. Important to note that the Devs only provide the builds for PPA and pip.

**Comment by q2dg** [comment]
It's a very reasonable approach. But then, would there be a way to run the (very convenient) ncurses options script? Thanks!

**Comment by eantowne** [comment]
That is a good question.

I believe that the below link takes you to the script involved. Keep in mind that the script is designed around the VM and not a bare-metal implementation.

https://github.com/GNS3/gns3-vm/blob/master/scripts/welcome.py

Once again, the VM is kind of the all-in-one "easy" solution. The bare-metal implementation assumes you are able to administrate a Linux server.

Another alternative is to run the VM on a Hypervisor like ESXi or Proxmox.

**Comment by q2dg** [comment]
Ooh, yeah! Thanks, that is what I wanted!
So I'll put this script on my bare-metal system with gns3-server installed and I'll modify accordingly to my OS.
Thanks a lot. I'll close this issue if you don't mind
