### ISSUE TITLE
Latest FortiGate Images for GNS3

### ISSUE THREAD

**Issue by CookieCr2nk** [GNS3/gns3-server#2356]
Hello,

Is it possible to add  the latest Fortigate Firmware to the File https://github.com/GNS3/gns3-server/blob/master/gns3server/appliances/fortigate.gns3a, so it can be used in GNS3.

Latest Fortigate VM Versions downloadable from Fortinet (https://support.fortinet.com/Download/VMImages.aspx):

- 6.4.15
- 7.0.14
- 7.2.7
- 7.4.3

**Comment by cristian-ciobanu** [comment]
The request needs to be placed here https://github.com/GNS3/gns3-registry not on this repository.

**Comment by CookieCr2nk** [comment]
Thanks, Issue placed on the right repo. https://github.com/GNS3/gns3-registry
