### ISSUE TITLE
DHCP client in Docker VM fails if DHCP server doesn't respond during first 3 discovers

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-server#2357]
**Describe the bug**
Since PR #2355 in a Docker VM the DHCP server must respond within the first 3 discovers, otherwise the DHCP client fails. This was not the case before that PR was merged.

**GNS3 version and operating system (please complete the following information):**
 - OS: Debian Linux v12.5 (bookworm)
 - GNS3 version 2.2.46.dev1
 - Local GNS3 server, no GNS3 VM or remote server

**To Reproduce**
1. Add a Docker VM and connect it to the NAT cloud
2. Suspend the link to the NAT cloud
3. Start the Docker VM and connect to the console
4. The console shows, that the udhcpc process fails after 3 discovers

```
alpine-1 console is now available... Press RETURN to get started.
udhcpc: started, v1.35.0
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: no lease, failing
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/sh
   19 root      0:00 /gns3/bin/busybox sh -c while true; do TERM=vt100 /gns3/bin/busybox sh; done
   34 root      0:00 /gns3/bin/busybox sh
   37 root      0:00 ps
```

**Screenshots or videos**
![project](https://github.com/GNS3/gns3-server/assets/49040325/0e0a88c4-df73-43a9-9146-397f0cd2fb5e)

**Additional context**

The reason is, that PR #2355 doesn't copy the whole resources directory hierarchy, only the contents of the top directory is copied (and the busybox program is installed).

```
behlers@iMac:~$ tree ~/GNS3/venv/lib/python3.11/site-packages/gns3server/compute/docker/resources
/home/behlers/GNS3/venv/lib/python3.11/site-packages/gns3server/compute/docker/resources
├── bin
│   └── udhcpc
├── etc
│   └── udhcpc
│       └── default.script
├── init.sh
└── run-cmd.sh

4 directories, 4 files
behlers@iMac:~$ tree ~/.local/share/GNS3/docker/resources
/home/behlers/.local/share/GNS3/docker/resources
├── bin
│   └── busybox
├── etc
├── init.sh
└── run-cmd.sh

3 directories, 3 files
```

The files `bin/udhcpc` and `etc/udhcpc/default.script` are missing.

After copying the whole directory hierarchy to the writable location (`cp -a ~/GNS3/venv/lib/python3.11/site-packages/gns3server/compute/docker/resources ~/.local/share/GNS3/docker/`) the DHCP client works as expected.

```
alpine-1 console is now available... Press RETURN to get started.
udhcpc: started, v1.35.0
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc failed to get a DHCP lease
udhcpc: no lease, forking to background
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/sh
   32 root      0:00 /gns3/bin/busybox sh -c while true; do TERM=vt100 /gns3/bin/busybox sh; done
   38 root      0:00 /gns3/bin/busybox sh
   51 root      0:00 /tmp/gns3/bin/udhcpc -s /gns3/etc/udhcpc/default.script -t 3 -T 2 -A 1 -b -R -p /var/run/udhcpc.eth0.pid -i eth0 -x hostname:alpine-1
   55 root      0:00 ps
```

**Comment by grossmj** [comment]
@b-ehlers 

The PR should fix the issue. Please can you check on your side? Thanks 👍
