### ISSUE TITLE
In version 2.2.46, busybox is missing from compute/docker/resource.

### ISSUE THREAD

**Issue by minpeter** [GNS3/gns3-server#2367]
This causes all docker type resources to fail to start.

`/usr/lib/python3.11/site-packages/gns3server/compute/docker/resources/bin`

 It may be related to #1747. thank you :)

**Comment by minpeter** [comment]
### ref:

https://www.gns3.com/community/featured/ipterm-appliance-cannot-start

Comment at https://gns3.com/marketplace/appliances/ipterm

**Comment by grossmj** [comment]
This is the same as https://github.com/GNS3/gns3-gui/issues/3569#issuecomment-2071983528 busybox is not shipped with GNS3 anymore, it must be manually installed.
