### ISSUE TITLE
GNS3 VM shuts down when starting appliances

### ISSUE THREAD

**Issue by JeffreyMik** [GNS3/gns3-server#2371]
### Discussed in https://github.com/GNS3/gns3-server/discussions/2370

<div type='discussions-op-text'>

<sup>Originally posted by **JeffreyMik** April 25, 2024</sup>
Hello,

I have a server that is running Windows 10 with Hyper-V enabled. On this Hyper-V, I have GNS3 VM running with more then enough resources. The server is running in subnet 77.0/24 and I am in 78.0/24. When I start the GNS3 application on my laptop and connect to the server using the Edit>preferences>server tab it works fine. The connection gets up and I have no problems. When I start adding appliances it also works as expected, but when I start the appliances the connection gets down.

When I look at my server in the Hyper-V manager, I can see that the heartbeat to the GNS3 VM is changed to 'Lost Connectivity'. What does this mean and how can I fix this problem? Anyone got suggestions or solutions?

EDIT:

Found out that it has something to do with QEMU appliances. When I start an IOU cisco router it works fine. But when I start Ubuntu 20.04.4 and start a console, then the GNS3 VM becomes unreachable.</div>

**Comment by grossmj** [comment]
Looks similar to this issue: https://github.com/GNS3/gns3-gui/issues/2815

There is something with Hyper-V that we haven't figured it out...
