### ISSUE TITLE
windows 10 behaves weird and slow down after install GNS3

### ISSUE THREAD

**Issue by lasha1616** [GNS3/gns3-server#2383]
Hello Guys,

Let me explain from where my problems started, first i installed GNS3 2.2.46 in my PC on Windows 10, soon i noticed my PC didn't work properly, it didn't load apps as usually, my web browsers started to slow down and even it caused to freeze and eventually Windows OS crashed sometimes. I thought reason was my old windows 10. 

Then i installed fresh Windows 10 in my PC almost two months ago, and it worked fine, until i installed GNS3 2.2.47  two days ago. My PC started to behave same as before, my PC didn't boot normally, i even cannot open Firefox. i cannot open MS Office Word, Excel etc... 

so i need to reinstall Windows 10 again to fix my PC.

here are Event Viewer log:

**Error    20.05.2024 16:16:53    Application Error    1000    (100)**

Log Name:      Application

Source:        Application Error

Date:          20.05.2024 16:16:53

Event ID:      1000

Task Category: (100)

Level:         Error

Keywords:      Classic

User:          N/A

Computer:      DESKTOP-P7CS7U1

Description:

Faulting application name: gns3.exe, version: 2.2.47.0, time stamp: 0x6537d870

Faulting module name: Qt5Core.dll, version: 5.15.2.0, time stamp: 0x5fa4dd3b

Exception code: 0xc0000409

Fault offset: 0x00000000000204e8

Faulting process id: 0x2104

Faulting application start time: 0x01daaaaf7ae67569

Faulting application path: C:\Program Files\GNS3\gns3.exe

Faulting module path: C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\Qt5Core.dll

Report Id: a4de7d9a-afb9-461a-9b51-accc62903472

Faulting package full name: 

Faulting package-relative application ID: 

Event Xml:

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">

  <System>

    <Provider Name="Application Error" />

    <EventID Qualifiers="0">1000</EventID>

    <Version>0</Version>

    <Level>2</Level>

    <Task>100</Task>

    <Opcode>0</Opcode>

    <Keywords>0x80000000000000</Keywords>

    <TimeCreated SystemTime="2024-05-20T12:16:53.2607482Z" />

    <EventRecordID>5248</EventRecordID>

    <Correlation />

    <Execution ProcessID="0" ThreadID="0" />

    <Channel>Application</Channel>

    <Computer>DESKTOP-P7CS7U1</Computer>

    <Security />

  </System>

  <EventData>

    <Data>gns3.exe</Data>

    <Data>2.2.47.0</Data>

    <Data>6537d870</Data>

    <Data>Qt5Core.dll</Data>

    <Data>5.15.2.0</Data>

    <Data>5fa4dd3b</Data>

    <Data>c0000409</Data>

    <Data>00000000000204e8</Data>

    <Data>2104</Data>

    <Data>01daaaaf7ae67569</Data>

    <Data>C:\Program Files\GNS3\gns3.exe</Data>

    <Data>C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\Qt5Core.dll</Data>

    <Data>a4de7d9a-afb9-461a-9b51-accc62903472</Data>

    <Data>

    </Data>

    <Data>

    </Data>

  </EventData>

</Event>

**Information    20.05.2024 16:34:24    Windows Error Reporting    1001    None**

Log Name:      Application

Source:        Windows Error Reporting

Date:          20.05.2024 16:34:24

Event ID:      1001

Task Category: None

Level:         Information

Keywords:      Classic

User:          N/A

Computer:      DESKTOP-P7CS7U1

Description:

Fault bucket 2015143381990381983, type 5

Event Name: BEX64

Response: Not available

Cab Id: 0

Problem signature:

P1: gns3.exe

P2: 2.2.47.0

P3: 6537d870

P4: Qt5Core.dll

P5: 5.15.2.0

P6: 5fa4dd3b

P7: 00000000000204e8

P8: c0000409

P9: 0000000000000007

P10: 

Attached files:

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA74.tmp.dmp

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB02.tmp.WERInternalMetadata.xml

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB03.tmp.xml

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB10.tmp.csv

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB21.tmp.txt

These files may be available here:

\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_gns3.exe_fd81a719802f4e1c6ef7f6b9bf07353995568a_e3cc9f0f_2bfc649e-2b81-46c6-9cda-9a22fdce26c0

Analysis symbol: 

Rechecking for solution: 0

Report Id: bcc333ef-de6c-4667-90c5-70c94b864c34

Report Status: 268435456

Hashed bucket: 188fa52f37fd9b437bf73a3aaf04199f

Cab Guid: 0

Event Xml:

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">

  <System>

    <Provider Name="Windows Error Reporting" />

    <EventID Qualifiers="0">1001</EventID>

    <Version>0</Version>

    <Level>4</Level>

    <Task>0</Task>

    <Opcode>0</Opcode>

    <Keywords>0x80000000000000</Keywords>

    <TimeCreated SystemTime="2024-05-20T12:34:24.5135688Z" />

    <EventRecordID>5288</EventRecordID>

    <Correlation />

    <Execution ProcessID="0" ThreadID="0" />

    <Channel>Application</Channel>

    <Computer>DESKTOP-P7CS7U1</Computer>

    <Security />

  </System>

  <EventData>

    <Data>2015143381990381983</Data>

    <Data>5</Data>

    <Data>BEX64</Data>

    <Data>Not available</Data>

    <Data>0</Data>

    <Data>gns3.exe</Data>

    <Data>2.2.47.0</Data>

    <Data>6537d870</Data>

    <Data>Qt5Core.dll</Data>

    <Data>5.15.2.0</Data>

    <Data>5fa4dd3b</Data>

    <Data>00000000000204e8</Data>

    <Data>c0000409</Data>

    <Data>0000000000000007</Data>

    <Data>

    </Data>

    <Data>

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA74.tmp.dmp

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB02.tmp.WERInternalMetadata.xml

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB03.tmp.xml

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB10.tmp.csv

\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAB21.tmp.txt</Data>

    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_gns3.exe_fd81a719802f4e1c6ef7f6b9bf07353995568a_e3cc9f0f_2bfc649e-2b81-46c6-9cda-9a22fdce26c0</Data>

    <Data>

    </Data>

    <Data>0</Data>

    <Data>bcc333ef-de6c-4667-90c5-70c94b864c34</Data>

    <Data>268435456</Data>

    <Data>188fa52f37fd9b437bf73a3aaf04199f</Data>

    <Data>0</Data>

  </EventData>

</Event>

crash report C:\ProgramData\Microsoft\Windows\WER\ReportArchive\: 

> Version=1
EventType=BEX64
EventTime=133606820623162240
ReportType=2
Consent=1
UploadTime=133606820625210945
ReportStatus=268435456
ReportIdentifier=2bfc649e-2b81-46c6-9cda-9a22fdce26c0
IntegratorReportIdentifier=bcc333ef-de6c-4667-90c5-70c94b864c34
Wow64Host=34404
NsAppName=gns3.exe
OriginalFilename=gns3.exe
AppSessionGuid=000031c8-0001-0026-7831-08d8b1aada01
TargetAppId=W:0006b419912c49e213b4a3cacedcff8d083300000904!00007ea3260fc8aebdd41657b036d8ee272c5df54f8f!gns3.exe
TargetAppVer=2023//10//24:14:45:04!0!gns3.exe
BootId=4294967295
TargetAsId=1353
UserImpactVector=808452912
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=188fa52f37fd9b437bf73a3aaf04199f
Response.BucketTable=5
Response.LegacyBucketId=2015143381990381983
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=gns3.exe
Sig[1].Name=Application Version
Sig[1].Value=2.2.47.0
Sig[2].Name=Application Timestamp
Sig[2].Value=6537d870
Sig[3].Name=Fault Module Name
Sig[3].Value=Qt5Core.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=5.15.2.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5fa4dd3b
Sig[6].Name=Exception Offset
Sig[6].Value=00000000000204e8
Sig[7].Name=Exception Code
Sig[7].Value=c0000409
Sig[8].Name=Exception Data
Sig[8].Value=0000000000000007
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.19045.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1079
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=ac51
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=ac51afe3464c04378dad520471e519e7
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=0896
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=0896f6ce060540a22db06d7e7880b5eb
UI[2]=C:\Program Files\GNS3\gns3.exe
LoadedModule[0]=C:\Program Files\GNS3\gns3.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\ucrtbase.dll
LoadedModule[5]=C:\Program Files\GNS3\VCRUNTIME140.dll
LoadedModule[6]=C:\Program Files\GNS3\python310.dll
LoadedModule[7]=C:\Windows\System32\WS2_32.dll
LoadedModule[8]=C:\Windows\System32\RPCRT4.dll
LoadedModule[9]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[10]=C:\Windows\System32\msvcrt.dll
LoadedModule[11]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[12]=C:\Windows\System32\sechost.dll
LoadedModule[13]=C:\Windows\System32\bcrypt.dll
LoadedModule[14]=C:\Program Files\GNS3\python3.dll
LoadedModule[15]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[16]=C:\Windows\system32\rsaenh.dll
LoadedModule[17]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[18]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[19]=C:\Program Files\GNS3\lib\_bz2.pyd
LoadedModule[20]=C:\Program Files\GNS3\lib\_lzma.pyd
LoadedModule[21]=C:\Program Files\GNS3\lib\_hashlib.pyd
LoadedModule[22]=C:\Program Files\GNS3\lib\libcrypto-1_1.dll
LoadedModule[23]=C:\Windows\System32\USER32.dll
LoadedModule[24]=C:\Windows\System32\win32u.dll
LoadedModule[25]=C:\Windows\System32\GDI32.dll
LoadedModule[26]=C:\Windows\System32\gdi32full.dll
LoadedModule[27]=C:\Windows\System32\msvcp_win.dll
LoadedModule[28]=C:\Windows\System32\IMM32.DLL
LoadedModule[29]=C:\Program Files\GNS3\lib\PyQt5\QtCore.pyd
LoadedModule[30]=C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\Qt5Core.dll
LoadedModule[31]=C:\Windows\System32\ole32.dll
LoadedModule[32]=C:\Windows\System32\combase.dll
LoadedModule[33]=C:\Windows\SYSTEM32\MPR.dll
LoadedModule[34]=C:\Windows\System32\SHELL32.dll
LoadedModule[35]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[36]=C:\Windows\SYSTEM32\NETAPI32.dll
LoadedModule[37]=C:\Program Files\GNS3\MSVCP140.dll
LoadedModule[38]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[39]=C:\Program Files\GNS3\MSVCP140_1.dll
LoadedModule[40]=C:\Program Files\GNS3\VCRUNTIME140_1.dll
LoadedModule[41]=C:\Windows\SYSTEM32\NETUTILS.DLL
LoadedModule[42]=C:\Windows\SYSTEM32\SRVCLI.DLL
LoadedModule[43]=C:\Program Files\GNS3\lib\PyQt5\sip.cp310-win_amd64.pyd
LoadedModule[44]=C:\Program Files\GNS3\lib\PyQt5\QtGui.pyd
LoadedModule[45]=C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\Qt5Gui.dll
LoadedModule[46]=C:\Windows\SYSTEM32\d3d11.dll
LoadedModule[47]=C:\Windows\SYSTEM32\dxgi.dll
LoadedModule[48]=C:\Program Files\GNS3\lib\PyQt5\QtNetwork.pyd
LoadedModule[49]=C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\Qt5Network.dll
LoadedModule[50]=C:\Windows\System32\CRYPT32.dll
LoadedModule[51]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[52]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[53]=C:\Windows\System32\NSI.dll
LoadedModule[54]=C:\Program Files\GNS3\lib\PyQt5\QtWidgets.pyd
LoadedModule[55]=C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\Qt5Widgets.dll
LoadedModule[56]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[57]=C:\Windows\SYSTEM32\UxTheme.dll
LoadedModule[58]=C:\Program Files\GNS3\lib\PyQt5\QtSvg.pyd
LoadedModule[59]=C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\Qt5Svg.dll
LoadedModule[60]=C:\Program Files\GNS3\lib\PyQt5\QtWebSockets.pyd
LoadedModule[61]=C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\Qt5WebSockets.dll
LoadedModule[62]=C:\Program Files\GNS3\lib\_socket.pyd
LoadedModule[63]=C:\Program Files\GNS3\lib\select.pyd
LoadedModule[64]=C:\Program Files\GNS3\lib\psutil._psutil_windows.pyd
LoadedModule[65]=C:\Windows\System32\PSAPI.DLL
LoadedModule[66]=C:\Windows\SYSTEM32\pdh.dll
LoadedModule[67]=C:\Windows\SYSTEM32\POWRPROF.dll
LoadedModule[68]=C:\Windows\SYSTEM32\UMPDC.dll
LoadedModule[69]=C:\Windows\SYSTEM32\wtsapi32.dll
LoadedModule[70]=C:\Program Files\GNS3\lib\_uuid.pyd
LoadedModule[71]=C:\Program Files\GNS3\lib\_ssl.pyd
LoadedModule[72]=C:\Program Files\GNS3\lib\libssl-1_1.dll
LoadedModule[73]=C:\Program Files\GNS3\lib\pywintypes310.dll
LoadedModule[74]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[75]=C:\Program Files\GNS3\lib\win32process.pyd
LoadedModule[76]=C:\Program Files\GNS3\lib\win32gui.pyd
LoadedModule[77]=C:\Windows\System32\COMDLG32.dll
LoadedModule[78]=C:\Windows\System32\shcore.dll
LoadedModule[79]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[80]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3636_none_60b6a03d71f818d5\COMCTL32.dll
LoadedModule[81]=C:\Windows\SYSTEM32\msimg32.dll
LoadedModule[82]=C:\Program Files\GNS3\lib\unicodedata.pyd
LoadedModule[83]=C:\Program Files\GNS3\lib\_elementtree.pyd
LoadedModule[84]=C:\Program Files\GNS3\lib\pyexpat.pyd
LoadedModule[85]=C:\Windows\system32\mswsock.dll
LoadedModule[86]=C:\Program Files\GNS3\lib\_queue.pyd
LoadedModule[87]=C:\Program Files\GNS3\lib\charset_normalizer.md.cp310-win_amd64.pyd
LoadedModule[88]=C:\Program Files\GNS3\lib\charset_normalizer.md__mypyc.cp310-win_amd64.pyd
LoadedModule[89]=C:\Program Files\GNS3\lib\_decimal.pyd
LoadedModule[90]=C:\Program Files\GNS3\lib\_ctypes.pyd
LoadedModule[91]=C:\Program Files\GNS3\lib\libffi-7.dll
LoadedModule[92]=C:\Program Files\GNS3\lib\win32console.pyd
LoadedModule[93]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\platforms\qwindows.dll
LoadedModule[94]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[95]=C:\Windows\SYSTEM32\windows.storage.dll
LoadedModule[96]=C:\Windows\System32\Wldp.dll
LoadedModule[97]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[98]=C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\libssl-1_1-x64.dll
LoadedModule[99]=C:\Program Files\GNS3\lib\PyQt5\Qt5\bin\libcrypto-1_1-x64.dll
LoadedModule[100]=C:\Windows\System32\MSASN1.dll
LoadedModule[101]=C:\Windows\system32\dwrite.dll
LoadedModule[102]=C:\Windows\SYSTEM32\WindowsCodecs.dll
LoadedModule[103]=C:\Windows\System32\clbcatq.dll
LoadedModule[104]=C:\Windows\System32\thumbcache.dll
LoadedModule[105]=C:\Windows\system32\napinsp.dll
LoadedModule[106]=C:\Windows\system32\pnrpnsp.dll
LoadedModule[107]=C:\Windows\system32\wshbth.dll
LoadedModule[108]=C:\Windows\system32\NLAapi.dll
LoadedModule[109]=C:\Windows\System32\winrnr.dll
LoadedModule[110]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\imageformats\qgif.dll
LoadedModule[111]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\imageformats\qicns.dll
LoadedModule[112]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\imageformats\qico.dll
LoadedModule[113]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\imageformats\qjpeg.dll
LoadedModule[114]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\imageformats\qsvg.dll
LoadedModule[115]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\imageformats\qtga.dll
LoadedModule[116]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\imageformats\qtiff.dll
LoadedModule[117]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\imageformats\qwbmp.dll
LoadedModule[118]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\imageformats\qwebp.dll
LoadedModule[119]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\iconengines\qsvgicon.dll
LoadedModule[120]=C:\Windows\system32\d3d9.dll
LoadedModule[121]=C:\Windows\System32\MSCTF.dll
LoadedModule[122]=C:\Windows\system32\dataexchange.dll
LoadedModule[123]=C:\Windows\system32\dcomp.dll
LoadedModule[124]=C:\Windows\system32\twinapi.appcore.dll
LoadedModule[125]=C:\Windows\SYSTEM32\textinputframework.dll
LoadedModule[126]=C:\Windows\System32\CoreMessaging.dll
LoadedModule[127]=C:\Windows\System32\CoreUIComponents.dll
LoadedModule[128]=C:\Windows\SYSTEM32\wintypes.dll
LoadedModule[129]=C:\Windows\SYSTEM32\ntmarta.dll
LoadedModule[130]=C:\Program Files\GNS3\lib\PyQt5\Qt5\plugins\bearer\qgenericbearer.dll
LoadedModule[131]=C:\Windows\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[132]=C:\Windows\SYSTEM32\dhcpcsvc.DLL
LoadedModule[133]=C:\Windows\System32\netprofm.dll
LoadedModule[134]=C:\Windows\System32\npmproxy.dll
LoadedModule[135]=C:\Windows\System32\rasadhlp.dll
LoadedModule[136]=C:\Windows\System32\fwpuclnt.dll
LoadedModule[137]=C:\Program Files\GNS3\lib\pythoncom310.dll
LoadedModule[138]=C:\Windows\SYSTEM32\urlmon.dll
LoadedModule[139]=C:\Windows\SYSTEM32\iertutil.dll
LoadedModule[140]=C:\Program Files\GNS3\lib\win32api.pyd
LoadedModule[141]=C:\Windows\SYSTEM32\secur32.dll
LoadedModule[142]=C:\Windows\SYSTEM32\SSPICLI.DLL
LoadedModule[143]=C:\Windows\SYSTEM32\sxs.dll
LoadedModule[144]=C:\Windows\system32\wbem\wbemdisp.dll
LoadedModule[145]=C:\Windows\SYSTEM32\wbemcomn.dll
LoadedModule[146]=C:\Windows\system32\wbem\wbemprox.dll
LoadedModule[147]=C:\Windows\system32\wbem\wmiutils.dll
LoadedModule[148]=C:\Windows\system32\wbem\wbemsvc.dll
LoadedModule[149]=C:\Windows\system32\wbem\fastprox.dll
LoadedModule[150]=C:\Windows\SYSTEM32\amsi.dll
LoadedModule[151]=C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.24040.4-0\MpOav.dll
LoadedModule[152]=C:\Program Files\GNS3\lib\win32service.pyd
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19045
OsInfo[3].Key=ubr
OsInfo[3].Value=4291
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=88
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222675179
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.3636.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32124
OsInfo[19].Key=svolsz
OsInfo[19].Value=111
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.4291.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=FX:119E26AD,FX:11C0E96C,FX:11CC111C,FX:11D5BFCD,FX:11DF5B12,FX:11DF5B75,FX:1240931B,FX:124117A5,FX:124B38D0,FX:127FC878,FX:1283FFE8,FX:12840617,FX:128979F9,FX:128EBD7E,FX:129135BB,FX:129E053F,FX:12A74DB5,FX:12AB734D,FX:12B8450E,FX:12BD6E73,FX:12C3331B,FX:12C7D66E,FX:12CDE644,FX:12D1574C,FX:12D281C4,FX:12D8EAA1,FX:12DB8C8B,FX:12DC3D56,FX:12DC4042,FX:12DD15C2,FX:12DD3EBD,FX:12E5D068,FX:12E5D322,FX:12E5D42F,FX:12E6742F,FX:12E67457,FX:12E674AF,FX:12E6D3CC,FX:12E8312D,FX:12E85DEC,FX:12E98915,FX:12E99480,FX:12E9C8EC,FX:12EAEB55,FX:12EC040E,FX:12EC0B54,FX:12EE69CF,FX:12EEB8F2,FX:12EF9116,FX:12F0318C,FX:12F0AC91,FX:12F10236,FX:12F2EE05,FX:2F470C6
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
FriendlyEventName=Stopped working
ConsentKey=BEX64
AppName=GNS3 Network simulator
AppPath=C:\Program Files\GNS3\gns3.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=A57D8535A2DFBF93E6C2E126EEFF1763

> MetadataHash=-1395088612

what is my problem? GNS3 doesn't work on AMD?

GNS3 Version: GNS3 v2.2.X

Operating System: Windows 10, CPU AMD Ryzen 7 5700G, 32GB RAM

**Comment by grossmj** [comment]
Not sure what the problem might be. Maybe try with v2.2.48.1 to see if your problem is solved?

**Comment by lasha1616** [comment]
> Not sure what the problem might be. Maybe try with v2.2.48.1 to see if your problem is solved?

I already reinstalled Windows 10 and i don't want to risk it again. I might try to do in VM but not on my working PC. I will update then

**Comment by grossmj** [comment]
> I already reinstalled Windows 10 and i don't want to risk it again. I might try to do in VM but not on my working PC. I will update then.

Indeed, the best in your situation is to have a separate environment by using VMware or VirtualBox to run the GNS3 VM with the bundled web interface. Thanks 👍
