### ISSUE TITLE
Unable to Establish Connection Between Host and Container via GNS3 Cloud Node

### ISSUE THREAD

**Issue by nazdridoy** [GNS3/gns3-server#2386]
## Description

I am experiencing an issue with GNS3 on my Arch Linux machine (no VM). I am trying to connect my container in GNS3 to the internet through my physical Ethernet interface "enp0s20f0u1c2". I have added "enp0s20f0u1c2" in the cloud node and connected my Ubuntu container to this cloud node.

The container successfully receives an IP address from my home router's DHCP, and it can connect to the internet. All hosts on the same network (192.168.0.0/24) can reach the container, and the container can ping all of them. However, there is an issue with connectivity between the host running the GNS3 instance and the container:
- The host cannot ping the container.
- The container cannot ping the host.

## Steps to Reproduce
1. Run GNS3 on Arch Linux (no VM).
2. Add the physical Ethernet interface "enpXXXX" to the GNS3 cloud node.
3. Connect an Ubuntu container to the cloud node("enpXXXX").
4. Obtain an IP address for the container from the home router's DHCP.
5. Try to ping the container from the host and the host from the container.

## Expected Behavior
- The host should be able to ping the container.
- The container should be able to ping the host.

## Actual Behavior
- The host cannot ping the container.
- The container cannot ping the host.

## Additional Information
- Host OS: Arch Linux
- GNS3 version: 2.2.47
- Network: 192.168.0.0/24

## Troubleshooting Steps Taken
- Verified that the container can reach other hosts on the network and access the internet.
- Confirmed that there are no firewall rules blocking the connection.

Is this behavior intended, or is it a bug? How can I establish a connection between the host and the container connected via the cloud node?

Thank you for your assistance.

---

Let me know if you need any additional information.

**Comment by grossmj** [comment]
The best way is to use a bridge with your physical Ethernet interface inside. Then use your bridge in the GNS3 cloud node. Something similar to this: https://github.com/GNS3/gns3-gui/issues/1921#issuecomment-288530478

or you could just use a NAT node as described in https://github.com/GNS3/gns3-gui/issues/3606#issuecomment-2245377389 You will have to install libvirt on your system.
