### ISSUE TITLE
The following packages have unmet dependencies:  libvirt-daemon-system : Depends: polkitd (>= 121+compat0.1-2) but it is not installable

### ISSUE THREAD

**Issue by Zero3Dash** [GNS3/gns3-server#2398]
When attempting to upgrade from 2.2.47 to 2.2.48
--------------------------------------------------------------------------------------------------------------------------

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1757  100  1757    0     0   9056      0 --:--:-- --:--:-- --:--:--  9103
+ set -e
+ export BRANCH=focal-stable
+ BRANCH=focal-stable
+ export UNSTABLE_APT=0
+ UNSTABLE_APT=0
+ export PYPI_GNS3SERVER_JSON_URL=https://pypi.org/pypi/gns3-server/json
+ PYPI_GNS3SERVER_JSON_URL=https://pypi.org/pypi/gns3-server/json
+ curl -Lk https://raw.githubusercontent.com/GNS3/gns3-vm/focal-stable/scripts/upgrade_vm.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1940  100  1940    0     0  12847      0 --:--:-- --:--:-- --:--:-- 12847
+ bash -x /tmp/upgrade_vm.sh
+ set -e
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ cd /tmp
+ sudo rm -Rf gns3-vm-focal-stable
+ echo 'Download https://github.com/GNS3/gns3-vm/archive/focal-stable.tar.gz'
Download https://github.com/GNS3/gns3-vm/archive/focal-stable.tar.gz
+ curl -Lk https://github.com/GNS3/gns3-vm/archive/focal-stable.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  135k  100  135k    0     0   275k      0 --:--:-- --:--:-- --:--:--  275k
+ tar -xzf gns3vm.tar.gz
+ rm gns3vm.tar.gz
+ sudo fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock
+ cd gns3-vm-focal-stable/config
+ sudo -E bash -x install.sh
+ set -e
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ dpkg-reconfigure libc6
+ sudo -E apt-get -q --option Dpkg::Options::=--force-confold --allow-change-held-packages --assume-yes install libssl1.1
Reading package lists...
Building dependency tree...
Reading state information...
libssl1.1 is already the newest version (1.1.1f-1ubuntu2.22).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
++ dpkg --print-architecture
+ [[ amd64 == \a\r\m\6\4 ]]
+ cat
+ dpkg --add-architecture i386
+ cp release-upgrades /etc/update-manager/release-upgrades
+ chmod 644 /etc/update-manager/release-upgrades
+ chown root:root /etc/update-manager/release-upgrades
++ which add-apt-repository
+ [[ ! -n /usr/bin/add-apt-repository ]]
+ [[ 0 == \1 ]]
+ sudo -E add-apt-repository -y ppa:gns3/ppa
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [128 kB]
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [128 kB]
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:5 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [772 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [997 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [3,025 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [453 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/universe i386 Packages [670 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [990 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3,410 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [533 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [3,055 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [427 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,209 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [796 kB]
Hit:17 http://ppa.launchpad.net/canonical-server/server-backports/ubuntu focal InRelease
Hit:18 http://ppa.launchpad.net/gns3/ppa/ubuntu focal InRelease
Fetched 16.6 MB in 3s (5,799 kB/s)
Reading package lists... Done
+ add-apt-repository -y --remove ppa:gns3/unstable
+ curl -fsSL https://download.docker.com/linux/ubuntu/gpg
+ sudo apt-key add -
OK
++ dpkg --print-architecture
++ lsb_release -cs
+ sudo -E add-apt-repository -y 'deb [arch=amd64] https://download.docker.com/linux/ubuntu    focal    stable'
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Get:3 https://download.docker.com/linux/ubuntu focal InRelease [57.7 kB]
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:6 http://ppa.launchpad.net/canonical-server/server-backports/ubuntu focal InRelease
Hit:7 http://ppa.launchpad.net/gns3/ppa/ubuntu focal InRelease
Get:8 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages [46.4 kB]
Fetched 104 kB in 1s (121 kB/s)
Reading package lists... Done
+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 https://download.docker.com/linux/ubuntu focal InRelease
Hit:6 http://ppa.launchpad.net/canonical-server/server-backports/ubuntu focal InRelease
Hit:7 http://ppa.launchpad.net/gns3/ppa/ubuntu focal InRelease
Reading package lists... Done
+ apt-get install -y jq
Reading package lists... Done
Building dependency tree
Reading state information... Done
jq is already the newest version (1.6-1ubuntu0.20.04.1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
+ apt-get install -y virt-what
Reading package lists... Done
Building dependency tree
Reading state information... Done
virt-what is already the newest version (1.19-1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
+ apt-get install -y mingetty
Reading package lists... Done
Building dependency tree
Reading state information... Done
mingetty is already the newest version (1.08-2build1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
+ apt-get install -y python3-dev python3-venv python3-setuptools
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-venv is already the newest version (3.8.2-0ubuntu2).
python3-setuptools is already the newest version (45.2.0-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
+ [[ ! -d /home/gns3/.venv/gns3server-venv ]]
+ apt-get install -y --allow-change-held-packages libvirt-daemon-system
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libvirt-daemon-system : Depends: polkitd (>= 121+compat0.1-2) but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR DURING THE UPGRADE PROCESS PLEASE, TAKE A SCREENSHOT IF YOU NEED SUPPORT

----------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by grossmj** [comment]
I have made some changes, please can you try to upgrade again? thanks.

**Comment by Zero3Dash** [comment]
No changes to the VM.
I've tried multiple times to upgrade, same error message.
I've rebooted and tried, same.

**Comment by grossmj** [comment]
Please can you try to execute these 2 commands inside the VM and then upgrade again? thanks.

```
sudo apt-mark unhold libvirt-daemon-system
sudo apt-mark unhold tigervnc-standalone-server
```

**Comment by Zero3Dash** [comment]
that resolved the issue. thanks

**Comment by grossmj** [comment]
Please see https://github.com/GNS3/gns3-vm/issues/185#issuecomment-2266650530
