### ISSUE TITLE
Empty page with "Web console on new tab"

### ISSUE THREAD

**Issue by nuqleo** [GNS3/gns3-server#2399]
Hi,

In Web UI v2.2.48 if I select from context menu "Web console on new tab" then empty page displayed.
Works fine in v2.2.47.

**Comment by grossmj** [comment]
Looks like something went wrong during the release.

I am probably going to have to release v2.2.48.1

**Comment by grossmj** [comment]
Fixed, I will release v2.2.48.1 soon
