### ISSUE TITLE
.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).   warnings.warn(msg, UserWarning)

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-server#24]
Hi,

Since the Beta was released I decided to give this a shot on the new CentOS 7.X linux distribution. I got everything installed, all the pre-req's. When I run gns3server from the command line this is what I get, now i'm not sure if this is normal of if this is a major issue in the functioning of GNS3. Please advise. 

[cnetworks-admin@localhost gns3-server]$ gns3server
GNS3 server version 1.0beta1
Copyright (c) 2007-2014 GNS3 Technologies Inc.
Running with Python 3.4.1 and has PID 13090
[I 140724 18:29:35 main:75] current locale is en_CA.UTF-8
[W 140724 18:29:35 config:82] no configuration file could be found or read
[I 140724 18:29:35 base:131] dynamips module running with PID 13092
[W 140724 18:29:35 **init**:77] VPCS binary couldn't be found!
[I 140724 18:29:35 base:84] ZeroMQ client (dynamips) connecting to 127.0.0.1:57597
[I 140724 18:29:35 base:131] vpcs module running with PID 13095
[I 140724 18:29:35 base:84] ZeroMQ client (vpcs) connecting to 127.0.0.1:57597
[I 140724 18:29:35 base:131] virtualbox module running with PID 13098
[W 140724 18:29:35 **init**:82] iouyap binary couldn't be found!
[I 140724 18:29:35 base:84] ZeroMQ client (virtualbox) connecting to 127.0.0.1:57597
[I 140724 18:29:35 server:223] ZeroMQ server listening to 127.0.0.1:57597
[I 140724 18:29:35 base:131] iou module running with PID 13101
[I 140724 18:29:35 base:84] ZeroMQ client (iou) connecting to 127.0.0.1:57597
/usr/local/lib/python3.4/site-packages/pkg_resources.py:1049: UserWarning: /home/cnetworks-admin/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Starting server on 0.0.0.0:8000 (Tornado v4.0, PyZMQ v14.3.1, ZMQ v4.0.4)

**Comment by YesPoX** [comment]
Command has space mistake. i creates error: 
> chmod: invalid mode: g-wx

Right one is `chmod g-wx,o-wx ~/.python-eggs`
