### ISSUE TITLE
Build in upgrade from 2.2.47 to 2.2.48 (or 2.2.48.1) fails with cannot create regular file (release-upgrades) 

### ISSUE THREAD

**Issue by itsamemarkus** [GNS3/gns3-server#2400]
Sorry, I currently don't have time to do a broader deep dive on this myself, maybe this helps as a starting point in case others experience this too.

I tried upgrading from 2.2.47 to 2.2.48.1 with the build in upgrade tool (initial install was via 2.2.47 KVM disks) downloaded here https://github.com/GNS3/gns3-gui/releases/tag/v2.2.47

Error message is

`cp: cannot create regular file '/etc/update-manager/release-upgrades': No such file or directory`

![Screenshot 2024-07-13 at 10 23 51@2x](https://github.com/user-attachments/assets/a13a3fcb-ad71-48b1-af56-c9fcdb4b54b7)

system was rebooted in between tries, system time is correct

**Comment by AlvaroBuelvas** [comment]
I'm having the same exact issue. Current version 2.2.47, and trying to upgrade to 2.2.48 or 2.2.48.1 fails with the same message.

**Comment by bmaljko** [comment]
Just did 

`cd /etc
sudo mkdir update-manager
sudo gns3restore`

and VM is upgraded to 2.2.48.1

**Comment by grossmj** [comment]
Thanks for the report. I have fixed the upgrade script and upgrades should work now.
