### ISSUE TITLE
Juniper devices failing to boot

### ISSUE THREAD

**Issue by dar72** [GNS3/gns3-server#2405]
After recent QEMU updates Juniper devices are failing to boot

This is the problem and the solution here fixed it for me:

[https://forum.proxmox.com/threads/qemu-8-1-available-on-pvetest-and-pve-no-subscription-as-of-now.136227/#post-610277](url)

Is there any way this can be handled in GNS3 in some way? Preferably to avoid having to edit every template and every device in every project to add the additional settings for the VM?

**Comment by grossmj** [comment]
Have you used any of the appliances we distribute on our marketplace? https://gns3.com/marketplace/appliances or have you manually added templates in GNS3 for your Juniper devices?

**Comment by dar72** [comment]
> Have you used any of the appliances we distribute on our marketplace? https://gns3.com/marketplace/appliances or have you manually added templates in GNS3 for your Juniper devices?

I've used the templates from the marketplace, those haven't been updated for a year and have this issue. The issue only occurred recently after an update in qemu

**Comment by grossmj** [comment]
I have added the configuration to add your Juniper appliances.
