### ISSUE TITLE
Docker containers MAC addresses change after a restart

### ISSUE THREAD

**Issue by yoennb** [GNS3/gns3-server#2412]
Hello,

I use the GNS3 VM version 2.2.49 on VMWare ESXi. I added a few docker containers in my project (based on different images, e.g webterm), and noticed that their MAC address changes after being stopped and restarted. This makes it inconvenient to create static DHCP mappings.

I did not observe this behavior when running containers on my docker engine, and I see that docker network is disabled on containers managed by GNS3, so I assume docker has no control over this.

Is this the expected behavior? I did not find any documentation on that topic.

Thanks for the help!

**Comment by grossmj** [comment]
I remember we already tried to implement this and this is my answer at that time: https://github.com/GNS3/gns3-server/issues/2034#issuecomment-1277180857

**Comment by grossmj** [comment]
We have added support for configuring custom MAC addresses.

**Comment by yoennb** [comment]
Excellent, thank you!
