### ISSUE TITLE
How to run Docker containers inside GNS3 with user namespaces enabled?

### ISSUE THREAD

**Issue by smart2128** [GNS3/gns3-server#2414]
Hi.
every time I try to instantiate a Docker appliance in GNS3, I receive the following error:

Error while creating node from template: Docker has returned an error: 400 privileged mode is incompatible with user namespaces.  You must run the container in the host namespace when running privileged mode

Is there a way to properly handle this issue?

Thank you in advance,

**Comment by grossmj** [comment]
What Docker image have you tried to use? Do you have this issue with any image?

**Comment by smart2128** [comment]
Yes, I experience the same behavior with any images. I tried several images, (Alpine Linux, DNS, Open vSwitch, etc.).
Thank you for your answer.

**Comment by grossmj** [comment]
Fixed, this should work in our next release.

**Comment by smart2128** [comment]
Hi Jeremy,
sorry for re-opening this issue.
I just installed v2.2.50, but, when I try to instantiate a Docker container in GNS3, I still get the same error 

`Error while creating node from template: Docker has returned an error: 400 privileged mode is incompatible with user namespaces.  You must run the container in the host namespace when running privileged mode`

Please, let me know if you need more details.

Regards,
Vincenzo

**Comment by grossmj** [comment]
Have you done anything to enable "user namespaces"?

**Comment by smart2128** [comment]
I don't remember any customizations by my side, but, reading the Archlinux
Docker's wiki page, there's a "User namespace isolation" section that
contains a reference to a vulnerability published and patched in February
2019.
I'm trying to figure out, if it had been enable by me or by Arch.
I'll keep you posted.

Thank you,
Vincenzo


Il giorno mer 23 ott 2024 alle ore 03:39 Jeremy Grossmann <
***@***.***> ha scritto:

**Comment by smart2128** [comment]
I removed userns-remap and now it works as expected.
Forgive me for wasting your time.

**Comment by grossmj** [comment]
> Forgive me for wasting your time.

No worries, I actually have tested with `userns-remap` and indeed the previous fix didn't work because the param `UsernsMode` was in the wrong spot. I fixed that and now everything should work even when `userns-remap` is enabled.
