### ISSUE TITLE
If KVM is missing qemu crash

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#242]
Actually if KVM is not available the VM quit.

I think we can make this transparent for user. If qemu exit at launch we restart it without the kvm flag. What did you think about that @grossmj ?

**Comment by grossmj** [comment]
What I would prefer to do is take stdout/stderr once the proces has crashed and send this info to the user via the notification system along with the command line we used. 

If KVM is enable we can maybe indicate that this is likely what prevented the process to start. I don't really want to do some magic behind user's back, if KVM doesn't work there is a reason that need to be fixed (like not running VirtualBox and VMware at the same time).

**Comment by noplay** [comment]
I agree we can display the log to the user.

But should the KVM setting be smarter ? And be something like use KVM if
available. Because otherwise it's more complicated for topology portability
if you want to move from a Linux Host with KVM to a cloud computer or a
VirtualBox VM you always need to modify the setting.

We can turn off kvm if /dev/kvm doesn't exist and raise warning to user if
/dev/kvm exist but can't be use actually.

**Comment by noplay** [comment]
But perhaps the KVM settings is not at the right place and should not be a part of the VM config but something we configure server / server.

**Comment by grossmj** [comment]
> But perhaps the KVM settings is not at the right place and should not be a part of the VM config but something we configure server / server.

I like that, it make more sense I think.

**Comment by grossmj** [comment]
KVM setting has been moved. We check for /dev/kvm in https://github.com/GNS3/gns3-server/issues/245 but there is not way to know if a VM can really use KVM until we start a Qemu process and it crashes, hence we should send that information to the user: https://github.com/GNS3/gns3-server/issues/243
