### ISSUE TITLE
Guest( VMware machine or qemu guest(openwrt) ) on GNS3 can't ping VMnat8 address through Cloud node

### ISSUE THREAD

**Issue by weiqi-chen** [GNS3/gns3-server#2421]
Herr is my "Virtual Network Editor" settings

![图片](https://github.com/user-attachments/assets/ad6ce46d-cc4b-416d-bf7c-5235b3594b1a)
![图片](https://github.com/user-attachments/assets/fee9428b-a1e6-4931-b839-7d91d7532cca)

Here is my GNS3 Preference for VMware preferences Advanced local settings
![图片](https://github.com/user-attachments/assets/395ddfb3-265a-4fa5-8b67-a5e14eec6a82)

Here is my Topology 
> By the way, I'm trying to setup strongswan, so I has the "INTERNET" zone, just ignore it.

![图片](https://github.com/user-attachments/assets/7546553d-3e2e-4a94-9834-2fee32edfd51)
![图片](https://github.com/user-attachments/assets/6165f175-ffd2-47b8-adad-d0f0219e6664)

I want to copy some files to `OpenWRT` router(scp).
So I created a Cloud node, connected the devices to `VMnet8`
It strange that both `Win7-2` and `OpenWRT` can't ping `192.168.80.1`.
But they can get ip address from dhcp, ping `192.168.80.2`and `8.8.8.8`(has Internet Access). 
It shows that VMware NAT is working well. `Win7-2` can access `OpenWRT` web admin page.

I verified that both `Win7-2` and `Win7-1` connect the custom VMware virtual network adapters (changed by gns3 automatically) and I did not modify them.
I also shutdown my Host Windows 10 firewall.

![图片](https://github.com/user-attachments/assets/f6c7f576-1c6f-4672-9759-ee9ec21f998f)

`OpenWRT`
```
root@OpenWrt:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-lan state UP group default qlen 1000
    link/ether 0c:b0:c5:f7:00:00 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 0c:b0:c5:f7:00:01 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::eb0:c5ff:fef7:1/64 scope link
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 0c:b0:c5:f7:00:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.80.131/24 brd 192.168.80.255 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::eb0:c5ff:fef7:2/64 scope link
       valid_lft forever preferred_lft forever
5: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 0c:b0:c5:f7:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 fdbc:fbef:7cd8::1/60 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::eb0:c5ff:fef7:0/64 scope link
       valid_lft forever preferred_lft forever
root@OpenWrt:/# nslookup bing.com
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
Name:   bing.com
Address: 13.107.21.200
Name:   bing.com
Address: 204.79.197.200

Non-authoritative answer:
Name:   bing.com
Address: 2620:1ec:c11::200

root@OpenWrt:/# ping 192.168.80.1
PING 192.168.80.1 (192.168.80.1): 56 data bytes
^C
--- 192.168.80.1 ping statistics ---
15 packets transmitted, 0 packets received, 100% packet loss
root@OpenWrt:/# ping 192.168.80.2
PING 192.168.80.2 (192.168.80.2): 56 data bytes
64 bytes from 192.168.80.2: seq=0 ttl=128 time=1.080 ms
64 bytes from 192.168.80.2: seq=1 ttl=128 time=1.744 ms
^C
--- 192.168.80.2 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 1.080/1.412/1.744 ms
root@OpenWrt:/# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.80.2    0.0.0.0         UG    0      0        0 eth2
192.168.1.0     *               255.255.255.0   U     0      0        0 br-lan
192.168.80.0    *               255.255.255.0   U     0      0        0 eth2

```

**Comment by weiqi-chen** [comment]
Windows 10 21H2 LTSC, 19044.4894.
GNS3 2.2.49,
Npcap 1.79 (WinPcap compatibility selected as I remember)
winpcap not installed
VMware workstation 17pro 17.5.2

**Comment by grossmj** [comment]
Looks like your need to use a NAT, not the normal cloud.

Please can you try both a NAT device and VPCS running inside the GNS3 VM? I was able to ping my VMnet8 interface.

![Image](https://github.com/user-attachments/assets/81f5913b-7a70-4172-9a7c-ded9a71da9c2)

**Comment by weiqi-chen** [comment]
![图片](https://github.com/user-attachments/assets/bd1cba8a-1a0e-40a5-a86d-88979a427de9)


![图片](https://github.com/user-attachments/assets/7fd0b5fa-7308-45f3-9f8e-2c2d4eb2abe1)

Test Result:
- PC1
![图片](https://github.com/user-attachments/assets/58d9e04b-a357-4019-8265-e12e2f74a86e)

- PC2
![图片](https://github.com/user-attachments/assets/ef7f24b9-8b6a-4e9f-a05b-b7d7721b8dc2)

- PC3
![图片](https://github.com/user-attachments/assets/2f52c955-7b30-4777-8cec-9d9eb158ac0b)

![图片](https://github.com/user-attachments/assets/2007efd6-ccc0-4f0c-8de7-80533f79ab67)

- PC4
![图片](https://github.com/user-attachments/assets/c755db83-3ef5-4038-a38a-c7c7df70c122)

- PC5
![图片](https://github.com/user-attachments/assets/7f7cd23d-642e-445b-af12-459c1390538b)

- PC6 
![图片](https://github.com/user-attachments/assets/b3ff1375-de34-436c-8057-c9ab51088efc)

I created a NAT cloud (NAT2) in GNS3 VM, It does not work.
I cannot ping 192.168.80.1, whether it's NAT or cloud.
