### ISSUE TITLE
gns3 dependency on sentry-sdk

### ISSUE THREAD

**Issue by mm1ke** [GNS3/gns3-server#2423]
Hi,

`sentry-sdk` has some issues (details can be found at: [1]) which ultimately will result in removing this package from the gentoo main repository.
`gns3-server` has a dependency on `sentry-sdk` which would mean it would be removed too as we couldn't fulfill it's dependencies anymore. I'm wondering if it's possible to either remove the dependency or replace it with some other package? Also: Is it possible to run gns3 without `sentry-sdk`? What restrictions would we have?

[1] https://bugs.gentoo.org/937896

**Comment by grossmj** [comment]
@mm1ke we are going to make the sentry-sdk dependency optional. It should be possible to run gns3 without sentry-sdk already.

**Comment by mm1ke** [comment]
@grossmj  thanks for the information. happy to hear that :)
