### ISSUE TITLE
Error when starting GNS3 VM on VMware workstation

### ISSUE THREAD

**Issue by Eldriad** [GNS3/gns3-server#2425]
Hello!

I don't remember my version of VM GNS3 but it was one of the latest. After one of the latest ugrades in Windows O encountered an error that I've pasted below. Now it's fixed but another problem showed up. 

![Zrzut ekranu 2024-10-14 170939](https://github.com/user-attachments/assets/17a4c21d-3665-46f0-8d98-da2182315210)

Instead of  booting GNS, it boots Ubuntu in BusyBox mode. How do I get GNS3 to boot?

![Zrzut ekranu 2024-10-14 174945](https://github.com/user-attachments/assets/556fbaab-76a6-468f-a58f-14272f353567)

GNS3 Version: GNS3 v2.2.X

Operating System: Windows 11

**Comment by grossmj** [comment]
What GNS3 VM version did you use? Do you have the same problem if you download another GNS3 VM?
