### ISSUE TITLE
 GNS3 not showing VirtualBox VMs

### ISSUE THREAD

**Issue by s-c-p** [GNS3/gns3-server#2429]
## Describe the bug
While using GNS3 add template - the GUI doesn't enumerate VirtualBox VMs.

## GNS3 version and operating system (please complete the following information):

**GNS3 Version:** GNS3 v2.2.49
**Operating System:** Linux pop-os 6.9.3-76060903-generic #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S x86_64 x86_64 x86_64 GNU/Linux

I installed GNS3 using the ppa and apt.

## To Reproduce

1. I make 2 VMs using ISO files of pfsense and ubuntu
2. go in terminal and type `vboxmanage list vms` I see correct output.
3. in my GNS3 project I do `Browse All Devices` > `New template` > `Manually create new template` > select `VirtualBox VMs` > click `New` button ...
4. I don't see anything in the drop down

**Comment by s-c-p** [comment]
There's no support on the [forums](https://www.gns3.com/community/support/gns3-not-showing-vbox-list-vms-list) also and can't find any thing relevant in docs.

**Comment by ahmedkhlief** [comment]
i have the same issue and found that when you use the terminal to list vms using gns3-server user it will not list any vm but if you try with your own user it will work so i think its permissions issue .
i tried : sudo -u gns3-server /usr/bin/vboxmanage list vms # it didn't work but using my user it works

**Comment by ahmedkhlief** [comment]
this worked for me but you need to purge the installation via apt ( apt-get purge gns3-server gns3-gui )
sudo apt install python3 python3-pip pipx python3-pyqt5 python3-pyqt5.qtwebsockets python3-pyqt5.qtsvg qemu-kvm qemu-utils libvirt-clients libvirt-daemon-system virtinst dynamips software-properties-common ca-certificates curl gnupg2
pipx install gns3-server==2.2.44
pipx install gns3-gui==2.2.44
pipx inject gns3-gui gns3-server PyQt5

**Comment by grossmj** [comment]
@s-c-p What do you see if you execute this command `vboxmanage list vms`?

**Comment by s-c-p** [comment]
> @s-c-p What do you see if you execute this command `vboxmanage list vms`?

I see

```
"pfs" {9a7c0132-05ba-49ba-b31e-f02549557215}
"pc1" {bc0fb4c7-4212-460c-9d84-14d9533d999c}
"o76" {f4bd5c6b-e6bb-4221-9b24-41749fb8d788}
```

Sorry for the late reply

**Comment by grossmj** [comment]
Do you see anything if you open `http://localhost:3080/v2/computes/local/virtualbox/vms`?

![Screenshot from 2024-11-26 19-03-34](https://github.com/user-attachments/assets/68bf4023-f61a-4590-a75f-3e88cf0e3926)

**Comment by grossmj** [comment]
@s-c-p ?
