### ISSUE TITLE
Errors in init.sh

### ISSUE THREAD

**Issue by nuqleo** [GNS3/gns3-server#2431]
There are a lot of errors in init.sh from gns3-server 2.2.50 (running in Fedora)

ln: /tmp/gns3/bin/usr/bin/[: No such file or directory
ln: /tmp/gns3/bin/usr/bin/[[: No such file or directory
ln: /tmp/gns3/bin/sbin/acpid: No such file or directory
ln: /tmp/gns3/bin/usr/sbin/add-shell: No such file or directory
ln: /tmp/gns3/bin/usr/sbin/addgroup: No such file or directory
...

Only /tmp/gns3/bin/linuxrc created.
Looks like this happened after this commit 
https://github.com/GNS3/gns3-server/commit/c0be6875c2c23b9376faab759dbc318688fef374

busybox Fedora package version:
busybox-1.37.0-1.fc42

# busybox --list-full
usr/bin/[
usr/bin/[[
sbin/acpid
usr/sbin/add-shell
usr/sbin/addgroup
usr/sbin/adduser
sbin/adjtimex
bin/arch
sbin/arp
usr/sbin/arping
bin/ash
usr/bin/awk
bin/base64
usr/bin/basename
bin/bbconfig
usr/bin/bc
usr/bin/beep
usr/bin/blkdiscard
sbin/blkid
sbin/blockdev
usr/sbin/brctl
usr/bin/bunzip2
usr/bin/bzcat
usr/bin/bzip2
....

**Comment by nuqleo** [comment]
Works with --list instead of --list-full

**Comment by grossmj** [comment]
Thanks for catching this 👍
