### ISSUE TITLE
python 3.8 is now end of life.

### ISSUE THREAD

**Issue by Zero3Dash** [GNS3/gns3-server#2432]
https://endoflife.date/python

Python 3.8 is now end of life.
On the next release could it be upgraded to current supported version.

In 2.2.50 the current version is 3.8.10 which was release on 3rd May 2021
https://www.python.org/downloads/release/python-3810/

**Comment by grossmj** [comment]
Indeed, it is end-of-life however the default Python version on Ubuntu Focal is 3.8. We usually aim to support Ubuntu LTS versions as long as they are not also end-of-life.

**Comment by grossmj** [comment]
Also, the GNS3 VM we use for v2.2.x is based on Ubuntu 20.04 Focal. So we would have to upgrade the GNS3 VM to a more recent Ubuntu LTS first.

We could also wait for Ubuntu Focal to be End of Standard Support (not end-of-life as mentioned above), this will happen in April 2025: https://wiki.ubuntu.com/Releases

**Comment by grossmj** [comment]
I have dropped Python 3.8 in GNS3 v3 for now. Version 2.2.x could be done a later date.
