### ISSUE TITLE
Could not send Dynamips command 'vm set_ghost_status "R1" 2' to localhost:34923: Connection lost, process running: False error in gns3

### ISSUE THREAD

**Issue by Durgesh002** [GNS3/gns3-server#2437]
I'm trying to run c7200 router image in gns3 on debian distro. But it's throwing me above error. I saw a similar issue reported for fedora. But couldn't see the solution to it.

**Comment by grossmj** [comment]
Sounds like your c7200 image is unstable and/or Dynamips has crashed as a result. What is your IOS image name?

**Comment by Durgesh002** [comment]
Hey bro. I'm running **Cisco 7200 124-24.T5** on my debian machine. Could there be any problem with gns3 in supporting IOU images? In Ubuntu based distro, we use following commands for IOU support:

**sudo dpkg --add-architecture i386
sudo apt update
sudo apt install gns3-iou**

Do we have any such commands to enable IOU support in debian? Also, I want to understand what these commands do that you're able to run IOU images in Ubuntu distro?

**Comment by grossmj** [comment]
How have you installed Dynamips?

Also, the above commands are only for IOU. Then basically enable the i386 architecture and gns3-iou package basically installs the correct libssl and configure the required symbolic links.

**Comment by grossmj** [comment]
Do you have the same problem on Linux Mint?

**Comment by grossmj** [comment]
Have you installed Dynamips via apt or did you compile it?

**Comment by Durgesh002** [comment]
I've used following commands for different distros.
For Linux mint:

**sudo add-apt-repository ppa:gns3/ppa
sudo apt update                                
sudo apt install gns3-gui gns3-server
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install gns3-iou**

With these commands, GNS3 is working fine.

For Debian:

**sudo apt update
sudo apt install python3 python3-pip pipx python3-pyqt5 python3-pyqt5.qtwebsockets python3-pyqt5.qtsvg qemu-kvm qemu-utils libvirt-clients libvirt-daemon-system virtinst dynamips software-properties-common ca-certificates curl gnupg2 
pipx install gns3-server
pipx install gns3-gui
pipx inject gns3-gui gns3-server PyQt5**

With this, GNS3 wasn't working how i wanted it to be.

**Comment by goudunz1** [comment]
> I've used following commands for different distros. For Linux mint:
> 
> **sudo add-apt-repository ppa:gns3/ppa sudo apt update sudo apt install gns3-gui gns3-server sudo dpkg --add-architecture i386 sudo apt update sudo apt install gns3-iou**
> 
> With these commands, GNS3 is working fine.
> 
> For Debian:
> 
> **sudo apt update sudo apt install python3 python3-pip pipx python3-pyqt5 python3-pyqt5.qtwebsockets python3-pyqt5.qtsvg qemu-kvm qemu-utils libvirt-clients libvirt-daemon-system virtinst dynamips software-properties-common ca-certificates curl gnupg2 pipx install gns3-server pipx install gns3-gui pipx inject gns3-gui gns3-server PyQt5**
> 
> With this, GNS3 wasn't working how i wanted it to be.

Have encountered the same problem on Kali Linux, installing dynamips:i386 instead of dynamips:amd64 solved my issue.

Hope it can help.

**Comment by goudunz1** [comment]
> > I've used following commands for different distros. For Linux mint:
> > **sudo add-apt-repository ppa:gns3/ppa sudo apt update sudo apt install gns3-gui gns3-server sudo dpkg --add-architecture i386 sudo apt update sudo apt install gns3-iou**
> > With these commands, GNS3 is working fine.
> > For Debian:
> > **sudo apt update sudo apt install python3 python3-pip pipx python3-pyqt5 python3-pyqt5.qtwebsockets python3-pyqt5.qtsvg qemu-kvm qemu-utils libvirt-clients libvirt-daemon-system virtinst dynamips software-properties-common ca-certificates curl gnupg2 pipx install gns3-server pipx install gns3-gui pipx inject gns3-gui gns3-server PyQt5**
> > With this, GNS3 wasn't working how i wanted it to be.
> 
> Have encountered the same problem on Kali Linux, installing dynamips:i386 instead of dynamips:amd64 solved my issue.
> 
> Hope it can help.

Compiling dynamips 0.2.23 from source also works. It seems like dynamips in debian official repository is out-dated.

**Comment by Durgesh002** [comment]
> > > I've used following commands for different distros. For Linux mint:
> > > **sudo add-apt-repository ppa:gns3/ppa sudo apt update sudo apt install gns3-gui gns3-server sudo dpkg --add-architecture i386 sudo apt update sudo apt install gns3-iou**
> > > With these commands, GNS3 is working fine.
> > > For Debian:
> > > **sudo apt update sudo apt install python3 python3-pip pipx python3-pyqt5 python3-pyqt5.qtwebsockets python3-pyqt5.qtsvg qemu-kvm qemu-utils libvirt-clients libvirt-daemon-system virtinst dynamips software-properties-common ca-certificates curl gnupg2 pipx install gns3-server pipx install gns3-gui pipx inject gns3-gui gns3-server PyQt5**
> > > With this, GNS3 wasn't working how i wanted it to be.
> > 
> > 
> > Have encountered the same problem on Kali Linux, installing dynamips:i386 instead of dynamips:amd64 solved my issue.
> > Hope it can help.
> 
> Compiling dynamips 0.2.23 from source also works. It seems like dynamips in debian official repository is out-dated.

how do we compile ? Could you please tell me the steps? My debian broke hence I'm using Mint rn. But please do lemme know the steps. It'd be useful in future

**Comment by goudunz1** [comment]
> how do we compile ? Could you please tell me the steps? My debian broke hence I'm using Mint rn. But please do lemme know the steps. It'd be useful in future

Just follow the installation instruction on <github.com/GNS3/dynamips>. You'd probably need cmake, libpcap-dev and libelf-dev.

After that replace `Preference>Dynamips>Path to Dynamips` with your local installation path.
