### ISSUE TITLE
Disk interface is being overriden when set to none

### ISSUE THREAD

**Issue by mrchrd** [GNS3/gns3-server#2438]
I'm creating an appliance that requires extra options for the `virtio-scsi-pci` and `scsi-hd` devices. I set those in the `qemu.options` field and also set `qemu.hd*_disk_interface: none` in the gns3a file, and then let GNS3 set the QEMU `-drive` option. The result I would expect is that GNS3 sets only the `-drive` with `if=none` and does not set the `-device` options. However, this [piece of code](https://github.com/GNS3/gns3-server/blame/97e5a5edc35184cb7358cfa9c767f4de64cbcd33/gns3server/compute/qemu/qemu_vm.py#L1918-L1921) overrides the disk interfaces to `ide`:

```
# fail-safe: use "ide" if there is a disk image and no interface type has been explicitly configured
if interface == "none":
    interface = "ide"
    setattr(self, "hd{}_disk_interface".format(drive), interface)
```

Because `none` is actually an accepted and useful value for QEMU, I think it should not be replaced when it is set explicitely.

**Comment by grossmj** [comment]
Fixed, thanks 👍
