### ISSUE TITLE
Spinning up containers with a dockerized server

### ISSUE THREAD

**Issue by miromeir** [GNS3/gns3-server#2444]
Hello,
I'm using the Dockerfile provided in this project to create a container of gns3-server.
I also need docker containers in my gns3 project.
It's possible if you share "/var/run/docker.sock" with the host, allowing gns3 to control the host docker daemon.
It works, but when trying to start a container i'm getting the following error:

`
gns3server.compute.docker.docker_error.DockerError: Docker has returned an error: 500 b'Mounts denied: \nThe path /root/.local/share/GNS3/docker is not shared from the host and is not known to Docker.\nYou can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.\nSee https://docs.docker.com/ for more info.\n'
`

I'm not sure what to map. My docker host is non-root so that folder doesn't exist.
Even when i map the user's relevant folder to "/root/.local/share....." i'm still getting this error.

Where to proceed from here?

**Comment by grossmj** [comment]
Why do you want to run the GNS3 server as a Docker container?

**Comment by grossmj** [comment]
No worries.

Here is an example how to run the GNS3 server in Docker: https://github.com/GNS3/gns3-server/blob/master/scripts%2Fdocker_dev_server.sh

Let me know if you need more help.
