### ISSUE TITLE
GNS3 2.2.50 uses project_id as directory name in the project folder when using "Save project as..."

### ISSUE THREAD

**Issue by needless** [GNS3/gns3-server#2446]
GNS3 2.2.50 generates random directory name in the project folder when using 'Save project as...'. It takes the GNS3 `project_id` value instead of `name`.

The `project_id` variable can be viewed using the `head *.gns3` in the GNS3 project directory.

**Describe the bug**

Since the GNS3 version 2.2.50 the "Save project as..." function generates a random string directory name in the project folder instead of the desired one.

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux
 - GNS3 version 2.2.50
 - GNS3 bare metal, everything runs locally on the workstation

Here the used versions of GNS3 on the workstation:
```
needle@lifeblind % eix -I gns3-
[I] net-misc/gns3-gui
     Available versions:  (~)2.2.49-r1^t{gpkg} (~)2.2.50^t{gpkg} {test PYTHON_TARGETS="python3_11 python3_12"}
     Installed versions:  2.2.50^t{gpkg}(22:02:32 07/11/24)(-test PYTHON_TARGETS="python3_12 -python3_11")
     Homepage:            https://www.gns3.com https://github.com/GNS3/gns3-gui
     Description:         Graphical Network Simulator

[I] net-misc/gns3-server
     Available versions:  (~)2.2.49-r1^t{gpkg} (~)2.2.50^t{gpkg} {test PYTHON_TARGETS="python3_11 python3_12"}
     Installed versions:  2.2.50^t{gpkg}(21:30:35 07/11/24)(-test PYTHON_TARGETS="python3_12 -python3_11")
     Homepage:            https://www.gns3.com https://github.com/GNS3/gns3-server
     Description:         GNS3 server to asynchronously manage emulators

Found 2 matches
```

 **To Reproduce**

1. Stop the current running project
2. Go to 'File'
3. Click on 'Save project as...'
4. Type in the desired new project name
5. New project is created. And the GUI show the new projects name.
6. Verify the '~/GNS3/project/' directory
7. Desired project name directory name is not found here the directory is called `62b9750e-7000-4c44-9566-078ca8ed85da`

**Screenshots or videos**

1. Current stopped project:
![2024-11-10-172944_735x558_scrot](https://github.com/user-attachments/assets/bc089d30-4f07-4b78-885c-756b926b1d4a)

4. The desired new project name:
![2024-11-10-173124_837x400_scrot](https://github.com/user-attachments/assets/4e75e855-1b15-47ac-b48b-3c4f5b1dc08a)

5. Everything is fine in the GUI:
![2024-11-10-173157_735x558_scrot](https://github.com/user-attachments/assets/7bcad371-7114-4a96-8a17-06fcdbe9590d)

7. Projects directory listing:
```
ls -lah | grep 17:31
drwxr-xr-x 188 needle needle 8.0K Nov 10 17:31 .
drwxr-xr-x   4 needle needle   94 Nov 10 17:31 62b9750e-7000-4c44-9566-078ca8ed85da
drwxr-xr-x   4 needle needle   85 Nov 10 17:31 VRP-SR-MPLS-00-MPLS-network-day-0
```

**Additional context**

The .gns3 filename in the random directory name is created as desired, and everything is as it should. Only the directory name is kind of randomly generated. This did not happen with previous GNS3 versions. Currently downgraded to GNS3-2.2.49 version where this does not happen.

Contents of the random directory showing that the project file is named correctly and  working:

```
pwd       
/home/needle/GNS3/projects/62b9750e-7000-4c44-9566-078ca8ed85da
ls -lah
total 52K
drwxr-xr-x   4 needle needle   94 Nov 10 17:31 .
drwxr-xr-x 188 needle needle 8.0K Nov 10 17:31 ..
drwxr-xr-x   2 needle needle  116 Oct 24 15:34 configs
drwxr-xr-x   6 needle needle   59 Oct 24 07:50 project-files
-rw-r--r--   1 needle needle  40K Nov 10 17:31 VRP-SRv6-01-Enabling-IPv6-routing-day-1.gns3
```

**Comment by grossmj** [comment]
Fixed, thanks for catching that! :+1:
