### ISSUE TITLE
Unable to Import IOU 17.15.1 Images (L2 and L3)

### ISSUE THREAD

**Issue by gitsakar** [GNS3/gns3-server#2449]
Unable to import Cisco IOU L3 version 17.15.1 and Cisco IOU L2 version 17.15.1
The error reads as file was not found. However, the image upload was successful and is listed in the /opt/gns3/images/IOU.

I have tried complete uninstallation and reinstallation of both GNS3 and GNS3 VM

 - OS: Windows 10 22H2 (OS Build 19045.5131)
 - GNS3 version 2.2.51
 - GNS3 VM 2.2.51 on VMware Workstation Pro 17.6.1 build-24319023

![image](https://github.com/user-attachments/assets/6b5866bd-2fcf-4772-8bfe-2e88f24c4cba)

![image](https://github.com/user-attachments/assets/7dace4a1-5b02-4882-addc-d36e4ee38de7)

**Comment by grossmj** [comment]
> It seems the issue is a little bit widespread. Another user is facing similar issue but with Cisco 7200 version 153-3.XB12 https://www.gns3.com/community/featured/ios-images-not-being-recognized-in-gns-vm-v2-2-51

Indeed, I think I found what was wrong and fixed that in https://github.com/GNS3/gns3-server/pull/2448

**Comment by grossmj** [comment]
This should be fixed in the next version: v2.2.52

Thanks 👍
