### ISSUE TITLE
If KVM is enable and not available raise error

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#245]

**Comment by grossmj** [comment]
Apparently the only thing that kvm-ok does is to check for /dev/kvm but unfortunately it does not say anything if I run a VirtualBox VM that uses VT-x and try to start a Qemu VM with --enable-kvm.

```
$ kvm-ok 
INFO: /dev/kvm exists
KVM acceleration can be used
```

Anyway, we can definitely check for /dev/kvm ourselves :)
