### ISSUE TITLE
Bare metal install Ubuntu Upgrade Missing Projects/Images

### ISSUE THREAD

**Issue by ob7** [GNS3/gns3-server#2453]
# gns3-server upgrade issue: Projects/Images not appearing

After doing an `apt update` / `upgrade` on Ubuntu 20.04.6 LTS to bump `gns3-server` version to `2.2.51`, and upgrading the `gns3-gui` to match the version, projects/images are not appearing as if it's a clean install of `gns3-server` or not connecting. The `gns3-gui` indicates it is connecting, however. The images/projects are still on the server where they were before inside `/root/GNS3/`.

The projects/images are also not visible in the web UI.

## Cause

Somewhere between first installing using Ubuntu 18.04, and various upgrades along the way, the working directory changed from `/root/` to `/var/lib/gns3-server`.

## Solution

Move or copy the following directories:

- `/root/GNS3`
- `/root/.local`
- `/root/.config`

To:

- `/var/lib/gns3-server`

Then, update the ownership of the new directory:

###
chown -R gns3-server:gns3-server /var/lib/gns3-server
###

## Notes

Not sure if this is actually an upgrade issue or due to `gns3-server` being installed into the wrong directory (`root`) initially, but it presented itself when going from `2.2.50` to `2.2.51`.  Possibly from user error during initial install or trying multiple methods of install such as from source / ppa.  Or systemd services file was overwritten in recent update changing where it pointed to for configuration.

Posting this in case anyone else encounters a similar issue.

## Suggestions

Potentially https://docs.gns3.com/docs/getting-started/installation/remote-server should be updated with more current instructions, as it currently suggests people start off with Ubuntu 18.04, but starting with a more recent version like 20.04 may avoid this issue.

This issue is specific to the repository-based installation. However, I believe the confusion arose due to a lack of clarity regarding the installation methods, with the repository-based approach being mixed up with the source-based approach during a bare metal installation.

I couldn't find comprehensive instructions for performing a full bare metal installation from source, so I've created a guide here: https://github.com/ob7/gns3-server-bare-metal-install. It details the steps I took to perform a fresh installation from source on Ubuntu 20.04 without using the PPA. I hope others find it useful.

**Comment by grossmj** [comment]
We have release v2.2.52 today. Please can you try again to see if the problem is still there? thanks.

**Comment by ob7** [comment]
Yep working fine in v2.2.52
