### ISSUE TITLE
BUG - deletion of links through web-ui (server-related)

### ISSUE THREAD

**Issue by miromeir** [GNS3/gns3-server#2459]
This was only tested in the web-ui, it throws an error upon deleting a link.
The reason is CORS related, probably the preflight checks of the DELETE request is being blocked.
The solution was to add 
```python
allow_methods="*"
``` 
to the cors ResourceOptions in web_server.py
Can you please check if this bug is reproducible?
if so, i'd love to submit a pull request, perhaps discuss an alternative solution.

**Comment by grossmj** [comment]
I am a bit confused because allow_methods is already set with "*": https://github.com/GNS3/gns3-server/blob/3.0/gns3server/api/server.py#L70

**Comment by grossmj** [comment]
Sorry, I thought you were talking about v3.0.


For v2, I think you must have changed this code:


https://github.com/GNS3/gns3-server/blob/master/gns3server%2Fweb%2Fweb_server.py#L314-L325


Is this correct?
