### ISSUE TITLE
[GNS3 3.0.0] If a normal user (not an administrator) opens the user management page in the web interface, the session is terminated

### ISSUE THREAD

**Issue by nwhisper2014** [GNS3/gns3-server#2460]
**Describe the bug**
If a normal user (not an administrator) opens the user management page in the web interface, the session is terminated. No error or restriction messages appear in the web interface or in the log.

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux (oficial apliance)
 - GNS3 version: 3.0.0
 - KVM, VirtualBox, ESXi

**To Reproduce**
1. Log in to the web interface as a normal user (not an administrator)
2. In the menu select "Management"

**Screenshots or videos**

![screenhot](https://github.com/user-attachments/assets/e44587b4-9b2a-4653-ad44-09f15aa447d8)

**Comment by grossmj** [comment]
Fixed however I am not sure this is the best way since I have limited Angular knowledge...
