### ISSUE TITLE
Timeout error for PUT call to http://127.0.0.1:3080/v2/compute/... after 20s

### ISSUE THREAD

**Issue by bs0c** [GNS3/gns3-server#2461]
Hi!
I get errors when my projects have more than 10 items. What is the problem?

**In console:**

> Timeout error for PUT call to http://127.0.0.1:3080/v2/compute/projects/d2b16700-f168-40dc-9591-b7349f08fbec after 20s

**In log:**

> 2024-12-26 13:08:08 INFO docker_vm.py:592 Docker container 'PTO1' fix ownership, state = running
> 2024-12-26 13:08:11 ERROR route.py:216 Controller error detected: <class 'gns3server.controller.compute.ComputeError'>
> Traceback (most recent call last):
>   File "/usr/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1058, in start
>     message, payload = await protocol.read()  # type: ignore[union-attr]
>                        ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/aiohttp/streams.py", line 643, in read
>     await self._waiter
> asyncio.exceptions.CancelledError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.12/site-packages/gns3server/controller/compute.py", line 511, in _run_http_query
>     response = await self._session().request(method, url, headers=headers, data=data, auth=self._auth, chunked=chunked, timeout=timeout)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 690, in _request
>     await resp.start(conn)
>   File "/usr/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1053, in start
>     with self._timer:
>          ^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/aiohttp/helpers.py", line 749, in __exit__
>     raise asyncio.TimeoutError from exc_val
> TimeoutError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.12/site-packages/gns3server/web/route.py", line 200, in control_schema
>     await func(request, response)
>   File "/usr/lib/python3.12/site-packages/gns3server/handlers/api/controller/project_handler.py", line 118, in update
>     await project.update(**request.json)
>   File "/usr/lib/python3.12/site-packages/gns3server/controller/project.py", line 176, in update
>     await compute.put(
>   File "/usr/lib/python3.12/site-packages/gns3server/controller/compute.py", line 574, in put
>     response = await self.http_query("PUT", path, data, **kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/gns3server/controller/compute.py", line 344, in http_query
>     response = await self._run_http_query(method, path, data=data, **kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/gns3server/controller/compute.py", line 513, in _run_http_query
>     raise ComputeError("Timeout error for {} call to {} after {}s".format(method, url, timeout))
> gns3server.controller.compute.ComputeError: Timeout error for PUT call to http://127.0.0.1:3080/v2/compute/projects/d2b16700-f168-40dc-9591-b7349f08fbec after 20s

**Comment by z5241248** [comment]
The url request looks corrent, are you using a vpn?

[https://gns3-server.readthedocs.io/en/stable/api/v2/compute/project/projectsprojectid.html#sample-session](https://gns3-server.readthedocs.io/en/stable/api/v2/compute/project/projectsprojectid.html#sample-session)

**Comment by grossmj** [comment]
I have fixed the problem. This should work in v2.2.53
