### ISSUE TITLE
python-jose library is unmaintained

### ISSUE THREAD

**Issue by nuqleo** [GNS3/gns3-server#2466]
Hi,

gns3-server 3.0.0 uses unmaintained library python-jose

https://github.com/mpdavis/python-jose/issues/340

https://github.com/lepture/authlib suggested instead of python-jose.

python-jose removed from Fedora but python-authlib is available.

Can you port the code to use authlib?

**Comment by grossmj** [comment]
Thanks, I ported the code to joserfc

**Comment by nuqleo** [comment]
Thanks for fixing this.
Unfortunately there is no package python-joserfc in Fedora repository (the only missing dependency), only python-authlib available
A quick search in Debian packages showed the same situation/

**Comment by grossmj** [comment]
> joserfc is derived from Authlib to facilitate easy maintenance and modularity. Previously, Authlib was developed as a mono library to design a comprehensive API that covered a wide range of authentication and security needs. However, as the project evolved, it became evident that splitting the modules from Authlib would improve maintainability and provide more focused and specialized libraries.

I could have used authlib however it seems the focus will be on joserfc going forward: https://jose.authlib.org/en/guide/introduction/

**Comment by nuqleo** [comment]
I am unable to create python3-joserfc package for CentOS 9 because it installs in UNKNOWN-0.0.0.dist-info (installs fine in latest Fedora). But python3-authlib package is available for  CentOS 9.
