### ISSUE TITLE
[gns3-server 3.0.1] /etc/hosts issue

### ISSUE THREAD

**Issue by AdrianSimionov** [GNS3/gns3-server#2468]
gns3-server version 3.0.1 has a new line added to /etc/hosts file:
127.0.0.254 xml.cisco.com

This configuration will crash coredump L2IOU version 17.12.1 and 17.15.1 when present.

Removing the DNS translation from /etc/hosts will allow both 17.12.1 and 17.15.1 L2IOU versions to start properly.

Seems gns3-server version 2.2.52 does not have the same configuration present into /etc/hosts.

**Comment by grossmj** [comment]
This has been fixed in https://github.com/GNS3/gns3-gui/issues/3685

**Comment by andrei-korshikov** [comment]
@AdrianSimionov see https://github.com/GNS3/gns3-registry/issues/868#issuecomment-3264630108 for an explanation.
