### ISSUE TITLE
Incorrect vboxmanage sudo command

### ISSUE THREAD

**Issue by tamtt3** [GNS3/gns3-server#247]
Hi,

There is error in line 100 of file:  gns3-server/gns3server/modules/virtualbox/__init__.py
The command must have a space right after user name.
Like this: sudo_command = "sudo -i -u {} ".format(vbox_user) + " ".join(command)
Instead of: sudo_command = "sudo -i -u {}".format(vbox_user) + " ".join(command)
Note: Add a space after {}

**Comment by noplay** [comment]
Thanks a lot
