### ISSUE TITLE
Could not start vbox instance if gns3-server start as root user due to permission of /tmp/gns3_vbox

### ISSUE THREAD

**Issue by tamtt3** [GNS3/gns3-server#248]
Hi,
I'm using Ubuntu 14.04 and GNS3 1.3.7.

I've already apply the Fix #247 to allow vboxmanage command execute correctly.

Steps to reproduce:
1: configure gns3-server run as root user by modify /etc/init/gns3.conf
2: change setting: run virtual box as another user to normal user. (because if run as root we will not see any vbox instance)
3: go to GNS3-GUI start Vbox instance.

Result:  Server error from 127.0.0.1:8000: Minix-PC1: Could not connect to the pipe /tmp/gns3_vbox/33307342-6858-49db-82ed-34439a96afca: [Errno 2] No such file or directory

Currently I've to work-around by execute: chmod 777 /tmp/gns3_vbox

**Comment by noplay** [comment]
This mean when we use sudo we need to chown the file to the VBOX, but if GNS3 is not started as root we can't access to the file. We can set rights to 777 but from a security point of view ...

@grossmj what did you think?

**Comment by tamtt3** [comment]
how about if we define temp directory with format: /tmp/gns3_vbox_<gns3-username>? and set owner to that user.

**Comment by noplay** [comment]
The issue is you start gns3 as bob and vbox as alice. Which user should be the owner of the file ?

**Comment by ehlers** [comment]
I'm **strongly** against running any complex application as root. The security problems are way too high. As an example see what the wireshark people have to say: https://wiki.wireshark.org/Security .

So either that application needs the elevated privileges only at start and drops them afterwards (e.g. apache) or it uses some small tools with elevated privileges (e.g. dump cap), which is controlled by the big program (wireshark) in non privileged mode.

I think for GNS3 the wireshark model works best. dynamips and iouyap (and ubridge ?) can have elevated privileges, but there should be **no** need for GNS3 client or server to need root privileges. If there are cases, then those cases should be fixed, not the issues when running as root.

I suggest giving a big fat warning, when running GNS3 as root, maybe even refuse to run.

**Comment by grossmj** [comment]
I totally agree. We should even drop that sudo option we have.

**Comment by noplay** [comment]
I suggest to drop it in 1.4. We have no good solution at all for the sudo.

**Comment by grossmj** [comment]
I dropped the option. We do not recommend running GNS3 as root.

**Comment by noplay** [comment]
Wireshark display a warning when started as root

On Fri, Jul 3, 2015 at 10:38 PM, Jeremy Grossmann <notifications@github.com>
wrote:

> I dropped the option. We do not recommend running GNS3 as root.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-server/issues/248#issuecomment-118422042>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>
