### ISSUE TITLE
Dynamips not found

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#249]
Some Windows users have had issues with the Dynamips path. Need to investigate.

https://community.gns3.com/thread/9004
https://community.gns3.com/thread/8995

**Comment by noplay** [comment]
For the user the server file is written by the GUI in:
I found gns3_server.ini from this location: C:\Users\smithjsp\AppData\Roaming\GNS3

Instead of:
'C:\Program Files\GNS3\%APPDATA%\GNS3'
