### ISSUE TITLE
SPICE support for Qemu VMs

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#256]
After a discussion at the RMLL with some guys they point me to SPICE. It's like RDP for qemu. The feedback is it really really faster than VNC (they use a remote Windows with SPICE)

It seem a client exist for all OS (people confirm me it's work on Linux and Windows but never test the OSX builds).

A basic websockify client exist also:
http://www.spice-space.org/page/Html5

**Comment by grossmj** [comment]
That is definitely on the roadmap :+1: 

So far I want to add support for:

- SPICE for Qemu VMs
- VRDP for VirtualBox VMs
- VNC for VMware VMs

**Comment by noplay** [comment]
I think If we do that we need to package virt-viewer in the installer for Windows and OSX.

**Comment by jean-christophe-manciot** [comment]
Virt-viewer is already available on Linux; how about adding the call in "General preferences - Console applications" & at the node level (cf. https://github.com/GNS3/gns3-gui/issues/675)?

**Comment by jean-christophe-manciot** [comment]
There are also a few VNC clients available on Linux: Remmina & TightVNC come to mind.

**Comment by noplay** [comment]
The main issue with Spice is *virt-viewer*.

For Windows it's available http://www.spice-space.org/download.html. But for MacOS nobody made binaries. :( Don't know if it's easy to build.

**Comment by noplay** [comment]
Open Stack people seem to use spice:
http://silverskysoft.com/open-stack-xwrpr/2015/07/enable-spice-html5-console-access-in-openstack-kilo/

**Comment by cayspekko** [comment]
You can use spice with GNS3 using additional settings in the qemu configuration. It's useful for copy/paste text files. Also drag and drop files is handy. It also has better graphics support.  The spice-vdagent has to be installed on the guest machine, then add these these commands to the additional settings in the qemu configuration:
-vga qxl -spice port=5800,addr=127.0.0.1,disable-ticketing -device virtio-serial-pci -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 -chardev spicevmc,id=spicechannel0,name=vdagent

**Comment by jean-christophe-manciot** [comment]
@cayspekko Very nice try, unfortunately it does not work with virt-viewer as spice client when adding your options to "-enable-kvm -cpu host"

**Comment by jean-christophe-manciot** [comment]
Here is an example of what is **automatically generated by virt-manager and works with virt-viewer:**

qemu-system-x86_64 -enable-kvm -name guest=KVM-Ubuntu-Gnome-Desktop-16.04,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-9-KVM-Ubuntu-Gnome-Des/master-key.aes -machine pc-i440fx-2.6,accel=kvm,usb=off,vmport=off -cpu host -m 2048 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid e9ae906c-611e-4120-bc2e-199b5fc95e5e -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-9-KVM-Ubuntu-Gnome-Des/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x7.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x7 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x7.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x7.0x2 **-device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x6** -drive file=/media/actionmystique/SAMSUNG-850-Ext4/KVM-Qemu/VMs/KVM-Ubuntu-Gnome-Desktop-16.04,format=vmdk,if=none,id=drive-virtio-disk0 -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x8,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -netdev tap,fd=27,id=hostnet0,vhost=on,vhostfd=29 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:59:32:cc,bus=pci.0,addr=0x3 -netdev tap,fd=30,id=hostnet1,vhost=on,vhostfd=31 -device virtio-net-pci,netdev=hostnet1,id=net1,mac=52:54:00:ae:58:44,bus=pci.0,addr=0x4 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 **-chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -spice port=5900,addr=127.0.0.1,disable-ticketing,image-compression=off,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x2** -device intel-hda,id=sound0,bus=pci.0,addr=0x5 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x9 -msg timestamp=on 

However, if I insert the bolded options inside an Ubuntu Gnome VM advanced settings options on GNS3, virt-viewer does not see it; I must be missing something.

**Comment by noplay** [comment]
I think in order to view it with virt-viewer virt-manager will probably write an info somewhere in a file.

**Comment by grossmj** [comment]
This has been implemented.
