### ISSUE TITLE
Improve the experience when KVM is not supported

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#263]
We can probably improve the experience for this users:
https://community.gns3.com/message/32127

The issue is even if you have a VMware workstation 11 and a processor 64 bit you can have unsupported virtualization instructions.

**Comment by grossmj** [comment]
I think there is no easy way to find if a processor supports virtualization instructions on Windows. I haven't tested on OSX.

**Comment by noplay** [comment]
I think all osx support them

**Comment by grossmj** [comment]
How do you think we could improve the user experience?

**Comment by noplay** [comment]
Perhaps we can improve it in the VM and ask if user want to turn off KVM if KVM is not available

**Comment by grossmj** [comment]
Let's do this. By choosing to deactivate KVM we write the following in the server config file:

```
[Qemu]
enable_kvm=False
```

**Comment by noplay** [comment]
Done on the VM side. Testable with the upgrade VM feature
