### ISSUE TITLE
Invalid umask on --daemon start

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#264]
When gns3server is started with --daemon an umask(700) is set.

That's wrong twice:
- umasks are typically expressed in octal notation, so I assume umask(0o700) is meant.
- A set bit in an umask defines a cleared permission. Therefore umask(0o700) gives no permissions to the user and all permissions to the group and world.  
I assume umask(0o077) was meant, which gives all permissions to the user and none to group and world. Or maybe umask(0o007), which gives all permissions to the user and group and none to world.

**Comment by noplay** [comment]
Thanks!
