### ISSUE TITLE
when bridge to another virtual machine via cloud , the device in Topology can not ping to each other 

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-server#270]
version 1.3.7
OS lubuntu 15.04 (working in vmware workstation)
when I running one Topology, and use cloud to bridge to another virtual machine , the device can not ping to  each other , when remove the cloud and restart the Topology again, they are working .
Is this a problem ?

**Comment by noplay** [comment]
What did you connect to the cloud?

**Comment by superwolfboy** [comment]
I only connect the eth0 to cloud.but no root (previously it not promised by GNS3 ), I didn't test root yet, but my friend test by root, not ok also.

**Comment by superwolfboy** [comment]
I have tested again , one IOU connect to the cloud without root , the GNS3 allow connect ,but every device in this Topology can not ping to each other, one other device connect to clould without root , the GNS3 not allowed.
but login with root , it is working fine .

**Comment by grossmj** [comment]
I think we will need more info: what Linux distro do you run?

Even better if you can provide snaphosts and as many details as you can to help us understand the issue.

Thanks,

**Comment by superwolfboy** [comment]
sorry for delay such a long time cause my job.,,
my OS is Lubuntu 15.04 
![screenshot](https://cloud.githubusercontent.com/assets/9411604/8960062/b3d59af6-3640-11e5-918b-823928a093c1.png)
