### ISSUE TITLE
IOUs cannot run at same time when remote GNS3 GUI client and local GNS3 GUI client both starts IOU

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-server#298]
OS: Lubuntu 15.04
Version GNS3 1.3.9
Windows which running GNS3 Gui for win Version: Win10
The GNS3 server running on Lubuntu with systemctl

Use GNS3 GUI on windows connect with Lubuntu GNS3 server and start IOU(IOU working )
at this moment , go back to Lubuntu desktop ,and start the GNS3 gui on lubuntu, 
run one topology with IOU on it , the IOU can not start.

otherwise , start IOU on Lubuntu GNS3 first , the GNS3 on windows can not start IOU also

Strange...

![image](https://cloud.githubusercontent.com/assets/9411604/9384289/1358baec-4782-11e5-92e5-8c8aa3c6411b.png)

**Comment by noplay** [comment]
Thanks for the report

**Comment by noplay** [comment]
From the screenshot it seem you have two server running at the same time (one for the GUI and one for server) perhaps it's create the issue. Could you try with turning off the server start in the Lubuntu GUI. 

Turn off also auth in the gns3_server.conf to avoid issue with that.

**Comment by superwolfboy** [comment]
auth = False already in gns3_server.conf
How to  turning off the server start in the Lubuntu GUI, and meanwhile the GUI in Lubuntu also working normailly?

**Comment by noplay** [comment]
In preferences just uncheck the local server checkbox.

**Comment by superwolfboy** [comment]
understood,
as my known, it need add the virtual equipments again

**Comment by grossmj** [comment]
I consider this has been resolved.
