### ISSUE TITLE
Starting a saved VirtualBox VM results in cryptic error message

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#299]
GNS3: 1.4.0beta1, OS: Mac OS X 10.9.5, VirtualBox 4.3.30

See https://community.gns3.com/message/46439#46439

When a VM is in the saved state and you try to start it in GNS3, you will get this error message:

```
Server error from http://192.168.1.10:8000: ost-drone: VirtualBox has returned an error: VBoxManage: error: The machine is not mutable (state is Saved)
VBoxManage: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "COMSETTER(CableConnected)(ValueUnion.f)" at line 1480 of file VBoxManageModifyVM.cpp
```

In gns3server/modules/virtualbox/virtualbox_vm.py line 197 the VM state "saved" is accepted, but VirtualBox can't handle the modifications GNS3 wants to make on the VM.

So please, either accept only the poweroff state, or handle the saved state.

**Comment by grossmj** [comment]
Got it, will fix this. We are both away for a few more days ;)
