### ISSUE TITLE
Qemu allow user to create their own interface

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#303]
Following the comment of @ehlers on https://github.com/GNS3/gns3-server/commit/b1ef49672e987a0241ae3c1ebe0e90debd10a5fe#commitcomment-12936963

Should we allow user to create Qemu interface? And how to do it. 

Actually you can do it via additional options like this:
```
-nographic -net nic,vlan=999,model=e1000 -net user,vlan=999,hostfwd=tcp::50001-:7878
```

**Comment by noplay** [comment]
The problem of the current behavior is GNS3 don't know about the additional interfaces. If we ask qemu about the list of interfaces we will see more than expected.  I think one day this can lead to bugs.

**Comment by noplay** [comment]
Perhaps a solution is to remove the need of such features by finding what is missing in current interfaces support.

Actually I see we need to support port forward.

**Comment by ehlers** [comment]
First I agree that network interface creation in the additional options is a hack, that will likely creates issues and therefore should be avoided.

The best way, of cause, is to remove the need for this by supporting missing features. So if port forwarding is supported for the NAT cloud interface, that be very nice. But then it should be implemented not only for QEMU but also for VirtualBox and VMware. That could be quite complex.

**Comment by grossmj** [comment]
```
The best way, of cause, is to remove the need for this by supporting missing features. So if port forwarding is supported for the NAT cloud interface, that would be very nice. But then it should be implemented not only for QEMU but also for VirtualBox and VMware. That could be quite complex.
```

I agree, I think this is the best way. It should be fairly easy to do the same for VirtualBox and I need to research about VMware.
