### ISSUE TITLE
Validation error when loading/saving a QEMU image

### ISSUE THREAD

**Issue by wdennis** [GNS3/gns3-server#304]
GNS3 management console. Running GNS3 version 1.4.0beta1 on Linux (64-bit) with Qt 5.2.1.
Copyright (c) 2006-2015 GNS3 Technologies.

=> {'qemu_path': '/usr/bin/qemu-system-x86_64', 'acpi_shutdown': False, 'options': '-net user,vlan=0,net=192.168.0.0/24,hostfwd=tcp::1401-:22', 'hda_disk_image': '/home/gns3user/GNS3/images/CumulusVX-2.5.3-4eb681f3df86c478.qcow2', 'hdd_disk_interface': 'ide', 'adapters': 4, 'hdb_disk_interface': 'ide', 'adapter_type': 'virtio', 'legacy_networking': False, 'hda_disk_interface': 'ide', 'name': 'Cumulus-VX-sw1-1', 'console': 2000, 'mac_address': '00:00:ab:f4:79:00', 'console_type': 'telnet', 'platform': 'x86_64', 'boot_priority': 'c', 'process_priority': 'normal', 'ram': 1024, 'cpus': 1, 'hdc_disk_interface': 'ide', 'cpu_throttling': 0} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['topology']['properties']['nodes']['items']['properties']['properties']:
    {'oneOf': [{'$ref': '#/definitions/properties_vpcs'},
               {'$ref': '#/definitions/properties_dynamips'},
               {'$ref': '#/definitions/properties_dynamips_frame_relay'},
               {'$ref': '#/definitions/properties_qemu'},
               {'$ref': '#/definitions/properties_virtualbox'},
               {'$ref': '#/definitions/properties_vmware'},
               {'$ref': '#/definitions/properties_iou'},
               {'$ref': '#/definitions/properties_cloud_host'}],
     'type': 'object'}

On instance['topology']['nodes'][0]['properties']:
    {'acpi_shutdown': False,
     'adapter_type': 'virtio',
     'adapters': 4,
     'boot_priority': 'c',
     'console': 2000,
     'console_type': 'telnet',
     'cpu_throttling': 0,
     'cpus': 1,
     'hda_disk_image': '/home/gns3user/GNS3/images/CumulusVX-2.5.3-4eb681f3df86c478.qcow2',
     'hda_disk_interface': 'ide',
     'hdb_disk_interface': 'ide',
     'hdc_disk_interface': 'ide',
     'hdd_disk_interface': 'ide',
     'legacy_networking': False,
     'mac_address': '00:00:ab:f4:79:00',
     'name': 'Cumulus-VX-sw1-1',
     'options': '-net '
                'user,vlan=0,net=192.168.0.0/24,hostfwd=tcp::1401-:22',
     'platform': 'x86_64',
     'process_priority': 'normal',
     'qemu_path': '/usr/bin/qemu-system-x86_64',
     'ram': 1024}

Validation error when dumping the topology.
It's probably a false positive but please send the .gns3 to developers@gns3.net.
Thanks !

**Comment by noplay** [comment]
Thanks it should be fixed in next release
