### ISSUE TITLE
Backport bug fix for VLAN saving in c3600 IOS routers

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#315]
https://github.com/GNS3/gns3-server/commit/958274e8f682e3624d516f57b4b5f351cc48d01d

**Comment by noplay** [comment]
Is a cherry pick of the commit enough? Or the backport is more complicate?

**Comment by grossmj** [comment]
Cherry pick should work well :+1:

**Comment by noplay** [comment]
Done
