### ISSUE TITLE
VMware: No VMnet interface available between vmnet2 and vmnet255

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#324]
GNS3 version 1.4.0b3 on Darwin (64-bit) with Python 3.4.3 Qt 5.5.0, VMware Fusion 8.0

When I initialize the VMnet interface list in preferences / VMware preferences / Network, I can use VMware VMs until I close GNS3.

But when I re-open GNS3 and I don't use the VMware Network initialization, I always get the following error when I start a VMware VM:
```
Server error from http://192.168.1.10:8000: NETem: No VMnet interface available between vmnet2 and vmnet255. Go to preferences VMware / Network / Configure to add more interfaces.
```

Even when I configured another range, it always reports the range 2-255. But even when I configure the whole range, on the next start I get this error message. It seems, that the list of available interfaces is only filled, when the VMnets are initialized.

Is it meant that way ?

**Comment by ehlers** [comment]
After complete removal of the vmnet configuration and a clean start it now seems to work, at least when fusion is started. When fusion is not started, the whole vmnet stuff isn't active and therefore doesn't work.

As I can't reproduce, I close it now.

**Comment by noplay** [comment]
Thanks for the informations

Le lun. 28 sept. 2015 19:06, Bernhard Ehlers <notifications@github.com> a
écrit :
