### ISSUE TITLE
VMware: Add support for different adapter types

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#325]
The default adapter type PCnet32 supports only a MTU of 1500. Would be nice, if the other adapter types e1000 and vmxnet3 would be supported, see https://communities.vmware.com/thread/463728

**Comment by grossmj** [comment]
@ehlers you can change the network adapter type in the VM template preferences, from default to e1000 or vmxnet3. Is this what you were looking for?

**Comment by ehlers** [comment]
Yes, that was it. I don't know, how I can overlook it.

You can close it.
