### ISSUE TITLE
VMware Player doesn't work on Linux

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#326]
GNS3 version 1.4.0b3 on Linux (64-bit) with Python 3.4.2 Qt 5.3.2, VMware Player 12.0.0

When adding a new VM, this error message pops up:
![vmware_player](https://cloud.githubusercontent.com/assets/896406/10164276/f6736eb2-66b8-11e5-9bbe-483eb2570b03.png)

Reason is, that there is no excutable named "vmware", only "vmplayer".

As a workaround I made a symbolic link from vmplayer to vmware, now it works.

**Comment by grossmj** [comment]
Hi Bernhard,

What is the output of ```cat /etc/vmware/config | grep product.name```?

Thanks,

**Comment by ehlers** [comment]
```
behlers@dell:~$ cat /etc/vmware/config | grep product.name
behlers@dell:~$ cat /etc/vmware/config
.encoding = "UTF-8"
NETWORKING = "yes"
VMBLOCK_CONFED = "yes"
gksu.rootMethod = "sudo"
libdir = "/usr/lib/vmware"
VMCI_CONFED = "yes"
VSOCK_CONFED = "yes"
initscriptdir = "/etc/init.d"
authd.fullpath = "/usr/sbin/vmware-authd"
bindir = "/usr/bin"
installerDefaults.componentDownloadEnabled = "yes"
installerDefaults.autoSoftwareUpdateEnabled.epoch = "7160337830"
vix.config.version = "1"
player.product.version = "12.0.0"
installerDefaults.dataCollectionEnabled.epoch = "7979668096"
installerDefaults.dataCollectionEnabled = "no"
installerDefaults.transferVersion = "1"
installerDefaults.autoSoftwareUpdateEnabled = "no"
product.buildNumber = "2985596"
vmware.fullpath = "/usr/bin/vmware"
vix.libdir = "/usr/lib/vmware-vix"
behlers@dell:~$ 
```

**Comment by ehlers** [comment]
Just downgraded from VMware Player 12.0.0 to 7.1.2. Same result, vmware binary doesn't exist, only vmplayer.

Just another information (not a bug):
VMware Player 12.0.0 doesn't seem to support headless mode in the free version. vmrun returns an error and the VMware log says, that a license is needed for this feature. With version 7.1.2 headless mode works fine, so for me it's the better choice.

**Comment by noplay** [comment]
```
pieter 29 sept. 2015 11:44 (en réponse à Julien Duponchelle)
 
Python 3.4.3 (default, Jul 28 2015, 18:20:59)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> vm_binaries = [shutil.which('vmware'), shutil.which('vmplayer')]
>>> vm_binaries
[None, '/usr/bin/vmplayer']
 
So vmware_path = shutil.which('vmware') or shutil.which('vmplayer') should do the trick.
```

**Comment by grossmj** [comment]
I had another idea to handle this. The problem is not to find vmware or vmplayer, it is to be sure that VMware is installed. 

The Linux technique is apparently to look into the /etc/vmware/config file like done in https://github.com/cloudbase/nova-vix-driver/blob/master/vix/vixutils.py#L119

However, according to @ehlers output, this is not a reliable way...

**Comment by ehlers** [comment]
I don't know, if the vmware-installer is always present. If it is, you can use it to query the installed products:

```
behlers@dell:~$ vmware-installer -l
Product Name         Product Version     
==================== ====================
vmware-player        7.1.2.2780323       
vmware-vix           1.14.2.2780323      
```

**Comment by grossmj** [comment]
Finally going with Julien's patch is the easiest and most reliable way I think.
