### ISSUE TITLE
Issues with vmware lock

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#328]
https://community.gns3.com/thread/22317

**Comment by noplay** [comment]
With fusion it's not working and I disable it. Perhaps we need to understand the format of the file.

**Comment by ehlers** [comment]
My results with fusion 8:
- &lt;VM&gt;.vmx.lck directory non-existent: VM not in use
- &lt;VM&gt;.vmx.lck directory non-empty: VM selected in fusion application (no matter if running or not) or running. The contents doesn't change, no matter if it is only selection in Fusion application or if it's running
- &lt;VM&gt;.vmdk.lck directory non-empty: Disk in use of a running VM

**Comment by noplay** [comment]
Perhaps a better way to do it:

```
➤  /Applications/VMware\ Fusion.app/Contents/Library/vmrun list
Total running VMs: 1
/Users/noplay/Documents/Virtual Machines.localized/GNS3 VM.vmwarevm/GNS3 VM.vmx
```

**Comment by grossmj** [comment]
:+1:

**Comment by grossmj** [comment]
Hopefully we should not have issues because GNS3 always read the vmx file just before making any change to it.
