### ISSUE TITLE
error: bad character range

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#332]
https://app.getsentry.com/gns3/gns3-server/group/86305923/

```
error: bad character range
(14 additional frame(s) were not displayed)
...
  File "c:\Python\64-bit\3.4\lib\re.py", line 288, in _compile
  File "c:\Python\64-bit\3.4\lib\sre_compile.py", line 465, in compile
  File "c:\Python\64-bit\3.4\lib\sre_parse.py", line 748, in parse
  File "c:\Python\64-bit\3.4\lib\sre_parse.py", line 358, in _parse_sub
  File "c:\Python\64-bit\3.4\lib\sre_parse.py", line 504, in _parse
```

**Comment by grossmj** [comment]
Seems we should use ```glob.escape()``` however it was introduced in Python 3.4. @noplay Do we still support python 3.3?

**Comment by grossmj** [comment]
Found out we already something to handle this: https://github.com/GNS3/gns3-gui/blob/master/gns3/utils/glob.py ;)

**Comment by noplay** [comment]
The glob.py is removed in 1.4 because we don't support 3.3. Be carefull during the merge process.

**Comment by noplay** [comment]
I have fixe the error with the GUI patch in 1.3 and in 1.4 we use glob.escape

**Comment by grossmj** [comment]
Glob is also used in

https://github.com/GNS3/gns3-server/blob/9b740e85d0837d416c63c3c9dbf21989b993fb95/gns3server/modules/dynamips/nodes/router.py#L340

and

https://github.com/GNS3/gns3-server/blob/c43960fbfd3d5fb8694634d5442ad03bd2179a5b/gns3server/modules/iou/iou_vm.py#L489

These should be protected as well.

**Comment by noplay** [comment]
I'm on it

**Comment by noplay** [comment]
And backported to unstable
