### ISSUE TITLE
Allow SSH connections to devices

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#333]
May leverage https://github.com/ktbyers/netmiko

**Comment by noplay** [comment]
Perhaps port forward can solve this issue.

**Comment by grossmj** [comment]
There is some research to do here. Maybe we could something similar with VIRL2, they use a breakout utility to create secure SSH connections to devices: https://www.youtube.com/watch?v=5xUvqDMxH3g&t=1410s

**Comment by ziajka** [comment]
Options:
1. Allow to connect by SSH directly
2. "Proxy" via the secure channel

**Comment by grossmj** [comment]
Duplicate of https://github.com/GNS3/gns3-server/issues/2181
