### ISSUE TITLE
Qemu master image is modified instead of the linked image

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#342]
```
image is defaulted no config and has made a change to the master image. i'll restore from backup and try earlier versions of the beta.
 
image within the master changed, image within the project folder didn't change.(looking at date/time)

working as expected with 1.4.0b3

broken with 1.4.0b4
 
i'll stick with 1.4.0b3 for the time being
```
https://community.gns3.com/thread/22821

**Comment by noplay** [comment]
Probably broke by the change:
* Support for modifications to a base Qemu VM (not a linked clone).

The user has report the problem with an old topologie from 1.3

**Comment by grossmj** [comment]
Yep, looks like I have broken something :(

**Comment by grossmj** [comment]
More info: https://community.gns3.com/thread/22821

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-gui/commit/6f0015a678eb396a219f0e2314e609de4f44626c
