### ISSUE TITLE
Host/Cloud VDE not working

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#345]
This used to work in gns3 pre 1.0.  I add a host with the connection to /var/run/vde2_vmnat0.ctl/ctl and a local file /var/run/vde2_vmnat0.ctl/gns3_connection.  However with 1.3.10, when I connect the host item to a switch or router, I get a a message such as:
 
Server error from 127.0.0.1:8000: SW1: unable to bind NIO 'vde-449388ca-6d1b-4cf1-999f-d8b7f8372dc5' to switch 'SW1'
 
I like to use the VDE2 switch for multiple reasons: it allows a normal user to connect without needing to run GNS3 as root, I can connect it easily to other VMs, and I can use the tap interface to bridge or route it to the real network.
 
Is there a workaround to get VDE2 working with GNS3 > 1.0?

After some more digging, I realized that dynamips seems to work correctly when I manually run it in hypervisor mode and execute the commands to create the router instance, create the VDE NIO, and bind the NIO to the router.  Something like this (from memory so commands and order may be wrong)
 
vm create R1 R1 c3725
vm set_ios R1 ...
vm set_con_tcp_port R1 ...
nio create_vde VDE /var/run/vde2_vmnat0.ctl/ctl /var/run/vde2_vmnat0.ctl/dummy
vm slot_add_nio_binding R1 0 0 VDE
vm enable_nio R1 0 0
vm start R1

**Comment by grossmj** [comment]
Not really urgent since not many users use VDE

**Comment by noplay** [comment]
Perhaps since no one complain we could drop it. It will simplify the over complicated cloud.

**Comment by grossmj** [comment]
Maybe this is a quick fix. I will have a pick at it. Otherwise, we may just drop it.

**Comment by grossmj** [comment]
Indeed it was a quick fix... just forgot a yield from ;)
