### ISSUE TITLE
GNS3 not saving config in Alcatel-lucent 7750 SR7 based on QEMU Virtual Machine

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#349]
https://community.gns3.com/ideas/1835

```
Hi,
I have installled GNS3 v1.3.7 in Windows 8.1 (64 bit)
 
i'm using  Alcatel-lucent 7750 VM based on QEMU,
i'm saving my configuration with "admin save" on router  and save project in gns3,
 
problem is that
after i stop the router and start again the router return back the initial configuration
how to solve this issue.
```

**Comment by noplay** [comment]
```
I have been looking into this myself but am relatively new to TiMOS and to qemu but I'm hoping these notes may help others with the same problem.
 
A workaround has been proposed elsewhere.
Basically you copy the Qemu Image from your Images directory to hda_disk.qcow2 in the Quemu project directory.
 
The Qemu wrapper executes qemu with the option
"-hda C:\users\<user>\GNS3\Projects\...\qemu\aa8ba...0d7-b966-9ead2af59786\hda_disk.qcow2"
Alcatel sees this as compact flash 3 which is where it stores its boot code and config file.
 
I'm not a qemu expert but I suspect that the problem arises because the system boots using the image from the image directory and then at some point in the boot process the new hda replaces the original but the new hda is missing some critical files.
 
When you start  qemu it creates a small hda_disk.qcow2 and this is where the configuration is written (this happens as soon as you use "admin save" you can see the configuration appear if you open the file with a text editor).   If you do a soft reboot the config file is read from here.
 
I'm speculating here but If you stop and start qemu it can't use  hda_disk.qcow2  because its missing the boot files so it reverts to the main image and then fails to pick up the config file.
 
The workaround of copying the whole qemu image to the project file does work but seems a bit disk heavy.
 
Right clicking Qemu allows you to specify hdb  hdc and hdd.
I haven't had time to try it yet but I am intending to try setting up hdb with the hope that TiMOS would see it as one of the other Compact Flash cards. I should them be able to set the TiMOS bof  to boot from one file and read the configuration from another.
 
If this works someone simply needs to re-write the wrapper so that this all happens automatically.
```

**Comment by noplay** [comment]
Moved from community:

Hi Paul,
 
In the past I was able to use the QEMU console to save the running image as a snapshot and could save the current configuration of Timos, now there is no option to access the QEMU console prompt. See my one older reply I made about this subject.
 
In Linux and OSX was working but for me is ideal run on Windows because in this laptop I have more memory.
 
I hope they fix it.
 
Regards.

**Comment by noplay** [comment]
Moved from community:

Hi Paul,
 
I configured the hda disk to point to "hda_disk.qcow2" file at folder created for each router in the Node configurator menu. Looks like the save of the configuration is working.
 
Regards

**Comment by noplay** [comment]
Moved from community:

Hi Nilton, I try your method,  
 
 
to point to "hda_disk.qcow2" file at folder created for each router in the Node configurator menu.
 
 
but it is not work, config is not saved after shutdown the router

**Comment by noplay** [comment]
Moved from community:

Have you done "admin save" first?

**Comment by noplay** [comment]
Moved from community:

Yes,  I start the router, change the configuration (for example create interface), save the config (admin save), shutdown router. Then I  to point to "hda_disk.qcow2" (~640 Kb) file at folder created for router, then enable router, but config is new(interface is not exist). I tryed to repeat create interface, admin save, shutdown the router and enable again and the config is not saved again (there are no interface ).
 
 
Please tell what I do wrong?

**Comment by noplay** [comment]
Moved from community:

Hi Alexander, you have to point to hda_disk.qcow2 first, after that when you do "admin save" this will save the configuration. Then you do not need to do anymore changes in the HDD configuration, every "admin save" will work correctly.
 
Regards.

**Comment by noplay** [comment]
Moved from community:


Hi Nilton, I don't  need to change the configuration menu as hda already points to hda_disk.qcow2 in the projects directory. - can you confirm that you have actually stopped and restarted QEMU.
 
What you describe works for me if i  use the command line to reboot within TiMOS but completely stopping QEMU and then restarting it loses the configuration.
 
As is mentioned elsewhere in the forums copying the entire  sros-vm.qcow2 into the project directory as
hda_disk.qcow2 before starting QEMU seems to improve things but I will have to run some more tests before I am satisfied that this is the solution.

**Comment by noplay** [comment]
Moved from community:

Hi Paul,
 
I just did a quick test, I changed the hostname of each router in my topology, four in this case. Then saved the configuration with "admin save". Then closed GNS3. When it says that "A device still running, would like to continue?" I answered yes.
 
After that I called the topology again and started the routers. They returned back with the new name I have configured above.
 
I am running GNS3 1.3.7 and qemu 2.2.0
 
I am pointing in the QEMU configuration the "Disk image(hda)" only, hdb, hdc and hdd are left in blank. In my case:
 
C:/Users/ntobita/GNS3/projects/Topologia SRC/project-files/qemu/e865d192-5d7a-436d-a6f5-20d3384c575d/hda_disk.qcow2
 
Regards

**Comment by noplay** [comment]
Moved from community:

I  do all as you said Nilton but it is not work for me, config is not saved after stop/strat router
 
In my case i point hda to
 
C:/Users/admin/GNS3/projects/TEST SAVE ALU CONF/project-files/qemu/b6a39af6-2260-487b-928c-26d665ba34ab/hda_disk.qcow2
 
start the router, change system name, then stop  router and start router and the system name is not saved

**Comment by noplay** [comment]
Moved from community:

I've been doing some more experimentation - unsuccessfully but thought it might give others some ideas.
 
I added a new 7750 and started it - this creates the hda_disk.qcow2   file in the projects directory
I then stopped the 7750 and copied hda_disk.qcow2  to  hdb_disk.qcow2
I right clicked on the 7750 chose config and added the full path to hdb_disk.qcow2  as hdb
 
I then booted the 7750 again and ran      file dir cf1:
This now holds a copy of cf3.
 
I made some configuration changes and then used           admin save cf1:config.cfg 
I verified that hdb_disk.qcow2 had been changed by using a text editor (read only)
 
I also used                                                                          admin save cf3:config.bak
 
I checked that both files had been created using            file dir cf1:          and     file dir  cf3:
 
I then changed the boot options file using     bof primary-config cf1:config.cfg         and      bof save
I verified that this had updated the boot options file on cf3:    using        file type   cf3:bof.cfg
 
I then stopped and started the 7750
The bof change didnt take effect at boot.
 
I was hoping I  could still use        exec cf1:config.cfg       or       exec  cf3:config.bak
but neither file existed after the boot.
 
I tried    file repair cf1:       and    file repair cf3:        
but the files were not recovered.
 
Is this a problem with the file system not syncing properly when the system is stopped ?
On UNIX i'd be using       sync;sync;haltsys   to make sure the file system is synced before shutdown.
 
*****
It appears that the only working solution is to copy the entire  sros-vm.qcow2 into the project directory as
hda_disk.qcow2 before booting. This was suggested elsewhere in the forum and has worked for me a few times but I haven't tested enough to be sure this is a permanent solution.
If it is, then the QEMU wrapper should be doing the copy whenever a new 7750 is created - although this may not be appropriate for all QEMU hosts.
*****
 
One potential clue can be found in   the small  hda_disk.qcow2  created in the project directory  at boot.
I looked at this in a text editor and found this  (of course it could just be a table of error messages).
 
guid Unable to find requested GPT disk or partition by guid.
label No label specified.
Unable to find requested GPT partition by label.
boot fs Can't find myself on the drive I booted from.
Unparsable drive specification.
Requested disk / partition combination not found.
WARNING: Partitions on floppy devices may not work.
When syslinux is not booted from physical disk (or its emulation),
'boot' and 'fs' are meaningless.
Couldn't read the boot file.
The boot file is too big to load at this address.
The sector cannot be loaded at such high address.
Couldn't read the sector.
Couldn't allocate cmp-buf for option 'save'.
WARNING: The sector won't be mmapped, as it would conflict with the boot file.
Could not build RAW hand-over record!
Could not build GPT hand-over record!
Could not build MBR hand-over record!
WARNING: Handover area won't be prepared,
as it would conflict with the boot file and/or the sector.
Press any key to continue booting... Cannot read system memory map
Booting...
Chainboot failed!
Loader file too large
Out of memory
Service-only run completed, exiting.
........

**Comment by noplay** [comment]
Moved from community:
 had the same problem but I found a way to make it work. At least it works for me.
 
When you do admin save, instead of shutting down the router from GNS3, I go to the QEMU window -> Machine -> Quit and then shut down the router from GNS. When I start the router again and it boots, the config is there. Tested it on 3 different routers in one topology with various configs and it worked every time.
 
It looks like when you directly shut down the router from GNS, QEMU VM is losing data.

**Comment by noplay** [comment]
Moved from community:
Thanks
 
I start my SR QEMU using "-nographic"   so it hadn't occurred to me to try that, I'll disable the option and give it a go when I get some time. It will be annoying if I can't use -nographic but it's certainly a step forward.
 
If you are right it is either a bug in the GNS3 implementation of the Stop button as it applies to QEMU
or QEMU itself does not respond correctly to the signal from GNS3.
 
At least it explains the inconsistent behaviour, others seem to have fixed it in other ways but I have never managed to find a rock solid solution.

**Comment by noplay** [comment]
Moved from community:
In my case I think I found a way to save the configuration. Basically what I do is to  suspend the devices and proceed to save , once the file is saved you can close GNS3 recovering the RAM memory used you were using. Once start to use GNS3 again all devices will appear turn off ( not suspended)  but witn the configuartion now saved. That problem is not only in qemu. I've had the same problem with Raizo and Tiny core using virtual box and I apply the same solution. In fact i found the problem when I started to see the same behaviour in Raizo.

**Comment by noplay** [comment]
@grossmj  I think we solved it with ACPI implementation

**Comment by grossmj** [comment]
This will have to be tested.
