### ISSUE TITLE
[1.3.7/Linux] Cannot locate qemu binary

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#351]
Report by @jean-christophe-manciot

The following error happens while creating a new project or loading existing projects:
"Response error: Error downloading http://127.0.0.1:8000/v1/projects/a01d21c9-3e01-45a8-8b52-1be58837e002/qemu/vms - server replied: Conflict
error while setting up vIOS-1: QEMU binary path is not set or not found in the path
Server error from 127.0.0.1:8000: vIOS-1: QEMU binary path is not set or not found in the path"
 
qemu-system-x86_64 and other qemu binaries  have been moved from /usr/local/bin to /usr/bin, but GNS3:
- does not look for the binaries using PATH environment variable
export PATH="/usr/local/ssl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:  
- does not offer a chance to manually modify the configuration:
![image](https://cloud.githubusercontent.com/assets/345437/11059760/e6635e2a-879b-11e5-8e72-cca2d4b70867.png)

**Comment by noplay** [comment]
Comment by @noplay:
How did you start the server? Because we use the PATH variable in order to locate the qemu binaries via the Python function shutil.which
 
Also do you have the permissions on the qemu binary? Because Python filter non executable files when searching for binaries in PATH.

**Comment by noplay** [comment]
Comment by @jean-christophe-manciot:
I run GNS3 locally as root. That should answer both questions:
 
root@acer-aspire-ubuntu:/# which qemu-system-x86_64
/usr/bin/qemu-system-x86_64
root@acer-aspire-ubuntu:/# env | grep -i path
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
Why have you removed the way to manually configure the location of qemu binaries, especially if they are located outside of the PATH folders (which was not the case in this situation)?
BTW, I don't imply that you should remove an automatic discovery of the binaries.

**Comment by noplay** [comment]
Comment by @noplay:
Core issue with manual path settings is topology portability. Now we try to keep only the binary name in the topology.
 
The server is started via something like upstart or by hand?

**Comment by noplay** [comment]
Comment by @jean-christophe-manciot
Good point!
 
I start GNS3 manually.
BTW, I use Ubuntu 15.04 and systemd has replaced upstart.

**Comment by noplay** [comment]
Hey @jean-christophe-manciot do you still have the issue?

**Comment by jean-christophe-manciot** [comment]
Yes with 1.3.11; as a workaround, I have to put symlinks in /usr/local/bin.

**Comment by noplay** [comment]
Can you check what Python return ?

You can do that by starting a python console and typing:
```python
import shutil
shutil.which("qemu-system-x86_64")
import os
os.environ["PATH"]
```

Sample session on my mac
``` 
➤  python3
Python 3.5.0 (default, Nov  2 2015, 10:40:13)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> shutil.which("qemu-system-x86_64")
'/usr/local/bin/qemu-system-x86_64'
>>> import os
>>> os.environ["PATH"]
'/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
```

Thanks for the help

**Comment by jean-christophe-manciot** [comment]
If I remove the usr/local/bin symlinks, it seems to work :)

sudo python3
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> shutil.which("qemu-system-x86_64")
'/usr/bin/qemu-system-x86_64'
>>> import os
>>> os.environ["PATH"]
'/usr/local/ssl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/actionmystique/Program-Files/Ubuntu/JDK/jdk1.8.0_65/bin:/home/actionmystique/Program-Files/Ubuntu/android-sdk/platform-tools:/home/actionmystique/Program-Files/Ubuntu/Filezilla/bin'

**Comment by noplay** [comment]
Cool
