### ISSUE TITLE
Restrict the list of available Ethernet adapters on a remote server 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#352]
_From @boob4k on May 29, 2015 12:35_

Hello.
I have remote a server. Client side i am using a cloud.
Is it possible to restrict some ports in cloud?
For example at the server side i configure that ports eth0 eth1 eth2 are not accessible and in client side they are deleted from the list.

Thanks

_Copied from original issue: GNS3/gns3-gui#377_

**Comment by noplay** [comment]
At this time it's not possible. It should not be something big to add.

**Comment by noplay** [comment]
_From @boob4k on May 29, 2015 13:5_

Can you add this feature in future releases? Thanks.

**Comment by grossmj** [comment]
Maybe some option in the gns3_server.conf would do it?

For instance ```hidden_ethernet_nios=eth1,eth2,eth3```

**Comment by grossmj** [comment]
Implemented.
