### ISSUE TITLE
Can't remove WIC from slot 0,1,2

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#354]
https://community.gns3.com/ideas/1678

GNS 1.3 rc2
 
When I try to remove WICs from a  3725, the interfaces reside after apply configuration save.
I can change from WIC-2T to WIC-1T, but I can't remove them completely.
 
Florian

**Comment by grossmj** [comment]
Cannot reproduce. I can remove WICs from c3745 and c3725 without issues, even after saving/restoring a topology.
