### ISSUE TITLE
TCP port 2000 is outside the range 2001-7000

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#358]
GNS3 version 1.4.0rc1 on Darwin (64-bit) with Python 3.5.0 Qt 5.5.0.

I have an old project, that uses console port 2000. Starting that gives
```
Server error from http://192.168.1.90:8000: IOU1: TCP port 2000 is outside the range 2001-7000
```

Manually changing the console port to 2001 in the .gns3 file resolves it. A grep shows, that this is the only project with console port 2000, all other start with 2001. I assume the fix https://github.com/GNS3/gns3-server/commit/bd47c21514177fdfef44888f09b478f6f405d5c5 causes that.

Update: This user is also affected: https://community.gns3.com/thread/22938#51156

**Comment by ehlers** [comment]
This project uses a remote server with a minimal gns3_server.conf, besides others console_start_port_range was not defined in this config file. Before change https://github.com/GNS3/gns3-server/commit/bd47c21514177fdfef44888f09b478f6f405d5c5 the default console_start_port_range was 2000, therefore it was used as a console port for projects using this server. With the new minimum start port of 2001 a project using the old port 2000 is rejected.

**Comment by noplay** [comment]
@grossmj do you have a specific reason for increasing to 2001?

**Comment by grossmj** [comment]
The original intend was that R1 = 2001, R2 = 2002 etc.

I think we should not check the range when loading a project.

**Comment by noplay** [comment]
But if we turn off the check and you have only open some port in firewall
you will not get an error.

Otherwise we can start router at R0 :p

Le sam. 14 nov. 2015 00:33, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by qianxideyu** [comment]
Server error from http://192.168.56.101:8000: P1: TCP port 2000 is outside the range 2001-7000，in gns3 default config ,the default port range 2001 to 7000!

**Comment by qianxideyu** [comment]
On windows，GNS3 1.4RC`s vmware,can stop,onlu delete it ,If II click the  stop button ,it will time out 60s!

**Comment by noplay** [comment]
I have sent a PR #370  the idea is to never trust the client for the console port. This should solve a lot of issues if you change the settings of the port range or move a topology to another computer.

**Comment by grossmj** [comment]
Resolved by https://github.com/GNS3/gns3-server/pull/374
