### ISSUE TITLE
on windows ,Gns3 1.4RC can`t stop vmware VM

### ISSUE THREAD

**Issue by qianxideyu** [GNS3/gns3-server#360]
in gns3 1.4RC  of windows platform , after start vmware any vm,,if i click stop buttion ,it will time out 60S !

**Comment by qianxideyu** [comment]
system version is windows 10 enterprise ，software version is vmware workstation  12 pro！

**Comment by noplay** [comment]
Thanks for the report

**Comment by grossmj** [comment]
@qianxideyu can you post the path to one of the .vmx corresponding to one of your VM?

Thanks,

**Comment by grossmj** [comment]
Duplicate of https://github.com/GNS3/gns3-gui/issues/922
