### ISSUE TITLE
IOU nvram export

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#362]
Bug report from Jessica.

So i was trying to save configuration from my IOU switches (regardless of image) when i realized that after a project reopens the configurations are missing. so i tried several different ways to see if there was an error from my side but everything seems to be in order. then looking through GNS3 VM log i see that there was an error from server side which i snap shot for your review so i hope it helps! 
these are upon saving a project:

errors from GNS3 console:

```
Server error from http://192.168.56.101:8000: IOU2: Traceback (most recent call last):   File "/usr/local/lib/python3.4/dist-packages/gns3server/web/route.py", line 179, in control_schema
    yield from func(request, response)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/gns3server/handlers/api/iou_handler.py", line 367, in save_configs
    vm.save_configs()
  File "/usr/local/lib/python3.4/dist-packages/gns3server/modules/iou/iou_vm.py", line 1193, in save_configs
    startup_config_content, private_config_content = self.extract_configs()
  File "/usr/local/lib/python3.4/dist-packages/gns3server/modules/iou/iou_vm.py", line 1180, in extract_configs
    startup_config_content, private_config_content = nvram_export(nvram_content)
NameError: name 'nvram_export' is not defined
```

keep in mind that i saved the configuration to startup-config already but even with out it wont work. 
i was going to report this as an Bug but i couldn't. so hopefully this issue can be addressed

**Comment by noplay** [comment]
Already fixed

**Comment by noplay** [comment]
c2a08a391cd1fe12051748874e3e584ab90ec93c
