### ISSUE TITLE
No Connectivity from Qemu interface to Host interface via Cloud

### ISSUE THREAD

**Issue by keshara** [GNS3/gns3-server#363]
OS: Ubuntu 15.10
GNS3 Ver: 1.4.0 release candidate 1

Topology:
========
Qemu Interface (Cisco ASAv) <-------> Cloud <-------> Bridge Interface on Host

Ping from either direction fails.

**Comment by ehlers** [comment]
When you mean with bridged interface an Ethernet NIO connection, then that's a known limitation of linux and Mac OS X, see fourth topic of this rather old FAQ: http://forum.gns3.net/topic18.html

As that's a limitation in the OS, that can't be changed. Workaround is to use TAP interfaces to connect from GNS3 to linux host, see this thread: https://community.gns3.com/thread/6619

**Comment by keshara** [comment]
Thanks for the info. It saves lot of time on tshooting...
