### ISSUE TITLE
Remote Server Setting won't Save

### ISSUE THREAD

**Issue by keshara** [GNS3/gns3-server#364]
OS: Ubuntu 15.10
GNS3 Ver: 1.4.0 release candidate 1

Even though it allows to set remote-sever config(ip address to use, protocol to use, etc), they won't be saved - when I click 'Ok' and the next time I check it, no previous settings can be found. Because of this I'm unable to access gns3-server which runs on a separate host.

I tried several times, though same results.

**Comment by noplay** [comment]
When you click on ok do you see the server in ~/.config/GNS3/gns3_gui.conf in the remote_servers section?

**Comment by keshara** [comment]
No, I dont see any remote server config under "remote_server" section when i click OK.

**Comment by noplay** [comment]
GNS3 as the permission on the file? You can check it with:
ls -l ~/.config/GNS3/gns3_gui.conf 

Thanks

**Comment by keshara** [comment]
No, it is owned by local user(me).

I check to see whether is there any user or group named GNS3, /etc/passwd or /etc/group, but no such user or group exist.

Then, I make rw- permission for Other on ~/.config/GNS3/gns3_gui.conf, though still remote server setting wont be persistent.

**Comment by noplay** [comment]
Can you start GNS3 with --debug and send to developers@gns3.net the result
to Help / Export debug informations

Thanks for helping

**Comment by keshara** [comment]
Finally, your guide helps to find the cause of the issue.

It was due to the console port range set 2001-7000, by default. When i config my remote server and saves by clicking OK, it seems, gns3 by itself get confuse because tcp port range 2001-7000 overlaps 5900-6000, which is, gns3 assumes, should reserved for VNC, by default.

Feeling glad to support GNS3 community.

**Comment by noplay** [comment]
Thanks for the feedback we will for the port issue
