### ISSUE TITLE
Dynamips 0.2.16 is require but this version doesn't exists

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#369]
https://github.com/GNS3/gns3-server/commit/8031cf10

**Comment by grossmj** [comment]
The Ethertype can only be changed in the dev version of Dynamips. We have not released Dynamips 0.2.16 yet as I would probably like to make some more changes like error messages for instance.

https://github.com/GNS3/dynamips/pull/66

**Comment by grossmj** [comment]
Dynamips 0.2.16 will be shipped in our next release.
