### ISSUE TITLE
GNS3 REST server credentials

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#372]
I would like to access GNS3 server though REST client, but it requires login/pass credentials, though deactivated in the preferences

![REST client](http://hpnouri.free.fr/misc/Selection_342.jpg)

![Server credentials](http://hpnouri.free.fr/misc/Selection_340.jpg)

In case we want to use a protected server, where to set the credentials in the preferences?

######
>GNS3 version is 1.4.0b4 
GNS3 Converter version is 1.2.3
Python version is 3.4.3 (64-bit) with utf-8 encoding
Qt version is 5.2.1
PyQt version is 5.2.1
SIP version is 4.15.5

>Linux gns3-iouvm 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

>Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

**Comment by noplay** [comment]
Hi,

You can found and change the informations in the ~/.config/GNS3/gns3_server.conf 

```
➤  cat ~/.config/GNS3/gns3_server.conf
[Server]
host = 172.16.16.1
port = 8000
auth = True
user = aaaaaaaaa
password = aaaaaaaaa
```
