### ISSUE TITLE
Using several QEMU VM, error: "bind:Address already in use"

### ISSUE THREAD

**Issue by jprietove** [GNS3/gns3-server#376]
Using GNS3 v.1.04rc1 on Linux (64-bit) with Python 3.4.2 Qt 5.3.2.

A Project with 3 QEMU VMs, each with 6 network adapter. After pressing 'Start All devices', sometimes one or several machines don't start with the error 
>bind: Address already in use
>qemu-system-i386: -netdev socket,id=gns3-1,udp=127.0.0.1:10016,localaddr=127.0.0.1:10017: Device 'socket' could not be initialized

Workaround:
I've found a workaround. Stop all devices and then start them one by one. This way, no socket repeated.

**Comment by noplay** [comment]
Are you running multiple instance of GNS3 at the same time?

**Comment by jprietove** [comment]
No. Just one GUI and one Server.

**Comment by noplay** [comment]
Which distribution are you using? 

What is the output of the `uname -a` command?

**Comment by noplay** [comment]
Thanks for the help

**Comment by jprietove** [comment]
Linux jprieto 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

It used to work fine with version 1.04b5 and previous...

**Comment by grossmj** [comment]
Has your Qemu version changed?

**Comment by jprietove** [comment]
Actual version is: QEMU emulator version 2.1.2 (Debian 1:2.1+dfsg-12+deb8u4), Copyright (c) 2003-2008 Fabrice Bellard

It has not been changed since v1.3.11b

**Comment by noplay** [comment]
Perhaps it's related to the fixes for #323

**Comment by noplay** [comment]
And the fact we reuse the ports

**Comment by jprietove** [comment]
Maybe. I've been trying to make a project for reproduce the bug and I can't find a way. It doesn't happens always. In fact, after rebooting the computer, it hasn't happened to me.
The next time the bug appears to me, I will check the ports with ss.

Thanks for your work! I really love GNS3

**Comment by noplay** [comment]
Thanks for the feedback
