### ISSUE TITLE
1.3.11 topology file cannot be read by 1.3.13

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#378]
error while setting up DHCP_Server: TCP port 5002 is outside the range 2001-5000
Server error from 127.0.0.1:8000: DHCP_Server: TCP port 5002 is outside the range 2001-5000

**Comment by jean-christophe-manciot** [comment]
Lab: 
[1.3.11 Lab not read by 1.3.13.zip](https://github.com/GNS3/gns3-server/files/62602/1.3.11.Lab.not.read.by.1.3.13.zip)

**Comment by jean-christophe-manciot** [comment]
It seems that the default port ranges have been changed. 
Isn't it possible to enhance GNS3 in a way that labs built with previous releases always remain compatible?

**Comment by noplay** [comment]
1.4 should fix that by trying to use the asked range or fallback if not
possible.

**Comment by noplay** [comment]
I'm don't think we have change the port range in 1.3

**Comment by jean-christophe-manciot** [comment]
Something has been changed:
- in 1.3.11, a qemu node console port number begins at 5001; you can check TT 3-solutions-linux.gns3 from the lab previously uploaded.
- in 1.3.13, a qemu node console port number begins at 2001, which is fine.
However, it should be possible to use 1.3.11 lab without an error.

**Comment by noplay** [comment]
I look at the code and the range has not change since the 2 february 2015.

But we fixed a bug allowing you to use the port outside the range creating
issues with people with a port range configured in their firewall not
matching the server range.

**Comment by noplay** [comment]
Daniel has shipped a new version

**Comment by jean-christophe-manciot** [comment]
But where? On github, the "compatibility fixes" branch has disappeared and replaced by "1710" which has not been committed by Daniel. And the master branch has not changed.

**Comment by noplay** [comment]
I see the commit here:
https://github.com/dlintott/gns3-converter/commits/master

The new release is 1.2.4

The pull request for 1710 is another issues.
