### ISSUE TITLE
Invalid idlepc value with some image

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#389]
User get this Idle PC value: 0xffffffff806384cc for the image c7200-adventerprisek9-mz.155-2.XB.image

https://gns3.com/discussions/idle-pc-problem-for-ios-15-5

**Comment by grossmj** [comment]
This is a negative number or overflown integer I think. Not much we can do, idle-pc values are provided by Dynamips. However, I have found this value which seem to work: 0x6018c294

**Comment by noplay** [comment]
You will add it to the default values?

**Comment by grossmj** [comment]
I will.
