### ISSUE TITLE
Warn user when using ASA 8

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#395]
I propose to add a warning when user use ASA 8. In order to avoid this:
https://gns3.com/discussions/assistance-with-gns-1-4-and-asa-

ASA 8 is a big hack, not supported by CISCO and Qemu team. This mean the support is random and doesn't depend of us.

**Comment by grossmj** [comment]
We need to understand why they say it works in version 1.3.

ASA 8 is supposed to "work" under Linux.

**Comment by noplay** [comment]
Perhaps Qemu 2.2 work better with ASA.  

But nobody sayed it's work after a rollback.

I never saw it work on my linux VM, perhaps my box it's too slow. Even with old release.
Often it's freeze at: Unpacking initramfs...

If you remove icount and allow KVM it's pass this step but crash later:
https://asciinema.org/a/6i9pt8fbhzybccwmf2fi9qzrf

And the fact it's doesn't work with KVM is a very bad smell for me.

**Comment by noplay** [comment]
Ok I investigate more since it's complaints number one. I got luck when changing icount to different value but it's not stable, it can work but one hour later it's broke.

If I correcly understand when ASA start he try to compute the speed of the CPU. If that failed the value is 0 and a CISCO program will crash later.

You can see that at boot:
```
Fast TSC calibration failed
TSC: Unable to calibrate against PIT
TSC: No reference (HPET/PMTIMER) available
Marking TSC unstable due to could not calculate TSC khz
```

When it's work:
```
Fast TSC calibration failed
TSC: Using PIT calibration value
Detected 1000.0 MHz processor. 
```

But if your emulated processor is too slow you will enter in a race condition during the next step of the boot process.

I have the feeling that this race condition depends if the filesystem has already been formated by a previous boot or not.
