### ISSUE TITLE
Can only use tap interfaces that both already exist and are up

### ISSUE THREAD

**Issue by rcprior** [GNS3/gns3-server#399]
In gns3 1.4.0 running on Linux (Fedora 23), I can only use tap interfaces that already exist and are up. This is regardless of running gns3 as root or as a regular user (in the last case, with proper capabilities assigned to dynamips). If a tap interface does not exist or if it exists but is currently down, gns3 gives me the following error:
"Server error from http://127.0.0.1:8000: R1: TAP interface tap0 is down"

The problem is in file "gns3server/modules/dynamips/_ _ init _ _.py" that tests whether the interface is up *before* attempting to create it (using the NIOTAP() call).

Commenting out lines 461 and 462 in this file makes this problem go away (no idea whether it might cause other problems).

**Comment by noplay** [comment]
Thanks for the report

@grossmj what did you think about this?

**Comment by grossmj** [comment]
Yep, actually I thought I already fixed that issue. Need to patch that.
