### ISSUE TITLE
Error when setting Qemu VM boot to 'cd' (HDD or CD/DVD-ROM)

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#400]
I receive the error below when boot priority is set to HDD or CD/DVD-ROM.

**Output:**
> Server error from http://<ip>:8000: A10 vThunder 4.0.1-1: 'cd' is not one of ['c', 'd']
> 
> Failed validating 'enum' in schema['properties']['boot_priority']:
>     {'description': 'QEMU boot priority', 'enum': ['c', 'd']}
> 
> On instance['boot_priority']:
>     'cd'
> ****** Exception detected, traceback information saved in /home/adosztal/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/share/gns3/gns3-gui/lib/python3.4/site-packages/gns3/qt.py", line 229, in partial
>     return func(*args, **kwargs)
>   File "/usr/share/gns3/gns3-gui/lib/python3.4/site-packages/gns3/http_client.py", line 726, in _processResponse
>     raise e
> gns3.http_client.HttpBadRequest: {
>     "message": "'cd' is not one of ['c', 'd']\n\nFailed validating 'enum' in schema['properties']['boot_priority']:> \n    {'description': 'QEMU boot priority', 'enum': ['c', 'd']}\n\nOn instance['boot_priority']:\n    'cd'",
>     "path": "/v1/projects/{project_id}/qemu/vms",
>     "request": {
>         "acpi_shutdown": false,
>         "adapter_type": "virtio-net-pci",
>         "adapters": 3,
>         "boot_priority": "cd",
>         "cdrom_image": "ACOS_vThunder_4_0_1_214.iso",
>         "cpu_throttling": 0,
>         "cpus": 1,
>         "hda_disk_image": "empty30g.qcow2",
>         "hda_disk_interface": "virtio",
>         "hdb_disk_interface": "ide",
>         "hdc_disk_interface": "ide",
>         "hdd_disk_interface": "ide",
>         "legacy_networking": false,
>         "linked_clone": true,
>         "options": "-nographic",
>         "process_priority": "normal",
>         "ram": 4096
>     },
>     "status": 400
> }

**Versions:**
![gns3 vm-2016-01-20-12-50-05](https://cloud.githubusercontent.com/assets/16632791/12448262/08b99532-bf75-11e5-8c2e-6be63a478e2e.png)

**Comment by noplay** [comment]
It's fixed. You can test the new version by switching to the dev version of 1.4 in the VM.
