### ISSUE TITLE
Check VIX library version

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#413]
The version shouldn't be too old...

**Comment by noplay** [comment]
I think we should put the link for downloading VIX when we show the popup

**Comment by grossmj** [comment]
Looks like there is no easy way to find the VIX library version. Just the vmrun version which I suppose match the library version.

**Comment by grossmj** [comment]
Minimum VIX library version should be 1.13 because we use the ```getGuestIPAddress``` command.

https://www.vmware.com/support/developer/vix-api/VIX-1.13-ReleaseNotes.html
