### ISSUE TITLE
GNS3 1.5 Docker: Running GUI apps.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#415]
Hi Julien,
I am using the following to run GUI apps in docker container using the host xserver:
**`xhost local:root`**
`docker create --privileged -ti -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/snd:/dev/snd -e DISPLAY=unix$DISPLAY --name pc1 ajnouri/dockervpc /bin/bash`

`docker start b3fff6dc86e1 `

`docker attach b3fff6dc86e1`

`root@b3fff6dc86e1:/# qupzilla &`

![qupzilla](https://cloud.githubusercontent.com/assets/1716020/12720911/5fbda3e6-c8fd-11e5-9178-ffc52abe47bb.png)

It would be great to add input for docker create options, maybe something like this:

![docker-gns3](https://cloud.githubusercontent.com/assets/1716020/12720818/e1adf6ae-c8fc-11e5-90ca-945006ab19fe.png)

Or maybe there is another way to allow create options and allow access to xserver?

Thanks.

**Comment by noplay** [comment]
What about allowing users to use VNC? The problem with the socket is most user will not be able to use it because docker run in the GNS3 VM or on a remote server this mean topology are not portable.

I opened an issue about that:
https://github.com/GNS3/gns3-gui/issues/947

**Comment by noplay** [comment]
VNC is the way to go
