### ISSUE TITLE
1.4.1 busted install

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-server#426]
Version 1.4.1 
Error: Server has replied with status code 0 when receiving version number

<img width="1709" alt="screen shot 2016-02-13 at 10 11 52 pm" src="https://cloud.githubusercontent.com/assets/3232190/13027330/d1a25132-d29e-11e5-8cbe-2af3c4c3483c.png">

**Comment by vader75** [comment]
Win 10 Pro, VMWare 12, installed and reinstalled a few times. :-(

**Comment by vader75** [comment]
I removed all the VM interfaces and readied the host only interface, and it seems to be working. Maybe self inflicted issues. Close?

**Comment by noplay** [comment]
Ok thanks for the feedbacks
