### ISSUE TITLE
1.5: Stopping docker VM with active console brings gns3-server process to 100% CPU

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#427]
GNS3 version 1.5.0dev1 on Linux (64-bit) with Python 3.4.2 Qt 5.3.2.

When the docker VM is stopped and a console to this VM is active, the CPU of the gns3-server process goes to 100% load and the console stays active. When I close the console to the docker VM, the CPU goes down to normal.

As a console command I use ```xfce4-terminal --tab -T "%d" -e "telnet %h %p"```, which works fine with all other VM types.

**Comment by ehlers** [comment]
The same issue (100% CPU load) happens when I close the console of a running container. The CPU load goes down to normal, after the VM sends output.

Test 1:
Start command: ```/bin/sh```
Closing the console brings the CPU load of gns3-server to 100%.
Starting another console doesn't change that, but immediately after pressing any key (and the output of the echo) the CPU load drops. The echo of the first character is not shown on the second console.
Stopping of the VM also brings down the CPU load.

Test2:
Start command: ```/bin/sh -c 'while true; do echo Test; sleep 10; done'```
Closing the console brings the CPU load of gns3-server to 100%.
When the next output is sent by the VM (0 - 10sec) the CPU load drops

**Comment by noplay** [comment]
Thanks

**Comment by noplay** [comment]
Fixed

**Comment by ehlers** [comment]
Sorry, but only the second case (closing console of a running docker VM) is fixed.

The initial issue (when you stop a docker VM with an active console the CPU load of gns3-server goes to 100%) is still not fixed.

**Comment by ehlers** [comment]
Works now, well almost. The 100% CPU load issue is gone. But after stopping a running container the console window stays open. Other then that, I'm quite happy with your changes.

Currently in the 1.5 branch the file gns3/version.py looks strange (syntax error in line 28), that has to be fixed.

**Comment by noplay** [comment]
Which console terminal are you using? My terminal never close when the remote end.

**Comment by noplay** [comment]
By the way the syntax is fixed

**Comment by ehlers** [comment]
On OS X I'm using iTERM, that closes when a router/VM (dynamips,IOU in VM, qemu, VMware, VirtualBox) stops. On Linux I tested with XFce4 and Xterm, same results. I'm tested every terminal type with the default GNS3 settings. Only with the docker VM on Linux the console window stays visible, when the container stops.

And on OS X, when I use Terminal, the window stays visible. But that seems specific to Terminal.

**Comment by noplay** [comment]
Good catch

**Comment by ehlers** [comment]
Yes, looks good.
