### ISSUE TITLE
Support for libvirt

### ISSUE THREAD

**Issue by herzcthu** [GNS3/gns3-server#429]
I'm trying to implement qemu + ubuntu MAAS + openstack + gns3 topology.
Almost everything work fine. Except power control from MAAS to qemu guests.
MAAS use libvirt to manage qemu machines. When I try to power on a node from MAAS, gns3 doesn't know that is running and vise versa. 
I would be great if we can use libvirt in gns3. So we can test openstack in gns3 perfectly.

**Comment by noplay** [comment]
Hi,

libvirt is not supported on other operating system. This prevent us to use it otherwise it could have been nice.

If you want to test openstack in GNS3 the good way is to install open stack inside VM in GNS3. Otherwise GNS3 and OpenStack will conflict on the network control.

@grossmj you thought? For me it's a won't fix since we have no plan to use libvirt.

**Comment by grossmj** [comment]
I would keep the idea open because we may support that one day.

**Comment by dagbdagb** [comment]
@grossmj :  Just curious about the current state of the plan w.r.t. libvirt.

**Comment by grossmj** [comment]
Sorry still no plans.

**Comment by dwbfox** [comment]
Any updates on this? Libvirt and by extension QEMU/KVM is open source and has a rich API that can be leveraged. Any specifics as to why it is still not a good idea?

**Comment by noplay** [comment]
It's not working on Windows and Mac is the biggest issue with libvirt for
us.

**Comment by dwbfox** [comment]
The whole idea behind a server is that you offload the compute heavy tasks of virtualization to the server right? So for people who have access to a Linux box, it would be ideal to install the GNS3 client on windows and install the server on libvirt/linux.

**Comment by victorock** [comment]
With clouds supporting nested virtualisation, perhaps this request should move up in the priority stack....
Any news on this?

**Comment by q2dg** [comment]
I think if this issue could be resolved things like this (http://www.brianlinkletter.com/build-a-network-emulator-using-libvirt/) could be a lot simpler
