### ISSUE TITLE
ACPI GNS3 VM shutdown does not work on Mac (OSX El Capitan) with GNS3 1.4.2 exit

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-server#432]
**Setup:**

GNS3 ver. 1.4.2
GNS3 VM version (inline upgraded from 1.4.0) 1.4.2 in VMWare Fusion 8.1.0
Platform MaC OSX El Capitan 10.11.3

**Issues**

- ACPI Shutdown with GNS3 is configured but GNS3 VM stays up upon closing GNS3.
- Fresh start of GNS3 does boot up GNS3 VM

**Comment by noplay** [comment]
Work for me. Do you have fusion normal or professional? The VM has been started by GNS3?

**Comment by vader75** [comment]
<img width="547" alt="screen shot 2016-02-18 at 8 35 36 pm" src="https://cloud.githubusercontent.com/assets/3232190/13139148/332fb9ce-d67f-11e5-9dbf-8c2f98ecff2d.png">

VMWare Fusion Pro 8
Yes its gets started by GNS3 but not closed on exit

**Comment by grossmj** [comment]
GNS3 will call vmrun stop with the soft param to tell the VMware VM to do an ACPI shutdown.

Can you try this on the command line?

```/Applications/VMware Fusion.app/Contents/Library/vmrun stop "/path/to/VM.vmx" soft```

Thanks,

**Comment by vader75** [comment]
Yeah it works from the command line but not from GNS3.
I deleted and downloaded a fresh version of GNS3 VM just in case, still the same.
I have attached the VM log file, just in case it tells you what is going on.
[vmware.txt](https://github.com/GNS3/gns3-server/files/137383/vmware.txt)

**Comment by vader75** [comment]
Something is definitely broken, when going into "IOS on UNIX >> IOU Devices" the Server type for GNS3 VM selection is greyed out...can only nominate IP as remote server to start to get it working.....

See pic, looks like comms problem with taking to GNS3 VM, not sure how to troubleshoot.

<img width="956" alt="screen shot 2016-02-19 at 8 23 05 pm" src="https://cloud.githubusercontent.com/assets/3232190/13171462/2630e7ca-d747-11e5-8be9-47033c30d1a4.png">

:-(

**Comment by noplay** [comment]
It's reported here:
https://github.com/GNS3/gns3-gui/issues/1049

But perhaps it's the same root issue for both problem. Bad detection that the VM is started in some cases.

Can you test this build:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-02-19/1.4/

Thanks for the help

**Comment by vader75** [comment]
GNS3 1.4.3dev1 fixed GNS3 VM detection for me (inc. IOU configuration segment)! Thanks, I guess have to wait until its committed in next release.
