### ISSUE TITLE
Improve version lookup for VMware fusion

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#435]
https://github.com/GNS3/gns3-server/commit/f73b288a2834939e2447f6ed4ae8b77a0011c822#commitcomment-16229492

**Comment by ehlers** [comment]
Just a comment:
`mdfind "kMDItemCFBundleIdentifier == 'com.vmware.fusion'"` can return back more then one line, in case the user manages to install a program more than once. Very unlikely with VMware Fusion, but quite possible with other programs, that you just move from a dmg to the applications folder.
