### ISSUE TITLE
Communication between IOU and VMware doesn't work

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#436]
Andrew reported it on his windows

**Comment by noplay** [comment]
Also
https://www.gns3.com/qa/vmware-workstation-and-winxp-ima

**Comment by noplay** [comment]
https://www.gns3.com/qa/vmware-guest-can-not-communicate

**Comment by noplay** [comment]
I have no way to test it, the only windows where I can test is in a VM and workstation not working inside.

On Mac no problem :(

**Comment by noplay** [comment]
https://gns3.com/qa/gns3-1-4-0-on-esxi-can-t-connect

**Comment by noplay** [comment]
Comment from andrew when tesing communication between two VMware on the same PC:

```
Well, that was an interesting result. From Debian to XP had about 63% loss, and 1548 duplicates sent
from xp to debian had about 45% loss
in wireshark on generic switch, I had about +26K packets in less than 5 minutes
Debian was on vmnet12, XP was on vmnet18.

**Comment by noplay** [comment]
https://github.com/GNS3/gns3-gui/issues/1092 give us another clue of what is wrong.

The generic hub work but not the generic switch.

**Comment by grossmj** [comment]
Fixed. Please see: https://github.com/GNS3/gns3-gui/issues/1092
