### ISSUE TITLE
GNS3 v1.5: Change container terminal prompt to container hostname

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#437]
It would be great to change container terminal prompts to container hostname, rather than the container ID, it will be easier to distinguish terminal.
Like docker command option  **--hostname <hostname>** and maybe **--name <name> ** so in the cli (linux) we can recognize the containers by their name in GNS3

![selection_920](https://cloud.githubusercontent.com/assets/1716020/13257763/652b95b8-da50-11e5-97b4-44eed45d657b.jpg)

Using the last build:

> unzip -l GNS3-1.5.0dev1.source.zip
> Archive:  GNS3-1.5.0dev1.source.zip
>   Length      Date    Time    Name
> 
>   1013203  2016-02-23 00:33   dynamips-0.2.14.zip
>     86796  2016-02-23 00:33   iouyap-0.97.zip
>     47936  2016-02-23 00:33   ubridge-0.9.0.zip
>    153350  2016-02-23 00:33   vpcs-0.6.1.zip
>    514181  2016-02-23 00:33   gns3-server-1.5.2016-02-23.zip
>   6260427  2016-02-23 00:33   gns3-gui-1.5.2016-02-23.zip
> 
>   8075893                     6 files

**Comment by noplay** [comment]
Thanks a small but usefull improvement
