### ISSUE TITLE
GNS3 v1.5: Container contextual menu "configure" doesn't work.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#438]
The following error is logged when try to click on container contextual menu "configure", without further incidence on the working container:

![selection_919](https://cloud.githubusercontent.com/assets/1716020/13258013/935363f2-da51-11e5-9662-aff2d14e847e.jpg)

> 2016-02-23 16:50:01 INFO vm.py:229 ajnouri/dockervpc-1 has stopped
> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/graphics_view.py", line 941, in configureActionSlot
>     self.configureSlot(items)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/graphics_view.py", line 647, in configureSlot
>     node_properties = NodePropertiesDialog(items, self._main_window)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/dialogs/node_properties_dialog.py", line 54, in __init__
>     self._loadNodeItems()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/dialogs/node_properties_dialog.py", line 94, in _loadNodeItems
>     self.showConfigurationPageSlot(item, 0)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/dialogs/node_properties_dialog.py", line 127, in showConfigurationPageSlot
>     page.loadSettings(item.settings(), item.node())
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/modules/docker/pages/docker_vm_configuration_page.py", line 50, in loadSettings
>     self.uiCategoryComboBox.setCurrentIndex(settings["category"])
> KeyError: 'category'
> 
> 2016-02-23 16:50:05 INFO crash_report.py:105 Crash report sent with event ID: 9c286210180a4c9e9dddc8ca089e3287
> 

Using the last build:

> unzip -l GNS3-1.5.0dev1.source.zip
> Archive:  GNS3-1.5.0dev1.source.zip
>   Length      Date    Time    Name
> 
>   1013203  2016-02-23 00:33   dynamips-0.2.14.zip
>     86796  2016-02-23 00:33   iouyap-0.97.zip
>     47936  2016-02-23 00:33   ubridge-0.9.0.zip
>    153350  2016-02-23 00:33   vpcs-0.6.1.zip
>    514181  2016-02-23 00:33   gns3-server-1.5.2016-02-23.zip
>   6260427  2016-02-23 00:33   gns3-gui-1.5.2016-02-23.zip
> 
>   8075893                     6 files

**Comment by noplay** [comment]
Fixed :)
