### ISSUE TITLE
GNS3 v1.5: Cannot open new terminal for a container with new hostname.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#439]
After changing the hostname of a running container, the terminal exit and I cannot open new one.

Need to restart the container to be able to console to it.

> 2016-02-23 17:34:35 DEBUG project.py:374 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 48.4, 'cpu_usage_percent': 6.7}}
> 2016-02-23 17:34:36 INFO telnet_console.py:97 Starting telnet console in thread "gnome-terminal -t "%d" -e "telnet %h %p""
> 2016-02-23 17:34:36 INFO telnet_console.py:82 Telnet console 127.0.0.1:2003 closed
> 2016-02-23 17:34:55 DEBUG project.py:374 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 48.4, 'cpu_usage_percent': 11.1}}
> 2016-02-23 17:34:56 INFO telnet_console.py:97 Starting telnet console in thread "gnome-terminal -t "%d" -e "telnet %h %p""
> 2016-02-23 17:34:56 INFO telnet_console.py:82 Telnet console 127.0.0.1:2003 closed
> 2016-02-23 17:35:10 DEBUG project.py:374 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 48.4, 'cpu_usage_percent': 7.9}}
> 2016-02-23 17:35:11 INFO telnet_console.py:97 Starting telnet console in thread "gnome-terminal -t "%d" -e "telnet %h %p""
> 2016-02-23 17:35:11 INFO telnet_console.py:82 Telnet console 127.0.0.1:2003 closed

Using the last build:

> unzip -l GNS3-1.5.0dev1.source.zip
> Archive:  GNS3-1.5.0dev1.source.zip
>   Length      Date    Time    Name
> 
>   1013203  2016-02-23 00:33   dynamips-0.2.14.zip
>     86796  2016-02-23 00:33   iouyap-0.97.zip
>     47936  2016-02-23 00:33   ubridge-0.9.0.zip
>    153350  2016-02-23 00:33   vpcs-0.6.1.zip
>    514181  2016-02-23 00:33   gns3-server-1.5.2016-02-23.zip
>   6260427  2016-02-23 00:33   gns3-gui-1.5.2016-02-23.zip
> 
>   8075893                     6 files

**Comment by noplay** [comment]
It's fixed the container is restarted after the change.

Please note that changing a settings is equal to destroy and recreate the container in docker. Volumes are not lost but it's a fresh container.
