### ISSUE TITLE
GNS3 v1.5: gns3-veth ip assignment and interference with GNS3 host/VM.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#440]
**Use case:**
Testing infrastructure services in GNS3, ex: deploy a dhcp server container to serve (range 192.168.1.0/24) GNS3 client devices.

**Issue:**
As soon as I configure DHCP container, the related host bridge (gns3-veth2ext below) get assigned an IP from the container, which affects host interfaces set as dhcp clients, beside the fact that it doesn't prevent using an already used subnet, ex: host VMNet interface (vmnet2: 192.168.1.0/24, same as DHCP range).
Which can lead to unintended effects.

In this case the host internet interface get reassigned a new IP/gateway from the docker dhcp server container.

> ajn:~$ route
> Kernel IP routing table
> Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
> default         192.168.1.254   0.0.0.0         UG    0      0        0 gns3-veth0ext

which break Internet connection.

> $ ip a
> ...
> 
> 7: vmnet2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
>     link/ether 00:50:56:c0:00:02 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.1.1/24 brd 192.168.1.255 scope global vmnet2
>        valid_lft forever preferred_lft forever
>     inet6 fe80::250:56ff:fec0:2/64 scope link 
>        valid_lft forever preferred_lft forever
> ...
> 
> 159: gns3-veth2ext: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
>     link/ether ea:11:2c:b5:6a:55 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.1.10/24 brd 192.168.1.255 scope global gns3-veth2ext
>        valid_lft forever preferred_lft forever
>     inet6 fe80::e811:2cff:feb5:6a55/64 scope link 
>        valid_lft forever preferred_lft forever
> ajn:~$ 

This concern GNS3 linux hosts as well as GNS3 VM.

If we could, for example, create gns3-vethxext interfaces without dhcp client, what do you think Julien ? @noplay

**Comment by AJNOURI** [comment]
I could work around it by setting static ip 0.0.0.0/0 to gns3-veth2ext (to which the dhcp server is connected).

**Comment by noplay** [comment]
Will need jeremy to get an advice on this

**Comment by noplay** [comment]
Perhaps a bug similar:
https://github.com/jpetazzo/pipework/issues/72

**Comment by noplay** [comment]
I have change the name of the adapter. 

Now it's :
veth-gns3-ext2

Could you test if it's fix your issue?

**Comment by AJNOURI** [comment]
The below build I am using:

> unzip -l GNS3-1.5.0dev1.source.zip
> Archive:  GNS3-1.5.0dev1.source.zip
>   Length      Date    Time    Name
> ! ---------  ---------- -----   ----
>   1013203  2016-03-01 00:34   dynamips-0.2.14.zip
>     86796  2016-03-01 00:34   iouyap-0.97.zip
>     47936  2016-03-01 00:34   ubridge-0.9.0.zip
>    153350  2016-03-01 00:34   vpcs-0.6.1.zip
>    515631  2016-03-01 00:34   gns3-server-1.5.2016-03-01.zip
>   6261680  2016-03-01 00:34   gns3-gui-1.5.2016-03-01.zip
> ! ---------                     -------
>   8078596                     6 files

doesn't reflect the changes.

![selection_947](https://cloud.githubusercontent.com/assets/1716020/13432679/fa862136-dfce-11e5-9cfd-42d9d8c8c08a.jpg)

It dates earlier that the fix, am I using the right build?

**Comment by AJNOURI** [comment]
Works like a charm, with networkmanager enabled. 

![selection_952](https://cloud.githubusercontent.com/assets/1716020/13437310/da47a326-dfe3-11e5-9c6b-2a566e0e9fab.jpg)

Good job Julien!

**Comment by noplay** [comment]
YES! 

I didn't suspect initially a solution like this.
