### ISSUE TITLE
1.5: Exception on removal of Docker VM

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#441]
Created a new project, then deleted the Docker VM alpine-1
![screenshot](https://cloud.githubusercontent.com/assets/896406/13284764/b5341a0c-daf6-11e5-8265-2acf2707f656.png)

```
Server error : Traceback (most recent call last):
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/web/route.py", line 179, in control_schema
    yield from func(request, response)
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/handlers/api/docker_handler.py", line 252, in delete_nio
    int(request.match_info["adapter_number"]))
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 508, in adapter_remove_nio_binding
    yield from self._delete_ubridge_connection(adapter_number)
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 457, in _delete_ubridge_connection
    yield from self._ubridge_hypervisor.send("bridge delete bridge{name}".format(
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by ehlers** [comment]
To be safe, I updated ubridge to the latest source version 0.9.4. No difference, same exception.

**Comment by AJNOURI** [comment]
@ehlers, @noplay, should we test v1.5 with ubridge 0.9.4 ?

**Comment by AJNOURI** [comment]
Same issue here:

> 2016-02-24 13:37:18 DEBUG vm.py:99 ajnouri/dockervpc-1 is being deleted
> 2016-02-24 13:37:18 INFO link.py:141 deleting link from ajnouri/dockervpc-1 Ethernet0 to IOU1 Ethernet1/0
> 2016-02-24 13:37:18 DEBUG vm.py:294 ajnouri/dockervpc-1 is deleting an NIO
> 2016-02-24 13:37:18 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/5d673230-1c98-4f85-97bb-ac14fb5ab83c/docker/vms/c5bc2219-99a7-415e-9817-c43395a9541c/adapters/0/ports/0/nio {}
> 2016-02-24 13:37:18 DEBUG vm.py:294 IOU1 is deleting an NIO
> 2016-02-24 13:37:18 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/5d673230-1c98-4f85-97bb-ac14fb5ab83c/iou/vms/85aa4ef2-45d8-4a92-9d0c-60e0d4ae2930/adapters/1/ports/0/nio {}
> 2016-02-24 13:37:18 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/5d673230-1c98-4f85-97bb-ac14fb5ab83c/docker/vms/c5bc2219-99a7-415e-9817-c43395a9541c {}
> 2016-02-24 13:37:18 DEBUG http_client.py:689 Decoding response from http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/5d673230-1c98-4f85-97bb-ac14fb5ab83c/iou/vms/85aa4ef2-45d8-4a92-9d0c-60e0d4ae2930/adapters/1/ports/0/nio response 204
> 2016-02-24 13:37:18 DEBUG http_client.py:696 
> 2016-02-24 13:37:18 DEBUG vm.py:315 IOU1 has deleted a NIO: {}
> 2016-02-24 13:37:19 INFO http_client.py:658 Response error: Error downloading http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/5d673230-1c98-4f85-97bb-ac14fb5ab83c/docker/vms/c5bc2219-99a7-415e-9817-c43395a9541c/adapters/0/ports/0/nio - server replied: Internal Server Error (error: 299)
> 2016-02-24 13:37:19 DEBUG http_client.py:681 {
>     "message": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/web/route.py\", line 179, in control_schema\n    yield from func(request, response)\n  File \"/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/handlers/api/docker_handler.py\", line 252, in delete_nio\n    int(request.match_info[\"adapter_number\"]))\n  File \"/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py\", line 507, in adapter_remove_nio_binding\n    yield from self._delete_ubridge_connection(adapter_number)\n  File \"/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py\", line 456, in _delete_ubridge_connection\n    yield from self._ubridge_hypervisor.send(\"bridge delete bridge{name}\".format(\nAttributeError: 'NoneType' object has no attribute 'send'\n",
>     "status": 500
> }
> 2016-02-24 13:37:19 ERROR vm.py:311 Error while deleting NIO ajnouri/dockervpc-1: Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/web/route.py", line 179, in control_schema
>     yield from func(request, response)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/handlers/api/docker_handler.py", line 252, in delete_nio
>     int(request.match_info["adapter_number"]))
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 507, in adapter_remove_nio_binding
>     yield from self._delete_ubridge_connection(adapter_number)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 456, in _delete_ubridge_connection
>     yield from self._ubridge_hypervisor.send("bridge delete bridge{name}".format(
> AttributeError: 'NoneType' object has no attribute 'send'
> 
> 2016-02-24 13:37:19 DEBUG http_client.py:689 Decoding response from http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/5d673230-1c98-4f85-97bb-ac14fb5ab83c/docker/vms/c5bc2219-99a7-415e-9817-c43395a9541c response 204
> 2016-02-24 13:37:19 DEBUG http_client.py:696 
> 2016-02-24 13:37:19 INFO vm.py:119 ajnouri/dockervpc-1 has been deleted

Doesn't seem to affect the lab.

**Comment by noplay** [comment]
Yes you need the last ubridge I will investigate this

**Comment by noplay** [comment]
Strange I don't reproduce it with VPCS but with IOU it's the case

**Comment by noplay** [comment]
Fixed
