### ISSUE TITLE
GNS3 v1.5: Wireshark doesn't close after "stop capture" of a container link.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#443]
Wireshark doesn't close after "stop capture" of a container link, including when the issue #442 occurs.

![selection_926](https://cloud.githubusercontent.com/assets/1716020/13285125/272bacfe-daf9-11e5-9189-0ff592bd4e6a.jpg)

Though all captured link context menus show
![selection_925](https://cloud.githubusercontent.com/assets/1716020/13285133/3c93d47c-daf9-11e5-8eca-9286c69981e1.jpg)

Need to kill the wireshark processes manually

The log doesn't show errors:

> 2016-02-24 13:23:02 INFO packet_capture.py:62 IOU1 has successfully started capturing packets on Ethernet0/1
> 2016-02-24 13:23:20 DEBUG project.py:374 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 54.3, 'cpu_usage_percent': 20.8}}
> 2016-02-24 13:23:22 DEBUG vm.py:391 IOU1 is stopping a packet capture on Ethernet0/1
> 2016-02-24 13:23:22 DEBUG http_client.py:566 POST http://127.0.0.1:8000/v1/projects/5d673230-1c98-4f85-97bb-ac14fb5ab83c/iou/vms/85aa4ef2-45d8-4a92-9d0c-60e0d4ae2930/adapters/0/ports/1/stop_capture {}
> 2016-02-24 13:23:22 DEBUG http_client.py:689 Decoding response from http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/5d673230-1c98-4f85-97bb-ac14fb5ab83c/iou/vms/85aa4ef2-45d8-4a92-9d0c-60e0d4ae2930/adapters/0/ports/1/stop_capture response 204
> 2016-02-24 13:23:22 DEBUG http_client.py:696

**Comment by noplay** [comment]
It's a problem? Seem good to me to not closing Wireshark if you want to inspect the capture.

**Comment by AJNOURI** [comment]
Not really a problem. I implied so because that wasn't the case with previous version.
I am ok with that.

**Comment by noplay** [comment]
Ok I will look
