### ISSUE TITLE
GNS3 v1.5: init.sh doesn't execute the parameters.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#452]
Looks like  **exec "$@"**  in init.sh doesn't execute the script parameters.

I see this with containers that should execute a process when running:
ex: Openvswitch container runs **/usr/bin/supervisord**

> CMD ["/usr/bin/supervisord"]

When I run the container in GNS3, _docker ps_ shows the "/gns3/init.sh /bin/b" as the command running.
![selection_963](https://cloud.githubusercontent.com/assets/1716020/13646139/642a2640-e62e-11e5-9eca-6f8604e070ad.jpg)

And the container hanging its execution
![image](https://cloud.githubusercontent.com/assets/1716020/13646135/5e89b89a-e62e-11e5-98a9-5da3a5ee8e3f.png)

**Comment by noplay** [comment]
I don't know if docker ps output is accurate or truncated

**Comment by ehlers** [comment]
The docker ps output is truncated, use --no-trunc for non-truncated output.

Example: `docker run -ti alpine echo this is a long command`

```
# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                          PORTS               NAMES
c8228a4385dc        alpine              "echo this is a long "   About a minute ago   Exited (0) About a minute ago                       amazing_williams
# docker ps -a --no-trunc
CONTAINER ID                                                       IMAGE               COMMAND                         CREATED              STATUS                          PORTS               NAMES
c8228a4385dcf17488d86896ca2e874f72178140ff585b4d7b18d4754c086823   alpine              "echo this is a long command"   About a minute ago   Exited (0) About a minute ago                       amazing_williams
```

**Comment by AJNOURI** [comment]
Hi, sorry for the late reply. 
I thought the command displays only the last running script (/usr/bin/supervisord) 
showing the init script with its argument mislead me, my bad.
In fact, I used the wrong shell as a start command  **/bin/bash** instead of **/bin/sh**
Now works fine. Thanks guys.

To finish with this ovs container, socketplane/openvswitch requires to run with **--cap-add NET_ADMIN**  to allow to control networking capabilities. How can I add such option?
Outside of GNS3:
`docker run -it --cap-add NET_ADMIN socketplane/openvswitch /bin/sh`

**Comment by noplay** [comment]
For OVS you have this container:
https://hub.docker.com/r/gns3/openvswitch/

The container from socketplane interact with the host OS I don't think it's a good idea.

**Comment by AJNOURI** [comment]
Thanks a lot.
