### ISSUE TITLE
What is the procedure to patch the GNS3 kernel with this http://lists.linuxfoundation.org/pipermail/bridge/2015-January/009291.html

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#455]
Hi guys

I have tried to reuse the kernel already compiled for GNS3 but with that kernel my vIOS L2 machines won't boot up.
The patch is described here: http://lists.linuxfoundation.org/pipermail/bridge/2015-January/009291.html

This adds some L2 transparency to the Linux bridge witch normally eats the frames for LLDP or CPD or any other non standard 802.1d L2 multicast addresses which blocks some L2 network protocols

With this patch the bridge becomes a tap.

**Comment by grossmj** [comment]
Hum... we don't use Linux bridges to connect VMs.

**Comment by noplay** [comment]
We didn't recompile a kernel.  And for supporting multiple distribution and the ability to install GNS3 on various provider we will avoid this solution.

**Comment by ehlers** [comment]
Even when it's a bit late for a comment:

@1001QAdotNET have you read the comment from one of the kernel developers (Stephen Hemming) about this patch:
> I am ok with forwarding LLDP because some people need it.
> But allowing forwarding STP or PAUSE frames is bad.
> 
> We don't let people do things that break networks. Other examples
> already exist like set all 0 ethernet addresses, or the restrictions
> on allowing net 127 in IP addresses.

So even when you need to use linux bridges, you should be extremely careful using this patch.

**Comment by 1001QAdotNET** [comment]
Yes I did and the comment sounded like a Nazi soup replica (See Seinfeld)
If you ask me that is a very nice way to solve a problem. Rigidly sticking with "the standard" never improved the things or led to progress

The truth is that we need a virtual patch cord with tap capabilities and that is a very nice way to do it. The developer that wrote the patch was clear, you can adjust the mask used for filtering MAC addresses as you like, so what is wrong here ??


the tc package has tons of features that if used improperly would do a lot more damage than the above.


BTW, the veth (virtual tap) already exists but connecting a Qemu machine to from GNS3 failed. Not to mention that sniffing the traffic on that connection is probably not going to work

As far as I can see UNL works fine with that patch for the kernel.
As long as you know what you are doing you will not break anything

**Comment by noplay** [comment]
We have a differences of philosophy with UNL. GNS3 run on top of on existing OS not on a modified one. This is important to allow people to deploy in various situations.

For example we have people installing GNS3 on host on top of Xen where the user need a special kernel. UNL is know to not working on baremetal AMD processor.

And also for security not shipping a custom kernel is better, we are not responsible for fast release of new kernel build in case of problems.

We will probably not using bridge for connecting stuff, we will study openvswitch has a network backend.

**Comment by 1001QAdotNET** [comment]
What good is it if GNS3 works on AMD and you can  not sniff Qemu traffic ?

**Comment by grossmj** [comment]
Openvswitch will allow us to sniff however in the meantime you can use an simple Ethernet switch between 2 Qemu VMs and sniff from the switch side.

**Comment by 1001QAdotNET** [comment]
Last time when I played with that switch it was buggy and unstable

**Comment by grossmj** [comment]
We have been working on that problem lately, what bug did you get?

**Comment by 1001QAdotNET** [comment]
It was a while ago. Some problems with vlans and later CDP, LLDP etc etc.
