### ISSUE TITLE
Are there any limitation that would prevent qemu2.5 used by GNS3 to work with Linux Kernel 3.16.7 ?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#456]
I am testing a kernel patched by Andrea (UNL) and I work on AMD processors
The only entry in the Qemu 2.5 change log that I could find referring to my issues is this:

> **x86**
> The emulated IOMMU (VT-d) supports devices behind a bridge

When I try to run vIOSl2 on UNL on my AMD server it fails (same if I use Andrea's kernel 3.16 with GNS3)
When I try to run vIOSl2 on GNS3 on my AMD server if works

What exactly makes the difference (the GNS3 kernel seems to be better for AMD but it lacks the patch that I posted about in my other request)

**Comment by grossmj** [comment]
Maybe because the GNS3 VM is based on Ubuntu? We haven't done anything in regard to AMD vs Intel.

**Comment by noplay** [comment]
We use the standard ubuntu server kernel.
