### ISSUE TITLE
Change default server port?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#457]
Actually the default port is 8000 but it seem we collision with various application. (HTTP proxy, web radio, various web application) and is  aggressively protected by antivirus.
http://www.speedguide.net/port.php?port=8000

Perhaps we should change it and use something less noisy.

Proposal:
* 8033 http://www.speedguide.net/port.php?port=8033
* 3030 http://www.speedguide.net/port.php?port=3030
* 3003 http://www.speedguide.net/port.php?port=3003 (Not trojan known on this port :P)

Other idea I reject:
* 3333 is use by various games
* 8333 is use by bitcoin

**Comment by AJNOURI** [comment]
Indeed, 3003 looks nice with no malicious activities.

**Comment by gcasella** [comment]
Looks like 3080-3090 are pretty quiet.
Seems like  a good range to use for any other future gns3 services that would need it. 

Checking out some other ones as we speak as well.

**Comment by grossmj** [comment]
I would vote for 3080 so we can use the rest of the range if we need to someday.

However, we need to change our default TCP range for consoles which is currently 2000-7000 by default. I think we can move that to 5000-10000
