### ISSUE TITLE
Remote install on  baremetal: Issue running IOU

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#465]
GNS3 GUI error:

> Server error from http://172.16.253.1:8000: IOU2: Could not start IOU: [Errno 2] No such file or directory: '/opt/gns3/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-15.4.1T.bin': 32-bit binary support is probably not installed

Tried installing gns3-iou

> root@gns3-iouvm:~# sudo apt-get install gns3-iou
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  gns3-iou : Depends: libssl1.0.0:i386 but it is not installable
> E: Unable to correct problems, you have held broken packages.

Though the server supports multiarch:

> root@gns3-iouvm:~# dpkg --print-architecture
> amd64
> root@gns3-iouvm:~# dpkg --print-foreign-architectures
> i386
>

**Comment by noplay** [comment]
It's an ubuntu 14.04?

**Comment by AJNOURI** [comment]
Yes.

> root@gns3server:~# uname -a
> Linux gns3server.local.lan 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> root@gns3server:~# 
> root@gns3server:~# lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 14.04.4 LTS
> Release:	14.04
> Codename:	trusty
>

**Comment by noplay** [comment]
Just tested and it seem broken you are right

**Comment by noplay** [comment]
Documentation fixed. After adding the architecture you need to do an apt-get update
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install gns3-iou
