### ISSUE TITLE
Run udhcp in background

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#469]
From @ehlers:
Currently the busybox ifupdown gives up getting a lease after 5 tries. It's the option -n of udhcpc, which is responsible for that. When using -b instead, it should continue to try to get a lease in the background (according to the documentation, I haven't tried).

To change that in the config file of the busybox build
CONFIG_IFUPDOWN_UDHCPC_CMD_OPTIONS="-R -n"
should be replaced by
CONFIG_IFUPDOWN_UDHCPC_CMD_OPTIONS="-R -b"

**Comment by noplay** [comment]
I designed a container for testing that ;)

**Comment by noplay** [comment]
https://github.com/GNS3/gns3-registry/pull/104

**Comment by ehlers** [comment]
I tested it with a IOS router (3725):
```
no ip dhcp conflict logging
ip dhcp excluded-address 10.1.1.0 10.1.1.127
!
ip dhcp pool DHCP_POOL
   network 10.1.1.0 255.255.255.0
   default-router 10.1.1.1
   dns-server 8.8.8.8 8.8.4.4
   domain-name lan
   lease 0 1
!
```

**Comment by ehlers** [comment]
But your container is a good base for a more complex DHCP configuration.

**Comment by noplay** [comment]
I finally found the correct settings.
