### ISSUE TITLE
Improve docker aux console

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#472]
That's something for 2.0

Currently the docker aux console is a pipe to a docker-exec command. That is quite good, but it lacks the advanced tty attributes. For example Ctrl-C doesn't work. Would be nice, if that can be changed to a full TTY connection.

Two ideas, completely untested:
- use pty's (pseudo ttys) to connect to the docker exec, see https://docs.python.org/3.4/library/pty.html
- use the API docker-exec-create, then docker-exec-start. After the HTTP/JSON exchange on docker-exec-start the raw tty data is exchanged (when tty=true). That must somehow connected to a telnet daemon.

**Comment by noplay** [comment]
I agree it could be nice to fix that.

When I have look for solutions.

The pty module fork, it's not really compatible with our asyncio stuff.

The problem with the docker exec create API is we can't get a websocket stream. We have only their strange HTTP stream. I have taken a look to the docker source code it doesn't seem trivial to change.


I don't exactly remember how pty work but the code from python doesn't seem very complicate:
https://github.com/python/cpython/blob/1fe0fd9feb6a4472a9a1b186502eb9c0b2366326/Lib/pty.py

It should be possible to rewrite it using asyncio primitive

**Comment by noplay** [comment]
I will commit something tomorrow. But mysteriously I need to use this regex to have a clean display on the client:
```python
data = re.sub(b'\x1B\[\[[0-9]+;5R', b'', data)
```

I suspect that this is a vt100 code or something like that. But no idea of what is the purpose

**Comment by noplay** [comment]
It was for moving the cursor after the prompt (5 characters)
```python
data = re.sub(b'\x1B\[\[[0-9]+;[0-9]+R', b'', data)
```

**Comment by noplay** [comment]
I found a ninja way using the script command

**Comment by ehlers** [comment]
Your ninja way to use the script command is genius, the aux console is perfect now.

**Comment by noplay** [comment]
Take a look on the code for HTTP support the same ninja trick but using
netcat :P
