### ISSUE TITLE
No traffic between IOU-L2 or vIOS-L2 and ASAv

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-server#473]
I have setup a small topology with 2 nodes vIOS-L2 and ASAv connected on Gi0/0 on both sides and setup vlans and subinterfaces. When I try to ping from each side there no response. Also if I replace vIOS-L2 with IOU-L2 or standard switch result is the same. I have tested this setup on Unetlab 1.0 and it works fine.

I'm using GNS3 1.5 dev version. Also I thought it might be a Qemu issue but I have tried 3 different versions 2.4, 2.5, and git with same result. I have attached the screenshot of the topology.

![screenshot](https://cloud.githubusercontent.com/assets/7124193/14182671/0da74412-f775-11e5-8340-e81d9d9ff655.png)

**Comment by noplay** [comment]
On which OS are you?

**Comment by cioby23** [comment]
I'm running Linux specifically ArchLinux. As for images I used the latest available ASAv 9.5.2-204 and IOSv-L2 15.2.4055.

**Comment by noplay** [comment]
Multiple possibilities. 

It's possible that something is missing in your qemu installation. 

Can you test with this image:
https://sourceforge.net/projects/gns-3/files/Qemu%20Appliances/linux-microcore-6.4.img/download

And see if you can ping two instance across a switch.

If it's work it could be a problem related to the KVM support of your Arch installation (I suspect something related to virtio driver). 

I installed a arch a few day ago. I should be able to test after the week end.

**Comment by cioby23** [comment]
Indeed it seems it was an issue with the virtio driver used by ASAv. As soon as I changed the driver to e1000 everything started to work. Thanks for your suggestion.
