### ISSUE TITLE
Remote server (public hosting): Server error Project ID  doesn't exist

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#474]
After rebooting the remote server (rackspace), the client cannot find the project ID anymore

![selection_069](https://cloud.githubusercontent.com/assets/1716020/14185477/51d764aa-f77a-11e5-9199-8a87c3532f28.png)

and each time I have to create a new project exclusively for the running server session.

**Comment by noplay** [comment]
If you close the topology on the client and reopen it the project will be available again.

Data of VM is persists on disk but not the list of projects and project are not reopened at server startup to avoid to use ressources. It's by design only the client actually has all the meta data.
