### ISSUE TITLE
DTP frames incorrectly handled ?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#475]
By accident I run into what seems to be a bug
Create a config with three switches daisy chained, no configs whatsoever, just as you created them.
Start all of them and capture the traffic at the most to the left or to the right port , like in the picture
You will see DTP frames originated by one switch making it all the way to the other end when they should be consumed by the middle switch

https://i.imgur.com/nTVvGT7.png

**Comment by noplay** [comment]
What run on the switches?

**Comment by 1001QAdotNET** [comment]
I tried both, IOU and vIOS, latest versions , it seem to be a server related issue

**Comment by noplay** [comment]
When using the vIOS it's direct connection between qemu emulator via UDP tunnel. This mean when sending a packet from SW1 to SW3 the packet is forwarded by the SW2 OS. It's not possible for a packet to leak from a link to another. It's possible that your cisco images missed that features.

Seem some images are buggy:
http://community.dev-innovate.com/t/bugs-associated-with-native-vlan-and-vlan1/6168

**Comment by 1001QAdotNET** [comment]
It does not happen on Unetlab

**Comment by grossmj** [comment]
Unetlab uses Linux bridges... they may filter out the DTP frames.

**Comment by 1001QAdotNET** [comment]
Then that would be equally blocked between SW1-SW2 and the packets will not reach SW3 either.

**Comment by grossmj** [comment]
I don't think there is anything to fix there. As Julien told we use UDP tunnels, what goes out of a source interface goes to a destination interface, no filtering, pretty simple. We don't control what is going on inside a VM.

**Comment by 1001QAdotNET** [comment]
ok, I already passed this section of my studies. If you do not think it is bug then close it and don't check it. Might be Cisco as you suggested.

**Comment by noplay** [comment]
It's interesting that unetlab doesn't have the same behavior. A proof that
 bridge could make subtle modifications to the packet with uncommon
protocol.
