### ISSUE TITLE
GNS3 v1.5:  network config editor "OSError: [Errno 98] Address already in use"

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#480]
Happens when trying to change network configuration of a running container:

> => Server error from http://127.0.0.1:8000: ajnouri/alpine-haproxy-1: Traceback (most recent call last):
>   File "/usr/lib/python3.4/asyncio/base_events.py", line 823, in create_server
>     sock.bind(sa)
> OSError: [Errno 98] Address already in use
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/web/route.py", line 179, in control_schema
>     yield from func(request, response)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/handlers/api/docker_handler.py", line 282, in update
>     yield from vm.update()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 278, in update
>     yield from self.start()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 309, in start
>     yield from self._start_console()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 372, in _start_console
>     self._telnet_servers.append((yield from asyncio.start_server(telnet.run, self._manager.port_manager.console_host, self.console)))
>   File "/usr/lib/python3.4/asyncio/streams.py", line 101, in start_server
>     return (yield from loop.create_server(factory, host, port, **kwds))
>   File "/usr/lib/python3.4/asyncio/base_events.py", line 827, in create_server
>     % (sa, err.strerror.lower()))
> OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 2006): address already in use
>

**Comment by AJNOURI** [comment]
Actually it happens when I modify any of the the parameters name, start command or networking configuration.

**Comment by noplay** [comment]
Do you still have the error with last source code version?

**Comment by noplay** [comment]
I just got it with the aux port:
```
Traceback (most recent call last):
  File "/gns3-server/gns3server/web/route.py", line 179, in control_schema
    yield from func(request, response)
  File "/gns3-server/gns3server/handlers/api/docker_handler.py", line 286, in update
    yield from vm.update()
  File "/gns3-server/gns3server/modules/docker/docker_vm.py", line 293, in update
    yield from self.start()
  File "/gns3-server/gns3server/modules/docker/docker_vm.py", line 327, in start
    yield from self._start_aux()
  File "/gns3-server/gns3server/modules/docker/docker_vm.py", line 346, in _start_aux
    self._telnet_servers.append((yield from asyncio.start_server(server.run, self._manager.port_manager.console_host, self.aux)))
  File "/usr/lib/python3.4/asyncio/streams.py", line 101, in start_server
    return (yield from loop.create_server(factory, host, port, **kwds))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 827, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 6000): address already in use

**Comment by AJNOURI** [comment]
I am using 

> Archive:  GNS3-1.5.0dev1.source.zip
>   Length      Date    Time    Name
> #---------  ---------- -----   ----
>   1005126  2016-04-07 00:35   dynamips-0.2.16.zip
>     86796  2016-04-07 00:35   iouyap-0.97.zip
>     76997  2016-04-07 00:35   ubridge-0.9.4.zip
>    153350  2016-04-07 00:35   vpcs-0.6.1.zip
>   1098856  2016-04-07 00:35   gns3-server-1.5.2016-04-07.zip
>   6294839  2016-04-07 00:35   gns3-gui-1.5.2016-04-07.zip
> #---------                     -------
>   8715964                     6 files

Still experiencing the same errors, though not systematically

[http://hpnouri.free.fr/misc/2016-04-07%2015:47:54%20DEBUG%20project](http://hpnouri.free.fr/misc/2016-04-07%2015:47:54%20DEBUG%20project)

With this version I get this when invoking the aux port for a container:
![selection_978](https://cloud.githubusercontent.com/assets/1716020/14353633/2118aa76-fcda-11e5-835e-01d65254fb18.jpg)

**Comment by noplay** [comment]
Seem to be fixed

**Comment by AJNOURI** [comment]
Hi Julien, sorry it persist here. 
This is the just cloned 1.5 branch

> 2016-04-08 15:54:29 INFO hypervisor.py:154 ubridge started PID=22783
> 2016-04-08 15:54:29 INFO base_vm.py:425 Hypervisor 127.0.0.1:47794 has successfully started
> 2016-04-08 15:54:29 INFO ubridge_hypervisor.py:84 Connected to uBridge hypervisor after 0.0162 seconds
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:208 sending hypervisor version
> 
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:263 returned result ['0.9.4']
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:208 sending docker create_veth veth-gns3-ext8 veth-gns3-int8
> 
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:263 returned result ['veth pair created: veth-gns3-ext8 and veth-gns3-int8']
> 2016-04-08 15:54:29 DEBUG docker_vm.py:540 Move container ajnouri/dockervpc-1 adapter veth-gns3-int8 to namespace 22769
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:208 sending docker move_to_ns veth-gns3-int8 22769 eth0
> 
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:263 returned result ['veth-gns3-int8 moved to namespace 22769']
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:208 sending docker create_veth veth-gns3-ext9 veth-gns3-int9
> 
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:263 returned result ['veth pair created: veth-gns3-ext9 and veth-gns3-int9']
> 2016-04-08 15:54:29 DEBUG docker_vm.py:540 Move container ajnouri/dockervpc-1 adapter veth-gns3-int9 to namespace 22769
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:208 sending docker move_to_ns veth-gns3-int9 22769 eth1
> 
> 2016-04-08 15:54:29 DEBUG ubridge_hypervisor.py:263 returned result ['veth-gns3-int9 moved to namespace 22769']
> 2016-04-08 15:54:29 ERROR route.py:209 Uncaught exception detected: <class 'OSError'>
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/asyncio/base_events.py", line 823, in create_server
>     sock.bind(sa)
> OSError: [Errno 98] Address already in use
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/web/route.py", line 179, in control_schema
>     yield from func(request, response)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/handlers/api/docker_handler.py", line 286, in update
>     yield from vm.update()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 293, in update
>     yield from self.start()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 324, in start
>     yield from self._start_console()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 387, in _start_console
>     self._telnet_servers.append((yield from asyncio.start_server(telnet.run, self._manager.port_manager.console_host, self.console)))
>   File "/usr/lib/python3.4/asyncio/streams.py", line 101, in start_server
>     return (yield from loop.create_server(factory, host, port, **kwds))
>   File "/usr/lib/python3.4/asyncio/base_events.py", line 827, in create_server
>     % (sa, err.strerror.lower()))
> OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 2005): address already in use
> 2016-04-08 15:54:29 WARNING crash_report.py:78 A .git directory exist crash report is turn off for developers
> 2016-04-08 15:54:29 INFO response.py:48 PUT /v1/projects/85ac2627-8984-463f-bfa9-7053e2c95bce/docker/vms/c765abb5-e9ed-4d17-8543-46f7bb6fd4df
> 2016-04-08 15:54:29 DEBUG response.py:49 {'USER-AGENT': 'GNS3 QT Client v1.5.0dev1', 'HOST': '127.0.0.1:8000', 'ACCEPT-ENCODING': 'gzip, deflate', 'CONNECTION': 'Keep-Alive', 'ACCEPT-LANGUAGE': 'en-US,*', 'CONTENT-TYPE': 'application/json', 'AUTHORIZATION': 'Basic VGhzd2Z1MEhzdGYweEluUmZXZUh2cFZKNDR4ZU5PZWlEZ3N3bVFrYWFIZ09jRjcybHptZ3RDZVhrdHlneHhkVDpKRzY5WHlxbFJydmx1WUZoYWRzTE9mTWQ0V0lOYm9VTHVQcGpkOWZscXFucnZFd0tkQml5c0c0REhhcEZyZkVO', 'CONTENT-LENGTH': '2'}
> 2016-04-08 15:54:29 DEBUG response.py:51 {}
> 2016-04-08 15:54:29 INFO response.py:52 Response: 500 Internal Server Error
> 2016-04-08 15:54:29 DEBUG response.py:53 {'ACCESS-CONTROL-ALLOW-ORIGIN': '*', 'X-ROUTE': '/v1/projects/{project_id}/docker/vms/{vm_id}', 'CONTENT-LENGTH': '1692', 'CONTENT-TYPE': 'application/json', 'SERVER': 'Python/3.4 GNS3/1.5.0dev1'}
> 2016-04-08 15:54:29 DEBUG response.py:55 {'message': 'Traceback (most recent call last):\n  File "/usr/lib/python3.4/asyncio/base_events.py", line 823, in create_server\n    sock.bind(sa)\nOSError: [Errno 98] Address already in use\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/web/route.py", line 179, in control_schema\n    yield from func(request, response)\n  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/handlers/api/docker_handler.py", line 286, in update\n    yield from vm.update()\n  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 293, in update\n    yield from self.start()\n  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 324, in start\n    yield from self._start_console()\n  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 387, in _start_console\n    self._telnet_servers.append((yield from asyncio.start_server(telnet.run, self._manager.port_manager.console_host, self.console)))\n  File "/usr/lib/python3.4/asyncio/streams.py", line 101, in start_server\n    return (yield from loop.create_server(factory, host, port, **kwds))\n  File "/usr/lib/python3.4/asyncio/base_events.py", line 827, in create_server\n    % (sa, err.strerror.lower()))\nOSError: [Errno 98] error while attempting to bind on address (\'127.0.0.1\', 2005): address already in use\n', 'status': 500}
> 2016-04-08 15:54:29 INFO http_client.py:677 Response error: Error downloading http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/85ac2627-8984-463f-bfa9-7053e2c95bce/docker/vms/c765abb5-e9ed-4d17-8543-46f7bb6fd4df - server replied: Internal Server Error (error: 299)
> 2016-04-08 15:54:29 ERROR docker_vm.py:134 error while deleting ajnouri/dockervpc-1: Traceback (most recent call last):
>   File "/usr/lib/python3.4/asyncio/base_events.py", line 823, in create_server
>     sock.bind(sa)
> OSError: [Errno 98] Address already in use
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/web/route.py", line 179, in control_schema
>     yield from func(request, response)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/handlers/api/docker_handler.py", line 286, in update
>     yield from vm.update()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 293, in update
>     yield from self.start()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 324, in start
>     yield from self._start_console()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/docker_vm.py", line 387, in _start_console
>     self._telnet_servers.append((yield from asyncio.start_server(telnet.run, self._manager.port_manager.console_host, self.console)))
>   File "/usr/lib/python3.4/asyncio/streams.py", line 101, in start_server
>     return (yield from loop.create_server(factory, host, port, **kwds))
>   File "/usr/lib/python3.4/asyncio/base_events.py", line 827, in create_server
>     % (sa, err.strerror.lower()))
> OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 2005): address already in use
>

**Comment by noplay** [comment]
Are you using SE linux or something like that?

**Comment by AJNOURI** [comment]
You hit the nail over the head there!
Indeed Julien, I was playing with apparmor in the wrong console...

> sudo apparmor_status
> apparmor module is loaded.
> 23 profiles are loaded.
> 23 profiles are in enforce mode.
>    /sbin/dhclient
>    /usr/bin/evince
>    /usr/bin/evince-previewer
>    /usr/bin/evince-previewer//sanitized_helper
>    /usr/bin/evince-thumbnailer
>    /usr/bin/evince-thumbnailer//sanitized_helper
>    /usr/bin/evince//sanitized_helper
>    /usr/bin/lxc-start
>    /usr/lib/NetworkManager/nm-dhcp-client.action
>    /usr/lib/connman/scripts/dhclient-script
>    /usr/lib/cups/backend/cups-pdf
>    /usr/lib/libvirt/virt-aa-helper
>    /usr/lib/lightdm/lightdm-guest-session
>    /usr/lib/lightdm/lightdm-guest-session//chromium
>    /usr/sbin/cupsd
>    /usr/sbin/libvirtd
>    /usr/sbin/ntpd
>    /usr/sbin/tcpdump
>    docker-default
>    lxc-container-default
>    lxc-container-default-with-mounting
>    lxc-container-default-with-nesting
>    system_tor
> 0 profiles are in complain mode.
> 2 processes have profiles defined.
> 2 processes are in enforce mode.
>    /sbin/dhclient (2027) 
>    /usr/sbin/cupsd (3346) 
> 0 processes are in complain mode.
> 0 processes are unconfined but have a profile defined.

Now works "comme sur des roulettes" : )
Thanks a lot!

**Comment by noplay** [comment]
App armor :P

![](https://media.giphy.com/media/13VrSPOyLAsXxm/giphy.gif)

**Comment by AJNOURI** [comment]
That's right : )
