### ISSUE TITLE
GNS3 v1.5:  When you delete a container without stopping it, it remains running in the background.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#485]
Looks like deleted running containers are only removed from the project, but remain running in the background. 
Without "docker ps", users are not aware of them.

**Comment by noplay** [comment]
I don't see this problem how do you delete the container?

**Comment by AJNOURI** [comment]
Just by deleting them without stopping first. 
I couldn't reproduce the issue. Must be some ephemeral conditions leading to this.
I will close this issue, until experiencing it again. Thanks Julien.
