### ISSUE TITLE
Restraint resource utilization for Docker containers

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#486]
When testing containers, sometimes happens that I messed up with the build or the config and it hogs 100% of the cpu.
Should we put a resource utilisation constraint on containers (cpu & mem)? If yes what general max limit  to put?

**Comment by noplay** [comment]
Do you know if docker has option for that?

**Comment by AJNOURI** [comment]
docker has CPU quota constraint https://docs.docker.com/engine/reference/run/
For a given specific container, we could monitor it for a baseline usage and set the limit accordingly, but I guess we will need to set a value to be used for all containers.

**Comment by noplay** [comment]
It seem a little obscure in the API:

*CpuShares* - An integer value containing the container’s CPU Shares (ie.
the relative weight vs other containers).

   - *CpuPeriod* - The length of a CPU period in microseconds.
   - *CpuQuota* - Microseconds of CPU time that the container can get in a
   CPU period.

**Comment by AJNOURI** [comment]
Indeed it is not straightforward. It looks like we cannot set an absolute max cpu value for a container, but we can control the relative share (-c) which by default equal for all running containers and we can attach a container to a specific core with --cpuset=<core>
I'll do some test in the afternoon to confirm these options.

**Comment by AJNOURI** [comment]
Here is some tests without and with restrcitions using --cpu-quota and --cpuset

1- Without any restriction, all containers will share the totality of cpu of all cores.

- https://youtu.be/7oAE-hQLxHU

2- Set max cpu% restriction per container **--cpu-quota=x000 (x%)**

- https://youtu.be/8NZagDhZ9kU

3- Set max cpu% restriction per container + assign containers to specific cpu cores: 

**--cpuset="<core>,<core>..."**

- https://youtu.be/C-YmHp0PZIw

**Comment by noplay** [comment]
Perhaps we could put a limit at 80%?

**Comment by AJNOURI** [comment]
Sounds good. It will allow heavy workload containers, without freezing the host.

**Comment by AJNOURI** [comment]
Looks like debian jessie, doesn't support some options:

> WARNING: Your kernel does not support CPU cfs quota. Quota discarded.

**Comment by noplay** [comment]
If it's only a warning not problem

**Comment by noplay** [comment]
The API doesn't allow us to pass a percentage we need to ask docker about the cpu details and after reconfigure the container.

We need to get the:
* cpuperiod - The length of a CPU period in microseconds.

And after we can compute the value of:
* cpuquota - Microseconds of CPU time that the container can get in a CPU period.

I will push this to a later release and we will see if we will do that. Because it's require little tricks.

**Comment by grossmj** [comment]
Apparently this could be easier to implement now: https://docs.docker.com/config/containers/resource_constraints/

**Comment by grossmj** [comment]
Implemented.
