### ISSUE TITLE
[2.0] Rename hypervisor to compute?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#487]
OpenStack and VIRL use the term controller node and compute node to design the different parts of their architecture.

**Comment by AJNOURI** [comment]
It appears to me that, the server part corresponds the most to a **compute node** which manages VMs/devices through different **hypervisor's** API's (qemu/kvm,Vmware,Vbox,dynamips).

**Comment by grossmj** [comment]
I am for renaming +1

**Comment by noplay** [comment]
Done
