### ISSUE TITLE
Export a VM as new VM template

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#489]
For appliance where you need to make the installation of an OS at each new VM (like VyOS) it could be nice to be able to export the VM to be able to use it as the base for futur installation.

**Comment by grossmj** [comment]
Is this similar to https://github.com/GNS3/gns3-gui/issues/1221?

**Comment by noplay** [comment]
No this issue is about saving a VM has an image.

For example I install a switch with an ISO, I want  to save the qcow2 has a base image for future usages.

**Comment by ehlers** [comment]
For Qemu it's already available. First create a qemu VM without the linked clone option, then do your installation/modification, then enable the linked clone option again.

In https://www.gns3.com/discussions/speedup-iosv second paragraph (Create a startup config) I demonstrate that with an IOSv image, that that principle works with all qemu images.

**Comment by ehlers** [comment]
For docker it's relative simple doing it by command line, see https://www.gns3.com/discussions/creating-a-new-docker-image, but having it in the GUI might be nice. To be consistent an option to create a new image could also be added for Qemu (even though it can be done today, see my previous comment).

**Comment by noplay** [comment]
I think the issue is about making gns3a files

Le mer. 17 mai 2017 à 13:13, Bernhard Ehlers <notifications@github.com> a
écrit :

**Comment by noplay** [comment]
Should we create a new appliance template with the disk snapshoted?

**Comment by noplay** [comment]
It's probably a call to qemu-img on each disk in order to flatten the overlay disk

**Comment by noplay** [comment]
We have spotted an issue:
If you create a custom base image you can no longer share the topology with others.

**Comment by grossmj** [comment]
Creating a custom base image shouldn't do that, is this a consequence of using qemu-img?

Also, is this feature only for Qemu VMs?

**Comment by noplay** [comment]
The problem if you create a custom base image of ASA you will merge the proprietary code with your own modification, preventing you to redistribute the changes.

This ticket was only for Qemu.

I propose to close this. If it's confusing for us, it will be confusing for users.

**Comment by grossmj** [comment]
Agreed.
