### ISSUE TITLE
Checkbox to delete the image from host

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#490]
From **Docker VM templates:**
When a user doesn't need a Docker image anymore and wants to delete it, a checkbox "Delete image from host" (docker rmi <image>) could be useful.

**Comment by noplay** [comment]
At this time we don't provide any management interfaces for the image for any emulators. I push this to later release.

**Comment by adosztal** [comment]
Maybe it could be done automatically when the user deletes the template. Your thoughts?

**Comment by noplay** [comment]
Problem we can't be sure if user don't use the image for something else.

Example if we delete alpine it's highly possible that the user need it for something else.
