### ISSUE TITLE
GNS3 v1.5: When delete links to a containers, interface disappear until reboot

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#491]
When deleting an intermediate device (switch/router) between containers, the interface disapear from the running container, though I still can link the container interface to new devices.
I need to stop and start it again to see the interface back.

[http://hpnouri.free.fr/misc/gns3.gif](http://hpnouri.free.fr/misc/gns3.gif)

**Comment by noplay** [comment]
You should not be allowed to remove a link on a running docker I will fix that.

**Comment by noplay** [comment]
Thanks now it 's blocked

**Comment by AJNOURI** [comment]
Thanks Julien.
