### ISSUE TITLE
Restore ethernet switch & hub & frame relay, etc... in 2.0

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#492]
Actually they are broken.

We should use the standard VM api to create them with specific vm_type (ethernet_hub, ethernet_switch...) without mention of dynamips.

And after use the backend of our choice (dynamips, OVS...)

Ref #337

**Comment by grossmj** [comment]
What about a built-in vm_type and then a subtype (Ethernet hub, Ethernet Switch etc.)?

**Comment by noplay** [comment]
One annoying thing is each type has totally different configuration for his ports

**Comment by grossmj** [comment]
I think we should keep the current switches under Dynamips devices for multiple reasons:

* ATM and Frame-Relay switches are specific to Dynamips and we won't provide any alternatives.
* The current Ethernet switch has options not available in Openvswitch (e.g. QinQ) and most likely other alternatives. Some users use these features.
* Only the Ethernet hub could have a direct replacement.

So I think there are 2 solutions:

* Rename the Ethernet switch to Dynamips switch or something similar, then introduce a generic switch and hub. See https://github.com/GNS3/gns3-server/issues/337.

* Have just one "generic" switch and "generic" hub, then the controller decides what back-end/calls to use (Dynamips vs Openvswitch) based on the settings that comes from the GUI.

**Comment by noplay** [comment]
> Rename the Ethernet switch to Dynamips switch or something similar, then introduce a generic switch and hub. See #337.

I think it's confusing. People should not have to understand what is dynamips for that usage and when they should use it and when they should not.

And stuff could change (exemple QinQ support is under developement for openvswitch).

> Have just one "generic" switch and "generic" hub, then the controller decides what back-end/calls to use (Dynamips vs Openvswitch) based on the settings that comes from the GUI.

Not a big fan but seem the best solution.

**Comment by grossmj** [comment]
I am thinking having another class named Builtin for the switches + the cloud or a parent class for VM named Node. Using the standard VM API doesn't seem right because the switches, cloud etc. do not use the disk and many other features of a VM.

@noplay what do you think? must I use the VM class based on how the rest works? (Project, controller etc.)

**Comment by noplay** [comment]
VPCS also don't have disk. 

Node seem to be the correct way to name stuff. We will need to find a name also for stuff only visual like images, rectangle...

**Comment by grossmj** [comment]
Implemented in https://github.com/GNS3/gns3-server/commit/57fd72c35c4f673561487e6ec84c8c8b622cc643 and https://github.com/GNS3/gns3-server/commit/6d5085910cb89b69bed2f7c6f1d02cc724a301c3

Maybe there are some adjustments to do later.
