### ISSUE TITLE
API for rectangle, circle & co

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#498]
Add api in controller for all the additional objects.

**Comment by noplay** [comment]
Perhaps this API should be a single endpoint receiving raw SVG of the element. 

I see multiple advantage for this:
* one time work on server for supporting any visual item (you can add stuff like line without touching the server)
* client could correctly render an element without the need to implement all properties

**Comment by noplay** [comment]
@grossmj what do you think about the idea of having only raw SVG in the api for all the visual elements?

**Comment by grossmj** [comment]
That should be good to have something generic and not implement one API per item like rectangles, ellipses and more.

**Comment by noplay** [comment]
We could call this shape and add a separate call for adding text in topologies and the api will be complete.

**Comment by noplay** [comment]
The API for shapes in is place we can build other stuff on top of that.
