### ISSUE TITLE
GNS3 v1.5: No connectivity between containers

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#502]
Cannot have any connectivity between containers, though interfaces are correctly set and UP.

![screenshot - 240416 - 13 35 37](https://cloud.githubusercontent.com/assets/1716020/14767249/8505ebee-0a21-11e6-9afc-91b26b59bfd5.png)

When trying to capture traffic, server doesn't recognize connected interfaces:

> 2016-04-24 13:26:06 INFO http_client.py:677 Response error: Error downloading http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/3de96b57-5783-4078-8155-6d219e96b89f/docker/vms/0fc2b29d-c090-49f3-8a66-53b806094e22/adapters/2/ports/0/start_capture - server replied: Conflict (error: 206)
> 2016-04-24 13:26:06 DEBUG http_client.py:700 {
>     "message": "Adapter 2 is not connected",
>     "status": 409
> }
> 2016-04-24 13:26:06 ERROR vm.py:380 error while starting capture ajnouri/uquagga-2: Adapter 2 is not connected
> 

![screenshot - 240416 - 13 27 37](https://cloud.githubusercontent.com/assets/1716020/14767233/fab7a702-0a20-11e6-8521-9bf6cb1ff6d6.png)

**Comment by noplay** [comment]
You have the issue with any container or just this one?

**Comment by AJNOURI** [comment]
Looks like for any container

![screenshot - 240416 - 17 43 14](https://cloud.githubusercontent.com/assets/1716020/14768495/202a8518-0a44-11e6-929a-a1c659fa273f.png)

**Comment by noplay** [comment]
I confirm

**Comment by noplay** [comment]
I try to found the last working commit:

For the moment on gns3server this is not working:
* head
* 2109fd4f4d083dc786affabef30be466edfb46c5

**Comment by noplay** [comment]
5531a576d17c804496e724d1ead9915b7d992170 is working

**Comment by AJNOURI** [comment]
indeed, that commit works fine:

![screenshot - 250416 - 15 57 16](https://cloud.githubusercontent.com/assets/1716020/14786320/9f69711c-0afe-11e6-9e66-79c5d9584640.png)

**Comment by noplay** [comment]
I suspect b93c85c39096f1aee62f9ad5d7238b714842ce20

**Comment by noplay** [comment]
Seem to be fixed. Thanks for the help!

**Comment by AJNOURI** [comment]
Works fine. Thanks Julien.
