### ISSUE TITLE
GNS3 v1.5: Client version 1.5.0dev2 differs with server version 1.5.0dev1

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#514]
Looks like mismatch between client and server versions

> 2016-05-05 18:56:33 DEBUG local_config.py:297 Section MainWindow has not changed. Skip saving configuration
> 2016-05-05 18:56:33 DEBUG http_client.py:710 Decoding response from http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/version response 200
> 2016-05-05 18:56:33 DEBUG http_client.py:717 {
>     "local": true,
>     "version": "1.5.0dev1"
> }
> 2016-05-05 18:56:33 ERROR http_client.py:472 Client version 1.5.0dev2 differs with server version 1.5.0dev1
> Client version 1.5.0dev2 differs with server version 1.5.0dev1
> WARNING: Use a different client and server version can create bugs. Use it at your own risk.
> 2016-05-05 18:56:33 DEBUG http_client.py:576 POST http://127.0.0.1:8000/v1/projects {'temporary': False, 'project_id': 'bd2cb678-54bb-4701-a0e2-8e9aa13aa8c8', 'path': '/home/ajn/GNS3/projects/ovs-switcing', 'name': 'ovs-switcing'}
> 2016-05-05 18:56:33 DEBUG http_client.py:710 Decoding response from http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects response 201
> 2016-05-05 18:56:33 DEBUG http_client.py:717 {
>     "location": "/home/ajn/GNS3/projects",
>     "name": "ovs-switcing",
>     "path": "/home/ajn/GNS3/projects/ovs-switcing",
>     "project_id": "bd2cb678-54bb-4701-a0e2-8e9aa13aa8c8",
>     "temporary": false
> }

As consequence, cannot load or insert containers:
![](http://hpnouri.free.fr/misc/ctn-load.png)

 here a more comprehensive log file:
http://hpnouri.free.fr/misc/server.log

**Comment by grossmj** [comment]
Make sure you have updated the server and than an old one is not already running when starting the GUI.

**Comment by grossmj** [comment]
Have you used the 1.5 branch?

**Comment by AJNOURI** [comment]
Yes, I am cloning 1.5 branch for both server and gui:
```
  git clone https://github.com/GNS3/gns3-server --branch 1.5 --single-branch
  git clone https://github.com/GNS3/gns3-gui --branch 1.5 --single-branch

  cd /home/ajn/Downloads/gns3-1.5/gns3-server && gns3server --debug --local&
  cd /home/ajn/Downloads/gns3-1.5/gns3-gui && gns3 --debug
```

I've made sure no server instance is running:
```
$pgrep gns3
$ss | grep :8000
$

```
Nevertheless, I got the same issue with server version.
And GUI "Invalid auth"

> ...
> 2016-05-06 01:10:56 DEBUG server.py:237 Loading module VirtualBox
> 2016-05-06 01:10:56 DEBUG server.py:237 Loading module Dynamips
> 2016-05-06 01:10:56 DEBUG server.py:237 Loading module Qemu
> 2016-05-06 01:10:56 DEBUG server.py:237 Loading module VMware
> 2016-05-06 01:10:56 DEBUG server.py:237 Loading module Docker
> 2016-05-06 01:10:56 DEBUG server.py:237 Loading module IOU
> 2016-05-06 01:10:56 INFO server.py:241 Starting server on 127.0.0.1:8000
> 
> GNS3 GUI version 1.5.0dev2
> Copyright (c) 2007-2016 GNS3 Technologies Inc.
> 2016-05-06 01:11:02 INFO logger.py:107 Log level: DEBUG
> 2016-05-06 01:11:02 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=24d2e6cd-b920-486e-8304-5c527c2e721c&aip=1&t=screenview&an=GNS3&av=1.5.0dev2&ua=Mozilla/5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20%20GNS3/1.5.0dev2&cd=Main%20Window&ds=gns3-gui&sr=1280x1024&ul=en_gb
> 2016-05-06 01:11:03 INFO servers.py:102 New local server connection http://127.0.0.1:8000 registered
> 2016-05-06 01:11:03 INFO __init__.py:181 VPCS module reset
> 2016-05-06 01:11:03 INFO __init__.py:322 Dynamips module reset
> 2016-05-06 01:11:03 INFO __init__.py:262 IOU module reset
> 2016-05-06 01:11:03 INFO __init__.py:256 QEMU module reset
> 2016-05-06 01:11:03 INFO __init__.py:302 VirtualBox module reset
> 2016-05-06 01:11:03 INFO __init__.py:368 VMware module reset
> 2016-05-06 01:11:03 INFO __init__.py:193 Docker module reset
> 2016-05-06 01:11:03 INFO __init__.py:70 Built-in module reset
> 2016-05-06 01:11:03 INFO topology.py:408 Topology reset
> 2016-05-06 01:11:03 INFO servers.py:640 GNS3 VM server initialized http://unset:3080
> 2016-05-06 01:11:03 DEBUG http_client.py:302 Synchronous get http://127.0.0.1:8000/v1/version with user '7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl'
> 2016-05-06 01:11:03 ERROR route.py:107 Invalid auth. Username should 7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl
> 2016-05-06 01:11:03 INFO response.py:48 GET /v1/version
> 2016-05-06 01:11:03 DEBUG response.py:49 {'HOST': '127.0.0.1:8000', 'CONNECTION': 'close', 'ACCEPT-ENCODING': 'identity', 'USER-AGENT': 'Python-urllib/3.4'}
> 2016-05-06 01:11:03 INFO response.py:52 Response: 401 Unauthorized
> 2016-05-06 01:11:03 DEBUG response.py:53 {'WWW-AUTHENTICATE': 'Basic realm="GNS3 server"', 'X-ROUTE': '/v1/version', 'CONTENT-LENGTH': '0', 'ACCESS-CONTROL-ALLOW-ORIGIN': '*', 'SERVER': 'Python/3.4 GNS3/1.5.0dev1'}
> 2016-05-06 01:11:03 INFO response.py:48 GET /v1/version
> 2016-05-06 01:11:03 DEBUG response.py:49 {'HOST': '127.0.0.1:8000', 'CONNECTION': 'close', 'AUTHORIZATION': 'Basic N0JURUk5bjV6bDVVeVBqUGhpT3lzTGROeGJMM3NwN3Y3UVFPSDhxREc0eFBIQWJ2QXFTelJ4dDhMUzRuMGNibDpybkZZYnlmbW1mRFR1c0hHbndrU0kzeGNtUHBuaXc3bTNEdlFGMDNLa1cyV3BzNEU4YlM5cEdINlllVzVvTWJh', 'ACCEPT-ENCODING': 'identity', 'USER-AGENT': 'Python-urllib/3.4'}
> 2016-05-06 01:11:03 DEBUG response.py:51 {}
> 2016-05-06 01:11:03 INFO response.py:52 Response: 200 OK
> 2016-05-06 01:11:03 DEBUG response.py:53 {'X-ROUTE': '/v1/version', 'CONTENT-LENGTH': '49', 'ACCESS-CONTROL-ALLOW-ORIGIN': '*', 'SERVER': 'Python/3.4 GNS3/1.5.0dev1', 'CONTENT-TYPE': 'application/json'}
> 2016-05-06 01:11:03 DEBUG response.py:55 {'version': '1.5.0dev1', 'local': True}
> 2016-05-06 01:11:03 INFO servers.py:411 A local server already running on this host
> 2016-05-06 01:11:03 DEBUG http_client.py:302 Synchronous get http://127.0.0.1:8000/v1/version with user '7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl'
> 2016-05-06 01:11:03 ERROR route.py:107 Invalid auth. Username should 7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl
> 2016-05-06 01:11:03 INFO response.py:48 GET /v1/version
> 2016-05-06 01:11:03 DEBUG response.py:49 {'HOST': '127.0.0.1:8000', 'CONNECTION': 'close', 'ACCEPT-ENCODING': 'identity', 'USER-AGENT': 'Python-urllib/3.4'}
> 2016-05-06 01:11:03 INFO response.py:52 Response: 401 Unauthorized
> 2016-05-06 01:11:03 DEBUG response.py:53 {'WWW-AUTHENTICATE': 'Basic realm="GNS3 server"', 'X-ROUTE': '/v1/version', 'CONTENT-LENGTH': '0', 'ACCESS-CONTROL-ALLOW-ORIGIN': '*', 'SERVER': 'Python/3.4 GNS3/1.5.0dev1'}
> ...


http://hpnouri.free.fr/misc/server2.log

**Comment by noplay** [comment]
I double check and in the current code it's dev2:
https://github.com/GNS3/gns3-server/blob/1.5/gns3server/version.py

I think it's different version that is install as the gns3server command.  You can try to start the server from the gns3server directory with:
python3 -m gns3server

**Comment by AJNOURI** [comment]
Ouch! Sorry guys, it came out, somehow I accidently removed sudo from my install script and was installing gns3server without sudo.
Thanks a lot!
