### ISSUE TITLE
[Feature request] private configs for IOL

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#520]
https://gns3.com/qa/-feature-request-private-configs

**Comment by grossmj** [comment]
I have removed the warning when importing configs from a directory: https://github.com/GNS3/gns3-gui/commit/05acf724a8798acac11b106d37ee04186e341a0e

**Comment by Sourg** [comment]
@grossmj seems to be broken again in 1.5.0rc2
Here is the "private-config.cfg" I've got after export:
`
end
`

**Comment by noplay** [comment]
Sound like a totally different issue. 

You have the problem with all your IOU images?

**Comment by grossmj** [comment]
I cannot reproduce the issue. What IOU image have you used?

**Comment by ehlers** [comment]
In my collection the following images do NOT support a private-config:

i86bi-linux-l2-adventerprise-15.1b.bin
i86bi-linux-l3-ipbase-12.4.bin
i86bi-linux-l3-p-15.0a.bin
i86bi-linux-l3-p-15.0b.bin

A good hint is the absence of "k9" in the filename. They don't support the "show crypto" command. Furthermore after "wr" the private-config is 5 bytes long, it contains only `end` with leading and trailing newline. If a user gets this result and not some garbage, it's a good indication that the nvram export is working fine.

```
IOU2#sh cry?
% Unrecognized command
IOU2#      
IOU2#dir nvram:
Directory of nvram:/

   28  -rw-        1888                    <no date>  startup-config
   29  ----        1070                    <no date>  private-config
    1  ----          35                    <no date>  persistent-data

32768 bytes total (28734 bytes free)
IOU2#wr
Warning: Attempting to overwrite an NVRAM configuration previously written
by a different version of the system image.
Overwrite the previous NVRAM configuration?[confirm]
Building configuration...
[OK]
IOU2#dir nvram:
Directory of nvram:/

   28  -rw-        1569                    <no date>  startup-config
   29  ----           5                    <no date>  private-config
    1  ----          35                    <no date>  persistent-data
    2  -rw-           0                    <no date>  ifIndex-table

32768 bytes total (29094 bytes free)
IOU2#
```

**Comment by grossmj** [comment]
We only save the private-config on disk if it is different from "/nend/n": https://github.com/GNS3/gns3-server/blob/1.5/gns3server/modules/iou/iou_vm.py#L1221
