### ISSUE TITLE
[Feature request] Configure the first 3 bytes of MAC address

### ISSUE THREAD

**Issue by jprietove** [GNS3/gns3-server#522]
When trying to connect several GNS3 scenarios running on different machines to a real network using TAP interfaces, some problems arises because the different projects uses same MAC addresses.

Configuring the first 3 bytes of MAC address in each machine should result in different MAC addresses.

**Comment by noplay** [comment]
For IOS routers?

**Comment by jprietove** [comment]
QEMU and VPCs is what I use. I don't know in IOS routers.

**Comment by grossmj** [comment]
Qemu you can change the base MAC address in the Qemu VM template preferences. VPCS I don't think it is supported. I will look into it.

**Comment by jprietove** [comment]
Yes, the base MAC can be modified, but it has to be done in each QEMU machine. If you do it on the template, each QEMU machine will have the same MAC address. As an example, if you choose 12:12:12:00:00:00 as MAC base, the first machine will have 12:12:12:00:00:00, and the second one the same MAC.
For that reason, I think that instead of using 00:00:ab as the 3 most significant bytes of MAC address, or choosing a full MAC address as a base (that gives duplicate MACs in the project), it would be useful to  give the chance in GNS3 preferences to change that value (00:00:ab).

Thanks !!

**Comment by noplay** [comment]
I think this patch introduce two problem:
* mac collision is possible (probability is rare)
* mac change at each project open preventing people to do stuff attached to a specific mac address

**Comment by noplay** [comment]
Also do you think that changing the mac address of existing topology will not create trouble?

**Comment by noplay** [comment]
Also it's no clear now in the IHM that the base address will use only the start pair of the mac and that you can get mac lower than what you set in the GUI.

**Comment by grossmj** [comment]
I've had added a tooltip in the Ui. However, yep I agree there is a problem the MAC being changed at each project opening.

**Comment by grossmj** [comment]
@jprietove if I understand correctly you use the same duplicated projects on different machine, right?

**Comment by jprietove** [comment]
Sorry for the delay. I've been out. I use GNS3 for teach networking. Sometimes, I propose a project to the students and sometimes, they do them on their own.
The problem arises anytime we try to inter-connect several GNS3 projects, each on a different machine. It happens even if it is not the same duplicated project.
Particularly, I can expect that a duplicated project HAS same MACs, as it happens, and in my opinion, it is OK this way. 
But, using different projects, I think it can be useful a simply way to avoid MAC collision when using DIFFERENT projects.
So, answering your question @grossmj, No, I don't use the same project on different machines.
Thank you for your effort. I haven't thinked about the consecuences of your patch, but it seems to me that @noplay is right.
Again, very thank you for your work!

**Comment by jprietove** [comment]
Looking into the code and the proposed patch, I think that something like this could be useful in gns3server/modules/qemu/qemu_vm.py:
```
# mac_address could be:
#		ab:cd:ef			Use this as the 3 first bytes of MAC
#		ab:cd:ef:01:02:03	Use this MAC
#		empty			Choose one MAC randomly

if len(mac_address) = 8:
	self._mac_address = mac_address[:8] + ":%02x:%02x:00" % (random.randint(0, 255), random.randint(0, 255))
elif len(mac_address) = 17:
	self._mac_address = mac_address
else
	self._mac_address = "12:%02x:%02x:%02x:%02x:00" % (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
```
But I don't know the code enough to see if it breaks something.

**Comment by noplay** [comment]
Your patch will create an issue that the mac address will be not stable. I think it's an issue when using an appliance requiring a licence computed from the mac address (it's common for license system).

Are you using save as to create new project? This could explain that  two project has duplicate mac if they come from the same original project.

I think about a solution for your use case. In 1.5 we offer an import/export project option for situation like your, easy distribution of a project to your students (you can even embed image). Perhaps we could add an option allowing you to randomize the mac during the import if asked.

**Comment by jprietove** [comment]
Thank you @noplay, you are right, this way is not useful. 
I'm very sorry I think I haven't explain correctly my proposal. Now that I have a little time, I will try:
# Scenario 1: Same project used by several students #
As it is the same project, copied to the students, I can expect that a duplicated project HAS same MACs, as it happens, and in my opinion, it is OK this way.
As a workaround, when I want to copy a project with same MACs to students and need them to be connectable, I tell them to open the .gns3 file with a text editor and Find/Replace **"mac_address": "00:00:ab : ** with another starting sequence.
I think a good way to put this option in GNS3 is taking Virtualbox as an example: when you import an OVA file, there is a switch 'restart MAC addresses'. Also, you can do it anytime in network properties of the Virtual Machine.
Properties of QEMU (or other kind of appliances) could have near 'Base MAC' a button for resetting it. This button also would be shown when selecting a group of appliances.
But this is another enhancement that the initially proposed, that cames in the...
# Scenario 2: different projects made by different students on different machines #
In this scenario, each students draw their own project and each QEMU machine has its own (different) MAC address.
But randomness seems to be against me or my students: several times we have had strange behaviours and after some deep analysis we found that there were duplicate MACs.
It doesn't happens always but when it happens, it can take a long time before founding it.
So, this is the origin of the proposal: instead of always using the hardcoded ''00:00:ab", let the user modify/choose this value. Maybe in QEMU 'General Settings', with 'Use the local server' and 'enable KVM'.
Ah! And VPCs always uses the same MACs, that's the reason because sometime ago I decided not to use it, but Microcore QEMU instead. And my plan is to use (lovely) Docker when 1.5 released!
Hope this helps! Again, thanks a lot!

**Comment by noplay** [comment]
No worry.

Teacher / Students is a scenario we really want to improve and we need such report from the battlefield.

For scenario 1 my proposition of resetting the mac at import should solve the issue.

For scenario 2 last fixe from jeremy should reduce a lot collision 3f61fbeb0e8330d43718ac93cdcd12fe40274753

The change is from
```python
self._mac_address = "00:00:ab:%s:%s:00" % (self.id[-4:-2], self.id[-2:])
```
65536 possibilities

```python
self._mac_address = "00:%s:%s:%s:%s:00" % (self.project.id[-4:-2], self.project.id[-2:], self.id[-4:-2], self.id[-2:])
```
4294967296 possibilities

**Comment by noplay** [comment]
@grossmj we will need to announce the change in 1.5 note because it will change the mac for current topologies

**Comment by noplay** [comment]
Oh after checking it's ok since the mac is stored in topologies

**Comment by noplay** [comment]
And if your student import a project a project the project_id will change so if you remove all mac_address field GNS3 will regenerate a new one (we will need to provide option for that)

**Comment by grossmj** [comment]
The will implement a reset of MAC addresses when you import a project in 2.0

**Comment by jprietove** [comment]
Thank you a lot! I have tested the patch and seems to work fine!
Option of reset MAC addresses would be very useful!
