### ISSUE TITLE
[Question] Multi-user GNS3 server for a school lab?

### ISSUE THREAD

**Issue by k4kfh** [GNS3/gns3-server#523]
I'm helping to start a cybersecurity class/club at my high school, and we're in need of a simple lab system. We want 4-5 users to be able to simulate networks, and I'm thinking gns3-server is a good option. Is there support for a multi-user style server on GNS3?

**Comment by noplay** [comment]
GNS3 itself doesn't support multi user with ressource control and isolation. Perhaps in a later release.

You can have mutliple user using the same server it's not an issue. It's common for enterprise to setup a server and share it bewteen employees.

But at this time most config is on the client this mean you need to share the config if you want to use the same images.
