### ISSUE TITLE
[2.0] Check if /config/reload is still require

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#539]
Actually we already have a system pooling the file for change since 1.4   (not sure when we introduced this) based on file modified time. I think /config/reload is a duplicate but need to check on windows.

**Comment by grossmj** [comment]
I think we introduced it because we could not reliably detect the modified time on Windows.

**Comment by noplay** [comment]
Related to https://github.com/GNS3/gns3-gui/issues/1187

**Comment by noplay** [comment]
I found the detection problem on windows look at 	2912789

We were changing the event loop on Windows after starting the watch of the files so the delayed task was lost.
