### ISSUE TITLE
Dissallow duplicate name for compute, node and project

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#541]

**Comment by noplay** [comment]
We have two possibility:
* auto fix the name by appending -1, -2, -3 to the name
* raise an error

**Comment by noplay** [comment]
Auto fix seem easier to avoid the need to manage error on the client

**Comment by grossmj** [comment]
Here is what I propose for nodes:

- "name" becomes optional, this field will be used when loading a project with node that already have names.
- add a name_format, also optional by with default values server side.

When creating a new node, the server will use the name format to create an unique name in the project.

**Comment by grossmj** [comment]
To be consistent with the rest compute_id should be renamed compute_name.

**Comment by grossmj** [comment]
Hum... looks like compute_id can be an UUID as well. Should we have a name for the compute?

**Comment by noplay** [comment]
I agree for having the server allocating name.

I think name is require to have something clear instead of http://mysuperserver.example.org:3080

We have a name field actually in compute like what we have for node.

**Comment by grossmj** [comment]
I will take care of the duplicate name for node.

**Comment by grossmj** [comment]
@noplay please review just in case I missed something. I started the implementation on the compute side before realizing it should be in the controller ;)
