### ISSUE TITLE
[1.5b1]:  Exporting project with VMs

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#542]
Is project with VMs not portable? If it is the case, a message box would be more appropriate.

> => ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 1641, in _exportProjectActionSlot
>     QtWidgets.QMessageBox.critical(self, "Export portable project" "A project containing VMware or VirtualBox VMs cannot be exported because the VMs are managed by these software.")
> TypeError: critical() missing 1 required positional argument: 'message'

**Comment by noplay** [comment]
Yes it should not crash. But it's not portable
