### ISSUE TITLE
[1.5b1]:  Export project with OVS container: Permission denied

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#543]
Cannot export project with OVS containers:

> Could not copy file to /home/ajn/GNS3/projects/linux-bridge-test0/project-files/docker/ad4678e4-130b-4da8-aacf-ce62f76db9bf/etc/openvswitch/.conf.db.~lock~: [Errno 13] Permission denied: '/home/ajn/GNS3/projects/linux-bridge-test1/project-files/docker/ad4678e4-130b-4da8-aacf-ce62f76db9bf/etc/openvswitch/.conf.db.~lock~'
> Could not copy file to /home/ajn/GNS3/projects/linux-bridge-test0/project-files/docker/d4418724-a8cf-4882-8dbf-da22eacd1825/etc/openvswitch/.conf.db.~lock~: [Errno 13] Permission denied: '/home/ajn/GNS3/projects/linux-bridge-test1/project-files/docker/d4418724-a8cf-4882-8dbf-da22eacd1825/etc/openvswitch/.conf.db.~lock~'
> Could not copy file to /home/ajn/GNS3/projects/linux-bridge-test0/project-files/docker/ad4678e4-130b-4da8-aacf-ce62f76db9bf/etc/openvswitch/.conf.db.~lock~: [Errno 13] Permission denied: '/home/ajn/GNS3/projects/linux-bridge-test1/project-files/docker/ad4678e4-130b-4da8-aacf-ce62f76db9bf/etc/openvswitch/.conf.db.~lock~'
> Could not copy file to /home/ajn/GNS3/projects/linux-bridge-test0/project-files/docker/d4418724-a8cf-4882-8dbf-da22eacd1825/etc/openvswitch/.conf.db.~lock~: [Errno 13] Permission denied: '/home/ajn/GNS3/projects/linux-bridge-test1/project-files/docker/d4418724-a8cf-4882-8dbf-da22eacd1825/etc/openvswitch/.conf.db.~lock~'

**Comment by noplay** [comment]
Can you give us the result of ls -l on the file?

**Comment by AJNOURI** [comment]
> ls -l /home/ajn/GNS3/projects/linux-bridge-text5/project-files/docker/ad4678e4-130b-4da8-aacf-ce62f76db9bf/etc/openvswitch/conf.db
> **-rw-r--r-- 1 ajn ajn** 52204 May 19 12:07 /home/ajn/GNS3/projects/linux-bridge-text5/project-files/docker/ad4678e4-130b-4da8-aacf-ce62f76db9bf/etc/openvswitch/conf.db

**Comment by noplay** [comment]
On my PC the lock file is owned by root

**Comment by noplay** [comment]
Ok I have no idea how to fix this :( The problem is docker container will create file as root in the volume and we could have no right on the file.

It's larger issue because we can not also delete a project with a file like this.

**Comment by noplay** [comment]
It seem I can change the user run in the container I will dig this solution

**Comment by noplay** [comment]
Problem when you do that you no longer have trouble with file created but you can no longer use root commands in the container.

**Comment by AJNOURI** [comment]
I use docker as non-root user, maybe this explains why in my PC the file is owned by user (ajn):

> sudo usermod -aG docker {user}

**Comment by noplay** [comment]
Yeah but in the container uid will change

**Comment by noplay** [comment]
I show a warning and doesn't block the export it's the best we can do :(

**Comment by AJNOURI** [comment]
OK, thanks Julien.

**Comment by albert-a** [comment]
Run this command in openvswitch console:
```
chown -R 1000:1000 /etc/openvswitch
```
It solves the problem.
Alternatively you can fix permissions all at once for all instances in all projects.
For example, on linux, to check which files are owned by root, use:
```
find /home/gns3 -user root
```
To change permissions (assuming GNS3 user and group is `gns3`):
```
chown -R --from root gns3:gns3 /home/gns3
```
