### ISSUE TITLE
[1.5b1]:  Exporting project (only containers: no ovs): Connection to http://unset:3080

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#544]
This happens after successfully exporting project (with only containers relatively to this issue https://github.com/GNS3/gns3-server/issues/543), then trying to importing it into another project name.

> 2016-05-24 10:17:39 INFO http_client.py:421 Connection to http://unset:3080
> 2016-05-24 10:17:39 DEBUG http_client.py:576 GET http://unset:3080/v1/version {}
> QObject: Cannot create children for a parent that is in a different thread.
> (Parent is HTTPClient(0x21a9690), parent's thread is QThread(0x1b30b00), current thread is QThread(0x3accbf0)
> QObject: Cannot create children for a parent that is in a different thread.
> (Parent is QNetworkAccessManager(0x21c0620), parent's thread is QThread(0x1b30b00), current thread is QThread(0x3accbf0)
> 2016-05-24 10:17:39 INFO http_client.py:680 Response error: Host unset not found (error: 3)
> 2016-05-24 10:17:39 INFO http_client.py:271 Connection to http://unset:3080 closed
> 2016-05-24 10:17:39 ERROR http_client.py:444 Cannot connect to remote server http://unset:3080
> 2016-05-24 10:17:39 CRITICAL progress_dialog.py:164 ImportProjectWorker thread stopping with an error: Can't import the project
> 2016-05-24 10:17:39 CRITICAL __init__.py:94 Can't import the project
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 9, in <module>
>     load_entry_point('gns3-gui==1.5.0b1', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main.py", line 262, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 1713, in _importProjectActionSlot
>     self.loadPath(path)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 457, in loadPath
>     progress_dialog.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/utils/progress_dialog.py", line 165, in _error
>     QtWidgets.QMessageBox.critical(self.parentWidget(), "Error", "{}".format(message))
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 94, in critical
>     log.critical(message, stack_info=LogQMessageBox.stack_info())
> 2016-05-24 10:17:39 DEBUG progress_dialog.py:110 ImportProjectWorker thread finished
> 2016-05-24 10:17:39 DEBUG progress_dialog.py:131 ImportProjectWorker thread is being destroyed
> 2016-05-24 10:17:39 DEBUG progress_dialog.py:138 ImportProjectWorker thread destroyed
> 
>

**Comment by noplay** [comment]
Are You are on Linux? Are you using the GNS3 VM?

**Comment by AJNOURI** [comment]
I am not using GNS3 VM.

> Linux gns3-iouvm 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux
> No LSB modules are available.
> Distributor ID:	Debian
> Description:	Debian GNU/Linux 8.4 (jessie)
> Release:	8.4
> Codename:	jessie
>

**Comment by noplay** [comment]
Fixed

**Comment by noplay** [comment]
Thanks for the report
