### ISSUE TITLE
[2.0] Discover the VM on the network

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#545]
Actually we start the VM server from the GUI via the VirtualBox and VMware commands. 

This create:
* huge complexity in client
* VMware is vmrun it's not reliable
* VMware vmrun require additional tools installed on system when using VMware player
* Creating Hyper-V VM require the same amount of work

We can imagine let the user start the VM manually and GNS3 will search it on the network via a home made broadcast or discovery protocol like UPNP.

**Comment by noplay** [comment]
About the host binding. On the VM it's already bind on all interface no problem with that.

We don't need to bind the GNS3 controller to an adapter in the same network of the VM. The only part that we need to bind is the emulator. We can decide this at emulator start.

**Comment by noplay** [comment]
The discovery could also work when use with a VPN remote (like packet)

**Comment by grossmj** [comment]
I would not say the current code is hugely complicated but it has its problems for sure and heavily rely on users correctly installing VMware as well as hoping for no problems with vmrun itself. I sill think it is nice to automatically start GNS3 VM for the users because I am concerned about the overall usability.

However, it could be nice to have a discovery method. We could use mDNS to discover the VM IP address, see https://en.wikipedia.org/wiki/Zero-configuration_networking and https://en.wikipedia.org/wiki/Multicast_DNS

**Comment by grossmj** [comment]
Maybe we can leverage avahi (to install on the GNS3 VM: apt-get install avahi-daemon) to publish a service.

There is a great example on http://stackoverflow.com/questions/3430245/how-to-develop-an-avahi-client-server. However our client should be made to run on Windows/OSX.

**Comment by grossmj** [comment]
Well on OSX we have Bonjour and apparently you can leverage the Bonjour implementation of iTunes to support mDNS on Windows: http://superuser.com/questions/491747/how-can-i-resolve-local-addresses-in-windows wicked! ;)

**Comment by noplay** [comment]
You are right the ideal is to discover only on vmnet, vboxnet. That solve the noisy neighbor problem


Python zeroconf seem easy to expose something (but use netfifaces):
https://github.com/jstasiak/python-zeroconf/blob/master/examples/registration.py

And even if not well documented it seem you can limit to some interface the discovery:
https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf.py

**Comment by grossmj** [comment]
I have added zeroconf to the server however I am not totally satisfied with how the service IP to advertise is found (via command line param) in case the server IP is 0.0.0.0.

**Comment by noplay** [comment]
We could support the interface in the configuration file.

I don't like the term of service interface but not sure what could be best:
* discovery interface ?

**Comment by grossmj** [comment]
Well when I read discovery or service interface I think of the interface used to send/receive discovery packets. Now we use that interface to just say this is the IP address to use to contact the server.

**Comment by noplay** [comment]
Announcement interface?

Also I think starting the service should be enable only if we configure an interface to avoid issues with people that install gns3 on a server in their network and don't want it to broadcast informations.

**Comment by grossmj** [comment]
I've implemented an UDP server discovery supporting both broadcast and multicast (on 239.42.42.1). 

Works well, however I cannot find how on to stop the executor when stopping the server, I get the following exception:

```
2016-06-15 17:39:00 ERROR _base.py:299 exception calling callback for <Future at 0x7f4ec318fef0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.4/asyncio/futures.py", line 408, in <lambda>
    new_future._copy_state, future))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 462, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 436, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 265, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

Apparently this is a know issue: https://github.com/python/asyncio/issues/258

**Comment by grossmj** [comment]
Additionally, here is a quick test client. Maybe something for the unit tests?

```
import socket
import struct

# broadcast
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
s.sendto(b"ABCD", ('<broadcast>', 3080))
print(s.recvfrom(1024))

# multicast
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
ttl = struct.pack('b', 1)
s.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, ttl)
s.sendto(b"ABCD", ('239.42.42.1', 3080))
print(s.recvfrom(1024))
```

**Comment by noplay** [comment]
I tested and don't see how to fix the executor stuff. Perhaps we need to implement an asyncio protocol like this:
https://github.com/python/asyncio/blob/master/examples/udp_echo.py

I also add a flag and a setting to enable it.

**Comment by grossmj** [comment]
There is one probleme with asyncio UDP, I cannot use the black magic to find out on what server IP to send to clients :(

**Comment by grossmj** [comment]
Well, I will just use a classic thread running in the background.

**Comment by noplay** [comment]
Yes

**Comment by noplay** [comment]
No success to make it work with virtualbox their adapter seem totally broken and prevent multicast and broadcast.

**Comment by grossmj** [comment]
Yep, I could make a broadcast work for VMware but I had to send the it specifically to the vmnet8 or vmnet1 interface, that meant finding the IP address etc... in the end I went back to the good old method ;)
