### ISSUE TITLE
[2.0] Connecting VPCS to cloud en1 on mac do nothing

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#549]
I have no error when I connect a VPCS to my wifi adapter but it's not working I see nothing during packet capture.

**Comment by grossmj** [comment]
Confirmed that Wifi adapters are not well supported by the libpcap. The workaround is to use TAP interfaces: http://www.fixedbyvonnie.com/2015/04/connect-your-gns3-lab-to-the-internet-mac-os-x/

**Comment by noplay** [comment]
The fix is not working because all adapters start with en. 

On my macbook:
* en0 RJ45
* en1 Wifi

On a macbook air without RJ45 port
* en0 Wifi

**Comment by grossmj** [comment]
Argh... ok :( How can we know it is a Wireless adapter on OSX? psutil doesn't give anything.

**Comment by grossmj** [comment]
Found a way on OSX using the ``networksetup -listallhardwareports`` command. After parsing the output you can know which interface is Wifi or not.

**Comment by grossmj** [comment]
@noplay please test and confirm it works on your Mac.
