### ISSUE TITLE
[1.5.0b1]  Permission denied when trying to rename a container.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#550]
> Server error : Could not delete the VM working directory: [Errno 13] Permission denied: 'rabbitmq'
> 
> => Server error from http://127.0.0.1:8000: ajnouri/rabbitmq-server-1: Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3server/web/route.py", line 179, in control_schema
>     yield from func(request, response)
>   File "/usr/local/lib/python3.4/dist-packages/gns3server/handlers/api/docker_handler.py", line 288, in update
>     vm.start_command = request.json.get("start_command", vm.start_command)
>   File "/usr/local/lib/python3.4/dist-packages/gns3server/modules/docker/docker_vm.py", line 132, in start_command
>     command = command.strip()
> AttributeError: 'NoneType' object has no attribute 'strip'

Directory  permission

> ls -l ~/GNS3/projects/rabbitmq-hello/project-files/docker/3be19923-fbf9-446d-ae8f-eff5d7555e38
> total 4
> drwxr-xr-x 3 ajn ajn 4096 May 31 00:28 etc

**Comment by noplay** [comment]
For the strip it's fixed and the traceback it's fixed

**Comment by noplay** [comment]
The issue is with subdirectories

**Comment by noplay** [comment]
It's fixed and it should also fixe the export issue.

When stopping the container the ownership of mounted volumes will be change to your user. It's prevent you having in your project file owned by root.

**Comment by ehlers** [comment]
I'm not too happy with your change. If the process in a docker container is not running as root (e.g. a web server with user www), it might not be able to access the files in the mounted volume.

I agree, that giving the user access to the mounted volume is a good thing, but changing the ownership of the files is quite drastic. Sad enough I don't have a good idea to solve that conflict.

**Comment by noplay** [comment]
Do you have a sample? I think if you run your container as different user command like ip will not work at all and your container will not work at all (I think container with USER directive could not be supported).

Also file created outside will have your user id, if you want to make them readable by the container you need to allow everyone to read them from the container if you are not root.

But I agree this could break stuff :( And the only way if you have a program running as root but with user changing is too change the permission at container boot.

My solution has the advantage to never block the user, with the drawback of potentially break  some containers. 

Ideally we should save the original ownership and permission to restore it later.  I will see if I could do that.

**Comment by ehlers** [comment]
Oh, my comment seems be too terse, it was a little later yesterday.

I don't mean to run the docker process with another user as root. I was talking about processes within the docker VM. For example my ftpd docker VM (https://github.com/ehlers/gns3-docker-images/tree/master/ftpd) starts ftp and tftp services within docker, which run with the user-id ftp. The numeric value of this user-id is chosen at create time of the docker image and has nothing to do with any user-id of the host system.

By your change the files in /ftp directory will get another user-id, so the ftp user within the docker container can't access it anymore. So the ftp and tftp service can't work.

If you look closely at my Dockerfile I was also unhappy about the different user-ids within the container and the outside world. I solved it with the environment variables FTP_UID and FTP_GID, but that's more a hack.

My actual idea is to keep your change, because it solves the issue that the user should be able to access those files. Additionally in the startup script of the docker container (start_ftp.sh in my example) I can adapt the user-id and group-id of the user ftp to match the owner of the mounted volume. That could be done with something like that:

```
uid=`stat -c %u /ftp`
[ 0$uid -ne 0 ] && usermod -o -u $uid ftp
gid=`stat -c %g /ftp`
[ 0$gid -ne 0 ] && groupmod -o -g $gid ftp
```

That way the service process within docker uses the same user/group id as in the host. Drawback, of course, is that the docker image has to be modified for GNS3 to work like that.

**Comment by noplay** [comment]
I see if I found a way to save and restore permission it will fix your issue right?

It's seem possible:
http://arstechnica.com/civis/viewtopic.php?f=20&t=370027

**Comment by ehlers** [comment]
Sure, that will fix my issue.

**Comment by noplay** [comment]
I don't see how we could do that using only tools provided with busybox. I think the only way to do that is to write a C program for dumping acl and restore them :( And embed a compiled version in GNS3

Any tough?

**Comment by ehlers** [comment]
Well, if permissions are enough we could try (just an idea, not fully tested):

save:
```
find $directory -depth -print0 | xargs -0 stat -c '%a,%u,%g,%n' > perms.csv
```

restore:
```
while IFS=, read PERMS OWNER GROUP FILE
do
    chmod "$PERMS" "$FILE"
    chown "${OWNER}:${GROUP}" "$FILE"
done < perms.csv
```

Drawback is, that file with comma in the filename might have some problems, maybe another separator is better. Also files with newline in the name wouldn't work. Furthermore ACL wouldn't be touched. But it should be OK for 99.9% of the cases.

The full solution could be the use of getfacl and setfacl but for that we have to build a static version of the acl package. But I think that is too much work. My case with the docker service not running as root is probably an exception and I wouldn't take that much effort to handle that.

**Comment by ehlers** [comment]
Just have another idea:

When a new docker VM is created by the gns3server:
- use setfacl to set access rights for the current user and group  
  `setfacl -m u:<user id>:rwx,g:<group id>:rx <directory>`
- use setfacl to set default access rights for the current user and group  
  `setfacl -dm u:<user id>:rwx,g:<group id>:rx <directory>`

That way the user and group has always access to that directory, even when files and directories are created by docker with user root (or any other user id).

That requires the installation of the acl package in the linux host running docker (normally the GNS3 VM). But you don't have to fiddle with access rights afterwards. No save/restore of permissions, no changes of the file ownership.

What do you think about that?

**Comment by noplay** [comment]
Problem GNS3 itself run as your user and can not change the ACL.

**Comment by noplay** [comment]
You are a genius your shell script work. I have used the : as seperator like in $PATH

**Comment by ehlers** [comment]
On a newly created docker VM the directories for the volumes are empty and belonging the host user and don't have any other ACL. Then (tested on debian jessie) I have no problems creating those ACLs. For me it worked.

But I agree, it won't work on existing docker VMs. But hey, we are in the beta phase.

Anyway, this save/restore stuff is fine as well. Only one comment: xargs and stat are not using the busybox binary, but are located in the usual path. So you should prepend the /gns3/bin/busybox stuff.

**Comment by noplay** [comment]
Fixed for busybox
