### ISSUE TITLE
[1.5.0b1]  container interface tcp offload issues

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#551]
Same issue as here https://github.com/GNS3/gns3-server/issues/444
By default tx offload enabled (all container interfaces)

> ethtool -k eth0
> Features for eth0:
> rx-checksumming: on
> tx-checksumming: on
> 	tx-checksum-ipv4: off [fixed]
> 	tx-checksum-ip-generic: on
> 	tx-checksum-ipv6: off [fixed]
> 	tx-checksum-fcoe-crc: off [fixed]
> 	tx-checksum-sctp: off [fixed]
> scatter-gather: on
> 	tx-scatter-gather: on
> 	tx-scatter-gather-fraglist: on
> tcp-segmentation-offload: on
> 	tx-tcp-segmentation: on
> 	tx-tcp-ecn-segmentation: on
> 	tx-tcp6-segmentation: on
> udp-fragmentation-offload: on
> generic-segmentation-offload: on
> generic-receive-offload: on
> large-receive-offload: off [fixed]
> rx-vlan-offload: on
> tx-vlan-offload: on
> ntuple-filters: off [fixed]
> receive-hashing: off [fixed]
> highdma: on
> rx-vlan-filter: off [fixed]
> vlan-challenged: off [fixed]
> tx-lockless: on [fixed]
> netns-local: off [fixed]
> tx-gso-robust: off [fixed]
> tx-fcoe-segmentation: off [fixed]
> tx-gre-segmentation: on
> tx-ipip-segmentation: on
> tx-sit-segmentation: on
> tx-udp_tnl-segmentation: on
> tx-mpls-segmentation: off [fixed]
> fcoe-mtu: off [fixed]
> tx-nocache-copy: off
> loopback: off [fixed]
> rx-fcs: off [fixed]
> rx-all: off [fixed]
> tx-vlan-stag-hw-insert: on
> rx-vlan-stag-hw-parse: on
> rx-vlan-stag-filter: off [fixed]
> l2-fwd-offload: off [fixed]

And the issue is solved when disabling tx offloading

> ethtool -K eth0 tx off

![screenshot - 310516 - 12 00 07](https://cloud.githubusercontent.com/assets/1716020/15670969/7deeb808-2728-11e6-8296-0d639e3dfe25.png)

**Comment by noplay** [comment]
Could you check if ubridge is 0.9.4 ? In beta 1 we forgot to check this.

**Comment by AJNOURI** [comment]
/usr/bin/ubridge -v
ubridge version 0.9.3

**Comment by noplay** [comment]
It's the issue you need 0.9.4. Now GNS3 will raise an error if it's not the case:
https://github.com/GNS3/ubridge/releases/tag/v0.9.4

Thanks for the report

**Comment by AJNOURI** [comment]
OK, got it. Thanks Julien.
