### ISSUE TITLE
Find a replacement for NAT in the cloud

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#553]
SLIRP is overly complicated and not documented. Next best thing is to leverage a bridge or VDE in the GNS3 VM.

**Comment by grossmj** [comment]
@noplay should we replace the VDE bridge by a TAP inside the VM (and also provide the instructions for Linux users to create one).

Then I will be able to create a NAT node that detect if the TAP exists and use that to connect to the outside world.

**Comment by noplay** [comment]
Can we ask ubridge to create a tap? It could simplify the life of Linux users.

For OSX I think we can embed the same tuntap kernel extension that tunnel blick use. It's create 10 /dev/tapX by default.

For windows we can embed in the installer the Tap of OpenVPN:
https://openvpn.net/index.php/download/community-downloads.html

**Comment by grossmj** [comment]
We could use ubridge for it. However, creating a TAP is not enough, there is something more to do. Do you remember what it is? and I don't think it is going to be easy to make it multi-platform.

**Comment by noplay** [comment]
We could start a docker container with DHCP, DNS, NAT...

**Comment by grossmj** [comment]
Why don't we use the docker0 bridge? it is supposed to exist to handle these things no?

**Comment by noplay** [comment]
I think the docker0 don't have a DHCP server

**Comment by noplay** [comment]
I confirm docker don't have a DHCP they don't need it.

**Comment by grossmj** [comment]
Duplicate of https://github.com/GNS3/gns3-server/issues/599
