### ISSUE TITLE
[1.5 rc1] cannot connect a container to a generic l2 switch neither to cloud tap interface

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#555]
![screenshot - 030616 - 07 24 19](https://cloud.githubusercontent.com/assets/1716020/15769543/5805909a-295c-11e6-97d5-a5536a92b137.png)

 
> 2016-06-03 07:17:22 DEBUG http_client.py:703 {
>     "message": "unable to create UDP NIO",
>     "status": 409
> }
> 2016-06-03 07:17:22 ERROR device.py:107 error while adding a NIO for SW1: unable to create UDP NIO
> 
---
> 2016-06-03 07:23:58 INFO http_client.py:680 Response error: Error downloading http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/c6548bbb-716c-446e-abbb-ae38f00af4b5/docker/vms/f1fb1d52-9f1a-4dd4-9b3b-ff110c4e1bef/adapters/0/ports/0/nio - server replied: Conflict (error: 206)
> 2016-06-03 07:23:58 DEBUG http_client.py:703 {
>     "message": "NIO of type nio_tap is not supported",
>     "status": 409
> }
> 2016-06-03 07:23:58 ERROR vm.py:286 error while adding a NIO for jenkins-1: NIO of type nio_tap is not supported
> 2016-06-03 07:23:58 INFO link.py:141 deleting link from Cloud 1 nio_tap:tap0 to jenkins-1 Ethernet0
>

**Comment by AJNOURI** [comment]
Some inf. worth mentioning:

> Distributor ID:	Debian
> Description:	Debian GNU/Linux 8.4 (jessie)
> Release:	8.4
> Codename:	jessie

tap interface is part of a bridge OpenVswitch

> sudo ovs-vsctl show
> 579f91e6-efc3-480b-96f3-b9f21bfbafb4
>     Bridge "ovsbr0"
>         Port "tap0"
>             Interface "tap0"
>         Port "ovsbr0"
>             Interface "ovsbr0"
>                 type: internal
>         Port "eth0"
>             Interface "eth0"
>     ovs_version: "2.3.0"

Now I could connect the generic switch to ovsbr0, but still not to tap0 or other tap not part of the bridge.

Sometimes (not systematically) rebooting solves the issue.

**Comment by noplay** [comment]
For a tap it's normal it's not supported.

Can you check if you don't have ghost dynamips process?

**Comment by AJNOURI** [comment]
Currently, for an opened lab (VMWare+docker+cloud connected to ovsbridge)

> ps -aux | grep dynamips
> ajn       4912  0.0  0.0  12728  2272 pts/2    S+   12:42   0:00 grep dynamips
> ajn      24817  0.4  0.0 212844  5180 pts/3    Sl+  04:40   2:11 /usr/local/bin/dynamips -N1 -l dynamips_i2_log.txt -H 127.0.0.1:53508
> ajn      30729  0.1  0.0 207060  5272 pts/3    Sl+  02:05   1:11 /usr/local/bin/dynamips -N1 -l dynamips_i1_log.txt -H 127.0.0.1:41714
>

**Comment by noplay** [comment]
Quit GNS3, killall dynamips.

Reopen it . Connect switch to tap and container to switch, it's work? And when you exit you should no longer have ghost dynamips. It's the case?

**Comment by AJNOURI** [comment]
These are my observations, cannot come with a clear isolation of the cause:

Before each one of these cases, I've made sure no ghost dynamips running.
1- Strangely, with simple topology, I have encountered no error or issues with connections after closing and reopning either the lab or GNS3.
![screenshot - 080616 - 15 38 59](https://cloud.githubusercontent.com/assets/1716020/15898016/e8f3e5fa-2d96-11e6-8b13-f2180ebc8fb7.png)


2- But with sightly more complicated lab, I can connect container to generic l2 switch and make it work, but issues start after closing gns3 and reopening the lab, it doesn't recognize the link between the container and the switch.
Have to manually reconnect them to make it work.

![screenshot - 080616 - 16 25 39](https://cloud.githubusercontent.com/assets/1716020/15897697/c60a8b12-2d95-11e6-975e-63edaea4d0ed.png)


> 2016-06-08 16:25:23 DEBUG http_client.py:576 POST http://127.0.0.1:8000/v1/projects/d84dbcfb-0275-4b87-be3c-d4ed25c450e0/docker/vms/4b63e48d-e896-4ba4-981b-bbd866238655/adapters/1/ports/0/nio {'rport': 10003, 'lport': 10002, 'type': 'nio_udp', 'rhost': '127.0.0.1'}
> 2016-06-08 16:25:23 DEBUG http_client.py:711 Decoding response from http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/d84dbcfb-0275-4b87-be3c-d4ed25c450e0/docker/vms/4b63e48d-e896-4ba4-981b-bbd866238655/adapters/1/ports/0/nio response 201
> 2016-06-08 16:25:23 DEBUG http_client.py:718 {
>     "lport": 10002,
>     "rhost": "127.0.0.1",
>     "rport": 10003,
>     "type": "nio_udp"
> }
> 2016-06-08 16:25:23 DEBUG http_client.py:711 Decoding response from http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/d84dbcfb-0275-4b87-be3c-d4ed25c450e0/dynamips/devices/2609cc27-9f58-4c19-8100-e2a14161e868/ports/1/nio response 201
> 2016-06-08 16:25:23 DEBUG http_client.py:718 {
>     "ethernet_device": "ovsbr0",
>     "type": "nio_generic_ethernet"
> }
> 2016-06-08 16:25:23 DEBUG link.py:343 NIO_Generic_Ethernet attached to Cloud 2 on port nio_gen_eth:ovsbr0
> 2016-06-08 16:25:23 DEBUG link.py:359 NIO_Generic_Ethernet attached to SW1 on port 1
> 2016-06-08 16:25:23 INFO http_client.py:680 Response error: Error downloading http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/d84dbcfb-0275-4b87-be3c-d4ed25c450e0/dynamips/devices/2609cc27-9f58-4c19-8100-e2a14161e868/ports/2/nio - server replied: Conflict (error: 206)
> 2016-06-08 16:25:23 DEBUG http_client.py:703 {
>     "message": "unable to create UDP NIO",
>     "status": 409
> }
> 2016-06-08 16:25:23 ERROR device.py:107 error while adding a NIO for SW1: unable to create UDP NIO
> 2016-06-08 16:25:23 INFO link.py:141 deleting link from SW1 2 to ajnouri/internet-1 Ethernet1

Slightly different error here, but related to the generic l2 switch:

![screenshot - 080616 - 16 49 26](https://cloud.githubusercontent.com/assets/1716020/15898531/fd68f82a-2d98-11e6-9b06-ca8ff2c524a9.png)


> 2016-06-08 16:45:43 INFO http_client.py:680 Response error: Error downloading http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/7a54433d-441f-4f37-b24a-ef4d9495fa06/dynamips/devices/eb693c74-2362-41e7-beba-859fc80312b6/ports/2/nio - server replied: Conflict (error: 206)
> 2016-06-08 16:45:43 DEBUG http_client.py:703 {
>     "message": "Port 2 isn't free",
>     "status": 409
> }
> 2016-06-08 16:45:43 ERROR device.py:107 error while adding a NIO for SW1: Port 2 isn't free
> 2016-06-08 16:45:43 INFO link.py:141 deleting link from SW1 2 to ajnouri/internet-1 Ethernet1

Sometimes it doesn't show the any error, but the generic l2 doesn't pass traffic.

**Comment by noplay** [comment]
And when GNS3 is close you see no dynamips process running?

**Comment by AJNOURI** [comment]
Yes, each time I have to kill it, before launching gns3 again.

**Comment by noplay** [comment]
How do you exit GNS3?

**Comment by noplay** [comment]
I think it's a common issue we should a way to kill ghost process when the gns3server start

**Comment by AJNOURI** [comment]
I stop devices and then close the window and by the way, often it keeps waiting for closure (progress bar) until it gives up and quit.

**Comment by grossmj** [comment]
If you right click on a node and select "Show in file manager" you should see a ubridge.log file that contains a description of the error.

**Comment by grossmj** [comment]
We now allow TAP connections in version 1.5.1. Do you still have issues?

**Comment by grossmj** [comment]
@AJNOURI ping ;)

**Comment by AJNOURI** [comment]
Yea, now (1.5.1) container connect beautifully to tap.
Good job guys!
