### ISSUE TITLE
[1.5 rc1] VNCviewer black screen.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#556]
GUI app. doesn't show up through vnc, I get black screen.
All containers either start the apps through start command or docker file CMD

![screenshot - 030616 - 05 08 53](https://cloud.githubusercontent.com/assets/1716020/15779481/ee2cdcbe-299c-11e6-9447-2ca62fbc52dd.png)

**Comment by noplay** [comment]
Can check via PS if x11vnc and xvfb run?

**Comment by AJNOURI** [comment]
They aren't running
![screenshot - 090616 - 01 57 41](https://cloud.githubusercontent.com/assets/1716020/15914968/a5eaf6f0-2de5-11e6-8ce7-fc8879a4dd84.png)

Looks like x11nx and xfvb not even installed

> / # ps -fax
>   PID TTY      STAT   TIME COMMAND
>    17 ?        Ss     0:00 /gns3/bin/busybox script -qfc /gns3/bin/busybox sh /d
>    23 pts/0    Ss     0:00  \_ /gns3/bin/busybox sh
>    47 pts/0    R+     0:00      \_ ps -fax
>     1 ?        Ssl+   0:00 /usr/lib/chromium/chromium --show-component-extension
>    40 ?        Z+     0:00 [chromium] <defunct>

/ # 

> / # find / -name 'xvfb'
> / # find / -name 'x11vnc'

**Comment by AJNOURI** [comment]
Installed xvfb and x11vnc from Dockerfile
`RUN apt-get update && apt-get install -qqy firefox Elinks **x11-apps x11vnc xvfb**`
Now works fine.

![screenshot - 090616 - 03 19 26](https://cloud.githubusercontent.com/assets/1716020/15916323/d2317e08-2df1-11e6-9abb-8eda002dba21.png)


Should they be installed manually? If yes, can we externalize this job to busybox?

**Comment by noplay** [comment]
No we are not running them in the container. I don't understand how it could work after. xvfb and x11vnc need to run on your PC not inside the container :(. They communicate with the X application in the container by exposing a unix socket inside. It's done by sharing the directory /tmp/.X11-unix/ with the container. And GNS3 use X11 display with display number >= 100

What is gns3-iouvm? It's a GNS3 VM?

**Comment by noplay** [comment]
I just test on a fresh install of Xenial no issues.

**Comment by AJNOURI** [comment]
Yes, hence my confusion. xvfb and x11vnc are running all the time in the pc, when it was showing the black screen.
All I have done is adding xvfb and x11vnc to the list of packages installed in the container.

"gns3-iouvm" is just the host running GNS3 (GUI+server) for iourc licence purpose...

**Comment by noplay** [comment]
And gns3-iouvm is under which OS/distribution? xvfb and x11vnc was installed on it?

Thanks for the help

**Comment by noplay** [comment]
Can you test it seem I fixed an issue: 	016c3e5

Thanks!

**Comment by AJNOURI** [comment]
Sorry for the late reply. 
iou-vm runs on debian jessie and both xvfb and x11vnc are installed

> Distributor ID:	Debian
> Description:	Debian GNU/Linux 8.4 (jessie)
> Release:	8.4
> Codename:	jessie

Well, for now it works only with a single container (Dockerfile below)  for other container it is the same black screen, though I managed to start the gui app at container start.


```
FROM ubuntu:14.04
# Fabio Rehm: http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/

RUN export uid=1000 gid=1000 && \
    mkdir -p /home/developer && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer

USER developer
ENV HOME /home/developer
CMD /usr/bin/firefox

```

**Comment by noplay** [comment]
The container gns3/xeyes work for you?

**Comment by AJNOURI** [comment]
Yes works with xeyes.
But same black screen for ostinato, though ostinato on alpine looks slightly better (ostinato window background shows up) than on ubuntu.

![screenshot - 140616 - 20 22 27](https://cloud.githubusercontent.com/assets/1716020/16054585/161822cc-326e-11e6-8ba2-2cf479988c05.png)

Ostinato on Ubuntu (phusion/baseimage)
```
FROM phusion/baseimage:0.9.16
CMD ["/sbin/my_init"]
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y ostinato
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
CMD ostinato
```

Ostinato on Alpine
```
FROM alpine
RUN apk update && apk add wget
RUN wget http://nl.alpinelinux.org/alpine/edge/testing/x86_64/ostinato-0.7.1-r0.apk
RUN wget http://nl.alpinelinux.org/alpine/edge/testing/x86_64/ostinato-drone-0.7.1-r0.apk
RUN wget http://nl.alpinelinux.org/alpine/edge/testing/x86_64/ostinato-gui-0.7.1-r0.apk
RUN apk add ostinato-0.7.1-r0.apk
RUN apk add ostinato-drone-0.7.1-r0.apk
RUN apk add ostinato-gui-0.7.1-r0.apk
RUN rm -rf /var/cache/apk/*
CMD ostinato
```

**Comment by noplay** [comment]
Seem to be a QT issue:
https://bbs.archlinux.org/viewtopic.php?id=185698

Adding : 
```
export QT_GRAPHICSSYSTEM=native
```

Before lauching it seem to fix the the issue. You can try in the aux console:
https://bbs.archlinux.org/viewtopic.php?id=185698

```
export QT_GRAPHICSSYSTEM=native
ostinato
```

I will add it by default

**Comment by AJNOURI** [comment]
Only Ostinato on ubuntu reacts positively

![screenshot - 150616 - 18 11 27](https://cloud.githubusercontent.com/assets/1716020/16089774/fdc105ee-332c-11e6-8068-cb8a1b340738.png)

But as soon as I add a new port group and validate, the screen turns to black

Ostinato on Alpine acts like below:

![screenshot - 150616 - 18 11 44](https://cloud.githubusercontent.com/assets/1716020/16089835/392b5dc8-332d-11e6-8b57-1fd115f7ac29.png)

**Comment by noplay** [comment]
I think you have missing font package on alpine. Can you try to start ostinato from the aux console you will see the warning on the console.

Same for the port group. It's probably a crash of ostinato.
