### ISSUE TITLE
[1.4.6/Linux] Automating GNS3: Exception launching a lab from CLI

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#558]
No issue launching the same lab from GNS3 GUI.

From the CLI:
```
gns3 Stress\ Test\ with\ IOSv\ and\ ASA-linux.gns3 
GNS3 GUI version 1.4.6
...
2016-06-04 20:06:25 INFO router.py:714 router SW2_ASAs is loading
router SW2_ASAs is loading
2016-06-04 20:06:25 INFO http_client.py:672 Response error: Error downloading http://AnIIj0n3Bq3DOgGy065HevlfGu4DKKxMqGG64wysNHM21pC8AtEgpAGA92VASTez@127.0.0.1:8000/v1/projects - server replied: Bad Request (error: 302)
Response error: Error downloading http://AnIIj0n3Bq3DOgGy065HevlfGu4DKKxMqGG64wysNHM21pC8AtEgpAGA92VASTez@127.0.0.1:8000/v1/projects - server replied: Bad Request (error: 302)
Error while creating project: Invalid JSON: '' is too short in schema: {"description": "Project directory", "minLength": 1, "type": ["string", "null"]}
****** Exception detected, traceback information saved in /root/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_gui-1.4.6-py3.5.egg/gns3/qt/__init__.py", line 228, in partial
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gns3_gui-1.4.6-py3.5.egg/gns3/http_client.py", line 729, in _processResponse
    raise e
gns3.http_client.HttpBadRequest: {
    "message": "Invalid JSON: '' is too short in schema: {\"description\": \"Project directory\", \"minLength\": 1, \"type\": [\"string\", \"null\"]}",
    "path": "/v1/projects",
    "request": {
        "name": "Stress Test with IOSv and ASA-linux",
        "path": "",
        "project_id": "71f18de6-f37d-4970-97cf-6cadecc82bf7",
        "temporary": false
    },
    "status": 400
}
...
```
Whole log
[Automating GNS3 - Exception launching a lab from CLI.txt](https://github.com/GNS3/gns3-server/files/298965/Automating.GNS3.-.Exception.launching.a.lab.from.CLI.txt)

It would be very helpful to be able to perform the following **tasks/commands** from *CLI in order t automate* some labs:
- launch the lab with its .gns3 topology file as argument
- return code describes success/failure
- start all nodes
- return code describes success/failure
- stop all nodes
- return code describes success/failure
- exit the lab and return to CLI

**Comment by noplay** [comment]
Could you share the content of the .gns3?

**Comment by noplay** [comment]
About the automation 2.0 will provide a full REST api to do that you will no longer need the GUI to this operations. A true cli could be build on top of that api.

**Comment by jean-christophe-manciot** [comment]
I can share the .gns3 [Stress Test with IOSv and ASA-linux.gns3.txt](https://github.com/GNS3/gns3-server/files/302190/Stress.Test.with.IOSv.and.ASA-linux.gns3.txt), but the issue does not depend on any specific topology file.
Do you plan on writing & distributing the related API documentation? Otherwise it will be mostly useless.
Also, I found it quite difficult to locate any open-source detailed doc about recent GNS3 online. 
And, I have no idea why the team blackholed ("archived") all very helpful posts made on your previous website. Does Jive keep them hostage? It should be possible to transfer all of them now that the new site is operational.

**Comment by noplay** [comment]
GNS3 is running on port 8000 ? I have the feeling that something else is running on port 8000 and redirect the query creating this error.

For API doc we have this WIP:
http://gns3-server.readthedocs.io/en/2.0/

For JIVE we got the archive but it's hard to found something inside. The forum should have everything inside. The blog post are still missing the web developers need to bring back the features.

**Comment by jean-christophe-manciot** [comment]
Nothing is running on 8000 before the call.
Afterwards, 3 gns3-server processes are running despite only one "gns3 topology.gns3" call:
![3 gns3-server](https://cloud.githubusercontent.com/assets/13176858/15854762/f082eb4a-2cab-11e6-84f9-367df9b71633.jpg)

**Comment by jean-christophe-manciot** [comment]
Then, they disappear...

**Comment by jean-christophe-manciot** [comment]
The API looks promising.
A few remarks:
- it would be clearer to name all actions, including create, for instance:
  + /v2/projects/{project_id}/create
  + /v2/projects/{project_id}get_id
  + ...
- some actions are missing, for instance:
  + /v2/projects/{project_id}/open
  + /v2/enable
  + ...

**Comment by noplay** [comment]
I can not reproduce the issue. @grossmj you reproduce it?

**Comment by noplay** [comment]
Not reproduced from our side, please reopen if you still have the issue with 1.5
