### ISSUE TITLE
[Ask] How To Add Router Huawei

### ISSUE THREAD

**Issue by nurhambali** [GNS3/gns3-server#559]
Hi all,
My problem add Router Huawei on GNS3 1.4.6
Help me.
Terima kasih.
Nurhambali

**Comment by noplay** [comment]
Hi,

You should ask this on the community forum if other users already tested this.
https://gns3.com/community

**Comment by ehlers** [comment]
Have a look at https://gns3.com/news/article/connecting-huawei-ensp-to-gns3
