### ISSUE TITLE
When you create a project folder create a symbolic link to the project folder and use the project name

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#560]
It is difficult to find the project folder if you need to do something manually in that folder
It would be helpful to have sympbolic links to each project folder, the name of the symlink should be the name of the project as it is used by GNS3 GUI

**Comment by noplay** [comment]
Hi,

In the GUI you can make a right click on a node and get the path via the menu open in file browser.

Later will provide a way to explore the files from the GUI or via the API to offer a simple and safe way to do that.

**Comment by 1001QAdotNET** [comment]
Great ..thanks, that makes the things bearable for now
