### ISSUE TITLE
Copy data of the original folder when mounting a VOLUME

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#561]
To be fully compatible with original behavior of Docker VOLUME. We need to copy the data from the original volume at the first start

**Comment by noplay** [comment]
@ehlers what do you think of this?

**Comment by ehlers** [comment]
Can you please revert the change https://github.com/GNS3/gns3-server/commit/775ee4259e2967975bce30c9ec5f8ea4c63cd63b Integrate fixes from @ehlers ?

On copy-paste the whitespaces have changed in several lines, which was not intended. Please use my diff/patch file. I wanted to change only the loop starting in line 32.

Other then that it's possibly a good idea, the users won't be surprised by using volumes. Hopefully they won't use it for export the root directory (/) as a volume 😄.

**Comment by noplay** [comment]
Done :)

**Comment by ehlers** [comment]
Initially I was a little bit sceptic about the need to copy the original folder. But after playing a little bit with that, I have to confess that I like it. It really feels more natural now.
