### ISSUE TITLE
Convert topologies for 2.0

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#564]
We need to support .gns3 made for previous version.

**Comment by grossmj** [comment]
That's the "fun" part... ;)

**Comment by noplay** [comment]
I have started the implementation with a test suite checking if conversion work.

For that you need to create directories in test/topologies. 

Each directory is a GNS3 project. You have two directory inside:
* before 
* after

Before is the state of the project before conversion and after is the reference for checking if conversion is a success.

To check if file are the same we check the file size except for .gns3

# .gns3 check

The .gns3 json is loaded and compare to the reference project.

You have some special value in the after project:
* "ANYSTR" allow for any string to match

# Run the tests

You can run the tests with:
``` 
    py.test -vv -x tests/test_topologies.py
