### ISSUE TITLE
Node update on controller should stop when receiving a node update error from compute

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#566]

**Comment by noplay** [comment]
I don't understand what you want.

**Comment by grossmj** [comment]
If an update fail (PUT on compute), the controller still thinks the update was successful and send a updated notification to the GUI.

**Comment by noplay** [comment]
Problem is much harder than expected. Because how to handle partial failure? Example I change the name (on controller) and a config (compute) the compute could failed but revert is not easy.

**Comment by noplay** [comment]
Fixed
