### ISSUE TITLE
1.5: leftover empty Volume after use of Docker VM

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#567]
GNS3 latest V1.5 commit https://github.com/GNS3/gns3-server/commit/313226786fb3ce2ddcde41396e14b93d16dc89d5
Docker v1.11.2

I created a small docker container, which uses a volume:
```
FROM alpine
VOLUME [ "/test" ]
CMD [ "sh" ]
```

When I use this docker VM, the volume is mounted into a subdirectory within the GNS3/projects, but additionally a docker volume is created.
```
root@gns3vm:~# docker volume ls
DRIVER              VOLUME NAME
local               bcc828a90fc17822008b465c63e75c584ec67d5709b3be60e1b0e3ad0fc0802a
```

When I then close the project containing this docker VM, `docker ps -a` shows no leftover docker container, but `docker volume ls` still shows this docker volume. After some time several of those leftover volumes will be created.

I assume, that this is a caused by change https://github.com/GNS3/gns3-server/commit/e3350155204f6d1200aaa82b1c4014ee0708f0fc . Previously the volume directory was mounted directly. Now `/gns3volumes/<volume>` is mounted, the real volume is mounted in the init.sh script. But docker doesn't know about that. At start of the container, docker sees that the volume directory is not assigned to a directory and assigns it to a docker volume container (and copies the contents).

A `docker inspect` of the container shows that:
```
root@gns3vm:~# docker inspect 942e13fce995
.
.
.
        "Mounts": [
            {
                "Source": "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev5-py3.4.egg/gns3server/modules/docker/resources",
                "Destination": "/gns3",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/opt/gns3/projects/67fc8dfa-91f1-494e-a4bd-870eac0706f8/project-files/docker/676a6b4a-7189-41fe-8392-d07c9d2bc058/etc/network",
                "Destination": "/gns3volumes/etc/network",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/opt/gns3/projects/67fc8dfa-91f1-494e-a4bd-870eac0706f8/project-files/docker/676a6b4a-7189-41fe-8392-d07c9d2bc058/test",
                "Destination": "/gns3volumes/test",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Name": "bcc828a90fc17822008b465c63e75c584ec67d5709b3be60e1b0e3ad0fc0802a",
                "Source": "/var/lib/docker/volumes/bcc828a90fc17822008b465c63e75c584ec67d5709b3be60e1b0e3ad0fc0802a/_data",
                "Destination": "/test",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
```

**Comment by noplay** [comment]
Not the best fix :( But I clean the volume after. 

The real clean solution should be have a VolumePlugin to allow us to write on disk but require a modified docker binary.

**Comment by ehlers** [comment]
Another alternative: Don't use the VOLUME info from the docker image, but let the user configure a list of persistent directories. But that has the drawback, that the user needs to know, where the important data is.

Normally the creator of the docker images has a better knowledge, what directory should be persistent. Therefore I still favor the VOLUME method. But it's debatable.
