### ISSUE TITLE
No keep-alives between client and server

### ISSUE THREAD

**Issue by hortongeo** [GNS3/gns3-server#57]
Not sure if this needs to be logged against the client or server - let me know if it needs to be moved.

Using gns3server on a remote server with the connection via a firewall, no keep-alives are sent.  This causes the firewall to identify the session as stale and close it.  Further updates requested via the GUI no longer reach the server.
Can a keep-alive be sent between the client/server to ensure that the TCP session stays up.

**Comment by noplay** [comment]
It's fixed in the upcoming 1.3 release
![capture d ecran 2015-02-24 a 15 45 50](https://cloud.githubusercontent.com/assets/345437/6351476/4970a594-bc3c-11e4-9690-d27ff1276658.png)
