### ISSUE TITLE
Docker container support creates wrong busybox links

### ISSUE THREAD

**Issue by ddompe** [GNS3/gns3-server#570]
Hi,

I'm using the 1.5 rc1, and trying to use the container support with OpenSwitch. The init.sh script is failing to start, since apparently when installing the busybox links into /tmp/gns3/bin, the links are broken since they point to busybox.nosuid (which is nowhere on the path).

**Comment by noplay** [comment]
The other containers work?

**Comment by ddompe** [comment]
Good question... it does. I test it with gns3/endhost

I did some debugging with strace over the install command being executed by the init.sh script and found the reason:

```
/tmp/gns3/bin # strace -v /gns3/bin/busybox --install -s /tmp/gns3/bin
execve("/gns3/bin/busybox", ["/gns3/bin/busybox", "--install", "-s", "/tmp/gns3/bin"], ["GNS3_VOLUMES=/etc/network", "HOSTNAME=OpenSwitch-1", "SHLVL=2", "OLDPWD=/", "HOME=/home/root", "_=zcat", "TERM=xterm", "PATH=/usr/local/sbin:/usr/local/"..., "GNS3_MAX_ETHERNET=eth7", "PWD=/tmp/gns3/bin"]) = 0
arch_prctl(ARCH_SET_FS, 0x6e0da0)       = 0
set_tid_address(0x6e0dd8)               = 44
getuid()                                = 0
brk(0)                                  = 0x1657000
brk(0x1658000)                          = 0x1658000
readlink("/bin/busybox", "busybox.nosuid", 80) = 14
symlink("busybox.nosuid", "/tmp/gns3/bin/[") = 0
symlink("busybox.nosuid", "/tmp/gns3/bin/[[") = 0
```

Seems like the busybox install has the wrong prefix compiled on it, and is checking the value on /bin (which in openswitch is a symlink to busybox.nosuid)

**Comment by noplay** [comment]
Awesome I will rebuild the busybox

**Comment by noplay** [comment]
I rebuild the bin will test it tommorow you can replace:
gns3server/modules/docker/resources/bin/busybox by https://github.com/GNS3/gns3-server/raw/049c34870912734cacb93b7cf335ecc879a3744d/gns3server/modules/docker/resources/bin/busybox

Or use the last commit of the branch 1.5

Thanks a lot for your help , it's think debug this will have take a long time otherwise

**Comment by ddompe** [comment]
Works like a charm now! Thanks a lot.
