### ISSUE TITLE
The ability to configure the name of the first interface and the other interfaces for containers 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#574]
The ability to configure the name of the first interface and the other interfaces for containers (similar to what is done for virtualbox). In the OpenSwitch appliance the first port is the mgmt from the CLI, and would be nice to show like that on the GNS3 UI, and that the ports have also the same name as in the CLI (ethX instead of EthernetX).

Suggestion of 	@ddompe

**Comment by noplay** [comment]
I will check if it's not too hard I'm afraid that could have side effects.

**Comment by ddompe** [comment]
Just a clarification with regards to the implementation and side effects: the name should be reflected only on the GNS3 UI. For example eth0 should still be called eth0 inside the container, it should be called differently only on the UI.

**Comment by noplay** [comment]
I renamed the name to ethX it's better.

About the fact to be able to change the name of the first port, I don't like the idea to be able to change it in GUI only because this will create questions from user.

Change it in the docker container create too much trouble. And on a standard linux the interface will be named ethX even the management interface. I don't touch it for the moment.  But perhaps the whole port naming could be refactor in the futur to allow more flexibility on port naming (not only for docker).
