### ISSUE TITLE
[1.5.rc1]  weird vnc port behavior

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#577]
Sometimes, when I open a project and try to vnc to a container, the connection is refused.
I have noticed that, even when gns3 is closed (no ghost processes), there is a bunch of x11vnc processes listing on host ports.

And when I open gns3 project and run a project and try to vnc to a container (below example port 5910),  I noticed there is no x11vnc listing on such port and I have to change the vnc container port to one of the already opened ports from previous sessions.

![selection_104](https://cloud.githubusercontent.com/assets/1716020/16089961/c6827652-332d-11e6-944d-f5ffc0723b3f.png)

This doesn't occur all the time.

**Comment by noplay** [comment]
Can you try with RC2?

**Comment by AJNOURI** [comment]
Looks OK now!
No more hanging x11vnc processes, they start with containers and close with the project.

**Comment by noplay** [comment]
Great thanks for the feedback !
