### ISSUE TITLE
[1.5]  docker image pulls images only once (first  time) from docker hub

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#587]
Looks related to #490 

After deleting a docker template, GNS3 will not delete the image from disk.
So when creating a new template (from new image) and then insert an instance of the image to a topology, GNS3 doesn't pull it from docker hub, but read the first installed image.

Outside of GNS3, I have to delete all containers using that image, delete the image itself and only then GNS3 pull the new updated version from docker hub.

**Comment by noplay** [comment]
It doesn't seem an issue for me. But normal Docker behavior. Docker keep a cache of used images.

We can't choose to delete because for example if you use an ubuntu image. You could want few minute later to create a new container based on that.

**Comment by AJNOURI** [comment]
I mean, how can use the new version of the same image built in docker hub if GNS3 always refer to the first pulled image?

**Comment by AJNOURI** [comment]
Here is a concrete case example:

1- Let's suppose I built an image in Docker hub
2- For the first time I create template from new image in GNS3
3- When I insert it to a topology, gns3 will pull the image from docker hub as expected

> => Info: Pulling image ajnouri/internet:latest:fae91920dcd4: [>                                                  ] 32.77 kB/2.31 MB
> ...

4- Suppose I'am not satisfied with my build image and decide to change Dockerfile and rebuild it in dockerhub
5- Now, I delete the template from GNS3 and create a new template hoping that it will pull the new image from docker hub.
6- When I insert it to a topology, gns3 will NOT pull the modified image from docker hub, but will use the old image installed before (because it was not deleted along with the template)

**Comment by noplay** [comment]
I think in this scenario you are supposed to push different tag to the dockerhub instead of using :latest

For me it's actual Docker design https://github.com/docker/docker/issues/13331

At this time they didn't  offer the option to change that.

**Comment by ehlers** [comment]
Just stumbled upon the same issue. When I'm planning to update a docker image in the GNS3 registry all existing user of that image have no change to get this update as long as we are using no tags.

The difference to "normal" docker user is, that the GNS3 user has normally no deep knowledge about docker and doesn't know, that he has to login into the CLI of the GNS3VM and delete the old docker image. Then a new version gets downloaded. But I also understand, that we shouldn't try to rewrite docker.

So the consequence is, that we should tag every docker image in the GNS3 registry. On a change not only the Dockerfile has to be modified but also the appliance file (.gns3a) to change the tag. Then an existing user of an appliance can re-download the appliance file and the docker image with the new tag will be automatically downloaded and used.

**Comment by AJNOURI** [comment]
What about something like "Update" button for docker images, GNS3 could ask the user only the new tag (ex:ajnouri/internet:**1.1**) to pull from Docker hub? 
This could make it easier, even if initially didn't tag the image.

**Comment by noplay** [comment]
This will not fix the topologies. Due to the fact topologies are anywhere
on the system change the tag will not change the topologies. In this case
update is like creating a new template.

I'm not sure of the side effect of fixing that, if docker do stuff like
this they probably have a reason. And we need to be carefull of not
breaking a container not used in GNS. Do you know if tools exist for docker
to manage this?

**Comment by AJNOURI** [comment]
As far as I know, this is done by recompiling locally (**docker build**) or remove (**docker rmi**) and pull (**docker pull**). Of course with container using volumes to not affect the data.
To update the topology, we could read the container connections and re-link them... 
API queries could be like this:
`/v1/projects/{project_id}/docker/images/{id}/getlinks` to read links and corresponding peer devices
`/v1/projects/{project_id}/docker/images/{id}/setlinks` to build a link

Ok, it is a bit far-fetched.
