### ISSUE TITLE
[2.0] Dump topology as an image

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#588]
With the move of the topology to the server we no longer have an easy way to have a screenshot of the topology in the project. Previously it was done by asking Qt to snapshot the image display on screen. Now due to the fact you can connect to a non Qt client we need if we want to dump an image to do it server side.

As discuss with jeremy not blocking for the 2.0

**Comment by noplay** [comment]
Render a PNG on server is a no GO because it will require complex dependencies to be installed on the server.

**Comment by noplay** [comment]
A solution could be to dump everything as a SVG.

**Comment by noplay** [comment]
The screenshot need to be regenerate at each save, it could create issues if topologies is big and you make a lot of modifications.

**Comment by grossmj** [comment]
I don't think this is an easy task nor it is very useful.
