### ISSUE TITLE
add daemon capabilities. 

### ISSUE THREAD

**Issue by anubisg1** [GNS3/gns3-server#59]
GNS3-server is ment to run standalone (without gui) on a remote server.

as of now, gns3-server is not able to run as a daemon or service.

this feature should be implemented if we really want to have a client/server application

**Comment by networkpadawan** [comment]
@anubisg1 does that script work on systemd? because on sysinit it does not. I created as script file, but when i try to start it "locks" itself to the shell.

**Comment by anubisg1** [comment]
Hi @networkpadawan  , yes, that is a systemd script and it works like a charm. tested on Fedora, Centos, and openSUSE

**Comment by networkpadawan** [comment]
ubuntu uses sysinit so i have to build a bash script, can´t use yours:/ manage to bypass by using the '&' flag...not perfect but works!

**Comment by anubisg1** [comment]
actually ubuntu uses upstart :D in any case ubuntu is a pain in the ass since it does always things its own way without following any real standard (unity, location of libraries, X server , ecc )

i'd say that the init script might be provided by gns3 as a template or something like that, but distribution packagers should add the service based on their standards.

**Comment by networkpadawan** [comment]
you're right, but to upstart seems a init daemon:P (still better than systemd imho )and yes gns3 should daemonize the server, even for a multi tenant env it would help.

**Comment by noplay** [comment]
For upstart:
```
description "GNS3 server"
author      "GNS3 Team"

start on filesystem or runlevel [2345]
stop on shutdown

script
    echo $$ > /var/run/gns3.pid
    if [ ! -f /usr/local/bin/gns3server ]; then
        pip3 install gns3-server==1.3.0rc2
    fi
    exec start-stop-daemon --start -c gns3 --exec /usr/local/bin/gns3server
end script

pre-start script
    echo "[`date`] GN3 Starting" >> /var/log/gns3.log
end script

pre-stop script
    rm /var/run/gns3.pid
    echo "[`date`] GNS3 Stopping" >> /var/log/gns3.log
end script
```

**Comment by noplay** [comment]
Daemon is ready in 1.4 I just create a an issue with the need of a systemd script #229

**Comment by noplay** [comment]
Systemd is ready
