### ISSUE TITLE
Failure with linux nio during portable project import

### ISSUE THREAD

**Issue by ddompe** [GNS3/gns3-server#590]
I tried to import a project from my Native Linux setup, into a Mac/GNS3 VM environment using docker, it seemed to work flawlessly except by one error. My network has a 'cloud' with Linux ethernet NIO, connected to a UML switch, and got the following error when importing the project:

Server error from http://127.0.0.1:3080: SW 1: Unknown command 'create_linux_eth'

I attached a project that only has a cloud and a UML switch that shows the problem (compressed since github doesn't support the extension)

[bug_report.gns3project.zip](https://github.com/GNS3/gns3-server/files/330361/bug_report.gns3project.zip)

**Comment by ddompe** [comment]
Digging more on the issue, I replaced the linux nio by a generic nio, but it now ask to remap to the interface on the target machine. However the list of ports is from the local server.... so the docker images are running on the VM, but seems like the cloud is running on the local server?

**Comment by noplay** [comment]
@grossmj What should we do with the cloud during import / export ?

**Comment by ddompe** [comment]
When you drag a cloud on the canvas and you have both a local server and VM server, it asks you in which server you want to create the cloud.

When importing the project I guess you should ask if you want to import the project into the local server or VM server (similar to cloud, but for the whole import). What is currently doing is importing the docker containers into the VM server by default (I guess because is the only one that supports it, since the local is mac), but the cloud is assuming should go into the local.

**Comment by grossmj** [comment]
Indeed, looks like there is an issue. I'll investigate.

**Comment by ddompe** [comment]
Adding more data.

I tried replacing my cloud by using the internet-for-gns3vm appliance, and got similar results. When I import the project on mac, the device gets created on the localhost, not the VM.

**Comment by noplay** [comment]
All qemu devices should be on the GNS3 VM, I confirmed a bug here.

For cloud I don't see how we can make a topology with a cloud portable because by nature the cloud depends of the host computer. I propose to turn it off for 1.5 and found solution in 2.0.

A solution in 2.X could be to disallow cloud in portable projects and have two special node: NAT and Bridge.  This node are globally configured in the controller. This would solved most of users need.

**Comment by noplay** [comment]
The qemu bug is fixed

**Comment by noplay** [comment]
Since it's fix in 1.5 by dissalowing export I proposed to postpone to 2.X
