### ISSUE TITLE
[ 1.5.0dev6] unknown nvram format

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#594]
When opening an existing project, cannot start IOU router.
A new inserted router works fine.

> 2016-06-24 15:49:15 DEBUG http_client.py:703 {
>     "message": "Cannot push configs to nvram /home/ajn/GNS3/projects/openstack-multinode/project-files/iou/74c388f9-3ef2-4860-8fae-3f332bb6b1d6/nvram_00002: unknown nvram format",
>     "status": 409
> }
> 2016-06-24 15:49:15 ERROR vm.py:146 error while starting IOU2: Cannot push configs to nvram /home/ajn/GNS3/projects/openstack-multinode/project-files/iou/74c388f9-3ef2-4860-8fae-3f332bb6b1d6/nvram_00002: unknown nvram format
>

**Comment by grossmj** [comment]
Any project?

**Comment by AJNOURI** [comment]
Well, looks like only with a particular project and with a particular router:
![screenshot - 240616 - 21 13 34](https://cloud.githubusercontent.com/assets/1716020/16348099/cc941814-3a50-11e6-976c-affc02844412.png)

**Comment by noplay** [comment]
Could you share the nvram file?

**Comment by AJNOURI** [comment]
[hpnouri.free.fr/misc/nvram_00002](hpnouri.free.fr/misc/nvram_00002)

**Comment by grossmj** [comment]
@ehlers any idea? ;)

**Comment by ehlers** [comment]
Well, according to my findings (see https://github.com/ehlers/IOUtools/blob/master/NVRAM.md) this NVRAM file is indeed invalid (sort of). iou_export is forgiving, therefore you can extract the contents. But iou_import mades some strict checks and refuses to overwrite images, that doesn't confirm.

In this case the NVRAM is mostly fine, but between the config and the private-config there is an additional padding of 4 bytes. This is normal for IOU images with version <= 15.1. But this IOU image has version 15.4 and I haven't seen an IOU with that version that behaves like that.

@AJNOURI what IOU image are you using? Do you have the same problems with this IOU images on other places? Have you copied the NVRAM from another existing router? Can you reproduce this from scratch?

**Comment by AJNOURI** [comment]
I haven't had such issue with other projects or IOUs.
In the project (picture above), IOU1 (OK) and IOU2 (with the issue) uses the same image i86bi-linux-l3-adventerprisek9-15.4.1T.bin, IOU3 (OK) uses another image i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin.
A project created from the scratch doesn't show any issues. 
I could not reproduce the problem.

**Comment by noplay** [comment]
Perhaps a bug in the image that corrupt the NVRAM

**Comment by ehlers** [comment]
Thanks @AJNOURI for the problematic NVRAM and the other information.

I found a bug in the iou_import tool. When I reverse-engineered the NVRAM format last year I tested only with smaller NVRAM sizes, I think I used 64KB. After some testing with this "faulty" NVRAM I found out, that the NVRAM is absolutely fine. It's IOU that slightly changes it's format for NVRAM sizes >= 128KB.

I changed the IOUtools in https://github.com/ehlers/IOUtools. Normally I would suggest to copy them into gns3server/modules/iou/utils . But as we are already in RC2 it's perhaps better to stick with the GNS3 version of the IOUtools and backport the bug fix.

Here it is:
```
diff --git a/gns3server/modules/iou/utils/iou_import.py b/gns3server/modules/iou/utils/iou_import.py
index 6ebe525..57d39c7 100644
--- a/gns3server/modules/iou/utils/iou_import.py
+++ b/gns3server/modules/iou/utils/iou_import.py
@@ -64,9 +64,10 @@ def put_uint32(data, off, value):


 # calculate padding
-def padding(off, ios):
+def padding(off, ios, nvram_len):
     pad = (4 - off % 4) % 4             # padding to alignment of 4
-    if ios <= 0x0F00 and pad != 0:      # add 4 if IOS <= 15.0
+    # add 4 if IOS <= 15.0 or NVRAM area >= 64KB
+    if (ios <= 0x0F00 or nvram_len >= 64*1024) and pad != 0:
         pad += 4
     return pad

@@ -118,7 +119,7 @@ def nvram_import(nvram, startup, private, size):
         if get_uint16(nvram, 0) == 0xABCD:
             ios = get_uint16(nvram, 6)
             config_len = 36 + get_uint32(nvram, 16)
-            config_len += padding(config_len, ios)
+            config_len += padding(config_len, ios, nvram_len)
             if get_uint16(nvram, config_len) == 0xFEDC:
                 config_len += 16 + get_uint32(nvram, config_len + 12)
     except IndexError:
@@ -158,7 +159,7 @@ def nvram_import(nvram, startup, private, size):
     put_uint32(new_nvram, 12, BASE_ADDRESS + 36 + len(startup))   # end address
     put_uint32(new_nvram, 16, len(startup))                     # length
     new_nvram.extend(startup)
-    new_nvram.extend([0] * padding(len(new_nvram), ios))
+    new_nvram.extend([0] * padding(len(new_nvram), ios, nvram_len))

     # import private config
     if private is None:
```

This bug influences mainly the insertion of the private config, so this bug fix should additionally improve https://github.com/GNS3/gns3-server/issues/520.

**Comment by ehlers** [comment]
As the default for most (all?) L2 images is 16KB and for L3 images is 64kB, this bug bites only users that modify the NVRAM size to 128MB or more. Therefore we haven't heard more complains.

**Comment by grossmj** [comment]
Well done! We will play it safe and add the change for 1.5.1.

Thanks again.

**Comment by AJNOURI** [comment]
Thanks guys. I will test it 1.5.1

**Comment by noplay** [comment]
I'm not sure that is good idea to embed this in a minor release. Because minor release are not well tested by community. And due to the fact IOU is only reverse engineering we can't be sure all images work use  the same padding system.

I propose to disallow NVRAM >= 128KB in 1.5 via the GUI and to embed the patch in 2.0.

**Comment by ehlers** [comment]
@AJNOURI please try this procedure to bypass your issue with the current software version:
- for safety reasons please copy the original nvram_00002 (you already did that), the startup-config.cfg and optionally the private-config.cfg
- in the node configuration of IOU2 set the NVRAM size to 64kB
- start IOU2

If you want to check, if an updated software is running fine with your problematic NVRAM, stop IOU2, copy back the saved nvram_00002, change back the NVRAM size to 256KB and then start IOU2.

**Comment by AJNOURI** [comment]
Hey @ehlers , sorry for the late reply.
Followed the steps you mentioned, the IOU now start successfully, though console stops right away.

> 2016-07-11 16:54:42 INFO vm.py:149 IOU2 has started
> 2016-07-11 16:54:42 DEBUG project.py:385 Event received: {'action': 'vm.started', 'event': {'console': 2006, 'startup_config': 'startup-config.cfg', 'iourc_path': '/home/ajn/iourc', 'path': 'i86bi-linux-l3-adventerprisek9-15.4.1T.bin', 'vm_id': '74c388f9-3ef2-4860-8fae-3f332bb6b1d6', 'ethernet_adapters': 2, 'private_config': None, 'serial_adapters': 2, 'l1_keepalives': False, 'md5sum': '2eabae17778316c49cbc80e8e81262f9', 'project_id': '7a54433d-441f-4f37-b24a-ef4d9495fa06', 'ram': 512, 'use_default_iou_values': False, 'nvram': 64, 'vm_directory': '/home/ajn/GNS3/projects/openstack-multinode/project-files/iou/74c388f9-3ef2-4860-8fae-3f332bb6b1d6', 'command_line': '/home/ajn/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-15.4.1T.bin -n 64 -m 512 -L 2', 'name': 'IOU2'}}
> 
> 2016-07-11 16:54:53 INFO telnet_console.py:97 Starting telnet console in thread "xfce4-terminal --tab -T "%d" -e "telnet %h %p""
> 2016-07-11 16:54:53 INFO telnet_console.py:82 Telnet console 127.0.0.1:2006 closed
> 

![screenshot - 110716 - 16 56 13](https://cloud.githubusercontent.com/assets/1716020/16735315/ea049b9a-4788-11e6-9054-be7e1d92df2b.png)

**Comment by ehlers** [comment]
I can't reproduce that.

I created a small project with 2 IOUs, for IOU2 set RAM=512 and NVRAM=256. Then started both IOUs, saved the NVRAM (wr), then stopped both.

Now I copied your nvram_00002 into the project directory of my IOU2 and extracted the startup-config.cfg . This should be a good copy of your environment.

When I now start IOU2 I get the initial error message "unknown nvram format". After changing the NVRAM size to 64k, IOU2 successfully starts.

> 2016-07-17 14:44:31 INFO vm.py:149 IOU2 has started
> 2016-07-17 14:44:31 DEBUG project.py:385 Event received: {'action': 'vm.started', 'event': {'private_config': None, 'vm_directory': '/opt/gns3/projects/cc66b67e-3475-449a-8894-29359494df95/project-files/iou/4aabf3bc-f2f4-4bdc-8940-4c0e5ab146c6', 'l1_keepalives': False, 'vm_id': '4aabf3bc-f2f4-4bdc-8940-4c0e5ab146c6', 'command_line': '/opt/gns3/images/IOU/i86bi-linux-l3-adventerprisek9-15.4.1T.bin -n 64 -m 512 -L 2', 'serial_adapters': 2, 'startup_config': 'startup-config.cfg', 'use_default_iou_values': False, 'project_id': 'cc66b67e-3475-449a-8894-29359494df95', 'console': 5001, 'path': 'i86bi-linux-l3-adventerprisek9-15.4.1T.bin', 'nvram': 64, 'iourc_path': '/home/gns3/.iourc', 'ram': 512, 'ethernet_adapters': 2, 'md5sum': '2eabae17778316c49cbc80e8e81262f9', 'name': 'IOU2'}}
> 2016-07-17 14:44:36 INFO telnet_console.py:97 Starting telnet console in thread "/usr/local/bin/run-iTerm "telnet %h %p" "%d""
> 2016-07-17 14:44:36 INFO telnet_console.py:82 Telnet console 192.168.1.99:5001 closed

You see, that for my telnet connection I also get the message, that it immediately closes. In my environment that's normal, as the script "start-iTerm" starts the real terminal emulator as a separate process and then terminates. In the real terminal session I see IOU2 running fine.

So I have no idea, what happens on your site and how to replicate it. @grossmj @noplay Any idea how to debug this?

**Comment by noplay** [comment]
@AJNOURI I'm not sure stuff was clear. The patch is not embed in 1.5.1 you need to apply it by hand (see @ehlers  comment).

**Comment by ehlers** [comment]
There seems some confusion:

When you change the NVRAM size, on the next start of this IOU the NVRAM is removed and then rebuild from startup-config.cfg (and optionally private-config.cfg). If you choose a NVRAM size < 128kB, e.g. 64 kB, you should be fine.

That's exactly what I proposed to @AJNOURI and what works fine for me. I'm also using the latest GNS3 version without my patch. But for @AJNOURI this workaround doesn't seem to work, the IOU starts, but he can't telnet into the console. At least that's what I understand.

**Comment by AJNOURI** [comment]
@noplay I have tested manually @ehlers instructions to reduce the nvram size. The image successfully starts but no telnet.
Cannot myself replicate the issue neither with another instance nor with another image not in another environement : (  
I just have conserved the router in question for eventual tests.

**Comment by grossmj** [comment]
@ehlers I think we can implement the patch in 2.0 (we will have a long testing period before we release it).
