### ISSUE TITLE
Packet Capture crashed IOU device 1.5 RC2

### ISSUE THREAD

**Issue by nrafia** [GNS3/gns3-server#595]
When i am capturing packets in 1.5 RC2, IOU devices, it will work 2/3 times and then it will crash the device, although all other devices (including other iou devices) will keep running. 
getting error Error: iouyap process has stopped, return code: -6

I am running my devices in GNS3 VM.

**Comment by grossmj** [comment]
Hi,

You should see a iouyap.log if you right click on the IOU node and choose "Show in File Manager". Can you post the content of that file after you get the error?

Thank you.

**Comment by nrafia** [comment]
Hi,
following are the contents of the IOUYap.log

`/usr/local/bin/iouyap: Parsing NETMAP...
/usr/local/bin/iouyap: --------------
/usr/local/bin/iouyap: Configuring 513:0/0...
/usr/local/bin/iouyap: starting foreign listener
/usr/local/bin/iouyap: --------------
/usr/local/bin/iouyap: Configuring 513:0/1...
/usr/local/bin/iouyap: starting foreign listener
/usr/local/bin/iouyap: --------------
/usr/local/bin/iouyap: Configuring 513:0/2...
/usr/local/bin/iouyap: starting foreign listener
/usr/local/bin/iouyap: --------------
/usr/local/bin/iouyap: Configuring 513:0/3...
/usr/local/bin/iouyap: starting foreign listener
/usr/local/bin/iouyap: --------------
/usr/local/bin/iouyap: Starting IOU UDS listener
/usr/local/bin/iouyap: Starting IOU UDP listener
/usr/local/bin/iouyap: Main thread going to sleep
/usr/local/bin/iouyap: Received signal 1
/usr/local/bin/iouyap: Stopping listeners and cleaning up
/usr/local/bin/iouyap: Reloading configuration because of SIGHUP
/usr/local/bin/iouyap: Parsing NETMAP...
*** Error in `/usr/local/bin/iouyap': free(): invalid next size (fast): 0x0000000000771470 ***
`

**Comment by grossmj** [comment]
Hi,

This is a bug with iouyap. I don't think we can fix it before we release a final version of 1.5 nor want to risk breaking iouyap.

We will probably use uBridge to connect IOU nodes in version 2.0.

**Comment by grossmj** [comment]
This should be fixed once we implement https://github.com/GNS3/gns3-server/issues/614

**Comment by grossmj** [comment]
The IOU implementation uses uBridge in 2.0, this fixes that issue.
