### ISSUE TITLE
[1.5.0] Invalid JSON: Additional properties are not allowed

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#597]
With labs containing docker containers.

![screenshot - 280616 - 02 47 38](https://cloud.githubusercontent.com/assets/1716020/16400380/0201d518-3cdb-11e6-9648-2075fe810f64.png)

> === GNS3 1.5.0dev6 traceback on 28 Jun 2016 00:44:11 ===
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev6-py3.4.egg/gns3/qt/__init__.py", line 206, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev6-py3.4.egg/gns3/http_client.py", line 737, in _processResponse
>     raise e
> gns3.http_client.HttpBadRequest: {
>     "message": "Invalid JSON: Additional properties are not allowed ('console_http_port', 'console_http_path', 'console_resolution' were unexpected) in schema: {\"properties\": {\"name\": {\"minLength\": 1, \"type\": \"string\", \"description\": \"Docker container name\"}, \"adapters\": {\"minimum\": 0, \"maximum\": 99, \"type\": [\"integer\", \"null\"], \"description\": \"number of adapters\"}, \"start_command\": {\"minLength\": 0, \"type\": [\"string\", \"null\"], \"description\": \"Docker CMD entry\"}, \"image\": {\"minLength\": 1, \"type\": \"string\", \"description\": \"Docker image name\"}, \"console_type\": {\"enum\": [\"telnet\", \"vnc\"], \"description\": \"console type\"}, \"environment\": {\"minLength\": 0, \"type\": [\"string\", \"null\"], \"description\": \"Docker environment\"}, \"console\": {\"maximum\": 65535, \"type\": [\"integer\", \"null\"], \"minimum\": 1, \"description\": \"console TCP port\"}, \"vm_id\": {\"pattern\": \"^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$\", \"minLength\": 36, \"type\": \"string\", \"maxLength\": 36, \"description\": \"Docker VM instance identifier\"}, \"aux\": {\"maximum\": 65535, \"type\": [\"integer\", \"null\"], \"minimum\": 1, \"description\": \"auxilary TCP port\"}}, \"$schema\": \"http://json-schema.org/draft-04/schema#\", \"additionalProperties\": false, \"type\": \"object\", \"description\": \"Request validation to create a new Docker container\"}",
>     "path": "/v1/projects/{project_id}/docker/vms",
>     "request": {
>         "adapters": 1,
>         "aux": 2009,
>         "console": 5900,
>         "console_http_path": "/",
>         "console_http_port": 80,
>         "console_resolution": "1024x768",
>         "console_type": "vnc",
>         "image": "ajnouri/firefox:latest",
>         "name": "ajnouri/firefox-1",
>         "vm_id": "2284cfca-ef23-4400-b66f-f633c52ef748"
>     },
>     "status": 400
> }

Exception file:
http://hpnouri.free.fr/misc/exceptions.log

**Comment by noplay** [comment]
You have an old server running (1.5.0dev1) you need to upgrade the server part

**Comment by AJNOURI** [comment]
OK, Thanks Julien.
