### ISSUE TITLE
A nat/internet node

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#599]
Often people use cloud to connect to the internet but configuration could be complex and depending of the computer.

My proposal is a node nat without any configuration from the topology. The target is to make it portable in  order to solve #590.

The configuration will be in the controller configuration with two parameter the compute and the interface. 

By default when the GNS3 VM is enable we can set it to vm and eth1. Or the VM could have a special tap interface with a dnsmasq server configured for serving it.

This will require a little more setup for linux user. And windows user without VM will not have access to it.

Perhaps we can call this node "internet" to make it more easier for new comers.

Ref #553

**Comment by noplay** [comment]
This could be a part of the builtins api like the ethernet switch.

**Comment by AJNOURI** [comment]
What about a Docker container running iptables and dnsmasq [https://github.com/AJNOURI/internet ](https://github.com/AJNOURI/internet )?
Need to connect to a cloud mapped to tap0 (tap0 part of a bridge along with the GNS3 VM or GNS3 host interface eth0)
Here is an example of lab:
[https://docs.google.com/document/d/1lHcCQ72_bEanVgBeF3ihYowdA-vJ9tBrRub_BirYrC8/edit?usp=sharing](https://docs.google.com/document/d/1lHcCQ72_bEanVgBeF3ihYowdA-vJ9tBrRub_BirYrC8/edit?usp=sharing)

With #603 there will be no need for bridging, the cloud will map directly to eth interface.

**Comment by noplay** [comment]
A docker container could work, but we create a hard dependency to docker. Not sure if it's a problem

**Comment by noplay** [comment]
In all case I think we need this node and in the controller we could experiment with multiple backend.

**Comment by grossmj** [comment]
I agree, we should have a built-in node for it. They we can change the way we access Internet without breaking user projects.

**Comment by noplay** [comment]
I will prepare this with the basic implementation: NAT node == GNS3 VM eth1

**Comment by noplay** [comment]
The way I plan to implement:
* nat is a new node_type
* it's a builtin like hub or switch
* no code change to controller
* all the code is in the compute with a new builtin class and a dedicated handler
* under the hood it will be a preconfigured cloud for the moment

I will stick as much as possible to the model of hub and switch because from the outside it's mostly the same. All the magic should be hide to users.

**Comment by grossmj** [comment]
Sounds good

**Comment by noplay** [comment]
Good news I found a solution to have a nat libvirt when installed offer a nat interface that we can use:
https://jamielinux.com/docs/libvirt-networking-handbook/nat-based-network.html

**Comment by grossmj** [comment]
We will need to document that.
