### ISSUE TITLE
[1.5.0]  Device still removed if one side is running

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#600]
Shouldn't allow removal of the conatiner until both containers on the link are stopped.

![screenshot - 010716 - 03 19 10](https://cloud.githubusercontent.com/assets/1716020/16509237/f2b3eb98-3f3a-11e6-8a32-67057fc3b228.png)

**Comment by noplay** [comment]
It's not present in 2.0 because we cleaned the system, but need a temporary fix in 1.5

**Comment by noplay** [comment]
Fixed by the hotlink I think
