### ISSUE TITLE
E: wrong-script-interpreter 

### ISSUE THREAD

**Issue by anubisg1** [GNS3/gns3-server#601]
gns3-server.noarch: E: wrong-script-interpreter (Badness: 533) /usr/lib/python3.5/site-packages/gns3server/modules/docker/resources/init.sh /gns3/bin/busybox

gns3-server.noarch: E: wrong-script-interpreter (Badness: 533) /usr/lib/python3.5/site-packages/gns3server/modules/docker/resources/etc/udhcpc/default.script /tmp/gns3/bin/sh

This script uses an incorrect interpreter. Correct interpreters should be an absolute path to a file in in /(s)bin or /usr/(s)bin. Alternatively, if the file isn't supposed to be executed, then don't mark it as executable.

**Comment by noplay** [comment]
How do you run this? 

It seem you try to run something designed to be run in a container.

**Comment by anubisg1** [comment]
opensuse build service.

trying to package as RPM gns3-server.

the point is that your scripts have as script headers things that aren't allowed. First of all the folder "/gns3" doesn't even exist.

i really don't know what you are trying to achieve but here is what you guys have on your scripts:

https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/docker/resources/init.sh

https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/docker/resources/etc/udhcpc/default.script

**Comment by anubisg1** [comment]
What happens is that RPM scans all the executable files (like those scripts) and generates dependencies based on the scripts headers as well as library dependencies ecc...

the script you have calls  /gns3/bin/busybox and  /tmp/gns3/bin/sh which obviously don't exist. The rpm generates them as dependencies.

**Comment by anubisg1** [comment]
also, the binary file "busybox" creates problems because is a pre-compiled binary that cannot be compiled on the system where gns3 is running

**Comment by noplay** [comment]
This scripts and busybox binaries are mounted in the docker container at startup. In this env the path will exists

**Comment by noplay** [comment]
Busybox is build using that:
https://github.com/GNS3/busybox/tree/gns3_build/gns3_build

**Comment by noplay** [comment]
Is it possible to not link this files to /bin ?

**Comment by anubisg1** [comment]
Busy box should either be built from sources or added as a dependency (using pre-built distro binaries). 

The scripts are easy to fix. They need to be installed without the Exec bit set ( -x )  to solve it. It can be done at packaging time hopefully not a problem for other packagers.

**Comment by noplay** [comment]
Problem for the busybox you need to compile it with the correct options.

You could use the config file to rebuild the busybox:
https://github.com/GNS3/busybox/blob/gns3_build/gns3_build/busyboxconfig#L53

It's important to have the correct path you can not use :
```
CONFIG_BUSYBOX_EXEC_PATH="/gns3/bin/busybox"
```

This should be keep in GNS3 ressource directory not installed on the system because user should have it in the $PATH we use it only inside docker containers to boostrap them, not in user system.

**Comment by anubisg1** [comment]
That's not a problem. If a specific configuration needs to happen, it can be handled at built time.

If we download the source code, busy box binary must be built from source.

**Comment by noplay** [comment]
Thanks for the feedback let's us know if you need more informations.
