### ISSUE TITLE
Docker connection to cloud instance not supported

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#603]
GNS3 version 1.5.1dev1 on Darwin (64-bit) with Python 3.5.1 Qt 5.6.0.
Docker and cloud instance are running in a (linux) GNS3 VM.

When connecting a docker instance to a cloud, GNS3 responds with a "not supported" message.
```
Server error from http://192.168.1.99:3080: alpine-1: NIO of type nio_generic_ethernet is not supported
Server error from http://192.168.1.99:3080: alpine-1: NIO of type nio_tap is not supported
```

Why is that not supported? I thought, that ubridge supports all those connection types.

**Comment by noplay** [comment]
Not sure but they doesn't seem supported in VMware also:
https://github.com/GNS3/gns3-server/blob/master/gns3server/handlers/api/vmware_handler.py#L274

**Comment by ehlers** [comment]
TAP connection is working now, that's my favorite cloud connection. Many thanks for that. But nio_generic_ethernet is still not implemented. Any plans for that?

**Comment by grossmj** [comment]
This will be supported in 2.0, hopefully in the meantime you can do everything with a TAP connection ;)

**Comment by ehlers** [comment]
Yes, I'm happy with TAP.
