### ISSUE TITLE
Integrated commentary/help/readme to the lab

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#606]
Often I need to take notes about a lab (some action to take or explanations) outside of gns3 and save the file in the project directory.
This can be very useful to me or to other (when exporting) to remember why, how and what actions to take.
Can we add an integrated commentary/help/readme to the lab, that can be edited by an external editor of choice (to be set in the settings) so we can just invoke it to see inf. about the lab?

**Comment by noplay** [comment]
It's so much documented than even you don't know about it :P But after testing it seem broken.

https://github.com/GNS3/gns3-gui/issues/1316
