### ISSUE TITLE
Permission error when deleting container

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#607]
Doesn't seem to affect other projects, only this specific container:

> 2016-07-04 12:56:33 DEBUG device.py:139 SW1 has deleted a NIO: {}
> 2016-07-04 12:56:34 INFO http_client.py:680 Response error: Error downloading http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/adc15a03-f5df-44f8-a05c-f198d29a88d1/docker/vms/48b997c2-73c2-4873-b6eb-a34cb32eb3ca - server replied: Internal Server Error (error: 401)
> 2016-07-04 12:56:34 DEBUG http_client.py:703 {
>     "message": "Could not delete the VM working directory: [Errno 1] Operation not permitted: '/home/ajn/GNS3/projects/internet-container/project-files/docker/48b997c2-73c2-4873-b6eb-a34cb32eb3ca/data/nat.sh'",
>     "status": 500
> }
> 2016-07-04 12:56:34 ERROR vm.py:119 error while deleting ajnouri/internet-1: Could not delete the VM working directory: [Errno 1] Operation not permitted: '/home/ajn/GNS3/projects/internet-container/project-files/docker/48b997c2-73c2-4873-b6eb-a34cb32eb3ca/data/nat.sh'
> 2016-07-04 12:56:34 INFO vm.py:121 ajnouri/internet-1 has been deleted
> Segmentation fault

**ls -l /home/ajn/GNS3/projects/internet-container/project-files/docker/48b997c2-73c2-4873-b6eb-a34cb32eb3ca/data/nat.sh**
> -rw-r--r-- 1 root root 410 Jun 22 16:04 /home/ajn/GNS3/projects/internet-container/project-files/docker/48b997c2-73c2-4873-b6eb-a34cb32eb3ca/data/nat.sh

Here is the exported project without the cloud:
[(http://hpnouri.free.fr/misc/internet.gns3project](http://hpnouri.free.fr/misc/internet.gns3project)

**Comment by noplay** [comment]
If you start and stop the container does it fix the issue?

**Comment by AJNOURI** [comment]
It doesn't, same behavior.

**Comment by AJNOURI** [comment]
$ gns3server --version
1.5.0
$ gns3 --version
1.5.0

Subsequent labs using the same image doesn't show any issue. 
Maybe we could close it, if nobody else having this issue.

**Comment by noplay** [comment]
Closed until we found a better way to reproduce

Thanks

**Comment by marcobox** [comment]
Hi. I had a similar problem in the past and I think I know the reason: when you create a file with root as owner inside the container, and place it in a folder shared with the host system (for example in case of GNS3 using a docker volume), the file will keeps his attributes (including the owner).
After you try to delete the container you cannot delete the files that you do not own and that raises the exception.

**Comment by noplay** [comment]
When we close the container we change the permission to the GNS3 owner:
https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/docker/docker_vm.py#L406

This should solve the problem.
