### ISSUE TITLE
Ethernet Switches in portable projects should be imported back into the VM

### ISSUE THREAD

**Issue by ddompe** [GNS3/gns3-server#609]
Hi,

I'm trying to use some portable projects that have some containers and also ethernet switches (UML). The current code: https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/project.py#L645 seems to import certain elements on the local node and others on the VM. Or I'm missing something?

**Comment by noplay** [comment]
Yes current code import all dynamips stuff on the local server. Because most people use dynamips locally. And it's allow for this kind of user to import without the need to setup the GNS3 VM.

We could improve that, but in 2.0 you will not have to care about where it's running.
