### ISSUE TITLE
user behind NAT, when using remote server, cause unidirectional communication

### ISSUE THREAD

**Issue by anubisg1** [GNS3/gns3-server#61]
Scenario:

Typical home user, computer assigned rfc 1918 ip address and internet reachability is achieved by NAT on provider's home router. For this example, home user has ip 192.168.0.1 natted to 32.32.32.32

192.168.0.1 <--> 32.32.32.32

Home user is running GNS3 gui.

A remote GNS3-Server is being used, the server exist somewhere on the internet.

remote server for this example has ip address 123.1.2.3

If the user connects a device running on a remote server, with a device running on a local server ( for example an ethernet switch/hub or frame-relay switch or any device that is running on the local server) , the NIO UDP is created.

in the direction LOCAL TO REMOTE, since we are behind NAT and we use the server outside global ip address we have reachability. the local UDP tunnel infact points to 123.1.2.3

This unidirectional communication is achieved without problems.

on the remote side instead, the tunnel is created to the inside local (192.168.0.1) ip address, therefore this traffic flow is lost.

the remote server, has no reachability to 192.168.0.1. the server should build the tunnel to the outside global ip address of the gui user (32.32.32.32).

This present a complex and not easy problem to solve.

Nodes behind a NAT are only reachable through the NAT's public address and in most cases only after the appropriate mapping state is set up in the NAT.  A NAT traversal mechanism or other means, is needed to make gns3 components communicate when a NAT exist somewhere..

first of all we need to be sure we use the outside global ip address, and we can do this by comparing the local server "\GET version and IP" with the remote one ..

this is very long and requires a lot of thoughts and a much more deep discussion

**Comment by anubisg1** [comment]
Any thoughts or work done about this ?

**Comment by noplay** [comment]
A part of the cloud support is enabling communication via ssh tunnels. Perhaps it will solve a part of this issue. But it's need a deeper reflexion and testing.

**Comment by noplay** [comment]
With the 1.4 actually we have script for setup a VPN I think it's the correct way to support nat.

**Comment by grossmj** [comment]
Agreed, VPN would be the only practical way I think

**Comment by noplay** [comment]
We can close that.
