### ISSUE TITLE
import/export: GNS3 cannot import a renamed image from the original host.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#610]
When creating new Docker template,  if I change the image name and export the corresponding lab, 

![screenshot - 050716 - 14 20 34](https://cloud.githubusercontent.com/assets/1716020/16584459/7b0929fc-42bc-11e6-931c-eb0ffcc1c024.png)

the original image name is lost and the new gns3 host importing the project doesn't recognize the image

![screenshot - 050716 - 14 21 58](https://cloud.githubusercontent.com/assets/1716020/16584468/86d0c7fe-42bc-11e6-80de-ae6775991c83.png)

Is there a way to keep inf. about the original image name, so the destination host can read and pull it?

**Comment by noplay** [comment]
I don't replicate your issue.

* You create a template with a image ajnouri/internet
*  You name the template dvpc
*  You use the template in a topology
*  You export
*  You import
*  GNS3 try to import the wrong image (work for me)

Can you test with the last source? (Use the master branch)

Thanks a lot

**Comment by AJNOURI** [comment]
**1.5.2dev1**

Same steps you mentioned with this new project:
![screenshot - 110716 - 16 26 05](https://cloud.githubusercontent.com/assets/1716020/16734013/302a2c0c-4784-11e6-8cec-86aab9ff5461.png)

> 
> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.2dev1-py3.4.egg/gns3/main_window.py", line 1701, in _exportProjectActionSlot
>     f.write(text.encode("utf-8"))
> TypeError: must be str, not bytes
> 
> /usr/local/lib/python3.4/dist-packages/raven/conf/remote.py:67: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
>   warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
> 2016-07-11 16:23:16 DEBUG base.py:230 Configuring Raven for host: <raven.conf.remote.RemoteConfig object at 0x7fe9d59e04a8>
> 2016-07-11 16:23:16 DEBUG base.py:669 Sending message of length 1248 to https://app.getsentry.com/api/38506/store/
> 2016-07-11 16:23:17 INFO crash_report.py:105 Crash report sent with event ID: 36bffe1286c949599015171b7da48051
>
