### ISSUE TITLE
[1.5.2dev1] GNS3 crash when deleting cloud 

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#613]
**Environment**
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.5 (jessie)
Release:	8.5
Codename:	jessie
No GNS3 VM

**Steps**
1- Opened a project with cloud mapped to eth0.
2- from gns3 host created ovs switch and added eth0 and tap0 to the bridge.
3- GNS3 crash when trying to delete the cloud.

> 2016-07-08 10:12:11 INFO link.py:141 deleting link from Cloud 5 nio_gen_eth:eth0 to SW1 1
> 2016-07-08 10:12:11 DEBUG device.py:120 SW1 is deleting an NIO
> 2016-07-08 10:12:11 DEBUG http_client.py:576 DELETE http://127.0.0.1:8000/v1/projects/c6e26ecc-7437-4730-bc7a-2069063f96ac/dynamips/devices/84edc5c3-0c4b-4c46-8723-b1ddaec4e90e/ports/1/nio {}
> 2016-07-08 10:12:11 DEBUG device.py:73 SW1 is being deleted
> 2016-07-08 10:12:11 INFO link.py:141 deleting link from SW1 3 to ajnouri/internet:1.1-1 eth1
> 2016-07-08 10:12:11 DEBUG device.py:120 SW1 is deleting an NIO
> 2016-07-08 10:12:11 DEBUG http_client.py:576 DELETE http://127.0.0.1:8000/v1/projects/c6e26ecc-7437-4730-bc7a-2069063f96ac/dynamips/devices/84edc5c3-0c4b-4c46-8723-b1ddaec4e90e/ports/3/nio {}
> 2016-07-08 10:12:11 DEBUG vm.py:299 ajnouri/internet:1.1-1 is deleting an NIO
> 2016-07-08 10:12:11 DEBUG http_client.py:576 DELETE http://127.0.0.1:8000/v1/projects/c6e26ecc-7437-4730-bc7a-2069063f96ac/docker/vms/abec598a-8175-43fe-99e4-f8d25f56c042/adapters/1/ports/0/nio {}
> 2016-07-08 10:12:11 DEBUG http_client.py:576 DELETE http://127.0.0.1:8000/v1/projects/c6e26ecc-7437-4730-bc7a-2069063f96ac/dynamips/devices/84edc5c3-0c4b-4c46-8723-b1ddaec4e90e {}
> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007f04bbc26700 (most recent call first):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.2dev1-py3.4.egg/gns3/main.py", line 262 in main
>   File "/usr/local/bin/gns3", line 9 in <module>
> Segmentation fault
>

**Comment by noplay** [comment]
You can reproduce it each time?

**Comment by AJNOURI** [comment]
Cannot reproduce it neither on the same machine (Debian Jessie) nor on a new Ubuntu 16.04
: (
Not sure if it is specific to my machine environment.
Should I report such bugs, which I cannot reproduce? Or only reproducible ones?
I don't want to clutter the issue section.
