### ISSUE TITLE
Use uBridge for IOL

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#614]
Use uBridge 0.9.5 once it is released. Also, waiting on https://github.com/GNS3/gns3-gui/issues/1298

**Comment by taurus8** [comment]
Is it possible to merge iouyap into ubridge ? for current IOU images 
will this have any advantages ?

**Comment by grossmj** [comment]
The dev version of uBridge can replace iouyap however this hasn't been tested yet in GNS3. Main advantage is we can concentrate on just one tool for all connections + I know there are some bugs in iouyap which would be difficult to fix and by using uBridge we don't have to.

**Comment by taurus8** [comment]
Cool, but why do you wait for new IOL images from VIRL?
why dnot you implement this for current IOU images ?

**Comment by taurus8** [comment]
One Question Sir, 
Will iou be running without iouyap ? or we must compile iouyap too ?

**Comment by grossmj** [comment]
You will not need iouyap anymore.
