### ISSUE TITLE
[v1.5.2dev1] Error while saving the project (save as)

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#616]
![screenshot - 110716 - 16 32 59](https://cloud.githubusercontent.com/assets/1716020/16734256/269d1ffe-4785-11e6-8140-15a64219e4bc.png)

> Could not copy file to /home/ajn/GNS3/projects/export/project-files/docker/89368e1e-9cc5-4593-ac0a-c74b20cb30d1/etc/openvswitch/.conf.db.~lock~: [Errno 13] Permission denied: '/home/ajn/GNS3/projects/untitled/project-files/docker/89368e1e-9cc5-4593-ac0a-c74b20cb30d1/etc/openvswitch/.conf.db.~lock~'

**ls -l /home/ajn/GNS3/projects/untitled/project-files/docker/89368e1e-9cc5-4593-ac0a-c74b20cb30d1/etc/openvswitch/.conf.db.~lock~**

> -rw------- 1 root root 0 May 28 02:51 /home/ajn/GNS3/projects/untitled/project-files/docker/89368e1e-9cc5-4593-ac0a-c74b20cb30d1/etc/openvswitch/.conf.db.~lock~

Note the project doesn't container openvswitch container!

---------

Open another project (with openvswitch container) as tried to "save as"

![screenshot - 110716 - 16 36 09](https://cloud.githubusercontent.com/assets/1716020/16734368/95620e36-4785-11e6-96c8-aa12e4b8c68a.png)

> Could not copy file to /home/ajn/GNS3/projects/save-as/project-files/docker/25b2c344-8d03-4799-b72b-f00ce9007fa3/root/.mozilla/firefox/jojpfaf8.default/lock: [Errno 2] No such file or directory: '/home/ajn/GNS3/projects/internet2/project-files/docker/25b2c344-8d03-4799-b72b-f00ce9007fa3/root/.mozilla/firefox/jojpfaf8.default/lock'

**ls -l /home/ajn/GNS3/projects/internet2/project-files/docker/25b2c344-8d03-4799-b72b-f00ce9007fa3/root/.mozilla/firefox/jojpfaf8.default/lock**
> lrwxrwxrwx 1 ajn ajn 13 Jul  8 19:48 /home/ajn/GNS3/projects/internet2/project-files/docker/25b2c344-8d03-4799-b72b-f00ce9007fa3/root/.mozilla/firefox/jojpfaf8.default/lock -> 127.0.1.1:+52
> 

--------

Nevertheless, each time, the project was saved as a new one

**Comment by noplay** [comment]
Do you have the last gui code? Because the exception at line 1701 should already be solved

For the /home/ajn/GNS3/projects/untitled/project-files/docker/89368e1e-9cc5-4593-ac0a-c74b20cb30d1/etc/openvswitch/.conf.db.~lock~

It's probably and old test you have done and you have files with invalid permissions in your folder you need to clean it by hand.

The file:
/home/ajn/GNS3/projects/internet2/project-files/docker/25b2c344-8d03-4799-b72b-f00ce9007fa3/root/.mozilla/firefox/jojpfaf8.default/lock

Is weird because it's linked to an IP

**Comment by AJNOURI** [comment]
The second project was created with a prior version (not sure which), but the first project was created under v1.5.2dev1

**Comment by noplay** [comment]
When you overwite a project we are not erasing the folder. You can have file from project in your untiled project.

I don't see how we can fix the second because the file is link to a non existing location. The only way I see for fixing that is to just display a warning

**Comment by noplay** [comment]
A warning is display
