### ISSUE TITLE
[v1.5.2dev1] GNS3 crash when trying to delete a stopped container

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#617]
GNS3 crash when trying to delete a stopped container, connected to another running one (openvswitch)

> 2016-07-11 17:13:09 DEBUG vm.py:216 ajnouri/firefox-1 is stopping
> 2016-07-11 17:13:09 DEBUG http_client.py:576 POST http://127.0.0.1:8000/v1/projects/7a54433d-441f-4f37-b24a-ef4d9495fa06/docker/vms/2284cfca-ef23-4400-b66f-f633c52ef748/stop {}
> sh: can't create /etc/network/.gns3_perms: Permission denied
> 2016-07-11 17:13:12 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 26.1, 'cpu_usage_percent': 31.2}}
> 2016-07-11 17:13:15 DEBUG http_client.py:711 Decoding response from http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/7a54433d-441f-4f37-b24a-ef4d9495fa06/docker/vms/2284cfca-ef23-4400-b66f-f633c52ef748/stop response 204
> 2016-07-11 17:13:15 DEBUG http_client.py:718 
> 2016-07-11 17:13:15 INFO vm.py:234 ajnouri/firefox-1 has stopped
> 2016-07-11 17:13:16 DEBUG project.py:385 Event received: {'action': 'vm.stopped', 'event': {'console': 5900, 'console_http_port': 80, 'environment': None, 'start_command': None, 'console_type': 'vnc', 'container_id': 'f9601d907361ea0fdc9aea41bdfe9d4b7ad762af10e66d8345b7bac0fe64528f', 'console_resolution': '1024x768', 'vm_id': '2284cfca-ef23-4400-b66f-f633c52ef748', 'console_http_path': '/', 'image': 'ajnouri/firefox:latest', 'project_id': '7a54433d-441f-4f37-b24a-ef4d9495fa06', 'vm_directory': '/home/ajn/GNS3/projects/openstack-multinode/project-files/docker/2284cfca-ef23-4400-b66f-f633c52ef748', 'aux': 2009, 'adapters': 1, 'name': 'ajnouri/firefox-1'}}
> 2016-07-11 17:13:21 DEBUG project.py:385 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 25.4, 'cpu_usage_percent': 21.3}}
> 2016-07-11 17:13:23 DEBUG vm.py:101 ajnouri/firefox-1 is being deleted
> 2016-07-11 17:13:23 INFO link.py:141 deleting link from gns3/openvswitch-2 Ethernet6 to ajnouri/firefox-1 eth0
> 2016-07-11 17:13:23 DEBUG vm.py:299 gns3/openvswitch-2 is deleting an NIO
> 2016-07-11 17:13:23 DEBUG http_client.py:576 DELETE http://127.0.0.1:8000/v1/projects/7a54433d-441f-4f37-b24a-ef4d9495fa06/docker/vms/f1db60cb-d025-4a45-b1c1-2b7c2d730eb4/adapters/6/ports/0/nio {}
> 2016-07-11 17:13:23 DEBUG vm.py:299 ajnouri/firefox-1 is deleting an NIO
> 2016-07-11 17:13:23 DEBUG http_client.py:576 DELETE http://127.0.0.1:8000/v1/projects/7a54433d-441f-4f37-b24a-ef4d9495fa06/docker/vms/2284cfca-ef23-4400-b66f-f633c52ef748/adapters/0/ports/0/nio {}
> 2016-07-11 17:13:23 DEBUG http_client.py:576 DELETE http://127.0.0.1:8000/v1/projects/7a54433d-441f-4f37-b24a-ef4d9495fa06/docker/vms/2284cfca-ef23-4400-b66f-f633c52ef748 {}
> caught signal: 15
> 2016-07-11 17:13:23 DEBUG http_client.py:711 Decoding response from http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/7a54433d-441f-4f37-b24a-ef4d9495fa06/docker/vms/2284cfca-ef23-4400-b66f-f633c52ef748/adapters/0/ports/0/nio response 204
> 2016-07-11 17:13:23 DEBUG http_client.py:718 
> 2016-07-11 17:13:23 DEBUG vm.py:320 ajnouri/firefox-1 has deleted a NIO: {}
> 2016-07-11 17:13:23 DEBUG http_client.py:711 Decoding response from http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/7a54433d-441f-4f37-b24a-ef4d9495fa06/docker/vms/f1db60cb-d025-4a45-b1c1-2b7c2d730eb4/adapters/6/ports/0/nio response 204
> 2016-07-11 17:13:23 DEBUG http_client.py:718 
> 2016-07-11 17:13:23 DEBUG vm.py:320 gns3/openvswitch-2 has deleted a NIO: {}
> 2016-07-11 17:13:24 DEBUG http_client.py:711 Decoding response from http://7BTEI9n5zl5UyPjPhiOysLdNxbL3sp7v7QQOH8qDG4xPHAbvAqSzRxt8LS4n0cbl@127.0.0.1:8000/v1/projects/7a54433d-441f-4f37-b24a-ef4d9495fa06/docker/vms/2284cfca-ef23-4400-b66f-f633c52ef748 response 204
> 2016-07-11 17:13:24 DEBUG http_client.py:718 
> 2016-07-11 17:13:24 INFO vm.py:121 ajnouri/firefox-1 has been deleted
> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007fea0b978700 (most recent call first):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.2dev1-py3.4.egg/gns3/main.py", line 262 in main
>   File "/usr/local/bin/gns3", line 9 in <module>
> Segmentation fault
> 

Subsequent open of the same project, the container in question has been deleted successfully, but I got this when starting devices:

> 2016-07-11 17:20:19 DEBUG project.py:385 Event received: {'action': 'log.error', 'event': {'message': 'iouyap process has stopped, return code: 1\nnetio error: sock lock: Address already in use\r\n'}}
> 2016-07-11 17:20:19 ERROR project.py:396 iouyap process has stopped, return code: 1
> netio error: sock lock: Address already in use
> 
> Error: iouyap process has stopped, return code: 1
> netio error: sock lock: Address already in use
>

**Comment by noplay** [comment]
Perhaps related to https://github.com/gns3/gns3-gui/issues/1374
