### ISSUE TITLE
Each time we close a project VBoxManage is called

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#627]
```
2016-07-21 18:35:48 INFO __init__.py:96 Executing VBoxManage with command: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage --nologo list hdds
```

Not a real problem, it's slow down the close process.

It's also in 1.5

**Comment by ehlers** [comment]
That was likely introduced to solve https://github.com/GNS3/gns3-server/issues/145. It's perhaps better to do this cleanup, when a virtualbox VM is deleted.

**Comment by noplay** [comment]
Or detect if Vbox is used in this project

**Comment by noplay** [comment]
Thanks for the issue number will be usefull

**Comment by noplay** [comment]
Fixed I have added an optim to not call the project_close of a module if the module is not use for the project.
