### ISSUE TITLE
WARNING __init__.py:99 Running GNS3 as root is not recommended and could be dangerous

### ISSUE THREAD

**Issue by liangzhuo9** [GNS3/gns3-server#629]
sudo /Applications/GNS3.app/Contents/MacOS/gns3

WARNING __init__.py:99 Running GNS3 as root is not recommended and could be dangerous

**Comment by noplay** [comment]
Hi,

You should not run GNS3 as root. It's not recommended and create issues with VMware and Virtualbox.
