### ISSUE TITLE
[1.5.1] gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: 500

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-server#631]
When trying to run a docker container I get the following traceback and error below;

> 2016-08-03 01:24:24 ERROR route.py:189 VM error detected: <class 'gns3server.modules.docker.docker_error.DockerError'>
> Traceback (most recent call last):
>   File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/web/route.py", line 179, in control_schema
>     yield from func(request, response)
>   File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/handlers/api/docker_handler.py", line 109, in start
>     yield from container.start()
>   File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/modules/docker/docker_vm.py", line 343, in start
>     result = yield from self.manager.query("POST", "containers/{}/start".format(self._cid))
>   File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/modules/docker/__init__.py", line 85, in query
>     response = yield from self.http_query(method, path, data=data, params=params)
>   File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/modules/docker/__init__.py", line 131, in http_query
>     raise DockerError("Docker has returned an error: {} {}".format(response.status, body))
> gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: 500 b'Container command could not be invoked.\n'
> 2016-08-03 01:24:24 INFO helpers.py:365 10.0.91.250 - - [03/Aug/2016:01:24:24 +0000] "POST /v1/projects/92e9e80e-0463-4a2f-b73c-9ee442c15bfe/docker/vms/8c824e06-8065-4b9c-add4-b89fec024a24/start HTTP/1.1" 409 119 "-" "GNS3 QT Client v1.5.1"

**Comment by gcasella** [comment]
I also get this error as well sometimes;

> 2016-08-03 03:14:36 ERROR route.py:189 VM error detected: <class 'gns3server.modules.docker.docker_error.DockerError'>
Traceback (most recent call last):
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/web/route.py", line 179, in control_schema
    yield from func(request, response)
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/handlers/api/docker_handler.py", line 109, in start
    yield from container.start()
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/modules/docker/docker_vm.py", line 343, in start
    result = yield from self.manager.query("POST", "containers/{}/start".format(self._cid))
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/modules/docker/__init__.py", line 131, in http_query
    raise DockerError("Docker has returned an error: {} {}".format(response.status, body))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: 500 b'Container command not found or does not exist.\n'

**Comment by noplay** [comment]
Do you have this with any containers? Because from the Docker documentation it seem the container try to start with a command that doesn't exist in the container.

**Comment by noplay** [comment]
From my test I can't reproduce it's the container that is broken/corrupt and it's normal that docker raise an error. Please comment if you have the problem with any containers and if it's work outside GNS3.
