### ISSUE TITLE
Sample systemd scripts should start with --controller

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#645]
To simplify life of people deploying GNS3 as a central server.

Or we should be able to detect in the client that a remote server is not a controller when someone try to use it as a controller.

**Comment by noplay** [comment]
Perhaps we should always enable the controller this will avoid complex configuration depending of the use case.

**Comment by grossmj** [comment]
:+1: but let's make sure we don't have any unexpected problems before.

**Comment by noplay** [comment]
I see no impact to always enable the controller. I will test

**Comment by noplay** [comment]
No problem to always enable controller
