### ISSUE TITLE
Traceback with VirtualBox and GNS3 1.2.3

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-server#65]
I have Virtual Box installed on CentOS 7.X, and have GNS installed on Windows.
My setup.

Windows 8.1 (GNS3 Client ONLY)
CentOS 7.X (GNS3 Server ONLY)

When try to view the list of VM's i get the following traceback 

Jan 30 15:29:38 gns3-iouvm gns3server: [E 150130 15:29:38 base:278] uncaught exception <class 'AttributeError'>
Jan 30 15:29:38 gns3-iouvm gns3server: Traceback (most recent call last):
Jan 30 15:29:38 gns3-iouvm gns3server: File "/usr/local/lib/python3.4/site-packages/gns3_server-1.2.3-py3.4.egg/gns3server/modules/base.py", line 276, in _decode_request
Jan 30 15:29:38 gns3-iouvm gns3server: self.modules[self.name][destination](self, params)
Jan 30 15:29:38 gns3-iouvm gns3server: File "/usr/local/lib/python3.4/site-packages/gns3_server-1.2.3-py3.4.egg/gns3server/modules/virtualbox/__init__.py", line 765, in vm_list
Jan 30 15:29:38 gns3-iouvm gns3server: result = self._execute_vboxmanage(vbox_user, command)
Jan 30 15:29:38 gns3-iouvm gns3server: File "/usr/local/lib/python3.4/site-packages/gns3_server-1.2.3-py3.4.egg/gns3server/modules/virtualbox/__init__.py", line 730, in _execute_vboxmanage
Jan 30 15:29:38 gns3-iouvm gns3server: if not user.strip() or sys.platform.startswith("win"):
Jan 30 15:29:38 gns3-iouvm gns3server: AttributeError: 'NoneType' object has no attribute 'strip'
Jan 30 15:29:38 gns3-iouvm gns3server: [I 150130 15:29:38 base:219] ZeroMQ client (virtualbox) sending JSON-RPC custom error: uncaught exception <class 'AttributeError'>: 'NoneType' object has no attribute 'strip'
Jan 30 15:29:38 gns3-iouvm gns3server: Traceback (most recent call last):
Jan 30 15:29:38 gns3-iouvm gns3server: File "/usr/local/lib/python3.4/site-packages/gns3_server-1.2.3-py3.4.egg/gns3server/modules/base.py", line 276, in _decode_request
Jan 30 15:29:38 gns3-iouvm gns3server: self.modules[self.name][destination](self, params)
Jan 30 15:29:38 gns3-iouvm gns3server: File "/usr/local/lib/python3.4/site-packages/gns3_server-1.2.3-py3.4.egg/gns3server/modules/virtualbox/__init__.py", line 765, in vm_list
Jan 30 15:29:38 gns3-iouvm gns3server: result = self._execute_vboxmanage(vbox_user, command)
Jan 30 15:29:38 gns3-iouvm gns3server: File "/usr/local/lib/python3.4/site-packages/gns3_server-1.2.3-py3.4.egg/gns3server/modules/virtualbox/__init__.py", line 730, in _execute_vboxmanage
Jan 30 15:29:38 gns3-iouvm gns3server: if not user.strip() or sys.platform.startswith("win"):
Jan 30 15:29:38 gns3-iouvm gns3server: AttributeError: 'NoneType' object has no attribute 'strip'
Jan 30 15:29:38 gns3-iouvm gns3server: for call id 8cc68aaf-6ec7-4051-a83e-9b05e2a9f8c4

**Comment by noplay** [comment]
It should be fixed. But it's not possible to run VirtualBox inside the gns3-iouvm
