### ISSUE TITLE
shutil.which is not always use for dynamips path and not correctly used for iouyap

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#655]
https://github.com/GNS3/gns3-server/commit/e481ffa94c3bc6fcdf85019f8128b38b27d14b1a#commitcomment-18803303

**Comment by ehlers** [comment]
ubridge_path and vpcs_path are behaving the same as iouyap_path, so all xxx_path variables should be changed.

**Comment by noplay** [comment]
A little note about shutil.which if the path doesn't exists which return None preventing you to use the path later in a error message.

I will workaround that

**Comment by noplay** [comment]
Should be OK now thanks for the idea
