### ISSUE TITLE
1.5.2 - deleting running docker VM leads to leftover files

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#659]
GNS3 version 1.5.2 on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0, docker running in GNS3-VM.

When a running docker VM, that has already written some files into a persistent volume, is deleted without stopping it before, the files in the volume won't be deleted.

GNS3 shows the following error:
`Server error : Could not delete the VM working directory: [Errno 1] Operation not permitted: '/opt/gns3/projects/ef7293e6-5165-4718-a779-7b0ae96c8633/project-files/docker/ee2a25be-79a5-44c3-a5ad-557b064e4068/root'`

Most likely the script, that changes the user/group in the volume back to the GNS3 user is not run in this situation, the files are still owned by root. Therefore GNS3 can't delete those files and they will be leftovers.

**Comment by ehlers** [comment]
Just re-tested. It isn't that easy. I don't have the issue on telnet docker VMs. I can start a telnet VM, fill some data in the volume and then delete it without any issues.

But when I use a VNC VM, I tested it with gns3/webterm I have this issue. Even stopping the web browser and then deleting all data in the /root volume doesn't help.

**Comment by ehlers** [comment]
Starting gns3/xeyes, then deleting it works fine.

Then I created a xeyes VM with a volume:
```
FROM gns3/xeyes
VOLUME [ "/root" ]
```

Starting this docker image, then deleting it (no need to start the VNC console) results in this issue.
Starting this docker image, then stop it, then delete it, is fine.

Stopping the xeyes image takes some time (10 seconds), because it doesn't react on the signal of `docker stop`. Deleting a running xeyes image doesn't take that time. So it doesn't do a normal stop before deleting.

Then I created a CLI VM with a /root volume (`FROM alpine` / `VOLUME [ "/root" ]`).
When I start that, then delete it, it takes it's 10 seconds time and I've got no issue. This time the delete seems to do a normal stop.

**Comment by ehlers** [comment]
I assume the problem is, that during close/reset the x11vnc process is terminated first and then the permissions are fixed (in stop). When I reverse this sequence, the issue seems to be fixed.

```
diff --git a/gns3server/modules/docker/docker_vm.py b/gns3server/modules/docker/docker_vm.py
index 386d73e..c47d38d 100644
--- a/gns3server/modules/docker/docker_vm.py
+++ b/gns3server/modules/docker/docker_vm.py
@@ -577,6 +577,9 @@ class DockerVM(BaseVM):
     @asyncio.coroutine
     def reset(self):
         try:
+            state = yield from self._get_container_state()
+            if state == "paused" or state == "running":
+                yield from self.stop()
             if self.console_type == "vnc":
                 if self._x11vnc_process:
                     try:
@@ -589,9 +592,6 @@ class DockerVM(BaseVM):
                         yield from self._xvfb_process.wait()
                     except ProcessLookupError:
                         pass
-            state = yield from self._get_container_state()
-            if state == "paused" or state == "running":
-                yield from self.stop()
             # v – 1/True/true or 0/False/false, Remove the volumes associated to the container. Default false.
             # force - 1/True/true or 0/False/false, Kill then remove the container. Default false.
             yield from self.manager.query("DELETE", "containers/{}".format(self._cid), params={"force": 1, "v": 1})
```

**Comment by noplay** [comment]
Thanks I have merge your patch
