### ISSUE TITLE
When the gns3server startup with system boot via upstart scrip, the qemu only can use "-nographic"

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-server#66]
/etc/init/upstart-gns3server.conf:
-------------------------------------------------------------
description "GNS3 Server"

start on runlevel [2345]
stop on runlevel [!2345]
respawn

setuid wolfboy
exec /usr/local/bin/gns3server

-------------------------------------------------------------

when I did like above, the gns3server can startup with system boot. so we can use this for remote server.
but at this time ,when I want to use its local GNS3, if qemu without "-nographic", the qemu equipment can not start. and see the task manager of ubuntu , can see one process "qemu-system-x86" with nothing.
If use initctl stop upstart-gns3server to stop gns3server, then start GNS3 gui, the phenomenon disappeard. At this time we can see the SDL screen.
I don't know if it is a bug for sure.

**Comment by noplay** [comment]
When you start upstart at system boot the shell environment doesn't  contain the X servers (in the variable DISPLAY). that why it can't start.

Perhaps we can detect if we are on a nix system and if DISPLAY is not set in the environment and add the -nographics option.

**Comment by noplay** [comment]
Thanks for the report
