### ISSUE TITLE
i receive error when i install aiohttp==0.22.5 

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-server#663]
Hi 
![error](https://cloud.githubusercontent.com/assets/8465075/18164773/ec1861c2-7056-11e6-8b20-dbe02223378b.png)
i want to try gns3 2.0 as local in Ubuntu 16.04 qt  5.5.1 python 3.5
but i receive following  error

**Comment by taurus8** [comment]
![error 2](https://cloud.githubusercontent.com/assets/8465075/18164878/8a46e7ec-7057-11e6-8c3a-1a31162a3f4d.png)

**Comment by taurus8** [comment]
i have the same problem in gns3 1.5 when i install 
when i install aiohttp by sudo pip3.5 install aiohttp==0.21.5
everything works in gns3 1.5 
but i can not install sudo pip3.5 uninstall aiohttp==0.21.5 for 2.0

**Comment by noplay** [comment]
I don't have this issue.

What is the result of pip  freeze?

It seem you have the wrong version of multidict loaded (2.0 instead of 1.2.2)

**Comment by noplay** [comment]
For release of 2.0 we should move to aiohttp 1.0.0  it should fix the problem but it's not yet released

**Comment by taurus8** [comment]
THX it has been fixed by installing multidict 1.2.2
