### ISSUE TITLE
Sometimes i receive following error in console when i close GNS3 

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-server#673]
![errr](https://cloud.githubusercontent.com/assets/8465075/18344884/662c3570-75ce-11e6-8996-ef9433cb76e3.png)

**Comment by noplay** [comment]
It's fixe.

The problem was compute list when no project is opened is refreshed by a timer. If we shutdown the local server the timer is still running and could make a request before shutdown is over.

It's solved by adding a shutdown method to the http client preventing new requests.

**Comment by taurus8** [comment]
THX , you solve problems so fast :)

**Comment by noplay** [comment]
Thanks for all the report it's really help
