### ISSUE TITLE
GNS3 VM Timesout

### ISSUE THREAD

**Issue by Zen4rx** [GNS3/gns3-server#675]
Dear GNS3 Support.

I am having some issues with the installation of GNS3 1.5.2 and GNS3 VM.

To simplify the installation, I removed VmWorkstation and installed Vmware Player with the new VIX API. The API was downloaded from this link: https://www.vmware.com/support/developer/vix-api/.

I changed the path to the vmrun.exe: 
![vmrun](https://cloud.githubusercontent.com/assets/14910009/18411622/5accdb90-777b-11e6-884b-c8ef25163f9e.png)

I cleared the VMware interfaces as explained on the post above and then re-configured all of them.

![server-1](https://cloud.githubusercontent.com/assets/14910009/18411642/b9c64050-777b-11e6-8f49-176f54648f5a.png)
![server-2](https://cloud.githubusercontent.com/assets/14910009/18411643/bb911f5e-777b-11e6-8ed6-6f0fed6a567e.png)

I run the wizard, under the "help menu" and I select Vmware and the GNS3 VM available.

That's the result. It starts the virtual machine, but it gets stuck until the process is timed out after 60 seconds.

![tmp1](https://cloud.githubusercontent.com/assets/14910009/18411653/e88a774e-777b-11e6-9d2d-973c1d02c216.png)
![tmp2](https://cloud.githubusercontent.com/assets/14910009/18411654/ea71698c-777b-11e6-8192-f2664d5a76ec.png)

I was able for a few minutes to upload few IOU images, but after a while, the server times out and I receive error 500. Although, the IP of the machine 192.168.159.128 can be successfully pinged.

I would like to receive some help since I am really stuck at this stage.

Kind Regards.

**Comment by Zen4rx** [comment]
I experience the same issue even with other GNS3 versions. I just tried with 1.4.2 and I see the exact same problem. Unfortunately I do not understand how to fix it.

**Comment by noplay** [comment]
Does it work if you run the command that timeout from cli? vmrun returned after start of the VM?

**Comment by Zen4rx** [comment]
I need to check. I had to downgrade to GNS3 1.3.13 since I needed a working copy of IOU and I did not know how to fix this problem. I will update you as soon as possible.

Thank you very much for replying.

**Comment by Zen4rx** [comment]
Hi, gents. I still experiencing the same issue. I tried today to install 1.5.2 due to some limitations in IOU.

Can somebody help me to fix this problem?

**Comment by noplay** [comment]
Can you test running the command from a terminal?

**Comment by Zen4rx** [comment]
Hi, Julien.

I did try via the CLI. It works if I run with the right permissions. Basically I run the CLI as administrator.

**Comment by noplay** [comment]
You always run VMware as admin?

When you are not running it as admin you have an error in the console? 

Thanks for the help

**Comment by Zen4rx** [comment]
Hi, Julien.

The output error shown by the CLI if started without enough privileges is: "unknown error".

**Comment by noplay** [comment]
Is it your choice to run VMware as admin and not as a standard user?

In your Virtual Machines folder your user Pierfransisco has permission to edit the GNS3 VM folder content? Perhaps we can detect that the VM has been imported as admin and not has a standard user.

**Comment by Zen4rx** [comment]
Hi, Julien.

Yes. This user can edit any file contained in the "GNS3 VM" folder without UAC asking for any permission. I actually turned it off to avoid any issue. 

Is this you wanted to know?

**Comment by noplay** [comment]
Yes

And do you know why you need to run VMware as admin? 

Thanks for the informations I have seen this error multiple times but never found the root cause. Now we know why and we can find a workaround or display a warning.

**Comment by Zen4rx** [comment]
The account I am using is the main account and the administrator. 

Would you mind to show the permission level you have set on your Vmware folder?

Kind Regards.

**Comment by Zen4rx** [comment]
Hi, Julien.

Should I shoot a video?

**Comment by noplay** [comment]
No need thanks

**Comment by Zen4rx** [comment]
Any advice to fix it? I am a bit stuck.

**Comment by noplay** [comment]
Run GNS3 as admin :(

**Comment by Zen4rx** [comment]
I do run GNS3 as admin.

**Comment by noplay** [comment]
And if you don't run GNS3 as admin it's work?

**Comment by Zen4rx** [comment]
Hi, Julien.

I do not what change on my Windows 8.1 machine, after some Microsoft updates. I tried the installation of GNS3 1.5.2 and it does work fine.

Can you please spend a bit of time to find out what's the issue that causes this problem?

I will give you all the information is required.

Kind Regards.

**Comment by noplay** [comment]
We rewrote that part in 2.0 I hope we solve the issue
