### ISSUE TITLE
GNS3 server http://127.0.0.1:3080 issue

### ISSUE THREAD

**Issue by JKKY** [GNS3/gns3-server#679]
Hi, I am having issue on GNS3 which always giving me the error to connect 127:0.0.1:3080. I am using GMS3 v 1.5.2 and VMWare Workstation 12.5.0. Hope anyone can help me.

**Comment by noplay** [comment]
For user support you need to ask this on:
http://gns3.com/community

Your problem is probably due to an antivirus. Test also to run GNS3 doctor via Help / GNS3 doctor

Here is the place for bug reports.
