### ISSUE TITLE
NAT node seem broken

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#686]

**Comment by noplay** [comment]
I fix an issue but I still have no IP

**Comment by noplay** [comment]
Even in the cloud the virbr0 seem to not work

**Comment by noplay** [comment]
The way to solve this:
* create a tap nat0
* add the tap to the virbr0

**Comment by noplay** [comment]
I made a PR to ubridge to add a command à la brctl to add the interface

**Comment by grossmj** [comment]
PR fixes the issue :+1:
