### ISSUE TITLE
Import of 1.2 IOU projects doesn't work in 1.3dev1

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#69]
The initial-config and nvram files are not copied.

**Comment by noplay** [comment]
It should be fixed, but i can't test because i'm on a mac and use only the remote server for iou. Can you check? Otherwise i will setup a VM with the full env for test.

**Comment by grossmj** [comment]
I'll test and let you know.

**Comment by grossmj** [comment]
This has been fixed :)

**Comment by noplay** [comment]
:+1:
