### ISSUE TITLE
Container name : change "/" with another symbol

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#695]
Looks like sometimes, the slash symbol in the default proposed container name, which is the image name, causes some recuring issues:
We could replace the slash with a dash. What do you think?
![selection_433](https://cloud.githubusercontent.com/assets/1716020/18954784/c566b2c2-8654-11e6-9e8d-dbd58a2e8648.png)

**Comment by noplay** [comment]
Did you try with:
https://github.com/GNS3/gns3-gui/commit/ac8ef05b06b0d2a2e8dad6973df77d7e829b0268

Should fix your issue but not yet released

**Comment by AJNOURI** [comment]
Nice! Thanks Julien.
