### ISSUE TITLE
[2.0.0a1] Error Transfering /qemu/binaries -- server replied: Not Found

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-server#696]
Hey Folks,

Playing around with GNS3 version 2.0 Alpha and got this error below when trying to look through my settings in the GNS3 client.

=> Error transferring http://gcasella@gns3.casella.local:3080/v2/computes/http://gns3.casella.local:3080/qemu/binaries - server replied: Not Found
Could not find /usr/bin/qemu-system-x86_64 in the Qemu binaries list

I'm not too sure if anything has changed from the configuration aspect on the server side, but I do see the new gns3_controller.conf file, not sure how to define it in the gns3_server.conf file

**Comment by noplay** [comment]
It was a server already defined migrated from 1.5?

Can you paste your gns3_server.conf and gns3_controller.conf?  

Thanks for help

**Comment by gcasella** [comment]
Hey @noplay 
It used to be version 1.5.2 (migrated and created a snapshot of my old settings) 
I put them all on google drive so it's easier to read instead of copying and pasting all of it. 

[gns3_server.conf](https://docs.google.com/document/d/1XnIf2ojewWbQMl0BKsZBJ0g7-4pe0WCLMhmTojrItOo/edit?usp=sharing)

[gns3_controller.conf](https://docs.google.com/document/d/1F4gw7B7wW7trYanTtMpIXbn1hPmX219rbVdqJ3L_cwU/edit?usp=sharing)

[gns3.service](https://docs.google.com/document/d/1wo67-2yNLef1Oj0vJCSuEQZTzacvxLXjCckC5Q6ZQv4/edit?usp=sharing)

**Comment by noplay** [comment]
OK it seem to be a migration issue with remote server I will make a fix
tomorrow.

Thanks a lot for the report

**Comment by gcasella** [comment]
No problem! 
Happy to help!

Will there be anything that I would need to do from my side other than updating the gns3-server?

Also, how can i have the gns3_controller.conf file be pulled from the /opt/gns3/.config/ directory?

**Comment by gcasella** [comment]
@noplay 
Also ran into this one;

> Server error from http://gns3.casella.local:3080: Error while setting up node: Compute ID http://gns3.casella.local:3080 doesn't exist
Error while setting up node: Compute ID http://gns3.casella.local:3080 doesn't exist

**Comment by noplay** [comment]
Gui config file before:
```
{
    "LocalServer": {},
    "Qemu": {
        "enable_kvm": true,
        "use_local_server": true,
        "vms": [
            {
                "acpi_shutdown": false,
                "adapter_type": "e1000",
                "adapters": 1,
                "boot_priority": "c",
                "category": 2,
                "cdrom_image": "",
                "console_type": "telnet",
                "cpu_throttling": 0,
                "cpus": 1,
                "default_name_format": "{name}-{0}",
                "first_port_name": "",
                "hda_disk_image": "linux-microcore-6.4.img",
                "hda_disk_interface": "ide",
                "hdb_disk_image": "",
                "hdb_disk_interface": "ide",
                "hdc_disk_image": "",
                "hdc_disk_interface": "ide",
                "hdd_disk_image": "",
                "hdd_disk_interface": "ide",
                "initrd": "",
                "kernel_command_line": "",
                "kernel_image": "",
                "legacy_networking": false,
                "linked_base": true,
                "mac_address": "",
                "name": "core",
                "options": "-nographic",
                "platform": "",
                "port_name_format": "Ethernet{0}",
                "port_segment_size": 0,
                "process_priority": "normal",
                "qemu_path": "/usr/bin/qemu-system-x86_64",
                "ram": 256,
                "server": "http://127.0.0.1:8001",
                "symbol": ":/symbols/qemu_guest.svg",
                "usage": ""
            }
        ]
    },
    "Servers": {
        "local_server": {
            "allow_console_from_anywhere": false,
            "auth": true,
            "auto_start": true,
            "configs_path": "/Users/noplay/GNS3/configs",
            "console_end_port_range": 10000,
            "console_start_port_range": 5000,
            "host": "127.0.0.1",
            "images_path": "/Users/noplay/GNS3/images",
            "password": "mq18Cv5spUhJ69JH1wexBfVzlBtfHvD27ID58YFxbRqdmv8EFeuHl5H1nk9k0ahf",
            "path": "/Applications/GNS3.app/Contents/MacOS/gns3server",
            "port": 3080,
            "projects_path": "/Users/noplay/GNS3/projects",
            "report_errors": true,
            "symbols_path": "/Users/noplay/GNS3/symbols",
            "ubridge_path": "/Applications/GNS3.app/Contents/Resources/ubridge",
            "udp_end_port_range": 20000,
            "udp_start_port_range": 10000,
            "user": "6R87uLQAdzrBzpp0n8bgjbaLbm1uqRXCY71kYJS8e2HMJUmzYU8cdohX1Vpitu6t"
        },
        "remote_servers": [
            {
                "host": "127.0.0.1",
                "password": "",
                "port": 8001,
                "protocol": "http",
                "url": "http://127.0.0.1:8001",
                "user": ""
            }
        ],
    },
    "type": "settings",
    "version": "1.5.2"
}
```

The problem seem to be we don't convert in the server id (url in 1.5, uuid in 2.0)

**Comment by noplay** [comment]
For the remote server please update update the gns3-gui

For the location of controller config I opened a new issue #701 

Thanks for the help!

**Comment by noplay** [comment]
Now the controller will be in the same directory as gns3_server.conf

**Comment by gcasella** [comment]
Awesome!
Thanks!

One question what do you mean by 

> For the remote server please update update the gns3-gui

One more thing I had found with a fresh install of 2.0.0a1; It appears the GNS3 GUI can't detect the remote server configured;
[Server Config](http://imgur.com/a/purYF)
[Import Appliance](http://imgur.com/a/6L76h)
[Remote Server List](http://imgur.com/a/npu2f)

**Comment by noplay** [comment]
You need to clone the GUI project:
```
git clone git@github.com:GNS3/gns3-gui.git
git checkout 2.0
python3 setup.py install 
```
This should fix all the remote server issues.

**Comment by gcasella** [comment]
Ah boy, I'm running the gns3-gui via Windows instead of Linux. Don't think doing it that way would work for me. 

I'll wait it out till a new commit gets to the releases for the gui.

**Comment by noplay** [comment]
You can get the nightly build tomorrow here:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/

;)

**Comment by gcasella** [comment]
Ah ha!!!
Good to know :)
I'll let you know how it goes!

Thanks again!

**Comment by gcasella** [comment]
Alright @noplay here are my findings -- not sure if they will require a separate bug report but here it is;

New Install of GNS3 2.0 with fresh Remote GNS3 server running on my own VM (Not the official GNS3 VM);
[Remote Main Server](http://imgur.com/a/V5TP6)
[Add new IOU Device](http://imgur.com/a/jImoU)
[Add new IOU Device 2](http://imgur.com/a/DjGeo)
[Add Appliance](http://imgur.com/a/U0LVh) -- might be related to #704 ?

Next, Migrated from 1.5.2 to 2.0.0 nightly build - I don't receive that error I showed you previously but now get the follwing Traceback when trying to view any of the settings in the client (I've updated the remote server as well with the most recent version);
[Exception Log](http://pastebin.com/Aw4mfae7)

At this point, I'm fine with making my gns3_gui config from scratch so that I don't run into the migration issue, however the first section still shows some of the problem I run into when using fresh installs of both gns3server (remote server) and gns3-gui

**Comment by noplay** [comment]
I have opened a second issue for https://github.com/GNS3/gns3-gui/issues/1550

Traceback:
```
Traceback (most recent call last):
  File "./gns3-gui\gns3\modules\iou\pages\iou_device_preferences_page.py", line 118, in _iouDeviceChangedSlot
  File "./gns3-gui\gns3\modules\iou\pages\iou_device_preferences_page.py", line 78, in _refreshInfo
  File "./gns3-gui\gns3\compute_manager.py", line 133, in getCompute
KeyError: 'Compute http://gns3.casella.local:3080 is missing.'
```
