### ISSUE TITLE
status of QEMU VM is "started" when QEMU VM exits immediately.

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#70]
From the community: https://community.gns3.com/ideas/1589

When invalid arguments are given, process of qemu starts correctly, and exits immediately.
No output is shown in console, and status of QEMU VM is "started".
Though QEMU VM seems to start correctly, it actually stopped.
 
You can see this problem, when you set too large memory (on my environment, maximum is 2044MB),
or type error in additional settings (ex. -nographics).
 
Though GNS3 server checks whether process starts, it does not check whether process is running. 
I think it would be better to wait for several seconds, and check process is running.
This is a sample code.

```
--- qemu_vm.py
+++ qemu_vm.py (working copy)
@@ -868,6 +868,10 @@
                                                      stderr=subprocess.STDOUT,
                                                      cwd=self._working_dir)
                 log.info("QEMU VM instance {} started PID={}".format(self._id, self._process.pid))
+                time.sleep(2)
+                returncode = self._process.poll()
+                if not returncode is None:
+                    raise QemuError("could not start QEMU: invalid arguments or crash immediately.")
                 self._started = True
             except (OSError, subprocess.SubprocessError) as e:
                 stdout = self.read_stdout()
```

**Comment by noplay** [comment]
Hey @grossmj the vm can die at any time and without a notification feed the client can't know that. I have fixe the crash but refreshing the status is not possible at time except if we get the status of all vm regulary.

**Comment by grossmj** [comment]
Yes, this was just to show you why I would like to have a notification system or long-polling ;) This can wait fafter the first alpha. Also as a side note the less articifical wait we have, the better (e.g. asyncio.sleep)

**Comment by noplay** [comment]
It should be ok now thanks to the notification feed :)

**Comment by noplay** [comment]
And the video demo :)
https://www.youtube.com/watch?v=vC3hsFrkmxE&feature=youtu.be
