### ISSUE TITLE
[2.0.0a1] : No save project

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#702]
1- Cannot find "save" to save the current project

![image](https://cloud.githubusercontent.com/assets/1716020/18990760/59578bd6-8714-11e6-954a-df63de9ec902.png)

When I try to "save as ..." I got:

![selection_440](https://cloud.githubusercontent.com/assets/1716020/18990769/6b20069a-8714-11e6-8fa2-6a487e720c22.png)

And the current project disappear:

![image](https://cloud.githubusercontent.com/assets/1716020/18990784/82fc8644-8714-11e6-8a36-c9252a8f2f8c.png)

2- Looks like a related consequence: Tried nevertheless to run a project with containers without saving, containers pulled and inserted successfully, but don't start:
```
2016-09-30 04:42:02 DEBUG http_client.py:424 POST http://127.0.0.1:3080/v2/projects/f3672a20-3443-4975-8652-1cef96abffac/nodes/start {}
Error response from daemon: Container 0440b5d5717af01f1cb4ce58fafa5e478b5d18fd437edf20384b7f859ad0e853 is not running
Error response from daemon: Container 0440b5d5717af01f1cb4ce58fafa5e478b5d18fd437edf20384b7f859ad0e853 is not running
2016-09-30 04:42:03 DEBUG http_client.py:527 Response error: Error downloading http://admin@127.0.0.1:3080/v2/projects/f3672a20-3443-4975-8652-1cef96abffac/nodes/start - server replied: Conflict (error: 206)
2016-09-30 04:42:03 ERROR http_client.py:559 standard_init_linux.go:175: exec user process caused "no such file or directory"
standard_init_linux.go:175: exec user process caused "no such file or directory"

2016-09-30 04:42:03 DEBUG project.py:427 Event received: {'event': {'console_host': '127.0.0.1', 'console_type': 'telnet', 'ports': [{'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet0', 'short_name': 'e0/0', 'adapter_number': 0, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}, {'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet1', 'short_name': 'e1/0', 'adapter_number': 1, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}, {'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet2', 'short_name': 'e2/0', 'adapter_number': 2, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}, {'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet3', 'short_name': 'e3/0', 'adapter_number': 3, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}, {'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet4', 'short_name': 'e4/0', 'adapter_number': 4, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}, {'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet5', 'short_name': 'e5/0', 'adapter_number': 5, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}, {'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet6', 'short_name': 'e6/0', 'adapter_number': 6, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}, {'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet7', 'short_name': 'e7/0', 'adapter_number': 7, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}], 'height': 59, 'project_id': 'f3672a20-3443-4975-8652-1cef96abffac', 'port_segment_size': 0, 'first_port_name': None, 'console': 5004, 'z': 1, 'x': -20, 'compute_id': 'local', 'node_directory': '/home/ajn/GNS3/projects/test1/project-files/docker/0e66ac63-3c24-4c01-996f-faf5b3b1ab8f', 'port_name_format': 'Ethernet{0}', 'symbol': ':/symbols/docker_guest.svg', 'node_type': 'docker', 'name': 'gns3-openvswitch-1', 'command_line': None, 'label': {'y': -25, 'x': -45, 'style': 'font-family: TypeWriter;font-size: 10;font-weight: bold;fill: #000000;fill-opacity: 1.0;', 'rotation': 0, 'text': 'gns3-openvswitch-1'}, 'properties': {'environment': None, 'image': 'gns3/openvswitch:latest', 'container_id': '0440b5d5717af01f1cb4ce58fafa5e478b5d18fd437edf20384b7f859ad0e853', 'console_http_port': 80, 'console_resolution': '1024x768', 'adapters': 8, 'console_http_path': '/', 'aux': 5005, 'start_command': None}, 'width': 65, 'node_id': '0e66ac63-3c24-4c01-996f-faf5b3b1ab8f', 'status': 'stopped', 'y': -44}, 'action': 'node.updated'}
Error response from daemon: Container daa5423a367f8f20c0739367f1afee20b822735dde532963f9eadd7cffa97d23 is not running
Error response from daemon: Container daa5423a367f8f20c0739367f1afee20b822735dde532963f9eadd7cffa97d23 is not running
2016-09-30 04:42:04 DEBUG project.py:427 Event received: {'event': {'console_host': '127.0.0.1', 'console_type': 'telnet', 'ports': [{'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet0', 'short_name': 'e0/0', 'adapter_number': 0, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}], 'height': 59, 'project_id': 'f3672a20-3443-4975-8652-1cef96abffac', 'port_segment_size': 0, 'first_port_name': None, 'console': 5002, 'z': 1, 'x': -147, 'compute_id': 'local', 'node_directory': '/home/ajn/GNS3/projects/test1/project-files/docker/7aa6eabd-4ac0-44d0-9a03-039896b204d8', 'port_name_format': 'Ethernet{0}', 'symbol': ':/symbols/docker_guest.svg', 'node_type': 'docker', 'name': 'gns3-webterm-2', 'command_line': None, 'label': {'y': -25, 'x': -31, 'style': 'font-family: TypeWriter;font-size: 10;font-weight: bold;fill: #000000;fill-opacity: 1.0;', 'rotation': 0, 'text': 'gns3-webterm-2'}, 'properties': {'environment': '', 'image': 'gns3/webterm:latest', 'container_id': 'daa5423a367f8f20c0739367f1afee20b822735dde532963f9eadd7cffa97d23', 'console_http_port': 80, 'console_resolution': '1024x768', 'adapters': 1, 'console_http_path': '/', 'aux': 5003, 'start_command': None}, 'width': 65, 'node_id': '7aa6eabd-4ac0-44d0-9a03-039896b204d8', 'status': 'stopped', 'y': 94}, 'action': 'node.updated'}
Error response from daemon: Container 770f36fb05ca4179c4034bf37a5c360b2817435db3bb2557bcf12a3648d8a874 is not running
Error response from daemon: Container 770f36fb05ca4179c4034bf37a5c360b2817435db3bb2557bcf12a3648d8a874 is not running
2016-09-30 04:42:04 DEBUG project.py:427 Event received: {'event': {'console_host': '127.0.0.1', 'console_type': 'telnet', 'ports': [{'link_type': 'ethernet', 'port_number': 0, 'name': 'Ethernet0', 'short_name': 'e0/0', 'adapter_number': 0, 'data_link_types': {'Ethernet': 'DLT_EN10MB'}}], 'height': 59, 'project_id': 'f3672a20-3443-4975-8652-1cef96abffac', 'port_segment_size': 0, 'first_port_name': None, 'console': 5000, 'z': 1, 'x': 119, 'compute_id': 'local', 'node_directory': '/home/ajn/GNS3/projects/test1/project-files/docker/801abe3e-85be-4286-a16c-80910176e239', 'port_name_format': 'Ethernet{0}', 'symbol': ':/symbols/docker_guest.svg', 'node_type': 'docker', 'name': 'gns3-webterm-1', 'command_line': None, 'label': {'y': -25, 'x': -31, 'style': 'font-family: TypeWriter;font-size: 10;font-weight: bold;fill: #000000;fill-opacity: 1.0;', 'rotation': 0, 'text': 'gns3-webterm-1'}, 'properties': {'environment': '', 'image': 'gns3/webterm:latest', 'container_id': '770f36fb05ca4179c4034bf37a5c360b2817435db3bb2557bcf12a3648d8a874', 'console_http_port': 80, 'console_resolution': '1024x768', 'adapters': 1, 'console_http_path': '/', 'aux': 5001, 'start_command': None}, 'width': 65, 'node_id': '801abe3e-85be-4286-a16c-80910176e239', 'status': 'stopped', 'y': 93}, 'action': 'node.updated'}
```

Containers run successfully from the cli

![image](https://cloud.githubusercontent.com/assets/1716020/18991098/b512df8c-8716-11e6-8fc3-190476f1be7e.png)

3- Strangely, when quiting GNS3 without saving the current project and then restart GNS3, I can open the previous project with "open existing project"

**Comment by noplay** [comment]
No save is a feature of 2.0  :) For the other issues I will check.

# Save as you go

Your projects are automatically saved as you make changes to them, there is no need to press any save button anymore. An additional benefit is this will avoid synchronisation issues between the emulators’ virtual disks and projects.

**Comment by AJNOURI** [comment]
OK, I see. 
So what about rolling back changes?  Is it done by managing snapshots?

**Comment by noplay** [comment]
Yeah snapshot is the solution.

It's less confusing. Because a lot of people think in 1.X when you reload
the project without save everything is rollback. But it's not true the disk
of VMware, Docker, Qemu, VirtualBox will be not be rollback.

**Comment by noplay** [comment]
Can you tests with last source code of server. I think I fix some issues.

Thanks

**Comment by AJNOURI** [comment]
Updated to latest code:


> => POST http://127.0.0.1:3080/v2/projects/f3672a20-3443-4975-8652-1cef96abffac/nodes/start {}
> 
> => Response error: Error downloading http://admin@127.0.0.1:3080/v2/projects/f3672a20-3443-4975-8652-1cef96abffac/nodes/start - server replied: Conflict (error: 206)
> standard_init_linux.go:175: exec user process caused "no such file or directory"
> standard_init_linux.go:175: exec user process caused "no such file or directory"
> standard_init_linux.go:175: exec user process caused "no such file or directory"
> standard_init_linux.go:175: exec user process caused "no such file or directory"
> 
> Event received: {'event': {'status': 'stopped', 'node_id': '801abe3e-85be-4286-a16c-80910176e239', 'node_type': 'docker', 'console_host': '127.0.0.1', 'label': {'rotation': 0, 'y': -25, 'style': 'font-family: TypeWriter;font-size: 10;font-weight: bold;fill: #000000;fill-opacity: 1.0;', 'x': -31, 'text': 'gns3-webterm-1'}, 'command_line': None, 'first_port_name': None, 'port_segment_size': 0, 'console': 5000, 'height': 59, 'name': 'gns3-webterm-1', 'z': 1, 'console_type': 'telnet', 'ports': [{'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e0/0', 'port_number': 0, 'adapter_number': 0, 'name': 'Ethernet0'}], 'node_directory': '/home/ajn/GNS3/projects/test1/project-files/docker/801abe3e-85be-4286-a16c-80910176e239', 'port_name_format': 'Ethernet{0}', 'x': 119, 'width': 65, 'symbol': ':/symbols/docker_guest.svg', 'y': 93, 'properties': {'console_http_port': 80, 'environment': '', 'console_resolution': '1024x768', 'adapters': 1, 'console_http_path': '/', 'image': 'gns3/webterm:latest', 'start_command': None, 'aux': 5001, 'container_id': 'eb9dcd3cf382cf2ffa1a4905d3fefe7a4e3da3f3bb1b4b4e45259d945ac4b741'}, 'compute_id': 'local', 'project_id': 'f3672a20-3443-4975-8652-1cef96abffac'}, 'action': 'node.updated'}
> Event received: {'event': {'status': 'stopped', 'node_id': '0e66ac63-3c24-4c01-996f-faf5b3b1ab8f', 'node_type': 'docker', 'console_host': '127.0.0.1', 'label': {'rotation': 0, 'y': -25, 'style': 'font-family: TypeWriter;font-size: 10;font-weight: bold;fill: #000000;fill-opacity: 1.0;', 'x': -45, 'text': 'gns3-openvswitch-1'}, 'command_line': None, 'first_port_name': None, 'port_segment_size': 0, 'console': 5004, 'height': 59, 'name': 'gns3-openvswitch-1', 'z': 1, 'console_type': 'telnet', 'ports': [{'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e0/0', 'port_number': 0, 'adapter_number': 0, 'name': 'Ethernet0'}, {'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e1/0', 'port_number': 0, 'adapter_number': 1, 'name': 'Ethernet1'}, {'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e2/0', 'port_number': 0, 'adapter_number': 2, 'name': 'Ethernet2'}, {'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e3/0', 'port_number': 0, 'adapter_number': 3, 'name': 'Ethernet3'}, {'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e4/0', 'port_number': 0, 'adapter_number': 4, 'name': 'Ethernet4'}, {'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e5/0', 'port_number': 0, 'adapter_number': 5, 'name': 'Ethernet5'}, {'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e6/0', 'port_number': 0, 'adapter_number': 6, 'name': 'Ethernet6'}, {'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e7/0', 'port_number': 0, 'adapter_number': 7, 'name': 'Ethernet7'}], 'node_directory': '/home/ajn/GNS3/projects/test1/project-files/docker/0e66ac63-3c24-4c01-996f-faf5b3b1ab8f', 'port_name_format': 'Ethernet{0}', 'x': -20, 'width': 65, 'symbol': ':/symbols/docker_guest.svg', 'y': -44, 'properties': {'console_http_port': 80, 'environment': None, 'console_resolution': '1024x768', 'adapters': 8, 'console_http_path': '/', 'image': 'gns3/openvswitch:latest', 'start_command': None, 'aux': 5005, 'container_id': 'bc94c3f95eb18e60d37a04c05b25a41646ef374dbfad87721ac279991697662c'}, 'compute_id': 'local', 'project_id': 'f3672a20-3443-4975-8652-1cef96abffac'}, 'action': 'node.updated'}
> 
> => 
> => 
> => Event received: {'event': {'status': 'stopped', 'node_id': '7aa6eabd-4ac0-44d0-9a03-039896b204d8', 'node_type': 'docker', 'console_host': '127.0.0.1', 'label': {'rotation': 0, 'y': -25, 'style': 'font-family: TypeWriter;font-size: 10;font-weight: bold;fill: #000000;fill-opacity: 1.0;', 'x': -31, 'text': 'gns3-webterm-2'}, 'command_line': None, 'first_port_name': None, 'port_segment_size': 0, 'console': 5002, 'height': 59, 'name': 'gns3-webterm-2', 'z': 1, 'console_type': 'telnet', 'ports': [{'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'link_type': 'ethernet', 'short_name': 'e0/0', 'port_number': 0, 'adapter_number': 0, 'name': 'Ethernet0'}], 'node_directory': '/home/ajn/GNS3/projects/test1/project-files/docker/7aa6eabd-4ac0-44d0-9a03-039896b204d8', 'port_name_format': 'Ethernet{0}', 'x': -147, 'width': 65, 'symbol': ':/symbols/docker_guest.svg', 'y': 94, 'properties': {'console_http_port': 80, 'environment': '', 'console_resolution': '1024x768', 'adapters': 1, 'console_http_path': '/', 'image': 'gns3/webterm:latest', 'start_command': None, 'aux': 5003, 'container_id': '57e52602a867d11d1d9c4c58c9061b059479c33a5325da1b25798ff92a413b2c'}, 'compute_id': 'local', 'project_id': 'f3672a20-3443-4975-8652-1cef96abffac'}, 'action': 'node.updated'}
> GET http://127.0.0.1:3080/v2/computes {}
> Decoding response from http://admin@127.0.0.1:3080/v2/computes response 200
> [
>     {
>         "capabilities": {
>             "node_types": [
>                 "cloud",
>                 "ethernet_hub",
>                 "ethernet_switch",
>                 "nat",
>                 "vpcs",
>                 "virtualbox",
>                 "dynamips",
>                 "frame_relay_switch",
>                 "atm_switch",
>                 "qemu",
>                 "vmware",
>                 "docker",
>                 "iou"
>             ],
>             "version": "2.0.0a1"
>         },
>         "compute_id": "local",
>         "connected": true,
>         "cpu_usage_percent": 40.6,
>         "host": "127.0.0.1",
>         "memory_usage_percent": 63.9,
>         "name": "ubuntu",
>         "port": 3080,
>         "protocol": "http",
>         "user": "admin"
>     }
> ]
> 
> => Event received: {'event': {'memory_usage_percent': 63.9, 'name': 'ubuntu', 'host': '127.0.0.1', 'connected': True, 'port': 3080, 'compute_id': 'local', 'protocol': 'http', 'capabilities': {'node_types': ['cloud', 'ethernet_hub', 'ethernet_switch', 'nat', 'vpcs', 'virtualbox', 'dynamips', 'frame_relay_switch', 'atm_switch', 'qemu', 'vmware', 'docker', 'iou'], 'version': '2.0.0a1'}, 'cpu_usage_percent': 60.0, 'user': 'admin'}, 'action': 'compute.updated'}
>

**Comment by AJNOURI** [comment]
Here is a debug export, I'm testing a freshly created VM.
[debug.zip](https://github.com/GNS3/gns3-server/files/504218/debug.zip)

**Comment by noplay** [comment]
It seem some file are not installed on your system.

How you install gns3? Can you copy me the output of the installation?

Thanks a lot

**Comment by AJNOURI** [comment]
#### Initial install:
```
sudo apt-get install python3-dev psutils

pip3 install gns3-gui==2.0.0a1
pip3 install gns3-server==2.0.0a1
```

#### For dev:
```
git clone -b 2.0 https://github.com/GNS3/gns3-server
git clone -b 2.0 https://github.com/GNS3/gns3-gui
cd ~/gns3-gui
sudo python3 setup.py install 
cd ~/gns3-server
sudo python3 setup.py install 

```

**Comment by noplay** [comment]
If you start the gui:
```
cd ~/gns3-gui
python3 - m gns3
```

And server:
```
cd ~/gns3-server
python3 - m gns3server
```

Does is work?

**Comment by noplay** [comment]
I reproduce the issue, seem to be an issue with python setup. install

**Comment by noplay** [comment]
Problem solved with last commit

**Comment by AJNOURI** [comment]
It didn't get to the next screen of import:

![selection_464](https://cloud.githubusercontent.com/assets/1716020/19116626/0a2f4890-8acb-11e6-93b0-8da136ab762d.png)

> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev2-py3.5.egg/gns3/dialogs/appliance_wizard.py", line 129, in initializePage
>     if (ComputeManager.instance().localPlatform().startswith("darwin") or ComputeManager.instance().localPlatform().startswith("win")):
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev2-py3.5.egg/gns3/compute_manager.py", line 127, in localPlatform
>     return self.localCompute().capabilities()["platform"]
> KeyError: 'platform'
> 
> 2016-10-05 07:01:39 WARNING crash_report.py:79 A .git directory exist crash report is turn off for developers. Instant exit

Also exited on debug creation, the debug file itself is created: [debug-1609.zip](https://github.com/GNS3/gns3-server/files/511388/debug-1609.zip)


> 2016-10-05 07:06:35 INFO export_debug_dialog.py:53 Export debug information to /home/ajn/debug-1605
> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev2-py3.5.egg/gns3/dialogs/export_debug_dialog.py", line 64, in _okButtonClickedSlot
>     dir = self._project.filesDir()
> AttributeError: 'NoneType' object has no attribute 'filesDir'
> 
> 2016-10-05 07:06:36 WARNING crash_report.py:79 A .git directory exist crash report is turn off for developers. Instant exit
>

**Comment by AJNOURI** [comment]
When starting a project (only containers):

> 2016-10-05 07:20:41 DEBUG http_client.py:424 POST http://127.0.0.1:3080/v2/projects/2c2185b7-f590-4e49-aa4a-fee660b48bdc/nodes/start {}
> Error response from daemon: Container 0f22e48c1533aa79dbf610817acf164a779dc096dc07fa586238a383d404f94d is not running
> Error response from daemon: Container 0f22e48c1533aa79dbf610817acf164a779dc096dc07fa586238a383d404f94d is not running
> 2016-10-05 07:20:42 DEBUG http_client.py:527 Response error: Error downloading http://admin@127.0.0.1:3080/v2/projects/2c2185b7-f590-4e49-aa4a-fee660b48bdc/nodes/start - server replied: Conflict (error: 206)
> 2016-10-05 07:20:42 ERROR http_client.py:559 standard_init_linux.go:175: exec user process caused "no such file or directory"
> 
> 2016-10-05 07:20:42 DEBUG project.py:427 Event received: {'event': {'status': 'stopped', 'first_port_name': None, 'x': -144, 'console': 5004, 'ports': [{'name': 'Ethernet0', 'port_number': 0, 'link_type': 'ethernet', 'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'short_name': 'e0/0', 'adapter_number': 0}], 'node_type': 'docker', 'height': 59, 'port_segment_size': 0, 'name': 'gns3-webterm-2', 'y': 41, 'console_type': 'telnet', 'properties': {'console_http_path': '/', 'start_command': None, 'aux': 5005, 'environment': '', 'adapters': 1, 'console_http_port': 80, 'console_resolution': '1024x768', 'image': 'gns3/webterm:latest', 'container_id': '0f22e48c1533aa79dbf610817acf164a779dc096dc07fa586238a383d404f94d'}, 'node_id': '81192ef6-35c0-4a3e-a25c-f7fda4c7d5f3', 'label': {'y': -25, 'rotation': 0, 'x': -31, 'style': 'font-family: TypeWriter;font-size: 10;font-weight: bold;fill: #000000;fill-opacity: 1.0;', 'text': 'gns3-webterm-2'}, 'console_host': '127.0.0.1', 'project_id': '2c2185b7-f590-4e49-aa4a-fee660b48bdc', 'compute_id': 'local', 'node_directory': '/home/ajn/GNS3/projects/untitled/project-files/docker/81192ef6-35c0-4a3e-a25c-f7fda4c7d5f3', 'z': 1, 'width': 65, 'symbol': ':/symbols/docker_guest.svg', 'port_name_format': 'Ethernet{0}', 'command_line': None}, 'action': 'node.updated'}
> Error response from daemon: Container dc0d72b02109434545029a742025762c14a135042e2b6a10d1f1d454ab73ab0e is not running
> Error response from daemon: Container dc0d72b02109434545029a742025762c14a135042e2b6a10d1f1d454ab73ab0e is not running
> 2016-10-05 07:20:43 DEBUG project.py:427 Event received: {'event': {'status': 'stopped', 'first_port_name': None, 'x': 73, 'console': 5000, 'ports': [{'name': 'Ethernet0', 'port_number': 0, 'link_type': 'ethernet', 'data_link_types': {'Ethernet': 'DLT_EN10MB'}, 'short_name': 'e0/0', 'adapter_number': 0}], 'node_type': 'docker', 'height': 59, 'port_segment_size': 0, 'name': 'gns3-webterm-1', 'y': 8, 'console_type': 'telnet', 'properties': {'console_http_path': '/', 'start_command': None, 'aux': 5001, 'environment': '', 'adapters': 1, 'console_http_port': 80, 'console_resolution': '1024x768', 'image': 'gns3/webterm:latest', 'container_id': 'dc0d72b02109434545029a742025762c14a135042e2b6a10d1f1d454ab73ab0e'}, 'node_id': '64b2f7bd-044c-4656-b4c0-d3ab1b972b38', 'label': {'y': -25, 'rotation': 0, 'x': -31, 'style': 'font-family: TypeWriter;font-size: 10;font-weight: bold;fill: #000000;fill-opacity: 1.0;', 'text': 'gns3-webterm-1'}, 'console_host': '127.0.0.1', 'project_id': '2c2185b7-f590-4e49-aa4a-fee660b48bdc', 'compute_id': 'local', 'node_directory': '/home/ajn/GNS3/projects/untitled/project-files/docker/64b2f7bd-044c-4656-b4c0-d3ab1b972b38', 'z': 1, 'width': 65, 'symbol': ':/symbols/docker_guest.svg', 'port_name_format': 'Ethernet{0}', 'command_line': None}, 'action': 'node.updated'}
> Error response from daemon: Container f22d37079f5b444f80475536ef146b35d8c740fa94c790316fa481b189097a6e is not running
> Error response from daemon: Container f22d37079f5b444f80475536ef146b35d8c740fa94c790316fa481b189097a6e is not running

**Comment by noplay** [comment]
What is the output of:
python3 setup.py install ?

**Comment by AJNOURI** [comment]
[gns3-server-install.txt](https://github.com/GNS3/gns3-server/files/511453/server-install.txt)
[gns3-gui-install.txt](https://github.com/GNS3/gns3-server/files/511456/gns3-gui-install.txt)

**Comment by noplay** [comment]
Strange everything seem installed :( Did you restart the server?

**Comment by AJNOURI** [comment]
@noplay , just tested with: 

If you start the gui:

> cd ~/gns3-server
> python3 - m gns3server &
> cd ~/gns3-gui
> python3 - m gns3
> 

And it works :+1: 

![selection_467](https://cloud.githubusercontent.com/assets/1716020/19119581/87ea4ab4-8b20-11e6-8db3-1c5361136cf1.png)

**Comment by noplay** [comment]
Thanks!
