### ISSUE TITLE
Set system uuid for qemu

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#711]
csr1000v require a stable uuid to not lost the configuration. We can just pass the node uuid when we start the VM it's the same syntax.

And if the user manually pass the -uuid option to the VM we don't add our own uuid.

See: 
* https://gns3.slack.com/archives/contributors/p1475486255000476
* https://github.com/GNS3/gns3-registry/issues/59
* https://gns3.com/discussions/csr1000v-3-15s-license-issues-in

**Comment by superwolfboy** [comment]
not only csr1000v, as I observed palo alto also need a uuid to working fine , so this uuid is needed and can be changed by users
