### ISSUE TITLE
[2.0.0dev2] : cannot delete devices, complaining about ubridge not running.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#719]
> 2016-10-08 03:28:15 INFO node.py:397 gns3-webterm-1 is being deleted
> 2016-10-08 03:28:15 DEBUG http_client.py:424 DELETE http://127.0.0.1:3080/v2/projects/cf0660f9-d5a9-47ea-b283-5ad5607320b0/nodes/8b00660b-dbfd-4000-ae03-eb5f28b059fd {}
> 2016-10-08 03:28:15 DEBUG http_client.py:527 Response error: Error downloading http://admin@127.0.0.1:3080/v2/projects/cf0660f9-d5a9-47ea-b283-5ad5607320b0/nodes/8b00660b-dbfd-4000-ae03-eb5f28b059fd - server replied: Conflict (error: 206)
> 2016-10-08 03:28:15 DEBUG http_client.py:550 {
>     "message": "Cannot send command 'bridge delete bridge0': uBridge is not running",
>     "status": 409
> }
> 2016-10-08 03:28:15 ERROR node.py:413 error while deleting gns3-webterm-1: Cannot send command 'bridge delete bridge0': uBridge is not running
> 2016-10-08 03:28:15 CRITICAL __init__.py:97 Cannot send command 'bridge delete bridge0': uBridge is not running
> Stack (most recent call last):
>   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/ajn/gns3-gui/gns3/__main__.py", line 20, in <module>
>     main()
>   File "/home/ajn/gns3-gui/gns3/main.py", line 281, in main
>     exit_code = app.exec_()
>   File "/home/ajn/gns3-gui/gns3/qt/__init__.py", line 208, in partial
>     return func(*args, **kwargs)
>   File "/home/ajn/gns3-gui/gns3/http_client.py", line 552, in _processResponse
>     callback(json.loads(body), error=True, server=server, context=context)
>   File "/home/ajn/gns3-gui/gns3/qt/__init__.py", line 208, in partial
>     return func(*args, **kwargs)
>   File "/home/ajn/gns3-gui/gns3/node.py", line 414, in _deleteCallback
>     self.server_error_signal.emit(self.id(), result["message"])
>   File "/home/ajn/gns3-gui/gns3/graphics_view.py", line 1483, in _displayNodeErrorSlot
>     QtWidgets.QMessageBox.critical(self._main_window, name, message.strip())
>   File "/home/ajn/gns3-gui/gns3/qt/__init__.py", line 97, in critical
>     log.critical(message, stack_info=LogQMessageBox.stack_info())

---------------

ajn@ubuntu:~$ ubridge -version
ubridge version 0.9.5
ajn@ubuntu:~$ 

---------------
Debug file:  [deleting-links.zip](https://github.com/GNS3/gns3-server/files/517631/deleting-links.zip)

**Comment by noplay** [comment]
Fixed by a previous commit
