### ISSUE TITLE
Deleting docker image used by projects

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#720]
This error appear when opening a project with container whose image was deleted.

![selection_469](https://cloud.githubusercontent.com/assets/1716020/19212830/8fe5f074-8d5a-11e6-8a46-a51abd3a3c66.png)

To avoid this, we could display a warning when someone tries to delete Docker image used in a project, what do you think @noplay ?

**Comment by noplay** [comment]
I will test you should not get this warning you are right. The minimum is to display what docker returned.

**Comment by noplay** [comment]
I don't reproduce the issue how do you delete the image? If I delete a image docker will pull it when need.

**Comment by AJNOURI** [comment]
Hi @noplay, 
Here is a video showing the procedure:
[Deleting image whose container used in a project](https://youtu.be/NoCUXmkQL0U)

Possible other issue:
By the way, note at the beginning it doesn't allow me to overrite an existing project.

**Comment by AJNOURI** [comment]
Here is a video showig the procedure:
[Delete an image whose container is used in a project](https://youtu.be/NoCUXmkQL0U)

Note:
By the way note that, it doesn't allow to override an existing project. If needed we could open another issue with more debug inf.

**Comment by noplay** [comment]
After watching your video, it can't be related deleting a template is purely a gui stuff with no impact on existing topologies.  This mean the error is probably in another place.

After the error can you go to  Help > Export debug informations and send me the .zip by email to julien@gns3.net

**Comment by AJNOURI** [comment]
Here is the debug:
[debug-delete-image-when-container-is-used.zip](https://github.com/GNS3/gns3-server/files/539650/debug-delete-image-when-container-is-used.zip)

**Comment by noplay** [comment]
Could you rexport the debug. But this time start the gui with --debug. It's strange I don't see the request which have generated the 403 in the log of the server ... 

How do you start the server? I see from the log it's not the GUI who started it or two gui was running during the test.

**Comment by AJNOURI** [comment]
Here is a debug file  with gns3 --debug
[debug-delete-image-when-container-is-used-21-10-1620.zip](https://github.com/GNS3/gns3-server/files/544512/debug-delete-image-when-container-is-used-21-10-1620.zip)

I start GNS3 as shown below, as a result of https://github.com/GNS3/gns3-server/issues/702
```
python3 -m gns3server
python3 -m gns3 --debug
```

**Comment by noplay** [comment]
Ok I understand why I don't see anything in the log, the log is not enable due to manual start.

Could you start the server with:
python3 -m gns3server --log  /tmp/server.log

And give use the log

And I think if you start the server like that it will work:
python3 -m gns3server --log  /tmp/server.log --local

**Comment by AJNOURI** [comment]
Hi julien,
1- Looks OK with latest update, it doesn't show the error message anymore:

![screenshot - 231016 - 06 37 08](https://cloud.githubusercontent.com/assets/1716020/19624271/a1bc20fe-98a2-11e6-8d25-4f71db243873.png)


That solves the issue of deleting image templates from GNS3 and projects using the images still work.

2- Even, removed the image outside of GNS3, and when reopening a project using the image, it just pulls it again, very nice.

Good job Julien!

By the way, should we continue to start GNS3 manually, as mentioned here https://github.com/GNS3/gns3-server/issues/702 ?

**Comment by noplay** [comment]
Thanks.

You should also no longer have issue with #702
