### ISSUE TITLE
Node not working when GNS3 is bound to an IPV6 host

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#725]
# Working
- Dynamips
- Vbox
- VMware
- IOU
- Docker

# Not working
- VPCS #722 
- Qemu

**Comment by AJNOURI** [comment]
Hi Julien,
To test GNS3 with IPv6, should we just disable IPv4 on interfaces and launch GNS3?

**Comment by noplay** [comment]
In server preferences you can bind the local server to an IPV6

We think that for the moment we will disable IPV6 binding.

**Comment by noplay** [comment]
In 2.0 it will not be supported

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/pull/1096
