### ISSUE TITLE
[1.5.2] cannot connect Vmware VMs: "These nodes cannot be connected together (NIOVMNET != NIOUDP)"

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#730]
GNS3 version is 1.5.2 
GNS3 Converter version is 1.3.0
Python version is 3.4.2 (64-bit) with utf-8 encoding
Qt version is 5.3.2
PyQt version is 5.3.2
SIP version is 4.16.4

**host:**
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.5 (jessie)
Release:	8.5
Codename:	jessie

--------------

Cannot connect VMware VM to either generic switch or Openvswitch container:

![selection_484](https://cloud.githubusercontent.com/assets/1716020/19489048/c67ce86a-9569-11e6-8b52-bdbec5b640d0.png)

> 2016-10-18 19:37:04 CRITICAL __init__.py:95 These nodes cannot be connected together (NIOVMNET != NIOUDP)
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main.py", line 262, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 489, in mousePressEvent
>     self._userNodeLinking(event, item)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 402, in _userNodeLinking
>     destination_port.defaultNio().__name__))
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 95, in critical
>     log.critical(message, stack_info=LogQMessageBox.stack_info())

No such issue with VirtualBox VMs:

![selection_486](https://cloud.githubusercontent.com/assets/1716020/19489090/0585e980-956a-11e6-88bf-c771459b69f1.png)

**Comment by noplay** [comment]
I think it's known limitation of 1.5 what do you think @grossmj ?

**Comment by grossmj** [comment]
uBridge must be enabled in Preferences -> VMware. NIOVMNET will be removed from 2.0.
