### ISSUE TITLE
[2.0.0dev3] SSL Traceback

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-server#733]
Hey @noplay 

When enabling SSL for the gns3_server I noticed this traceback message -- not sure if it's an issue or not, but just wanted to bring it to your attention (there's this message along with multiple other ones;

> 2016-10-22 23:44:06 ERROR base_events.py:1148 Error on transport creation for incoming connection
> handle_traceback: Handle created at (most recent call last):
>   File "/usr/local/bin/gns3server", line 9, in <module>
>     load_entry_point('gns3-server==2.0.0.dev3', 'console_scripts', 'gns3server')()
>   File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev3-py3.5.egg/gns3server/main.py", line 79, in main
>     run()
>   File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev3-py3.5.egg/gns3server/run.py", line 264, in run
>     server.run()
>   File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev3-py3.5.egg/gns3server/web/web_server.py", line 323, in run
>     self._loop.run_forever()
>   File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
>     self._run_once()
>   File "/usr/lib/python3.5/asyncio/base_events.py", line 1304, in _run_once
>     handle._run()
>   File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
>     self._callback(*self._args)
>   File "/usr/lib/python3.5/asyncio/selector_events.py", line 669, in _read_ready
>     self._protocol.data_received(data)
>   File "/usr/lib/python3.5/asyncio/sslproto.py", line 493, in data_received
>     ssldata, appdata = self._sslpipe.feed_ssldata(data)
>   File "/usr/lib/python3.5/asyncio/sslproto.py", line 233, in feed_ssldata
>     self._handshake_cb(exc)
>   File "/usr/lib/python3.5/asyncio/sslproto.py", line 588, in _on_handshake_complete
>     self._wakeup_waiter(exc)
>   File "/usr/lib/python3.5/asyncio/sslproto.py", line 446, in _wakeup_waiter
>     self._waiter.set_exception(exc)
>   File "/usr/lib/python3.5/asyncio/futures.py", line 349, in set_exception
>     self._schedule_callbacks()
>   File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
>     self._loop.call_soon(callback, self)
> protocol: <RequestHandler none:none disconnected>
> transport: <asyncio.sslproto._SSLProtocolTransport object at 0x7f160953fd30>
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/asyncio/selector_events.py", line 210, in _accept_connection2
>     yield from waiter
>   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
>     yield self  # This tells Task to wait for completion.
>   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
>     future.result()
>   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
>     raise self._exception
>   File "/usr/lib/python3.5/asyncio/sslproto.py", line 493, in data_received
>     ssldata, appdata = self._sslpipe.feed_ssldata(data)
>   File "/usr/lib/python3.5/asyncio/sslproto.py", line 201, in feed_ssldata
>     self._sslobj.do_handshake()
>   File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:645)

**Comment by noplay** [comment]
You got this when you have non ssl traffic on an ssl enabled server. We can't do nothing to catch it cleanly it's outside our code.
