### ISSUE TITLE
Issue with framerelay switch

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#735]
https://gns3.com/qa/frame-relay-switch-configure-in-

**Comment by noplay** [comment]
# Config
![capture d ecran 2016-10-26 a 11 31 00](https://cloud.githubusercontent.com/assets/345437/19720925/77a815a4-9b70-11e6-813d-05aa228982a6.png)


# 1.5
![capture d ecran 2016-10-26 a 11 35 55](https://cloud.githubusercontent.com/assets/345437/19720955/99cbd24c-9b70-11e6-8229-a5d2b50888c0.png)

# 2.0

![capture d ecran 2016-10-26 a 11 31 36](https://cloud.githubusercontent.com/assets/345437/19720959/9fae509a-9b70-11e6-9e54-53bb4d3f5dbc.png)

**Comment by noplay** [comment]
Seem to be fix but if @grossmj you can test

**Comment by grossmj** [comment]
I will test soon.
