### ISSUE TITLE
When IOU process stopped explain that user need probably to use a different image

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#739]
When we got an error "IOU process has stopped" we should enhance the error message to explain to the user that it could be an image error and he should try with a different image.

**Comment by vader75** [comment]
sure but how does one know which image to use that will not crash?

**Comment by noplay** [comment]
If I remember a thread with best IOU images exists on the community but no real best image as emerged. The problem is the image could work for someone but a specific feature could be buggy.  And due to the fact Cisco doesn't officially support no reference web site exists on their side.

**Comment by vader75** [comment]
No worries, I guess it is what it is, just strange a bit, maybe use vIOS
instead, thanks for your help.

On 28 October 2016 at 1:26:03 am, Julien Duponchelle (
notifications@github.com) wrote:

If I remember a thread with best IOU images exists on the community but no
real best image as emerged. The problem is the image could work for someone
but a specific feature could be buggy. And due to the fact Cisco doesn't
officially support no reference web site exists on their side.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/GNS3/gns3-server/issues/739#issuecomment-256656728>,
or mute
the thread

**Comment by vader75** [comment]
I just tested a different image, this one just stops working (no console response), but no exit return code. Are you sure its not some other issue with GNS3VM and GNS3 1.5.2 ?

**Comment by vader75** [comment]
tested on windows (as well as mac as stated above), same behaviour, while I can't claim it, looking if anyone else in community is having this issues with IOU (L2) nodes silently crashing and needing to be restarted to function again.

I tested 2 different images, so are getting more inclined to suspect the GNS3 VM its running on or some internal keep-alives or similar?

**Comment by noplay** [comment]
Signal 11 mean segfault. Because IOU run as a standalone program this mean IOU has crashed itself. 

We didn't touch this code recently. The only thing that could impact IOU is recent OpenSSL bug fixes on debian.

Perhaps testing with an IOU images supported by unetlab is a good idea:
http://www.unetlab.com/2014/11/adding-cisco-iouiol-images/

**Comment by vader75** [comment]
the last crash did not even send sig 11 on GNS3 console, IOU just died (i know by not having traffic passing to from device connected to it). Interesting note is that console "appeared accessible", but could not do anything with it, it looks as it froze.

Again this worked before with these images without crashing that I know of, so not sure where to go.

I will test with unetlab image and report back, to test the idea.

**Comment by noplay** [comment]
Interresting that console seem frozen.

**Comment by noplay** [comment]
I close the issue because now we have a better error message. Let us know if you discover something with IOU.

**Comment by vader75** [comment]
great to close it but even unetlab image crashes, its getting impossible to use switching in GNS3...:-(
knowing that you can flag the error is ok, bt how do we progressing having crashes on different images.....they can't be all sig 11

===ver top L2 image from unetlab list=========
Cisco IOS Software, Solaris Software (I86BI_LINUXL2-ADVENTERPRISEK9-M), Experimental Version 15.1(20130726:213425) [dstivers-july26-2013-team_track 104]
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Fri 26-Jul-13 15:56 by dstivers

======GNS3 console error=======

=> Error: IOU process has stopped, return code: -11
***************************************************************
IOS On Unix - Cisco Systems confidential, internal use only
Port 0/0 is connected to:
 	513:0/0
Port 1/0 is connected to:
 	513:1/0
Port 2/0 is connected to:
 	513:2/0
Port 3/0 is connected to:
 	513:3/0
Port 4/0 is connected to:
 	513:4/0
Port 5/0 is connected to:
 	513:5/0
Port 6/0 is connected to:
 	513:6/0
Port 7/0 is connected to:
 	513:7/0
Port 8/0 is connected to:
 	513:8/0
Port 9/0 is connected to:
 	513:9/0
Port 10/0 is connected to:
 	513:10/0
Port 11/0 is connected to:
 	513:11/0
Port 12/0 is connected to:
 	513:12/0
Port 13/0 is connected to:
 	513:13/0
Port 14/0 is connected to:
 	513:14/0
Port 15/0 is connected to:
 	513:15/0
Port 0/1 is connected to:
 	513:0/1
Port 1/1 is connected to:
 	513:1/1
Port 2/1 is connected to:
 	513:2/1
Port 3/1 is connected to:
 	513:3/1
Port 4/1 is connected to:
 	513:4/1
Port 5/1 is connected to:
 	513:5/1
Port 6/1 is connected to:
 	513:6/1
Port 7/1 is connected to:
 	513:7/1
Port 8/1 is connected to:
 	513:8/1
Port 9/1 is connected to:
 	513:9/1
Port 10/1 is connected to:
 	513:10/1
Port 11/1 is connected to:
 	513:11/1
Port 12/1 is connected to:
 	513:12/1
Port 13/1 is connected to:
 	513:13/1
Port 14/1 is connected to:
 	513:14/1
Port 15/1 is connected to:
 	513:15/1
Port 0/2 is connected to:
 	513:0/2
Port 1/2 is connected to:
 	513:1/2
Port 2/2 is connected to:
 	513:2/2
Port 3/2 is connected to:
 	513:3/2
Port 4/2 is connected to:
 	513:4/2
Port 5/2 is connected to:
 	513:5/2
Port 6/2 is connected to:
 	513:6/2
Port 7/2 is connected to:
 	513:7/2
Port 8/2 is connected to:
 	513:8/2
Port 9/2 is connected to:
 	513:9/2
Port 10/2 is connected to:
 	513:10/2
Port 11/2 is connected to:
 	513:11/2
Port 12/2 is connected to:
 	513:12/2
Port 13/2 is connected to:
 	513:13/2
Port 14/2 is connected to:
 	513:14/2
Port 15/2 is connected to:
 	513:15/2
Port 0/3 is connected to:
 	513:0/3
Port 1/3 is connected to:
 	513:1/3
Port 2/3 is connected to:
 	513:2/3
Port 3/3 is connected to:
 	513:3/3
Port 4/3 is connected to:
 	513:4/3
Port 5/3 is connected to:
 	513:5/3
Port 6/3 is connected to:
 	513:6/3
Port 7/3 is connected to:
 	513:7/3
Port 8/3 is connected to:
 	513:8/3
Port 9/3 is connected to:
 	513:9/3
Port 10/3 is connected to:
 	513:10/3
Port 11/3 is connected to:
 	513:11/3
Port 12/3 is connected to:
 	513:12/3
Port 13/3 is connected to:
 	513:13/3
Port 14/3 is connected to:
 	513:14/3
Port 15/3 is connected to:
 	513:15/3
===================

**Comment by noplay** [comment]
Do you have the problem if you use a fresh GNS3 VM for 1.5.2?

**Comment by vader75** [comment]
Would have to try, is there a reason to start with fresh GNS3 VM ?

**Comment by noplay** [comment]
The only thing I see could a deb package updated breaking IOU for you.

**Comment by vader75** [comment]
I have tested with brand new downloaded GNS3 VM. With no traffic passing through IOU, the instance ran for hours (overnight for 7-8 hours).  I had also increased IOU ram from 256 to 384 MB just to be sure its not memory issue.

Once I have attached/enables devices to pass traffic, it crashed after few hours. It was sig -11 and was shown crashed down/red on GNS3. Had to start it up again.

Not sure if this tells you anything, but IOU for me is unusable on 1.5.2. It is rather crucial for this to work, as its basis for many labs.

If I remember we still have the issue open for GNS3 hubs/switches not passing traffic, so it may be somehow connected.

If you can suggest anything that can be done, would appreciate it.

**Comment by vader75** [comment]
Additional info:

- Tries different IOU images, they all eventually crash
- Tried vIOS L2, performing well over last 15 hours, albeit slower as it runs in QEMY (GNS3 VM)
- IOU running without connected nodes to it (no traffic passing), IOU still up over last 10 hours

So, while not very scientific approach, appears the issue point to either many IOU images that crash in GNS3VM due to process handling and/or traffic load on IOU instance. As vIOS is running similar experimental coed to IOU, not sure how this translates.

IOU is much better in terms of CPU utilisation, and I would prefer having it working, but I do understand that neither GNS3 and Cisco support it officially in this arrangement.

Thanks.
