### ISSUE TITLE
Loading a topology creates multiple projects

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#74]
Each node in the topology created a new instance of Project() which led to inconsistencies like the self._vms of Project() not containing all the nodes in the project which led to other major issues. 

I have fixed that for now, however I think we should prevent a user to open a lab if it is already used by the server. I think we will have to change the way projects are dynamically created on the client side if we choose to do this.

https://github.com/GNS3/gns3-server/blob/asyncio/gns3server/modules/project_manager.py#L74

**Comment by noplay** [comment]
What is the issue of reopening a project? The topology will be send again by the client we should not have a conflict.

**Comment by noplay** [comment]
And the client can't really know if a project exists on a server when ewe restore the project.
