### ISSUE TITLE
Drop the threaded telnet server

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#747]
Actually we have:
- A telnet server using thread use by VMware and VirtualBox
- A telnet server using thread use by IOU (reading on a tty)
- A telnet server based on asyncio use by docker

My proposal is to put some effort in order to use the docker asyncio code in place of multiple telnet server implementation.

The telnet server use for Docker has many advantage:
- use asyncio like the rest of server (no thread)
- support multiple user at the same time connected to the same console
- the telnet server receive a reader and writer. This mean the code for telnet is independent of the code for interacting with emulator. Easier to debug

And the benefits of a single code base:
- We can drop ioucon  which is hard to debug (I suspect it's freeze sometimes but not sure)
- More tested by users (I think almost nobody use telnet for Vbox and VMware)
- Easier to switch from telnet to a different console protocol (websocket for a web version?)

The long test session for 2.0 could be the good time to clean that.

**Comment by grossmj** [comment]
I agree, would be nice to merge all of that to only use the Asyncio version. Be careful to test it well on Windows because this is usually the most troublesome platform regarding Telnet.

> A telnet server using thread use by VMware and VirtualBox

Telnet server for VMware and VirtualBox acutally uses threads only on Windows because Named Pipes cannot be monitored by select() on this platform (default on OSX/Linux)

> More tested by users (I think almost nobody use telnet for Vbox and VMware)

Some VMware and VirtualBox appliances are non graphic and you must use Telnet.

> Easier to switch from telnet to a different console protocol (websocket for a web version?)

Could we / do we need to support SSH?

**Comment by noplay** [comment]
SSH will problably creat trouble with the need to include paramiko and all the legal stuff related due to crypto export :(

**Comment by noplay** [comment]
It's ok for VMware and VirtualBox on Windows and OSX (should be the same for linux)

@Raizo62 serial console should work for VirtualBox

**Comment by Raizo62** [comment]
> @Raizo62 serial console should work for VirtualBox

It works :-D Thanks :-D

**Comment by noplay** [comment]
Thanks for the feedback

**Comment by noplay** [comment]
Now IOU use the same telnet server. The code is much much simple:
https://github.com/GNS3/gns3-server/commit/3754a49cc095a6986be8b81d7da10d47276e898f
