### ISSUE TITLE
Drop serial console type

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#748]
Actually we support in GUI and server a type of console: serial. This type of console allow a direct connection of the client to a serial console without using any telnet wrapper.

Problems:
- this will not work if you use a remote server or will not work for a web client
- this require specific console applications (it seem we have a patched putty version for that)
- it's not clear for user that telnet console and serial console are the same console just the transport change

If I don't miss something it seem we use it only for VMware and VirtualBox. And we don't really need it, because we can just always use a telnet console and convert current VM to use that.

**Comment by grossmj** [comment]
Let's just drop that. I think it was just useful for to setup the Cisco CSR appliance running on VirtualBox back in the day.
