### ISSUE TITLE
Support bridge in cloud

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#761]
It seem we can detect if an interface is a bridge:
http://unix.stackexchange.com/questions/40560/how-to-know-if-a-network-interface-is-tap-tun-bridge-or-physical

And in this case we should use the nat code to create a tap and connect it to the bridge:
https://github.com/GNS3/gns3-server/blob/2.0/gns3server/compute/builtin/nodes/nat.py

**Comment by noplay** [comment]
@Raizo62 you can test that. Your bridge should work without problem when use in a cloud

**Comment by Raizo62** [comment]
Yes, that works. Thanks :-)
