### ISSUE TITLE
Feature Request: Integration with Cisco Packet Tracer

### ISSUE THREAD

**Issue by DeathCamel57** [GNS3/gns3-server#763]
Since GNS3 does not handle Cisco switches, would it be possible to emulate switches in Packet Tracer (which does support it) and have it controlled by and configured by GNS3?

**Comment by grossmj** [comment]
We do handle Cisco switches, here is how:

* Using ESW16 modules in classic IOS routers.
* Using IOU/IOL L2 images
* Using vIOS-L2 just like VIRL does (recommended solution)

Agreed, none of these solutions will cover 100% of the switching features but it comes pretty close (somewhere around 90-95%). Also, note that Packet Tracer does not emulate switches but simulated them which is a big difference, I doubt it simulates 100% of the switching features as well.
