### ISSUE TITLE
Log gets slowly filled in with the same entry

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#765]
```
2016-11-06 11:37:41 INFO __init__.py:383 Executing vmrun with command: /usr/bin/vmrun -T ws readVariable /home/grossmj/vmware/GNS3 VM/GNS3 VM.vmx guestVar gns3.eth0
```

**Comment by noplay** [comment]
Not sure that it's a real bug. 

The problem is we try to get the ip from the GNS3 VM. For that:
* we call vmrun in order to get the info
* if nothing we sleep 1 seconds
* we retry 120 time in order to let the VM boot

I will improve VMware code to allow tunning log level by command

**Comment by noplay** [comment]
Now the search use the debug log level
