### ISSUE TITLE
[2.0.0dev4] "Internal server error http://127.0.0.1:3080/v2"

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#768]
Environment: GNS3 installed inside VMWare Workstation

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Linux ubuntu 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

-------------------------

Occurs when trying to import docker image:
[Video](https://youtu.be/N4muWJN8N1g)

Debug file:  [internal-server-error-1014.zip](https://github.com/GNS3/gns3-server/files/574916/internal-server-error-1014.zip)

> 2016-11-07 01:14:31 DEBUG http_client.py:535 Response error: Error downloading http://admin@127.0.0.1:3080/v2/projects/2e6a6bf3-1eb2-4f3a-97de-cafd949a0ee1/nodes/8ee87e21-147b-4409-9f81-348b10be588d - server replied: Internal Server Error (error: 401)
> 2016-11-07 01:14:31 DEBUG http_client.py:559 {
>     "message": "Internal server error http://127.0.0.1:3080/v2/compute/projects/2e6a6bf3-1eb2-4f3a-97de-cafd949a0ee1/docker/nodes/8ee87e21-147b-4409-9f81-348b10be588d",
>     "status": 500
> }

**Comment by noplay** [comment]
How GNS3 is installed ? It seem docker can't find the init.sh file

**Comment by AJNOURI** [comment]
```
git clone -b 2.0 https://github.com/GNS3/gns3-server
git clone -b 2.0 https://github.com/GNS3/gns3-gui
cd ~/gns3-gui
sudo python3 setup.py install 
cd ~/gns3-server
sudo python3 setup.py install 

```

**Comment by noplay** [comment]
I don't reproduce. I suspect it's fixed by something else.

Thanks
