### ISSUE TITLE
1.5: Error message, when stopping IOU router

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#769]
GNS3 version latest 1.5.3dev1 https://github.com/GNS3/gns3-server/commit/bd4de862c889c655fc02aebe56a2cfba4b952bc7

When stopping a running IOU router the console shows the message `Error: iouyap process has stopped, return code: 0`

This "feature was introduced with the latest 1.5 commit https://github.com/GNS3/gns3-server/commit/bd4de862c889c655fc02aebe56a2cfba4b952bc7

**Comment by grossmj** [comment]
I've fixed that issue in 2.0 but not in 1.5

**Comment by ehlers** [comment]
Internally I corrected it that way:
```
diff --git a/gns3server/modules/iou/iou_vm.py b/gns3server/modules/iou/iou_vm.py
index f58612a..8e427c6 100644
--- a/gns3server/modules/iou/iou_vm.py
+++ b/gns3server/modules/iou/iou_vm.py
@@ -541,8 +541,6 @@ class IOUVM(BaseVM):
         self._ioucon_thread_stop_event.set()

         if returncode != 0:
-            log.info("{} process has stopped, return code: {}".format(process_name, returncode))
-        else:
             if returncode == 11:
                 message = "{} process has stopped, return code: {}. This could be an issue with the image using a different image can fix the issue.\n{}".format(process_name, returncode, self.read_iou_stdout())
             else:
```

**Comment by noplay** [comment]
I apply the patch to the 1.5 branch. Thanks!
