### ISSUE TITLE
You can't connect two telnet console to some node type

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#770]
Most of our nodes support multiple client connected to the same console via telnet.

# Working due to builtin support
* Dynamips

# Working due to AsyncioTelnetServer
* Docker
* VMware
* VirtualBox
* IOU

# Not working
* VPCS
* Qemu

**Comment by noplay** [comment]
Fixing VPCS is trivial we can replace the builtin telnet by our own if like IOU we read/write the console output of VPCS.

**Comment by noplay** [comment]
For qemu possible solutions:

```
-chardev pipe ,id=id ,path=path
Create a two-way connection to the guest.
The behaviour differs slightly between Windows hosts and other hosts:

On Windows, a single duplex pipe will be created at \\.pipe\path.

On other hosts, 2 pipes will be created called path.in and path.out.
Data written to path.in will be received by the guest.
Data written by the guest can be read from path.out.
QEMU will not create these fifos, and requires them to be present.

path forms part of the pipe path as described above. path is required.

```


```
-chardev stdio ,id=id [,signal=on|off]
Connect to standard input and standard output of the QEMU process.

signal controls if signals are enabled on the terminal, that includes exiting QEMU with the key sequence Control-c.
This option is enabled by default, use signal=off to disable it.
stdio is not available on Windows hosts.
```

**Comment by noplay** [comment]
VPCS check if run from a tty we can't just wrap the terminal. The only way is via TCP.

**Comment by noplay** [comment]
I fixed it by putting a proxy for telnet using our telnet server. It's consume an additionnal TCP port but no bad surprise possible with multiple qemu version.

We could use local socket but I'm not really sure it's really better. On Windows NamedPipe is more ressource consuming because we can't wait for data we need to loop over it.

**Comment by cioby23** [comment]
I think the issue https://github.com/GNS3/gns3-server/issues/687 is a duplicate of this one.
