### ISSUE TITLE
Manage base configuration on server

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#786]
Actually the config file could be located anywhere on the client system. This lead to multiple issue. 
* Two client can send different base config file.
* Complex API call where sometimes you need to pass the base config file content to the call (at creation) but not later
* If you create a third partie client he will not use the default config file

Todo:
* [x] Move creation of base file if not exists from client to server
* [x] Remove sending base file from client to server
* [x] When creating a node that require a base file send it from controller to client
* [x] Support abs and non abs paths
* [x] Rewrote config import / export to not use the node object but dedicated API
* [x] Disable file browser in GUI for remote controller

**Comment by noplay** [comment]
I think we should change the way we manage that.

* We need an interfaces for listing config files available on server and to edit them.
* Instead of putting absolute path to something on disk in preferences, we should be able to select one of the remote config files

**Comment by noplay** [comment]
To big for 2.0 change. Question opened for 2.1

**Comment by grossmj** [comment]
PR merged.
