### ISSUE TITLE
[2.0.0dev4] Project (containers) doesn't start: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#795]
Environment: GNS3 installed inside VMWare Workstation

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Linux ubuntu 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

GNS3 version is 2.0.0dev4 
Python version is 3.5.2 (64-bit) with utf-8 encoding
Qt version is 5.5.1
PyQt version is 5.5.1
SIP version is 4.17

-------------------------

Built a project using containers, but doesn't start:

> 2016-11-24 01:43:44 DEBUG http_client.py:432 POST http://127.0.0.1:3080/v2/projects/e9a1befc-f620-447d-997c-cdf35c7fed79/nodes/start {}
> Error response from daemon: Container 100404d6647ac423b93123e3c59b4c2a92e4a6f9355bd17b4f454fb3cf6e8518 is not running
> Error response from daemon: Container 100404d6647ac423b93123e3c59b4c2a92e4a6f9355bd17b4f454fb3cf6e8518 is not running
> 2016-11-24 01:43:45 DEBUG http_client.py:535 Response error: Error downloading http://admin@127.0.0.1:3080/v2/projects/e9a1befc-f620-447d-997c-cdf35c7fed79/nodes/start - server replied: Conflict (error: 206)
> 2016-11-24 01:43:45 ERROR http_client.py:568 standard_init_linux.go:175: exec user process caused "no such file or directory"
> 

Here is the debug file:
[debug-2411-1037.zip](https://github.com/GNS3/gns3-server/files/610940/debug-2411-1037.zip)

**Comment by noplay** [comment]
/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/compute/docker/resource/init.sh exists on your computer?

**Comment by noplay** [comment]
Something seem strange when I see the path. It sound like you have the debian package installed and the source version of GNS3.

**Comment by AJNOURI** [comment]
> ls: cannot access '/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/compute/docker/resources/init.sh': No such file or directory


I generally clone the latest dev, but because of the error mentioned above tried to I indeed installed gns3 from pip.

**Comment by noplay** [comment]
And no install via apt install ?

**Comment by AJNOURI** [comment]
I don't remember installing it through apt.

**Comment by noplay** [comment]
I think you have multiple gns3 installation on your system because setup.py and pip should put their stuff in /usr/local

Try:
```
apt remove gns3 gns3-server
rm -Rf /usr/share/gns3

**Comment by AJNOURI** [comment]
Thanks Julien, works now!
