### ISSUE TITLE
[2.0.0dev4] Issues with docker containers

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#798]
Cannot stop containers, or console to started ones:
[https://youtu.be/zZIOXsWHb50](https://youtu.be/zZIOXsWHb50)

Debug file:
[debug-1125-1547.zip](https://github.com/GNS3/gns3-server/files/613486/debug-1125-1547.zip)

**Comment by noplay** [comment]
You need to upgrade yarl

pip3 install -U yarl

**Comment by AJNOURI** [comment]
Yarl was already installed from https://github.com/GNS3/gns3-server/issues/796

![selection_569](https://cloud.githubusercontent.com/assets/1716020/20639369/0db42e70-b3c2-11e6-864d-fdd9cb3d1c9d.png)

**Comment by noplay** [comment]
But you need yarl 0.7.1 they fixed an issues.

**Comment by AJNOURI** [comment]
No such group "admin"

![selection_577](https://cloud.githubusercontent.com/assets/1716020/20663823/30abaf8c-b559-11e6-80b7-739f897eb2f3.png)

> chown: invalid group: ‘root:admin’
> 2016-11-28 01:42:33 CRITICAL progress_dialog.py:159 WaitForCommandWorker thread stopping with an error: Could not execute command "sudo chown root:admin /home/ajn/ubridge": Command '['sudo', 'chown', 'root:admin', '/home/ajn/ubridge']' returned non-zero exit status 1
> 2016-11-28 01:42:33 CRITICAL __init__.py:97 Could not execute command "sudo chown root:admin /home/ajn/ubridge": Command '['sudo', 'chown', 'root:admin', '/home/ajn/ubridge']' returned non-zero exit status 1
> Stack (most recent call last):
>   File "/home/ajn/.local/bin/gns3", line 11, in <module>
>     sys.exit(main())
>   File "/home/ajn/.local/lib/python3.5/site-packages/gns3/main.py", line 283, in main
>     exit_code = app.exec_()
>   File "/home/ajn/.local/lib/python3.5/site-packages/gns3/main_window.py", line 1014, in startupLoading
>     LocalServer.instance().localServerAutoStartIfRequire()
>   File "/home/ajn/.local/lib/python3.5/site-packages/gns3/local_server.py", line 313, in localServerAutoStartIfRequire
>     if not self.initLocalServer():
>   File "/home/ajn/.local/lib/python3.5/site-packages/gns3/local_server.py", line 340, in initLocalServer
>     self._checkUbridgePermissions()
>   File "/home/ajn/.local/lib/python3.5/site-packages/gns3/local_server.py", line 182, in _checkUbridgePermissions
>     sudo(["chown", "root:admin", path])
>   File "/home/ajn/.local/lib/python3.5/site-packages/gns3/utils/sudo.py", line 70, in sudo
>     if not progress_dialog.exec_():
>   File "/home/ajn/.local/lib/python3.5/site-packages/gns3/qt/__init__.py", line 223, in func_wrapper
>     return func(*args, **kwargs)
>   File "/home/ajn/.local/lib/python3.5/site-packages/gns3/utils/progress_dialog.py", line 160, in _error
>     QtWidgets.QMessageBox.critical(self.parentWidget(), "Error", "{}".format(message))
>   File "/home/ajn/.local/lib/python3.5/site-packages/gns3/qt/__init__.py", line 97, in critical
>     log.critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> 

`cat /etc/group | grep admin`

> lpadmin: x:113:ajn

According to this the admin group is no more installed since 12.04:
https://wiki.ubuntu.com/PrecisePangolin/ReleaseNotes/UbuntuDesktop#PrecisePangolin.2FReleaseNotes.2FCommonInfrastructure.Common_Infrastructure


Had to create the group "admin"
`groupadd admin`

**Comment by noplay** [comment]
This warning is not made for ubuntu. For ubuntu you should install from package and permission will be correct.
