### ISSUE TITLE
Cannot close GUI if the server is dead.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#80]
It seems the problem has not been totally fixed or I have added a regression somewhere... Steps to reproduce.

Manually start a local server.
Load a previously created project in the GUI.
Kill the server.
Try to quit the GUI.

I get the following messages in the console (debug mode) which is expected:

```
Response error: Connection refused
Error while closing project 8efbef8a-c7c0-4f6b-84be-6edae918650b: Can't connect to server http://127.0.0.1:8000
```

**Comment by noplay** [comment]
I don't have this issue.

Tested with the folowing:
* Open GNS 3 GUI
* Start a project
* Add two VPCS
* Save project
* Close GUI
* Reopen GUI
* Reopen Project

**Comment by noplay** [comment]
@grossmj  Can you try with the last client?

**Comment by grossmj** [comment]
@noplay All good, it works now.

**Comment by noplay** [comment]
Awesome
