### ISSUE TITLE
[ 2.0.0dev4  ] : error when exporting a container-only project

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#826]
GNS3 version is 2.0.0dev4 
Python version is 3.5.2 (64-bit) with utf-8 encoding
Qt version is 5.5.1
PyQt version is 5.5.1
SIP version is 4.17

---------------------

Environment: GNS3 installed inside VMWare Workstation

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Linux ubuntu 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

------------------

Error when exporting container-only project:

> 2016-12-12 07:29:46 DEBUG http_client.py:535 Response error: Error downloading http://admin@127.0.0.1:3080/v2/projects/e9a1befc-f620-447d-997c-cdf35c7fed79/files//README.txt - server replied: Not Found (error: 203)
> 2016-12-12 07:29:46 DEBUG http_client.py:559 {
>     "message": "404: Not Found",
>     "status": 404
> }

The export debug file:
[export-debug.zip](https://github.com/GNS3/gns3-server/files/646389/export-debug.zip)

**Comment by noplay** [comment]
I don't reproduce the issue. Do you have the issue with recent GNS3 version?

**Comment by AJNOURI** [comment]
Updated to the latest version:

> GNS3 version is 2.0.0dev6 
> Python version is 3.5.2 (64-bit) with utf-8 encoding
> Qt version is 5.5.1
> PyQt version is 5.5.1
> SIP version is 4.17

same error:
[https://youtu.be/DwulHeRThCQ](https://youtu.be/DwulHeRThCQ)

When trying to open an exported portable project (with or without images) I got this error:

![selection_597](https://cloud.githubusercontent.com/assets/1716020/21191294/81e4ade0-c1d9-11e6-820d-1e9a6362dfbc.png)


> 2016-12-14 08:40:24 DEBUG http_client.py:534 Response error: Error downloading http://admin@127.0.0.1:3080/v2/projects/f3cfc845-deda-4b35-a774-7ed5d5decfe9/open - server replied: Conflict (error: 206)
> 2016-12-14 08:40:24 DEBUG http_client.py:558 {
>     "message": "Docker has returned an error: 404 No such image: webterm:latest",
>     "status": 409
> }
> 2016-12-14 08:40:24 CRITICAL __init__.py:110 Docker has returned an error: 404 No such image: webterm:latest
> Stack (most recent call last):
>   File "/home/ajn/.local/bin/gns3", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev6-py3.5.egg/gns3/main.py", line 286, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev6-py3.5.egg/gns3/qt/__init__.py", line 225, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev6-py3.5.egg/gns3/http_client.py", line 560, in _processResponse
>     callback(json.loads(body), error=True, server=server, context=context)
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev6-py3.5.egg/gns3/qt/__init__.py", line 225, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev6-py3.5.egg/gns3/project.py", line 362, in _projectOpenCallback
>     self.project_creation_error_signal.emit(result["message"])
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev6-py3.5.egg/gns3/topology.py", line 203, in _projectCreationErrorSlot
>     QtWidgets.QMessageBox.critical(self._main_window, "New project", message)
>   File "/usr/local/lib/python3.5/dist-packages/gns3_gui-2.0.0.dev6-py3.5.egg/gns3/qt/__init__.py", line 110, in critical
>     log.critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> Error response from daemon: Container bf8a83989c76707ab2a57653d23f424bf9d7a9e34b1bd15de5cf15e9f1310040 is not running
> Error response from daemon: Container ff0eaa9c0833192e4c7fa9523489dd1f96ee77615e247757528e91f33b64ab27 is not running
> Error response from daemon: Container bf8a83989c76707ab2a57653d23f424bf9d7a9e34b1bd15de5cf15e9f1310040 is not running
> Error response from daemon: Container fa1b761c77782a3b4c7f3163b90551751f4f0ea2addc822b51134a9aa0e2c842 is not running
> Error response from daemon: Container ff0eaa9c0833192e4c7fa9523489dd1f96ee77615e247757528e91f33b64ab27 is not running
>

**Comment by noplay** [comment]
Ok i opened an issue for the import #834

I think I fixed the issue for the export. If you can test it.

Be carefull last server code require to install last ubridge from source otherwise link will not work.
