### ISSUE TITLE
Sporadic dead link on docker VM

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#835]
Running GNS3 version 2.0.0dev6 commit https://github.com/GNS3/gns3-gui/commit/95c443e127cb91156bcbdbbb3060dabae0071973 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7,
Self made GNS3 VM version 2.0.0dev6 commit https://github.com/GNS3/gns3-server/commit/46b6e7c5eef1bea202442aad952f6a39ba0b941d on Debian stretch (64-bit) with Python 3.5.2.

1. move 2 docker alpine VMs in an empty project and interconnect them
2. configure IP addresses
3. start VM
4. open console to all devices
5. ping from one docker VM the other one
6. stop VM

Repeat steps 3 - 6 until the ping doesn't work. Sometimes it takes 10 tries, sometimes only 2 to get this issue. I haven't noticed it on other devices, but I haven't tested that much.

Here a debug log from the server, the first start was OK, on the second start ping doesn't work. At least I haven't seen a difference.
[sparadic_link_failure.txt](https://github.com/GNS3/gns3-server/files/652462/sparadic_link_failure.txt)

**Comment by noplay** [comment]
After the fail the next will also failed ?

**Comment by ehlers** [comment]
It's totally random, sometimes the next fails also after a fail, but not always.

**Comment by ehlers** [comment]
It's seems to affect only one direction.

Here an example, where the ping was done from alpine-2 to alpine-1:

alpine-1 receives data and responds
```
/ # ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 5E:63:CF:77:F0:EB
          inet addr:10.1.1.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::5c63:cfff:fe77:f0eb%32706/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:29 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1530 (1.4 KiB)  TX bytes:1530 (1.4 KiB)
```

alpine-2 receives no data
```
/ # ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 42:EB:D3:C6:69:87
          inet addr:10.1.1.2  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::40eb:d3ff:fec6:6987%32512/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:1530 (1.4 KiB)
```

**Comment by noplay** [comment]
Not sure if it could be related to https://github.com/GNS3/gns3-gui/issues/1717

**Comment by ehlers** [comment]
Maybe, but when ping works my wireshark trace is fine as well.

BTW, it's not always the direction alpine-1 -> alpine-2, that's dead. Just I had the issue in the opposite direction.

**Comment by ehlers** [comment]
Here a netstat output, when a connection is blocked:
```
gns3@gns3vm:~$ sudo netstat -aupn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp     9984      0 192.168.1.99:10000      192.168.1.99:10001      ESTABLISHED 32452/ubridge
udp        0      0 192.168.1.99:10001      192.168.1.99:10000      ESTABLISHED 32449/ubridge
```

So both UDP tunnels are there. But what's strange is the Recv-Q counter. According to the netstat man page
```
Recv-Q
    Established: The count of bytes not copied by the user program  connected  to  this  socket.
    Listening: Since Kernel 2.6.18 this column contains the current syn backlog.
```

For me it looks as if data transported to port 10000 (first line) is not read by the ubridge program.

**Comment by ehlers** [comment]
When the connection is blocked one thread of ubridge is missing (3 threads instead of the normal 4).

```
gns3@gns3vm:~$ pgrep ubridge | xargs -r ps
   PID TTY      STAT   TIME COMMAND
  1256 ?        Sl     0:00 /usr/local/bin/ubridge -H 0.0.0.0:39371
  1258 ?        Sl     0:00 /usr/local/bin/ubridge -H 0.0.0.0:59109
gns3@gns3vm:~$ ps -T -p 1256
   PID   SPID TTY          TIME CMD
  1256   1256 ?        00:00:00 ubridge
  1256   1259 ?        00:00:00 ubridge
  1256   1269 ?        00:00:00 ubridge
  1256   1270 ?        00:00:00 ubridge
gns3@gns3vm:~$ ps -T -p 1258
   PID   SPID TTY          TIME CMD
  1258   1258 ?        00:00:00 ubridge
  1258   1266 ?        00:00:00 ubridge
  1258   1300 ?        00:00:00 ubridge
gns3@gns3vm:~$
```

**Comment by ehlers** [comment]
The ubridge log in case of blocked connection. The destination NIO thread terminates, because of an input/output error.

```
Hypervisor TCP control server started (IP 0.0.0.0 port 43359).
UDP tunnel connecting from local port 10000 to IPv4 addresss 192.168.1.99 on port 10001
Source NIO listener thread for bridge0 has started
Destination NIO listener thread for bridge0 has started
Received 90 bytes on bridge bridge0 (destination NIO)
0000: 33 33 00 00 00 16 92 9e 8c c2 35 f5 86 dd 60 00 33........5.....
0010: 00 00 00 24 00 01 00 00 00 00 00 00 00 00 00 00 ................
0020: 00 00 00 00 00 00 ff 02 00 00 00 00 00 00 00 00 ................
0030: 00 00 00 00 00 16 3a 00 05 02 00 00 01 00 8f 00 ................
0040: 38 d3 00 00 00 01 04 00 00 00 ff 02 00 00 00 00 8...............
0050: 00 00 00 00 00 01 ff c2 35 f5                   ........5.

send: Input/output error
Destination NIO listener thread for bridge0 has stopped
Received 90 bytes on bridge bridge0 (source NIO)
0000: 33 33 00 00 00 16 ba be c0 5e 63 af 86 dd 60 00 33........c.....
0010: 00 00 00 24 00 01 00 00 00 00 00 00 00 00 00 00 ................
0020: 00 00 00 00 00 00 ff 02 00 00 00 00 00 00 00 00 ................
0030: 00 00 00 00 00 16 3a 00 05 02 00 00 01 00 8f 00 ................
0040: 0b 7d 00 00 00 01 04 00 00 00 ff 02 00 00 00 00 ................
0050: 00 00 00 00 00 01 ff 5e 63 af                   ........c.

... more packets on  bridge bridge0 (source NIO) ...
```

The log of the other bridge process is fine, receiving from both NIOs, no errors.

**Comment by ehlers** [comment]
Created a workaround in ubridge, which ignores EIO (with warning). Now, sometimes I get this warning, one packet is lost then, but otherwise everything works. I really don't know why this EIO error is thrown, therefore this patch may not be the real solution.

```
diff --git a/ubridge.c b/ubridge.c
index ccc4622..e45725a 100644
--- a/ubridge.c
+++ b/ubridge.c
@@ -72,8 +72,10 @@ static void bridge_nios(nio_t *source_nio, nio_t *destination_nio, bridge_t *bri
     bytes_sent = nio_send(destination_nio, pkt, bytes_received);
     destination_nio->bytes_received += bytes_sent;
     if (bytes_sent == -1) {
-        if (errno == ECONNREFUSED || errno == ENETDOWN)
+        if (errno == ECONNREFUSED || errno == ENETDOWN || errno == EIO) {
+           perror("Warning: send");
            continue;
+        }
         perror("send");
         break;
     }
``

**Comment by noplay** [comment]
I try to figure wha we could have a EIO error. I think it's an error of the tap driver.

**Comment by noplay** [comment]
I suspect that:
Since Linux upstream commit 1bd4978a88ac("tun: honor IFF_UP in
tun_get_user()"), included in 4.4, writing to a tap device that is not
up sets errno to EIO.

https://patchwork.ozlabs.org/patch/633999/

The problem will not be visible with the GNS3 VM (Kernel 3.13) but will appear with a more recent kernel.

**Comment by noplay** [comment]
How it's occur. If a packet is send by the container before finishing to init the interface the error will be raised (this why it's random).

**Comment by noplay** [comment]
Could you try my ubridge patch:
https://github.com/GNS3/ubridge/commit/d441756d8b74a3a5492b139701ed32ec5bdb1339

Thanks a lot for all your debug informations without that I don't know how we will have found the issue.

**Comment by ehlers** [comment]
Just tested 10 time, ping works all the time, no errors shown in the ubridge log.

Normally "ifconfig eth0" shows 8 sent and 8 received packets just after start. Two times on one of the alpine VMs ifconfig shows only 7 received packets. That should be the lost packets because of the EIO error.

In future I will check for ubridge issues by "sudo netstat -aupn" to check if the processes are up and the UDP ports are correctly set up and by "cat /opt/gns3/projects/\<project-id\>/*/*/ubridge.log" to see if any error has occurred.

For me the issue looks resolved.

**Comment by noplay** [comment]
Thanks a lot
