### ISSUE TITLE
AttributeError: can't set attribute when creating a virtualbox device

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#84]
URL : /v1/projects/96a0f3b9-509f-48c8-b1a2-8f865226c988/virtualbox/vms
Method:	POST

Body parameters:	
adapter_type	Intel PRO/1000 MT Desktop (82540EM)
adapters	4
enable_remote_console	True
headless	False
use_any_adapter	False

Related sentry issue:
https://app.getsentry.com/gns3/gns3-server/group/56626910/

**Comment by grossmj** [comment]
This was fixed yesterday ;)
