### ISSUE TITLE
Sporadically systemd is unable to start gns3-server

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#851]
Self made GNS3VM with GNS3 Version 1.5 and 2.0 on Debian Testing

Since several months systemd sporadically can't start the gns3-server. The gns3-server is started, but remains in the status starting (it doesn't reach status running). After 90 seconds systemd kills the gns3-server.

I don't recall, that I had this issue in the beginning, so I assume it was introduced with a newer systemd or kernel version.

This happens only on cold start of the GNS3VM and the probability is quite high when the host OS (OS X in my case) is also cold started as well.

Here the systemd status of a successful start:
```
gns3@gns3vm:~$ sudo service gns3 status
● gns3.service - GNS3 server
   Loaded: loaded (/lib/systemd/system/gns3.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2016-12-31 09:44:35 CET; 1min 14s ago
  Process: 653 ExecStart=/usr/local/bin/gns3server --log /var/log/gns3/gns3server.log --pid /var/run/gns3/gns3server.pid --daemon (code=exited, status=0/SUCCESS)
  Process: 649 ExecStartPre=/bin/chown -R gns3:gns3 /var/log/gns3 /var/run/gns3 (code=exited, status=0/SUCCESS)
  Process: 646 ExecStartPre=/bin/mkdir -p /var/log/gns3 /var/run/gns3 (code=exited, status=0/SUCCESS)
 Main PID: 679 (gns3server)
    Tasks: 1 (limit: 19660)
   Memory: 52.4M
      CPU: 1.901s
   CGroup: /system.slice/gns3.service
           └─679 /usr/bin/python3 /usr/local/bin/gns3server --log /var/log/gns3/gns3server.log --pid /var/run/gns3/gns3server.pid --daemon

Dec 31 09:44:21 gns3vm systemd[1]: Starting GNS3 server...
Dec 31 09:44:30 gns3vm systemd[1]: gns3.service: PID file /var/run/gns3/gns3server.pid not readable (yet?) after start: No such file or directory
Dec 31 09:44:35 gns3vm systemd[1]: Started GNS3 server.
```

and here the status of a failed start:
```
gns3@gns3vm:~$ sudo service gns3 status
[sudo] password for gns3:
● gns3.service - GNS3 server
   Loaded: loaded (/lib/systemd/system/gns3.service; enabled; vendor preset: enabled)
   Active: activating (start) since Sat 2016-12-31 09:50:41 CET; 19s ago
    Tasks: 1 (limit: 19660)
   Memory: 52.9M
      CPU: 738ms
   CGroup: /system.slice/gns3.service
           └─506 /usr/bin/python3 /usr/local/bin/gns3server --log /var/log/gns3/gns3server.log --pid /var/run/gns3/gns3server.pid --daemon

Dec 31 09:50:41 gns3vm systemd[1]: Starting GNS3 server...
Dec 31 09:50:43 gns3vm systemd[1]: gns3.service: PID file /var/run/gns3/gns3server.pid not readable (yet?) after start: No such file or directory
```

In the system log I've noticed, that the gns3-server is started by systemd very early in the boot process, even before the network interfaces are configured. After reading http://unix.stackexchange.com/questions/126009/cause-a-script-to-execute-after-networking-has-started I added this to the (example) systemd configuration file of GNS3:
```
diff --git a/init/gns3.service.systemd b/init/gns3.service.systemd
index 82a8d7c2..9bf766f5 100644
--- a/init/gns3.service.systemd
+++ b/init/gns3.service.systemd
@@ -1,5 +1,7 @@
 [Unit]
 Description=GNS3 server
+Wants=network-online.target
+After=network.target network-online.target

 [Service]
 Type=forking
```

Since these changes two weeks ago the start of the gns3-server from systemd works flawless. But I have to confess, that I have no good knowledge about systemd. So I'm not sure, that this is the real solution.

**Comment by noplay** [comment]
Thanks I merged your patch. It seem ok for me, even if I confess I don't know more than you on systemd :(
