### ISSUE TITLE
[2.0] : incompatibility with jinja2

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-server#857]
Hi

Since this morning, when i compile GNS3-server, i have this error message : 
```
*** Error compiling '/tmp/pip-build-grbsezwc/Jinja2/jinja2/asyncfilters.py'...
  File "/tmp/pip-build-grbsezwc/Jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax
```

I believe that jinja2 has been updated just before.

I have found this post : [Installing 2.9.1 on Python 3 < 3.6 (or 3.5) seems problematic](https://github.com/pallets/jinja/issues/643)

**Comment by noplay** [comment]
Does it block the install because in the issue people say it's safe to ignore and recent pip version will hide the message:
https://github.com/pypa/pip/issues/1873

**Comment by Raizo62** [comment]
With my first tests, GNS3 works.
But, i don't know where/how you use jinja2 to know how to test this new release.

**Comment by noplay** [comment]
http://localhost:3080 if you see a page it's ok

**Comment by Raizo62** [comment]
Then, that works :-)

**Comment by noplay** [comment]
Ok I close it because their is not nothing we can do on our side and it's not blocking for user. Even if it's not perfect I think we will make worse if we provide workarounds.
