### ISSUE TITLE
Optimize HTTP upload

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#86]
Actually a large file can consume a lot of memory

https://github.com/KeepSafe/aiohttp/issues/183

**Comment by noplay** [comment]
The memory usage is improved but we still have an issue the FileReader not async. 

I think we can limit the size of the files to 100MB in the HTML form and ask user to upload larger file via GNS3. Because the uploaded file with GNS3 use directly a stream an aoihttp doesn't need to parse the query in order to build a file object.

**Comment by grossmj** [comment]
I'll have to limit to 200MB because some IOU images are around 150MB.
