### ISSUE TITLE
1.5.3 needs additional python module "typing"

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#870]
Several threads  in the GNS3 forum report an missing python module "typing" after upgrading to 1.5.3.

Ubuntu 14.04: https://www.gns3.com/qa/update-to-ubuntu-14-04-broke-gns
Debian 8.7: https://www.gns3.com/discussions/gns3-doesn-t-work-on-debian-8-7-
Mint 17.3: https://www.gns3.com/qa/gns3-1-5-3-linux-mint-17-3-could

**Comment by noplay** [comment]
It seem the package fail on distribution using Python 3.4.

**Comment by ehlers** [comment]
The same seems to happen in version 2.0b2, see comment from Amar Bapu in https://www.gns3.com/discussions/gns3-2-0-beta-2-released

**Comment by noplay** [comment]
Package for 1.5.3 have been pushed but not tested I don't have access to a desktop with an old linux.

**Comment by ehlers** [comment]
Doesn't work for me in a jessie VM:

`sudo apt-get install gns3-server` successfully installs the new gns3-server package:
```
Get: 8 http://ppa.launchpad.net/gns3/ppa/ubuntu/ trusty/main gns3-server amd64 1.5.3~trusty2 [4.659 kB]
```

But running the gns3server fails:
```
behlers@jessie:~$ gns3server
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/pkg_resources.py", line 2716, in <module>
    working_set.require(__requires__)
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/pkg_resources.py", line 685, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: typing
```

**Comment by noplay** [comment]
Do you have also the issue with the GUI?

**Comment by ehlers** [comment]
I don't have installed a desktop environment, therefore no X server. Starting gns3 fails when it tries to open the display, but at least it starts.

```
behlers@jessie:~$ gns3
GNS3 GUI version 1.5.3
Copyright (c) 2007-2017 GNS3 Technologies Inc.
QXcbConnection: Could not connect to display
Aborted
```

**Comment by noplay** [comment]
It the problem is here:
https://github.com/aio-libs/yarl/blob/ccd79b4b29c81f7c5fe3c79554a753f66ad9d84e/yarl/__init__.pyi

**Comment by ehlers** [comment]
Just installed a desktop environment, GNS3 gui works, but gns3-server still crashes.

**Comment by noplay** [comment]
I tag a v1.5.3.1 on git and pushing it to the ppa and tested it in a container seem ok

**Comment by ehlers** [comment]
In my VM it also works. Minor issue is, that it shows the version 1.5.4dev1, not 1.5.3.1.

**Comment by noplay** [comment]
Oh I will need to release another build :( The version will be 1.5.3 because

**Comment by noplay** [comment]
New build released

**Comment by ehlers** [comment]
No new version available in the ppa, latest is more than 4 hours old.

**Comment by noplay** [comment]
You don't see 1.5.3~trusty3 ?

**Comment by ehlers** [comment]
Sure, but according to http://ppa.launchpad.net/gns3/ppa/ubuntu/pool/main/g/gns3-server/ gns3-server_1.5.3~trusty3_amd64.deb is dated Jan-2017 09:44 (UTC). That's the 1.5.4dev1 version.

**Comment by ehlers** [comment]
While the tag v1.5.3.2 looks good for the server, the tag v1.5.3.2 on the GUI points to 2.0.0dev8. So pushing this tag to the PPA will/should fix the server, but create an unwanted GUI version.

**Comment by ehlers** [comment]
And the first issue because of the 1.5.4dev1 pops up on the forum: https://www.gns3.com/qa/is-there-a-way-to-downgrade-the-

**Comment by noplay** [comment]
Dammed

Le jeu. 19 janv. 2017 19:53, Bernhard Ehlers <notifications@github.com> a
écrit :

**Comment by noplay** [comment]
After test this time the package seem to be be correctly sync since yesterday. And uploaded to the correct repository. Just for unknow reason the willy (ubuntu 1.5.10) package seem to be stuck on 1.5.2 even if previous and next version are availables.
