### ISSUE TITLE
GNS VM version information not displaying

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-server#876]
Perhaps I am mistaken, but I believe the version information is not being displayed in the VM information section sense I last updated the VM

![image](https://cloud.githubusercontent.com/assets/6335629/22224147/a16d9aa6-e18b-11e6-91f4-c81b6ddcf7ed.png)

![image](https://cloud.githubusercontent.com/assets/6335629/22224174/b9cf17dc-e18b-11e6-97a9-53d404f37400.png)

**Comment by noplay** [comment]
The problem is GNS3 is not correctly installed what do you see when you run upgrade again?

**Comment by codeassassin** [comment]
Still a no-go after running upgrade again...

**Comment by codeassassin** [comment]
[gns3.log.txt](https://github.com/GNS3/gns3-server/files/727278/gns3.log.txt)

**Comment by noplay** [comment]
Could you try again the upgrade? It seem a package use by GNS3 as changed his dependencies, I fixed that in the upgrade script ....

**Comment by codeassassin** [comment]
Julien,

GNS3 VM updates successfully, and link re-established with GNS3 UI. Keep up the great work.

![image](https://cloud.githubusercontent.com/assets/6335629/22260893/dfb6390a-e238-11e6-9c55-692c5a387e5e.png)

**Comment by noplay** [comment]
Thanks for the help!

**Comment by codeassassin** [comment]
Greetings @noplay. Not sure if there is another dependency issue, but the symptoms have returned. When I upgrade VM, version number disappears and no longer connects with GUI. Attached are logs that might show some error... Thanks!

**Comment by codeassassin** [comment]
[gns3.log.txt](https://github.com/GNS3/gns3-server/files/754852/gns3.log.txt)

**Comment by noplay** [comment]
Fix pushed

**Comment by noplay** [comment]
Thanks
