### ISSUE TITLE
Crash if IOU is not started and you start a capture

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#90]
https://app.getsentry.com/gns3/gns3-server/group/56772289/

**Comment by grossmj** [comment]
My theory for this one is that the user was using the first version of iouyap (no version number) which does not support packet capture that probably stops when encountering the capture params in its config file. The version after that added packet capture support, a version number (0.95) and the -V parameter to print the version on the command line.

We should check that the iouyap version >= 0.95 and raise a VPCSError if not.

**Comment by noplay** [comment]
I just add a check you can call the capture  API if the VM is not running.
