### ISSUE TITLE
Private-config not restored from config file

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#906]
The private-config is not restored for IOS routers (this works for IOU) after you reload a project. This works if you simply reboot the router. Looks like the problem is present in 1.5.x and 2.0.

You will need these commands to test:

```
configure terminal
crypto key generate rsa label test
copy run start
show crypto key mypubkey rsa
```

Generate a new key which will be stored in the private-config (don't forget to save with copy run start, no shown in this example):
 
![private-key-1](https://cloud.githubusercontent.com/assets/4752614/23114099/e4c47cf0-f777-11e6-9442-d5c9924fa398.png)

Close and re-open the project, start the router and you can see the key has not been restored:

![private-key-2](https://cloud.githubusercontent.com/assets/4752614/23114102/ece5edc4-f777-11e6-84fb-e74454f23fab.png)

The file containing the private-config exists:

![private-key-3](https://cloud.githubusercontent.com/assets/4752614/23114181/7881d866-f778-11e6-826f-d8280d0b6e63.png)

However, the key will be restored if we don't delete the nvram/disks, see https://gns3.com/qa/saving-ssh-keys-in-gns3

**Comment by noplay** [comment]
And you see that nobody use private config :(
