### ISSUE TITLE
Project deletion issue (2.0.0b4)

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#924]
## Environment
- GNS3 VM 2.0.0dev9
- Windows 2012R2 client running 2.0.0b4
- "Remote server only" setup

## 1. A project has been created
It appears in the GNS3 VM's projects directory:
```
gns3@gns3vm:/opt/gns3/projects$ ls -l | grep "Mar  5"
drwxr-xr-x 3 gns3 gns3 4096 Mar  5 16:44 e9e60b11-5007-4b97-853a-a7d0d54ce6fa
gns3@gns3vm:/opt/gns3/projects$
```

## 2. The project gets deleted
Clicking on "File / Delete project" drops an error:
```
Error while closing project e9e60b11-5007-4b97-853a-a7d0d54ce6fa: Can not delete project directory /opt/gns3/projects/e9e60b11-5007-4b97-853a-a7d0d54ce6fa: [Errno 2] No such file or directory: '/opt/gns3/projects/e9e60b11-5007-4b97-853a-a7d0d54ce6fa'
```

However the project on the VM gets deleted:
```
gns3@gns3vm:/opt/gns3/projects$ ls -l | grep "Mar  5"
gns3@gns3vm:/opt/gns3/projects$
```

The project doesn't disappear from the project library:
![gns3_delete_issue](https://cloud.githubusercontent.com/assets/16632791/23589383/403c2c3c-01cc-11e7-94cc-96f6f6a55a78.png)

## 3. Re-opening the project
By clicking on the project in the library and dragging in a node, the project is recreated on the VM with the same project ID (obviously the previously created nodes are missing):
```
gns3@gns3vm:/opt/gns3/projects$ ls -l | grep "Mar  5"
drwxr-xr-x 3 gns3 gns3 4096 Mar  5 16:52 e9e60b11-5007-4b97-853a-a7d0d54ce6fa
gns3@gns3vm:/opt/gns3/projects$
```

**Comment by adosztal** [comment]
Note: I couldn't reproduce on my main box running Ubuntu 16.04 and a local gns3-server too (+ the VM).

**Comment by noplay** [comment]
I can't reproduce it. Do you have something special in your topology?

**Comment by adosztal** [comment]
Not really. Maybe it's something on the Windows server because the projects and images directories (in C:\Users\*username*\AppData\Roaming\GNS3) are also not created; I can only see the configs directory there.

Is it normal for a remote server only setup, or those directories should exist? I saw no related error messages.

**Comment by adosztal** [comment]
Oooh, my bad. There was a typo in my config. Sorry. :)
