### ISSUE TITLE
[Linux/1.5.3.1] Gateway timeout & qemu binaries list empty

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#925]
On Ubuntu 16.10 4.8 
GNS3 server & GUI 1.5.3.1 (1.5.4dev1)
GNS3 ubridge 0.9.11
aiohttp 1.3.3

When right-clicking on a qemu node and choosing "Configure" , I get the following error messages:
![gns3 timeout](https://cloud.githubusercontent.com/assets/13176858/23603462/a2c43db6-0255-11e7-8ed0-8be0f0cfadfc.jpg)
![gns3 qemu issue](https://cloud.githubusercontent.com/assets/13176858/23603466/ae0f530e-0255-11e7-87a1-351163a6d10d.jpg)
The state of the node - running or idle - has no influence in this situation.

However, qemu binaries are present:
```
# qemu-system-x86_64 --version
QEMU emulator version 2.8.0 (v2.8.0-dirty)
Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers
# which qemu-system-x86_64
/usr/bin/qemu-system-x86_64
```

**Comment by noplay** [comment]
What do you have in your $PATH variable?

**Comment by jean-christophe-manciot** [comment]
/usr/bin is in my PATH.
Downgrading aiohttp to 1.2.0 is a workaround.

**Comment by noplay** [comment]
The .deb don't have this problem, we highly recommend it on ubuntu it's the only way for us to freeze the version without breaking the install on distribution with rolling release.
