### ISSUE TITLE
The IOU import create directories in the project directory

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#93]
https://community.gns3.com/thread/7197#21589

I've been testing 1.3.0alpha1 and 1.3.0beta1.dev1 on Mac OS X with an Ubuntu IOU VM.
 
Testing on new projects has been solid, including the ASA. I think the UUID approach is definitely the right way to go.
 
Opening existing projects that have been created in GNS 1.2.3 has been problematic. When I open an existing project in GNS3, the following occurs
1. GNS3 Creates the UUID for the project in root of GNS3/projects because it does not yet exist - in the example screenshot this is 02ad31bd-920b-4dde-a65a-b219e82c62f4
2. Creates all the UUID's of the IOU devices in the root of GNS3/projects
3. Creates all the UUID's of the IOU devices in the project UUID (02ad31bd-920b-4dde-a65a-b219e82c62f4)- it looks to be a different set of UUID's for the same IOU devices
 
The outcome is that
1. There are UUID's created which don't reference any device in the root of GNS/projects
2. More importantly, the UUID's created within the project UUID do not contain the existing configuration (eg nvram) of the pre 1.2.3 IOU devices. As such the IOU device configuration is lost and reset to default.
 
Will there be support for opening topologies in GNS3 1.2.3 and keeping the existing IOU device configurations?

**Comment by grossmj** [comment]
This was due do a different directory structure for projects running on remote servers. Now the server should automatically convert that to the new structure and therefore this problem should have been fixed.
