### ISSUE TITLE
e1000: Reading register at offset: 0x00002410. It is not fully implemented.

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#939]
OS: Ubuntu 16.10 4.8
Target: IOSv-L2 15.2-4055

Booting that node always triggers an infinite number of previous error message in its log.

**Comment by noplay** [comment]
Which qemu binary are you using?

**Comment by jean-christophe-manciot** [comment]
qemu 2.8

**Comment by noplay** [comment]
x86_64 or i386?

**Comment by jean-christophe-manciot** [comment]
x86_64

**Comment by noplay** [comment]
Can you test using virtio-net-pci adapter?

**Comment by ehlers** [comment]
Same here with debian stretch, also qemu 2.8, tested with the same IOSv-L2 version.

It doesn't matter if I'm using x64_64 or i386, both are working, but both generate lots of these log messages.

Using different network adapters doesn't help, tested virtio-net-pci, i82550 and vmxnet3. Then the IOSv-L2 doesn't recognize the network interfaces.

I had a look into the source https://github.com/qemu/qemu/blob/master/hw/net/e1000.c, there is no runtime option to suppress this warning, only recompilation with different debugflags would help.

A crude workaround is to make a symbolic link from qemu.log to /dev/null in the all the directories, where this VM log is stored.

Hopefully a newer IOSv will fix this, but I have no access to other/newer versions.

**Comment by noplay** [comment]
I close the issue because this is not something we can solve on our side.  Hopefully for the moment official packages in stable most use linux version don't have this problem.

Newer IOSv could fix that but not soon, Cisco use ubuntu LTS 16.04 in the new VIRL version they don't have the problem.

I think you should try to report the issue to Qemu. I see two solution:
* Improve the faulty code to not log the same registry multiple time
* Disable the log by default 

The culprit commit is:
https://github.com/qemu/qemu/commit/bc0f0674f037a01f2ce0870ad6270a356a7a8347

Sadly the fix will arrive too late for Ubuntu 17.04 and Debian 9.

Also you can test as an adapter: rtl8139 or pcnet with some luck the IOSv kernel will have this.

**Comment by ehlers** [comment]
Tested rtl8139 and pcnet adapters, both don't work. We really need to use e1000.

As a quick-and-dirty workaround I patched qemu-i386 and qemu-x86-64. Searched for `e1000: Reading` and changed the first character to a NUL character. That way qemu prints an empty string.

But Julien is right, this is a qemu issue, not a GNS3 issue.

**Comment by noplay** [comment]
I move the bug to 2.1 to track it.

If you can go to:
https://bugs.launchpad.net/qemu/+bug/1673722

And support the issue.

**Comment by noplay** [comment]
They will fix the problem at qemu level
https://bugs.launchpad.net/qemu/+bug/1673722

**Comment by ehlers** [comment]
Just as an information:
This happens also with qemu 2.5, so most GNS3 installations are affected
```
$ qemu-system-x86_64 --version
QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.10), Copyright (c) 2003-2008 Fabrice Billard
```

**Comment by ehlers** [comment]
Even though qemu reports a lot a debug message, IOSv is still usable. It "just" creates lots of log messages.
I patched that issue away, I changed the first byte of the "e1000: Reading ..." message to hex 0, so no actual output is done. Here my patch script:
```
#!/bin/bash

if [ "$USER" != "root" ]; then
	echo "Must be run as root, start with sudo" >&2
	exit 1
fi

# patch qemu-system-i386 and -x86_64
qemu=`compgen -c | grep '^qemu-system' | grep -v '\.orig$' | sort`
which $qemu | while read fname; do
	offsets=`grep -a -b -o "e1000: Reading" "$fname" | \
	        sed -n 's/^\([0-9][0-9]*\):.*/\1/p'`
	if [ -n "$offsets" ]; then
		echo Patching "$fname" ...
		cp -p "$fname" "${fname}.orig"
		for offset in $offsets; do
			echo "0: 00" | xxd -s $offset -r - "$fname"
		done
	fi
done
```

**Comment by noplay** [comment]
I will try to make a clean patch, in order to progress

**Comment by noplay** [comment]
Could you try this patch?
```patch
From ab82d349243780908ebe3401196ab290ef9927ca Mon Sep 17 00:00:00 2001
From: Julien Duponchelle <julien@gns3.net>
Date: Thu, 4 May 2017 12:41:10 +0200
Subject: [PATCH] Disable the not fully implemented warning for e1000

Otherwise for image like CISCO IOSv you got a lot
of warning on the console preventing you to use
the VM because it's slow down the machine.

This fix:
https://bugs.launchpad.net/qemu/+bug/1673722

Signed-off-by: Julien Duponchelle <julien@gns3.net>
---
 hw/net/e1000.c | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/hw/net/e1000.c b/hw/net/e1000.c
index f2e5072d27..04c390103b 100644
--- a/hw/net/e1000.c
+++ b/hw/net/e1000.c
@@ -35,6 +35,7 @@
 #include "sysemu/dma.h"
 #include "qemu/iov.h"
 #include "qemu/range.h"
+#include "qemu/log.h"
 
 #include "e1000x_common.h"
 
@@ -1264,7 +1265,7 @@ e1000_mmio_write(void *opaque, hwaddr addr, uint64_t val,
         if (!(mac_reg_access[index] & MAC_ACCESS_FLAG_NEEDED)
             || (s->compat_flags & (mac_reg_access[index] >> 2))) {
             if (mac_reg_access[index] & MAC_ACCESS_PARTIAL) {
-                DBGOUT(GENERAL, "Writing to register at offset: 0x%08x. "
+                qemu_log_mask(LOG_UNIMP, "Writing to register at offset: 0x%08x. "
                        "It is not fully implemented.\n", index<<2);
             }
             macreg_writeops[index](s, index, val);
-- 
2.11.0 (Apple Git-81)

```

**Comment by ehlers** [comment]
The patch looks good, but setting up a compile environment to create a new deb is quite a lot of work for me. So I can't do this in the near future, sorry.

**Comment by ehlers** [comment]
Additional note: You seem to modify only the "Writing to register..." debug message, but more annoying is the "Reading register ..." message.

**Comment by noplay** [comment]
Right:
```patch
From b29ec3a27dc568888688a7298531767a06e38049 Mon Sep 17 00:00:00 2001
From: Julien Duponchelle <julien@gns3.net>
Date: Thu, 4 May 2017 12:41:10 +0200
Subject: [PATCH] Disable the not fully implemented warning for e1000

Otherwise for image like CISCO IOSv you got a lot
of warning on the console preventing you to use
the VM because it's slow down the machine.

This fix:
https://bugs.launchpad.net/qemu/+bug/1673722

Signed-off-by: Julien Duponchelle <julien@gns3.net>
---
 hw/net/e1000.c | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/hw/net/e1000.c b/hw/net/e1000.c
index f2e5072d27..5580bde399 100644
--- a/hw/net/e1000.c
+++ b/hw/net/e1000.c
@@ -35,6 +35,7 @@
 #include "sysemu/dma.h"
 #include "qemu/iov.h"
 #include "qemu/range.h"
+#include "qemu/log.h"
 
 #include "e1000x_common.h"
 
@@ -1264,7 +1265,7 @@ e1000_mmio_write(void *opaque, hwaddr addr, uint64_t val,
         if (!(mac_reg_access[index] & MAC_ACCESS_FLAG_NEEDED)
             || (s->compat_flags & (mac_reg_access[index] >> 2))) {
             if (mac_reg_access[index] & MAC_ACCESS_PARTIAL) {
-                DBGOUT(GENERAL, "Writing to register at offset: 0x%08x. "
+                qemu_log_mask(LOG_UNIMP, "Writing to register at offset: 0x%08x. "
                        "It is not fully implemented.\n", index<<2);
             }
             macreg_writeops[index](s, index, val);
@@ -1291,7 +1292,7 @@ e1000_mmio_read(void *opaque, hwaddr addr, unsigned size)
         if (!(mac_reg_access[index] & MAC_ACCESS_FLAG_NEEDED)
             || (s->compat_flags & (mac_reg_access[index] >> 2))) {
             if (mac_reg_access[index] & MAC_ACCESS_PARTIAL) {
-                DBGOUT(GENERAL, "Reading register at offset: 0x%08x. "
+                qemu_log_mask(LOG_UNIMP, "Reading register at offset: 0x%08x. "
                        "It is not fully implemented.\n", index<<2);
             }
             return macreg_readops[index](s, index);
-- 
2.11.0 (Apple Git-81)
```

**Comment by ehlers** [comment]
Just created new qemu debs with your patches (boy, that takes time). Looks good, no more debug messages about e1000 not fully implemented register access. With qemu option `-d unimp` they can be enabled again.

Slightly changed your patch so the messages include the prefix "e1000: " (as before):
```
--- qemu-2.5+dfsg.orig/hw/net/e1000.c
+++ qemu-2.5+dfsg/hw/net/e1000.c
@@ -1482,7 +1482,8 @@ e1000_mmio_write(void *opaque, hwaddr ad
         if (!(mac_reg_access[index] & MAC_ACCESS_FLAG_NEEDED)
             || (s->compat_flags & (mac_reg_access[index] >> 2))) {
             if (mac_reg_access[index] & MAC_ACCESS_PARTIAL) {
-                DBGOUT(GENERAL, "Writing to register at offset: 0x%08x. "
+                qemu_log_mask(LOG_UNIMP, "e1000: "
+                       "Writing to register at offset: 0x%08x. "
                        "It is not fully implemented.\n", index<<2);
             }
             macreg_writeops[index](s, index, val);
@@ -1509,7 +1510,8 @@ e1000_mmio_read(void *opaque, hwaddr add
         if (!(mac_reg_access[index] & MAC_ACCESS_FLAG_NEEDED)
             || (s->compat_flags & (mac_reg_access[index] >> 2))) {
             if (mac_reg_access[index] & MAC_ACCESS_PARTIAL) {
-                DBGOUT(GENERAL, "Reading register at offset: 0x%08x. "
+                qemu_log_mask(LOG_UNIMP, "e1000: "
+                       "Reading register at offset: 0x%08x. "
                        "It is not fully implemented.\n", index<<2);
             }
             return macreg_readops[index](s, index);
```

**Comment by ehlers** [comment]
And the include file hw/hw.h already includes qemu/log.h, so it's not necessary to include it again.

**Comment by noplay** [comment]
Compiler complaint if you don't add the log.h

**Comment by noplay** [comment]
Patch send to the mailing list: http://lists.nongnu.org/archive/html/qemu-devel/2017-05/msg01294.html

**Comment by noplay** [comment]
Patch still waiting to be merged

**Comment by ryangurazov** [comment]
Thank you for tracking it is all down @noplay 
I see milestone for this issue is set to 2.2.
So after is all addressed on QEMU side there is no plan to have GNS3 2.0.x VM?

**Comment by noplay** [comment]
The GNS3 VM is not impacted because we are using an older qemu.

**Comment by ehlers** [comment]
I've got different findings, see https://github.com/GNS3/gns3-server/issues/939#issuecomment-299129895

**Comment by noplay** [comment]
Ok I will see to release a patched a qemu 2.5

**Comment by noplay** [comment]
Not easy to rebuild the package because debian as moved to qemu 2.8, need to update build scripts.

**Comment by noplay** [comment]
Updated version of Qemu 2.5 as been pushed to https://launchpad.net/~gns3/+archive/ubuntu/qemu

**Comment by noplay** [comment]
GNS3 VM wil have the correct version

**Comment by grossmj** [comment]
Should we close this issue?

**Comment by ehlers** [comment]
As I'm neither the issuer nor assigned, so I can give only my opinion:

What can be done more by GNS3? The QEMU guys are informed and a special QEMU version fixes that in the GNS3 VM. Sure, all those people using QEMU in their own linux environment are effected, but there's nothing GNS3 can do about that. QEMU is not under control of GNS3, so an update can't be forced. Maybe a warning can be added to the Linux installation guide, but that's all.

So I'm for closing this issue (and #1164)

**Comment by jean-christophe-manciot** [comment]
> Hopefully a newer IOSv will fix this, but I have no access to other/newer versions.

I've tested IOSv-L2 15.2(20170321:233949) and the issue is still there with qemu **2.8.1**(Debian 1:2.8+dfsg-7).

With qemu **2.10.1**(Debian 1:2.10.0+dfsg-2), the issue is masked and the execution log is now empty.
However, I cannot use this last release because it makes NX-OSv 9k crash.
