### ISSUE TITLE
When IOU gets a SIGSEGV, the explanation to use a different image is not shown

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#948]
Ref: https://github.com/GNS3/gns3-server/issues/739: When IOU process stopped explain that user need probably to use a different image
Both versions 1.5 and 2.0 are affected

When an IOU process gets a SIGSEGV it exits with a return code of -11, but the code in iou_vm.py checks for (plus) 11. Therefore the special message for SIGSEGV is never shown.

**Comment by noplay** [comment]
Thanks good catch!
