### ISSUE TITLE
1.3.0beta2: No qemu data connectivity when server IP <> 127.0.0.1

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#96]
OS: Debian Linux 8 (Jessie), GNS3 Version 1.3.0beta2.

When I change the server IP from 127.0.0.1 to my ethernet IP 192.168.1.11 the data transfer between two qemu devices doesn't work. It tried it by connecting two qemu VMs with a link. This connectivity works with dynamips, IOU and virtualbox devices, both with server IP 127.0.0.1 and 192.168.1.11. With qemu it only works with server IP 127.0.0.1.

The problem is the local IP of the UDP tunnel, it's always 127.0.0.1 (wrong!!!). The remote IP is the correct 192.168.1.11.

Here the command lines of two qemu processes and the netstat output:
behlers@dell:~/.config/GNS3$ ps x | grep qemu
 7212 ?        Sl     0:02 /usr/bin/qemu-system-x86_64 -name ost-drone-1 -m 128 -hda /home/behlers/GNS3/projects/b49a9eac-6ca8-4820-823d-ae73aacca1e6/project-files/qemu/19ee17be-0d56-4eb3-b71a-c69c996c377a/hda_disk.qcow2 -serial telnet:127.0.0.1:2003,server,nowait -monitor tcp:127.0.0.1:2004,server,nowait -nographic -enable-kvm -net nic,vlan=999,model=e1000 -net user,vlan=999,hostfwd=tcp::50001-:7878 -device e1000,mac=00:00:ab:2e:84:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10000,localaddr=127.0.0.1:10001 -device e1000,mac=00:00:ab:93:c1:01,netdev=gns3-1 -netdev user,id=gns3-1 -device e1000,mac=00:00:ab:2e:e3:02,netdev=gns3-2 -netdev user,id=gns3-2 -device e1000,mac=00:00:ab:b3:f6:03,netdev=gns3-3 -netdev user,id=gns3-3
 7213 ?        Rl     0:05 /usr/bin/qemu-system-x86_64 -name JunOS-1 -m 512 -hda /home/behlers/GNS3/projects/b49a9eac-6ca8-4820-823d-ae73aacca1e6/project-files/qemu/8e0b6ac4-deb5-49fd-89a4-845eebf9d1c0/hda_disk.qcow2 -serial telnet:127.0.0.1:2001,server,nowait -monitor tcp:127.0.0.1:2002,server,nowait -nographic -enable-kvm -device e1000,mac=00:00:ab:c2:b0:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device e1000,mac=00:00:ab:63:c8:01,netdev=gns3-1 -netdev user,id=gns3-1 -device e1000,mac=00:00:ab:bd:e8:02,netdev=gns3-2 -netdev user,id=gns3-2 -device e1000,mac=00:00:ab:ca:b2:03,netdev=gns3-3 -netdev user,id=gns3-3
 7221 pts/0    S+     0:00 grep qemu
behlers@dell:~/.config/GNS3$ netstat -una
Aktive Internetverbindungen (Server und stehende Verbindungen)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
udp        0      0 0.0.0.0:5353            0.0.0.0:*                          
udp        0      0 127.0.0.1:10000         0.0.0.0:*                          
udp        0      0 127.0.0.1:10001         0.0.0.0:*                          
udp        0      0 0.0.0.0:35454           0.0.0.0:*                          
udp        0      0 0.0.0.0:32721           0.0.0.0:*                          
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::26007                :::*                               
udp6       0      0 :::34602                :::*                               
behlers@dell:~/.config/GNS3$

**Comment by ehlers** [comment]
Here the netstat table without formatting.
```
behlers@dell:~/.config/GNS3$ netstat -una
Aktive Internetverbindungen (Server und stehende Verbindungen)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
udp        0      0 0.0.0.0:5353            0.0.0.0:*                          
udp        0      0 127.0.0.1:10000         0.0.0.0:*                          
udp        0      0 127.0.0.1:10001         0.0.0.0:*                          
udp        0      0 0.0.0.0:35454           0.0.0.0:*                          
udp        0      0 0.0.0.0:32721           0.0.0.0:*                          
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::26007                :::*                               
udp6       0      0 :::34602                :::*                               
behlers@dell:~/.config/GNS3$ 
```

**Comment by ehlers** [comment]
Sorry, that was the wrong ps output, that first output was for server 127.0.0.1, this is the output for server 192.168.1.11. The relevant part is:
-netdev socket,id=gns3-0,udp=192.168.1.11:10001,localaddr=127.0.0.1:10000

behlers@dell:~/.config/GNS3$ ps x | grep qemu
 7138 ?        Sl     0:05 /usr/bin/qemu-system-x86_64 -name ost-drone-1 -m 128 -hda /home/behlers/GNS3/projects/blah/project-files/qemu/cee10800-e5cf-471b-955a-87efe00887c5/hda_disk.qcow2 -serial telnet:192.168.1.11:2003,server,nowait -monitor tcp:127.0.0.1:2004,server,nowait -nographic -enable-kvm -net nic,vlan=999,model=e1000 -net user,vlan=999,hostfwd=tcp::50001-:7878 -device e1000,mac=00:00:ab:47:74:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=192.168.1.11:10001,localaddr=127.0.0.1:10000 -device e1000,mac=00:00:ab:de:27:01,netdev=gns3-1 -netdev user,id=gns3-1 -device e1000,mac=00:00:ab:71:35:02,netdev=gns3-2 -netdev user,id=gns3-2 -device e1000,mac=00:00:ab:24:ab:03,netdev=gns3-3 -netdev user,id=gns3-3
 7139 ?        Sl     0:27 /usr/bin/qemu-system-x86_64 -name JunOS-1 -m 512 -hda /home/behlers/GNS3/projects/blah/project-files/qemu/4c56b484-3ad6-4680-97f1-f9632655c195/hda_disk.qcow2 -serial telnet:192.168.1.11:2001,server,nowait -monitor tcp:127.0.0.1:2002,server,nowait -nographic -enable-kvm -device e1000,mac=00:00:ab:26:3d:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=192.168.1.11:10000,localaddr=127.0.0.1:10001 -device e1000,mac=00:00:ab:d0:80:01,netdev=gns3-1 -netdev user,id=gns3-1 -device e1000,mac=00:00:ab:21:10:02,netdev=gns3-2 -netdev user,id=gns3-2 -device e1000,mac=00:00:ab:e7:56:03,netdev=gns3-3 -netdev user,id=gns3-3
 7150 pts/0    S+     0:00 grep qemu
behlers@dell:~/.config/GNS3$

**Comment by grossmj** [comment]
Should be all good now :) Thanks.
