### ISSUE TITLE
Docker: Error starting more than 20 containers

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#963]
See https://www.gns3.com/qa/docker-error-starting-more-than-

Tested with official 1.5.3 OS X dmg (and official GNS3 VM). I could start "only" 19, not 20 without issues. On more devices it blocks as described in the GNS3 forum. Even when starting 19 docker VMs, afterwards I couldn't stop them, again the process bar halts and after some time an error message "Server error from http://192.168.1.98:3080: alpine2-1: Operation canceled" is shown. it seems, that the 20th operation blocks.

I went back to commit https://github.com/GNS3/gns3-server/commit/bd4de862c889c655fc02aebe56a2cfba4b952bc7, just before the upgrade to aiohttp v1.2. I've installed aiohttp v0.22.5. Furthermore I have to fake the version to the official 1.5.3, otherwise the client will show a version mismatch. That works fine. So aiohttp v1.2 (and later) are somehow creating this issue.

**Comment by noplay** [comment]
It seem now the UnixConnector of aiohttp as by default a limit of 20 connection at the same time.  And depending in which order operation happen it could block or not.

I'm able to reproduce it sometimes depending of the machine load. If my machine as a low load (uncommon :P ) I reproduce it everytime.

I pushed a fix on the 2.0
