### ISSUE TITLE
GNS3 2.0 RC3 Docker templates using VNC not working

### ISSUE THREAD

**Issue by dkhenderson2** [GNS3/gns3-server#965]
GNS3 2.0 RC3 Docker templates using VNC not working

After creating the template the error below is presented after dragging the node to the work space
 
receives error:

GNS3 2.0 RC3 Docker templates using VNC not working

Error while setting up node: Please install Xvfb and x11vnc before using the VNC support

tested with Linux, windows, Ubuntu and MAC OS all have the same result.

**Comment by noplay** [comment]
Hi,

On which server the docker is running it's a GNS3 VM? An ubuntu with GNS3 installed from package? If it's not the case you need to install the package xvfb and x11vnc for your distribution.

**Comment by dkhenderson2** [comment]
Docker is running on the GNS3 VM.

**Comment by noplay** [comment]
I'm not able to reproduce it. Which GNS3 VM edition are you using? It's a fresh install or you upgrade it?

**Comment by dkhenderson2** [comment]
its a fresh installation just downloaded from https://github.com/GNS3/gns3-gui/releases.  Docker templates  needing VNC like chromium or webterm for example throw the error, once you try to add one to a project. 

seems to follow the GNS3 VM.  I have tried it from a windows installation of the GNS3 gui and ubuntu with the same result.

![capture](https://cloud.githubusercontent.com/assets/21106062/24618571/782f71da-1865-11e7-9660-d8fc36393275.PNG)

**Comment by dkhenderson2** [comment]
Its the VM workstation version

**Comment by noplay** [comment]
Run an upgrade in the VM should fix the problem for you. I will make sure
the default package are correctly installed.

**Comment by dkhenderson2** [comment]
Thanks Julien, this is confirmed. after running the upgrade issue is now resolved,

**Comment by noplay** [comment]
Great, thanks for the update!

**Comment by noplay** [comment]
Confirmed the next VM will be OK.

Thanks a lot for the help

**Comment by kishorekannanbsc** [comment]
Hi All,

I am getting the same error again

Error while creating node from template: Please install TigerVNC server (recommended) or Xvfb + x11vnc before using VNC support

Setup is simple 
![Setup](https://user-images.githubusercontent.com/69117335/93303038-7f7ca480-f818-11ea-9868-14ac97be6ee8.png)
need to use Webterm inside GNS3 to access PA firewall, GNS Version : 2.2.14

GNS3 Server is a remote server running inside Google Cloud. Using Ubuntu 18.04
![GNS3 Error](https://user-images.githubusercontent.com/69117335/93302955-5e1bb880-f818-11ea-8c0a-488177fad660.png)

**Comment by kishorekannanbsc** [comment]
Installed VNC using the below command in GNS3 Server
sudo apt install tigervnc-standalone-server tigervnc-common

But i am getting the error 

Could not start VNC program with command 'vncviewer 172.16.253.1:5901': [Errno 2] No such file or directory: 'vncviewer'
![gns3 error](https://user-images.githubusercontent.com/69117335/93303813-a9829680-f819-11ea-9cc1-481b25c346ec.png)
