### ISSUE TITLE
vCPUs option from appliance template not used

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#968]
Looks like the vcpus from template files is not used.

For instance the NX-OSv 9000 template has 2 vcpus:

```
{
    "name": "Cisco NX-OSv 9000",
    "category": "multilayer_switch",
...
    "qemu": {
        "vcpus": 2,
...
```

But it shows only one vCPU in the VM properties after importing the template:

![nx-osv_9000_2](https://cloud.githubusercontent.com/assets/4752614/24745951/b0c10142-1a74-11e7-9b81-9147566a9c51.png)

Same thing in the Qemu command line:

```
/usr/bin/qemu-system-x86_64 -name CiscoNX-OSv9000-1 -m 8096M -smp cpus=1 
```

**Comment by noplay** [comment]
The name of the var in qemu is cpus should we use the same name in the appliance? Could be logic

**Comment by grossmj** [comment]
Yes agreed we can name it 'cpus', we just need to edit all templates that include 'vcpus'.

**Comment by noplay** [comment]
We have only the nxos

Le ven. 7 avr. 2017 à 01:06, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
Easier then :)

**Comment by noplay** [comment]
Appliance fixed
