### ISSUE TITLE
ESXi OVF: Failed to deploy OVF Package

### ISSUE THREAD

**Issue by danieldemers** [GNS3/gns3-server#980]
![ovf failed gns3 154](https://cloud.githubusercontent.com/assets/17289463/25100947/d9950972-2377-11e7-9395-9d3bcb11e1ed.png)

When I imported to OVA into vCenter 6.5 it failed with the attached error.

GNS3 ESXi OVA for 1.5.4 on ESXi 6.5

**Comment by noplay** [comment]
Do you have more informations? 

On ESXi 6.5 you need to upgrade to the last version of the web interface because the version released with 6.5 has bug:
http://docs.gns3.com/1hEoK0rmtdBRnMaUaVoMHUbYwtDAltXYShiMJUp1GMxk/index.html#h.vxyo1vmd358z

Perhaps it's the same problem with vcenter
