### ISSUE TITLE
Error transferring old gns3 local projects to remote server - server replied: Forbidden

### ISSUE THREAD

**Issue by dkhenderson2** [GNS3/gns3-server#984]
I am trying to transfer a old topology file in to GNS32.0RC3. when trying to open the file I am getting the following error:

Error transferring http://172.17.50.134:3080/v2/projects/load - server replied: Forbidden.

I am running on windows 10. using VM workstation to run the GNS3VM. I am running GNS3 all on the remote server, the local GNS3 is disabled.

**Comment by dkhenderson2** [comment]
remote server is NOT in auth mode.

**Comment by noplay** [comment]
Perhaps it's a permission issue. Can you check the permissions on the files of the project on the remote server?

**Comment by dkhenderson2** [comment]
not transferring from a remote server, I am trying to open from a local directory.  The file opens when I turn on local gns3 server, but fails to transfer to the gns3vm when I disable the local server.

**Comment by noplay** [comment]
How do you try to transfer them?

**Comment by dkhenderson2** [comment]
I am going direct to the .gns3 file and opening it.

**Comment by dkhenderson2** [comment]
Having a similar issue importing Portable projects.

As I said I can open the project if I have the local server enabled. This happens with any old .gns3 file. So I tried to export it as a portable project and try to import it. but when I do what I get this error.

=> QObject: Cannot create children for a parent that is in a different thread.
(Parent is HTTPClient(0x1b107082830), parent's thread is QThread(0x1b1049929e0), current thread is QThread(0x1b1070b9180)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNetworkAccessManager(0x1b107081fc0), parent's thread is QThread(0x1b1049929e0), current thread is QThread(0x1b1070b9180)
ImportProjectWorker thread stopping with an error: Could not import the project: [Errno 13] Permission denied: 'None'
Could not import the project: [Errno 13] Permission denied: 'None'

[T-Shoot Base.zip](https://github.com/GNS3/gns3-server/files/968405/T-Shoot.Base.zip)


I attached the file I am trying to open. The only image needed to open it is i86bi-linux-l2-ipbasek9-15.1g.bin

**Comment by diablozzq** [comment]
I'm also having this issue running 2.0 RC4 with the remote GNS3 server on ESXI.  I downloaded a GNS3 vault lab and when I attempt to open the .gns3 file directly, it pops up with the server replied: forbidden error.

**Comment by noplay** [comment]
Ok this a bug you can't open a .gns3 with a remote server. You need a portable project.

**Comment by dkhenderson2** [comment]
Even when I save the gns3 file as a portable project it will not allow me to import the project. see error;

=> QObject: Cannot create children for a parent that is in a different thread.
(Parent is HTTPClient(0x1b107082830), parent's thread is QThread(0x1b1049929e0), current thread is QThread(0x1b1070b9180)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNetworkAccessManager(0x1b107081fc0), parent's thread is QThread(0x1b1049929e0), current thread is QThread(0x1b1070b9180)
ImportProjectWorker thread stopping with an error: Could not import the project: [Errno 13] Permission denied: 'None'
Could not import the project: [Errno 13] Permission denied: 'None'
