### ISSUE TITLE
Error Dynamips

### ISSUE THREAD

**Issue by Saki0** [GNS3/gns3-server#988]
Hello,
After installing Gns3 server RC4 on an Ubuntu serv, fulfill requirements and build/install it.
I tested it with client in same version.
Sadly I have an error.
Indeed I add a Cisco router from image, it's downloaded to server, end configure it.

But when I drag and drop the router, a dynamips error occurs.
What the server print in attach files.
![dynaimps](https://cloud.githubusercontent.com/assets/9914509/25509740/77f3c2fc-2bbb-11e7-9089-b5eab3cfc044.PNG)

Do I have to install dynamips separetly ?

**Comment by noplay** [comment]
Yes you need to install it.

We highly recommend using package for the installation:
https://gns3.com/discussions/gns3-2-0-rc4-released
