### ISSUE TITLE
VMnet not working in cloud node on Windows

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#989]
If you try asking for DHCP via a cloud interface VMnet8 (Nat) you will get your own packet back.

**Comment by noplay** [comment]
I have no idea why it's not working :(

**Comment by grossmj** [comment]
Looped packets due to winpcap?

**Comment by noplay** [comment]
Yes

Le ven. 12 mai 2017 à 08:59, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
Worth a try with npcap maybe.

**Comment by grossmj** [comment]
Duplicate of https://github.com/GNS3/gns3-gui/issues/2228
