### ISSUE TITLE
Vboxnet not working in the cloud node

### ISSUE THREAD

**Issue by julien-duponchelle** [GNS3/gns3-server#990]
If you try to use a vboxnet in a cloud node. The cloud is correcly initalized but nothing work

**Comment by noplay** [comment]
On windows it seem the packet like for VMnet are sent back like  #771

**Comment by noplay** [comment]
I have no idea why it's not working :(  Perhaps we will need to add code
specific to vboxnet to ubridge

**Comment by grossmj** [comment]
Do you see any packets?

**Comment by noplay** [comment]
Andras mention that:
https://www.virtualbox.org/ticket/3768

**Comment by grossmj** [comment]
Great latest VirtualBox (5.1.14 r112924) and I cannot even add vboxnet interfaces :(

![vbox_error](https://user-images.githubusercontent.com/4752614/27628531-e60f24fc-5c21-11e7-9ebd-a1f657fa9e69.png)

**Comment by noplay** [comment]
Perhaps you need to reboot to reload the kernel driver

**Comment by grossmj** [comment]
No packets can be seen. I don't know what is wrong.
