### ISSUE TITLE
Timeout when loading large image library

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-server#996]
Hi again,

This is for 2.0 using a remote server.  The first time an image (qemu etc)  is configured on 2.0 and the image directory has a lot of images (for example ours has about 40gb of images) the client will timeout waiting for http://10.x.x.x:3080/v2/computes and the server will stay at 100% CPU for a while.  In this case, the client does not give the server enough time to process the images and aborts the process.  The only way to complete the process was to run  http://10.x.x.x:3080/v2/computes from a browser and let the server finish up.

Does this make sense?  Let me know if I need to clarify.

**Comment by noplay** [comment]
I think it's because we compute the md5sum of the images. 

The best option is to start the computing at server startup to make it independent of client connection.
